### ISSUE TITLE
How to run the server for wss ?

### ISSUE THREAD

**Issue by billibit** [websockets/ws#1001]
How to run the web socket server in secure mode? basically start the server as wss:<hot name>:<port>.

**Comment by lpinca** [comment]
In the same way you [create an HTTPS server](https://nodejs.org/dist/latest-v7.x/docs/api/https.html#https_https_createserver_options_requestlistener) with Node.js. Once created, you can pass it to the `WebSocket.Server` constructor.

```js
const WebSocket = require('ws');
const https = require('https');

const server = https.createServer(...);
const wss = new WebSocket.Server({ server });
```

**Comment by alallier** [comment]
What if you don't want to attach to the node server? If you create with just a port like:

```js
const WebSocket = require('ws');
const https = require('https');

const server = https.createServer(...);
const wss = new WebSocket.Server({ port: 45676 });
```

Is there anyway to run secure WebSockets this way?

**Comment by lpinca** [comment]
No, it will create and use a plain HTTP server in that way.

**Comment by alallier** [comment]
Okay thanks. Any examples you can point me too?

**Comment by lpinca** [comment]
@alallier 

```js
const wss = new WebSocket.Server({ noServer: true });
const server = http.createServer();

server.on('upgrade', (request, socket, head) => {
  wss.handleUpgrade(request, socket, head, (ws) => {
    wss.emit('connection', ws, request);
  });
});
```
