### ISSUE TITLE
wss.clients.length always returns undefined even if the clientTracking option is set to true

### ISSUE THREAD

**Issue by joeshae** [websockets/ws#1002]
Hi, from ws@2.0.0 on, wss.clients.length always returns undefined even if the clientTracking option is set to true.

**Comment by lpinca** [comment]
I wonder if people read the [release notes](https://github.com/websockets/ws/releases/tag/2.0.0).
`clients` is no longer an array but a set, so you should use [`Set.prototype.size`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set/size).

**Comment by cyclux** [comment]
No, not everyone tracks release notes. So this question was perfectly legit and helped me as well.
