### ISSUE TITLE
Necessary to have WS implemented on the server in nodejs?

### ISSUE THREAD

**Issue by arshmakker** [websockets/ws#1005]
Hi,

I was trying to use ws in meteor. The use case is to have the meteor server act as a WS client for an external service which may or may not be hosted on nodejs. I am receiving an error that there is no 'on' function in the ws client. Is this because this package needs WS to be hosted on nodejs only?

REgards
ARsh

**Comment by lpinca** [comment]
Yes, this library makes use of some Node.js core modules so it will probably not work outside Node.js unless the environment is Node.js compatible.
