### ISSUE TITLE
on('close') sets underlying socket to null?

### ISSUE THREAD

**Issue by christofferTP** [websockets/ws#1006]
If i have a wss connection and it terminates, for instance in the below code:

```
connection.on('close', function(reasonCode, description) {
      console.log(reasonCode, description);
      const address = connection._socket.remoteAddress; // Doesnt work - socket is null
      console.log('[' +new Date() + ']'
        +" EXTERNAL: Disconnected: "
        + address );
      registry.remove_device(address);

```
I get the following on close:
```
/home/chritof/Documents/vbox/wsh.js:232
      const address = connection._socket.remoteAddress;
                                        ^

TypeError: Cannot read property 'remoteAddress' of null
```
This seems like a bad design decision, why cant I access the socket and its data ? I need to remove this information from my map..

Regards

**Comment by lpinca** [comment]
Yes, a cleanup process is run before emitting the `close` event and it sets the underlying socket to null. You shouldn't rely on `_socket` as it is a private property.

**Comment by christofferTP** [comment]
How do you suggest I get a hold of the connection information in the on close method?

**Comment by lpinca** [comment]
This is on the server right? If so use the public [`upgradeReq`](https://github.com/websockets/ws/blob/master/doc/ws.md#websocketupgradereq) property.

**Comment by christofferTP** [comment]
Yes, on the server. Will look at retrieving IP from the `upgradeReq`

**Comment by lpinca** [comment]
```js
ws.upgradeReq.connection.remoteAddress
```

should work. If your server is behind a proxy use the `X-Forwarded-For` header or whatever you use.

**Comment by christofferTP** [comment]
Nice, that worked. Thanks.
