### ISSUE TITLE
Close event doesn't fire if the client is powered off

### ISSUE THREAD

**Issue by angel1st** [websockets/ws#1007]
Hey guys,
The case I have could seem to you odd, but I would like to know if it could be supported by WS Server side. I have two type of clients:

1. Hybrid Mobile app
1. ESP8266 based devices.

Both are communicating just fine via NodeJS and WS on top of it.

The issue I have - if any of the devices - either mobile phone or ESP module is powered off, it doesn't able to send `close` event to the server. First I thought it is because of the client library on ESP module side, but it seems even on mobile device, where I am using angular-websocket (https://github.com/AngularClass/angular-websocket) it is easy to reproduce the case - while I am running the app (WebSocket is connected), if I simply turn off the device, I don't receive `close` event on the server side. I received it however, when I close the app. 
So I guess the server side, should periodically check if the clients are still live and in case some of them are not - to send either `close` even or other event. At least it would be nice to know how to check this by myself - any hints / thoughts are highly appreciated.
Thanks!

**Comment by lpinca** [comment]
> So I guess the server side, should periodically check if the clients are still live and in case some of them are not

Yes, you need an heartbeat system to check if the client is still connected. You can build it using [ping/pong](https://github.com/websockets/ws/issues/977).

**Comment by angel1st** [comment]
@lpinca - one more inquiry on this - looking at `ping` method and the topic referred above, I believe it is expected, once the server sends `ping`, the client should respond with `pong` and hence the server will receive **pong** event. So far so good. In case however such heartbeating system should be implemented, it should periodically go through all `server.clients` set and execute `ping` for each on those clients. 
Then once `pong` event is received I have to find a way to distinct the clients which are *not* responding and close those. Basically - I am more interested to identify **dead** sockets than the ones still alive....
Any hints how this could be implemented?
Best Regards

**Comment by lpinca** [comment]
@angel1st see this comment https://github.com/websockets/ws/pull/635#issuecomment-281026825
