### ISSUE TITLE
Broadcast interface?

### ISSUE THREAD

**Issue by Edisoni** [websockets/ws#1009]
https://github.com/websockets/ws/issues/617

And what`s frame? Array?
const frame = frameMessage(1, 'message', true, true, true, false);

**Comment by lpinca** [comment]
That was only an idea on how to improve broadcast performance. The idea was to make [`frameAndSend()`] a standalone function to frame a message and export it but nothing has been done yet.

**Comment by Edisoni** [comment]
What`s return frameMessage? outputBuffer or data ?

**Comment by lpinca** [comment]
There is no `frameMessage`, and currently `frameAndSend()` does not return anything, it calls `sendFramedData()`.

**Comment by Edisoni** [comment]
But how to get frame for send all clients? i don`t understand and sorry for my bad english.

**Comment by lpinca** [comment]
There is no way now unless you build the frame yourself. You can read [here](https://tools.ietf.org/html/rfc6455#section-5) how data framing works or extract the logic from `frameAndSend()`.

Hope this makes sense.

**Comment by lpinca** [comment]
Closing as we already have another open issue for this.
