### ISSUE TITLE
TypeError: Cannot read property 'unmask' of undefined at Receiver.unmask

### ISSUE THREAD

**Issue by kamilsmuga** [websockets/ws#1010]
I have a very simple node app that uses socket.io. When I connect to the server from an external client it works fine. However, when I attempt to render UI using a browser, the server crashes on TypeError from Receiver.unmask.

My server code:
```javascript
const express = require('express');
const app = express();
const http = require('http').createServer(app);
const io = require('socket.io')(http);

const PORT = process.env.PORT || 8080;

app.use(express.static('public/dashboard'));

app.get('/', (req, res) => {
  res.sendFile(__dirname + '/public/dashboard/index.html');
});

io.on('connection', (client) => {
  console.log('Client connected');
  client.on('disconnect', () => console.log('Client disconnected'));
});

// broadcast PING to all connected sockets
// hoping to hear back from bots
setInterval(() => io.emit('PING', new Date().toTimeString()), 5000);

http.listen(PORT, function(){
  console.log(`listening on *:${PORT}`);
});
```

UI code:
```html
bunch of HTML and JS
    <script src="/socket.io/socket.io.js"></script>
    <script>
      var socket = io();
    </script>
```
Error on node server side:
```javascript
  socket.io:socket socket connected - writing packet +4ms
  socket.io:socket joining room Ipoywx491U9SrqRxAAAA +1ms
  socket.io:client writing packet {"type":0,"nsp":"/"} +1ms
  socket.io-parser encoding packet {"type":0,"nsp":"/"} +2s
  socket.io-parser encoded {"type":0,"nsp":"/"} as 0 +0ms
  engine:socket sending packet "message" (0) +10ms
  socket.io:socket joined room Ipoywx491U9SrqRxAAAA +4ms
  engine upgrading existing transport +16ms
  engine:socket might upgrade socket transport from "polling" to "websocket" +1ms
[my_workspace]/node_modules/ws/lib/Receiver.js:306
  if (mask != null && buf != null) bufferUtil.unmask(buf, mask);
                                             ^
TypeError: Cannot read property 'unmask' of undefined
    at Receiver.unmask ([my_workspace]/node_modules/ws/lib/Receiver.js:306:46)
    at Receiver.finish ([my_workspace]/node_modules/ws/lib/Receiver.js:505:25)
    at Receiver.expectHandler ([my_workspace]/node_modules/ws/lib/Receiver.js:493:33)
    at Receiver.add ([my_workspace]/node_modules/ws/lib/Receiver.js:103:24)
    at Socket.realHandler ([my_workspace]/node_modules/ws/lib/WebSocket.js:825:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:548:20)
```

Error in UI:
```javascript
engine.io-client:socket probe transport "websocket" opened +132ms
universalModuleDefinition:1 engine.io-client:polling polling got data ArrayBuffer +3ms
universalModuleDefinition:1 engine.io-client:socket socket receive: type "message", data "0" +1ms
universalModuleDefinition:1 socket.io-parser decoded 0 as {"type":0,"nsp":"/"} +0ms
universalModuleDefinition:1 engine.io-client:polling polling +5ms
universalModuleDefinition:1 engine.io-client:polling-xhr xhr poll +0ms
universalModuleDefinition:1 engine.io-client:polling-xhr xhr open GET: http://localhost:8080/socket.io/?EIO=3&transport=polling&t=LfNIZqL&sid=LZfZtocuqb1C9V0fAAAA +1ms
universalModuleDefinition:1 engine.io-client:polling-xhr xhr data null +1ms
universalModuleDefinition:1 engine.io-client:socket probe transport "websocket" failed because of error: transport closed +20ms
VM445:2 GET http://localhost:8080/socket.io/?EIO=3&transport=polling&t=LfNIZqL&sid=LZfZtocuqb1C9V0fAAAA net::ERR_CONNECTION_REFUSED
(anonymous) @ VM445:2
i.create @ universalModuleDefinition:2
i @ universalModuleDefinition:2
o.request @ universalModuleDefinition:2
o.doPoll @ universalModuleDefinition:2
n.poll @ universalModuleDefinition:2
n.onData @ universalModuleDefinition:2
(anonymous) @ universalModuleDefinition:2
n.emit @ universalModuleDefinition:2
i.onData @ universalModuleDefinition:2
i.onLoad @ universalModuleDefinition:2
hasXDR.r.onreadystatechange @ universalModuleDefinition:2
universalModuleDefinition:1 engine.io-client:socket socket error {"type":"TransportError","description":0} +13ms
universalModuleDefinition:1 socket.io-client:manager error +5ms Error: xhr poll error
    at o.n.onError (universalModuleDefinition:2)
    at i.<anonymous> (universalModuleDefinition:2)
    at i.n.emit (universalModuleDefinition:2)
    at i.onError (universalModuleDefinition:2)
    at universalModuleDefinition:2
universalModuleDefinition:1 engine.io-client:socket socket close with reason: "transport error" +8ms
```

Using Node v6.8.1, socket.io 1.7.3 that uses ws@1.1.2.
Is this a known issue or am I missing something obvious?

**Comment by lpinca** [comment]
Do you have `bufferutil` as dependency?

**Comment by kamilsmuga** [comment]
That was it! Thanks @lpinca

**Comment by eordano** [comment]
This is really annoying. Why isn't bufferutils a dependency instead of a devDependency?

**Comment by 3rd-Eden** [comment]
For the simple reason that binary module don't work everywhere. Adding it as dependency could cause the whole installation of the project fail. It's an optional dependency. But even adding it as optional dependency, if the compilation fails the whole installed dies. So the only solution is to have users install it manually if they want to use the binary addons.

**Comment by eordano** [comment]
Thanks for your prompt response!

Maybe I should open a new issue. I run into this on a clean install of `express` and `socket.io`. I wasn't aware that this lib was being used under the hood, and even less aware that there was an option for binary addons.

For some reason `bufferUtils` is undefined (the fallback did not work, same stack trace as the OP). I suspect that another package installed `bufferutils@2` and somehow that caused the error. But this definitely should not break.

**Comment by lpinca** [comment]
@eordano The problem is that [engine.io@1.8.3](https://github.com/socketio/engine.io/blob/f0bbc674d997960a0823128035450c54a891175c/package.json#L32) has a pinned version of `ws`.

If they upgrate to version `ws@1.1.4` the issue should disappear.

**Comment by eordano** [comment]
Thanks! I'll ping them.

**Comment by YuliyF** [comment]
"ws": "2.2.3"
Client connected -> error:
C:\Projects\NodeJs\WebStormProjects\WebSockets\node_modules\engine.io\node_modules\ws\lib\Receiver.js:306
  if (mask != null && buf != null) bufferUtil.unmask(buf, mask);

**Comment by lpinca** [comment]
@YuliyF `socket.io@1.7.3` depends on `engine.io@1.8.3` which depends on `ws@1.1.2`.
Ping them on https://github.com/socketio/engine.io/pull/495 to have this fixed.

**Comment by anamanuel** [comment]
I've that in my package.json:

  "optionalDependencies": {
    "bufferutil": "^3.0.2",
    "utf-8-validate": "^3.0.3"
  }

and  "ws": "^3.0.0" in dependencies

It doesn't still working

**Comment by lpinca** [comment]
@anamanuel if your other dependencies like `engine.io` require an incompatible `ws` version it doesn't matter what you set. You should check what `engine.io` version you are using.

**Comment by anamanuel** [comment]
@lpinca the version of engine.io is - "version": "1.8.2"

**Comment by lpinca** [comment]
Yes, that doesn't work you need 1.8.4 or use older versions of `bufferutil` and `utf-8-validate`.

**Comment by anamanuel** [comment]
@lpinca still doesn't work..

>`{
  "name": "autobot-builder",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "4.0.0",
    "@angular/common": "4.0.0",
    "@angular/compiler": "4.0.0",
    "@angular/core": "4.0.0",
    "@angular/forms": "4.0.0",
    "@angular/http": "4.0.0",
    "@angular/material": "^2.0.0-beta.3",
    "@angular/platform-browser": "4.0.0",
    "@angular/platform-browser-dynamic": "4.0.0",
    "@angular/router": "4.0.0",
    "@ngx-translate/core": "^6.0.1",
    "@ngx-translate/http-loader": "0.0.3",
    "@types/jointjs": "^1.0.3",
    "@types/rappid": "^1.5.28",
    "angular-in-memory-web-api": "~0.2.4",
    "core-js": "^2.4.1",
    "engine.io": "^1.8.4",
    "hammerjs": "^2.0.8",
    "material": "^0.1.1",
    "materialize-css": "^0.98.2",
    "rxjs": "^5.1.0",
    "underscore": "^1.8.3",
    "ws": "^1.1.4",
    "zone.js": "^0.8.4"
  },
  "devDependencies": {
    "@angular/cli": "^1.0.2",
    "@angular/compiler-cli": "4.0.0",
    "@types/jasmine": "2.5.38",
    "@types/node": "~6.0.60",
    "@types/jquery": "2.0.34",
    "autoprefixer": "^6.5.3",
    "backbone": "1.3.3",
    "codelyzer": "~2.0.0",
    "css-loader": "^0.27.3",
    "cssnano": "^3.10.0",
    "exports-loader": "^0.6.3",
    "extract-text-webpack-plugin": "^2.1.0",
    "file-loader": "^0.10.0",
    "graphlib": "1.0.7",
    "istanbul-instrumenter-loader": "^2.0.0",
    "jasmine-core": "~2.5.2",
    "jasmine-spec-reporter": "~3.2.0",
    "jointjs": "1.1.0",
    "json-loader": "^0.5.4",
    "karma": "~1.4.1",
    "karma-chrome-launcher": "~2.0.0",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^0.2.0",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "karma-sourcemap-loader": "^0.3.7",
    "less": "^2.7.2",
    "less-loader": "^4.0.3",
    "lodash": "^3.10.1",
    "node-sass": "^4.5.2",
    "postcss-loader": "^1.3.3",
    "postcss-url": "^5.1.2",
    "protractor": "~5.1.0",
    "sass-loader": "^6.0.3",
    "script-loader": "^0.7.0",
    "select2": "^4.0.3",
    "source-map-loader": "^0.1.5",
    "style-loader": "^0.13.2",
    "stylus-loader": "^3.0.1",
    "ts-node": "~2.0.0",
    "tslint": "~4.5.0",
    "typescript": "~2.2.0",
    "url-loader": "^0.5.7",
    "webpack-dev-server": "~2.4.2"
  },
  "optionalDependencies": {
    "bufferutil": "^3.0.2",
    "utf-8-validate": "^3.0.3"
  }
}
`

**Comment by anamanuel** [comment]
@lpinca still doesn't work

{
  "name": "autobot-builder",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "4.0.0",
    "@angular/common": "4.0.0",
    "@angular/compiler": "4.0.0",
    "@angular/core": "4.0.0",
    "@angular/forms": "4.0.0",
    "@angular/http": "4.0.0",
    "@angular/material": "^2.0.0-beta.3",
    "@angular/platform-browser": "4.0.0",
    "@angular/platform-browser-dynamic": "4.0.0",
    "@angular/router": "4.0.0",
    "@ngx-translate/core": "^6.0.1",
    "@ngx-translate/http-loader": "0.0.3",
    "@types/jointjs": "^1.0.3",
    "@types/rappid": "^1.5.28",
    "angular-in-memory-web-api": "~0.2.4",
    "core-js": "^2.4.1",
    "engine.io": "^1.8.4",
    "hammerjs": "^2.0.8",
    "material": "^0.1.1",
    "materialize-css": "^0.98.2",
    "rxjs": "^5.1.0",
    "underscore": "^1.8.3",
    "ws": "^1.1.4",
    "zone.js": "^0.8.4"
  },
  "devDependencies": {
    "@angular/cli": "^1.0.2",
    "@angular/compiler-cli": "4.0.0",
    "@types/jasmine": "2.5.38",
    "@types/node": "~6.0.60",
    "@types/jquery": "2.0.34",
    "autoprefixer": "^6.5.3",
    "backbone": "1.3.3",
    "codelyzer": "~2.0.0",
    "css-loader": "^0.27.3",
    "cssnano": "^3.10.0",
    "exports-loader": "^0.6.3",
    "extract-text-webpack-plugin": "^2.1.0",
    "file-loader": "^0.10.0",
    "graphlib": "1.0.7",
    "istanbul-instrumenter-loader": "^2.0.0",
    "jasmine-core": "~2.5.2",
    "jasmine-spec-reporter": "~3.2.0",
    "jointjs": "1.1.0",
    "json-loader": "^0.5.4",
    "karma": "~1.4.1",
    "karma-chrome-launcher": "~2.0.0",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^0.2.0",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "karma-sourcemap-loader": "^0.3.7",
    "less": "^2.7.2",
    "less-loader": "^4.0.3",
    "lodash": "^3.10.1",
    "node-sass": "^4.5.2",
    "postcss-loader": "^1.3.3",
    "postcss-url": "^5.1.2",
    "protractor": "~5.1.0",
    "sass-loader": "^6.0.3",
    "script-loader": "^0.7.0",
    "select2": "^4.0.3",
    "source-map-loader": "^0.1.5",
    "style-loader": "^0.13.2",
    "stylus-loader": "^3.0.1",
    "ts-node": "~2.0.0",
    "tslint": "~4.5.0",
    "typescript": "~2.2.0",
    "url-loader": "^0.5.7",
    "webpack-dev-server": "~2.4.2"
  },
  "optionalDependencies": {
    "bufferutil": "^3.0.2",
    "utf-8-validate": "^3.0.3"
  }
}

**Comment by lpinca** [comment]
Adding `engine.io` to your dependencies doesn't solve anything as it is a dependency of one or more of your other dependencies.

Remove the `optionalDependencies` completely or use

```
"optionalDependencies": {
  "bufferutil": "^1.0.0",
  "utf-8-validate": "^2.0.0"
}
```

**Comment by anamanuel** [comment]
I try do install the old version of bufferutil but appears this error: xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

**Comment by anamanuel** [comment]
but now the error is different when i run the ng test

14 07 2017 11:39:51.160:INFO [karma]: Karma v1.4.1 server started at http://0.0.0.0:9876/
14 07 2017 11:39:51.161:INFO [launcher]: Launching browser Chrome with unlimited concurrency
14 07 2017 11:39:51.178:INFO [launcher]: Starting browser Chrome
14 07 2017 11:39:59.829:WARN [karma]: No captured browser, open http://localhost:9876/  
14 07 2017 11:40:00.116:INFO [Chrome 59.0.3071 (Mac OS X 10.12.3)]: Connected on socket gvg7WJ6Hy186rxErAAAA with id 48755019
14 07 2017 11:40:00.150:ERROR [karma]: TypeError: Cannot read property 'isValidUTF8' of undefined
    at /Users/asantos/workspace/autobot_builder/node_modules/socket.io/node_modules/ws/lib/Receiver.js:532:28
    at /Users/asantos/workspace/autobot_builder/node_modules/socket.io/node_modules/ws/lib/Receiver.js:368:7
    at /Users/asantos/workspace/autobot_builder/node_modules/socket.io/node_modules/ws/lib/PerMessageDeflate.js:249:5
    at afterWrite (_stream_writable.js:383:3)
    at onwrite (_stream_writable.js:374:7)
    at afterTransform (_stream_transform.js:79:3)
    at TransformState.afterTransform (_stream_transform.js:54:12)
    at Zlib.callback (zlib.js:625:5)

**Comment by anamanuel** [comment]
solved

**Comment by adnanhaddad** [comment]
Could you guys help me out with this? I have `bufferutil@^4.0.1` and `ws@^7.3.1` installed. Node version is **12.6.2**
Other info and _package.json_ is [here](https://stackoverflow.com/questions/64353032/angular-typeerror-cannot-read-property-unmask-of-undefined-adding-bufferuti)

**Comment by windsome** [comment]
suggestion: don't not use dynamic require of bufferutil and utf-8-validate, because of when packaging using webpack, will lose both, and will crash.
