### ISSUE TITLE
Sessions don't update until I close my connection and reconnect

### ISSUE THREAD

**Issue by jrgleason** [websockets/ws#1011]
Based on [this example](https://github.com/websockets/ws/tree/master/examples/express-session-parse) I have added session support to my Websockets. Under the following use case everything works fine.

```
app.ws('/messages', function(ws, req) {
  ws.on('message', function(msg) {
    const session = ws.upgradeReq.session;
    req.session.reload(function(err) {
      // session updated
      console.log(`Session ${JSON.stringify(session)}`);
      expressWs.getWss().clients.forEach(function(client) {
        client.send(msg+" Added")
      });
    });
  });
  console.log("Connection Created");
});
```

1.) Open Websocket
2.) Send a message note that there is no session
3.) Disconnect Websocket
4.) Login over http
5.) Open Websocket
6.) Send Message, note that there is a session

That works as expected so I try a more confusing use case...

1.) Open Websocket
2.) Send a message note that there is no session
3.) Login over http
4.) Send Message, note that there is no session

This is not as I would expect I would expect the session to be there since they are logged in. So if I disconnect and reconnect the Websocket I see the session as I would expect.

Why do I have to disconnect and reconnect? Is there a way I can refresh the session without closing and opening the websocket?

**Comment by shortercode** [comment]
As far as i understand websockets are a single http request. The request performs the handshake with the server, then it returns to the client. After that no headers are exchanged ( which includes session cookies ).

This means you can only recieve headers/cookies at the very start of the socket creation and only set them during the handshake.

**Comment by jrgleason** [comment]
Thanks I will look into the spec a little more and confirm.

**Comment by lpinca** [comment]
> This means you can only recieve headers/cookies at the very start of the socket creation and only set them during the handshake.

This is correct, closing.
