### ISSUE TITLE
purpose of readyState

### ISSUE THREAD

**Issue by namgk** [websockets/ws#1014]
It seems _readyState_ does not reflect the actual state of the connection right? 

I have a ws client and ws server, they are disconnected by pulling the cord for hours but readyState still shows as connected.

I know there are "table tennis"-style approaches but I just want to confirm the actual purpose of _readyState_.

Thanks.

**Comment by lpinca** [comment]
I'm not sure what you mean. Yes, the `readyState` property should reflect the status of the connection.

**Comment by lpinca** [comment]
> they are disconnected by pulling the cord for hours but readyState still shows as connected

I guess you mean that the server is unable to detect that connection is closed if you unplug the cable? That's correct and as you said you need a heartbeat system to detect that.

**Comment by namgk** [comment]
I mean it only reflects connection status in ideal cases when server and client are able to talk to each other. With network disconnection, both server amd client are unaware of the situation and I cannot rely on this state variable to determine. 

My client is also a Node program, not the browser.

**Comment by lpinca** [comment]
If there is no way to detect a disconnection there is also no way to update the `readySate`.
