### ISSUE TITLE
EPIPE Write

### ISSUE THREAD

**Issue by jssuttles** [websockets/ws#1017]
Not sure when this comes up but just wondering if you have changed any code that might cause these to occur more frequently.

![pasted image at 2017_02_23 05_38 pm](https://cloud.githubusercontent.com/assets/8527741/23282384/f1d65ee4-f9ee-11e6-9fbe-acaca8dd1845.png)

I used to run ws without 
socket.on('error'
Now I have to have it or it crashes the application.

**Comment by lpinca** [comment]
This is odd as there is always ([1](https://github.com/websockets/ws/blob/eed0814853dbd4ac9b1ca3a29057121c8a0a703f/lib/WebSocket.js#L126), [2](https://github.com/websockets/ws/blob/eed0814853dbd4ac9b1ca3a29057121c8a0a703f/lib/WebSocket.js#L193-L195)) an `error` listener on the internal socket which should prevent this.

What version of `ws` are you running? What is the Node.js version? Also what is the operating system?

**Comment by jssuttles** [comment]
ws@2.1.0
node@6.2.2
macOS Sierra

**Comment by lpinca** [comment]
Do you have a test case to reproduce the issue or is this something that happens randomly on a production app?

**Comment by jssuttles** [comment]
Randomly on socket close while on development. Haven't seen it yet on production.

**Comment by lpinca** [comment]
Can you try to upgrade to latest v6.x and see if the issue persists? Does you app interact with the `_socket` property directly?

**Comment by jssuttles** [comment]
No, to the second question. I'll get back to the first when I get time.

**Comment by brenc** [comment]
Just upgraded to ws@2.2.0 today and started seeing this (Node v6.10.0, Debian 7). I have haproxy set up to do websocket health checks so it does a quick connect / disconnect every second or so. I detect these types of connections and handle them differently, which includes not assigning handlers including socket errors (hence the crash). 

What I was doing was detecting these types of connections and manually running a close() on them. Right before this I checked readyState and it was set to open. I think maybe what happened was the connection was closed / closing in some way by the time close() actually ran.

All I had to do to fix this was to setTimeout for a second later, check readyState, and if the connection is still open, I run a close(). Before I was running ws@1.1.1 and had to check readyState before a send as well otherwise I'd get a crash.

**Comment by brenc** [comment]
Just as I posted this, I decided to try running close() without a readyState check a second after connection, and it worked without a crash. I then tried 100ms later and it worked as well. Seems there is a timing issue such that if I call close() too soon after connection, I get the "write EPIPE" error and a crash.

**Comment by lpinca** [comment]
@brenc thanks. Are you able to create a reproducible test case?

**Comment by lpinca** [comment]
Ok I think I've found a possible explanation for this. Here is a test case which doesn't use `ws` but reproduces what I think happens:

```js
'use strict';

const arr = [];

function callback(err) {
  if (err) arr.push({ from: 'callback', err });
}

process.on('exit', () => console.error(arr));

process.stdout.on('error', (err) => arr.push({ from: 'listener', err }));

for (var i = 0; i < 100; i++) {
  process.stdout.write('something\n', callback);
}
```

Running the above example with

```
node index.js | head
```

prints

```
something
something
something
something
something
something
something
something
something
something
[ { from: 'callback',
    err: 
     { Error: write EPIPE
         at exports._errnoException (util.js:1033:11)
         at WriteWrap.afterWrite [as oncomplete] (net.js:816:14) code: 'EPIPE', errno: 'EPIPE', syscall: 'write' } },
  { from: 'listener',
    err: 
     { Error: write EPIPE
         at exports._errnoException (util.js:1033:11)
         at WriteWrap.afterWrite [as oncomplete] (net.js:816:14) code: 'EPIPE', errno: 'EPIPE', syscall: 'write' } } ]
```

so the `error` [listener](https://github.com/websockets/ws/blob/72170d455c38637ef5702c5d8270e72c55313181/lib/WebSocket.js#L129) on the socket is called **after** the write [callback](https://github.com/websockets/ws/blob/72170d455c38637ef5702c5d8270e72c55313181/lib/Sender.js#L379). When the callback is invoked, the error is [emitted](https://github.com/websockets/ws/blob/72170d455c38637ef5702c5d8270e72c55313181/lib/WebSocket.js#L285) on the `WebSocket` instance and if there isn't a listener it crashes.

I don't see this as a big issue, we can avoid [re-emitting](https://github.com/websockets/ws/blob/72170d455c38637ef5702c5d8270e72c55313181/lib/WebSocket.js#L285) the error but I think it is actually a valuable info.

An error listener on the `WebSocket` instance is sufficient and should always be added anyway as there are a lot of more errors which can be emitted and make the process crash if they are not handled.

**Comment by brenc** [comment]
Makes sense. I definitely think that an error listener should always be added. I might have to add one even for these health check connections.

**Comment by lpinca** [comment]
Closing, please comment or reopen if needed.

**Comment by crazyyi** [comment]
I get this error too when I am writing my multiplayer game. I use the following code to send a message.

```
try {
    ws.send(msg, function(error) {
	if(error == undefined)
		return;
	ws.close();
	logger.debug("Async error:"+error);
    });		
} catch (e) {
    logger.debug("Sync error: " + e);
    ws.close();
}				
```

But I still get the error when I am playing the game normally. 
I have no idea why the readyState is switched silently.
What should I do to avoid getting this error when the readyState is not OPEN for some unknown reason?
