### ISSUE TITLE
Multiple path on same port

### ISSUE THREAD

**Issue by LYZhelloworld** [websockets/ws#1019]
Is it possible to host multiple applications on the same port, but with different path? For example one on ws://host-name:1234/path1 and another on ws://host-name/path2

**Comment by LYZhelloworld** [comment]
Well I think I have found it.

After reading the source code, I realized that I can use ws.upgradeReq.url to get the path of request on connection.

**Comment by maxcnunes** [comment]
In case someone else needs it too. There is a good example here as well: https://github.com/websockets/ws/pull/885#issue-187590719.
