### ISSUE TITLE
How to send binary data from browser?

### ISSUE THREAD

**Issue by terbooter** [websockets/ws#1022]
web browser client
```HTML
<body>
<script>
    //const WebSocket = require('ws');

    const ws = new WebSocket('ws://127.0.0.1:8080');
    ws.binaryType = "blob";
    ws.onopen = function open() {
        const array = new Float32Array(5);

        for (var i = 0; i < array.length; ++i) {
            array[i] = i / 2;
        }
        console.log(array);
        ws.send(array);
    };
</script>
</body>
```

nodejs server
```js
const WebSocket = require('ws');

const wss = new WebSocket.Server({ port: 8080  });

wss.on('connection', function connection(ws) {
    ws.on('message', function incoming(message) {
        console.log(message.data);
        console.log(message.type);
        console.log('received: %s', message);
    });

    ws.send('something');
});
```

server logs
```
undefined
undefined
received:        ?  �?  �?   @
```

How can I parse data on server?  
How check message type (arraybuffer or blob) on server?

**Comment by lpinca** [comment]
On the server, by default, you receive a Node.js [`Buffer`](https://nodejs.org/dist/latest-v7.x/docs/api/buffer.html#buffer_buffer) for binary messages.
If you want to get an `ArrayBuffer` you can convert the buffer yourself or set the `binaryType` to `arraybuffer`.

```js
wss.on('connection', (ws) => {
  ws.binaryType = 'arraybuffer';

  ws.on('message', (message) => {
    const array = new Float32Array(message);

    console.log(array);
  });
});
```

**Comment by cbratschi** [comment]
I have a strange problem with Starscream on iOS:

https://github.com/daltoniam/Starscream

If the iOS app sends a message as binary (Data), the Node.js server returns a typeof 'object' and not a Buffer. Stranger, the object is the JSON string I sent as Data on iOS. So why is this getting converted to an Object? Any clue?

String messages work as expected.

**Comment by lpinca** [comment]
> So why is this getting converted to an Object? Any clue?
 
I don't know, you can only receive a `String` a Node.js `Buffer` or an `ArrayBuffer`, what is the exact object you are receiving?

**Comment by cbratschi** [comment]
console.dir() displays a fully expanded object, the same as receiving as a string and using JSON.parse(). I would have expected a Buffer.

**Comment by lpinca** [comment]
@cbratschi add a listener for the `'data'` event to the internal socket and see if the client sends the correct data.

```js
ws._socket.on('data', (data) => console.log(data));
```

The first byte should be `0x89`.
