### ISSUE TITLE
WebSocket Server send so many unknown opcode

### ISSUE THREAD

**Issue by harlentan** [websockets/ws#1038]
My server try to ping the client every 30 seconds. 

```
        client.ping(undefined, undefined, true);
```
I use wireshark to capture the packets sended by server on the client side. But I get so many unknown opcode.

Why the WebSocket Server sends so many unknown opcode? 

![snip20170309_2](https://cloud.githubusercontent.com/assets/1267060/23733409/ad4c62e4-04b3-11e7-9764-863538135839.png)

**Comment by lpinca** [comment]
I think this is an issue with how wireshark inspect the packets. Both the client and server send only valid frames.

Maybe this happens because a frame is split over multiple TCP packets.

**Comment by lpinca** [comment]
@harlentan it works as expected for me:

![screenshot at 2017-03-09 16-13-15](https://cloud.githubusercontent.com/assets/1443911/23756299/7e058ae4-04e3-11e7-815a-161f1023f4e9.png)

This is the server code:

```js
'use strict';

const WebSocket = require('ws');

const wss = new WebSocket.Server({ port: 3000 });

wss.on('connection', (ws) => {
  setInterval(() => ws.ping(null, null, true), 30000);
});
```
