### ISSUE TITLE
Node server keeps crashing repeatedly with "Error: reserved fields must be empty"

### ISSUE THREAD

**Issue by booboothefool** [websockets/ws#1039]
This started happening suddenly, and now I can't even get my server back up. It's been a few hours. it just restarts, then immediately crashes.

![screen shot 2017-03-09 at 6 52 02 pm](https://cloud.githubusercontent.com/assets/13257645/23778589/19f14a36-0509-11e7-962c-e6a3603f52e5.png)

Any ideas?

![screen shot 2017-03-09 at 8 26 49 pm](https://cloud.githubusercontent.com/assets/13257645/23778340/acc1d418-0507-11e7-9e1a-f636204ffef6.png)

Very scary...

**Comment by lpinca** [comment]
Add an error listener to your `WebSocket` objects and handle the error.

```js
wss.on('connection', (ws) => {
  ws.on('error', (err) => handleError(err));
});
```

This error is raised when the client sends a frame with one or more reserved bit on. It can happen because the client is broken or because a bad actor is sending invalid frames with the aim of crashing your server.

**Comment by booboothefool** [comment]
@lpinca Do you have any advice on how to implement this with this library?

https://github.com/apollographql/subscriptions-transport-ws/issues/94

It looks like I'd do something like this:

```
new SubscriptionServer(
  {
    subscriptionManager,
    keepAlive: 20000,
    onConnect: async (connectionParams, webSocket) => {
      webSocket.on('error', err => console.error('(webSocket) =>\t'.red, err));
    },
  },
  {
    server: websocketServer,
    path: '/',
  }
);
```

which does not seem to be helping as the server continues to crash with "reserved fields must be empty".

**Comment by lpinca** [comment]
What you wrote in this comment https://github.com/apollographql/subscriptions-transport-ws/issues/94#issuecomment-285777678 seems correct to me. There should be an error listener there.

**Comment by booboothefool** [comment]
@lpinca Yes, after I made sure the change was in:

Wrong:
```
new SubscriptionServer(
  {
    subscriptionManager,
    keepAlive: 20000,
    onConnect: async (connectionParams, webSocket) => {
      webSocket.on('error', err => console.error(err));
    },
  },
  {
    server: websocketServer,
    path: '/',
  }
);
```

Correct:
```
            request.on('error', function (err) {
                console.error(err);
            });
```
https://github.com/apollographql/subscriptions-transport-ws/blob/master/src/server.ts#L96

It is catching the error, and no longer crashing. All is well now. Thanks so much.
