### ISSUE TITLE
add an option to limit message (and/or frame) size for the WebSocketServer 

### ISSUE THREAD

**Issue by julienboeuf** [websockets/ws#104]
First off, thanks for this great (and fast!) node.js module. 

This is a feature request:

If I'm not mistaken, a client could send a 4GB frame (32 bits max in the Receiver.js code) without the server being able to reject the request with a 1009 error. This could cause some problems in a real life deployment of the stack where not all your clients can be trusted to send you a reasonable amount of data per message (as the whole message has to be able to fit in memory).

Are you planning on adding such an option?

Thanks much.

**Comment by andvgal** [comment]
+1
It looks like an easy DoS vector.

**Comment by galambalazs** [comment]
+1

**Comment by rangercyh** [comment]
+1

**Comment by avesus** [comment]
:+1:

**Comment by galambalazs** [comment]
Issue is from 3 years ago.

Do we have a chance for it to be implemented, or not unless someone from the community picks it up?

**Comment by lpinca** [comment]
Server now accepts a `maxPayload` option which specifies the maximum allowed message size.
