### ISSUE TITLE
Unsupported bufferutil is required then throws TypeError

### ISSUE THREAD

**Issue by xuset** [websockets/ws#1040]
This is almost the same as #1010 except the main difference is that I can't control the versions of `ws` and `bufferutil` since they are dependencies of dependencies. The test runner I'm using uses `ws@1` while an unrelated dependency relies on `bufferutil@3`. This causes `TypeError: Cannot read property 'unmask' of undefined` to be thrown.

This issue surfaced when `bufferutil@3` was added as an optional dependency for feross/bittorrent-tracker@d22ad6b6fab0ee44f54483b0586e48644787515f . I'm not sure what my options are in fixing this on my end since I can't control the dependencies of my dependencies.

Any help is greatly appreciated! 👍

**Comment by lpinca** [comment]
Do you rely on optional dependencies? If not use `npm install --no-optional`.

**Comment by xuset** [comment]
Ah that does fix it! The fix does seem to cover up the actual problem though, but I'm lucky that it's only an optional dependency :)

**Comment by lpinca** [comment]
Yeah it's a workaround. I can't think of a good way to fix the issue.
`ws@1` could be made compatible with new versions of `bufferutil ` and `utf-8-validate` but their fallback versions are no longer compatible with Node.js < 4.
Also even if a new `ws@1` is released, it is possible that the dependency is pinned down so the fix may be useless.

The only way to get rid of the problem is not installing the optional dep or reverting https://github.com/feross/bittorrent-tracker/commit/d22ad6b6fab0ee44f54483b0586e48644787515f.

**Comment by lpinca** [comment]
Another option is to make `bittorrent-tracker` use `bufferutil@1`. If the number of users affected by this issue grows I'll propose the change there.

**Comment by xuset** [comment]
Those are all good points. I did have one idea for a general fix though. In `BufferUtil.js` when `bufferutil` is required the code assumes the `bufferutil` version is compatible with the version of `ws`. Maybe a check could be put in place to only use `bufferutil` if it's version is compatible with that version of `ws`. What are your thoughts on this? It wouldn't fix the pinned dependency problem you mentioned, but hopefully most people don't pin down the patch version number

**Comment by lpinca** [comment]
> Maybe a check could be put in place to only use bufferutil if it's version is compatible with that version of ws.

It's almost the same of making `ws@1` compatible with `bufferutil@>1` and `utf-8-validate@>2`.

**Comment by xuset** [comment]
Yeah I see that now. I'm all for that then!

**Comment by lpinca** [comment]
@xuset done. `ws@1.1.4` should work with `bufferutil@>1` and `utf-8-validate@>2`.
