### ISSUE TITLE
Error: (SystemJS) Buffer.alloc is not a function

### ISSUE THREAD

**Issue by normanjaeckel** [websockets/ws#1041]
I used [JSPM](http://jspm.io/) and installed [angular.wamp](https://github.com/voryx/angular-wamp) which depends on autobahn which depends on this project. (Then I had to override the optional dependencies (bufferutil and utf-8-validate) in the package.json so that SystemJS does not complain about missing deps, but this is not my point here.)

Then I got the following error in my browser console:
```
Error: (SystemJS) Buffer.alloc is not a function
	@http://127.0.0.1:8080/jspm_packages/npm/ws@2.2.0/lib/Constants.js:6:26
	@http://127.0.0.1:8080/jspm_packages/npm/ws@2.2.0/lib/Constants.js:2:2
	@http://127.0.0.1:8080/jspm_packages/npm/ws@2.2.0/lib/Constants.js:1:31
	@http://127.0.0.1:8080/jspm_packages/npm/ws@2.2.0/lib/Constants.js:1:2
	@http://127.0.0.1:8080/jspm_packages/npm/ws@2.2.0/lib/WebSocket.js:13:21
	@http://127.0.0.1:8080/jspm_packages/npm/ws@2.2.0/lib/WebSocket.js:2:2
	@http://127.0.0.1:8080/jspm_packages/npm/ws@2.2.0/lib/WebSocket.js:1:31
	@http://127.0.0.1:8080/jspm_packages/npm/ws@2.2.0/lib/WebSocket.js:1:2
	@http://127.0.0.1:8080/jspm_packages/npm/ws@2.2.0/index.js:3:19
	@http://127.0.0.1:8080/jspm_packages/npm/ws@2.2.0/index.js:1:31
	@http://127.0.0.1:8080/jspm_packages/npm/ws@2.2.0/index.js:1:2
	@http://127.0.0.1:8080/jspm_packages/npm/ws@2.2.0.js:1:123
	@http://127.0.0.1:8080/jspm_packages/npm/ws@2.2.0.js:1:31
	@http://127.0.0.1:8080/jspm_packages/npm/ws@2.2.0.js:1:2
	
	Evaluating http://127.0.0.1:8080/jspm_packages/npm/ws@2.2.0/lib/Constants.js
	Evaluating http://127.0.0.1:8080/jspm_packages/npm/ws@2.2.0/lib/WebSocket.js
	Evaluating http://127.0.0.1:8080/jspm_packages/npm/ws@2.2.0/index.js
	Evaluating http://127.0.0.1:8080/jspm_packages/npm/ws@2.2.0.js
	Error loading http://127.0.0.1:8080/src/main.js
```

I have absolutely no idea what I can do here. The `Buffer.alloc` in the Constants.js is the problem and I found only some StackOverflow stuff about upgrading Node.js but here I am in the browser (Firefox 52.0) and so this has nothing to do with Node.js I think.

Can you please give me a hint? Many thanks in advance.

**Comment by lpinca** [comment]
I don't know how JSPM works but `ws` only works in Node.js. In the browser you have to use the native `WebSocket` object.

`autobahn` uses the [`browser`](https://github.com/crossbario/autobahn-js/blob/8b092ed3b59445679df52132c126807ce39fe4f5/package.json#L26) field in the package.json to tell bundlers that `ws` should not be included in the bundle.

Maybe JSPM is ignoring that?

**Comment by normanjaeckel** [comment]
It looks like that `angular-wamp` refers to autobahn 0.9.9 which is outdated and does not exclude `ws` in the browser field. So I will go ahead here. Many thanks for your answer.
