### ISSUE TITLE
Slow transferring files to client - HOL blocking?

### ISSUE THREAD

**Issue by smithrobert** [websockets/ws#1042]
I noticed that there are significant delays when repeatedly transferring a file (10 - 100 kB) from server to client using the same connection/socket. E.g. transferring 100kB file with 100 repetitions takes ~7 seconds.

My first hunch is that the connection is susceptible to HOL blocking, or have I missed something?

**Server code**
```
const WebSocket = require('ws');
const https = require('https');
const fs = require('fs');

const options = {
  key: fs.readFileSync('<path-to-key>'),
  cert: fs.readFileSync('<path-to-cert>')
};

var file = fs.readFileSync('<path-to-file>')

var httpServer = new https.createServer(options).listen(443);

var wss = new WebSocket.Server({
  server: httpServer,
  perMessageDeflate: false
});

wss.on('connection', function(ws) {
  for (let i = 0; i < repetition; i++) {
    ws.send(file);
  }
});
```

**Comment by lpinca** [comment]
@smithrobert I'm not sure.

It's pretty fast on localhost. On my prehistoric machine I get 

```
100 * 100 KiB: 465.877ms
```

with the following test

<details>
<summary>Server</summary>

```js
'use strict';

const crypto = require('crypto');
const WebSocket = require('ws');

const data = crypto.randomBytes(100 * 1024);
const wss = new WebSocket.Server({ port: 3000 });

wss.on('connection', (ws) => {
  for (var i = 0; i < 100; i++) {
    ws.send(data);
  }
});
```

</details>

<details>
<summary>Client</summary>

```js
'use strict';

const WebSocket = require('ws');

const ws = new WebSocket('ws://localhost:3000');

ws.on('open', () => console.time('100 * 100 KiB'));

var count = 0;
ws.on('message', () => {
  if (++count === 100) {
    console.timeEnd('100 * 100 KiB');
    ws.close();
  }
});
```

</details>

**Comment by smithrobert** [comment]
@lpinca Running your code on localhost I get
``100 * 100 KiB: 606.160ms``

WAN connection to my desktop takes a bit longer
``100 * 100 KiB: 2225.619ms``

What's confusing me is that pushing the same amount of data on a HTTP/2 connection is much faster (LAN: 330.785ms, WAN: 571.245ms). Are the WS-messages blocking?

<details>
<summary>Server code (HTTP/2)</summary>

```
const spdy = require('spdy');
const fs = require('fs');
const crypto = require('crypto');

const data = crypto.randomBytes(100 * 1024);
const options = {
  key: fs.readFileSync('keys/privkey.pem'),
  cert: fs.readFileSync('keys/fullchain.pem')
};

spdy.createServer(options, function(request, response) {
  for (let i = 0; i < 100; i++) {
    response.push('./' + i, {}, function(err, stream) {
      stream.end(data);
    });
  }
}).listen(443);
```

</details>

<details>
<summary>Client code (HTTP/2)</summary>

```
const spdy = require('spdy');
const https = require('https');
const url = 'website.me';

console.time('100 * 100 KiB');
var agent = spdy.createAgent({
  host: url,
  port: 443,
});

var request = https.get({
  host: url,
  agent: agent
});

var count = 0;
request.on('push', () => {
  if (++count == 100) { console.timeEnd('100 * 100 KiB'); }
});
```
</details>

**Comment by lpinca** [comment]
@smithrobert I forgot to disable the permessage-deflate extension in the example. With permessage-deflate disabled:

```js
const wss = new WebSocket.Server({
  perMessageDeflate: false,
  port: 3000
});
```

I get `100 * 100 KiB: 31.903ms`. Can you please see if it makes any difference for you?

**Comment by marwankhalili** [comment]
@lpinca  Disabling _permessage-deflate_ was a huge improvement when testing on localhost:
``100 * 100 KiB: 39.441ms.`` 

However, I still get the same results as before over WAN (e.g. ``100 * 100 KiB: 2115.659ms``). Any ideas on how to improve the WAN transfers?

**Comment by lpinca** [comment]
I don't know. Can it be something in your setup? Slow client? Throttled network? Too many variables.

For completeness I get `100 * 100 KiB: 188.775ms` with `node-spdy`.

<details>
<summary>Server (SPDY)</summary>

```
'use strict';

const crypto = require('crypto');
const spdy = require('spdy');
const fs = require('fs');

const data = crypto.randomBytes(100 * 1024);

spdy.createServer({
  cert: fs.readFileSync('keys/server.crt'),
  key: fs.readFileSync('keys/server.key')
}, (req, res) => {
  for (var i = 0; i < 100; i++) {
    const push = res.push(`/${i}`, {});
    push.end(data);
  }
  res.end();
}).listen(8080);
```
</details>

<details>
<summary>Client (SPDY)</summary>

```
'use strict';

const https = require('https');
const spdy = require('spdy');

const agent = spdy.createAgent({
  rejectUnauthorized: false,
  port: 8080
});

const req = https.get({ agent }, (res) => {
  console.time('100 * 100 KiB');
  res.resume();
});

var count = 0;
const onEnd = () => {
  if (++count === 100) {
    console.timeEnd('100 * 100 KiB');
    agent.close();
  }
};

req.on('push', (push) => {
  push.resume();
  push.on('end', onEnd);
});
req.end();
```
</details>

**Comment by lpinca** [comment]
One thing to keep in mind in this example is multiplexing.

HTTP2 uses `n` streams that work in parallel. Frames of different streams can be interleaved preventing one large message from monopolizing the output channel.

With WebSocket this is not possible by default (there is a draft of an extension for multiplexing) and a message will not start to be read until the previous one has been fully received.

**Comment by smithrobert** [comment]
The multiplexing reason seems plausible. I'll close the issue for now since there doesn't seem to be a clear solution.

**Comment by lpinca** [comment]
Yeah but the timer is stopped when all streams end so I doubt this is what makes the difference as the throughput is the same.
