### ISSUE TITLE
Multiple paths to one server

### ISSUE THREAD

**Issue by JoshuaWise** [websockets/ws#1044]
@lpinca 

I noticed [this code](https://github.com/websockets/ws/blob/master/lib/WebSocketServer.js#L157-L160) in `WebSocketServer.js`. Wouldn't that prevent multiple websocket servers from being attached to the same http server at different paths?

**Comment by lpinca** [comment]
@JoshuaWise yes, see https://github.com/websockets/ws/pull/885.

**Comment by JoshuaWise** [comment]
Ahh okay, I missed that. Thanks for the clarification.
