### ISSUE TITLE
Add new client method for sending fake requests

### ISSUE THREAD

**Issue by mirik123** [websockets/ws#1047]
Please add new client method (for example - emit) for directly invoking onMessage event without sending requests to WebSocket server. It can greatly help in scenarios like this:

```javascript
public send(content: any) {
        if(!this.ws || this.ws.readyState !== WebSocket.OPEN) {
            this.ws.emit(JSON.stringify({ error: 'server is disconnected' }));
            return;
        }

        try {
            this.ws.send(JSON.stringify(content));
        }
        catch (err) {
            this.ws.emit(JSON.stringify({ error: 'server error' }));
        }
    }
```

**Comment by lpinca** [comment]
The `WebSocket` class inherits from `EventEmitter` so you can already emit events.

```js
ws.emit('message', 'foo');
```

**Comment by mirik123** [comment]
Yes, I see now.
I just checked native browser's WebSocket API.
Thanks for the answer.
