### ISSUE TITLE
Option to add properties on verifyClient

### ISSUE THREAD

**Issue by Sybergoth** [websockets/ws#1049]
Hey I'm currently implementing a service based on webSockets. In my project I am using passport for authentication. I wanted to add the authentication also to the websocket protocol establishment so on the client side I am adding the session ID to the upgradeReq.
I made a function for verifyClient that verifies the user using the cookie from the upgradeReq header.
However, I have no option to add to the ws object any properties (the user info for example) and so I need to call the same authentication functions again using ws.upgradeReq.headers after the ws connection is established.

Maybe I'm missing something but it would be very helpful if I could add extra properties.

**Comment by lpinca** [comment]
You can add stuff to `req` object which is passed to the `verifyClient` function. You can then find the things you added in `ws.upgradeReq`.

`info.req` and `ws.upgradeReq` are the same object.

Hope this makes sense.

**Comment by Sybergoth** [comment]
Please look at the code below. The req param is passed through info constant which cannot be changed. I tried adding my auth object to it and nothing happend.
`const info = {
        origin: req.headers[`${version === 8 ? 'sec-websocket-origin' : 'origin'}`],
        secure: !!(req.connection.authorized || req.connection.encrypted),
        req
      };

      if (this.options.verifyClient.length === 2) {
        this.options.verifyClient(info, (verified, code, message) => {
          if (!verified) return abortConnection(socket, code || 401, message);

          this.completeUpgrade(protocol, version, req, socket, head, cb);
        });
        return;
      }`

**Comment by lpinca** [comment]
```js
function verifyClient(info, next) {
  info.req.foo = 'bar';
  next(true);
}

const wss = new WebSocket.Server({ port: 8080, verifyClient });

wss.on('connection', function (ws) {
  assert.ok(ws.upgradeReq.foo === 'bar');
});
```

**Comment by lpinca** [comment]
@Sybergoth is there anything you still need help with?

**Comment by Sybergoth** [comment]
Thank you, it worked

**Comment by revl-ca** [comment]
Hey @lpinca ,

Let's assume that I use the example above, how can I get `foo` it from a client object?

```
wss.clients.forEach(client => {
  // Any way to get foo?
})
```

Thank you

**Comment by lpinca** [comment]
```js
wss.on('connection', function (ws, req) {
  ws.foo = req.foo;
  req.foo = undefined;
});

wss.clients.forEach(function (client) {
  // client.foo
})
```

**Comment by revl-ca** [comment]
@lpinca works like a charm.

You are very responding. I'm truly impressed.

Have a great weekend Luigi.
