### ISSUE TITLE
Support for React.JS

### ISSUE THREAD

**Issue by rajiff** [websockets/ws#1051]
From documents, its not clear how to use this library in React.JS (in ES6)

Please drop a example about the same

**Comment by lpinca** [comment]
It works like any other Node.js package.
In the browser you have to use the native WebSocket object not ws.

**Comment by rajiff** [comment]
@lpinca Thanks

An example would help (it can be incorporated to this if needed as Pull Request https://github.com/rajiff/ws-react-demo)

That means, in WS we also don't have support for any channel/room/namespace concept?

**Comment by lpinca** [comment]
> That means, in WS we also don't have support for any channel/room/namespace concept?

Yes, that's correct.

As for the examples, there are a lot of results if you search "react websocket example" on google.

**Comment by rajiff** [comment]
@lpinca : I update my repo now with working version, please have a look and suggest

What is the suggestion if we want to send data to specific client sockets only? only emit on that socket object alone?

**Comment by 3rd-Eden** [comment]
Here's another example; I'm using the React Context API to share the connection between all components: 

https://github.com/DestinyTheGame/anubis/blob/master/components/websocket/index.js

**Comment by rajiff** [comment]
Thanks @3rd-Eden 

I now have this updated, a fully functional react ws client with 'WS' as server

Going to try this with socket.io also as i need put channels/rooms

**Comment by rajiff** [comment]
Thanks @3rd-Eden 

I now got it updated https://github.com/rajiff/ws-react-demo/blob/master/public/components/WebSocketClient.jsx, a fully functional react ws client with 'WS' as server

Going to try this with socket.io also as i need pvt channels/rooms
