### ISSUE TITLE
Write EPIPE error on ws.send(), unable to catch.

### ISSUE THREAD

**Issue by Stylesoftware** [websockets/ws#1052]
Using node 6 latest
I get this error if a client disco's as ws.send() is called.

```
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at exports._errnoException (util.js:1022:11)
    at WriteWrap.afterWrite (net.js:801:14)

```

I try to check for existence, and readyState, wrapped in a try-catch, but it won't catch.

```
        if(ifExists(ws) && ifExists(ws.readyState) && (ws.readyState == 1)) {
		try {
			ws.send(s);
		} catch (e) {
                        log('im never called');
			// delete Clients[ws.__clientCount];
			}
		}
	}
```

**Comment by Stylesoftware** [comment]
I Think i fixed this with:

                

```
                  try {
			ws.send(s, function ack(error) {
				if(error == undefined)
					return;
				ws.close();
                                log("Async error:"+error);
			});
		} catch (e) {
                        log("Sync error:"+e);
                        ws.close();
		}
```

**Comment by lpinca** [comment]
https://github.com/websockets/ws/issues/1017

**Comment by crazyyi** [comment]
How long will it take for a websocket connection to close itself? I have used @Stylesoftware 's code above and the error is gone. However it can log the "Async error:" information for a few seconds. Suppose I have an online game, the server may send the information multiple times a second and bad connections appear often for 24/7 the log file will be huge.

**Comment by Stylesoftware** [comment]
You should consider using your own ping thru WS, I use client ping and
server checking:

Add all your user authentication and last ping time and WS connection
object to an array of user objects,
Add the user array number to the WS connection object
When a new WS event occurs, use the WS.user_array_number to look up the
user info for any auth checking, and reset the ping time.
Use a function with setInterval to check all ping times in your user array,
if over 6 seconds, kill the WS connection, delete the user_array object
Ensure all clients send a ping thru ws every 3 seconds or so.
