### ISSUE TITLE
Angular - crypto.randomBytes is not a function

### ISSUE THREAD

**Issue by mihaesandrei** [websockets/ws#1053]
I'm trying to import ws library into an Angular2 project, but I receive this error: 
`ERROR TypeError: crypto.randomBytes is not a function`

Importing the library in the component: `import WebSocket from 'ws'`
And in _onInit_ hook of the component I'm creating the socket:
```
 const ws = new WebSocket('ws:localhost:8080');
    ws.on('open', function() {
      ws.send('something');
    });
    ws.on('message', function(message) {
      console.log('received: %s', message);
    });
```
My assumption is that crypto module is not loaded into angular project.

**Comment by lpinca** [comment]
In the browser you have to use the native WebSocket object.
There is no way to get access to a raw TCP socket so there is no way to "browserify" ws.
