### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by robertmylne** [websockets/ws#1055]
1. Does this re-establish a connection if it drops?
2. If 1 is re-established does it queue messages while the connection is down and resend them once it becomes available again?
3.  Does it send heartbeats to keep the connection alive so that firewalls and such don't disconnect it?

**Comment by lpinca** [comment]
The answer is no to all questions.

**Comment by 3rd-Eden** [comment]
What you are looking for is https://github.com/primus/primus which adds all your requested functionality on top of websockets and any other realtime framework.

**Comment by slidenerd** [comment]
I dont mean to be rude but primus is seriously super bloated for a simple task such as reconnecting
