### ISSUE TITLE
Where are client information stored?

### ISSUE THREAD

**Issue by dynek** [websockets/ws#1058]
Hello,

First of all thanks for the great work!

I have recently updated an "old" app from node 0.12 to 6.x.

I was using ws.clients.length to know if any client was currently connected (instead of incrementing a counter upon connection) but it now returns undefined.

In package.json, I did not mention any specific version of ws to use in the dependencies. So I'm unfortunately unable to tell which version I was using when this was working.

Did this vanish or move somewhere else?

Thanks a bunch!

**Comment by lpinca** [comment]
`ws.clients` is no longer an array but a set in version 2.x so you can achieve the same by using `ws.clients.size`.

**Comment by dynek** [comment]
Really appreciate it @lpinca - I was able to fix my app!
