### ISSUE TITLE
Secure websocket

### ISSUE THREAD

**Issue by wcoebergh** [websockets/ws#1061]
Is it possible to create a secure websocket with certificate? (wss://)

If so, please let me know how. I was unable to find it in the docs.

If not, is there another client that can?

Regards

**Comment by lpinca** [comment]
See https://github.com/websockets/ws/blob/master/doc/ws.md#new-websocketaddress-protocols-options.

**Comment by lpinca** [comment]
If you want to create a secure server instead, you have to create a HTTPS server as specified here https://nodejs.org/dist/latest-v7.x/docs/api/https.html#https_https_createserver_options_requestlistener and pass that server as an option to the WebSocket server constructor.

**Comment by wcoebergh** [comment]
Would something like this be correct:

var key = {
	key: fs.readFileSync('path/to/key/key.pem'),
	cert: fs.readFileSync(path/to/cert/cert.pem')
};

var options = {
	port: 8080,
	verifyClient: someVerifyFunction,
	agent: new http.Agent(key)
}

var wss = new WebSocketServer(options);

**Comment by wcoebergh** [comment]
Or should it be:

var options = {
port: 8080,
verifyClient: someVerifyFunction,
agent: new http.Agent()
key: fs.readFileSync('path/to/key/key.pem'),
cert: fs.readFileSync(path/to/cert/cert.pem')
}

var wss = new WebSocketServer(options);

**Comment by wcoebergh** [comment]
I don't know if you can leave the agent options without entering certificate files?

**Comment by lpinca** [comment]
You are mixing client and server stuff.
See this test https://github.com/websockets/ws/blob/master/test/WebSocketServer.test.js#L601-L625 maybe it helps.

**Comment by wcoebergh** [comment]
Ah I see now, thanks for pointing out my mistake, and thanks for the link. However, the syntax seems weird, am I missing something? see below code:

const server = https.createServer({
        cert: fs.readFileSync('test/fixtures/certificate.pem'),
        key: fs.readFileSync('test/fixtures/key.pem')
});

const wsserver = new WebSocketServer({
	verifyClient: (info) => {
		success = info.secure === true;
		return true;
	},
	<MISSING_KEY?>: server
});

**Comment by lpinca** [comment]
Yes, in ES6 `{ foo }` is equivalent to `{ foo: foo }`.

**Comment by wcoebergh** [comment]
Cool, did not know that yet! Thanks for the support/help! Appreciate the work
