### ISSUE TITLE
Received messages are corrupted

### ISSUE THREAD

**Issue by zdila** [websockets/ws#1063]
After upgrding from 1.1.4 to 2.2.3 we are often getting corrupted messages with ws as websocket client. Such messages start with some binary data and are truncated. We are connectiong to [Janus](https://janus.conf.meetecho.com/) and it uses Libwebsockets version: 2.0.3.

Sample of single full message where valid JSON was expected:
```
�~�{
   "janus": "success",
   "session_id": 6223375661722642,
   "transaction": "bf054e78-27ae-4ca9-a9bd-9bbc8bdd00cc",
   "data": {
      "id": 8870118644590313
```

Version of Node is v6.10.2 and it is running on 4.6.0-1-amd64 #1 SMP Debian 4.6.4-1 (2016-07-18) x86_64 GNU/Linux.

**Comment by lpinca** [comment]
Is there an easy way to reproduce the issue?

**Comment by zdila** [comment]
Yes, we can easily reproduce it.

**Comment by lpinca** [comment]
Yes, I mean can you create a reproducible test case and share it? So we can investigate.

**Comment by zdila** [comment]
OK

**Comment by zdila** [comment]
Because of this issue we had to downgrade ws to 1.1.4. But now after upgrading it back from 1.1.4 to 2.2.3 to create a testcase we are no longer getting corrupted messages :-o.

**Comment by lpinca** [comment]
This is weird :) Please keep us posted.

**Comment by lpinca** [comment]
@zdila any updates here?

**Comment by zdila** [comment]
@lpinca I couldn't reproduce it anymore. Feel free to close this issue and I'll open a new one if I will be able to reproduce it reliably.
