### ISSUE TITLE
Using SSL

### ISSUE THREAD

**Issue by BamItsPixel** [websockets/ws#1067]
Hello- amazing library but I can't seem to find anything about SSL in the documentation (in your MD file).

How could I host a WSS server instead of a WS server?

I've loaded my certificates into strings- is it possible to pass them on as options or something?

Thank you!

**Comment by OrangeChaten** [comment]
This would be great! I would love it if you implemented this.

**Comment by euroclydon37** [comment]
[Here](http://www.giacomovacca.com/2015/02/websockets-over-nodejs-from-plain-to.html) is an article that I'm going to try and mimic today for this purpose.

It really would be nice to have this implemented into the library itself. It's otherwise a fantastic library.

**Comment by lpinca** [comment]
1. Create an HTTPS server as described here: https://nodejs.org/dist/latest-v7.x/docs/api/https.html#https_https_createserver_options_requestlistener

2. Pass that server to the WebSocket server constructor. This test https://github.com/websockets/ws/blob/a4cc55d1c707e1515bfdba6da357231443454b39/test/WebSocketServer.test.js#L602-L624 works as an example.

**Comment by BamItsPixel** [comment]
Ah. Thank you very much! That's convenient because I already create a HTTPS server a few lines up.
