### ISSUE TITLE
How To Use Client Library In Browser?

### ISSUE THREAD

**Issue by HomeboxJim** [websockets/ws#1069]
Hi, I'm trying to use the client library in the browser, but I'm getting tripped up by the "require" syntax. How do I fix this error message? 

> Uncaught ReferenceError: require is not defined

**Comment by rodel77** [comment]
I client side you can use this:

`var socket = new WebSocket('ws://ip:port')`

Its vanilla JS then handle events with: `socket.onopen socket.onclose socket.onerror socket.onmessage = callback`

**Comment by LordMajestros** [comment]
The client library is not for use in the browser. Modern up to date browsers come with their own Websocket Object you can use to create connections. The client library is for use in node.js to create client connections to your server for testing or other purposes.

**Comment by HomeboxJim** [comment]
Thanks @rodel77, but it's not working for me. The callback functions are never fired. :/

var ws = new WebSocket('ws://120.0.0.1:8889');


function connectToServer() {

  console.log('connecting to server...');

  ws.onopen = function open() {

    console.log('connected to server!')

  };

  ws.onmessage = function incoming(data, flags) {

    console.log('got a message! ' + JSON.stringify(data));

**Comment by HomeboxJim** [comment]
Server:

Last login: Wed Apr  5 11:51:51 on ttys001
client (master) ♘ cd ../server/
.idea/                 room-walker-server.js  server.js              
client (master) ♘ cd ../server/
server (master) ♘ nodie room-walker-server.js 
-bash: nodie: command not found
server (master) ♘ node room-walker-server.js 
module.js:471
    throw err;
    ^

Error: Cannot find module 'ws'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/jlynch/Github/Room-Walkers/server/room-walker-server.js:1:81)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
server (master) ♘ npm init
This utility will walk you through creating a package.json file.
It only covers the most common items, and tries to guess sensible defaults.

See `npm help json` for definitive documentation on these fields
and exactly what they do.

Use `npm install <pkg> --save` afterwards to install a package and
save it as a dependency in the package.json file.

Press ^C at any time to quit.
name: (server) room-walker-server
version: (1.0.0) 0.0.1
description: 
entry point: (server.js) room-walker-server.js
test command: 
git repository: 
keywords: 
author: 
license: (ISC) GPL-3.0
About to write to /Users/jlynch/Github/Room-Walkers/server/package.json:

{
  "name": "room-walker-server",
  "version": "0.0.1",
  "description": "",
  "main": "room-walker-server.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "node server.js"
  },
  "author": "",
  "license": "GPL-3.0"
}


Is this ok? (yes) 
server (master) ♘ npm i ws --save
room-walker-server@0.0.1 /Users/jlynch/Github/Room-Walkers/server
└─┬ ws@2.2.3 
  ├── safe-buffer@5.0.1 
  └── ultron@1.1.0 

npm WARN room-walker-server@0.0.1 No description
npm WARN room-walker-server@0.0.1 No repository field.
server (master) ♘ node room-walker-server.js 
server listening...
^C
server (master) ♘ vim room-walker-server.js 
server (master) ♘ node room-walker-server.js 
server listening...
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EACCES 0.0.0.0:443
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at Server._listen2 (net.js:1246:19)
    at listen (net.js:1295:10)
    at net.js:1405:9
    at _combinedTickCallback (internal/process/next_tick.js:77:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
server (master) ♘ lsof -i :443
COMMAND     PID   USER   FD   TYPE            DEVICE SIZE/OFF NODE NAME
Microsoft  1052 jlynch   24u  IPv4 0xc61cfcacc600c01      0t0  TCP 10.182.243.229:50425->206.208.179.53:https (CLOSE_WAIT)
Microsoft  1052 jlynch   46u  IPv4 0xc61cfcacc600c01      0t0  TCP 10.182.243.229:50425->206.208.179.53:https (CLOSE_WAIT)
Microsoft  1052 jlynch   50u  IPv4 0xc61cfcac64866e9      0t0  TCP 10.182.243.229:50426->getmail.hbo.com-vip-east.tw.tweis.net:https (CLOSED)
Microsoft  1052 jlynch   67u  IPv4 0xc61cfcac64866e9      0t0  TCP 10.182.243.229:50426->getmail.hbo.com-vip-east.tw.tweis.net:https (CLOSED)
AtHoc\x20  5513 jlynch    9u  IPv4 0xc61cfcac929ddf1      0t0  TCP 10.182.243.229:49268->216.3.22.14:https (ESTABLISHED)
AtHoc\x20  5513 jlynch   10u  IPv4 0xc61cfcac929ddf1      0t0  TCP 10.182.243.229:49268->216.3.22.14:https (ESTABLISHED)
Google    61418 jlynch   77u  IPv4 0xc61cfcadf18d6e9      0t0  TCP 10.182.243.229:63124->qt-in-f188.1e100.net:https (ESTABLISHED)
Google    61418 jlynch   80u  IPv4 0xc61cfcacc2cfdf1      0t0  TCP 10.182.243.229:49378->lga34s11-in-f14.1e100.net:https (ESTABLISHED)
Google    61418 jlynch   85u  IPv4 0xc61cfcac67d7df1      0t0  TCP 10.182.243.229:65074->lga34s11-in-f14.1e100.net:https (ESTABLISHED)
Google    61418 jlynch   98u  IPv4 0xc61cfcae0fa86e9      0t0  TCP 10.182.243.229:49490->120.0.0.1:https (SYN_SENT)
Google    61418 jlynch   99u  IPv4 0xc61cfcac4bf18d9      0t0  TCP 10.182.243.229:64909->lga34s11-in-f14.1e100.net:https (ESTABLISHED)
Google    61418 jlynch  100u  IPv4 0xc61cfcac5113fe1      0t0  TCP 10.182.243.229:64913->192.30.253.125:https (ESTABLISHED)
Google    61418 jlynch  105u  IPv4 0xc61cfcac5ef2309      0t0  TCP 10.182.243.229:54687->edge-star-shv-01-lga3.facebook.com:https (ESTABLISHED)
Google    61418 jlynch  162u  IPv4 0xc61cfcae1021df1      0t0  TCP 10.182.243.229:64912->151.101.20.133:https (ESTABLISHED)
Google    61418 jlynch  202u  IPv4 0xc61cfcac67b44f9      0t0  TCP 10.182.243.229:60763->151.101.20.133:https (ESTABLISHED)
Google    61418 jlynch  204u  IPv4 0xc61cfcac67fadf1      0t0  TCP 10.182.243.229:60768->192.30.253.125:https (ESTABLISHED)
Google    61418 jlynch  207u  IPv4 0xc61cfcae0fd88d9      0t0  TCP 10.182.243.229:58313->stackoverflow.com:https (ESTABLISHED)
Google    61418 jlynch  211u  IPv4 0xc61cfcacc3878d9      0t0  TCP 10.182.243.229:61908->192.30.253.125:https (ESTABLISHED)
Google    61418 jlynch  218u  IPv4 0xc61cfcae0f6f309      0t0  TCP 10.182.243.229:61826->151.101.20.133:https (ESTABLISHED)
Google    61418 jlynch  221u  IPv4 0xc61cfcac92acfe1      0t0  TCP 10.182.243.229:60656->151.101.20.133:https (ESTABLISHED)
Google    61418 jlynch  239u  IPv4 0xc61cfcac929c309      0t0  TCP 10.182.243.229:64529->lga34s11-in-f14.1e100.net:https (ESTABLISHED)
Google    61418 jlynch  251u  IPv4 0xc61cfcacb1044f9      0t0  TCP 10.182.243.229:57640->lga34s11-in-f14.1e100.net:https (ESTABLISHED)
Google    61418 jlynch  298u  IPv4 0xc61cfcadf1f64f9      0t0  TCP 10.182.243.229:58351->stackoverflow.com:https (ESTABLISHED)
Google    61418 jlynch  299u  IPv4 0xc61cfcac92abdf1      0t0  TCP 10.182.243.229:65224->lga25s61-in-f14.1e100.net:https (ESTABLISHED)
Google    61418 jlynch  310u  IPv4 0xc61cfcac5d7e6e9      0t0  TCP 10.182.243.229:61846->192.30.253.125:https (ESTABLISHED)
Google    61418 jlynch  317u  IPv4 0xc61cfcac93c44f9      0t0  TCP 10.182.243.229:58345->stackoverflow.com:https (ESTABLISHED)
Google    61418 jlynch  333u  IPv4 0xc61cfcac4780c01      0t0  TCP 10.182.243.229:58359->stackoverflow.com:https (ESTABLISHED)
Google    61418 jlynch  356u  IPv4 0xc61cfcaca4216e9      0t0  TCP 10.182.243.229:60658->151.101.20.133:https (ESTABLISHED)
Google    61418 jlynch  363u  IPv4 0xc61cfcac517afe1      0t0  TCP 10.182.243.229:62110->192.30.253.124:https (ESTABLISHED)
Google    61418 jlynch  376u  IPv4 0xc61cfcacc6264f9      0t0  TCP 10.182.243.229:54169->edge-star-mini-shv-01-lga3.facebook.com:https (ESTABLISHED)
Slack     61446 jlynch   44u  IPv4 0xc61cfcae1020309      0t0  TCP 10.182.243.229:56261->server-52-84-94-170.yul62.r.cloudfront.net:https (CLOSED)
Slack     61446 jlynch   62u  IPv4 0xc61cfcacc6646e9      0t0  TCP 10.182.243.229:57772->ec2-54-165-249-88.compute-1.amazonaws.com:https (ESTABLISHED)
Slack     61446 jlynch   71u  IPv4 0xc61cfcac4a8f309      0t0  TCP 10.182.243.229:56242->tps2.jfk.hv.prod:https (CLOSED)
Slack     61446 jlynch   72u  IPv4 0xc61cfcae0f5bdf1      0t0  TCP 10.182.243.229:56243->151.101.20.84:https (CLOSED)
Slack     61446 jlynch   73u  IPv4 0xc61cfcacc6456e9      0t0  TCP 10.182.243.229:56244->server-52-84-90-177.yul62.r.cloudfront.net:https (CLOSED)
Slack     61446 jlynch   74u  IPv4 0xc61cfcac646edf1      0t0  TCP 10.182.243.229:56245->151.101.20.65:https (CLOSED)
Slack     61446 jlynch   75u  IPv4 0xc61cfcadf7c86e9      0t0  TCP 10.182.243.229:56246->https-69-164-36-41.lga.llnw.net:https (CLOSED)
Slack     61446 jlynch   77u  IPv4 0xc61cfcacd568309      0t0  TCP 10.182.243.229:56248->8.27.232.251:https (CLOSED)
Slack     61446 jlynch   81u  IPv4 0xc61cfcae1044fe1      0t0  TCP 10.182.243.229:56249->8.253.47.231:https (CLOSED)
Slack     61446 jlynch   83u  IPv4 0xc61cfcae10b7fe1      0t0  TCP 10.182.243.229:56251->151.101.20.102:https (CLOSED)
Google    63170 jlynch   12u  IPv4 0xc61cfcadf7af309      0t0  TCP 10.182.243.229:56136->ec2-107-23-53-233.compute-1.amazonaws.com:https (CLOSED)
Google    63170 jlynch  115u  IPv4 0xc61cfcae103cfe1      0t0  TCP 10.182.243.229:56060->ec2-107-23-53-233.compute-1.amazonaws.com:https (CLOSED)
Google    63170 jlynch  116u  IPv4 0xc61cfcae0f70df1      0t0  TCP 10.182.243.229:56063->*.122.2o7.net:https (ESTABLISHED)
Google    63170 jlynch  118u  IPv4 0xc61cfcadf162df1      0t0  TCP 10.182.243.229:56066->ec2-34-195-171-138.compute-1.amazonaws.com:https (CLOSED)
Google    63170 jlynch  119u  IPv4 0xc61cfcae10a96e9      0t0  TCP 10.182.243.229:56067->ec2-34-195-171-138.compute-1.amazonaws.com:https (CLOSED)
Google    63170 jlynch  125u  IPv4 0xc61cfcadf1524f9      0t0  TCP 10.182.243.229:56076->8.247.98.119:https (CLOSED)
Google    63170 jlynch  132u  IPv4 0xc61cfcacb274c01      0t0  TCP 10.182.243.229:56122->8.247.98.119:https (CLOSED)
Google    63170 jlynch  139u  IPv4 0xc61cfcacb129309      0t0  TCP 10.182.243.229:56103->*.122.2o7.net:https (ESTABLISHED)
Google    63170 jlynch  143u  IPv4 0xc61cfcac1f3cdf1      0t0  TCP 10.182.243.229:56123->8.247.98.119:https (CLOSED)
Google    63170 jlynch  149u  IPv4 0xc61cfcacc6196e9      0t0  TCP 10.182.243.229:62796->lga34s11-in-f14.1e100.net:https (CLOSED)
Spotify   64228 jlynch   63u  IPv4 0xc61cfcadf2856e9      0t0  TCP 10.182.243.229:59910->ash2-accesspoint-a45.ash2.spotify.com:https (ESTABLISHED)
Spotify   64228 jlynch  108u  IPv4 0xc61cfcacb104df1      0t0  TCP 10.182.243.229:55507->a104-97-118-227.deploy.static.akamaitechnologies.com:https (CLOSED)
Spotify   64228 jlynch  112u  IPv4 0xc61cfcac47838d9      0t0  TCP 10.182.243.229:55509->a104-97-118-227.deploy.static.akamaitechnologies.com:https (CLOSED)
Spotify   64228 jlynch  113u  IPv4 0xc61cfcac5ed14f9      0t0  TCP 10.182.243.229:55511->ec2-107-22-236-230.compute-1.amazonaws.com:https (CLOSED)
Spotify   64228 jlynch  124u  IPv4 0xc61cfcae10214f9      0t0  TCP 10.182.243.229:55530->ec2-50-17-177-105.compute-1.amazonaws.com:https (CLOSED)
Spotify   64228 jlynch  126u  IPv4 0xc61cfcacc659df1      0t0  TCP 10.182.243.229:55532->69.172.216.111:https (CLOSED)
Spotify   64228 jlynch  127u  IPv4 0xc61cfcae0f74df1      0t0  TCP 10.182.243.229:55537->208.185.50.90.ipyx-063360-004-zyo.zip.zayo.com:https (ESTABLISHED)
Spotify   64228 jlynch  128u  IPv4 0xc61cfcadf4b3df1      0t0  TCP 10.182.243.229:55538->208.185.50.90.ipyx-063360-004-zyo.zip.zayo.com:https (ESTABLISHED)
server (master) ♘ vim room-walker-server.js 
server (master) ♘ node room-walker-server.js 
server listening...
^C
server (master) ♘ 
server (master) ♘ vim room-walker-server.js 

```
const WebSocket = require('ws');
const util = require('util');  

const wss = new WebSocket.Server({ port: 8889 });
```

**Comment by rodel77** [comment]
I dont know if this care but try to add connection listener to server

wss.on('connnection', (client) => {})

**Comment by LordMajestros** [comment]
Are you doing this on your computer or you are connecting to a remote server?
If remote then make sure 120.0.0.1:8889 is the right ip:port if on your computer use localhost 127.0.0.1:8889

```
wss.on('connnection', function(client){
//do something with client here
});
```

**Comment by HomeboxJim** [comment]
@LordMajestros - Hmm it's saying, "wss.on is not a function"

**Comment by rodel77** [comment]
Are you sure you are calling the WebSocket.Server var like this?

```
const wss = new WebSocket.Server({ port: 8889 });

wss.on('connection', (client) => {
	console.log(client);
});
```

**Comment by HomeboxJim** [comment]
On the server I am, but the problem I'm having in in the client code.

**Comment by rodel77** [comment]
And "WebSocket" var in client its called wws?
In the example i put first is `var socket = new WebSocket('ws://ip:port')` then you have to use `socket.onopen = function(){console.log('Callback')};`

**Comment by HomeboxJim** [comment]
Ah, I think I was entering the ip address wrong. *facepalm*

Thanks @rodel77. The syntax you gave me is working. 👍
