### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by jaimehrubiks** [websockets/ws#1071]
Hi, thanks for your time, I need to know 2 little things about this lib.

1) Is this library standard compilant? I mean, would I be able to connect with a client written in other language with other lib?

2) Can I save session data with something like:
```
ws.user = username
```
so that then I can find sessions for that specific user like:
```js
wss.clients.forEach(function each(client) {
   if (client.user == username && client.readyState === WebSocket.OPEN) {
        client.send(data);
   }
});
```
thanks in advance

**Comment by lpinca** [comment]
> 1. Is this library standard compilant? I mean, would I be able to connect with a client written in other language with other lib?

Yes.

> 2. Can I save session data with something like:

Yes.

**Comment by jaimehrubiks** [comment]
Thanks for your fast response.
