### ISSUE TITLE
Const declaration in strict mode

### ISSUE THREAD

**Issue by Starillusion** [websockets/ws#1077]
Your libraries all seem to to declare 'use strict' then declare variables (directly afterwards!) with 'const'.
This is causing my server application to crash with this error: "SyntaxError: Use of const in strict mode"
There's also a library or two that use the word "class". Node.JS does **not** like this and throws an error " reserved word". I don't know if other users are having problems with this, but please create a branch with the problems I listed above fixed (replace 'const' declarations with 'var', or figure out how to not have to use strict mode in your libraries.) I hope this fixes other users' problems along with mine....

**Comment by lpinca** [comment]
`ws@2` only works in Node.js >= 4.0.0. If you can't update you Node.js version use `ws@1`.

**Comment by Starillusion** [comment]
Interesting...

**Comment by Starillusion** [comment]
But why?

**Comment by Starillusion** [comment]
Also, where do you get v1?

**Comment by lpinca** [comment]
> But why?

Node.js 0.10 and 0.12 reached EOL. 

> Also, where do you get v1?

```
npm install ws@1
```

**Comment by Starillusion** [comment]
Never knew NPM could install different versions of a module, always thought it installed only the latest version
