### ISSUE TITLE
[HELP] Get Buffer instead of string from onmessage

### ISSUE THREAD

**Issue by lifaon74** [websockets/ws#1079]
In the documentation, it says that we can get Buffer and/or string when using : 
```js
socket.on('message', (data) => {
  console.log(data);
});
```
But I only get string even if I set `websocket.binaryType = "arraybuffer" or "nodebuffer"`. This result in improper encoding sometimes. For example, if I send an `String.fromCharCode(129) ` from the browser, the encoding type could be wrong.

Is there any way to get raw binary data as Buffer ?

Thanks for your answer.

**Comment by lpinca** [comment]
The other peer should send a binary frame. If you get a string it means that you are receiving a text frame.

**Comment by lifaon74** [comment]
Ok thanks to you. I post here an anwser if it could help others : 

```js
/** CLIENT SIDE **/
socket.binaryType = 'arraybuffer'; // to receive arraybuffer instead of blob
// https://developer.mozilla.org/en-US/docs/Web/API/TextEncoder
socket.send(new TextEncoder().encode('some string with special chars : 😁'))
// https://developer.mozilla.org/en-US/docs/Web/API/TextDecoder => to decode
```
