### ISSUE TITLE
API does not conform to official WebSocket API?

### ISSUE THREAD

**Issue by lll000111** [websockets/ws#1084]
For events like `message` the official API document says:

https://html.spec.whatwg.org/multipage/comms.html#messageevent

Or on MDN: https://developer.mozilla.org/de/docs/Web/API/MessageEvent

But WS does not send an object to the event handler.

https://github.com/websockets/ws/blob/master/lib/WebSocket.js#L146

**Comment by lpinca** [comment]
You can also use the [`EventTarget`](https://github.com/websockets/ws/blob/master/lib/EventTarget.js) interface.

See https://github.com/websockets/ws/blob/master/doc/ws.md#websocketonmessage.

**Comment by lll000111** [comment]
So when I use `onmessage` the callback gets an object with a `data` property?

Background for my question is that I argued with the uWebSockets maintainer [over an issue I had opened](https://github.com/uWebSockets/bindings/issues/13)...

**Comment by lpinca** [comment]
> So when I use onmessage the callback gets an object with a data property?

Yes, correct.

**Comment by lpinca** [comment]
Quick example:

```js
const WebSocket = require('ws');

const wss = new WebSocket.Server({ port: 3000 }, () => {
  const ws = new WebSocket('ws://localhost:3000');

  ws.onmessage = function (evt) {
    console.log('client received data: %s', evt.data);
  };

  ws.onopen = function () {
    ws.send('foo');
  };
});

wss.on('connection', (ws) => {
  ws.onmessage = function (evt) {
    console.log('server received data: %s', evt.data);
    ws.send(evt.data);
  };
});
```

**Comment by lll000111** [comment]
Thank you! I'm trying it out just now.  So if that is so it seems to me that -- see the ticket over at uws that I linked above ([link](https://github.com/uWebSockets/bindings/issues/13)) -- alexhultman, who even threatened to ban me, is incorrect in saying his uws package behaves like ws, and that ws behaves according to the standard.

**Comment by lpinca** [comment]
@lll000111 I understand your point but there isn't a

```js
ws.on('message', callback);
```

in the browser so that doesn't follow the browser interface and use the Node.js "style" instead.
It's up to the user what interface to use. Like you said the two interfaces behaves differently.

P.S. I've also been banned by Alex in the past, nothing new :smile: .

**Comment by lll000111** [comment]
Ahhhhhh... oh yes, the `on`method. I completely overlooked that. Anyway, I'll switch to 'ws'  now because I don't want to use a package where I'm threatened with expulsion over nothing. Any potential gain in speed isn't worth losing any form of support, including even that I can't even submit pull requests.

**Comment by lpinca** [comment]
Unless I'm missing something I think he is correct, it works "like" `ws` but instead of using dedicated [constructors](https://github.com/websockets/ws/blob/732aaf06b76700f104eeff2740e1896be4e88199/lib/EventTarget.js#L27-L41) he use plain JS objects.

**Comment by lll000111** [comment]
Yeah I noticed that, looking at your code and the `class` you use for the message. Is that actually necessary?

**Comment by lpinca** [comment]
Probably not but that pre dates me (https://github.com/websockets/ws/pull/920).
