### ISSUE TITLE
Notify when client closes a connection from server

### ISSUE THREAD

**Issue by nodesocket** [websockets/ws#1088]
Is there a way to notify from the server when a client closes a connection?

Tried:

````javascript
wss.on('close', () => {
    console.info(color.green(`Current Connections: ${wss.clients.size}`));
});
````

But that did not work.

**Comment by lpinca** [comment]
No, but you can do it yourself with something like this:

```js
wss.on('connection', (ws) => {
  ws.on('close', () => wss.emit('disconnection', ws));
});
```

**Comment by nodesocket** [comment]
Worked. Thanks.

**Comment by vladyn** [comment]
In the given an example - how can I send to the rest of the clients that one has left? 
"ws.emit" send the message where? 
In my scenario (which is pretty trivial) I have: 

`WS_SERVER.on('request', request => {
    const connection = request.accept('echo-protocol', request.origin);
    console.log((new Date()) + ' Connection accepted.');

    // Broadcast incoming messages back to other connections on channel
    // First connection to send a JOIN_CHANNEL message, creates the channel
    connection.on('message', (data) => {
        const { message, channelName, meta = {} } = JSON.parse(data.utf8Data);

        console.log((new Date()) + ' Peer ' + connection.remoteAddress + ' connected.');

        Array.from(channel.connections)
            .filter(con => con !== connection)
            .forEach(con => con.send(JSON.stringify({
                    message, meta,
                    channel: {
                        size: channel.connections.size,
                        name: channelName
                    }
                }
            )));
    });

    connection.on('close', (...data) => {
      console.log(`Connection closed with the following data: ${data}`);
        console.log((new Date()) + ' Peer ' + connection.remoteAddress + ' disconnected.');
    });
});;`

I can't see where to send to the channel with other clients a left message?

**Comment by rgawenda** [comment]
> In my scenario (which is pretty trivial) I have:
...
> I can't see where to send to the channel with other clients a left message?

This doesn't seem an issue, so you sould better ask in StackOverflow. Anyway, I can't see where you're tracking your connections (channel.connections?). In the README there's a quite clear example of a broadcast.
