### ISSUE TITLE
ws host information and id

### ISSUE THREAD

**Issue by nodesocket** [websockets/ws#1089]
Two questions. From the server, is there a way to get the host ip of a client connection? Second do client connections have an internal id or a reference hash or number?

```javascript
wss.on('connection', (ws) => {
     // is the client host ip in the ws object?
     // is there an id or reference number for the ws object?
});
```

**Comment by lpinca** [comment]
> From the server, is there a way to get the host ip of a client connection?

```js
wss.on('connection', (ws) => {
  const ip = ws.upgradeReq.connection.remoteAddress;
  // Use the `X-Forwarded-For` header if your server is behind a proxy.
});
```

> do client connections have an internal id or a reference hash or number?

No, it's up to you to assign and id to the objects. You could use the `sec-websocket-key` header as id but I wouldn't do that as it's value is generated by the client.

**Comment by nodesocket** [comment]
Heads up, in `v3.0.0` getting the host ip of a client connection has changed from `ws.upgradeReq.connection.remoteAddress` to:

    **req.connection.remoteAddress**
