### ISSUE TITLE
throw error in on 'message' cause message send lost

### ISSUE THREAD

**Issue by narychen** [websockets/ws#1092]
```
wss.on('connection', function connection(ws) {
  ws.on('message', function incoming(message) {
    throw new Error('An error without catch')
  });

  ws.send('something');
});
```
If you don't catch the error thrown in the block, the messages send afterwards will get messed up.
Seems like some data is not been sent during the error thrown and it will be sent in the next turn.
But the proto sequence will be wrong as you will get some weird characters at beginning of a json like ' �~�{"proto":"notify",.......}

**Comment by lpinca** [comment]
Can you create a test case to reproduce the issue?

**Comment by narychen** [comment]
```
const http = require('http');
const ws = require('ws');
const readline = require("readline");

process.on('uncaughtException', function (e) {
  console.error(e.stack);
});

var server = http.createServer();
server.listen(8888, ()=>{
  (new ws.Server({server})).on('connection', (ws)=>{
    ws.on('message', (data)=>{
      console.log('ws: ', data);
      throw new Error('fffff'); // The proto will be abnormal after this 
      ws.send(JSON.stringify({proto:'res', data:'res ok'}));
    });
  });
  wsc.on('close', (code, message)=>{
    console.log('server close', code, message);
  });
  wsc.on('error', (error)=>{
    console.log('server error', error);
  });
});

var wsc = new ws(`ws://127.0.0.1:8888/`);
wsc.on('open', ()=>{
  console.log('client open');

});
wsc.on('message', (data, flags)=>{
  console.log('wsc: ', data);
});
wsc.on('close', (code, message)=>{
  console.log('client close', code, message);
});
wsc.on('error', (error)=>{
  console.log('client error', error);
});

var rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout
});

rl.question('', function shell(data) {
  try {
    wsc.send(JSON.stringify({
      proto: 'req', data
    }));
  } catch(err) {
    console.log(err);
  } finally {
    rl.question('', shell);
  }
});
```
A simple demo to reproduce this issue.
You will see the output
```
client open
kk
ws:  {"proto":"req","data":"kk"}
Error: fffff
    at WebSocket.ws.on (/home/ubuntu/code/node-talk/node_test/wsThrow.js:14:13)
    at emitTwo (events.js:106:13)
    at WebSocket.emit (events.js:191:7)
    at Receiver._receiver.onmessage (/home/ubuntu/code/node-talk/node_modules/ws/lib/WebSocket.js:146:54)
    at Receiver.dataMessage (/home/ubuntu/code/node-talk/node_modules/ws/lib/Receiver.js:389:14)
    at Receiver.getData (/home/ubuntu/code/node-talk/node_modules/ws/lib/Receiver.js:330:12)
    at Receiver.startLoop (/home/ubuntu/code/node-talk/node_modules/ws/lib/Receiver.js:165:16)
    at Receiver.add (/home/ubuntu/code/node-talk/node_modules/ws/lib/Receiver.js:139:10)
    at Socket._ultron.on (/home/ubuntu/code/node-talk/node_modules/ws/lib/WebSocket.js:142:22)
    at emitOne (events.js:96:13)
sdf
┌�4  │┌�└N▒�≤┬�←N┘�±N4�⎼
E⎼⎼⎺⎼: °°°°°
    ▒├ WebS⎺c┐e├↓┬⎽↓⎺┼ (/▒⎺└e/┤b┤┼├┤/c⎺de/┼⎺de↑├▒┌┐/┼⎺de_├e⎽├/┬⎽T▒⎼⎺┬↓┘⎽:14:13)
    ▒├ e└☃├T┬⎺ (e┴e┼├⎽↓┘⎽:1▮6:13)
    ▒├ WebS⎺c┐e├↓e└☃├ (e┴e┼├⎽↓┘⎽:191:7)
    ▒├ Rece☃┴e⎼↓_⎼ece☃┴e⎼↓⎺┼└e⎽⎽▒±e (/▒⎺└e/┤b┤┼├┤/c⎺de/┼⎺de↑├▒┌┐/┼⎺de_└⎺d┤┌e⎽/┬⎽/┌☃b/WebS⎺c┐e├↓┘⎽:146:54)
    ▒├ Rece☃┴e⎼↓d▒├▒Me⎽⎽▒±e (/▒⎺└e/┤b┤┼├┤/c⎺de/┼⎺de↑├▒┌┐/┼⎺de_└⎺d┤┌e⎽/┬⎽/┌☃b/Rece☃┴e⎼↓┘⎽:389:14)
    ▒├ Rece☃┴e⎼↓±e├D▒├▒ (/▒⎺└e/┤b┤┼├┤/c⎺de/┼⎺de↑├▒┌┐/┼⎺de_└⎺d┤┌e⎽/┬⎽/┌☃b/Rece☃┴e⎼↓┘⎽:33▮:12)
    ▒├ Rece☃┴e⎼↓⎽├▒⎼├L⎺⎺⎻ (/▒⎺└e/┤b┤┼├┤/c⎺de/┼⎺de↑├▒┌┐/┼⎺de_└⎺d┤┌e⎽/┬⎽/┌☃b/Rece☃┴e⎼↓┘⎽:165:16)
    ▒├ Rece☃┴e⎼↓▒dd (/▒⎺└e/┤b┤┼├┤/c⎺de/┼⎺de↑├▒┌┐/┼⎺de_└⎺d┤┌e⎽/┬⎽/┌☃b/Rece☃┴e⎼↓┘⎽:139:1▮)
    ▒├ S⎺c┐e├↓_┤┌├⎼⎺┼↓⎺┼ (/▒⎺└e/┤b┤┼├┤/c⎺de/┼⎺de↑├▒┌┐/┼⎺de_└⎺d┤┌e⎽/┬⎽/┌☃b/WebS⎺c┐e├↓┘⎽:142:22)
    ▒├ e└☃├O┼e (e┴e┼├⎽↓┘⎽:96:13)
⎽d°
┬⎽:  �Q���Q���9��ϜM─��؂

```

**Comment by narychen** [comment]
My node.js version is v6.10.2

**Comment by lpinca** [comment]
Thanks. The problem is that the thrown error prevents the parser state from being updated. This [assignment](https://github.com/websockets/ws/blob/d75ab9dc91e98673a9fcfdf585d5a0c8cfc48e99/lib/Receiver.js#L393) is not done so the next frame is incorrectly parsed.

I think this should be handled in the application code. An synchronous error in a listener should either be wrapped in a `try...catch` or crash the process.

cc: @websockets/admin

**Comment by lpinca** [comment]
https://nodejs.org/dist/latest-v7.x/docs/api/process.html#process_warning_using_uncaughtexception_correctly for reference.

**Comment by narychen** [comment]
I've already added try-catch block in my code after finding this issue.
Put up here just wanna to make sure that if it is a duty of ws package or application code.
I think it may be dangerous if someone don't realize this issue and forget to put a try-catch block in his large on message event handler. Then if something bad happens, they will be very hard to find out what happened.

**Comment by lpinca** [comment]
@narychen yes, thanks for the report and the test case.
The faulty code should crash the process if not wrapped in `try...catch` statement. Relying on `uncaughtException` and resuming operations after it is emitted is not a good idea as documented above.

> The correct use of `'uncaughtException'` is to perform synchronous cleanup of allocated resources (e.g. file descriptors, handles, etc) before shutting down the process. **It is not safe to resume normal operation after `'uncaughtException'`**.

**Comment by lpinca** [comment]
Maybe it makes sense to add a note about this in the docs. Feel free to open a PR.
