### ISSUE TITLE
How to obtain the ip address of the client?

### ISSUE THREAD

**Issue by picarsite** [websockets/ws#1095]
See above.

Thank you

**Comment by tabone** [comment]
Hi @picarsite ,

The HTTP Request the user used to establish a WebSocket connection with your server will be accessible from the user's socket object as documented [here](https://github.com/websockets/ws/blob/master/doc/ws.md#websocketupgradereq).

```javascript
'use strict'

const { Server } = require('ws')

const server = new Server({
  host: '192.168.1.64',
  port: 8080
})

server.on('connection', (socket) => {
  console.log('user ip:', socket.upgradeReq.connection.remoteAddress)
})
```

Hope this helps :)
Luca

**Comment by lpinca** [comment]
@tabone is correct.
Thanks.
