### ISSUE TITLE
I don't receive any errors when sending a message to a client.

### ISSUE THREAD

**Issue by Valen558** [websockets/ws#1096]
```
ws.send("sendData", function ack(error) {
console.log("error="+error);
if(error)console.log("move send error");
}
```

Even when the client does not have an internet connection and cannot receive the message,
the error in ack function is undefined.
What am I doing wrong?

Thanks,
Valentin

**Comment by lpinca** [comment]
The report is a bit vague can you please elaborate?
It's possible that the disconnection is not detected (e.g. when pulling the cord) so technically you still have a "working" connection.

In these cases you have to manually close the connection using something like this:

```js
const WebSocket = require('ws');

const wss = new WebSocket.Server({ port: 8080 });

function heartbeat() {
  this.alive = true;
}

wss.on('connection', (ws) => {
  ws.isAlive = true;
  ws.on('pong', heartbeat);
});

const interval = setInterval(() => {
  wss.clients.forEach((ws) => {
    if (ws.isAlive === false) return ws.terminate();

    ws.isAlive = false;
    ws.ping('', false, true);
  });
}, 30000);
```

**Comment by Valen558** [comment]
Thank you for the prompt response. Yes I am talking exactly about -the pull the cord- types of disconnects. I thought that **send** would throw an error of some kind when sending to a client with cord pulled off.

Now I see how I should deal with this kind of situation with isAlive parameter.

Related question - should I use ws.terminate();
or ws.close();  already does the work at the end of the session with client?

**Comment by lpinca** [comment]
> I thought that send would throw an error of some kind when sending to a client with cord pulled off

Unfortunately there is no proper way to detect this kind of disconnections.

I'd use `ws.terminate()` as that immediately close the connection without trying to send a close frame which is probably what you want in these circumstances. `ws.close()` also works but it waits until the client sends back a close frame. The server waits for 30 sec for this to be received, after that it forcibly closes the connection.

The client will probably be in a similar state when the disconnection can't be detected so you probably need a timer there too.

**Comment by Valen558** [comment]
I found some idea and code that probably helps to detect hard disconnects on client side in browser:

function doesConnectionExist() {
    var xhr = new XMLHttpRequest();
    var file = "your_site.net/contest.pgn";
    var randomNum = Math.round(Math.random() * 10000);
 
    xhr.open('HEAD', file + "?rand=" + randomNum, true);
    xhr.send();
     
    xhr.addEventListener("readystatechange", processRequest, false);
 
    function processRequest(e) {
      if (xhr.readyState == 4) {
        if (xhr.status >= 200 && xhr.status < 304) {
		console.log("connection exists!");
        } else {
	console.log("No Internet Connectioin");
	}
      }
    }
}

It seems to work well  but I am unsure how reliable it is. (Code taken from another place).

**Comment by lpinca** [comment]
Well you don't need that. If you use a heartbeat system similar to the one I posted above you send a special message instead of a ping frame which will be received by the client event `x` seconds. If the client does not receive this message within `y` seconds close the connection.

P.S. ping/pong frames work in the browsers and a pong frame is automatically sent in response to a ping frame. This is per spec.

Hope it makes sense.

**Comment by Valen558** [comment]
Thanks, I see now.

**Comment by lpinca** [comment]
Closing, feel free to continue discussing on the closed thread.

**Comment by xosg** [comment]
> The report is a bit vague can you please elaborate? It's possible that the disconnection is not detected (e.g. when pulling the cord) so technically you still have a "working" connection.
> 
> In these cases you have to manually close the connection using something like this:
> 
> ```js
> const WebSocket = require('ws');
> 
> const wss = new WebSocket.Server({ port: 8080 });
> 
> function heartbeat() {
>   this.isAlive = true;
> }
> 
> wss.on('connection', (ws) => {
>   ws.isAlive = true;
>   ws.on('pong', heartbeat);
> });
> 
> const interval = setInterval(() => {
>   wss.clients.forEach((ws) => {
>     if (ws.isAlive === false) return ws.terminate();
> 
>     ws.isAlive = false;
>     ws.ping('', false, true);
>   });
> }, 30000);
> ```

could you pls implement this?
