### ISSUE TITLE
Enhancements

### ISSUE THREAD

**Issue by lpinca** [websockets/ws#1097]
Following are some possible enhacements that require a major version bump.

- [x] Remove the `upgradeReq` property from the `WebSocket` object and instead pass the `http.IncomingMessage` as the second argument to the `'connection'` event. This reduces memory usage by ~20%.
- [x] Remove the `flags` argument from the `'message'`, `'ping'`, and `'pong'` events. This object is not needed.
- [x] The permessage-deflate extension should be disabled by default due to its overhead on performance and memory comsumption.
- [x] ~~Use symbols for private properties?~~ Prefix all private properties.

**Comment by lpinca** [comment]
@3rd-Eden any opinion on the last two points? Especially permessage-deflate?

I think it's fine to disable it by default on the server but on the client I would keep it enabled by default as it may be used to debug other server and explicitly setting the `perMessageDeflate` option might be developer friendly.

This will create an inconsistency where the option is disabled by default on the server, and enabled by default on the client.

**Comment by 3rd-Eden** [comment]
I'm down for it.
