### ISSUE TITLE
ws.send method should support objects too

### ISSUE THREAD

**Issue by ZaDarkSide** [websockets/ws#1102]
This code works:

```js
ws.send(JSON.stringify({test: 'test'}));
```

This doesn;t:

```js
ws.send({test: 'test'});
```

I propose an enhancement in [Sender.js](https://github.com/websockets/ws/blob/master/lib/Sender.js#L266) to allow or convert objects automatically.

**Comment by 3rd-Eden** [comment]
Sending JSON would make no sense as it would not be decoded automatically on a WebSocket client.

**Comment by ZaDarkSide** [comment]
You are right, but instead of throwing an error like this one:

```
"TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object."
```

Maybe instead the error message should be improved at least.

**Comment by lpinca** [comment]
That error is thrown by Node.js when you try to make a buffer from an object.

```js
Buffer.from({ test: 'test' });
```

The WebSocket protocol only work with text and binary data so anything regarding SerDes should not be handled by this lib.

**Comment by ZaDarkSide** [comment]
Yes I understand, but in [Sender.js](https://github.com/websockets/ws/blob/master/lib/Sender.js#L266) there is already some code that does conversion from `ArrayBuffer` to `Buffer`, why not add conversion from `Object` to `Buffer` also?

**Comment by lpinca** [comment]
That's already binary data, we have to convert to it `Buffer` because that's the "type" required by Node.js API.

**Comment by ZaDarkSide** [comment]
Okay, it's a minor issue for me, closing this.

**Comment by zvictor** [comment]
It is great that I find this issue, though. I couldn't figure out what I was doing wrong... Thanks for posting @ZaDarkSide !

**Comment by fabiel-leon** [comment]
workaround

```
ws.json = (obj) => ws.send(JSON.stringify(obj));

ws.json({ message: "hello" });
```
