### ISSUE TITLE
Distributed websocket, how to make people hitting different servers communicate with each other?

### ISSUE THREAD

**Issue by ghost** [websockets/ws#1110]
As  we all  know ,the  important point of different server communications are the shared data.

However,websocket is an  object . I tryed but cant saved it in  Database ,such as redis ,mysql. But  if just saved it in Memory. it cant work if we want to  make people hitting different servers communicate with each other?

The official website  offer two methods to solve it ,
https://socket.io/docs/using-multiple-nodes/
one is  set the ip_hash of nginx ,another one is socket.io-adapter.
var io = require('socket.io')(3000);
var redis = require('socket.io-redis');
io.adapter(redis({ host: 'localhost', port: 6379 }));

I want to know how to implement the  websocket  shared data  inorder  to make people hitting different servers communicate with each other?

**Comment by lpinca** [comment]
You can use Pub/Sub. There are tons of articles on the internet for this problem.

https://socket.io/ is not the official website of this project. Socket.IO and ws and two different things.
