### ISSUE TITLE
How to find out if client is unauthorized after connect

### ISSUE THREAD

**Issue by Cheprer** [websockets/ws#1111]
I have situation that I'm listening to only one particular message where rejectUnauthorized = false and then after decoding the message, I want to check if the client is authorized(has trusted SSL certificate) is this a correct way to do it (code below)?

```javascript
let wss = new WebSocketServer({ server: server.listener });
wss.on('connection', handleConnection);

let handleConnection = ws => 
  wss.on('message', message => someMsgHandler(message, ws));

const someMsgHandler = (message, ws) => {
  if(ws.upgradeReq.client.authorized){
    ...
  }
}
```

**Comment by lpinca** [comment]
It looks legit.
