### ISSUE TITLE
[help wanted] 'wss://...' link send request to http. How to send transports websocket headers?

### ISSUE THREAD

**Issue by YUzhva** [websockets/ws#1117]
Hey hi.

I created react new react project using `create-react-app` and would like to implement some API fetching from third party API server (API from another web app).

I installed `yarn add ws`, and my next steps are:

```javascript
import WebSocket from 'ws';

class App extends Component {
  constructor(props) {
    super(props);

    this.socket = new WebSocket('wss://ws.cex.io/ws');
  }
  componentWillMount() {
    console.log('this.socket', this.socket);
    this.socket.on('connect', () => console.log('Socket is connected'));
  }
```

But when I'm opening the console, I can see that request actually goes through HTTP like:

```bash
# Network tab
Request URL: http://echo.websocket.org:443/

# Browser console
GET http://echo.websocket.org:443/ net::ERR_EMPTY_RESPONSE
```
I'm getting `net::ERR_EMPTY_RESPONSE` because there is no such a page under http/https, but it exist on `wss://`

Expected behavior:
```
Request URL: wss://echo.websocket.org:443/
Request Method: GET
Status Code: 101 Web Socket Protocol Handshake
```

The current proposal from socket.io-client is to send  transports headers that say this is websocket request:
```javascript
this.socket = io.connect('wss://echo.websocket.org', { transports: ['websocket'] });
```

**Comment by lpinca** [comment]
Hi,
in the browser you have to use the native `WebSocket` object. You can use a shim like this:

```js
var ws;

if (typeof WebSocket !== 'undefined') {
  ws = WebSocket;
} else if (typeof MozWebSocket !== 'undefined') {
  ws = MozWebSocket;
} else {
  ws = window.WebSocket || window.MozWebSocket;
}

module.exports = ws;
```

and add the `browser` field in your `package.json`.

```json
{
  "browser": {
    "ws": "./shim.js"
  }
}
```

**Comment by YUzhva** [comment]
Okay.

Server rendering of the component also doesn't help, because `ws` require live server instead of URL where this server hosted )=

Thank, you for help. There are no any issues with native WebSocket, so will use them.

**Comment by piranna** [comment]
What about adding the shim in the `ws` source code and add a `browser` field in `package.json`? :-)

**Comment by lpinca** [comment]
@piranna it has been removed in https://github.com/websockets/ws/commit/e54d45fbab3b19c2940e9057ce1e7b8f105873e0.

**Comment by piranna** [comment]
> @piranna it has been removed in e54d45f.

Sorry to read that, I can only say that you would have your reasons, but I agree with the others that removing the shim was a bad movement :-(

**Comment by lpinca** [comment]
I didn't take part in that decision, wasn't a collaborator at the time. Maybe we can re-evaluate and add it again if other collaborators agree.

**Comment by piranna** [comment]
It would be good to open an issue to evaluate it...

**Comment by AJLoveChina** [comment]
> Hi,
> in the browser you have to use the native `WebSocket` object. You can use a shim like this:
> 
> ```js
> var ws;
> 
> if (typeof WebSocket !== 'undefined') {
>   ws = WebSocket;
> } else if (typeof MozWebSocket !== 'undefined') {
>   ws = MozWebSocket;
> } else {
>   ws = window.WebSocket || window.MozWebSocket;
> }
> 
> module.exports = ws;
> ```
> 
> and add the `browser` field in your `package.json`.
> 
> ```json
> {
>   "browser": {
>     "ws": "./shim.js"
>   }
> }
> ```
Yes, your answer is right.

But I found there is also a solution provided by webpack,
the usage is like this:
`node: {
            ws: "empty",
        },`
But unhappy, I found this is not working! And only for `ws`!
When I am testing other keywords like `fs`, `crypto`, `path`, all of them are OK!

So why is `ws` not working in webpack `node` configuration?
