### ISSUE TITLE
CITGM fail

### ISSUE THREAD

**Issue by refack** [websockets/ws#1118]
Maybe just a load induced timeout...
```
 274 passing (5s)
   1 failing
   1) WebSocket permessage-deflate #terminate will raise error callback, if any, if called during send data:
      Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
```
Same error on `osx1010` and `aix61-ppc64`
Test: https://github.com/websockets/ws/blob/master/test/WebSocket.test.js#L1990
CITGM report: https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/813/testReport/

**Comment by mcollina** [comment]
@refack I do not think opening a bug on the target module is the best approach for core. You should really open a bug in core.

**Comment by refack** [comment]
> @refack I do not think opening a bug on the target module is the best approach for core. You should really open a bug in core.

I usually do, initially I thought it was a load induced timeout.
Now @lpinca seems to agree https://github.com/nodejs/node/pull/12828#issuecomment-303113552

P.S. It's CITGM policy to inform module authors https://github.com/nodejs/citgm/blob/master/CONTRIBUTING.md#submitting-a-module-to-citgm

**Comment by mcollina** [comment]
Anyway, as the author of the offending issue I would have loved to know :).
I'm a bit unsure how I missed that, and why it fails only on AIX and OSX, but not everywhere else.

**Comment by refack** [comment]
> Anyway, as the author of the offending issue I would have loved to know :).
> I'm a bit unsure how I missed that, and why it fails only on AIX and OSX, but not everywhere else.

Big Ack 🤦‍♂️ 
Re: https://github.com/nodejs/node/pull/12925#issuecomment-303120426

**Comment by mcollina** [comment]
Anyway, it's confirmed and a fix is on its way.

**Comment by lpinca** [comment]
Awesome, thanks.
