### ISSUE TITLE
write EPIPE

### ISSUE THREAD

**Issue by UNST4BL3** [websockets/ws#1123]
Hi there. I just tried posting this issue to the node repository as I thought it was a core problem but apparently not.

I have the following error being produced after spam refreshing a page which connects to the WebSocket server.

```
Error: write EPIPE
    at exports._errnoException (util.js:1050:11)
    at WriteWrap.afterWrite [as oncomplete] (net.js:814:14)
```

I have identified that this is being caused by the broadcast function given in the README, which as far as I'm aware does all the necessary checks and should work.

```
ws.broadcast = (data) => {
  ws.clients.forEach((client) => {
    if(client.readyState === WebSocket.OPEN) 
      client.send(data);
  });
};
```

**Comment by lpinca** [comment]
Add a listener for the `'error'` event and handle the error or ignore it in this case when it occurs. See https://github.com/websockets/ws/issues/1017.
