### ISSUE TITLE
WS and Node clustering share user connections.

### ISSUE THREAD

**Issue by goriunov** [websockets/ws#1124]
I went through many different websites trying to figure out how to implement Websokets and Node clustering. So the basic idea which i wanted to try is : I have and array of all users who are connected to the server , like : 
{key:ws, key:ws ,key:ws} 

So what i want to do is to run Node js Clusters with Websockets , i will get some thing like that

Master  : place to store all the connected ws in array : {key:ws, key:ws ,key:ws} 
Worker1 : Ws server to connect
Worker2 : Ws server to connect 

What i am wondering is for example user which is connected to the Worker2 wants to send message to user which is connected to the Worker2 and worker1.

So i will send message from Worker2 to the Master to get all the users , Master will send  {key:ws(worker1), key:ws(worker2) ,key:ws} . And  Worker2 will iterate over this array and send message to each user. 
Will that implementation work or message will not be send to the user which is connected to another Worker?

Thank you very much for the answer.

**Comment by lpinca** [comment]
No, this will not work as you can't share connections in that way. You have to build a shared registry which maps workers and connections.

|worker id   | socket ids  |
|:----------:|:-----------:|
|1           | 1, 2, 3   |
|2           | 4, 5, 6   |

Then send a message to the correct worker and broadcast the message to all or a subset of connections in that worker.

**Comment by lpinca** [comment]
Closing, feel free to continue discussing on the closed thread.

**Comment by aprilmintacpineda** [comment]
Or broadcast it to all the workers.

```js
const cluster = require('cluster');

if (cluster.isMaster) {
  const workers = [];
  for (let a = 0, maxA = require('os').cpus().length; a < maxA; a++) {
    const fork = cluster.fork();
    workers.push(fork);
    fork.on('message', event => workers.forEach(worker => worker.send(event)));
  }
} else {
  console.log('worker', process.pid);

  const userId = Math.random();
  const users = {
    [userId]: [
      {
        send (payload) {
          console.log('user got it!', userId, payload);
        }
      }
    ]
  };

  process.on('message', ({ action, payload }) => {
    switch (action) {
      case 'emitSocketEvent':
        if (payload.userId in users) {
          users[payload.userId].forEach(socket => {
            socket.send(payload.message);
          });
        }
        break;
      // .. handle other actions
    }
  });

  setTimeout(() => {
    process.send({
      action: 'emitSocketEvent',
      payload: {
        userId,
        message: {
          event: 'test event',
          data: 'test data'
        }
      }
    });
  }, 1000);
}
```

But what about when using [pm2](https://pm2.keymetrics.io/docs/usage/cluster-mode/)'s cluster? Any idea?
