### ISSUE TITLE
Add .pipe

### ISSUE THREAD

**Issue by bmeck** [websockets/ws#113]
WebSockets are often used to stream data streams, it would be convenient if .pipe and on('pipe') were provided in order to consume and provide to other streams.

**Comment by olalonde** [comment]
Has this been implemented yet? I can't seem to be able to pipe to websocket.

**Comment by ronkorving** [comment]
+1 on this. It's now impossible to stream large amounts of data without the risks that come with the lack of back-pressure knowledge. It doesn't seem to be very hard to make Node run out of memory this way.

**Comment by JoshuaWise** [comment]
This functionality is currently implemented via the `ws#stream` method, no? Can we close this issue?

**Comment by bmeck** [comment]
@JoshuaWise stream doesn't do anything with backpressure / error propagation so idk. At this point though I avoid anything without a real stream interface (this issue is rather ancient).

**Comment by JoshuaWise** [comment]
I see. I'd like to hear @einaros's 2016 opinion on the issue.

**Comment by JoshuaWise** [comment]
It's possible we prematurely closed https://github.com/websockets/ws/pull/602
