### ISSUE TITLE
WS reports invalid error code

### ISSUE THREAD

**Issue by herkyl** [websockets/ws#1134]
#### Description

I am using [Gorilla Websockets](http://www.gorillatoolkit.org/pkg/websocket) to send a close frame to a connected client (the client being ws). The close frame is a standard 2 byte integer code + message.

I am setting the code to be 1008, however ws reports it as `code: 1006`. I know that Gorilla sends out the correct message because I have debugged what the first two bytes of the message are and the same code works correctly in Chrome, showing the correct 1008 code.

#### Reproducible in:

version: 3.0.0
Node.js version(s): 6.9.2
OS version(s): OSX 10.12.3

#### Steps to reproduce:

1. I am using this Go code to close the connect with an event:
```go
cm := websocket.FormatCloseMessage(websocket.ClosePolicyViolation, msg)
if err := c.conn.WriteMessage(websocket.CloseMessage, cm); err != nil {
    log.Error(err)
}
err = c.conn.Close()
```
2. Listen to the close event of the ws connection and check the code.

### Expected result:

I expect the close code to be 1008

### Actual result:

The code is 1006

**Comment by lpinca** [comment]
Do you know if the close handshake is respected and the connection is closed cleanly? This example works as expected.

```js
const WebSocket = require('ws');

const wss = new WebSocket.Server({ port: 3000 }, () => {
  const ws = new WebSocket('ws://localhost:3000');

  ws.on('close', (code, reason) => {
    console.log(code, reason);
  });
});

wss.on('connection', (ws) => ws.close(1008));
```

I wonder if the socket is closed with an error https://nodejs.org/dist/latest/docs/api/net.html#net_event_close_1. In that case the close code is set to [`1006`](https://github.com/websockets/ws/blob/942f825ff0702ce7ce66d8731a56b071269d88b4/lib/WebSocket.js#L190) even if the close frame was received by the client.

**Comment by lpinca** [comment]
I tried with this code:

```go
package main

import (
	"log"
	"net/http"

	"github.com/gorilla/websocket"
)

var upgrader = websocket.Upgrader{}

func echo(w http.ResponseWriter, r *http.Request) {
	c, err := upgrader.Upgrade(w, r, nil)
	if err != nil {
		log.Print(err)
		return
	}
	cm := websocket.FormatCloseMessage(websocket.ClosePolicyViolation, "")
	err = c.WriteMessage(websocket.CloseMessage, cm)
	if err != nil {
		log.Print(err)
	}
	err = c.Close()
	if err != nil {
		log.Print(err)
	}
}

func main() {
	log.SetFlags(0)
	http.HandleFunc("/echo", echo)
	log.Fatal(http.ListenAndServe("localhost:3000", nil))
}
```

The close frame is correctly received by the client but an [error](https://github.com/websockets/ws/blob/942f825ff0702ce7ce66d8731a56b071269d88b4/lib/WebSocket.js#L130) is emitted on the socket.

```
Error: read ECONNRESET
    at exports._errnoException (util.js:1026:11)
    at TCP.onread (net.js:607:25)
```

so the close code is set to `1006`. This seems correct to me.

To get the expected result in the issue description we can update this [if condition](https://github.com/websockets/ws/blob/942f825ff0702ce7ce66d8731a56b071269d88b4/lib/WebSocket.js#L190) as follows:

```js
if (!this._closeCode && error) this._closeCode = 1006;
```

but I'm not sure if it makes sense.

**Comment by herkyl** [comment]
I don't fully understand why an error is emitted. How does `wss.on('connection', (ws) => ws.close(1008));` work differently than the Go code?

**Comment by lpinca** [comment]
`ws.close()` works a bit differently. It implements the close handshake. The connection is not immediately closed after sending the data. It waits for the other peer to send back a close frame.

This is how it works in ws:

```
            +----------+  +-----------+  +----------+
     - - - -|ws.close()|->|close frame|->|ws.close()|- - - -
    |       +----------+  +-----------+  +----------+       |
            +----------+  +-----------+        |
    |       |ws.close()|<-|close frame|<-------+            |
            +----------+  +-----------+
 CLOSING          |                                      CLOSING
                  |
    |             |           +---+     +-------------+     |
                  +---------->|fin|---->|ws.finalize()|- - -
    |                         +---+     +-------------+
           +-------------+    +---+            |
    + - - -|ws.finalize()|<---|fin|<-----------+
           +-------------+    +---+
```

In the go code the connection is closed without reading data that has been sent to it and I think this is why an ECONNRESET error is emitted.

**Comment by herkyl** [comment]
Interesting. I found that Gorilla often uses a sleep before closing the connection https://github.com/gorilla/websocket/blob/5ade364dff1f03abefdae800ed19074bf707b08f/examples/command/main.go#L77 but it seems kind of dirty.
Maybe I could instead wait for the close frame from the socket myself. Could you please show me the part in `ws` that handles this, I will try to duplicate it in Go.

**Comment by lpinca** [comment]
1. Is starts in the [`close`](https://github.com/websockets/ws/blob/942f825ff0702ce7ce66d8731a56b071269d88b4/lib/WebSocket.js#L265-L295) method.

2. When a peer receives a [close frame](https://github.com/websockets/ws/blob/942f825ff0702ce7ce66d8731a56b071269d88b4/lib/WebSocket.js#L149-L153) it calls the `close` method.

3. And finally is handled by the [event listeners](https://github.com/websockets/ws/blob/942f825ff0702ce7ce66d8731a56b071269d88b4/lib/WebSocket.js#L129-L131) on the socket.

**Comment by lpinca** [comment]
Hmm I think my explanation was similar to this

![owl](https://cloud.githubusercontent.com/assets/1443911/26756457/13af1da0-48a3-11e7-8e99-0adbc4482c78.jpg)

so if something isn't clear just ask.

**Comment by garyburd** [comment]
> I found that Gorilla often uses a sleep before closing the connection https://github.com/gorilla/websocket/blob/5ade364dff1f03abefdae800ed19074bf707b08f/examples/command/main.go#L77 but it seems kind of dirty.

The [sleep and close](https://github.com/gorilla/websocket/blob/5ade364dff1f03abefdae800ed19074bf707b08f/examples/command/main.go#L77-L78) calls in the Gorilla example ensures that the connection is closed in the case where the client does not reply to the close message.  If you want to rely on the client replying to the close frame, then delete the call to `time.Sleep` and `ws.Close`. Do not delete the call to `time.Sleep()` without also deleting the call to `ws.Close()`.

**Comment by herkyl** [comment]
Thanks for all the help!
Since I misunderstood how closing works in the first place I designed an erroneous for handling the closing on my part. You are correct, the sleep is simply there to ensure that if the handshake doesn't finish the connection still gets closed.
I will close the issue.
