### ISSUE TITLE
Docs don't mention `on` method, just `.addEventListener`, but examples use `.on`

### ISSUE THREAD

**Issue by trusktr** [websockets/ws#1139]
Furthermore, using `.on` the message data seems to be a non-parsed string, but the message passed into handlers assigned with `addEventListener` are object instances, not strings.

Basically, the following two examples behave _completely_ different:

```js
        ws.addEventListener('message', onconnect)
```

```
        ws.on('message', onconnect)
```

This makes it really hard to guess how the API works, leaving people to guess blindly.

It'd be nice to update the docs, and mention that when using `addEventListener`, the argument passesd to the handler is a `MessageEvent`, while the argument passed into a handler assigned with `.on` is a string which is the actual message.

![1qpzlc](https://user-images.githubusercontent.com/297678/27015675-c914bbf8-4ed1-11e7-9dbc-6fe4c68b6fd8.jpg)

which is confusing, and will waste people's time.

**Comment by trusktr** [comment]
On top of that, there seems to be no reciprocal `.off()` method when using `.on`, to further add to the confusion.

**Comment by lpinca** [comment]
From https://github.com/websockets/ws/blob/master/doc/ws.md#class-websocket

> This class represents a WebSocket. It extends the `EventEmitter`.

This means that you can use the [`EventEmitter`](https://nodejs.org/dist/latest/docs/api/events.html) methods. There is no `events.off()`.

The difference between `ws.on('message', listener)` and `ws.addEventListener('message', listener)` is also documented.

In the former case the listener is called with a `data` argument which can be `String|Buffer|ArrayBuffer|Buffer[]`: https://github.com/websockets/ws/blob/master/doc/ws.md#event-message.
In the latter the docs say that using `ws.addEventListener()` register a listener emulating the [`EventTarget`](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener) interface.

That said PRs are always welcome.
