### ISSUE TITLE
Allow to use url.URL as WebSocket constructor input

### ISSUE THREAD

**Issue by timanovsky** [websockets/ws#1143]
- [x] I've searched for any related issues and avoided creating a duplicate issue.

#### Description

Currently `new Websocket(url)` expects string argument and fails with `TypeError: Parameter "url" must be a string, not object` if passed nodejs `URL` object. Would be convenient to pass URL objects too.

#### Reproducible in:

version: 3.0.0
Node.js version(s): 8
OS version(s):

#### Steps to reproduce:

1. 
```
const WebSocket = require('ws');
const { URL } = require('url');
new WebSocket(new URL("ws://localhost"))
```

### Expected result:

Properly initialized websocket

### Actual result:

Exception

**Comment by lpinca** [comment]
This is consistent with the browser behavior where an error is thrown if the URL is not a string.
I have no strong opinions though.

**Comment by timanovsky** [comment]
@lpinca true, but comparing to HTTP client libraries, which do accept `URL`, is also relevant

**Comment by lpinca** [comment]
Yes it may be a nice to have feature. Anyway it should accept the object returned by both parsers: legacy and WHATWG.

An inefficient workaround is something like this.

```js
const url = require('url');
const WebSocket = require('ws');

const parsed = url.parse('ws://localhost:8080');

const ws = new WebSocket(url.format(parsed));
```

**Comment by 3rd-Eden** [comment]
> This is consistent with the browser behavior where an error is thrown if the URL is not a string.
I have no strong opinions though.

This is no longer the case. Browsers, or at least chrome, supports this.

**Comment by lpinca** [comment]
Just tested and it also work on Firefox, but I think the spec has not been updated: https://html.spec.whatwg.org/multipage/web-sockets.html#the-websocket-interface
