### ISSUE TITLE
wasClean property might be wrong

### ISSUE THREAD

**Issue by roymiloh** [websockets/ws#1144]
When I try to use the Chrome's (same for Safari / Firefox) `WebSocket` instance directly and call `close` with any valid code (1000 or 3000 - 4999), I always get `wasClean === true`.
On the other hand, [we have this](https://github.com/websockets/ws/blob/fe44ff81cc414495f19416847ce658cbea079d06/lib/EventTarget.js#L58).
Yes, we are talking about browsers' implementation, but still, I believe it should be consistent (especially in my case where I use `ws` in my tests so I can simulate WebSocket client in nodejs).

[By W3C spec](https://www.w3.org/TR/2011/WD-websockets-20110419/#dfnReturnLink-1):

> The wasClean attribute represents whether the connection closed cleanly or not.

I'd suggest to add check for 3000 - 4999 range as well in order to determine `wasClean`'s value.

**Comment by lpinca** [comment]
It makes sense. Please open a pull request.

**Comment by lpinca** [comment]
Fixed by #1146.
Thanks.
