### ISSUE TITLE
Missing upgradeReq property makes it impossible to determine request URL

### ISSUE THREAD

**Issue by jancurn** [websockets/ws#1145]
#### Description

In version 3.0.0 the `WebSocket.upgradeReq` property has been removed. Unfortunately that means that now there's no simple way to determine on the server which URL the client originally requested. In version 2.3.1 you could do this simply using `ws.upgradeReq.url` where `ws` is the instance of the `WebSocket` class.

#### Reproducible in:

version: 3.0.0
Node.js version(s): any
OS version(s): any

#### Steps to reproduce:

N/A

### Expected result:

N/A

### Actual result:

N/A

### Attachments:

N/A

**Comment by lpinca** [comment]
You can save it when the `connection` event is emitted:

```js
wss.on('connection', function connection(ws, req) {
  const url = req.url;
  // Do whatever you want with it. You can even reattach it to the `ws` object if you need to.
});
```

**Comment by jancurn** [comment]
Great, I didn't see this possibility, many thanks for the hint!

**Comment by Globik** [comment]
ws.url=req.url

**Comment by cre8** [comment]
@Globik using `ws.url` will return undefined for me with version `3.2.1`.

**Comment by Globik** [comment]
@cre8 
Yes, it should be.
Please use req.url from second parameter.
