### ISSUE TITLE
clientTracking set to true by default

### ISSUE THREAD

**Issue by josezulu** [websockets/ws#1153]
Hi all,

Maybe I misunderstand the docs, but "Please note that this property is only added when the clientTracking is truthy." seems to me that clientTracking would be false by default.
However, I don't have that property on my server config object, yet server.clients is created.

It only becomes disabled when I explicitly add it to my config and set it to false.
Or perhaps I'm doing something wrong?

**Comment by lpinca** [comment]
> It only becomes disabled when I explicitly add it to my config and set it to false.

Yes, correct.

**Comment by josezulu** [comment]
Thank you for the clarification.
