### ISSUE TITLE
websocket.send callback question

### ISSUE THREAD

**Issue by josezulu** [websockets/ws#1154]
websocket.send(data, [options][, callback])

callback {Function} An optional callback which is invoked when data is written out.

I was expecting that the callback would be called AFTER the data has been sent to the client.

Testing shows me that the value of ws._socket._bytesDispatched during the callback is not the same value after a few seconds after sending the message.

I'm just trying to see how much data is sent by the server, perhaps there is a different way to achieve this?

**Comment by lpinca** [comment]
The callback is forwarded to [`socket.write()`](https://nodejs.org/dist/latest/docs/api/net.html#net_socket_write_data_encoding_callback). The behavior is defined by that api.
