### ISSUE TITLE
Don't fire client.send error event if not error

### ISSUE THREAD

**Issue by wayofthefuture** [websockets/ws#1156]
It seems odd that the error event is fired when no error occurs. Is it possible to Only call the client.send error event when an error actually occurs?

**Comment by lpinca** [comment]
Can you please elaborate? I'm not sure I understand. The issue template is there for a reason.

**Comment by wayofthefuture** [comment]
client.send(msg, errFunc) will always call the errFunc even if there is no error.

**Comment by lpinca** [comment]
Yes that's by design, the callback is always called. That's how all callback work in Node.js.

It also serves as a mean to know when the data is flushed to the kernel buffer not only to know if an error occurred.
