### ISSUE TITLE
Unable to catch errors thrown on connection

### ISSUE THREAD

**Issue by artdude543** [websockets/ws#1157]
- [X] I've searched for any related issues and avoided creating a duplicate issue.

#### Description

I'm experiencing an issue with connecting to a socket which is behind CloudFlare which they occasionally return a `521` error. WS seems to be catching this internally and then emitting it as an error but this is done quicker than the app can register a listener for that socket.

The error handler given above should capture the emitted error from WS but it does not and it's emitted to Node's level instead.

Currently, this is a problem for me with creating a chatbot we have many sockets open at once on the same node process and using the node error handler makes handling individual socket connections a pain as we don't know what socket threw the error to deal with said error.

#### Reproducible in:

Version: 3.0.0
Node.js version(s): 8.1.2
OS version(s): Windows 10

#### Steps to reproduce:

Connect to a WebSocket server which throws a `521` on a handshake. (Common with servers running behind CloudFlare)

```javascript
const socket = new WebSocket(url, protocol, extras);
socket.addEventListener('error', function (err) {
  // Code to handle the error.
  console.error(err); // unexpected server response (521)
});
```

### Expected result:

The error event handler should be called with the connection error.

### Actual result:

The error is emitted to node's level which you can catch using Node's method. But if you have an app such as a chat bot this is not efficient to catch which socket threw the error to clear that socket/instance of the bot up. When you have multiple bots running on the same process.

### Possible solution:

Ideally, we should be able to attach event listeners before the module attempts to connect to a server. This way we can guarantee that we'll be able to handle connection errors.

### Attachments:

![Screenshot](https://i.artdude.uk/jioyg738.png)

**Comment by lpinca** [comment]
I can't reproduce the issue. The `'error'` listener works as expected.

```js
const WebSocket = require('ws');
const http = require('http');

const server = http.createServer();

server.on('upgrade', function (request, socket) {
  socket.write(
    `HTTP/1.1 ${521} ${http.STATUS_CODES[521]}\r\n` +
    'Connection: close\r\n' +
    '\r\n'
  );
  socket.destroy();
});

server.listen(3000, () => {
  const ws = new WebSocket('ws://localhost:3000');

  ws.addEventListener('error', (err) => console.log(err.message));
});
```

**Comment by artdude543** [comment]
I did some more debugging (after some sleep) to find the issue with a middleware app hacking into WS for some bizarre reason. So nothing wrong with the module here. Sorry for spending your time! D:

**Comment by milosjovac** [comment]
Hi,
Just wondering, when I try  
`var ws = WebSocketServer({ server: wsServer, port: port });
ws.addEventListener('error', (err) => console.log(err.message));`
I get following error: 
`TypeError: ws.addEventListener is not a function`

Only `.on('specific_event', fun())` works for me. Any ideas why?

Tnx,
Milos
