### ISSUE TITLE
close event not fired when network disconnected

### ISSUE THREAD

**Issue by kuangyunsheng** [websockets/ws#1158]
- [ ] I've searched for any related issues and avoided creating a duplicate issue.

#### Description

I want to listen close event to do something, but when network disconnect, this event don't fire.

#### Reproducible in:

version:
Node.js version(s):  v7.3.0
OS version(s): windows 7

#### Steps to reproduce:

1. listen close event on the server side
```
websocket.on('connection', function(client){
    console.log('socket opened')

    client.on('close', ()=>{
        console.log('websocket closed')
    }
})
```
2. create a websocket in a html page
```
var socket = new WebSocket('ws://' + location.host)

socket.onclose = event=>{
    console.log('websocket closed')
}
```
3. open the page in browser, it shows "socket opened" at server side console and browser console 

4.  then, disconnect network. but only see "websocket closed" at browser console.

### Expected result:

close event fired both at server side and client side 

### Actual result:

close event only fired at client side

**Comment by lpinca** [comment]
See https://github.com/websockets/ws#how-to-detect-and-close-broken-connections.

**Comment by kuangyunsheng** [comment]
thanks very much
