### ISSUE TITLE
@types/ws clients WebSocket[] should be Set<WebSocket>

### ISSUE THREAD

**Issue by Manusan42** [websockets/ws#1161]
Please, can someone fix this little typing error in @types/ws: 
https://github.com/DefinitelyTyped/DefinitelyTyped/issues/14774

This ticket seems not to be recognised from anyone who is responsible for?
I hoped it would be fixed by upgrading to v3.0.0 but it's still there.

The ticket flood in DefinitelyTyped is just a mess so I post this here in hope someone will fix this.

A thousand thanks in advance!

**Comment by lpinca** [comment]
@Manusan42 you can do it yourself by submitting a PR to the DefinitelyTyped repo.

**Comment by Manusan42** [comment]
Yay, finally! Thank you so much!!! I thought about doing it myself, but I've never done this before and GitHub, Typescript, etc... is all quite new to me. So it was probably much easier for you to do it.

**Comment by renannprado** [comment]
can't use typescript with this lib because of this issue :(
the fix wasn't merged yet... is there anything I can do?
