### ISSUE TITLE
Server.clients returns a SET however type definitions says it is an array

### ISSUE THREAD

**Issue by mustafaekim** [websockets/ws#1163]
The Websocket.Server.clients property returns me a SET instead of an array.

However, typescript complains me that it is an array so that it results with errors.

Am I right?

```ts
    export class Server extends events.EventEmitter {
        options: IServerOptions;
        path: string;
        clients: WebSocket[];
...
```

**Comment by lpinca** [comment]
Yes you are right, see https://github.com/websockets/ws/issues/1161.
