### ISSUE TITLE
Do I always have to check the readyState of current socket is WebSocket.OPEN before I send any message on the server?

### ISSUE THREAD

**Issue by crazyyi** [websockets/ws#1170]
I am using this library to build an online game. Some connection will be closed intentionally when the player loses the game. But every time I send some message on the server if the readyState is not WebSocket.OPEN it will give an error saying "Not Opened". So my code is full of state checking condition clauses. Is it possible to check this state less often? For example, giving some extra configs in the `send` command to enable checking this state automatically or go without checking it.

**Comment by lpinca** [comment]
You can add a callback. It will be called with an error if the `readyState` is not `OPEN`. If you want to ignore the error you can use noop function.

**Comment by crazyyi** [comment]
Thanks I know there is a callback. But I need a check before sending the message not after sending it and get a feedback.

**Comment by lpinca** [comment]
The callback is invoked before sending the message when the `readyState` is not `OPEN`. See https://github.com/websockets/ws/blob/d7811907ad590cbc7a6354f61dd283e36d1eee4d/lib/WebSocket.js#L353-L357.

**Comment by crazyyi** [comment]
Oh nice. I didn't read that carefully.

**Comment by lpinca** [comment]
Closing, feel free to continue discussing on the closed thread.

**Comment by crazyyi** [comment]
Now I am using this code:

```
try {
	ws.send(msg, function(error) {
        	if(error == undefined)
			return;
		else
		        logger.debug("Async error:"+error);
	});
} catch(e) {
	logger.debug("Sync error: " + e);
	ws.close();
}
```
And I have the error listener on the virtual client on the server side:
```
ws.on('error', function error(event) {
		      logger.debug(event.err + '  state: ' + ws.readyState);
 });
```

and client side:
```
ws.onerror = function error(event) {
	      console.log(event.err + '  state: ' + socket.readyState);
};
```

On server side:
```
wss.on('error', function error(err) {
	console.log('Error: ' + err.code);
});
```

But I still get this error after I run the server for a while and one of the clients logs off. 

```
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at exports._errnoException (util.js:1014:11)
    at WriteWrap.afterWrite (net.js:850:14)
```

Sometimes I get the log saying:

> Async error:Error: write EPIPE

and the client is kicked out of the server ( I have only one client on a different computer). But the server keeps running. And the readyState is not opened. What could be the problem?

**Comment by smsalarmas** [comment]
crazyyi 
You're the best!

try {
                                        ws.send(RespuestaToUser, function(error) {
                                                if(error == undefined)
                                                return;
                                            else
                                            Salida = true
                                        });
                                    } catch(e) {
                                        Salida = true
                                        ws.close();
                                    }
Run Perfect!
