### ISSUE TITLE
The order of send may be messed up

### ISSUE THREAD

**Issue by narychen** [websockets/ws#1171]
It's hard to re-produce. But I found that weird bugs that may caused by this situation. 
If I do ==>
ws.send('1')
ws.send('2')

While on the other side, is there a chance that '2' arrive first and the onmessage callback been called earlier than the '1' ??

**Comment by lpinca** [comment]
No this shouldn't be possible, the order of message should be the same.

**Comment by narychen** [comment]
You mean that must be caused by other codes, not possible by ws?

**Comment by lpinca** [comment]
Messages are written in order of arrival to a TCP socket. TCP guarantees that a receiver will receive the reconstituted stream of bytes as it was originally sent by the sender.

It's not possible that the order of messages is altered by this lib unless there is a bug which seems unlikely as there are tests to ensure that the order is respected.

**Comment by narychen** [comment]
OK. I will check the other codes. Thanks.

**Comment by cloutiertyler** [comment]
@narychen were you ever able to reproduce this bug?
