### ISSUE TITLE
Error "write EPIPE" causes client to disconnect but server keeps running

### ISSUE THREAD

**Issue by crazyyi** [websockets/ws#1172]
I get an error message on the server saying "Found error: Error: write EPIPE" when I use the following code to send messages from server to client and use an error listener. The error message is from the error listener I write on server. (Some codes are on the client which I didn't post here)

```
try {
	ws.send(msg, function(error) {
        	if(error == undefined)
			return;
		else
		        logger.debug("Async error:"+error);
	});
} catch(e) {
	logger.debug("Sync error: " + e);
	ws.close();
}
wss.on('error', function error(err) {
	console.log('Error: ' + err.code);
});

```
Error listener is inside `wss.on('connection', function(ws, req) {})`:

```
ws.on('error', function(err) {
      logger.debug('Found error: ' + err);
});

ws.on('close', function() {
      logger.debug('connection closed.');
});
```

When I get this error, the client closes (readyState is not open), but the server keeps running. Is there anything I can do to figure out what causes the error and closes the client? I am running a realtime game.  I didn't do anything special other than just run the client normally and the client computer is in my room. I wonder if this is related to the server thinking the client is in idle status. For example, when I send little data from client to the server, the client crashes, when I keep pressing the mouse button, it sends messages to the server very often and the client is always alive.

I have used the "ping-pong" code on the server. But not sure if I need to implement that on the client.

**Comment by lpinca** [comment]
Hi, you already posted the same question here https://github.com/websockets/ws/issues/1170#issuecomment-314807518.

EPIPE means you're writing to a socket when the other end has terminated the connection.
It's a runtime error and there is nothing you can do to avoid it. You only have to close your end as well but that is done automatically.

You can find more info here https://github.com/websockets/ws/issues/1017.

All you have to do is adding an error listener:

```js
wss.on('connection', (ws) => {
  ws.on('error', handleError);
});
```

Wrapping `ws.send()` in a `try...catch` statement doesn't make sense if you are already passing a callback to `ws.send()`.

I have no idea why you client closes the connection.

**Comment by crazyyi** [comment]
Thanks for your reply. Sorry to create a new issue but I hope you can have a look at this.
 I already have the error listener. That's why it sends the message on server instead of stopping the server. I just want to know if this is related to client being assumed idle if no data is sent to the server for half a minute.

**Comment by lpinca** [comment]
You are sending pings so that is unlikely but I can't really know what happens on your environment. Try to use wireshark and see what happens.

**Comment by crazyyi** [comment]
I have already tried wireshark sniffing before I ask here. But I can't find anything useful as when the connection is closed the server just try to resend data again and again and ignore the ACK message.

**Comment by lpinca** [comment]
Are you able to create a minimal (using only ws) reproducible test case? If not it's hard to help.

**Comment by crazyyi** [comment]
That is hard to reproduce using only ws. I need to figure out some other way.

**Comment by lpinca** [comment]
Any update here?

**Comment by crazyyi** [comment]
Yes. There doesn't seem to be any issue any more.  The error is gone and can not be reproduced again. I don't even know what I have changed.

**Comment by lpinca** [comment]
Ok nice. I'm closing then.
