### ISSUE TITLE
Is the onerror callback parameter correct?

### ISSUE THREAD

**Issue by lll000111** [websockets/ws#1173]
I have looked into the types of the various event handlers because I had some type trouble with `onerror` callbacks in Flow (type annotations). See https://github.com/facebook/flow/issues/3819

It seems to me that "ws" sends an `Error` object (`instanceof Error === true`) which has the properties "type" and "target" added to it? But it should be either of those:

- https://dom.spec.whatwg.org/#interface-event
- https://html.spec.whatwg.org/multipage/webappapis.html#errorevent

according to 

https://html.spec.whatwg.org/multipage/indices.html#event-error

which is linked from 

https://html.spec.whatwg.org/multipage/web-sockets.html#handler-websocket-onerror

I guess it works, but since I'm trying to get those darn types right and possibly even submit a pull request for the Flow default type library definitions for `WebSocket` I want to understand what's going on with this stuff.

**Comment by lpinca** [comment]
Yes, we are currently using an `Error` instance instead of a proper `ErrorEvent`.
It might makes sense to fix this but it would be a breaking change.
