### ISSUE TITLE
How to send websocket to specific client?

### ISSUE THREAD

**Issue by Donaut** [websockets/ws#1174]
# Hello.
**## How i can send websocket data to specific client?**

**Comment by Globik** [comment]
Like this:
var sendtoclients=true;
if(sendtoclients){
if(msg.target && msg.target !==undefined && msg.target.length !==0){
	console.log('sending target message to one user: ',msg)
wss.clients.forEach(function(el){
if(el.username==msg.target){
if(el && el.readyState==1) el.send(JSON.stringify(msg)
}})
}

**Comment by hydrogen-studio** [comment]
made the code easier to read:
`Like this:
var sendtoclients=true;
if(sendtoclients){
if(msg.target && msg.target !==undefined && msg.target.length !==0){
console.log('sending target message to one user: ',msg)
wss.clients.forEach(function(el){
if(el.username==msg.target){
if(el && el.readyState==1) el.send(JSON.stringify(msg)
}})
}`
