### ISSUE TITLE
Allow new `broadcastAllButMe` method on the `wss` object

### ISSUE THREAD

**Issue by ejwaibel** [websockets/ws#1180]
- [X] I've searched for any related issues and avoided creating a duplicate issue.

#### Description

Broadcast example for "everyone else" doesn't allow for same `broadcast` method against the `wss` object. 

#### Reproducible in:

version: 3.1.0
Node.js version(s): 6.11.1
OS version(s): OSX 10.12.2

#### Steps to reproduce:

1.
2.
3.

### Expected result:

Would like to call a method, like `wss.broadcast`, from outside the `.on('message')` that would broadcast the message to everyone except self. It seems the only example is putting the `wss.clients.forEach` inside the `.on('message')`, which doesn't allow me to call the broadcast from outside, such as an API route that has access to the `wss` object.

**Comment by lpinca** [comment]
The reason why the loop is inside the `'message'` event listener in the example is simple: You need to know which client to exclude.

A top level `broadcastAllButMe` would still need to know what client to exclude (me).

```js
wss.broadcastAllButMe = function (data, me) {
  // `me` is the WebSocket object to exclude.
  wss.clients.forEach(function each(client) {
      if (client !== me && client.readyState === WebSocket.OPEN) {
        client.send(data);
      }
    });
}
```

**Comment by ejwaibel** [comment]
@lpinca right, that's what I figured, and I was trying that, but this means that where ever I call `wss.broadcastAllButMe` would need to have a reference to the `ws` that is sending the broadcast. Is there a solution for this?

The problem I'm having is that my configuration for the websockets is in a file called "websocket.js" and I want to call a broadcast from an API route in another file called "players.js" that doesn't have reference to the websocket client.

**Comment by lpinca** [comment]
> this means that where ever I call wss.broadcastAllButMe would need to have a reference to the ws that is sending the broadcast. Is there a solution for this?

You can add an ID for each client and use that but somehow you have to identify the object you want to exclude. There is no way around that.

**Comment by ejwaibel** [comment]
👍
