### ISSUE TITLE
Uncaught exception: connect ECONNREFUSED [host]:[port]

### ISSUE THREAD

**Issue by webrtcn** [websockets/ws#1186]
` 
connect(addr){ 

       this.ws = new webSocket(addr);

        process.on('uncaughtException', (err) => { 

            console.log('Caught exception: ' + err.message); 

        });

}
` 

if addr not exists, I got a "Uncaught exception"

 Caught exception: connect ECONNREFUSED 10.101.126.121:44400
 And
 Caught exception: Cannot read property 'aborted' of null

I hope get a error like

this.ws.on('error',  function(err) {

});

Please fix the bug. 
thanks

**Comment by lpinca** [comment]
Please fill the issue template in particular the steps to reproduce the issue.
The following example works as expected on my machine:

```js
const WebSocket = require('ws');

const ws = new WebSocket('ws://localhost:80');

ws.on('error', (err) => console.error(err));
```

```
{ Error: connect ECONNREFUSED 127.0.0.1:80
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1045:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1161:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 80 }
```

**Comment by webrtcn** [comment]
@lpinca 
Thanks
I will try your code.
