### ISSUE TITLE
Connected Client list is not updated on connection close code 1001.

### ISSUE THREAD

**Issue by geek96** [websockets/ws#1187]
- [ ] I've searched for any related issues and avoided creating a duplicate issue.

#### Description
When connection closed by client with code 1001 the client state remain `readyState`  in the clients lists. Its causing issue when I am broadcast data to all connected clients. In this case server send duplicate content to the client.

#### Reproducible in:

version:
Node.js version(s): v 6.11.1
OS version(s): Ubuntu 16.04

#### Steps to reproduce:

```js
const wss = new WebSocket.Server({ port: 10000, path: '/path', clientTracking: true });

wss.on('connection', (ws, req) => {
  ws.on('message', (message) => {
    console.log('received: %s', message);
  });

  ws.on('close', () => {
    console.log('connection closed by client');
  });
});

setInterval(() => {
  const obj = { message: 'This is dummy text from socket server' };

  console.log(wss.clients.size);

  wss.clients.forEach((client) => {
    if (client.readyState === WebSocket.OPEN) {
      client.send(JSON.stringify(obj));
    }
  });
}, 3000);
```

### Expected result:
Client state should be `closed`.

### Actual result:

Client state remain `open`.

**Comment by lpinca** [comment]
`readyState` is [set to `WebSocket.CLOSING`](https://github.com/websockets/ws/blob/a1ac65994d59d46feb7b93ab1f91cd658394e301/lib/WebSocket.js#L281) as soon as a [close frame](https://github.com/websockets/ws/blob/a1ac65994d59d46feb7b93ab1f91cd658394e301/lib/WebSocket.js#L152) is received from the client.

If you print `readyState` in you `'close'` event listener you'll see that it's `3` (`WebSocket.CLOSED`).

**Comment by geek96** [comment]
You are right in `close` event listener `readystate` is closed. But its not updated in `clients` list.

**Comment by lpinca** [comment]
Please show us a reproducible test case. In your example it's not clear when the connection gets closed.
In your example you are broadcasting as soon as the connection is established so `readyState` is expected to be `WebSocket.OPEN` at least for the just established connection.

**Comment by geek96** [comment]
I have updated the code. I am using default websocket client, Whenever I click on browser reload button. On the server side `close` listener triggered and that time `readystate` is `3`. As I am broadcasting message every `3000ms` , there should be one client in list but clients list increase on each reload from the browser.

**Comment by lpinca** [comment]
I've cleaned up your code and ran it on localhost. It works as expected, the list does not grow on every refresh and

```js
console.log(wss.clients.size);
```

always prints 1.
