### ISSUE TITLE
the ablity to parse req with express session middleware on per req base

### ISSUE THREAD

**Issue by calidion** [websockets/ws#1188]
- [ x ] I've searched for any related issues and avoided creating a duplicate issue.

#### Description

fail to parse req with session middleware

#### Steps to reproduce:

```
    wss.on("connection", async (ws, req) => {
       await sessionMiddleware(req, {})
       // req.session should be properly assigned with right values.
    });
```

### Expected result:

correctly parse session info.

### Actual result:

fail to parse session info.

**Comment by lpinca** [comment]
How is this a `ws` issue?

The `req` object in your example is the `http.IncomingMessage` argument of the [`'upgrade'`](https://nodejs.org/dist/latest/docs/api/http.html#http_event_upgrade) event. This seems an issue with the session middleware or how you are using it.

**Comment by calidion** [comment]
althought i have now hacked it, but it would be good to provide a way to easily provide a session for ws. 

I have integrated the following code into my web framework, and have tested with several `express-session` based session stores. 

```
    let cookies = req.headers.cookie;
    let store =  // getSessionStore

    if ( cookies && store) {
      let id = cookies.split("=");
      id = id[1];
      id = decodeURIComponent(id);
      id = id.split(".")[0].split(":")[1];
      let getSession = promisify(store.get);
      let session = await getSession.call(store, id);
      req.session = session;
    }
```

It would be somewhat difficult a ws server to integrate with a session.
But as i have seen that the ws server creation process has provided a way for session handling, i think it would be good to provide a way to handle a ws session on per connection base.

**Comment by lpinca** [comment]
While useful I think it's out of the scope of the library and it depends on the framework/store used. An external module would be better imho. Maybe there are already some on npm.

**Comment by lpinca** [comment]
Closing for now.
