### ISSUE TITLE
Serving Multiple Paths on Same Port

### ISSUE THREAD

**Issue by physiii** [websockets/ws#1189]
Someone brought up trying to use different paths on the same port in 2012: https://github.com/websockets/ws/issues/21

you talked about examples, can't you link to them? 

I do not want to use a proxy to solve this problem. Can we set multiple paths for the same server instance?

 something like:
var WebSocketServer = require('ws').Server
var wss1 = new WebSocketServer({ port: 1234, path:'/a' });
var wss2 = new WebSocketServer({ port: 1234, path:'/b' });

**Comment by lpinca** [comment]
See https://github.com/websockets/ws/pull/885#issue-187590719.
