### ISSUE TITLE
When a client disconnects not gracefully, how do you notice it on the server ?

### ISSUE THREAD

**Issue by joaojeronimo** [websockets/ws#119]
When a client is connected to the server and closes a tab or the browser, the "close" event will fire on the server, but if the browser crashes or he looses the internet connection, how does the server know it happened ?

I'm asking this because for me and the thing I'm working on, catching these things is as important as catching the "close" event...

Other than this the only way I can think of that will tell me if the user's browser has exited non gracefully, is catching the exception of ws.send() or using its callback... Am I right about this ?

**Comment by dankle** [comment]
We are having a big problem with this in our project as well. Since we can't send PINGS too often we are relying on the ws.send() callback which doesn't work.

**Comment by boynet** [comment]
+1

**Comment by n4ru** [comment]
I believe I'm having this issue. non-graceful closes are leading to crashes despite try/catch and on error handlers.

**Comment by Mo33n** [comment]
+1

**Comment by lpinca** [comment]
There are cases where the only way to detect that a connection has been closed is via a heartbeat system which can be implemented, for example, by sending [pings](https://tools.ietf.org/html/rfc6455#section-5.5.2).

**Comment by nalvarezdomingo** [comment]
You can't be sure of connection sending ping, because some ip can be online but not connected to your websocket.

**Comment by lpinca** [comment]
@nalvarezdomingo pings in this context are not icmp packets, but special WebSocket frames as specified by the protocol.
