### ISSUE TITLE
Client to Server connections are not masked as per RFC6455

### ISSUE THREAD

**Issue by d3x0r** [websockets/ws#1194]
- [X] I've searched for any related issues and avoided creating a duplicate issue.

#### Description

Client data to server MUST be masked according to.....
https://tools.ietf.org/html/rfc6455#section-5.3

  Masking-key:  0 or 4 bytes

      **All frames sent from the client to the server** are masked by a
      32-bit value that is contained within the frame.  This field is
      present if the mask bit is set to 1 and is absent if the mask bit
      is set to 0.  See Section 5.3 for further information on client-
      to-server masking.

#### Reproducible in:

version: all
Node.js version(s): doesn't matter
OS version(s): any

#### Steps to reproduce:

1. create a websocket client
2.send data.
3. observe with network monitor.

### Expected result:

Websocket Text and Binary frames (and control frames that have data like Close) should be masked.

### Actual result:

None of the client to server frames are masked.  

### History
I did a search for websock benchmark and found a Javascript package 'Thor'  It uses 'ws' as its default websocket provider.  I was testing against 'uws' npm, and it refused to receive frames.  Bug report to them was unhelpful as the owner is ..(omitted)....   and merely claimed he was expecting 4 bytes.

Today I was attempting to discover why there was an issue with uws receiving data, and with my own library I had by default enabled masking on client to server connections, so everything worked (the Thor test was using a 1000 byte array buffer with 0's, and I managed to send the same data without issue)  I then realized while looking at the protocol in wireshark that I was masking the data.  I added an option to allow disabling the default behavior, and uws stopped receiving said buffer, merely because it was not masked.  Now while it is true that uws should also be updated to throw an error on receiving a non-masked frame, 'ws' should be masking all frames from a client to a server as per the spec.

**Comment by d3x0r** [comment]
The RFC states that clients MUST mask, but does not define behavior if they do not.  The current behavior may be acceptable (that is, if the packet is not masked, do not complain and just use it in the server instance).

Although; if masking is enforce client to server, server side should generate a error if receiving unmasked client data.  

These close statuses may be applicable.

1003
1003 indicates that an endpoint is terminating the connection
because it has received a type of data it cannot accept (e.g., an
endpoint that understands only text data MAY send this if it
receives a binary message).

1007
1007 indicates that an endpoint is terminating the connection
because it has received data within a message that was not
consistent with the type of the message (e.g., non-UTF-8 [RFC3629]
data within a text message).

1008
1008 indicates that an endpoint is terminating the connection
because it has received a message that violates its policy. This
is a generic status code that can be returned when there is no
other more suitable status code (e.g., 1003 or 1009) or if there
is a need to hide specific details about the policy.

1011
1011 indicates that a server is terminating the connection because
it encountered an unexpected condition that prevented it from
fulfilling the request.

**Comment by Nibbler999** [comment]
Thor disables masking, see observing/thor/issues/8

**Comment by d3x0r** [comment]
I see :) thanx.
