### ISSUE TITLE
connections Set allows duplicates instances from same client

### ISSUE THREAD

**Issue by coffee-mug** [websockets/ws#1195]
- [X] I've searched for any related issues and avoided creating a duplicate issue.

#### Description

First, thanks to all contributors for the amazing work, it's a real pleasure to work with this lib. 

I am new to websocket, so sorry in advance if it sounds silly, but I am writing a small chat app, and I log the connections count from the server console. 

I get the count without problems, still, if I keep opening connections from the client tab (Chrome 52) through the standard Web Socket constructor function, the server count keeps increasing. Is that normal, as the wss.clients is actually a Set ? 

#### Reproducible in:

version: ws ^3.1.0
Node.js version(s): 7.8.0
OS version(s): Ubuntu 16.04

#### Steps to reproduce:

```
// Server code
const app = express();
const server = http.createServer(app);
const wss = new WebSocket.Server({ server });

wss.on('connection', (ws) => {
    console.log(`Connection size ${wss.clients.size}`);
})

server.listen(8000, () => console.log(`Listening on ${server.address().port}`);
```

```
// Client code

for (var i = 0; i < 3; i++) { var ws = new WebSocket('ws://localhost:8000') }
```

### Expected result:
// Server console should display, I guess : 
Connection size: 1
Connection size: 1
Connection size: 1

### Actual result:
Connection size: 1
Connection size: 2
Connection size: 3

My problem here is that if instead of 3 I let the loop run 10000 times, it will eventually make the server hang and blocks new connections. 

Two ideas came to my mind : 

    - I thought of creating another Set, fed with a client unique attribute for the Set to work, but I don't find a unique connection property in the Socket object. 

    - I've also thought of using the verifyConnection, but don't know yet how to manage it. 

Thanking you again for the great work, I am open for any help on this matter. Thanks !

**Comment by lpinca** [comment]
Yes this is normal, every new connection is unique.

Your operating system may limit the number of open file descriptor imposing a limit on the number of connection but you can increase this limit. You can find more info on Google.

If you are opening many connections from the same machine you also have to distribute them across multiple network interfaces using the `localAddress` on the client.

**Comment by coffee-mug** [comment]
@lpinca Thanks a lot for the reactivity !

Ok for the file descriptor limit, I'll google it. 

So, if I get it correctly, as a mean of defense against someone creating many ws connection, I have to distribute them accrosse network interfaces, using client localAdress. 

Would it be sufficient in your mind to prevent the server from blocking ?

**Comment by lpinca** [comment]
> So, if I get it correctly, as a mean of defense against someone creating many ws connection, I have to distribute them accrosse network interfaces, using client localAdress.

No, you can't do that as you are not the one creating the connections. You can close those connection immediately during the handshake (see the `verifyClient` hook) or use something to stop the denial-of-service if that is the problem.

**Comment by coffee-mug** [comment]
Ok, I'll look at the verifyClientHook then. Thanks a lot @lpinca ! I wish you a great day
