### ISSUE TITLE
Security Issue

### ISSUE THREAD

**Issue by edouardbrossette** [websockets/ws#1196]
https://github.com/websockets/ws/blob/6663b89cd7c19269c6f9a527e96f3cd7db0c5fea/lib/WebSocketServer.js#L163

Split need to be protected against potential 'array' type param.

Sec-WebSocket-Protocol is normaly served for multi protocol like this :

Sec-WebSocket-Protocol: protocolOne, protocolTwo

but you can also serve it like this :

Sec-WebSocket-Protocol: protocolOne
Sec-WebSocket-Protocol: protocolTwo

Already test with a telnet request on last node version 8.4.0 and node concat req.header 'sec-websocket-protocol': 'protocolOne, protocolTwo' id two  => so there is no issue.

GET ws://localhost:8080/ HTTP/1.1
Host: localhost:8080
Connection: Upgrade
Upgrade: websocket
Sec-WebSocket-Version: 13
Sec-WebSocket-Key: 
Sec-WebSocket-Protocol: protocolOne, protocolTwo

But not certain this is done on all node version. No time to test, sorry. Better would be to verify that req.headers['sec-websocket-protocol'] is a string before split. or check potential error.

**Comment by lpinca** [comment]
AFAIK the property values of the `req.headers` are always strings.

**Comment by lpinca** [comment]
From https://nodejs.org/dist/latest-v8.x/docs/api/http.html#http_message_headers

> Duplicates in raw headers are handled in the following ways, depending on the header name:
>
> - Duplicates of age, authorization, content-length, content-type, etag, expires, from, host, if-modified-since, if-unmodified-since, last-modified, location, max-forwards, proxy-authorization, referer, retry-after, or user-agent are discarded.
> - set-cookie is always an array. Duplicates are added to the array.
> - For all other headers, the values are joined together with ', '.
