### ISSUE TITLE
Set-Cookie client

### ISSUE THREAD

**Issue by KyKyIIIKuH** [websockets/ws#1200]
Interested in the question of how to assign cookies to users such as id from the database that they are assigned?
if there is for example an array with connected clients

```
wss.on('headers', function(headers) {
    var cookie = require('cookie');
    headers.push('Set-Cookie: ' + cookie.serialize('id_user', 'ID from the database' ) );
});
```

When you execute the following code, the cookie is assigned to everyone who has connected to the server

**Comment by lpinca** [comment]
The `'headers'` event it emitted before sending the http response to a **single** client/connection.
If you use a different id for each connection your code should work fine.

**Comment by KyKyIIIKuH** [comment]
And then how to determine which client is connected if the array contains `wss` ?

**Comment by lpinca** [comment]
> And then how to determine which client is connected if the array contains `wss` ?

I'm not sure I understand. The listener of the `'headers'` event takes two argument, the headers array and an `http.IncomingMessage` which is http GET request sent by the client. You can use this to know which client is connecting if this is what you want.
