### ISSUE TITLE
Referencing info available in verifyClient in the client object

### ISSUE THREAD

**Issue by phaistonian** [websockets/ws#1203]
Hello.

I think the title does it, but is there any way to either access this info without using the verifyClient or accessing the client itself from the verifyClient method so I can pass the info to it?

ps: sorry for not using the template.

**Comment by lpinca** [comment]
@phaistonian you can add the required "info" to the `request` object that is passed as second argument to the `'connection'` event.

```js
wss.on('connection', (ws, request) => {
  // request is the same `http.IncomingMessage` instance you have in `info.req`.
});
```

**Comment by phaistonian** [comment]
@lpinca Figured out this out a moment later after I filed this issue; silly me.

Sorry for the trouble.
