### ISSUE TITLE
When server option`s clientTracking is false, server.close() will never trigger the callback.

### ISSUE THREAD

**Issue by mx601595686** [websockets/ws#1205]
I think this place may be having a problem . When clientTracking is **false**, the server will not to track clients, so the `this.clients` is undefined, all of the connected sockets will not be terminated, so the server will wait forever before the callback was triggered.
> WebSocketServer.js
```
  /**
   * Close the server.
   *
   * @param {Function} cb Callback
   * @public
   */
  close (cb) {
    //
    // Terminate all associated clients.
    //
    if (this.clients) {
      for (const client of this.clients) client.terminate();
    }
```

**Comment by lpinca** [comment]
@mx601595686 it is expected. If `clientTracking` is falsy it's up to the user/application to close the open connections.
