### ISSUE TITLE
Tagging ws in the wss.clients object

### ISSUE THREAD

**Issue by paulddrix** [websockets/ws#1212]
Is there a way to tag the _ws_ with an id in the _verifyClient_ function so that it can be used in the _wss.connection_ event with the _wss.clients_ ?
I need to be able to search the _wss.clients_ object for a specific _ws_

so something like this:

```
function verifyClient(info, done){
 // authorize user
// tag the ws with and id
done(true);

}

wss.on('connection', (ws, req) => {
// find the ws in wss.clients with an specific id
wss.clients.forEach(function each(client) {
      if (clien.id === '<someid>') {
        client.send(data);
      }
});
```
Thank you all for your time and support.

**Comment by lpinca** [comment]
Hi,
you can do something like this:

```js
function verifyClient(info, done) {
  info.req.mytag = 'gaqu1Osh';
  done(true);
}

wss.on('connection', (ws, req) {
  ws.mytag = req.mytag;
  delete req.mytag;
});
```

**Comment by paulddrix** [comment]
Let me try that and see if it shows up in the _wss.clients_, thank you for your fast response.
