### ISSUE TITLE
netty server / node.js client - websocket hang up error

### ISSUE THREAD

**Issue by donnydarko** [websockets/ws#1216]
* **Version**: 5.3.0
* **Platform**: Windows 7 Pro SP1 64bit
* **Subsystem**: 

https://stackoverflow.com/questions/46721436/netty-server-node-js-client-websocket-hang-up-error
```

- 47 45 54 20 2F 25 37 44 2F 77 73 2F 20 48 54 54 ; GET /%7D/ws/ HTT
- 50 2F 31 2E 31 0D 0A 53 65 63 2D 57 65 62 53 6F ; P/1.1..Sec-WebSo
- 63 6B 65 74 2D 56 65 72 73 69 6F 6E 3A 20 31 33 ; cket-Version: 13
- 0D 0A 53 65 63 2D 57 65 62 53 6F 63 6B 65 74 2D ; ..Sec-WebSocket-
- 4B 65 79 3A 20 57 30 67 77 4E 52 44 4B 4E 76 53 ; Key: W0gwNRDKNvS
- 74 53 73 78 32 68 78 75 79 73 77 3D 3D 0D 0A 43 ; tSsx2hxuysw==..C
- 6F 6E 6E 65 63 74 69 6F 6E 3A 20 55 70 67 72 61 ; onnection: Upgra
- 64 65 0D 0A 55 70 67 72 61 64 65 3A 20 77 65 62 ; de..Upgrade: web
- 73 6F 63 6B 65 74 0D 0A 48 6F 73 74 3A 20 31 32 ; socket..Host: 12
- 37 2E 30 2E 30 2E 31 3A 38 36 38 33 0D 0A 0D 0A ; 7.0.0.1:8683....
```
```
const WebSocket = require('ws');
let url = "ws://127.0.0.1:8683/ws";
let ws = new WebSocket(url, {perMessageDeflate: false});
ws.on('open', ()=> { console.log('open'); });
ws.on('message', (msg)=> { console.log('received: '+msg); });
ws.on('error', (error)=> { console.log(error); });
ws.on('close', ()=> { console.log('closed');});
```
Result:

> Error: socket hang up
> closed

My client websockets implementation in chrome still connects perfectly without problem.... this only happens with node sockets.

**Comment by lpinca** [comment]
Try to skip ws and use the built-in `http` module:

```js
const request = http.get({
  port: 8683,
  path: '/ws',
  headers: {
    upgrade: 'websocket',
    connection: 'Upgrade',
    'Sec-WebSocket-Key': 'rfeGe1izPRq2JyonWunAQw==',
    'Sec-WebSocket-Version': 13
  }
});

request.on('upgrade', (res, socket, head) => console.log('upgraded'));
request.on('error', (err) => console.error(err));
```

Let us know if you still get the error.

**Comment by donnydarko** [comment]
Thanks for answering :)
This is what I'm getting now:

```
47 45 54 20 2F 77 73 20 48 54 54 50 2F 31 2E 31 ; GET /ws HTTP/1.1
0D 0A 75 70 67 72 61 64 65 3A 20 77 65 62 73 6F ; ..upgrade: webso
63 6B 65 74 0D 0A 63 6F 6E 6E 65 63 74 69 6F 6E ; cket..connection
3A 20 55 70 67 72 61 64 65 0D 0A 53 65 63 2D 57 ; : Upgrade..Sec-W
65 62 53 6F 63 6B 65 74 2D 4B 65 79 3A 20 72 66 ; ebSocket-Key: rf
65 47 65 31 69 7A 50 52 71 32 4A 79 6F 6E 57 75 ; eGe1izPRq2JyonWu
6E 41 51 77 3D 3D 0D 0A 53 65 63 2D 57 65 62 53 ; nAQw==..Sec-WebS
6F 63 6B 65 74 2D 56 65 72 73 69 6F 6E 3A 20 31 ; ocket-Version: 1
33 0D 0A 48 6F 73 74 3A 20 6C 6F 63 61 6C 68 6F ; 3..Host: localho
73 74 3A 38 36 38 33 0D 0A 0D 0A                ; st:8683....
```

Result:

> upgraded
> closed

No error, but the client it self closes immediately after upgrade.

**Comment by lpinca** [comment]
I'm not sure why it gets closed immediately.
How did you get "close" on the console? Did you add a listener for the `'close'` event to the `socket`?

**Comment by donnydarko** [comment]
yes, Ι added an onClose handler  to your code... and at the server side I got an exception of connection closed by client

**Comment by donnydarko** [comment]
I solved the problem (using the hardcoded way) by modifying node_modules/ws/WebSocket.js
Line 596:
Line 698:
```
    if (serverUrl.path.charAt(0) !== '/') {
      requestOptions.path = '/ws';//`/${serverUrl.path}`;
    } else {
      requestOptions.path = '/ws';//serverUrl.path;
    }
```
and now it doesn't send GET /%7D/ at the handshake and everything goes smooth.

**Comment by lpinca** [comment]
@donnydarko weird, did you try to log `serverUrl.path` in the `else` branch? I would add an assertion there like `assert(serverUrl.path === '/ws')` to see if that's the issue.

**Comment by donnydarko** [comment]
it returns 
```
    console.log("serverUrl="+serverUrl.path);

    if (serverUrl.path.charAt(0) !== '/') {
      
      requestOptions.path = '/ws';//`/${serverUrl.path}`;
    } else {
      requestOptions.path = '/ws';//serverUrl.path;
    }
```
Result (at the console):

> serverUrl=%7D/ws

**Comment by donnydarko** [comment]
It also does the same if I ask something else than /ws
```
let url = `ws://${ip}:${port}}/somethingelse`;
let ws = new WebSocket(url);
```

> serverUrl=%7D/somethingelse

**Comment by lpinca** [comment]
Then I guess it's something in url parser.
Can I ask you to run

```js
var url = require('url');
var u = url.parse("ws://127.0.0.1:8683/ws");
console.log(u.path);
```

in the Node.js REPL or a script?
What version of Node.js are you running?

**Comment by donnydarko** [comment]
node v8.6.0
I put your code after all my requires and it returns just /ws

**Comment by donnydarko** [comment]
I just installed the latest version v8.7.0 and it does the same issue

**Comment by donnydarko** [comment]
omg I'm so silly
`let url = `ws://${ip}:${port}}/ws`;`
I had a second } on the url

**Comment by lpinca** [comment]
Yes that makes sense :)

**Comment by lpinca** [comment]
Closing as the mystery has been solved.
