### ISSUE TITLE
Detection of TCP backpressure/flow control

### ISSUE THREAD

**Issue by kevincharm** [websockets/ws#1218]
- [x] I've searched for any related issues and avoided creating a duplicate issue.

Possibly related to: #492 #602

#### Description

Hi! Ran into this issue a few months ago. A slow WebSocket client (consumer) can block up a `ws` server, and AFAIK there is no means of detecting backpressure/flow control that you could use to pause the connection or otherwise.

This problem appeared when the client was Python, on Linux 4.x (we tried most of the python websocket libs). After much debugging, we found that the `Recv-Q` kernel buffer was growing indefinitely on the client, which in turn was starting to block up the outgoing buffers on the `ws` server's network stack, and finally the server just stopped sending messages. In the end, the actual issue that was slowing down the client was a very slow synchronous JSON parse of the WebSocket message. However; this is irrelevant if you are providing a WebSocket API and have no control over what your client does.

My fix was to propagate the return value of `socket.write` and also the `drain` event on the TCP layer to the `ws` API. This way, you could stop sending messages when you detect TCP backpressure, and wait for a `drain` event before resuming sending messages to the slow client.

Please check out the diff at: https://github.com/websockets/ws/compare/master...kevincharm:feature/propagate-backpressure
This is not in the WebSocket spec, however it doesn't break the existing API and I suspect it will become a problem in the future with more IoT devices integrating into the web. If you guys are interested in having this upstream, I will rebase my branch to latest and create a PR. Cheers!

**Comment by lpinca** [comment]
Hey,
yes you are right, handling backpressure is very important. I had a quick look at you code and it seems good but I think there are a couple of issues when permessage-deflate is enabled:

- Why are you returning [`true`](https://github.com/kevincharm/ws/blob/c0181ce4e49c54b46f25118ee7b9ca0c6472727b/lib/Sender.js#L375) when a message is enqueued?
- Why are you returning [`true`](https://github.com/kevincharm/ws/blob/c0181ce4e49c54b46f25118ee7b9ca0c6472727b/lib/Sender.js#L349) when the sender is compressing a message?

Currently the proper way to handle this is by using the `WebSocket#send()` callback which is invoked when the data is written out. For example the `websocket-stream` module uses a "proxy" stream which implements `_write` as follow:

https://github.com/maxogden/websocket-stream/blob/1a140a8e492d3011b09868e98c130f6fe9669536/stream.js#L103-L115

**Comment by kevincharm** [comment]
Yes, you are right! Those `return true`s should be removed, along with the `flushed` expecting a return value from `this.enqueue` and `this.dispatch`.

My memory is hazy, but I do recall trying the approach you mentioned, by using the [callback](https://nodejs.org/dist/latest-v6.x/docs/api/net.html#net_socket_write_data_encoding_callback) to throttle socket writes. It seemed to have different behaviour (callback gets invoked when the write returns false - or something like that). Perhaps I need to dig up node's TCP implementation and test it again.

**Comment by kevincharm** [comment]
I've been able to use the `websocket-stream` package you linked to detect and handle backpressure in the same way @lpinca. Thanks!
