### ISSUE TITLE
Server example for binary data

### ISSUE THREAD

**Issue by cn007b** [websockets/ws#1222]
#### Description

It isn't an issue I'd rather call it request...

In your README.md file, you have an example "Sending binary data" and this example contains only client, and you don't have server example for binary data. Could you please provide server example for binary data.

### Expected result:

README.md file contains server example for binary data.

**Comment by lpinca** [comment]
You can take the https://github.com/websockets/ws#server-example, it's the same.

```js
const WebSocket = require('ws');

const wss = new WebSocket.Server({ port: 8080 });

wss.on('connection', function connection(ws) {
  ws.on('message', function incoming(message) {
    // If the client sends binary data `message` is a `Buffer` by default.
  });

  const data = Buffer.from('binary data');
  ws.send(data); // You can also use a `TypedArray` an `ArrayBuffer`, etc.
});
```

**Comment by cn007b** [comment]
But it won't work(((

[Client](https://github.com/websockets/ws#sending-binary-data):

````
const WebSocket = require('ws');
const ws = new WebSocket('ws://localhost:5432/binary');
ws.on('open', function open() {
  const array = new Float32Array(5);
  for (var i = 0; i < array.length; ++i) {
    array[i] = i / 2;
  }
  ws.send(array);
});
````

Server:

````
const WebSocket = require('ws');
const wss = new WebSocket.Server({ port: 5432 });
wss.on('connection', function connection(ws) {
  console.log('Established new binary connection.');
  ws.on('message', function incoming(message) {
    console.log('Received message:');
    console.log(message);
    console.log(new Buffer(message, 'base64').toString());
    console.log(Buffer.from(message));
  });
});
````

Result:

````
Established new binary connection.
Received message:
<Buffer 00 00 00 00 00 00 00 3f 00 00 80 3f 00 00 c0 3f 00 00 00 40>
?�?�?@
<Buffer 00 00 00 00 00 00 00 3f 00 00 80 3f 00 00 c0 3f 00 00 00 40>
````

Maybe I've missed something... But I just can't find solution...

**Comment by lpinca** [comment]
You have to convert the received `Buffer` to a `Float32Array` if you want a `Float32Array` again, for example:

```js
const ab = message.buffer.slice(message.byteOffset, message.byteOffset + message.byteLength);
const array = new Float32Array(ab);
```

**Comment by cn007b** [comment]
Now it works! Thank you so much! 🙂
Does it make sense to add your code into readme file, maybe someone in the future also will be seeking this?

**Comment by lpinca** [comment]
The documentation already covers what are the possible types of a message so it seems a bit redundant, but I'm not against that. Feel free to submit a PR if you think it will useful for others.

**Comment by cn007b** [comment]
Ok, sounds like a plan!)
Just need to find something reasonable with strings, like pack JSON string into binary on client and unpack on the server side...

**Comment by lpinca** [comment]
Closing this, discussion can continue on the closed thread.
