### ISSUE TITLE
[Question] Impact of Latency on websocket streams

### ISSUE THREAD

**Issue by binarykitchen** [websockets/ws#1232]
Wondering if there is any prior research on latency here?

Considering moving the www.videomail.io server to another country which will increase latency for 90% of all my clients. Because www.videomail.io relies heavily on your websocket code, I'd be better careful here. How badly will more latency impact on websocket performance? Or can this be ignored since it affects initial page load only?

My question reworded and simplified: how will a higher latency like 30 more milliseconds impact websocket performance?

**Comment by lpinca** [comment]
AFAIK no prior research has been done for this module but I think you will not notice any difference.

**Comment by lpinca** [comment]
Closing, discussion can continue on the closed thread.
