### ISSUE TITLE
Extensions parser does not handle quoted values

### ISSUE THREAD

**Issue by jcoglan** [websockets/ws#1235]
- [x] I've searched for any related issues and avoided creating a duplicate issue.

#### Description

While inspecting the changes made in 3.3.1 to prevent the DOS problem caused by extension names clashing with `Object.prototype`, I discovered the extension parser does not handle quoted values. This allows a client to submit a malformed `Sec-WebSocket-Extensions` header that the server interprets as valid, and the server accepts a header it should refuse.

#### Reproducible in:

version: 3.3.1
Node.js version(s): 8.9.1
OS version(s): macOS Sierra

#### Steps to reproduce:

Start a `ws` server on port 7000 with `perMessageDeflate: true`. Then install `faye-websocket` and run this script:

```js
var WebSocket = require('faye-websocket').Client;

var ws = new WebSocket('ws://localhost:7000/', [], {
  headers: {
    'Sec-WebSocket-Extensions': 'x; y=",permessage-deflate; client_max_window_bits,"'
  }
});

ws.onerror = function(error) {
  console.log('[error]', error.message);
};
```

### Expected result:

The server does not accept the client's extension offer and no `Sec-WebSocket-Extensions` header is returned.

### Actual result:

The server accepts the client's offer and it returns a `Sec-WebSocket-Extensions` header indicating that `permessage-deflate` has been activated. The client raises an error since it did not initiate this extension.

**Comment by lpinca** [comment]
Yes, the parser is naïve and not spec compliant. We should definitely rewrite it.
