### ISSUE TITLE
Unable to connect to secure websocket endpoint using proxy when using node-v9.1.0

### ISSUE THREAD

**Issue by xshyamx** [websockets/ws#1239]
#### Description

Unable to connect to secure websocket through a proxy endpoint when using node-v9.1.0 but, the same works in node-v8.7.0 & node-v8.9.0

#### Reproducible in:

**version:**
Node.js version(s): 9.1.0
OS version(s): OSX, Darwin Kernel Version 16.7.0

**Dependency Versions:**
https-proxy-agent: 2.1.0
ws: 3.3.1

#### Steps to reproduce:

1. Run the following code in node v8.7.0 and v9.1.0
   ``` js
   var WebSocket = require('ws'),
       url = require('url'),
       HttpsProxyAgent = require('https-proxy-agent'),
       endpointUrl = 'wss://websocketstest.com/service',
       opts = {};
   
   
   if ( !!process.env.https_proxy ) {
     console.log('Setting up proxy', process.env.https_proxy)
     opts.agent = new HttpsProxyAgent(url.parse(process.env.https_proxy))
   }
   console.log(JSON.stringify(process.versions, null, 2))
   var socket = new WebSocket(endpointUrl, opts);
   socket.on('open', function(){
     console.log('Socket opened')
   });
   socket.on('error', function(err){
     console.log(err)
   });
   socket.once('message', function(){
     socket.send('version,', function(err){
       if ( err ) {
         console.log('Failed to send message');
       } else {
         console.log('Sent message successfully')
       }
     });
   });
   socket.on('message', function(data){
     console.log('Received', data)
   });
   socket.on('close', function(){
     console.log('Socket closed')
   });
   
   setTimeout(function(){
     console.log('Closing')
     socket.terminate();
   }, 5000);
   
   ```
2. On running with node-v8.9.1
   ``` text
   Setting up proxy http://10.0.2.2:3128
   {
     "http_parser": "2.7.0",
     "node": "8.9.1",
     "v8": "6.1.534.47",
     "uv": "1.15.0",
     "zlib": "1.2.11",
     "ares": "1.10.1-DEV",
     "modules": "57",
     "nghttp2": "1.25.0",
     "openssl": "1.0.2m",
     "icu": "59.1",
     "unicode": "9.0",
     "cldr": "31.0.1",
     "tz": "2017b"
   }
   Socket opened
   Received connected,
   Sent message successfully
   Received version,hybi-draft-13
   Closing
   Socket closed
   ```
3. On running with node-v9.1.0
   ``` text
   Setting up proxy http://10.0.2.2:3128
   {
     "http_parser": "2.7.0",
     "node": "9.1.0",
     "v8": "6.2.414.32-node.8",
     "uv": "1.15.0",
     "zlib": "1.2.11",
     "ares": "1.13.0",
     "modules": "59",
     "nghttp2": "1.25.0",
     "openssl": "1.0.2m",
     "icu": "59.1",
     "unicode": "9.0",
     "cldr": "31.0.1",
     "tz": "2017b"
   }
   Error: unexpected server response (400)
       at ClientRequest._req.on (/app/node_modules/ws/lib/WebSocket.js:649:26)
       at emitOne (events.js:125:13)
       at ClientRequest.emit (events.js:221:7)
       at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:550:21)
       at HTTPParser.parserOnHeadersComplete (_http_common.js:117:23)
       at Socket.socketOnData (_http_client.js:439:20)
       at emitOne (events.js:125:13)
       at Socket.emit (events.js:221:7)
       at addChunk (_stream_readable.js:265:12)
       at readableAddChunk (_stream_readable.js:252:11)
   Socket closed
   Closing
   ```

**Comment by lpinca** [comment]
Sounds like an external issue that needs investigation. Maybe `https-proxy-agent` doesn't work with Node.js 9.x and needs to be updated.

**Comment by xshyamx** [comment]
@lpinca You are right it is a problem with `node-agent-base` which is a dependency of `https-proxy-agent`

After some digging around found a clue [here](https://github.com/TooTallNate/node-agent-base/blob/e66f64cb58f2132d390711ce2dda8c05825cfecc/patch-core.js) where the `secureEndpoint` is supposed to be set but, is not set.

But, adding `secureEndpoint` to the `requestOptions` fixes the problem. 

https://github.com/xshyamx/ws/commit/b87ffdb3f8572e48b7c84f5f2f37fded9a37b1d4

**Comment by lpinca** [comment]
Can this be fixed in `node-agent-base`? Why is that option no longer set?

**Comment by lpinca** [comment]
The problem is that `agent-base` monkey patches only [`https.request()`](https://github.com/TooTallNate/node-agent-base/blob/e66f64cb58f2132d390711ce2dda8c05825cfecc/patch-core.js) but `ws` uses `https.get()`.

In Node.js < 9.0.0, `https.get()` uses the overridden `https.request()` so it works, but since https://github.com/nodejs/node/commit/5118f3146643dc55e7e7bd3082d1de4d0e7d5426#diff-dc1e3006797f52c8d34db55abaf1fe7e, `https.get()` no longer uses the patched `https.request()`, thus the issue.

I can think of two possible ways to fix this:

1. Use `http(s).request()` instead of `http(s).get()` in `ws`.
2. Monkey patch `https.get()` in `agent-base`.

The latter is probably better as it would make `agent-base` work with `https.get()` and not `https.request()`.

In the meanwhile you can use [`tunnel`](https://github.com/koichik/node-tunnel) which works similarly to `https-proxy-agent`.

```js
const tunnel = require('tunnel');
const WebSocket = require('ws');
const setup = require('proxy');

const proxy = setup();

proxy.listen(function () {
  const ws = new WebSocket('wss://websocketstest.com/service', {
    agent: new tunnel.httpsOverHttp({
      proxy: {
        hostname: '127.0.0.1',
        port: proxy.address().port
      }
    })
  });

  ws.on('open', function () {
    console.log('open');
  });
});
```

**Comment by xshyamx** [comment]
Thanks @lpinca. Will try it out

**Comment by lpinca** [comment]
@xshyamx fyi `agent-base@4.1.2` has just been released. It includes https://github.com/TooTallNate/node-agent-base/commit/7de92df780e147d46185281d26a1b534b3aaa97e which should fix this issue.
