### ISSUE TITLE
Wrong extentions property type

### ISSUE THREAD

**Issue by dcharbonnier** [websockets/ws#1244]
The extension property of the client return an object, the websocket api expect a string.

https://github.com/websockets/ws/blob/4e7d48aafec4ad85958e4c5171db2fd2b0e85ea4/lib/WebSocket.js#L53 

[MDN documentation](https://developer.mozilla.org/en-US/docs/Web/API/WebSocket)

| Attribute | Type | Description |
| --- | --- | --- |
|Extensions | DOMString | The extensions selected by the server. This is currently only the empty string or a list of extensions as negotiated by the connection.|

**Comment by lpinca** [comment]
We try to emulate the browser interface but in this case I don't see a reason to use a string.
We could use a private property for the extensions map and make `extensions` a getter.

```js
get extensions () {
  return Object.keys(this._extensions).join(',');
}
```

but again I don't see any real advantage.

**Comment by dcharbonnier** [comment]
I agree it's not so important for this property but in general I find it very interesting to have ws that implements Websocket as much as possible and it's already the case :+1: 
`const ws: typeof WebSocket = typeof (WebSocket) !== "undefined" ? WebSocket : require("ws");`

Making this a getter would make ws behave like the WebSocket specifications from what I know and I could remove one test here https://github.com/dcharbonnier/advanced-websocket/blob/develop/src/Waterfall.ts#L49

Was just to let you know, feel free to close it if you want.

**Comment by lpinca** [comment]
I see, feel free to open a PR.
