### ISSUE TITLE
method broadcast issue

### ISSUE THREAD

**Issue by killerlayup** [websockets/ws#1248]
#### Description

when I use method braodcast to broadcast msg to clients, but sometimes the clients seem not be ready as ````client.readyState```` is 2. Here is my code:

````

wss.broadcast = function broadcast(data) {
            try {
                console.log('length = ' + wss.clients.length);
                wss.clients.forEach(function each(client) {
                    console.log('readyState = ' + client.readyState);
                    if (client.readyState === ws.OPEN) {
                        client.send(data);
                    }
                });
            } catch (e) {
                console.log(e);
            }
            
        };

````

here is the log:

````
2|fe-vms   | length = 2
2|fe-vms   | readyState = 1
2|fe-vms   | readyState = 2

````

it seems one of the clients is not ready for send msg.
This is infrequent, with a probability of about 25%.

Is anyone have an idea about this?

thanks

**Comment by lpinca** [comment]
From a quick look there is nothing wrong. The WebSocket is `CLOSING` and is no longer writable.

**Comment by killerlayup** [comment]
I mean I don't close the websocket on purpose, but **sometimes** it shows the websocket is closing.  I think it is wired and abnormal, maybe something is wrong with using ws. Do you have meet this situation before?

**Comment by lpinca** [comment]
The client can close the connection at any time so unless you are directly controlling all your clients in a reliable environment, this is normal.

**Comment by killerlayup** [comment]
I mean, why does the client close the connection with no sign? 
when  I  start a connection from page like:

````
let ws = new WebSocket('ws://' + ip + ':' + port + '/ws/user');
ws.onopen = function(){
        if(ws && ws.readyState === 1){
                ws.send([self.userInfo.headImg, id]);
        }
}
````
 but sometimes `ws.readyState` is not 1 ( at close status).  I am confused that when is the websocket closed and when is open? 

Sorry to disturb you.

**Comment by lpinca** [comment]
The TCP connection can be closed for many reasons. Under normal circumstances the close procedure is initiated by the WebSocket client or server but this is not always the case.

> but sometimes ws.readyState is not 1 ( at close status)

The `readyState` attribute reflects the state of the WebSocket. It can't be `1` if the WebSocket is closing or closed.

**Comment by lpinca** [comment]
In the above code the `readyState` check is redundant as it is always `OPEN` (`1`) when the `'open'` event is emitted.

**Comment by killerlayup** [comment]
OK, I get it.
However I am still confused that the why websocket  client's status is closed?
here is my procedure:
````
1. let ws = new WebSocket('ws://' + ip + ':' + port + '/ws/user');
2. ws.send([self.userInfo.headImg, id]);
````

It is quite simple but **sometimes** it shows error in the console:
````
WebSocket is already in CLOSING or CLOSED state.
````

Why WebSocket client is sometimes closed or closing when I instantiate an object ws and try to send message to server.

This situation is infrequent, with a probability of about 25%.

What should I do to solve this problem?

**Comment by lpinca** [comment]
You have to wait the `'open'` event.

```js
const ws = new WebSocket(url);
ws.onopen = () => ws.send(data);
```

If you get that error in the `onopen` callback, I don't know, make sure you are using the same `WebSocket` instance, the one you just created.
