### ISSUE TITLE
Websockets are timing out after idling

### ISSUE THREAD

**Issue by mayeaux** [websockets/ws#1254]
If I don't send a message via the socket it ends up dying within a minute and a half

That's fine for one connection I'm making because I'll just send some rubbish filler text, but the other I'd like to actually send a legitimate message back to the client when I send a message

How can I stop my websocket from idling and timing out ? Thanks

**Comment by lpinca** [comment]
Are you using a proxy like NGINX? if so this probably caused by your proxy.
You can increase the idle timeout or periodically send a ping message to prevent the socket from being closed.

Anyway this doesn't seem an issue in ws. Please don't post general support question here.

**Comment by mayeaux** [comment]
I was just figuring there was a setting in the API for it that I couldn't find in the documentation, but yeah I'm using NGINX so I'll look into that, thanks
