### ISSUE TITLE
No way to know when socket buffer is full

### ISSUE THREAD

**Issue by jfriend00** [websockets/ws#1255]
There does not appear to be any way to know when a webSocket you are sending to has a full OS buffer (and consequently you need to wait for a drain event before sending some more).  With regular node.js net.socket, .write() returns a boolean that indicates whether the system buffer is full or not and if it's full, you can then wait for a drain event.  But, the sendFrame() method does not return the result of this._socket.write() so there is no way for that to propagate back to the caller of socket.send().

FYI, original question surfaced here: https://stackoverflow.com/questions/47843543/what-is-websockets-net-connect-write/47848281#47848281

**Comment by lpinca** [comment]
You can use the callback of `WebSocket.prototype.send()`, see https://github.com/maxogden/websocket-stream/blob/48dc3ddf943e5ada668c31ccd94e9186f02fafbd/stream.js#L90-L102 for example.

The [`bufferedAmount`](https://github.com/websockets/ws/blob/6a6ae04ef3514e2f8b1b0890649523d59dcf27f4/doc/ws.md#websocketbufferedamount) attribute can also be used to stop writing when the buffer grows too much.

**Comment by lpinca** [comment]
See also discussion in https://github.com/websockets/ws/issues/1218.

**Comment by lpinca** [comment]
Closing this, discussion can continue on the closed thread.
