### ISSUE TITLE
Empty closing handshake should use 1005 error code

### ISSUE THREAD

**Issue by TimothyGu** [websockets/ws#1257]
- [x] I've searched for any related issues and avoided creating a duplicate issue.

#### Description

Currently, the `Receiver` class treats an empty closing control message as if it is a closing handshake with code 1000:

https://github.com/websockets/ws/blob/157f58a73250674eb57c505a522c7e5fe5fb3bee/lib/Receiver.js#L405

However, per [RFC 6455 "The WebSocket Protocol"](https://tools.ietf.org/html/rfc6455):

> #### [7.1.5. The WebSocket Connection Close Code](https://tools.ietf.org/html/rfc6455#section-7.1.5)
> If this Close control frame contains no status code, _The WebSocket Connection Close Code_ is considered to be 1005.

> #### [7.4.1.  Defined Status Codes](https://tools.ietf.org/html/rfc6455#section-7.4.1)
>  <dl><dt>1005<dt><dd>1005 is a reserved value and MUST NOT be set as a status code in a       Close control frame by an endpoint.  It is designated for use in     applications expecting a status code to indicate that no status       code was actually present.

I am currently attempting to integrate this module into [jsdom](https://github.com/tmpvar/jsdom). The current behavior runs against the behavior expected by [closing-handshake/003.html](https://github.com/w3c/web-platform-tests/blob/master/websockets/closing-handshake/003.html) of Web Platform Tests, which is a test suite run by web browsers and jsdom. All major web browsers return 1005 as the status code.

#### Reproducible in:

version: 3.3.3
Node.js version(s): 9.2.0
OS version(s): Linux 4.9.0-4-amd64 Debian 4.9.65-3 (2017-12-03) x86_64 GNU/Linux (Debian 9.3)

#### Steps to reproduce:

```js
'use strict';

const WebSocket = require('ws');

const ws = new WebSocket('ws://w3c-test.org:82/echo');
ws.on('open', () => {
  ws.close();
  ws.on('close', (code, reason) => {
    console.log(code, reason);
  });
});
```

### Expected result:

The script should print `1005 ''`.

### Actual result:

The script prints `1000 ''`.

**Comment by lpinca** [comment]
It is easy to fix, I'm only worried about the breakage it can cause.

**Comment by TimothyGu** [comment]
Well, this is a bug, and bugs need to be fixed. Just because a fix is semver-major doesn’t mean it can’t get applied. That would be a sad state of affairs. Plus, it is difficult and fragile to monkeypatch this on the user’s side.

**Comment by lpinca** [comment]
Sure, I'm planning to make other server-major changes in the coming days and release version 4.0 with a fix for this issue.
How urgent is this fix for you?

**Comment by TimothyGu** [comment]
Awesome. It's not very urgent but would be nice to get a timetable on it. It's being used in https://github.com/tmpvar/jsdom/pull/2088, which will probably need a few weeks for others to review

**Comment by lpinca** [comment]
Ok, it shouldn't take too long. I think a week (or two) is sufficient.
