### ISSUE TITLE
Can't connect through wss 

### ISSUE THREAD

**Issue by cymruu** [websockets/ws#1264]
#### Description
I have code like this
```js
var options = {};
if (fs.existsSync('./certs')) {
    options.key = fs.readFileSync('./certs/privatekey.key');
    options.cert = fs.readFileSync('./certs/certificate.crt');
  if(fs.existsSync('./certs/ca_bundle.crt')){
    options.ca = fs.readFileSync('./certs/ca_bundle.crt');
  }
}
const httpsServer = https.createServer(options, (req, res) => {
  res.writeHead(200);
  res.end('hello world\n');
});
var wss = new WebSocketServer({server: httpsServer, port: 1030});
```

And it looks like the server is not listening for wss connections. I can connect using ws protocol, but wss doesn't work. It used to work on version 2.x.x Doesn't work on the most recent one. 
#### Reproducible in:

version: 3.3.3
Node.js version(s): 8.4, 8.9.1, 4.8.6
OS version(s): FreeBSD 11.1-RELEASE-p4 amd64, Windows 10

![obraz](https://user-images.githubusercontent.com/2981598/34360754-029f2b32-ea64-11e7-87f4-efd9adaccc80.png)

**Comment by lpinca** [comment]
If you use the `port` option the `WebSocketServer` will create and use its own HTTP server.
To use the HTTPS server, you have to remove the `port` option and use it in the [`server.listen()`](https://nodejs.org/dist/latest/docs/api/https.html#https_server_listen) method instead.

**Comment by cymruu** [comment]
@lpinca Thank you very much. That solved my issue.
```js
var options = {};
if (fs.existsSync('./certs')) {
    options.key = fs.readFileSync('./certs/privatekey.key');
    options.cert = fs.readFileSync('./certs/certificate.crt');
  if(fs.existsSync('./certs/ca_bundle.crt')){
    options.ca = fs.readFileSync('./certs/ca_bundle.crt');
  }
}
const httpsServer = https.createServer(options, (req, res) => {
  res.writeHead(200);
  res.end('hello world\n');
});
httpsServer.listen(1030);
var wss = new WebSocketServer({server: httpsServer});
```
