### ISSUE TITLE
support question - do we need to use getConnections()

### ISSUE THREAD

**Issue by ORESoftware** [websockets/ws#1268]
I would have guessed we need to use

```js
wss.getConnections(function(err, clients){
   clients.forEach();
});

```
but it looks like we can just use

```js
wss.clients.forEach();
```

**Comment by lpinca** [comment]
[`server.getConnections()`](https://nodejs.org/dist/latest/docs/api/net.html#net_server_getconnections_callback) returns the number of connections on the server.

There is no such thing on `WebSocketServer`, you can use `wss.clients.size`.

**Comment by ORESoftware** [comment]
ok thx!
