### ISSUE TITLE
ECONNRESET on server side

### ISSUE THREAD

**Issue by ORESoftware** [websockets/ws#1269]
I have this code:

```js
const {Server} = require('ws');
const wss = new Server({port: 6969});

wss.on('connection', function (ws) {
  console.log('new connection');
});

wss.on('disconnect', function (ws) {
  console.log('client disconnected');
});
```

I keep getting ECONNRESET and the process just shuts down with that error. Why does that need to happen? 

I know for a fact that the client has "abruptly closed the connection", but why does my server need to crash in that case?

**Comment by ORESoftware** [comment]
ok so if I add this in the browser:

`socket.close();`

then the ECONNRESET issue on the server goes away. However, if the browser crashes and the connection is not closed properly, does my server really need to crash?

I tried adding an error handler:

```js
const wss = new Server({port: 6969});

wss.on('error', function (e) {
  console.error(e.message);
});
```

that didn't prevent the server and process from crashing.

**Comment by ProgrammingLife** [comment]
ORESoftware, try to put that "on" on the ws, not wss. I mean to put it inside 'connection' function (ws.on....).

**Comment by ORESoftware** [comment]
ok will do thanks, that's probably it

**Comment by lpinca** [comment]
Duplicate of https://github.com/websockets/ws/issues/1256.
FWIW I filed an issue here: https://bugs.chromium.org/p/chromium/issues/detail?id=798194#c3

**Comment by ORESoftware** [comment]
nice, ok cool thanks, will close
