### ISSUE TITLE
Error: not opened

### ISSUE THREAD

**Issue by ztiandan** [websockets/ws#1274]
```
Error: not opened
    at WebSocket.send (/var/www/html/site_avalokitesvara/node_modules/ws/lib/WebSocket.js:360:18)
    at Tb.send (/var/www/html/site_avalokitesvara/app/extend/h5service.patch.js:1827:25)
    at Tb.pingAP (/var/www/html/site_avalokitesvara/app/extend/h5service.patch.js:1907:16)
    at Tb.timerCheck (/var/www/html/site_avalokitesvara/app/extend/h5service.patch.js:1900:37)
    at Timeout.<anonymous> (/var/www/html/site_avalokitesvara/app/extend/h5service.patch.js:1928:13)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5) } reason: Error: not opened
    at WebSocket.send (/var/www/html/site_avalokitesvara/node_modules/ws/lib/WebSocket.js:360:18)
    at Tb.send (/var/www/html/site_avalokitesvara/app/extend/h5service.patch.js:1827:25)
    at Tb.pingAP (/var/www/html/site_avalokitesvara/app/extend/h5service.patch.js:1907:16)
    at Tb.timerCheck (/var/www/html/site_avalokitesvara/app/extend/h5service.patch.js:1900:37)
    at Timeout.<anonymous> (/var/www/html/site_avalokitesvara/app/extend/h5service.patch.js:1928:13)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)

  ```

System: Centos 7.4
Language: Nodejs 8.9.4

System configuration
[root@web-1 log]# cat /etc/sysctl.conf

```
fs.file-max = 1000000
vm.overcommit_memory = 1
net.ipv4.ip_local_port_range = 1024 65535
net.ipv4.tcp_fin_timeout = 1
net.ipv4.tcp_keepalive_time = 1200
net.ipv4.tcp_mem = 94500000 915000000 927000000
net.ipv4.tcp_tw_reuse = 1
net.ipv4.tcp_tw_recycle = 1
net.ipv4.tcp_timestamps = 0
net.ipv4.tcp_synack_retries = 1
net.ipv4.tcp_syn_retries = 1
net.ipv4.tcp_abort_on_overflow = 0
net.core.rmem_max = 16777216
net.core.wmem_max = 16777216
net.core.netdev_max_backlog = 262144
net.core.somaxconn = 65535
net.ipv4.tcp_max_orphans = 3276800
net.ipv4.tcp_max_syn_backlog = 262144
net.core.wmem_default = 8388608
net.core.rmem_default = 8388608
```

[root@web-1 log]# cat /etc/security/limits.conf
```
* hard nofile 1000000
* soft nofile 1000000
root hard nofile 1000000
root soft nofile 1000000
```

When i create connections about 1W+, system can not use curl get any response, and i felt maybe fd limits or any thing, but i did't know what i need to do to resolve this problem
```
[root@web-1 log]# lsof -p 1441 | wc
  10524  105213 1255001

[root@web-1 log]# ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 30724
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1000000
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 30724
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
[root@web-1 log]# curl www.baidu.com
```

**Comment by lpinca** [comment]
Check the `readyState` before sending data

```js
if (ws.readyState === WebSocket.OPEN) {
  ws.send(data);
}
```

or use a callback

```js
ws.send(data, (err) => console.error);
```

**Comment by ztiandan** [comment]
is there any limits on concurrent websockets? on my system only about 9K+ connections can work, i have opt my system, but don't know what i need to do?

cpu and memory only use 20%

**Comment by lpinca** [comment]
I think you already increased the maximum number of file descriptor correctly. Are the client connections created from the same machine and from the same address? If so you need to use multiple interfaces. Something like this should work:

```js
const WebSocket = require('ws');

let i = 0;
(function createClient() {
  const ws = new WebSocket('ws://localhost:3000', {
    localAddress: `127.0.0.${i % 100 + 1}`
  });

  ws.on('open', () => {
    if (++i === 50000) return;
    createClient();
  });
})();
```

**Comment by ztiandan** [comment]
yes, same machine same address, i'll try you suggestion, could u inform me why only 9k websockts 1 interfaces can not handle? 1 interface can handle 65535 connection? i do really want to understand it.

**Comment by lpinca** [comment]
Yes, you can only have a limited number of outgoing connection from a single interface. I don't know what the exact number is and I guess it depends on the OS but it's limited to a few thousands.

**Comment by ztiandan** [comment]
I was disable selinux, firewall, no iptables installed, does it will affect connection performance?

**Comment by lpinca** [comment]
I can't tell, try with that stuff enabled and disabled and see if there is any difference.

**Comment by ztiandan** [comment]
> it depends on the OS but it's limited to a few thousands
could u tell me the name of limit, i wanna research it.

**Comment by lpinca** [comment]
The theoretical maximum is 32768 (32768-65535) as most OS only create ephemeral source ports starting at port 32768. In practice that number is smaller. As far as I know there is no way to configure this.

**Comment by lpinca** [comment]
Closing this as I see nothing wrong in ws. Discussion can continue if needed but this issue tracker is not a support forum so please use it only to report bugs or feature requests.

**Comment by ztiandan** [comment]
`[root@web-1 site_avalokitesvara]# ifconfig 
ens160: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.255.210.84  netmask 255.255.255.0  broadcast 10.255.210.255
        inet6 fe80::997c:fa81:8942:2647  prefixlen 64  scopeid 0x20<link>
        ether 00:0c:29:6c:74:09  txqueuelen 1000  (Ethernet)
        RX packets 2685004  bytes 376131435 (358.7 MiB)
        RX errors 0  dropped 33  overruns 0  frame 0
        TX packets 3117802  bytes 294231973 (280.6 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1  (Local Loopback)
        RX packets 218  bytes 15171 (14.8 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
`
`[root@web-1 site_avalokitesvara]# cat /etc/sysconfig/network-scripts/ifcfg-ens160 
TYPE="Ethernet"
PROXY_METHOD="none"
BROWSER_ONLY="no"
BOOTPROTO="none"
DEFROUTE="yes"
IPV4_FAILURE_FATAL="no"
IPV6INIT="yes"
IPV6_AUTOCONF="yes"
IPV6_DEFROUTE="yes"
IPV6_FAILURE_FATAL="no"
IPV6_ADDR_GEN_MODE="stable-privacy"
NAME="ens160"
UUID="7472eca9-dc67-434f-bc4e-22ecb9274ddb"
DEVICE="ens160"
ONBOOT="yes"
# IPADDR="10.255.210.84"
# IPADDR1="10.255.210.85"
PREFIX="24"
GATEWAY="10.255.210.1"
IPV6_PRIVACY="no"
`
`[root@web-1 site_avalokitesvara]# ping 10.255.210.85
PING 10.255.210.85 (10.255.210.85) 56(84) bytes of data.
64 bytes from 10.255.210.85: icmp_seq=1 ttl=64 time=0.028 ms
64 bytes from 10.255.210.85: icmp_seq=2 ttl=64 time=0.033 ms
64 bytes from 10.255.210.85: icmp_seq=3 ttl=64 time=0.029 ms
`
my vm use 10.255.210.84, added 10.255.210.85

in node code

`let wsOpt = {
	agent: new HttpsProxyAgent(url.parse(this.mod.globals.proxyAddr)),
	handshakeTimeout: 15000,
	rejectUnauthorized: false
}

if (global.h5ServiceMap.size > 5000){
    wsOpt['localAddress'] = '10.255.210.85';
}

this.wsSock = new WebSocket(this.wsAddr, wsOpt);`

After these changed, i want to find the connections with 10.255.210.85
` netstat -antup | grep 10.255.210.85` 

not found

all connections using  10.255.210.84, like this

`tcp        0      0 10.255.210.84:31557     125.211.211.174:23499   ESTABLISHED 1458/node           
tcp        0      0 10.255.210.84:16433     125.211.211.134:18756   ESTABLISHED 1458/node           
tcp        0      0 10.255.210.84:41332     125.211.211.155:19376   ESTABLISHED 1458/node           
tcp        0      0 10.255.210.84:35002     125.211.211.176:21913   ESTABLISHED 1458/node           
tcp        0      0 10.255.210.84:42957     125.211.211.170:24176   ESTABLISHED 1458/node           
tcp        0      0 10.255.210.84:23539     125.211.211.175:23382   ESTABLISHED 1458/node           
tcp        0      0 10.255.210.84:22685     125.211.211.155:24855   ESTABLISHED 1458/node           
tcp        0      0 10.255.210.84:45144     125.211.211.171:20245   ESTABLISHED 1458/node`

anything wrong on my code or sys config?
