### ISSUE TITLE
Error during WebSocket handshake: Unexpected response code: 200

### ISSUE THREAD

**Issue by Hclmaster** [websockets/ws#1275]
Hi,
I want to build a wss protocol in my server, I use nginx to help me achieve that.
But when I want to reach that wss url, it gave me the error "Error during WebSocket handshake: Unexpected response code: 200", I have searched online for solutions, but none of them seem work for me.
## Here is my nginx configuration file：
```
user  appuser appuser;
worker_processes 2;

error_log  logs/error.log;

pid        /usr/local/webserver/nginx/nginx.pid;

events {
    use epoll;
    worker_connections  40960;
}


http {

    log_format main '$remote_addr - $remote_user [$time_local] '
            '"$request" $status $body_bytes_sent '
            '$cookie_uid "$http_referer" "$http_user_agent" "$http_x_forwarded_for" $upstream_addr $upstream_response_time $request_time';

    include       mime.types;
    default_type  application/octet-stream;

    charset utf-8;

    server_names_hash_bucket_size 128;
    client_header_buffer_size 32k;
    large_client_header_buffers 4 64k;
    client_max_body_size 8m;
    client_header_timeout   1800;
    client_body_timeout     1800;

    tcp_nopush     on;
    tcp_nodelay on;
    keepalive_timeout 60;
    fastcgi_intercept_errors on;
    fastcgi_connect_timeout 300;
    fastcgi_send_timeout 300;
    fastcgi_read_timeout 300;
    fastcgi_buffer_size 64k;
    fastcgi_buffers 4 64k;
    fastcgi_busy_buffers_size 128k;
    fastcgi_temp_file_write_size 128k;

#    open_file_cache max=65535 inactive=10s;
#    open_file_cache_valid 30s;
#    open_file_cache_min_uses 1;

    gzip on;
    gzip_min_length  1k;
    gzip_buffers     4 16k;
    gzip_http_version 1.1;
    gzip_comp_level 2;
    gzip_types       text/plain application/x-javascript text/css application/xml application/javascript;
    gzip_vary on;
    gzip_disable "MSIE [1-6]\.";

    proxy_connect_timeout 90;
    proxy_send_timeout 90;
    proxy_read_timeout 90;
    proxy_buffer_size 4k;
    proxy_buffers 4 32k;
    proxy_busy_buffers_size 64k;
    proxy_temp_file_write_size 64k;


    index index.html index.htm index.php;
    include /usr/local/webserver/nginx/conf.d/*.conf;
}
```

## I included the wss.conf file here:
```
upstream websocket{
	server 106.12.18.131;
}
upstream web{
	server dev.bieok.top;
}

# 通过下面的反响代理到上面的接口去
server{
	listen 443;
	ssl on;
	ssl_certificate /usr/local/webserver/nginx/conf/cert/server.pem;
	ssl_certificate_key /usr/local/webserver/nginx/conf/cert/server.key;
	ssl_session_timeout 5m;
	ssl_session_cache shared:SSL:50m;
	ssl_protocols SSLv3 SSLv2 TLSv1 TLSv1.1 TLSv1.2;
	ssl_ciphers ALL:!ADH:!EXPORT56:RC4+RSA:+HIGH:+MEDIUM:+LOW:+SSLv2:+EXP;
	underscores_in_headers on;#开启自定义头信息的下划线
	#wss协议转发 小程序里面要访问的链接
	location /mqtt {
		proxy_pass http://websocket; #代理到上面的地址去
		proxy_set_header Host dev.bieok.top;
		proxy_http_version 1.1;
		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header Connection "Upgrade";
		add_header Access-Control-Allow-Origin *;#跨域访问设置
	}
	#https协议转发 
	location / {
		proxy_pass http://web;
		proxy_set_header   X-Real-IP        $remote_addr;
		proxy_set_header   X-Forwarded-For  $proxy_add_x_forwarded_for;
		add_header Access-Control-Allow-Origin *;
	}
}
```

As I want to use the wss protocol url in the wechat app as follows:
![_20180108221626](https://user-images.githubusercontent.com/16880879/34674841-686eaec0-f4c2-11e7-8b27-f5b6ac4c69c5.png)
But it gave me the error that I'm very confused about:
![_20180108222440](https://user-images.githubusercontent.com/16880879/34674932-bed424b6-f4c2-11e7-95de-df2dd524a785.png)

Can anyone give me some advice?

**Comment by lpinca** [comment]
```
location /mqtt { ... }
```

but your connection url does not include the `/mqtt` pathname so I guess the request is proxied to `http://web` thus the error.

**Comment by lpinca** [comment]
Closing this as I see nothing wrong in ws. Discussion can continue if needed but this issue tracker is not a support forum so please use it only to report bugs or feature requests.

**Comment by Hclmaster** [comment]
Thanks for the quick reply, but as I add /mqtt pathname to the request url, it gave me the 404 error. It seems very curious, and I can't figure out why this happening :(
![image](https://user-images.githubusercontent.com/16880879/34709636-efbf4fb6-f552-11e7-9aac-1bffc4f2ec3f.png)

**Comment by lpinca** [comment]
Your url in the screenshot has a `/wss` pathname but it should be `/mqtt`. Is that the result of a redirect?

**Comment by bugs181** [comment]
Had this issue myself. It should be noted that some invalid URLs will get this error. For example, I forgot to add the colon to my address between host and port, which processed it as `wss://hostport`. Hope this saves someone the trouble of tracking this sneaky issue down.
