### ISSUE TITLE
set localAddress param not working

### ISSUE THREAD

**Issue by ztiandan** [websockets/ws#1276]
I set 10.255.210.86 in code, but it seems not working, still use prev ip 10.255.210.84.

Node: 8.9.4 ws: 3.3.3  
System config
```
[root@web-1 ~]# ifconfig -a
ens160: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.255.210.84  netmask 255.255.255.0  broadcast 10.255.210.255
        inet6 fe80::997c:fa81:8942:2647  prefixlen 64  scopeid 0x20<link>
        ether 00:0c:29:6c:74:09  txqueuelen 1000  (Ethernet)
        RX packets 499  bytes 36048 (35.2 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 139  bytes 42478 (41.4 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

ens160:0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.255.210.86  netmask 255.255.255.0  broadcast 10.255.210.255
        ether 00:0c:29:6c:74:09  txqueuelen 1000  (Ethernet)

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1  (Local Loopback)
        RX packets 6  bytes 504 (504.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 6  bytes 504 (504.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

my code
```
let wsOpt = {
  agent: new HttpsProxyAgent(url.parse(this.mod.globals.proxyAddr)),
  handshakeTimeout: 15000,
  localAddress: '10.255.210.86',
  rejectUnauthorized: false,
}

this.wsSock = new WebSocket(this.wsAddr, wsOpt);
```
```
netstat -antup
```
```
tcp        0      0 10.255.210.84:36576     125.211.211.171:18187   ESTABLISHED 1462/node           
tcp        0      0 10.255.210.84:18262     125.211.211.170:21438   ESTABLISHED 1462/node           
tcp        0      0 10.255.210.84:23489     125.211.211.175:18640   ESTABLISHED 1462/node           
tcp        0      0 10.255.210.84:25770     125.211.211.176:19905   ESTABLISHED 1462/node           
tcp        0      0 10.255.210.84:41199     125.211.211.171:24938   ESTABLISHED 1462/node           
tcp        0      0 10.255.210.84:61717     125.211.211.176:21612   ESTABLISHED 1462/node           
```
10.255.210.84 be used? 
Agent (HttpsProxyAgent) be used for this websocket, is it problem?

**Comment by lpinca** [comment]
The `localAaddress` option works, we have a [test](https://github.com/websockets/ws/blob/be3717e29dd95c121cebe1f41f213d5c427823fb/test/websocket.test.js#L67-L90) for it.

I'm not sure what's wrong in your setup, could it be the proxy agent?

**Comment by lpinca** [comment]
I _think_ [`https-proxy-agent`](https://github.com/TooTallNate/node-https-proxy-agent) does not handle the `localAddress` option.

**Comment by ztiandan** [comment]
is there a solution for me? use proxy and localAddress same time.

**Comment by lpinca** [comment]
Instead of passing a string to the constructor, you can try passing an options object as documented [here](https://github.com/TooTallNate/node-https-proxy-agent#new-httpsproxyagentobject-options). Include the `localAddress` option in that options object.

**Comment by ztiandan** [comment]
changed my code, seems not working.
```
let virtualIp = '10.255.210.86';

let proxyOpt = url.parse(this.mod.globals.proxyAddr);
proxyOpt.localAddress = virtualIp;

let wsOpt = {
  agent: new HttpsProxyAgent(proxyOpt),
  handshakeTimeout: 15000,
  localAddress: virtualIp,
  rejectUnauthorized: false
}
```

**Comment by lpinca** [comment]
I don't know, try to monkey patch https-proxy-agent and see if the options are passed correctly here https://github.com/TooTallNate/node-https-proxy-agent/blob/c58d365dd153104d1147967a0a6b4e1dd1698e50/index.js#L72-L77.

You can try to use another module like https://github.com/request/tunnel-agent or https://github.com/koichik/node-tunnel.

**Comment by ztiandan** [comment]
thanks for u tips, i'll try it.

**Comment by ztiandan** [comment]
I have one question, when i pass localAddress to https-proxy-agent, do i need to pass it to ws too?

**Comment by lpinca** [comment]
I think it doesn't make any difference.

**Comment by ztiandan** [comment]
after test, only use localAddress with ws it works, add https-proxy-agent, did't work, as your mention proxy can add additional params for net.connect function, i had passed localAddress to it, but not work, i don't know what the issue from? Nodejs, https-proxy-agent or ws, and what i need to do, could u give me any suggestion, figure out this issue my project will be done, thank you very much.

**Comment by ztiandan** [comment]
I changed proxy from [https-proxy-agent](https://github.com/TooTallNate/node-https-proxy-agent) to [node-tunnel](https://github.com/koichik/node-tunnel), they are all works when without localAddress params with ws, [node-tunnel](https://github.com/koichik/node-tunnel) support localAddress by param, but didn't work, it confuse me, [node-tunnel](https://github.com/koichik/node-tunnel) support localAddress, [ws](https://github.com/websockets/ws) also, how could i make them work together?

**Comment by lpinca** [comment]
It seems to work fine:

```
[luigi@fedora gh-1276]$ cat server.js 
const http = require('http');
const WebSocket = require('ws');

const server = http.createServer();
const wss = new WebSocket.Server({ server });

wss.on('listening', () => {
  console.log('WebSocket server listening on 127.0.0.1:8080');
});

server.listen(8080, '127.0.0.1');
[luigi@fedora gh-1276]$ 
[luigi@fedora gh-1276]$ 
[luigi@fedora gh-1276]$ cat proxy.js 
const http = require('http');
const setup = require('proxy');

const server = setup(http.createServer());

server.on('connect', (req, socket) => {
  console.log(socket.remoteAddress); // => 127.0.0.2 as expected
});

server.on('listening', () => {
  console.log('Proxy server listening on 127.0.0.1:3000');
});

server.listen(3000, '127.0.0.1');
[luigi@fedora gh-1276]$ 
[luigi@fedora gh-1276]$ 
[luigi@fedora gh-1276]$ cat client.js 
const HttpsProxyAgent = require('https-proxy-agent');
const WebSocket = require('ws');

const agent = new HttpsProxyAgent({
  hostname: 'localhost',
  port: 3000,
  localAddress: '127.0.0.2'
});

const ws = new WebSocket('ws://localhost:8080', { agent });

ws.on('open', () => {
  console.log('connected');
});
[luigi@fedora gh-1276]$
```
The proxy server prints 127.0.0.2 as expected.

**Comment by ztiandan** [comment]
Thank you very very much for your code, maybe anything wrong in my code, i'll research it by your code, is it need proxy server must support any params? like localAddress?

**Comment by lpinca** [comment]
I'm going to close this because there isn't anything actionable here.

**Comment by ttodua** [comment]
quite old topic, but as this issue was referenced from a chain of other answers, for the sake of completeness, i'll add a small change, as the proxy snippet should look like this now:
```
const http = require('http');
const createProxy = require ('proxy').createProxy;
const server = createProxy(http.createServer());
const port = 9877; // sudo ufw allow 9877
server.listen(port, () => {
  var port = server.address().port;
  console.log('HTTP(s) proxy server listening on port %d', port);
});
```
