### ISSUE TITLE
close WebSocket.Server within nodeJS due to problems with Plesk

### ISSUE THREAD

**Issue by schlaubumms** [websockets/ws#1277]
- [X] I've searched for any related issues and avoided creating a duplicate issue.

#### Description

Don´t think this is a bug but i don´t know where to ask for this.
I develope a little game on a Plesk powered environment, running on CentOS. All software is newest expect the node.js because i had errors on the npm installs, so i read it is better to go to the last working version. So i did.

I made a nodeJS app within a websocket Server which i connect from a single client. If i use a special port to define the websocket, all works. Now comes the bad news. If i restart the nodeJS App for this, the App can´t open a websocket with the same port, because it is already open. But i can´t close this, except i restart the complete server. For my developtment it is necessary to restart the App several times and i don´t want to have multiple websockets open.

So, my question is: is there a command to deactivate the previous websocket with the same port, if the app restarts?

NOTE: there is no possibility to use normal shell commands like "kill -9 all" etc. I need a command within the js code in the app, which i didn´t find.

#### Reproducible in:

version: newest
Node.js version(s): 6.12.2
Plesk Onyx Version 17.5.3 Update #37
OS version(s): CentOS Linux 7.4.1708 (Core)‬

#### Steps to reproduce:

1. code websocket on nodeJS app and specify a port (as recommended)
2. press the restart Button in Plesk to restart the node
3. start the script to activate the app
4. get the error result

### Expected result:

Error: listen EADDRINUSE :::5556
    at Object.exports._errnoException (util.js:1020:11)
    at exports._exceptionWithHostPort (util.js:1043:20)
    at Server._listen2 (net.js:1262:14)
    at listen (net.js:1298:10)
    at net.js:1408:9
    at _combinedTickCallback (internal/process/next_tick.js:83:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:383:7)
    at startup (bootstrap_node.js:149:9)

**Comment by lpinca** [comment]
I don't know how Plesk work but the problem seems to be in how it restart the Node.js process. Why does it keeps the previous server alive?

You can try to use `WebSocketServer#close()`.

```js
const wss = new WebSocket.Server(options);
wss.close(callback);
```

**Comment by lpinca** [comment]
@schlaubumms any update?

**Comment by schlaubumms** [comment]
Hey, sry, tried hard the last time.

Solved the problem: kill -all node works to close all nodes and the websockets (for clear). A reload will start another instance of node. Plesk... ;)

**Comment by lpinca** [comment]
Ok, closing this then.
