### ISSUE TITLE
Client IP Not working

### ISSUE THREAD

**Issue by bioinfo35** [websockets/ws#1279]
const WebSocket = require('ws');

const wsss = new WebSocket.Server({ port: 2000 });

wsss.on('connection', function connection(ws, req) {
    console.log(req);
  const ip = req.connection.remoteAddress;
});

i get `req` is not defined 

- [ ] I've searched for any related issues and avoided creating a duplicate issue.

#### Reproducible in:

version:
Node.js version(s):
OS version(s):

#### Steps to reproduce:

1.
2.
3.

**Comment by lpinca** [comment]
Update you `ws` version to 3.0.0 or greater.

**Comment by bioinfo35** [comment]
i am using ws v 4.0
here is screenshot https://www.screencast.com/t/ESZdbNg5
i tested it on windows and ubuntu

**Comment by lpinca** [comment]
`npm info` queries the public registry, so you get the latest version.
Run `npm ls ws` from the root of your project to find out what version of `ws` you are actually using.

If you are on `ws@<3.0.0`, use `ws.upgradeReq` instead of `req`.

**Comment by bioinfo35** [comment]
Thank You @lpinca
