### ISSUE TITLE
Certificate pinning?

### ISSUE THREAD

**Issue by homakov** [websockets/ws#1281]
Is there any way to pin certificate when i contact someone's wss:// to avoid CA trust?

**Comment by lpinca** [comment]
There is no official way.
An hacky workaround could be something like this:

```js
const ws = new WebSocket(url);

ws._req.on('socket', function (socket) {
  socket.on('secureConnect', function () {
    const fingerprint = socket.getPeerCertificate().fingerprint;

    if (fingerprint !== validFingerprint) ws.close();
  });
});
```

**Comment by o2genum** [comment]
SSL pinning is possible in a non-hacky way.

[The `ws` docs](https://github.com/websockets/ws/blob/master/doc/ws.md#new-websocketaddress-protocols-options) say that it supports _any other option allowed in http.request() or https.request()._

So it supports passing the `checkServerIdentity` function that overrides certificate verification. Search for `checkServerIdentity` on the [Node 'https' module docs](https://nodejs.org/api/https.html) for an example of SSL pinning.

I believe this should be briefly covered in the `ws` docs, SSL pinning is a frequent use case for Electron apps.
