### ISSUE TITLE
Server.close Callback Failure: Server Continues to Run

### ISSUE THREAD

**Issue by shellscape** [websockets/ws#1288]
- [x] I've searched for any related issues and avoided creating a duplicate issue.

#### Description

It would appear that `WebSocket.Server` has an issue when attempting to close while an active client `WebSocket` is connected. In my tests, the `close()` method is called with `process.exit` as the callback. The process exits correctly, but the server continues to run in the background. This is a nasty bugbear, as any environment quickly spinning up and destroying/closing server instances will run into port conflicts, putting additional burden of portfinding on the script.

#### Reproducible in:

version: 4.0.0
Node.js version(s): 9.2.0
OS version(s): MacOS 10.13.2

#### Steps to reproduce:

This is the test script that I've been working from to reproduce the issue:

```js
'use strict';

const http = require('http');
const WebSocket = require('ws');

const server = http.createServer();
const host = '127.0.0.1';
const port = 8081;

let wss;

server.listen(1337, '127.0.0.1', () => {
  wss = new WebSocket.Server({ host, port });

  wss.on('connection', (socket) => {
    console.log('WebSocket Client Connected');
  });

  wss.on('listening', () => {
    setTimeout(() => {
      const ws = new WebSocket('ws://127.0.0.1:8081');
    }, 1000);
  });
});

for (const sig of ['SIGINT', 'SIGTERM']) {
  process.on(sig, () => {
    wss.close(() => {
      console.log(`Process Ended via ${sig}`);
      process.exit();
    });
  });
}

```

Running that snippet, waiting a few moments and hitting `CMD+C` produces the following console output:

```console
→ node ws
WebSocket Client Connected
```

That's correct output. In another terminal tab, I ran and got the following:

```console
→ netstat -vanp tcp | grep 8081
tcp4       0      0  127.0.0.1.8081         127.0.0.1.49790        ESTABLISHED 408077 146988   5583      0
tcp4       0      0  127.0.0.1.49790        127.0.0.1.8081         ESTABLISHED 408171 146988   5583      0
tcp4       0      0  127.0.0.1.8081         *.*                    LISTEN      131072 131072   5583      0
```

Also correct. Next, I hit `CMD+C` in the test script terminal to produce a `SIGINT`, which effected the console output as such:

```console
→ node ws
WebSocket Client Connected
^CProcess Ended via SIGINT
```

That would appear correct, and it's what we expect to happen. However, when running `netstat` again, we get:

```console
→ netstat -vanp tcp | grep 8081
tcp4       0      0  127.0.0.1.8081         127.0.0.1.49790        TIME_WAIT   408077 146988   5583      0
```

It would appear that the server is still waiting for something from the client that was connected.

### Expected result:

It's expected that the callback to `close()` would not be called until the server was actually terminated and closed. 

### Actual result:

The server continues to run in the background for several minutes (it's random; I've seen it take up to 20 minutes to finally release). This results in any subsequent attempt to start a server on that port throwing an `EADDRINUSE` error.

**Comment by lpinca** [comment]
The callback is [forwarded](https://github.com/websockets/ws/blob/b8900786c2925a43543751e6dcf8fec671ebe504/lib/websocket-server.js#L116) to [server.close()](https://nodejs.org/dist/latest/docs/api/http.html#http_server_close_callback) so I'm not sure if we can do anything about this.

**Comment by shellscape** [comment]
Damn. Do we have any accessors to easily tell if the server is in TIME_WAIT, or any way to abort that?

**Comment by lpinca** [comment]
You can access the server with the `_server` property but I think you can't do much with the public API.

Also I can't reproduce on macOS 10.11.6. I'll add a recording of my terminal in a bit.

**Comment by lpinca** [comment]
https://asciinema.org/a/eiLCOfh2S6IRZB271nyh8aiCm

**Comment by shellscape** [comment]
Hrm. I wonder if this is (another) issue with High Sierra then. If I don't connect a client socket to it, then it produces exactly the same results as your video. With the client connected, I get the results I pasted. Not sure where to look next on this one.

**Comment by lpinca** [comment]
I'll try on a different machine with Fedora later.

**Comment by lpinca** [comment]
I can partially reproduce the issue on this machine. I don't get the `EADDRINUSE` error. The server can be rebound as soon as the previous one closes, but the client connection goes in TIME_WAIT.

I thought that it was because `wss.close()` uses [`socket.destroy()`](https://nodejs.org/dist/latest-v9.x/docs/api/net.html#net_socket_destroy_exception) so I changed the example like this

```js
const WebSocket = require('ws');
const http = require('http');

const host = '127.0.0.1';
const port = 8081;

const server = http.createServer();
const wss = new WebSocket.Server({ server });

wss.on('connection', () => {
  console.log('WebSocket Client Connected');
});

server.listen(port, host, () => {
  setTimeout(() => {
    const ws = new WebSocket('ws://127.0.0.1:8081');
  }, 1000);
});

for (const sig of ['SIGINT', 'SIGTERM']) {
  process.on(sig, () => {
    console.log(sig);

    // Stop accepting new connections.
    server.close();

    // Close all clients gracefully.
    for (const ws of wss.clients) ws.close();
  });
}
```

but it doesn't make any difference. I'll try to dig a little more to see if the issue is in ws.

**Comment by lpinca** [comment]
Not an issue in ws apparently as I still have a TIME_WAIT connection after running this

```js
const net = require('net');

const server = net.createServer();
let serverSocket;

server.on('connection', (socket) => {
  serverSocket = socket.resume();
});

server.listen(8081, '127.0.0.1', () => {
  const socket = net.createConnection(8081);
  socket.on('connect', () => {
    console.log('connection established');
    socket.resume();
  });
});

for (const sig of ['SIGINT', 'SIGTERM']) {
  process.on(sig, () => {
    console.log(sig);

    // Stop accepting new connections.
    server.close();
    serverSocket.end();
  });
}
```

**Comment by shellscape** [comment]
Thanks for looking into it deeper on your end. I'm gonna close this, as it's not the fault of `ws`. Since you're not getting the EADDRINUSE error, I'll do some more digging to figure out if that's a fault of the OS on my end.
