### ISSUE TITLE
this.error.code

### ISSUE THREAD

**Issue by lzl124631x** [websockets/ws#1292]
- [x] I've searched for any related issues and avoided creating a duplicate issue.

#### Reproducible in:

version:
Node.js version(s):
OS version(s):

#### Steps to reproduce:

When there is network issue.

### Actual result:

```
C:\Richard\Project\crypto-portal\back-end\node_modules\node-binance-api\node-bi                       nance-api.js:231
                        options.log("WebSocket Error: "+this.endpoint, this.error.code);
                                                                                                         ^

TypeError: Cannot read property 'code' of undefined
    at WebSocket.<anonymous> (C:\Richard\Project\crypto-portal\back-end\node_mo                       dules\node-binance-api\node-binance-api.js:231:62)
    at emitOne (events.js:116:13)
    at WebSocket.emit (events.js:211:7)
    at WebSocket.finalize (C:\Richard\Project\crypto-portal\back-end\node_modul                       es\ws\lib\WebSocket.js:182:41)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)


```

**Comment by jaggedsoft** [comment]
Actually, this looks like a problem with my library located at https://github.com/jaggedsoft/node-binance-api/ but it might have already been fixed

**Comment by lzl124631x** [comment]
@jaggedsoft  Ah, yes. I mistakenly posted this issue here.

Curious. How did you find this issue? I just posted it.

I just pull your code yesterday. Are you sure it's fixed?

**Comment by slidenerd** [comment]
Just a curious question highly related to this post, to get say orderbook candle and ticker from binance, one needs to open 3 ws connections, are there any limits to how many ws connections can run in a single node process, i could not find any benchmarks for this in bench folder, I intend to also connect to bitfinex which requires 4 more connections in addition to binance, how many such connections can be run inside a single node process, some clarity would be super appreciated, thanks in advance

**Comment by jaggedsoft** [comment]
@slidenerd I believe this comes down more to the operating system limits than javascript limits. i've had several thousand connections open and hear reports of others going beyond 600k connections or even beyond a million. At this point it would depend more on processing speed and probably RAM as well.
