### ISSUE TITLE
Creating websocket.Server from http2.createSecureServer

### ISSUE THREAD

**Issue by cTn-dev** [websockets/ws#1293]
Hi (sorry for creating the ticket here, stackoverflow didn't seem like the right place for this).

I was wondering if there is a way, or if it will be possible to create a websocket server on top/from the http2.createSecureServer instance.

Right now i have to create an additional regular https.server and then create the websocket server from this instance, this works fine but it forces me to have another port open (which makes sense).

I am aware that http2 in node is still in "experimental" stage, but better support for it in ws would be great.

**Comment by lpinca** [comment]
There is no support for WebSocket over HTTP/2. See https://daniel.haxx.se/blog/2016/06/15/no-websockets-over-http2/, https://github.com/nodejs/node/issues/15230.

**Comment by cTn-dev** [comment]
Oh, i didn't know :/ thank you very much for the links.
Loving the module btw!

**Comment by lucsoft** [comment]
Hey there is support for WebSockets over HTTP/2 now.

https://tools.ietf.org/html/rfc8441 

i would like to know if it just got forgotted or are there some other reason

**Comment by linuxd3v** [comment]
if anyone else stumbles on this tix. 
HTTP2 web-sockets are now reality - added as part of this rfc: https://datatracker.ietf.org/doc/html/rfc8441

Firefox is defaulting to websockets over http2  - see network.http.spdy.websockets
Chrome also allegedly added support to http2 web-sockets recently:   
https://www.chromestatus.com/feature/6251293127475200  

Reverse proxy solutions are beginning to support http2 web-sockets as well:
https://www.haproxy.com/blog/announcing-haproxy-2-4/   
   
There are significant changes in how ugrade happens over http2 - notably there are no Upgrade header utilized, instead ssl hello extension is being used to convey the upgrade intent.
