### ISSUE TITLE
Wrong HTTP status code when handleProtocols returns false

### ISSUE THREAD

**Issue by heldplayer** [websockets/ws#1296]
- [X] I've searched for any related issues and avoided creating a duplicate issue.

#### Description

When a WebSocket.Server instance is configured with `handleProtocols` set. If this function returns false ws will generate an HTTP 401 error code to indicate failure. According to [RFC7235](https://tools.ietf.org/html/rfc7235#section-3.1):

```
3.1.  401 Unauthorized

   The 401 (Unauthorized) status code indicates that the request has not
   been applied because it lacks valid authentication credentials for
   the target resource.  The server generating a 401 response MUST send
   a WWW-Authenticate header field (Section 4.1) containing at least one
   challenge applicable to the target resource.

   If the request included authentication credentials, then the 401
   response indicates that authorization has been refused for those
   credentials.  The user agent MAY repeat the request with a new or
   replaced Authorization header field (Section 4.2).  If the 401
   response contains the same challenge as the prior response, and the
   user agent has already attempted authentication at least once, then
   the user agent SHOULD present the enclosed representation to the
   user, since it usually contains relevant diagnostic information.
```

No such `WWW-Authenticate` header is generated however, because it does not apply to the failure to decide on a sub-protocol. Instead a more appropriate HTTP status code should be used like 400 Bad Request or possibly 403 Forbidden. Ideally the WebSocket specification would mention which to use, however it does not and all I know is that 401 is not the right status code.

#### Reproducible in:

version: 4.0.0
Node.js version(s): 9.5.0
OS version(s): Ubuntu 16.04.3 LTS

#### Steps to reproduce:

1. Write a simple ws server with `verifyClient: () => false`
2. Write a simple browser WebSocket client that connects to the server in step 1
3. Run the page from step 2 in a browser like Chrome and in the developer tools Network tab, observe that the request returns status code 401

### Expected result:

The status code is 400 or 403.

### Actual result:

The status code is 401, and no `WWW-Authenticate` header is present.

### Extra information:
The code writing out a 403 status code was authored in #364.

**Comment by lpinca** [comment]
Fixing this is trivial but it will probably be a semver-major change.

**Comment by lpinca** [comment]
If I'm reading https://tools.ietf.org/html/rfc6455#section-4.2.2 correctly

> /subprotocol/
          Either a single value representing the subprotocol the server
          is ready to use or null.  The value chosen MUST be derived
          from the client's handshake, specifically by selecting one of
          the values from the |Sec-WebSocket-Protocol| field that the
          server is willing to use for this connection (if any).  If the
          client's handshake did not contain such a header field or if
          the server does not agree to any of the client's requested
          subprotocols, the only acceptable value is null.  The absence
          of such a field is equivalent to the null value (meaning that
          if the server does not wish to agree to one of the suggested
          subprotocols, it MUST NOT send back a |Sec-WebSocket-Protocol|
          header field in its response).  The empty string is not the
          same as the null value for these purposes and is not a legal
          value for this field.  The ABNF for the value of this header
          field is (token), where the definitions of constructs and
          rules are as given in [RFC2616].

It's the client that should close the connection if the server does not agree to any of the client's requested subprotocols, so we should not abort the handshake but only avoid including the `Sec-WebSocket-Protocol` header in the server response.

**Comment by heldplayer** [comment]
Looks good 👍
