### ISSUE TITLE
Upgrade required

### ISSUE THREAD

**Issue by VisWong** [websockets/ws#1297]
Thank you for your sharing of the "ws" module. It helps me done the web app with websocket. It worked for one year, but it suddenly not working from these few days. It shows "Upgrade required" when I am accessing the page. Does anyone has ideas or experience for this issue? Thanks.

**Comment by lpinca** [comment]
Your WebSocket server is probably receiving a plain HTTP request so it answers with 426: https://github.com/websockets/ws/blob/828194044bf247af852b31c49e2800d557fedeff/lib/websocket-server.js#L62-L70

Make sure that the request is initiated by the `WebSocket` object in the client.
