### ISSUE TITLE
Customizing Clients property in WebSocketServer

### ISSUE THREAD

**Issue by basitsattar** [websockets/ws#1299]
Hi
I am using this library for a chat application where I need to track online users and the sockets for a specific user. Is it possible to customize the clients in clients set to include app specific information like username, token etc. so that we can track online users etc. or the only way is to make another array of objects for online users and their sockets?

**Comment by lpinca** [comment]
You can add custom properties to the `WebSocket` instance on connection and use those properties but it's not ideal for performance if you have many of them.

Disabling the built-in `clientTracking` and using a map of <user, socket> is probably better.

**Comment by basitsattar** [comment]
Ok. but how'll I track users who went offline? I mean I have to keep track of them with respect to socket ids too? Also is there a on disconnect event in ws like Socket.io? And how to uniquely identify a socket, through id or what?

**Comment by lpinca** [comment]
Each WebSocket emits a `'close'` event which can be used for that purpose.

> How to uniquely identify a socket, through id or what?

That's up to you. Creating a unique id for each WebSocket is the usual solution.

**Comment by lpinca** [comment]
Closing as there isn't anything actionable to do here.
