### ISSUE TITLE
Problem with React build - Failed to minify the code - permessage-deflate.js

### ISSUE THREAD

**Issue by iMitaka** [websockets/ws#1303]
**Description:**
I have a problem when install the 'ws' in my React App and then try to make a build, i had an Error that says:

> Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file:

        ./node_modules/ws/lib/permessage-deflate.js:29

Read more here: http://bit.ly/2tRViJ9

And in documentation they explain it like this:

> Note: Create React App can consume both CommonJS and ES modules. For Node.js compatibility, it is recommended that the main entry point is CommonJS. However, they can optionally provide an ES module entry point with the module field in package.json. Note that even if a library provides an ES Modules version, it should still precompile other ES6 features to ES5 if it intends to support older browsers.

**Comment by lpinca** [comment]
https://github.com/websockets/ws#ws-a-nodejs-websocket-library

> Note: This module does not work in the browser. The client in the docs is a reference to a back end with the role of a client in the WebSocket communication. Browser clients must use the native WebSocket object. To make the same code work seamlessly on Node.js and the browser, you can use one of the many wrappers available on npm, like isomorphic-ws.
