### ISSUE TITLE
TypeError: One of the "port", "server", or "noServer" options must be specified

### ISSUE THREAD

**Issue by kevindenight** [websockets/ws#1310]
- [x] I've searched for any related issues and avoided creating a duplicate issue.

#### Description

I'm using [babel-register](https://babeljs.io/docs/usage/babel-register/) to refine my folder structure, finally i got "TypeError: One of the "port", "server", or "noServer" options must be specified" while running script.

#### Reproducible in:

version:
Node.js version(s): v8.9.4
OS version(s): macOS High Sierra 10.13.3

#### JS files like:

webSocket.js

> import WebSocket from 'ws';
> import server from './httpServer';
> 
> const wss = new WebSocket.Server({server});

httpServer.js

> import http from 'http';
> import app from './express';
> 
> export const server = http.createServer(app);

and node debug like:

>  17 /* eslint-disable no-debugger */
> 8 debugger;
> 19 var wss = new _ws2.default.Server({ server: _httpServer2.default });

Anyone can help?

**Comment by kevindenight** [comment]
Well, i copied the content of httpServer.js to webSocket.js, then it works.  emmmm

**Comment by lpinca** [comment]
I don't know maybe the problem is how babel handles default exports but it doesn't seem to be an issue in ws.

**Comment by kevindenight** [comment]
Find the problem finally, it caused by circle import. Thank you for reply anyway!
