### ISSUE TITLE
One of the "port", "server" or "noServer" options must be specified

### ISSUE THREAD

**Issue by fxbabys** [websockets/ws#1314]
- [ ] I've searched for any related issues and avoided creating a duplicate issue.

#### Description

I put the node code on the server and use the pm2 to listen to the server.
The server response the title error but I actually write the port line.

#### Reproducible in:

version: latest
Node.js version(s): 8.9.4
OS version(s): windowServer2012

#### Steps to reproduce:

1. I declared the wss variable as follow：
```javascript
var WebsocketServer = require("ws").Server;
var wss  = new WebsocketServer({
  port: 3001
});
```
2. Then I used the pm2 to listen to the server.
### Expected result:

The server should be normal.

### Actual result:

The server response the error as the title: One of the "port", "server" or "noServer" options must be specified. 
And when I annotation the port line it response the error instantly. When I rewrite the port line it just stops but no more response.

**Comment by lpinca** [comment]
I can't reproduce the issue, it works as expected. An error is thrown if you don't specify one of those options.

**Comment by fxbabys** [comment]
Thank you for the response! It works after a while, maybe due to the server cache.
