### ISSUE TITLE
Websocket errors when client and server are closed simultaneously

### ISSUE THREAD

**Issue by mtharrison** [websockets/ws#1316]
- [x] I've searched for any related issues and avoided creating a duplicate issue.

#### Description

When calling `close()` on both ends of the socket concurrently it leads to a socket error but it seems only to occur on MAC OS X High Sierra.

I'm working on maintaining nes (the websocket library for hapi). The test suite has problems. It succeeds on all platforms apart from Mac OSX High Sierra (10.13.3). I've traced this to the fact that nes's test will close both the server and the client websockets when the test is complete. This causes each test to log a socket error.

I have a small example snippet using only Ws:

```js
const Ws = require('ws');

const wss = new Ws.Server({ port: 8080 });
const ws = new Ws('ws://localhost:8080');

ws.on('open', () => {

    ws.onclose = () => console.log('Websocket closed');
    ws.onerror = (err) => console.log(`Websocket errored: ${err.message}`);

    wss.close();
    ws.close();
});
```

If I run this on Mac I get:

```
Websocket errored: read ECONNRESET
Websocket closed
```

If I run on other platforms, such as linux or earlier Mac OS X version, I just get:

```
Websocket closed
```

I'm not sure if we were wrong to assume that it wouldn't error before or if this is now a bug in Ws? 

#### Reproducible in:

version: 3.3.3
Node.js version(s): 8.9.4
OS version(s): Mac OSX High Sierra (10.13.3)

**Comment by lpinca** [comment]
This happens because `wss.close()` destroys the socket on the server and right after that the client tries to send a close frame on the destroyed socket with `ws.close()`.

These errors were not emitted before version 3.3.3 so your assumption was not wrong and are not re-emitted again in upcoming version 5 (a4050db).

**Comment by lpinca** [comment]
To clarify, this is not a bug, the error is expected but was not re-emitted is version < 3.3.3 and is again not re-emitted in the next major version.

**Comment by mtharrison** [comment]
Thanks, so in your opinion would you expect a consuming library to ignore errors on the socket after open has completed successfully? And only care about the socket close events after that?

**Comment by lpinca** [comment]
It depends, there is not much that can be done to prevent network errors so it makes sense to ignore them and this is the reason why we decided to not re-emit them again, but I would not ignore protocol errors which indicate that something isn't working properly.

```js
const ws = new WebSocket(url);

ws.onerror = function (evt) {
  if (this.readyState > WebSocket.OPENING && evt.error.errno) {
    // Ignore network errors after the 'open' event
    return;
  }

  handleError(evt.error);
}
```

**Comment by mtharrison** [comment]
Ok, thank you for the information!
