### ISSUE TITLE
no 'error` event emitted when killed the running server on Ubuntu

### ISSUE THREAD

**Issue by YxxY** [websockets/ws#1320]
#### Description
when killed the running server on windows 7 x64  , the connected client would receive both 'error' and 'close' events while only got a 'close' event if the server in running on ubuntu 16.04 x64

not sure whether this is a bug, but this different behavior really caused me lots of trouble when the same code had to run on different system

#### Reproducible in:

version: 4.0.0
Node.js version(s): v8.2.1
OS version(s): win7 x64 / ubuntu 16.04 x64

#### Steps to reproduce:

1. start the server
2. start the client, listening to both 'error' and 'close' event
3. kill the server(ctrl+c to terminate the program)
4. confirm acceptance of the results
### Expected result:

behave the same

### Actual result:
Got both 'error' and 'close' events on windows
Got only 'close' event on ubuntu

**Comment by lpinca** [comment]
What is the emitted error?

**Comment by YxxY** [comment]
@lpinca thanks for your reply.

on windows, the error code is `ECONNRESET`
on ubuntu, the 'error' event handler received nothing, the 'close' event handler as below got `1006`
```js
    ws.on('close', function (err) {
        console.log(err)
    })
```

**Comment by lpinca** [comment]
Ok, try to update to version 5. We are no longer re-emitting network errors so both platforms should work in the same way.

**Comment by YxxY** [comment]
it works, thanks a lot!
