### ISSUE TITLE
Binding connection event

### ISSUE THREAD

**Issue by SuperOP535** [websockets/ws#1325]
I'm using classes so I need `this` variable but the callbacks break this, when using a ws client I can do `this.ws.onopen = this.onOpen.bind(this);` but there is no onconnection for the server one, I also need onmessage..

**Comment by SuperOP535** [comment]
Cool, when I do this with 'message', how can I pass the ws object (for using ws.close() ws.send() etc.)

**Comment by SuperOP535** [comment]
Ok so forget my old comment ( deleted now ) but when I do this does it pass the ws object if I do like onconnections(ws) { etc... }

**Comment by lpinca** [comment]
Yes, see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_objects/Function/bind.
Please don't open issues like this. This issue tracker is for bugs in the lib and feature requests only.

**Comment by SuperOP535** [comment]
I'm sorry, I'm new to classes and I thought I would ask here but I won't do it again.. Thanks for helping me :)
