### ISSUE TITLE
how to handle data from onmessage

### ISSUE THREAD

**Issue by ztiandan** [websockets/ws#1327]
Node: 8.9.1
ws: 3.3.2

I need to use Nodejs simulate like browser, the browser use H5 API FileReader for read all blob data and then call w funciton and pass the arraybuffer, on Node  I have try [filereader](https://www.npmjs.com/package/filereader), but it need blob as datasource, how could i read all data once like FileReader?

Browser code for onmessage (t.data) is blob type
```
let e = new WebSocket(i)
e.onopen = h;
e.onclose = f;
e.onerror = m;
e.onmessage = I;

function I(t) {
    var e = new FileReader;
    e.onload = w;
    e.readAsArrayBuffer(t.data)
}
 function w() {
    var e = this.result;
 }
```

Node code  (t.data is Buffer type)
```
function I(t) {
    let buf = t.data;  (just first package)
}
```

**Comment by lpinca** [comment]
If the problem is that you get a `Buffer` instead of an `ArrayBuffer`, set the `binaryType` to `'arraybuffer'`, or convert the buffer yourself.

```js
const ws = new WebSocket(url);

ws.binaryType = 'arraybuffer';

ws.onmessage = function (evt) {
  const buf = evt.data; // This is an `ArrayBuffer`.
};
```

**Comment by ztiandan** [comment]
does binaryType support blob?

**Comment by lpinca** [comment]
No, as that is a browser only binary type.

**Comment by ztiandan** [comment]
server work with browser with blob, what type i need to use with node, arraybuffer?

**Comment by lpinca** [comment]
I don't know :) https://www.npmjs.com/package/filereader seems to support `.readAsArrayBuffer(<File>)` so it should work if you use `ArrayBuffer`.

**Comment by ztiandan** [comment]
when i set binaryType = "arraybuffer", but evt.data still Buffer type, how could i figure it out?

**Comment by lpinca** [comment]
It seems you also need https://github.com/node-file-api/file-api in order for https://github.com/node-file-api/FileReader to work.

Untested but the following should work:

```js
const FileReader = require('filereader');
const WebSocket = require('ws');
const { File } = require('file-api');

const ws = new WebSocket(url);

ws.onmessage = function (evt) {
  const file = new File({
    name: 'foo.txt',
    buffer: evt.data
  });

  const fileReader = new FileReader();

  const string = fileReader.readAsDataURL(file);
}

```

**Comment by ztiandan** [comment]
the browser code like this
```
const FileReader = require('filereader');
const WebSocket = require('ws');

const ws = new WebSocket(url);

ws.onmessage = function (evt) {
  const fileReader = new FileReader;
  fileReader.onload = w;
  fileReader.readAsArrayBuffer(evt.data)
}

function w() {
   let e = this.result;
}
```

H5 API FileReader read data from evt.data directly, I debug on the browser, it seems readAsArrayBuffer read lots of times, and then enter w function

**Comment by ztiandan** [comment]
use above code on Node, there is an error will be throw
```
if (!file || !file.name || !(file.path || file.stream || file.buffer)) {
   throw new Error("cannot read as File: " + JSON.stringify(file));
}
```

**Comment by lpinca** [comment]
Yes, `fileReader.readAsArrayBuffer()` wants a `File` instance, see https://github.com/websockets/ws/issues/1327#issuecomment-372937002.

**Comment by ztiandan** [comment]
it works, thank u very much.

**Comment by titoBouzout** [comment]
Does this means that client (the browser) will always receive a blob and never an arraybuffer?  Im confused because I been trying to avoid having to convert to arraybuffer.

**Comment by titoBouzout** [comment]
Nevermind, I understood now. In the browser you need to tell the connection will user arraybuffer as the binaryType. ws.binaryType = 'arraybuffer'
then messages when messages are received event.data will be instance of ArrayBuffer instead of instanceof Blob
