### ISSUE TITLE
cannot get error code after verifyClient is rejected

### ISSUE THREAD

**Issue by endel** [websockets/ws#1331]
Hi there,

I'm trying to send a custom error code on `verifyClient`, e.g.: 

```javascript
verifyClient: (info, next) => next(false, 4002, "error message");
```

The problem is, I can't get either the error code or the error message from the client-side:

```javascript
let ws = new WebSocket("ws://...");
ws.onclose = (e) => {
  console.log(e.code) // outputs 1006
  console.log(e.reason) // outputs ""
}
ws.onerror = (e) => {
  // error code or reason is not avaiaible on this callback
}
```

Am I missing something? Or is it a bug in the library? 
Cheers!

**Comment by lpinca** [comment]
`verifyClient` works before response headers are sent (before the handshake is completed). Rejecting `verifyClient` means aborting the handshake and you can't send frames (a close frame in this case) before a successful handshake.

The `code` argument is the HTTP status code to use in the response, not WebSocket status code. See https://github.com/websockets/ws/blob/1504d6713138431dacd67407c115290c0985899c/lib/websocket-server.js#L335-L350

**Comment by lpinca** [comment]
Closing, discussion can continue on the closed thread.

**Comment by Jokero** [comment]
@lpinca So, is any way to get these http response code and message?) I guess the only way to pass the reason to the client why WebSocket connection is not established is to set cookie with specific value.

**Comment by lpinca** [comment]
If ws is used as client you can use the [`'unexpected-response'`](https://github.com/websockets/ws/blob/master/doc/ws.md#event-unexpected-response) event. In the browser there is no way.

**Comment by Jokero** [comment]
@lpinca What do you think about extending the callback of `verifyClient` with new param for additional (custom) headers?

So `abortHandshake` will look something like this:
```js
function abortHandshake (socket, code, message, headers) {
  if (socket.writable) {
    message = message || http.STATUS_CODES[code];
    headers = headers || {};
    socket.write(
      `HTTP/1.1 ${code} ${http.STATUS_CODES[code]}\r\n` +
      'Connection: close\r\n' +
      'Content-type: text/html\r\n' +
      `Content-Length: ${Buffer.byteLength(message)}\r\n` +
      Object.keys(headers).map(h => `${h}: ${headers[h]}`).join('\r\n') +
      '\r\n' +
      message
    );
  }

  socket.removeListener('error', socketOnError);
  socket.destroy();
}
```

In that case I can send cookie to the client and show some message based on its value.

**Comment by lpinca** [comment]
There are a couple of open issues for that, feel free to propose a PR.
