### ISSUE TITLE
verifyClient req.headers.authorization is undefined when performing Basic Auth

### ISSUE THREAD

**Issue by Altiano** [websockets/ws#1333]
- [yes] I've searched for any related issues and avoided creating a duplicate issue.

#### Description
Server is running on HTTPS
I'm using `express` to create httpServer instance
then pass it to `ws`
It runs on `https://localhost:8443`
I'm using Chrome 65

#### Reproducible in:

version: 5.1.0
Node.js version(s): 8.9.4
OS version(s):

#### Steps to reproduce:

1. Navigate to `https://localhost:8443/test`
2. Open Chrome Console
3. new WebSocket('wss://username:password@localhost:8443')
4. on verfifyClient callback, `console.log(req.headers.authorization)`

### Expected result:
Authorization header should not be `undefined`

### Actual result:
Authorization header is `undefined`

### My hack is..
`new WebSocket('wss://localhost:8443', 'username:password')`

**Comment by lpinca** [comment]
Ok, yes it seems browsers no longer add the authorization header if the URL has userinfo. There is not much we can though as that is outside our control.

A possible workaround is to use a query string parameter:

```js
const ws = new WebSocket('wss://localhost:8443/?token=abc');
```

**Comment by Altiano** [comment]
@lpinca Too bad.. I wonder is it safe to put token in URL?
Will it be encrypted when using `wss`?

**Comment by lpinca** [comment]
Yes, it's ok.
subprotocol has a different meaning, it's used to negotiate a subprotocol which will be used by both peers. Nothing prevents you from using it to send data but it is not designed to do this. Also keep in mind that the value of the negotiated subprotocol is saved to `ws.protocol`.

**Comment by JulienLeotier** [comment]
Hello, 
i have a solution for pass a token in header 

```
const headers = Object.assign({
        'Authorization': 'Token  YourToken'
      }, headers);
      const ws = new WebSocket('ws://YourUrl', ['protocole1', 'protocole2'], options={'headers':headers});
```

**Comment by lpinca** [comment]
@Altiano's issue is in the browser, you can't specify custom headers there.

**Comment by lpinca** [comment]
Closing as there isn't anything actionable to do.

**Comment by Paxa** [comment]
I was able to do it if first request will end with status 401 and require authorization, then chrome will send one more request with auth headers:
```js
const auth = require('basic-auth');

function verifyClient(info, callback) {
  if (info.req.url.includes('require_auth=1')) {
    var adminUser = auth(info.req);

    if (adminUser && adminUser.name == AppConfig.admin_auth.name && adminUser.pass == AppConfig.admin_auth.pass) {
      callback(true)
    } else {
      console.log('WS: require basic auth', adminUser);
      callback(false, 401, 'Unauthorized', {'WWW-Authenticate': 'Basic realm=Authorization Required'})
    }
  } else {
    callback(true)
  }
}

/// ...

const wss = new WebSocket.Server({ server, verifyClient });

wss.on('connection', async (ws, req) => {
  var user = auth(req) || {};
  // user <- this will have values
})
```

**Comment by ksac1** [comment]
What is the solution for this problem?
