### ISSUE TITLE
MIME type

### ISSUE THREAD

**Issue by qm3ster** [websockets/ws#1335]
How can I set `type` property when sending binary data?
In the browser, it's done through the `Blob` constructor, but we don't have `Blob` in node.

**Comment by lpinca** [comment]
You can use the [`binaryType`](https://github.com/websockets/ws/blob/master/doc/ws.md#websocketbinarytype) attribute but keep in mind that `Blob` is not supported.

```js
const ws = new WebSocket(url);

ws.binaryType = 'arraybuffer';

ws.on('message', function (message) {
  // `message` is an `ArrayBuffer`.
});
```

**Comment by qm3ster** [comment]
Sorry for the confusion, I meant types like `'application/json'`, when sending a message.
In a browser this would be achieved by the following:
```js
ws.send(new Blob([JSON.stringify({ test: 1 })], { type: 'application/json' }))
```
but `Buffer` and such don't have anything like that, so I was looking to sideload it, something like this:
```js
ws.send(new Buffer(JSON.stringify({ test: 1 })), { type: 'application/json' })
```

**Comment by lpinca** [comment]
When you send a `Blob` in the browser only the data contained in it is sent to server as a binary frame. The server does not know what the MIME type of the data contained in the blob was. It actually doesn't know it was a blob in the first place.

This is to say that it doesn't matter what you send, the receiving end only sees binary or text data. There is no way to indicate the nature and format of a message to the receiving end unless you embed that info in the message itself.

**Comment by lpinca** [comment]
Closing, discussion can continue on the closed thread.
