### ISSUE TITLE
Documentation option port and noServer

### ISSUE THREAD

**Issue by rgranger** [websockets/ws#1338]
- [x ] I've searched for any related issues and avoided creating a duplicate issue.

# Description

I have been struggling to make a Websocket Server that does not listen on the new ws.Server(), but rather when I call the method 'listen(8080)' myself.

Most examples are provided with the option { port: 8080 }

# Documentation

Would it be possible to do the following ?

* Add in the doc about option { port } that it will listen automagically and how to prevent that.
* Add an example of Server that doesn't listen 'automagically' (when the port option is not provided)
* Add an example usage of Server with 'noServer' : I still don't understand what this option is for.

Thanks for reading.

**Comment by lpinca** [comment]
The `noServer` option is used when you want to use an external server without passing it to the constructor, so you can share the same server between multiple WebSocket server. For example:

```js
const server = http.createServer();
const wss = new WebSocket.Server({ noServer: true });

server.on('upgrade', function (request, socket, head) {
  wss.handleUpgrade(request, socket, head, function (ws) {
    // ...
  })
})
```

Feel free to open a PR. https://github.com/websockets/ws/issues/1334 can also be addressed in the same PR.

**Comment by Metrophobe** [comment]
> The `noServer` option is used when you want to use an external server without passing it to the constructor, so you can share the same server between multiple WebSocket server. For example:
> 
> ```js
> const server = http.createServer();
> const wss = new WebSocket.Server({ noServer: true });
> 
> server.on('upgrade', function (request, socket, head) {
>   wss.handleUpgrade(request, socket, head, function (ws) {
>     // ...
>   })
> })
> ```
> 
> Feel free to open a PR. #1334 can also be addressed in the same PR.

you mean share the same server on multiple websocket Clients?
