### ISSUE TITLE
Error when sending simple string in node ts application

### ISSUE THREAD

**Issue by FlowShowcontrol** [websockets/ws#1339]
- [x ] I've searched for any related issues and avoided creating a duplicate issue.

#### Description

When using ws.send() in a typescript node application, the example results in a 'Invalid data, chunk must be a string or buffer, not object' error

#### Reproducible in:

version: 5.0.1
Node.js version(s): Latest
OS version(s): MacOS

#### Steps to reproduce:

1. Clone boilerplate: https://github.com/maximegris/angular-electron
2. Install ws and add to webpack config
3. Create Server in Angular app src and send message

### Expected result:

Send message as done in the example

### Actual result:

Invalid data, chunk must be a string or buffer, not object' error

### Attachments:

The readystate is 1 and the socket is not closing

<img width="948" alt="screen shot 2018-03-29 at 5 51 28 pm" src="https://user-images.githubusercontent.com/10196339/38099037-e08b6330-3379-11e8-9b5f-848531b04b17.png">

Code
```

`        
this.wss = new WebSocket.Server({ port: 9020 });

        this.wss.on('connection', function connection(ws, req) {

            ws.on('close', function close() {
                console.log('disconnected');
              });

            ws.on('message', function incoming(message) {
                ws.send('something');
        
                console.log("Send Changed Message");
            });
        });`
```

**Comment by lpinca** [comment]
Can you reproduce the issue using only `ws`? If not chances are the issue is not in `ws`.

**Comment by FlowShowcontrol** [comment]
It seems that when using Electron, the resulting buffer created by ws is not recognized by net.js as being a Buffer at all. Is there some conversion needed here?

**Comment by lpinca** [comment]
I don't know, the buffer created by `ws` is a Node.js buffer, see https://github.com/websockets/ws/blob/7c74567b974b79253ac32aac8f7d3dcb3e6d17e8/lib/sender.js#L266

and 

https://github.com/websockets/ws/blob/7c74567b974b79253ac32aac8f7d3dcb3e6d17e8/lib/sender.js#L58

**Comment by lpinca** [comment]
I can't reproduce. Here is my test case

```
$ tree
.
├── index.html
├── index.js
└── package.json

0 directories, 3 files
```

```
$ cat package.json 
{
  "name": "app",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "start": "electron ."
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "electron": "^1.8.4",
    "ws": "^5.1.0"
  }
}
```

```
$ cat index.js 
const path = require('path');
const url = require('url');
const WebSocket = require('ws');
const { app, BrowserWindow } = require('electron');

app.on('ready', function () {
  const wss = new WebSocket.Server({ port: 8080 }, function () {
    const win = new BrowserWindow({ width: 800, height: 600 });

    win.loadURL(url.format({
      pathname: path.join(__dirname, 'index.html'),
      protocol: 'file:'
    }));

    win.on('closed', function () {
      app.quit();
    });
  });

  wss.on('connection', function (ws) {
    ws.on('message', ws.send.bind(ws));
  });
});
```

```
$ cat index.html 
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>GH-1339</title>
  </head>
  <body>
    <script>
      const WebSocket = require('ws');

      const ws = new WebSocket('ws://localhost:8080');

      ws.on('open', function () {
        ws.send('Hello');
      });

      ws.on('message', function (msg) {
        document.write(msg);
      });
    </script>
  </body>
</html>
```

It works as expected.
