### ISSUE TITLE
Explain the Behavior of server.close() More Precisely

### ISSUE THREAD

**Issue by anliting** [websockets/ws#1341]
- [x] I've searched for any related issues and avoided creating a duplicate issue.

I think it would be good to explain the behavior of server.close() more precisely in the API docs:

- The pre-created HTTP server is not closed when 'server' is in the constructing options.
- No server is closed when 'noServer' is in the constructing options.

**Comment by lpinca** [comment]
Please open a PR.

**Comment by lpinca** [comment]
Fixed by https://github.com/websockets/ws/pull/1342.
