### ISSUE TITLE
We should provide a valid WebSocket for Browser, or throw a Error explicitly.

### ISSUE THREAD

**Issue by zixia** [websockets/ws#1344]
- [x] I've searched for any related issues and avoided creating a duplicate issue.

#### Description

When a module that is using `import * as WebSocket from 'ws'`, and it's user use it in the Browser, we will get a `WebSocket` provided by `ws` which does not work.

#### Reproducible in:

version: 5.1.0
Node.js version(s): 9.8.0
OS version(s): Darwin zixia-pro.local 16.7.0 Darwin Kernel Version 16.7.0: Mon Nov 13 21:56:25 PST 2017; root:xnu-3789.72.11~1/RELEASE_X86_64 x86_64

#### Steps to reproduce:

1. `import * as WebSocket from 'ws'` in a javascript file
2. use WebPack to pack it into a bundle
3. run it in Browser

### Expected result:

I understood that the `ws` module is designed for the Node.js environment, we should not expect it work in the Browser. 

However, when users used `ws` in their module code, sometimes the module user might use the module in the Browser, and without the knowledge of the limitation of the `ws` module.

#### Suggested Behavior

It should be either throw an error explicitly or provide a valid `WebSocket` implementation for the Browser.

### Actual result:

It provides a not worked WebSocket for the Browser silently.

### Attachments:

This issue cost me 2 days to find out the problem, even I know the `ws` not work in the Browser.

I had wroten a NPM module named `@chatie/graphql` which use `ws` to connect with the GraphQL server, it work without any problem in the Node.js enviornment.

After some time, I want to use this module in my Ionic/Angular project, then I got a very strange error. After digging it deep, I found out that it's because I'm using `ws` in my `@chatie/graphql`. 

See more at: 
1. https://github.com/Chatie/graphql/issues/12
1. https://www.graph.cool/forum/t/cors-problem-no-access-control-allow-origin-header-is-present-in-the-subscriptions-endpoint/2988/8?u=huan

**Comment by lpinca** [comment]
This is documented, it is the first thing written after the project description: https://github.com/websockets/ws#ws-a-nodejs-websocket-library.

That said, I'm happy to revisit https://github.com/websockets/ws/pull/661 if @3rd-Eden agrees.

**Comment by zixia** [comment]
@lpinca Yes, I understand that it is documented very clearly.

This issue comes out because there might be a module using `ws`, but others module require this module without any knowledge of the limitation of `ws`.

It seems I just sent a duplicated PR very similar to #661. 

My suggestion is that we should revisit this problem and at least warn the user by throwing an exception.

**Comment by generateui** [comment]
Just wasted a good amount of time on this, googling for all kinds of weird errors. Infuriating. Especially when the first line reads 

> ws is a simple to use, blazing fast, and thoroughly tested WebSocket client and server implementation.

Yes, there is a note, but usually I only read that when implementation details are needed. I may try to see if the referenced fix works in combination with Browserify.

**Comment by lpinca** [comment]
Fixed by #1345.

**Comment by generateui** [comment]
Awesome!
