### ISSUE TITLE
Write EPROTO Error

### ISSUE THREAD

**Issue by Devoxin** [websockets/ws#1346]
- [x] I've searched for any related issues and avoided creating a duplicate issue.

#### Reproducible in:

version: 5.1.0
Node.js version(s): 9.10.1, 8.11.1
OS version(s): Windows 10 (1709)

#### Steps to reproduce:

1. Try to connect websocket client to a websocket Server using WSS protocol

### Expected result:

The websocket to connect to the websocket server and be able to send/receive data

### Actual result:

The websocket throws an error
```
{ Error: write EPROTO 101057795:error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure:openssl\ssl\s23_clnt.c:802:

    at WriteWrap.afterWrite [as oncomplete] (net.js:844:14) errno: 'EPROTO', code: 'EPROTO', syscall: 'write' }
```

### Additional Info:
The websocket server looks to be running fine; websocket implementations in Java, Python and in the browser are able to connect without issue

**Comment by lpinca** [comment]
Does it work if you run the following code (replace the `hostname` and `port` accordingly)?

```js
const crypto = require('crypto');
const https = require('https');

const request = https.get({
  headers: {
    'Sec-WebSocket-Key': crypto.randomBytes(16).toString('base64'),
    'Sec-WebSocket-Version': 13,
    'Connection': 'Upgrade',
    'Upgrade': 'websocket'
  },
  hostname: 'echo.websocket.org',
  path: '/',
  port: 443
});

request.on('upgrade', function () {
  console.log('It works.');
});
```

**Comment by Devoxin** [comment]
Yep, `It works.` is logged to console without issue

**Comment by lpinca** [comment]
Stupid question, are you using `wss://` in the connection url?

**Comment by Devoxin** [comment]
Yeah, is that not needed?

**Comment by Devoxin** [comment]
If I use `ws://` it returns `Error: Unexpected server response: 400`, and without the `ws://` prefix completely I just get `Error: getaddrinfo ENOTFOUND 2096 2096:80` (2096 is the port of the websocket server)

**Comment by lpinca** [comment]
It is, I'm just trying to understand where the issue is. Can you try with this?

```js
const crypto = require('crypto');
const https = require('https');
const tls = require('tls');

const request = https.get({
  headers: {
    'Sec-WebSocket-Key': crypto.randomBytes(16).toString('base64'),
    'Sec-WebSocket-Version': 13,
    'Connection': 'Upgrade',
    'Upgrade': 'websocket'
  },
  createConnection: tls.createConnection,
  hostname: 'echo.websocket.org',
  path: '/',
  port: 443
});

request.on('upgrade', function () {
  console.log('It works.');
});
```

**Comment by Devoxin** [comment]
That second code snippet is also working

**Comment by lpinca** [comment]
Hmm weird, is the server public accessible? Or is there a way to reproduce the issue?

**Comment by Devoxin** [comment]
Yep, server's publicly accessible, it only seems to be `ws` that's not able to connect for some reason.

**Comment by lpinca** [comment]
I mean, can you share server url so I can debug :)

**Comment by Devoxin** [comment]
`union.serux.pro:2096`

**Comment by lpinca** [comment]
Thank you.

**Comment by lpinca** [comment]
Ok, it works with `ws@5.0.0` so we had a regression. I think it has been introduced with 9e152f920a1818d8a23e0a113b4625c83f90d30d.

I'll investigate.

**Comment by lpinca** [comment]
Found the issue, we are no longer using an agent by default and for this reason the `servername` TLS option is no longer automatically added, so 

https://github.com/websockets/ws/blob/f52debe945f412f22f4fe27b9c1c9a9bfb82accd/lib/websocket.js#L625

fails.

We should fix this. A possible workaround for now is to specify the `servername` option explicitly or use a custom agent.

```js
const WebSocket = require('ws');

const ws = new WebSocket('wss://union.serux.pro:2096', {
  servername: 'union.serux.pro'
});
```

```js
const WebSocket = require('ws');
const { Agent } = require('https');

const ws = new WebSocket('wss://union.serux.pro:2096', {
  agent: new Agent()
});

```
