### ISSUE TITLE
Invalid WebSocket frame: invalid opcode 0

### ISSUE THREAD

**Issue by Lsy-kg** [websockets/ws#1350]
- [ ] I've searched for any related issues and avoided creating a duplicate issue.

#### Description

RangeError: Invalid WebSocket frame: invalid opcode 0
    at Receiver.getInfo (D:\workfolder\work-project\wxpc-agency\node_modules\ws\lib\receiver.js:182:16)
    at Receiver.startLoop (D:\workfolder\work-project\wxpc-agency\node_modules\ws\lib\receiver.js:121:22)
    at Receiver._write (D:\workfolder\work-project\wxpc-agency\node_modules\ws\lib\receiver.js:69:10)
    at doWrite (_stream_writable.js:397:12)
    at writeOrBuffer (_stream_writable.js:383:5)
    at Receiver.Writable.write (_stream_writable.js:290:11)
    at Socket.socketOnData (D:\workfolder\work-project\wxpc-agency\node_modules\ws\lib\websocket.js:785:35)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)

when I open a connection from the client to server, then server get the error in connection. why? please help me. thanks!
#### Reproducible in:

version:5.1.0
Node.js version(s):8.10.0
OS version(s):win10 x64

#### Steps to reproduce:

1.
2.
3.

**Comment by lpinca** [comment]
The client is sending an invalid frame with opcode 0 and the message was not fragmented. It may be a faulty client or data got corrupted.

**Comment by Lsy-kg** [comment]
@lpinca thanks, first. What must the server do to solve this problem? or can only be resolved by the client.

**Comment by lpinca** [comment]
The server will close the connection when an error like this occurs, you only have to add an `'error'` listener to prevent the process from crashing.

```js
wss.on('connection', (ws) => {
  ws.on('error', console.log);
});
```

To fix the issue the client should send valid frames.

**Comment by lpinca** [comment]
Closing as there is not much we can do.

**Comment by evanshabsove** [comment]
Hey I'm running into the same problem and was hoping for some help, I have 
`
// ws catch errors
ws.on('error', function(error){
   console.log(error);
})
`
Inside of my `wss.on('connection') method, I think the error is happening when I am sending ping and pong messages between the clients to check if they are still open. 

`
const interval = setInterval(function ping() {
    wss.clients.forEach(function each(ws) {
        if (ws.isAlive === false) {
              console.log("I am terminating");
              return ws.terminate();
            }
          }
        }
       ws.isAlive = false;
       ws.ping(self.noop);
   });
}, 30000);
`

Is my code sending the ping and inside my `wss.on('connection')` I have 

`
ws.on('pong', self.heartbeat);
`

I'm just wondering where I could add the error handling to catch this. For a bit I included the error handler inside of the ping check but it was still crashing.
