### ISSUE TITLE
Error: connect ECONNREFUSED 127.0.0.1:8080

### ISSUE THREAD

**Issue by HanHtoonAung** [websockets/ws#1352]
- [ ] I've searched for any related issues and avoided creating a duplicate issue.

#### Description

I have disable fire wall and antivirus no one using port 8080
I got this error
Error: connect ECONNREFUSED 127.0.0.1:8080
Please advise
#### Reproducible in:

version:
Node.js version(s):8.11.1
OS version(s): Windows 10

#### Steps to reproduce:

1.
2.
3.

### Attachments:

![image](https://user-images.githubusercontent.com/34746725/38359494-1dab33ae-38fb-11e8-8fc9-c8175efb25aa.png)
![image](https://user-images.githubusercontent.com/34746725/38359621-793631f6-38fb-11e8-9de0-5c74d294e4c1.png)
![image](https://user-images.githubusercontent.com/34746725/38359655-8592aaec-38fb-11e8-9f45-410ebfda0bb1.png)

**Comment by lpinca** [comment]
Is there a WebSocket server listening on 127.0.0.1:8080?

**Comment by lpinca** [comment]
Closing, as I can't see a server running in the above screenshots so the error is expected.

**Comment by manusrivastav** [comment]
START server
cannot call  http://localhost:3000 0 5 { Error: connect ECONNREFUSED 127.0.0.1:3000
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1085:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 3000 }
