### ISSUE TITLE
Supporting multiple instances of WS on a single HTTP server.

### ISSUE THREAD

**Issue by sysaxis** [websockets/ws#1353]
!! I am fully aware that this issue has been raised multiple times in the past and has known workarounds such as one listed [here](https://github.com/websockets/ws/pull/885#issue-187590719).

This issue still persists when using multiple modules that are built on top of ws. For example, I have a ws layer for client-server communications. When adding another layer for server-admin terminal that uses ws, there is no way for a workaround because the layer uses the given server instance for handling certain http requests as well. Passing in a {noServer: true} will cause an exception since it's not an http server.

Here's a solution:

Change websocket-server.js@167
```
    if (
      req.method !== 'GET' || req.headers.upgrade.toLowerCase() !== 'websocket' ||
      !req.headers['sec-websocket-key'] || (version !== 8 && version !== 13) ||
      !this.shouldHandle(req)
    ) {
      return abortHandshake(socket, 400);
    }
```
to
```
    if (
      req.method !== 'GET' || req.headers.upgrade.toLowerCase() !== 'websocket' ||
      !req.headers['sec-websocket-key'] || (version !== 8 && version !== 13)
    ) {
      return abortHandshake(socket, 400);
    } else {
      if (!this.shouldHandle(req)) {
        if ((this._server.listeners('upgrade').length > 1)) return; // let another listener handle it
        return abortHandshake(socket, 400);
      }
    }
```

If there are multiple listeners on"upgrade" event, then ws should ignore the request completely, on a presumption that one of the other listener's will handle it.

**Comment by lpinca** [comment]
I still don't understand. Why do have to forward the options passed to `mod2.init()` to the WebSocket server created in the same function? In the `mod2.init()` can't you use the `noServer` option when creating the WebSocket server?

**Comment by lpinca** [comment]
I think this is an edge case and not an issue in ws but in the wrapper modules you are using. They should add the ability to use ws in no server mode instead of blindly binding it to server passed as option.

**Comment by sysaxis** [comment]
I think you're right. Although I wonder what is the purpose of defaulting the "upgrade" to abort when ws determines that it should not handle it. The default socket timeout of 2 min would kick in anyway if the upgrade request is left unhandled.

**Comment by lpinca** [comment]
True but it's a waste of resources, there could be a lot of connections sitting there with no purpose. It could also be used as an attack vector.

**Comment by lpinca** [comment]
Closing this as I think this should be addressed in the wrapping modules not ws.

**Comment by josdotso** [comment]
@lpinca Given the history of this topic, would you recommend avoiding multiple websockets on a single server?  Are there any gotchas remaining?

**Comment by lpinca** [comment]
@josdotso if used like this https://github.com/websockets/ws#multiple-servers-sharing-a-single-https-server then it's perfectly fine.

**Comment by smallst** [comment]
@lpinca  i don't know where to ask questions (new Issue can only report bug ? ) . i want to know if i'm using multiple-servers-sharing-a-single-https-server with `noServer` option, what's the performance of it? i mean, if i have 2 websocket logics need to write (for example raw string based json message and byte based voice/video messages) , i think i can use 2 different ws.server({noServer}) right? i can use a single ws server and handle message type & logics in `on('message')` too righit? 
is 2 servers makes code using more cpu/memory resources? or it's almost same with more logics in `on('message')` function?

**Comment by lpinca** [comment]
It's the same if you are still using the same Node.js process.
