### ISSUE TITLE
how to use in as external routing?

### ISSUE THREAD

**Issue by Cariaga** [websockets/ws#1356]
//SocketController.js
`var express = require('express'),
    http = require("https"),
    app     = express(),
    morgan  = require('morgan');
var path    = require("path");

var router = express.Router();
app.engine('html', require('ejs').renderFile);
app.use(morgan('combined'));

var server = require('http').createServer(app);
const wss = new WebSocket.Server({ server });

router.get('/', function(req, res){
  let url = path.join(__dirname+'/../views/SocketController.html');
  //res.send(url);
 res.sendFile(url);
});
wss.on('connection', function connection(ws, req) {
  const location = url.parse(req.url, true);
  ws.on('message', function incoming(message) {
    console.log('received: %s', message);
  });
  ws.send('something');
});

module.exports = router;`

**Comment by lpinca** [comment]
What is the issue? Can you clarify your question?

**Comment by Cariaga** [comment]
i'm tying to move the code to an SocketController.js basically using  module.export instead of the doing it directly with server.js
