### ISSUE TITLE
ID for socket

### ISSUE THREAD

**Issue by Craigzyc** [websockets/ws#1363]
I don't see in any examples. 

How do I access a specific ws by id?

I need to store the ws reference in mongo for each client so I can send to the specific client. 
I don't see any way to do this?

**Comment by lpinca** [comment]
There is no ID, generate it yourself and add it to the `WebSocket` instance when the `'connection'` event is emitted. If you search the closed issues there are multiple examples.

**Comment by Craigzyc** [comment]
I did try to search the closed. What specifically are you searching for?

**Comment by lpinca** [comment]
https://github.com/websockets/ws/issues/859

**Comment by Craigzyc** [comment]
Yea that one doesn't help much since it provides no way of later referencing.

#1308 is a little more helpful but still not ideal. 

Thank you
