### ISSUE TITLE
ErrorEvent is emitted in websocket's 'error' event, but documented as Error

### ISSUE THREAD

**Issue by Throne3d** [websockets/ws#1366]
- [x] I've searched for any related issues and avoided creating a duplicate issue.

#### Description

When binding to a WebSocket `error` event, it looks like you're handed an `ErrorEvent`, instead of an `Error` [as currently documented](https://github.com/websockets/ws/blob/HEAD/doc/ws.md#event-error-1). 

The documentation lists it as being an `Error`, and while I know you can access it straightforwardly by using `errorEvent.error`, it's been a slight pain for me to debug why, when I output the error using `console.log`, it doesn't show its stack trace very neatly, but instead shows:

```
 message=function onMessage(data) {
      listener.call(this, new MessageEvent(data, this));
    }, open=function onOpen() {
      listener.call(this, new OpenEvent(this));
    }, error=function onError(error) {
      listener.call(this, new ErrorEvent(error, this));
    }, close=function onClose(code, message) {
      listener.call(this, new CloseEvent(code, message, this));
    }, _eventsCount=4, _maxListeners=undefined, readyState=2, protocol=, _binaryType=nodebuffer, _finalize=function () { [native code] }, _closeFrameReceived=false, _closeFrameSent=false, _closeMessage=, _closeTimer=null, _finalized=true, _closeCode=1006, , _isServer=false, _receiver=null, _sender=null, _socket=null, _error=null, url=wss://gateway.discord.gg/?v=6&encoding=json, _req=null, type=error, message=getaddrinfo EAI_AGAIN gateway.discord.gg:443, message=getaddrinfo EAI_AGAIN gateway.discord.gg:443, errno=EAI_AGAIN, code=EAI_AGAIN, syscall=getaddrinfo, hostname=gateway.discord.gg, host=gateway.discord.gg, port=443
```

#1173 seems to describe when the behavior was changed, but I think a corresponding update to the documentation wasn't performed. The tests seem to describe the parameter as an `errorEvent`, too (<https://github.com/websockets/ws/blob/master/test/websocket.test.js#L1531>), so it seems intentional, and it also fits with browser websockets, but the documentation doesn't reflect this.

#### Reproducible in:

version: originally encountered in 4.0.0, reproducible in 5.1.1
Node.js version(s): v9.7.1
OS version(s): Windows 10 (version 1709)

#### Steps to reproduce:

1. Initialize a websocket with an expected unsuccessful connection
2. Set the `onerror` attribute to log the parameters

### Expected result:

The documentation (<https://github.com/websockets/ws/blob/HEAD/doc/ws.md#event-error-1>) should reflect the fact that the parameter is an ErrorEvent.

### Actual result:

Despite the output being an ErrorEvent, the documentation describes it as an Error.

### Attachments:

Example code which offers error output when you run without a successful internet connection:

```js
const WebSocket = require('ws');

const url = "wss://gateway.discord.gg/?v=6&encoding=json";
const ws = new WebSocket(url);
ws.onerror = function onError(error) {
  console.log("error:", error);
};
```

Output:
```
error: ErrorEvent {
  target:
   WebSocket {
     _events: { error: [Function] },
     … (truncated)
  },
  type: 'error',
  message: 'getaddrinfo EAI_AGAIN gateway.discord.gg:443',
  error:
   { Error: getaddrinfo EAI_AGAIN gateway.discord.gg:443
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)
     message: 'getaddrinfo EAI_AGAIN gateway.discord.gg:443',
     errno: 'EAI_AGAIN',
     code: 'EAI_AGAIN',
     syscall: 'getaddrinfo',
     hostname: 'gateway.discord.gg',
     host: 'gateway.discord.gg',
     port: 443 } }
```

**Comment by lpinca** [comment]
https://github.com/websockets/ws/releases/tag/4.0.0

It's an `ErrorEvent` only if you use `ws.onerror = fn` or use `WebSocket.prototype.addEventListener()` to mirror the `EventTarget` interface. If you use the EventEmitter interface it's a JavaScript error.

**Comment by Throne3d** [comment]
Oh. Right. Oops, I completely missed the later part of the documentation: <https://github.com/websockets/ws/blob/master/doc/ws.md#websocketonerror>.

I apologize – this issue was in error.
