### ISSUE TITLE
CORS error.

### ISSUE THREAD

**Issue by sujitwarrier11** [websockets/ws#1367]
When I implemented this on client side, I am getting a cors error and havent found a way to set the origin headers in the docs. Is it possible or do I have to switch to socket IO

**Comment by lpinca** [comment]
The same origin policy (CORS) does not apply for WebSocket, so you are probably doing something wrong.

**Comment by maoueh** [comment]
With server:

```
const WebSocket = require("ws");
const rxjs = require("rxjs");

const wss = new WebSocket.Server({ port: 8080 });

wss.on("connection", function connection(ws) {
  ws.on("message", function incoming(message) {
    console.log("received: %s", message);
  });

  rxjs.Observable.interval(500).map(i => {
    ws.send(JSON.stringify({ producer: "AntMiner", block: i.toString() }));
  });
});
```

And client (in the browser, running on `localhost:3000`):

```
import * as WebSocket from "ws"

const ws = new WebSocket("ws://localhost:8080")

ws.on("open", function open() {
  ws.send("something")
})

ws.on("message", function incoming(data: Object) {
  console.log(data)
})
```

The browser complains with the following errors:

```
GET http://localhost:8080/ 426 (Upgrade Required)
<stack trace>

localhost/:1 Failed to load http://localhost:8080/: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access. The response had HTTP status code 426. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

localhost/:1 Uncaught (in promise) TypeError: Failed to fetch
``` 

Not sure what's wrong, something is fishy for sure.

**Comment by lpinca** [comment]
> GET http://localhost:8080/ 426 (Upgrade Required)

The client is not sending an upgrade request. My guess is that you are not using the native `WebSocket` object on the client but a "browserified" one which doesn't work.

**Comment by maoueh** [comment]
@lpinca I double-checked and did not find anything. I will continue investigating but I don't see in my current project build where this would happen (not saying it's not the case though).

**Comment by maoueh** [comment]
I'm not sure I fully understand the problem. What kind of `shim` should I need for `ws` (and is it this project `ws`, I guess).

Also, why it wouldn't work out of the box? I mean, why webpack would play with the `WebSocket` API exactly?

I tried with plain WebSocket API and `sockette` and it's working from there. So not sure why `ws` would not work out of the box?

Thanks for your time 😄though!

**Comment by lpinca** [comment]
Because `ws` needs a plain TCP socket and there is no way to get one in the browser via JavaScript (that's why WebSocket exists).

If you want the above snippet to work include something like this calling it `ws-browser.js`.

```js
var ws = null;

if (typeof WebSocket !== 'undefined') {
  ws = WebSocket;
} else if (typeof MozWebSocket !== 'undefined') {
  ws = MozWebSocket;
} else if (typeof global !== 'undefined') {
  ws = global.WebSocket || global.MozWebSocket;
} else if (typeof window !== 'undefined') {
  ws = window.WebSocket || window.MozWebSocket;
} else if (typeof self !== 'undefined') {
  ws = self.WebSocket || self.MozWebSocket;
}

module.exports = ws;
```

Then in your `package.json` add

```son
"browser": {
  "ws": "./ws-browser.js"
}
```

**Comment by maoueh** [comment]
So then if I get your code snippet right, that would mean using `ws` library for the client in a browser environment is useless (i.e. that `ws` adds nothing at all over the browser `WebSocket` API). Is that correct?

**Comment by maoueh** [comment]
Ok excellent, didn't understood that, I thought `ws` client was wrapping the `WebSocket` API when running in a browser automatically and was adding some goodies which is not the case.

Just to clarify for sake of others:

> other WebSocket library in the browser

It's possible to use a WebSocket library on the browser as long as the said library is wrapping the native `WebSocket` API provided by the browser.

Thank you for all your explanations, problem solved to me (not sure for the initial author).

**Comment by lpinca** [comment]
For me WebSocket library == library that implements the WebSocket protocol 😄

**Comment by lpinca** [comment]
Closing, discussion can continue on the closed thread if needed.
