### ISSUE TITLE
Close method reason and code are undefined

### ISSUE THREAD

**Issue by Apoorva2405** [websockets/ws#1373]
I am sending close() from client. On checking server side onClose, I can see below result:

WS Message received from client: test message
connection closed
reason undefined
code undefined

Below is the server code:

    ws.on('close', function (ev) {
        console.log("connection closed");
        console.log("reason " + ev.reason);
        console.log("code " + ev.code);
    });

How can we check on server side, what code has been sent by client side?

**Comment by lpinca** [comment]
https://github.com/websockets/ws/blob/master/doc/ws.md#event-close

**Comment by Apoorva2405** [comment]
@lpinca So, I am using:
ev.reason
ev.code
But getting undefined values in it

**Comment by lpinca** [comment]
```js
ws.on('close', function (code, reason) {
  console.log(code, reason);
});
```
