### ISSUE TITLE
Connection closed before receiving a handshake response

### ISSUE THREAD

**Issue by pokal4u** [websockets/ws#1374]
Hi,
We are getting below error in some browsers(chrome or mozilla) when we connect mqtt using web sockets. When we clear browser history then connected. 
Error:
**WebSocket connection to 'wss://host:port/mqtt' failed: Connection closed before receiving a handshake response         Paho.MQTT.ClientImpl._doConnect @ mqttws31.js:979**

My connection:

var client = new Paho.MQTT.Client("host", Number(port), "myClientId" + new Date().getTime());
client.connect({userName:username,password:password,onSuccess:onConnect,onFailure:doFail,useSSL:true,cleanSession:false});

So please look into this.
Thanks

**Comment by lpinca** [comment]
This issue report is not very useful. It doesn't say anything about what version of `ws` is used, where and how or if `ws` is used at all? Maybe on the server? So please please fill the issue template correctly and create a minimal test case that reproduces the issue without any external libraries.

**Comment by pokal4u** [comment]
I din't understand your point, I am new to hear.
but this error not for all users and browsers, some users connected in all browsers some users getting this error in chrome or mozilla and it works for that users when they clear the browser cache. 
So how can I reproduce the issue?

**Comment by lpinca** [comment]
`ws` can't be used in the browser so it is definitely not a `ws` issue. Sorry but I can't help.
