### ISSUE TITLE
getter for httpServer internal 

### ISSUE THREAD

**Issue by Mathsfly** [websockets/ws#1375]
- [x] I've searched for any related issues and avoided creating a duplicate issue.

#### Description
There isn't 'close' event for server, it may be useful the 'listening' event  and 'close' event  of httpServer. I think we should make a httpServer getter of  Server that is actually private.

**Comment by lpinca** [comment]
Adding a getter for the private http server is like making it public. I don't think it makes sense.
We can forward the `'close'` event to the `WebSocketServer` but it's already possible to use that event by using an external http server.

```js
const server = http.createServer();

const was = new WebSocket.Server({ server });

server.on('close', function () {
  // ...
});
server.listen();
```

**Comment by Mathsfly** [comment]
The purpose is to make the 'close' event to be official that we can use it in both case.  
`
// Create internally, listening automatically
const wss = new WebSocket.Server({ port: 3333 });
//does 
wss.on('listening', function () {
  // ...
});
//behavior given
wss.close(callback)

// behavior expect
wss.on('close', () => {})
wss.close()
`

**Comment by lpinca** [comment]
The problem is that our listeners are [removed](https://github.com/websockets/ws/blob/690b3f277c6f5c3aef8cd84792929450f516b3ae/lib/websocket-server.js#L125) when `WebSocketServer.prototype.close()` is called so we can't currently reemit the `'close'` event.

We can remove the listeners after the `'close'` event  is emitted but I'm not sure if it has side effects.

**Comment by izelnakri** [comment]
Is there any way to listen to WebSockerServer close currently?

**Comment by lpinca** [comment]
There is no `'close'` event on `WebSocketServer` only on the internal HTTP server.

```js
wss.close(function () {
  // Clear listeners.
});
```
