### ISSUE TITLE
Accessing request object

### ISSUE THREAD

**Issue by fabiosantoscode** [websockets/ws#1377]
- [x] I've searched for any related issues and avoided creating a duplicate issue.

#### Description

I'm developing a websocket-based API, and I'd like to communicate some parameters out-of-band using the socket URL. To do this, I need to be given the request object, or just the URL.

### Expected result:

```
wss.on('connection', ws => assert(ws.request))
// or
wss.on('connection', ws => assert(ws.url))
```

**Comment by lpinca** [comment]
```js
wss.on('connection', (ws, req) => {
  // Do whatever you want with `req`.
});
```

**Comment by fabiosantoscode** [comment]
Thanks!
