### ISSUE TITLE
Android Browser not closing WebSocket connections

### ISSUE THREAD

**Issue by endel** [websockets/ws#1380]
Hi there,

I've noticed that Mobile Chrome doesn't close WebSocket connections properly on Android. I'd like to have a discussion in case someone had this problem before.

**Steps to reproduce:**
- Open Chrome on Android
- Create a WebSocket connection
- Move Chrome to the background
- Reboot the phone

The WebSocket connection will remaing active with `readyState` as `OPEN`.

Maybe there's some event I'm missing? I have no idea how to fix this.
Cheers!

**Comment by endel** [comment]
The same behaviour can be observed on `uws` library.

**Comment by lpinca** [comment]
This is another example of https://github.com/websockets/ws#how-to-detect-and-close-broken-connections

**Comment by endel** [comment]
I see, thanks a lot @lpinca! You're always so helpful! <3
