### ISSUE TITLE
MaxListenersExceededWarning when opening more then 11 connections 

### ISSUE THREAD

**Issue by aryeharmon** [websockets/ws#1381]
wsServer = new ws.Server({}) * 11 

(node:19024) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit

**Comment by lpinca** [comment]
Please fill the issue template correctly, this issue description is not useful. Show us a piece of code that reproduces the issue.

Thanks.

**Comment by lpinca** [comment]
Closing, feel free to reopen if you have more details.
