### ISSUE TITLE
Events connection/opened explained [docs]

### ISSUE THREAD

**Issue by damianobarbati** [websockets/ws#1386]
Sorry to bother and it may be a very stupid question but I didn't find proper documentation about this neither here in ws docs or mozilla resources (?!).

What's the difference between "open" and "connection" event? What's the order in which they happen? Are there other events? 

Thanks for the great work!

**Comment by lpinca** [comment]
`'connection'` is a server only event, `'open'` is instead emitted on the `WebSocket` object. `'connection'` and `'open'` are emitted in the same tick on the server and this is why you can ignore the `'open'` event on the server.

All events are documented here: https://github.com/websockets/ws/blob/master/doc/ws.md

**Comment by damianobarbati** [comment]
Thanks @lpinca !
