### ISSUE TITLE
add Support of Express Websocket Router

### ISSUE THREAD

**Issue by yiakwy** [websockets/ws#1387]
Hi, here is a solution by adding faked wbsocket router method to "Application", and "Router".

> amekkawi/express-ws-routes#8.

His solution is really nice. But there is no people maintaining it. It does not work in new version of express and websocket anymore.

Could any developers help me to figure out how to modify the code so that we can use it again?

**Comment by lpinca** [comment]
Sorry but this issue tracker is only for bugs and feature requests, please use another channel like SO for that kind of questions.

**Comment by yiakwy** [comment]
copy
