### ISSUE TITLE
How to get the specified websocket connection object.

### ISSUE THREAD

**Issue by thankjava** [websockets/ws#1388]
#### Description
```
Dear:
The documentation shows that I can get all available webscocket 
connection objects in the following code.
```
```javascript
const wss = new WebSocket.Server({ port: 8080 });
const clients = wss.clients;
```
```
So how do I find out exactly what I want from them?
Just like every connection is another unique identifier,
I can get it directly through this identifier.
I now create a Map object to store it and then get the target based on my Key. 
However, doing so I need to maintain my Map object to keep it 
synchronized with the clients object.
Is there any graceful practice in the government?
Just as you will assign an ID for each connection,
I can get a connection through the associated API and this ID.
I think this may be a relatively frequent demand.
Looking forward to your reply.
```

**Comment by lpinca** [comment]
Yes, you have to maintain your own list of connections and eventually assign a unique id to each connection. If you don't want to have two lists, you can disable `clientTracking` in `ws`.

**Comment by thankjava** [comment]
Okey~
But I think you can provide a similar API, because more details of the interaction you know best, so we do not have to repeat the wheel.
Thanks.

**Comment by lpinca** [comment]
No, it's out of the scope of this module. If it can be done outside of `ws` it does not belong to this module. Ideally this module should only implement protocol specification and nothing else.

**Comment by thankjava** [comment]
Yes, this is true for module, thank you for your doubts.

**Comment by SuperXFan** [comment]
How do we get information from each client?  like   host  port ...    and i also  want to know about every client  name,type  and so on

**Comment by eskimo** [comment]
> No, it's out of the scope of this module. If it can be done outside of `ws` it does not belong to this module. Ideally this module should only implement protocol specification and nothing else.

This is a pretty dumb reply. Nearly every websocket lib for every other language keeps track of clients like this issue is about.
