### ISSUE TITLE
This is more a question then a issue about the perMessageDeflate?

### ISSUE THREAD

**Issue by LittleGnome** [websockets/ws#1391]
If I have this
`new Webscoket.Server({
host: 'url', 
port: 8080,
perMessageDeflate: true
})`
will this work to turn the perMessageDeflate on??

This line is from the documentation:
"perMessageDeflate {Boolean|Object} Enable/disable permessage-deflate." 

But I can't really understand if a boolean true does the trick with default values or I need to pass a empty object through.

Many thanks for giving the answer to this probably stupid question.

**Comment by lpinca** [comment]
Yes that will work.
