### ISSUE TITLE
Emit event for upgrade errors?

### ISSUE THREAD

**Issue by danfuzz** [websockets/ws#1392]
- [x] I've searched for any related issues and avoided creating a duplicate issue.

#### Description

I'm interested in adding enough listeners to a websocket server, such that I can log its activity meaningfully (such as ultimately to an HTTP log file), including in error cases. As currently designed, there is at least one case which can't be logged (at least not in a straightforward way).

Specifically, when `abortHandshake()` gets called (such as when the configured `path` doesn't match), no event gets emitted from the server which might be used as a trigger to log the failure.

#### Reproducible in:

version: 5.2.0
Node.js version(s): 10.2 (but irrelevant)
OS version(s): macOS (but irrelevant)

#### Steps to reproduce:

[This feature request doesn't quite fit the "steps-to-repro" model, but here's a go…]

1. `wsServer = new ws.Server(...);`
2. `wsServer.on('upgradeError', (headers) => { console.log(headers); });`.

### Expected result:

Headers from errors during an upgrade get logged to the console.

### Actual result:

`upgradeError` event never gets emitted.

### Attachments:

N/A

**Comment by lpinca** [comment]
I suggest to use an external HTTP server, which gives you a lot of more freedom.

```js
const wss1 = new WebSocket.Server({ noServer: true });
const wss2 = new WebSocket.Server({ noServer: true });
const server = http.createServer();

function handshakeAborted() {
  // your logic.
}

server.on('upgrade', (request, socket, head) => {
  const pathname = url.parse(request.url).pathname;

  function handshakeAborted() {
    // your logic.
  }

  socket.on('close', handshakeAborted);

  if (pathname === '/foo') {
    wss1.handleUpgrade(request, socket, head, (ws) => {
      socket.removeListener('close', handshakeAborted);
      wss1.emit('connection', ws);
    });
  } else if (pathname === '/bar') {
    wss2.handleUpgrade(request, socket, head, (ws) => {
      socket.removeListener('close', handshakeAborted);
      wss2.emit('connection', ws);
    });
  } else {
    socket.destroy();
  }
});
```

**Comment by lpinca** [comment]
@danfuzz is the suggested method to track failed upgrade satisfactory?

**Comment by danfuzz** [comment]
Not really, because I'd like to be able to log what `ws` thinks. For example, with your suggested arrangement, I can't tell what status code or headers `ws` reported back to the client.

**Comment by lpinca** [comment]
I thought `headers` in your example was referring to request headers, not response headers.
Response status code and headers are hardcoded unless `verifyClient()` is used and in that case you already have a way to log the status code and headers as they are passed from `verifyClient()` itself.

**Comment by danfuzz** [comment]
I understand your position. From my perspective, though, I don't want to have to hard-code details of `ws`'s implementation into my code; I'd prefer instead it to have a contract for reporting its actions back to its clients.

**Comment by lpinca** [comment]
Got it, to keep the codebase small and easy to maintain I prefer to add only things that can't be solved outside of `ws` and this is not exactly one of those things but I understand that doing it outside of `ws` is a bit cumbersome. Feel free to open a PR.
