### ISSUE TITLE
TypeError: Cannot read property 'add' of null

### ISSUE THREAD

**Issue by fuchidahiro** [websockets/ws#1397]
- [X] I've searched for any related issues and avoided creating a duplicate issue.

Similar issue was about timeout, does not seem related.

#### Description

As mentioned in https://github.com/amark/gun/issues/535
```
.....\node_modules\ws\lib\websocket.js:143
    this._ultron.on('data', (data) => this._receiver.add(data));
                                                     ^

TypeError: Cannot read property 'add' of null
    at Socket._ultron.on (....\node_modules\ws\lib\websocket.js:143:54)
    at Socket.emit (events.js:185:15)
    at Socket.emit (domain.js:422:20)
    at addChunk (_stream_readable.js:274:12)
    at readableAddChunk (_stream_readable.js:261:11)
    at Socket.Readable.push (_stream_readable.js:218:10)
    at TCP.onread (net.js:581:20)
```
using
this.gun.opt({peers: peers}) (nodejs GunServer)

Then getting a gun.js:2024 WebSocket connection to 'ws://127.0.0.1:7667/gun' failed: Invalid frame header which also seems replated. Happens on differrent peers, running on differrent peers all same code base.

#### System Info:

version:4.0.0
Node.js version(s): 8.11.2
OS version(s): N/A

### Expected result:

Websocket Connection added as peer

### Actual result:

Error message after which a invalid frame header error message is generated.

**Comment by amark** [comment]
Author of amark/gun here, just wanted to say I'm pretty sure this isn't our fault (maybe?) because the error stack is full `ws` (no gun source code listed) and `Cannot read 'add' of null` is a fairly common error when a typecheck isn't handled.

Would it be helpful if we PRed a patch like:

```
this._ultron.on('data', (data) => this._ && this._.receiver && this._receiver.add(data));
```

?

**Comment by lpinca** [comment]
Not sure how this can happen. [`ultron` is destroyed](https://github.com/websockets/ws/blob/a04d9855a5a3d9bab62f9d22bcf5d1ee8185726b/lib/websocket.js#L196) before nulling the [`_receiver`](https://github.com/websockets/ws/blob/a04d9855a5a3d9bab62f9d22bcf5d1ee8185726b/lib/websocket.js#L208) property. When `ultron` is destroyed the `'data'` listener is removed synchronously so no more `'data'` event should be handled.

Anyway the 4.x release line is no longer supported, so I suggest to update to `ws@5`.

**Comment by amark** [comment]
Interesting. Thanks, updating to ws@5 , please close, will re-open if we see it again.
