### ISSUE TITLE
Firefox changes URL protocol from wss to https when sending a websocket upgrade HTTP request

### ISSUE THREAD

**Issue by dariour** [websockets/ws#1398]
- [x] I've searched for any related issues and avoided creating a duplicate issue.

#### Description

This issue only occurs in firefox (React frontend app using ws to establish websocket connetcion). While trying to fetch data Firefox automatically resolves url protocol from wss to https which causes issues during load balancing. Instead 101 message we get a 404 not found. Is there a way to mitigate said behavior?

#### Reproducible in:

version: 3.3.2
Node.js version(s): 8.10.0
OS version(s): Any

**Comment by lpinca** [comment]
Why is this a problem? For the load balancer it's still TLS, it doesn't matter if the connection was initiated from a url starting with `wss:` or `https:`.

Anyway it doesn't seem to be an issue in this module.

**Comment by lpinca** [comment]
Closing, discussion can continue if needed.
