### ISSUE TITLE
cannot able to resolve 'net','tls' and fs when using the ws package

### ISSUE THREAD

**Issue by anikethsaha** [websockets/ws#1399]
I am using ws package as a third argument in a apollo subscription as it is 

> Unable to find native implementation, or alternative implementation for WebSocket! in subscription client in apollo subscription
But when using this package I am getting error 

> Cannot able to resolve 'fs'
then same for net and tls
and in the browser console same error

```
const  ws  = require('ws').ws;
// Create an http link:
const httpLink = new HttpLink({
  uri: 'http://localhost:3000/graphql'
});

// // Create a WebSocket link:
// const wsLink = new WebSocketLink({
//   uri: `ws://localhost:3000/subscriptions`,
//   options: {
//     reconnect: true
//   }
// });

const GRAPHQL_ENDPOINT = "ws://localhost:3000/subscriptions";

const wsClient = new SubscriptionClient(GRAPHQL_ENDPOINT, {
  reconnect: true
},ws);

const wsLink = new WebSocketLink(wsClient);


```
My webpack.config
```
ApolloServerConfig = {
              entry: './src/ApolloServer/index.js',
              output: {
                    path: path.resolve(__dirname),
                    filename: './subscriptionServer.js',
                    libraryTarget: "commonjs2",
                    publicPath: '/'

                },
                node: {
                    __dirname: false,
                    net :'empty',
                    tls : 'empty'
                },
              target: 'node',
              externals:[nodeExternals()],
              plugins: [
                 new webpack.DefinePlugin({
                   __isBrowser__: "false"
                 })
               ],
              module: {
                  loaders: [
                      {
                          test: /\.js$/,

                          exclude: /(node_modules)/,
                          loader: 'babel-loader',
                          query: {
                              presets: ['es2015', 'react']
                          }
                      }
                  ]
              },
              devServer: {
                historyApiFallback: true,
              }
};
```

**Comment by lpinca** [comment]
https://github.com/websockets/ws#ws-a-nodejs-websocket-library

> This module does not work in the browser. The client in the docs is a reference to a back end with the role of a client in the WebSocket communication. Browser clients must use the native WebSocket object. To make the same code work seamlessly on Node.js and the browser, you can use one of the many wrappers available on npm, like isomorphic-ws.

**Comment by anikethsaha** [comment]
@lpinca I got your point . But my node console is showing unable to use the native websocket .I dont know why it is showing like the. I used the isomorphic-ws it is showing the errors related to 'net' which is coming from the `ws` package.

**Comment by lpinca** [comment]
I don't know but I'm pretty sure this is not a `ws` issue. Also this line

```js
const  ws  = require('ws').ws;
```

from the above snippet does not have much sense. This module does not export anything with the `ws` name. I think it should be `const  ws  = require('ws')`.

**Comment by anikethsaha** [comment]
Yeah...it seems this issue is with apollo-link only and this `require('ws').ws` is typo error actually
