### ISSUE TITLE
Logging feature ?

### ISSUE THREAD

**Issue by Altiano** [websockets/ws#1400]
- [x] I've searched for any related issues and avoided creating a duplicate issue.

#### Description
I don't see any documentation for logging the message. I need to know the message size sent to `ws` server.

I'm using non-browser ws client so it is important for me to know how many bytes the received message is

**Comment by lpinca** [comment]
```js
wss.on('connection', function (ws) {
  ws.on('message', function (message) {
    if (typeof message === 'string') {
      console.log(Buffer.byteLength(message));
    } else {
      console.log(message.length);
    }
  });
});
```

**Comment by Altiano** [comment]
Yup. Thanks. Probably should open an issue, but there is no other way.
