### ISSUE TITLE
Secure client code

### ISSUE THREAD

**Issue by happydebugging** [websockets/ws#1401]
Trying to use Secure Websockets but got an Error: self signed certificate.
Is there any good way to run encrypted connection  on a localhost/network ?

**Comment by lpinca** [comment]
On Node.js you can set the `rejectUnauthorized` option to false, on the browser you have to add an exception to trust the self-signed certificate.

**Comment by happydebugging** [comment]
Thanks, that worked.

**Comment by lpinca** [comment]
Good, closing then.
