### ISSUE TITLE
How can I get headers from websocket client using ws, not socket.io?

### ISSUE THREAD

**Issue by tannineo** [websockets/ws#1407]
- [x] I've searched for any related issues and avoided creating a duplicate issue.

#### Description

For some reasons our team choose to use `ws` instead of `socket.io`. when it comes to authentication, I want to get the headers from the webscoket client.  

The `client` in ws-adapter depends on it's package so I refer to the [FAQ](https://github.com/websockets/ws#how-to-get-the-ip-address-of-the-client) and find that the callback of event `connection` is like `(client, req) => {}`.  

I try to get the header from the `connection` req but it seems to have no way. The code in `web-sockets-controller.ts` is like:
```ts
  public getConnectionHandler(
    context: WebSocketsController,
    instance: NestGateway,
    messageHandlers: MessageMappingProperties[],
    disconnect: Subject<any>,
    connection: Subject<any>,
  ) {
    const adapter = this.config.getIoAdapter();
    return client => {
      connection.next(client);
      context.subscribeMessages(messageHandlers, client, instance);

      const disconnectHook = adapter.bindClientDisconnect;
      disconnectHook &&
        disconnectHook.call(adapter, client, _ => disconnect.next(client));
    };
  }
```
It returns a func which receives only `client` but no `req`.  Then this func is binded to the `connection` event in `ws-adapter.ts`:
```ts
  public bindClientConnect(server, callback: (...args) => void) {
    server.on(CONNECTION_EVENT, callback);
  }
```

How can I get the headers from the connection req?

**Comment by lpinca** [comment]
As you said you can get the header from the headers from the `http.IncomingMessage` object (`req`) that is passed to the listeners of the `'connection'` event.

```js
wss.on('connection', (ws, req) {
  console.log(req.headers);
});
```

**Comment by tannineo** [comment]
THX @lpinca.
So this means to modify `web-sockets-controller.ts` which is in `@nestjs/websockets`?

**Comment by lpinca** [comment]
I think so, I have no idea how @nestjs/websockets works :)

**Comment by tannineo** [comment]
Oh sorry I made a mistake by publishing this issue here, it should be in another project.
Sorry for the bothering. @lpinca
