### ISSUE TITLE
WebSocket.Server event 'headers' listener isn't called

### ISSUE THREAD

**Issue by ziglee** [websockets/ws#1409]
- [X] I've searched for any related issues and avoided creating a duplicate issue.

#### Reproducible in:

version: 5.2.1
Node.js version(s): 8.9.4
OS version(s): Windows 10

#### Steps to reproduce:

const WebSocket = require('ws');
const wss = new WebSocket.Server({
  port: 8091
});
wss.on('headers', function(headers) {
  console.log('headers', headers);
});

### Expected result:

Should log in the console the response headers.

### Actual result:

Nothing is logged 

### Attachments:

The client (ionic app running in Chrome at http://localhost:8100/) gets the following errors:

GET http://localhost:8091/ 426 (Upgrade Required)
Failed to load http://localhost:8091/: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8100' is therefore not allowed access. The response had HTTP status code 426. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by lpinca** [comment]
> `GET http://localhost:8091/ 426 (Upgrade Required)`

This means that the request hitting the WebSocket server does not have the required headers, precisely 

```
Connection: upgrade
Upgrade: websocket
```

In this case the server does not switch the protocol and responds with [426](https://github.com/websockets/ws/blob/5d90141505dc41c129ab5d5228e37d49979d7541/lib/websocket-server.js#L59-L67).

This works as intended, the `'headers'` event is only emitted when the WebSocket handshake completes successfully.

**Comment by ziglee** [comment]
Thanks @lpinca . I guess the client messed up with the protocol.
