### ISSUE TITLE
An error in example "External HTTP/S server"

### ISSUE THREAD

**Issue by freeheart** [websockets/ws#1412]
`const fs = require('fs');
const https = require('https');
const WebSocket = require('ws');

const server = new https.createServer({
  cert: fs.readFileSync('/path/to/cert.pem'),
  key: fs.readFileSync('/path/to/key.pem')
});
const wss = new WebSocket.Server({ server });

wss.on('connection', function connection(ws) {
  ws.on('message', function incoming(message) {
    console.log('received: %s', message);
  });

  ws.send('something');
});

server.listen(8080);`

### const wss = new WebSocket.Server({ server });
should change to 
### const wss = new WebSocket.Server({ server:server});

If I change the server's name 'server' to the other,such as 'webs'.
It will boom a error .

**Comment by lpinca** [comment]
It isn't an error it's the shorthand syntax, see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Object_initializer.
