### ISSUE TITLE
how configure on 2 server in load balancing

### ISSUE THREAD

**Issue by ddtraceweb** [websockets/ws#1416]
Hello,

i don't find how to configure a setup with 2 servers in load balancing, have you an example ?

Thanks,

**Comment by lpinca** [comment]
Hi,
this is not the place for these kind of questions. This issue tracker is only for bugs and feature requests.

Anyway you can use the cluster module on use a reverse proxy like NGINX or HAProxy in front of your servers.

**Comment by lpinca** [comment]
Closing as answered, discussion can continue if needed.
