### ISSUE TITLE
ws crashes node server

### ISSUE THREAD

**Issue by jabberwock31415** [websockets/ws#1417]
- [x ] I've searched for any related issues and avoided creating a duplicate issue.

I'm fairly new to nodejs and just starting to add websocket support.  My initial test managed to crash my server which seems very wrong to me--however bad my client is, the server shouldn't crash

#### Reproducible in:

version: 5.2.1
Node.js version(s): 8.10
OS version(s): Ubuntu Xenial  (Linux 4.4.0-128-generic, x86_64)

#### Steps to reproduce:

1.  Create a minfail.js file with the following:
```
const websocket = require('ws');
const wss = new websocket.Server({ port: 8080 });

wss.on('connection', (ws) => {
    ws.on('message', function msg (message) {
        console.log('received: %s', message);
    });
    ws.send('something', function snd (err) {
        if (err)
            console.error(`WebSocket failed: ${err}`);
    });
});
```
2.  run "node minfail.js"

3. In another window, telnet localhost 8080 and enter the following text after connected:
```
GET /chat HTTP/1.1
Host: foo.bar.com
Upgrade: websocket
Connection: Upgrade
Origin: http://foo.com
Sec-WebSocket-Key: x3JJHMbDL1EzLkh9GBhXDw==
Sec-WebSocket-Protocol: chat, superchat
Sec-WebSocket-Version: 13



```
(note that there are three carriage returns at the end)

### Expected result:
I'd get back the text string "something" and then presumably a disconnect because the final carriage return is a protocol violation

### Actual result:

I get the "something" string, and then the node server crashes with:
```
events.js:183
      throw er; // Unhandled 'error' event
      ^

RangeError: Invalid WebSocket frame: invalid opcode 13
    at Receiver.getInfo (/mnt/storage/npl/www/express-web/node_modules/ws/lib/receiver.js:215:14)
    at Receiver.startLoop (/mnt/storage/npl/www/express-web/node_modules/ws/lib/receiver.js:121:22)
    at Receiver._write (/mnt/storage/npl/www/express-web/node_modules/ws/lib/receiver.js:69:10)
    at doWrite (_stream_writable.js:397:12)
    at writeOrBuffer (_stream_writable.js:383:5)
    at Receiver.Writable.write (_stream_writable.js:290:11)
    at Socket.socketOnData (/mnt/storage/npl/www/express-web/node_modules/ws/lib/websocket.js:794:35)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)

```

**Comment by lpinca** [comment]
Add a listener for the `'error'` event:

```js
wss.on('connection', (ws) => {
  ws.on('error', console.error);
});
```

**Comment by jabberwock31415** [comment]
Could you please reopen this bug

This solution did not work--I get the same crash.

**Comment by lpinca** [comment]
@jabberwock31415 I can't reproduce. Here is your same code with the `'error'` listener added:

```js
const WebSocket = require('ws');
const wss = new WebSocket.Server({ port: 8080 });

wss.on('connection', (ws) => {
  ws.on('error', console.error);
  ws.on('message', function msg (message) {
    console.log('received: %s', message);
  });
  ws.send('something', function snd (err) {
    if (err)
      console.error(`WebSocket failed: ${err}`);
  });
});
```

It doesn't crash.

**Comment by jabberwock31415** [comment]
Thank you!  I had a typo in my implementation of your solution.  You are correct--this works fine.  Thank you for taking the time to help me.
