### ISSUE TITLE
Use of this[kWebSocket] after it was undefined in socketOnData()

### ISSUE THREAD

**Issue by jpambrun** [websockets/ws#1418]
- [x] I've searched for any related issues and avoided creating a duplicate issue.

#### Description

Use ```this[kWebSocket]._receiver.write(chunk)``` in [socketOnData (chunk)](https://github.com/websockets/ws/blob/master/lib/websocket.js#L793) after ```this[kWebSocket]``` was set to undefined in [socketOnClose ()](https://github.com/websockets/ws/blob/master/lib/websocket.js#L755)

It might be related to the ```websocket._socket.read()``` after ```this[kWebSocket] = undefined``` at [websocket.js#L769](https://github.com/websockets/ws/blob/master/lib/websocket.js#L769)

#### Reproducible in:

version: 5.21
Electron version: 2.0.4
OS version(s): Linux

#### Steps to reproduce:

Not 100% sure. Close the socket while fragments are still coming in? 

### Expected result:

No 'cannot read property X of undefined exception' in the library.

### Actual result:

Exception thrown.

**Comment by lpinca** [comment]
Good catch, I think this has been introduced with https://github.com/websockets/ws/commit/6046a2873944793b01457488aed8062ccaa53743.

https://github.com/websockets/ws/commit/6046a2873944793b01457488aed8062ccaa53743#diff-13a0e23b4df05bd40179ab73312bf77bR754 should go after the `'data'` event listener is removed.

**Comment by jpambrun** [comment]
I didn't realize my commit would get linked here. It says 'fix', but it's really just a poor man's workaround.

**Comment by lpinca** [comment]
No problem, don't worry about that.

**Comment by lpinca** [comment]
Should be fixed on master, I'll release 5.2.2 shortly.

**Comment by lpinca** [comment]
Ok, version 5.2.2 is out, please let me know if the issue persists. It's an edge case that is not covered by tests.

Thank you.

**Comment by jpambrun** [comment]
Yep, that did it. Thanks for the unbelievably fast response.
