### ISSUE TITLE
message sender identity

### ISSUE THREAD

**Issue by Merethiel** [websockets/ws#1419]
Hi I would like to use this library to write a server but instantly I noticed an issue that I can't really wrap my head around the design of. 
Every code example I see of ws, the on_message callback is placed directly inside the connecting callback which ws is an argument, then ws.on('message') function callback is set. But the only argument which gets passed into the 'message' callback is an argument of message. There is no identifier for which client actually sent that message. Unless it's part of the message object but I don't know enough about it. Is there a message.sender? To me it makes sense for a server to establish all callbacks at the beginning then on each callback routine, an identifier a long with extra arguments are passed. The identifier could be like the socket connection, or specific object created specifically for that socket. I'm not seeing this with the ws library. Is there any solution for this?

**Comment by lpinca** [comment]
See https://github.com/websockets/ws/issues/859 or https://github.com/websockets/ws/issues/1308 and possibly other closed issues for the question.

**Comment by Merethiel** [comment]
Oh okay, so I can simply do,
`wss.ClientUniqueId = UniqueId` upon joining, then check that later through the message callback. Is there a way though to remove the message callback from the main connection handler? Does it have to be tied in that same handler?

**Comment by lpinca** [comment]
> Is there a way though to remove the message callback from the main connection handler? Does it have to be tied in that same handler?

Not sure what you mean, you can use a single listener for the `'message'` event shared among all your WebSocket instances or use one per WebSocket:

```js
function onMessage(message) {
  console.log(this.id);
}

wss.on('connection', function (ws) {
  ws.id = uuid();
  ws.on('message', onMessage);
});
```

or 

```js
wss.on('connection', function (ws) {
  const id = uuid();
  ws.on('message', function (message) {
    console.log(id);
  });
});
```

Both works.

**Comment by Merethiel** [comment]
Thank you! That helped a lot!

**Comment by lpinca** [comment]
Ok, I'm going to close this then.
