### ISSUE TITLE
express-session-parse  Failure to use DEMO

### ISSUE THREAD

**Issue by thinkive** [websockets/ws#1422]
I can't reproduce, the example works for me. Try to log info.req.session here

[ ws/examples/express-session-parse/index.js  ](https://github.com/websockets/ws/blob/38d2e8b3f75ebccf8b0b205fafac959c1702ddfb/examples/express-session-parse/index.js#L54)
`info.req.session` is undefined

**Comment by lpinca** [comment]
I can't reproduce, the example works for me. Try to log `info.req.session` here https://github.com/websockets/ws/blob/38d2e8b3f75ebccf8b0b205fafac959c1702ddfb/examples/express-session-parse/index.js#L54.

Also please fill the issue template correctly.

**Comment by thinkive** [comment]
This is my code problem here, the problem is closed
