### ISSUE TITLE
node_api.h: No such file or directory

### ISSUE THREAD

**Issue by jana4cheyenne** [websockets/ws#1425]
hi support, error "node_api.h: No such file or directory" when i install ws@1, 
what can i do? tkx.

=====================================================
[root@ffmpeg-01 0.0.2.0]# npm install --save bufferutil ws@1
|
> bufferutil@4.0.0 install /usr/local/telbet/jana/0.0.2.0/node_modules/bufferutil
> node-gyp-build

make: Entering directory `/usr/local/telbet/jana/0.0.2.0/node_modules/bufferutil/build'
  CC(target) Release/obj.target/bufferutil/src/bufferutil.o
../src/bufferutil.c:2:22: fatal error: node_api.h: No such file or directory
 #include <node_api.h>
                      ^
compilation terminated.
make: *** [Release/obj.target/bufferutil/src/bufferutil.o] Error 1
make: Leaving directory `/usr/local/telbet/jana/0.0.2.0/node_modules/bufferutil/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.10.0-862.6.3.el7.x86_64
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/telbet/jana/0.0.2.0/node_modules/bufferutil
gyp ERR! node -v v4.4.7
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
npm ERR! Linux 3.10.0-862.6.3.el7.x86_64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--save" "bufferutil" "ws@1"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! code ELIFECYCLE

npm ERR! bufferutil@4.0.0 install: `node-gyp-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bufferutil@4.0.0 install script 'node-gyp-build'.
npm ERR! This is most likely a problem with the bufferutil package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs bufferutil
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls bufferutil
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/local/telbet/jana/0.0.2.0/npm-debug.log
[root@ffmpeg-01 0.0.2.0]#

**Comment by lpinca** [comment]
Use an older version of https://github.com/websockets/bufferutil. Version 4.x does not work with Node.js < 6.

```
npm install --save bufferutil@3 ws@1
```

Anyway if you can update everything.
