### ISSUE TITLE
ECONNREFUSED throws a fatal exception

### ISSUE THREAD

**Issue by artus9033** [websockets/ws#1426]
ECONNREFUSED throws a fatal exception, closing the app

- [ ] I've searched for any related issues and avoided creating a duplicate issue.

#### Description

If a network error makes the client disconnect from a web socket server, the whole program crashes:

`Socket error:  { Error: connect ECONNREFUSED 127.0.0.1:3000
    at Object._errnoException (util.js:1021:11)
    at _exceptionWithHostPort (util.js:1043:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1175:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 3000 }`

Handling the error with process.on("uncaughtException", (err)=>{}) does not help, as it enables the program to execute to WS's lib/websocket.js line 524, where it turns out that `this._req` is null and a TypeError occurs. Changing the if statement to `if (this._req && this._req.aborted) return;` helps, but shortly afterwards, a "socket hang up error" crashes the program:

`Error: socket hang up
    at createHangUpError (_http_client.js:329:15)
    at Socket.socketCloseListener (_http_client.js:361:23)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at TCP._handle.close [as _onclose] (net.js:547:12)`

I tried modifying the WS's lib/websocket.js at the line 514: `var req = this._req = httpObj.get(options);` to `var req = (this._req = httpObj.get(options).on("error", (err) => {console.error("ERROR", err);});`, but it didn't help (although probably should?).

#### Reproducible in:

version: 6.0.0
Node.js version(s): 8.7.0
OS version(s): Windows 10 x64

#### Steps to reproduce:

1. Create an instance of WebSocket.Server
2. Create an instance of WebSocket & connect it to that server
3. Interrupt the connection (e.g. shut down the server during connection)

### Expected result:

WebSocket instance fires a "close" event

### Actual result:

The program crashes

### Attachments:

Logs pasted in description

**Comment by lpinca** [comment]
Add a listener for the `'error'` event.

**Comment by artus9033** [comment]
Alright, thanks, I found the problem. I was listening for the 'error' event, but I was doing this in a wrapper, which also needed to emit errors, but only non-fatal ones. The line which was causing the crash was `this.emit("error", ...)` in the wrapper. Thanks again and sorry for the problem

**Comment by loucadufault** [comment]
We are seeing this issue using ws@8.18.0, the `'error'` listener is not called despite being registered on the `WebSocket` client, and the app crashes.

**Comment by leumasic** [comment]
Also encountered the same bug @loucadufault
