### ISSUE TITLE
cyclic object When trying to stringify connection

### ISSUE THREAD

**Issue by goriunov** [websockets/ws#1434]
- [x] I've searched for any related issues and avoided creating a duplicate issue.

#### Description
When i try to run JSON.stringify on new connection i getcyclic object  error not surre if it is a big issue but it is better to check out ( may be can improve momory managment) 

#### Reproducible in:

version: very old i have seen it from vertion 3 and till 6.0.0
Node.js version(s): 8.9
OS version(s): mac os

#### Steps to reproduce:

1. On connection run JSON.stringify on the passed option. 
2.
3.

**Comment by lpinca** [comment]
This is done on purpose, see https://github.com/websockets/ws/blob/1e78aba9b9b29407517ec7ba1da97427c1678e5c/lib/websocket.js#L130-L131.

This way we can have a single shared handler for socket events instead of n where n is the number of connections.

**Comment by goriunov** [comment]
Thanks :)
