### ISSUE TITLE
WSS Error on Localhost

### ISSUE THREAD

**Issue by dcflow** [websockets/ws#1437]
- [x] I've searched for any related issues and avoided creating a duplicate issue.

#### Description

Hello,

I have followed the instructions over at `External HTTP/S server` to connect the websocket over https but I keep getting an error saying the connection to the websocket failed `ERR_SSL_PROTOCOL_ERROR `. 
I'm using a self-signed certificate for `localhost` and the server and client use the same `cert` and `key`.
Is it possible to test `ws` with https on localhost or `ws` cannot recognize self-signed certificates?

Thank You!

**Comment by lpinca** [comment]
Use the `rejectUnauthorized` option on the client, set it to `false`.

**Comment by lpinca** [comment]
See https://github.com/websockets/ws/blob/1e78aba9b9b29407517ec7ba1da97427c1678e5c/test/websocket.test.js#L1634-L1651.

**Comment by dcflow** [comment]
Hey @lpinca thank you for your help.
It turned out that the problem was I was setting a custom port `WebSocket.Server({ server , port: 3005})`. 
It's strange cause with `http` custom ports work, anyway thanks again :smile:.
