### ISSUE TITLE
Unable to catch some errors. Servers crashes

### ISSUE THREAD

**Issue by a-shafir** [websockets/ws#1442]
I notices some "RSV1 must be clear" errors in one project most likely related to unstable WiFi hardware of the slave device. It happens into PING/PONG scenario.

The real problem is that i see no way to put try/catch on it so the server is crashing/restarting completely that is unacceptable. 

According my finding there crash happens because on receiver.js (69) there is no result check of
    this.startLoop(cb);

**Comment by slidenerd** [comment]
I was having this issue but I emitted the error event and handled it
