### ISSUE TITLE
Connection Reset

### ISSUE THREAD

**Issue by Kio-td** [websockets/ws#1443]
- [ *] I've searched for any related issues and avoided creating a duplicate issue.

#### Description

The issue I have is that I am suddenly unable to connect when I use my domain, both w/ and w/o cloudflare. When I ran a mini-http server, it shows that it's able to connect, ruling out DNS & Cloudflare as the issue.
The funny thing is though, is that I am able to use my IP address to connect to the websocket.

I'm using the detached https server to host 4 websockets, all of which time out in both the websocket client and in the browser's omnibox.

#### Reproducible in:

version: 6.0.0
Node.js version(s): 10.10.0-1nodesource1
OS version(s): Linux debian-stretch-1 4.9.0-8-amd64 #1 SMP Debian 4.9.110-3+deb9u4 (2018-08-21) x86_64 GNU/Linux

#### Steps to reproduce:
Sadly, I'm unsure how to reproduce this.

### Expected result:
Normal greeting from the webserver from the domain.

### Actual result:
Timeout from the domain.

**Comment by lpinca** [comment]
Try to just use https://nodejs.org/api/dns.html#dns_dns_resolve_hostname_rrtype_callback and see if it works. I doubt it's a bug in the lib.

**Comment by Kio-td** [comment]
> 
> 
> Try to just use https://nodejs.org/api/dns.html#dns_dns_resolve_hostname_rrtype_callback and see if it works. I doubt it's a bug in the lib.

I'm sorry, I'm a little confused on what you're asking me to do here.
I tried to use Firefox's websocket connector, if this helps - 
var s = new WebSocket("wss://direct.loi.nayami.party:2096/anon");

**Comment by lpinca** [comment]
My suggestion is to use the dns module directly to see if the address is correctly resolved.

**Comment by Kio-td** [comment]
Well again, IPinca, as I said before, I was able to connect to a minihttp server I setup in place of the original host and port. Besides an exception for an SSC, it let me see the test content I put on there.

**Comment by lpinca** [comment]
If the problem is the self-signed certificate you can set the `rejectUnauthorized` option to `false`;

```js
const WebSocket = require('ws');

const ws = new WebSocket('wss://direct.loi.nayami.party:2096/anon', {
  rejectUnauthorized: false
});

ws.on('open', () => {
  console.log('It works');
});
```

**Comment by Kio-td** [comment]
Sorry, thats not it either. I have a valid SSL certificate for my domain, I just had to scratch up something quickly because I was too lazy to actually attempt linking my cert.

**Comment by lpinca** [comment]
Sorry but this is still super vague.

> I can connect to the domain and port using a test server.
I cannot connect to the server through the domain.

In the first sentence you say that connecting to a test server using the hostname and port works, in the second you say that using the same hostname to connect to another server on another port? does not work.

There are so many variables here that I don't know where to start.

**Comment by Kio-td** [comment]
This is all that I know.
When I use WS, I'm unable to connect using the domain, but if I use a regular http server, I can.

**Comment by lpinca** [comment]
When you use ws, does it work if you connect from a browser like you did in 
https://github.com/websockets/ws/issues/1443#issuecomment-420992540?

**Comment by Kio-td** [comment]
![image](https://user-images.githubusercontent.com/7786316/45497497-f96b8600-b745-11e8-8778-52963c9032c0.png)

**Comment by Kio-td** [comment]
I'm able to connect on the Loopback, but not from anywhere else anymore. This is an outrage. -.-

**Comment by lpinca** [comment]
FYI, `wss://loi.nayami.party:2096/anon` works on my side while `wss://direct.loi.nayami.party:2096/anon` errors due to ssc.

**Comment by Kio-td** [comment]
I'm so confused. What're you using?

**Comment by lpinca** [comment]
Tested on Chrome 68 and Safari 11.

**Comment by Kio-td** [comment]
Mind lending me your code?

**Comment by lpinca** [comment]
```js
var ws = new WebSocket('wss://loi.nayami.party:2096/anon');

ws.onopen = function () {
  console.log('It works');
}
```

**Comment by Kio-td** [comment]
![image](https://user-images.githubusercontent.com/7786316/45500095-d643d500-b74b-11e8-9ec4-f988f8c7f76a.png)

**Comment by Kio-td** [comment]
![image](https://user-images.githubusercontent.com/7786316/45500125-ec519580-b74b-11e8-82ce-dc0239b0c1df.png)

**Comment by lpinca** [comment]
![screen shot 2018-09-13 at 17 55 21](https://user-images.githubusercontent.com/1443911/45500189-613dc300-b77e-11e8-8fba-8cc20544cc35.png)

**Comment by lpinca** [comment]
![screen shot 2018-09-13 at 18 00 45](https://user-images.githubusercontent.com/1443911/45500459-fd67ca00-b77e-11e8-9f52-4d7de5e31785.png)

**Comment by Kio-td** [comment]
I just get resets now- nothing else. My friend reports this aswell- getting no response except for an Connection Reset, and they're over the pacific.

**Comment by lpinca** [comment]
No clue, I'm Italy.

**Comment by Kio-td** [comment]
I tried flushing my DNS Cache, and tried changing ports (to 2053) - but still I get a connection reset.

**Comment by Kio-td** [comment]
That was really odd and uncomfortable. After a travel home, one of the domains work. ^^

**Comment by lunascsant** [comment]
> That was really odd and uncomfortable. After a travel home, one of the domains work. ^^

I am with the same issue, there is nothing that you did to one of the domains work? I really need this.
