### ISSUE TITLE
ws.close() or ws.terminate() doesn't remove socket object from wss.

### ISSUE THREAD

**Issue by koushikreddyu** [websockets/ws#1444]
I am using node `ws `library for some TCP communication with my node server.

when new connection establishes `wss `stores it. But my requirement is at some point I want to close the connection. I tried with both `ws.close` and `ws.terminate`. Both closes the connection and changes the readystate to closed. But `wss` still has client socket details. when same socket is connected again `wss` will have duplicate sockets, which makes my single client receive same message two times.

Below is my code

```
const WebSocket = require('ws');

const wss = new WebSocket.Server({ port: 3333 });

wss.on('connection', function connection(ws) {
        ws.on('message', function incoming(message) {
            console.log(message);
        });
});

wss.clients.forEach(function each(client) {
        client.send(JSON.stringify("some message here"), () => {
            console.log("message sent successfully");
        });
})

wss.clients.forEach(function each(client) {
        if (client.readyState === WebSocket.OPEN) {
            client.close();
        }
});
```
How do I remove socket from wss.clients. Thanks in advance

**Comment by lpinca** [comment]
Clients are removed from the `clients` set as soon as the `'close'` event is emitted on the `WebSocket` instance.
