### ISSUE TITLE
Post data when creating new ws client

### ISSUE THREAD

**Issue by rptl** [websockets/ws#1445]
Is there a way to post data when creating a new wsclient object ?

The reason I am asking is because websockets server upgrades the connection to WebSocket ONLY after post correct data.

**Comment by lpinca** [comment]
The spec says that no data should be exchanged until the handshake is complete. There is not way to send data from the ws client before the `'open'` event is emitted.

You can use a query string though for tokens, API keys, etc.

**Comment by rptl** [comment]
Thanks for your prompt reply. 

Do you see any solution using 'websockets/ws' to handle websocket connection based in the below scenario?
  
Example of post data
```
POST /triggerurl HTTP/1.1
Content-Type: application/json
Content-Length: 12345

{
 "data1": false,
 "data2: true
}

```
Which responds and starts to stream data:
```
HTTP/1.1 200 OK
Content-Type: application/raw-stream


<<DATA STREAMING>>

```

**Comment by lpinca** [comment]
I'd use a query string.

```js
const params = new URLSearchParams({ data1: false, data2: true });
const ws = new WebSocket(`wss://example.com?${params}`);
```

Then check the params server-side during the handshake and eventually start streaming the data.

**Comment by lpinca** [comment]
No, you only have this event on the client: https://github.com/websockets/ws/blob/master/doc/ws.md#event-upgrade.

**Comment by rptl** [comment]
Thanks. Just for the records, I see ws is initiated with GET method only. Some REST API doesn't accept GET to instantiate websockets. (ie. docker exec method)

**Comment by lpinca** [comment]
It must be a GET see https://tools.ietf.org/html/rfc6455#section-4.1

> The requirements for this handshake are as
   follows.
>
>  1.   The handshake MUST be a valid HTTP request as specified by
        [RFC2616].
>
>   2.   The method of the request MUST be GET, and the HTTP version MUST
        be at least 1.1.

**Comment by rptl** [comment]
Oh oh. The issue is with Docker API then. That explain why 'attach' method work and both are pretty much the same. Anyway, thanks for all you help. I really appreciated it.

**Comment by lpinca** [comment]
Closing as this is not an issue in the lib.
