### ISSUE TITLE
Should it be possible to use ws in an Electron renderer process?

### ISSUE THREAD

**Issue by flp** [websockets/ws#1459]
- [X] I've searched for any related issues and avoided creating a duplicate issue.

#### Description

I would like to use the client websocket implementation from `ws` in an Electron app. The [Electron architecture](https://electronjs.org/docs/tutorial/application-architecture) uses two types of processes, main and renderer. Renderer processes launch browser windows. I can use `ws` in the main process, but when I try to use ws in a renderer process, ws loads `browser.js` from its `package.json` which throws an error: `Error(ws does not work in the browser...)`.

Electron renderer processes have full access to Node APIs, so maybe it should be possible to use `ws` in a renderer process even though it is also a browser environment?

#### Reproducible in:

version: 6.1.0
Node.js version(s): 8.10.0
OS version(s): OS X 10.13.6

**Comment by lpinca** [comment]
> Electron renderer processes have full access to Node APIs, so maybe it should be possible to use ws in a renderer process even though it is also a browser environment?

Yes, probably. You can try to use `ws@5` or make your bundler ignore the browser filed.
I would use the implementation that ships with the browser window though.

**Comment by flp** [comment]
I was able to bypass the browser field with my bundler, thanks for the the suggestion.
>I would use the implementation that ships with the browser window though.

Why do you say that? I want to use the `ws` client because it exposes the http headers in the upgrade request and response and allows for sending arbitrary headers. The browser WebSocket client mostly obscures the websocket handshake.

**Comment by lpinca** [comment]
Well, I guess it depends on the use case. If you need custom headers or features not supported by the browser interface like ping messages or fragmented messages, then yes it makes sense. In other cases, it's just an additional dependency for something that is already available natively. It will also make your bundle bigger but I guess this is not a problem for Electron apps.

**Comment by flp** [comment]
Ok, thanks for explaining! Configuring the bundler to bypass the browser field works, so I'm closing this issue

**Comment by JuniorNunes7** [comment]
@flp How did you bypass the browser field? I have the same problem.

**Comment by yonatanMedan** [comment]
using 
```javascript
const WebSocket = window.require('ws');
```
instead of
```javascript
const WebSocket = require('ws');
```
solved it for me
