### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by world70104** [websockets/ws#1461]
npm install --save ws

When install, show next error.

npm ERR! code ENOSELF
npm ERR! Refusing to install package with name "ws" under a package
npm ERR! also called "ws". Did you name your project the same
npm ERR! as the dependency you're installing?
npm ERR! 
npm ERR! For more information, see:
npm ERR!     <https://docs.npmjs.com/cli/install#limitations-of-npms-install-algorithm>

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/master/.npm/_logs/2018-10-18T06_50_28_132Z-debug.log

What reason?

Regards

**Comment by lpinca** [comment]
You get the reason in the error message.

> Refusing to install package with name "ws" under a package

See https://github.com/npm/npm/issues/12884#issuecomment-222319087

**Comment by world70104** [comment]
I am node beginer.
I want to know ws server execute detail

Regards.

**Comment by world70104** [comment]
Ok

Thanks
