### ISSUE TITLE
Losing connection without knowing

### ISSUE THREAD

**Issue by manix** [websockets/ws#1467]
I believe this is not an issue with the library itself but with how TCP works, however I decided to share with you the trouble we went through along with a suggestion on how to supposedly improve the library such that this problem will be avoided for other unfortunate users who might be faced with it.

**The problem**: A successful connection between the client and server (both utilizing this library) is established. Then under some specific circumstances the client loses internet connection for a brief time (1s) and then reconnects, this could happen for example when there are 2 APs in range and the one the client is connected to dies, then the client connects to the other one immediately but there are other cases as well. The result is a broken TCP connection which the server detects after a short period when the heartbeat example is implemented and cleans the connection from its pool. The client though has no idea that it has no connection to the server and what really surprised me was that `client.readyState` remained `1`. We had implemented other functionalities to monitor network connectivity like doing a `dns.lookup` on an interval, which also failed to detect this because the internet connection was restored almost immediately after it was lost. It was sure a really tricky problem but we handled it and the solution was very simple.

**The solution**: We had to simply ping the server from the clients and whenever a pong was not received we terminate the connection, exactly like it was shown in the server example.

**The suggestion**: What I suggest is to instruct people to perform the heartbeat principle on both ends instead of just on the server. This could be easily implemented without much changes and without an increase in the traffic. The algorithm is as follows:

- Clients `.ping()` the server on a `X`s interval and set heartbeat to `false`. If heartbeat is already false then `.terminate()`
- Clients listen for `pong` events and set their heartbeat to `true`.
- Server listens for `ping` events and sets a timestamp on the connection.
- Server checks all connections on an interval (supposedly greater than `X`s) and closes those whose timestamp is less than X subtracted from the current timestamp.

I hope it is okay I didn't use the suggested issue format.

As to why this was such a huge problem for us is because our clients are expected to automatically reconnect whenever there was a problem. This scenario kept our clients from reconnecting and they remained offline forever. Perhaps its highly dependent on the application but people could benefit from this experience.

**Comment by manix** [comment]
Or that, shame we didn't come up with this straight away but to be fair we were quite exhausted at the end of the day. Thank you!

**Comment by lpinca** [comment]
Closing this, PRs to improve the documentation are welcome. Feel free to open one.
Thank you.
