### ISSUE TITLE
Typescript Example

### ISSUE THREAD

**Issue by xinthose** [websockets/ws#1470]
Hello.  Do you have any examples using Typescript and Angular 6?  I found your typescript [readme](https://github.com/websockets/ws/blob/master/doc/ws.md), but I would like to see example code.  Here is my attempt:

- `npm install --save ws @types/ws`
- `ng generate service websocket`

**websocket.service.ts**
```
import { Injectable } from '@angular/core';

import * as WebSocket from "ws"

@Injectable({
  providedIn: 'root'
})
export class WebsocketService {

  constructor() { 
    const wss = new WebSocket.Server({ port: 8080 });
    
    wss.on('connection', function connection(ws, req) {
    
      ws.on('close', function close() {
        console.log('disconnected');
      });
    
      ws.on('message', function incoming(message) {
        ws.send('something');
    
        console.log("Send Changed Message");
      });
    });
  }
}
```
When the service constructor is called, I get this error:

> ERROR Error: Uncaught (in promise): TypeError: ws__WEBPACK_IMPORTED_MODULE_1__.Server is not a constructor

**Comment by xinthose** [comment]
Step 1: npm install --save ws @types/ws
Step 2: import
import { WebSocket } from "ws"  // member not found
import { EventEmitter } from "ws"   // this works
Step 3: ?

**Comment by xinthose** [comment]
OK.  Thank you.

**Comment by jdspugh** [comment]
I had the same error and fixed it by using

`import WebSocket from 'ws'`
