### ISSUE TITLE
Subscribing to channel

### ISSUE THREAD

**Issue by danielbronder** [websockets/ws#1475]
This is not necessarily more of a question than a bug report. I've been playing around with ws today and I found it very easy to use. I am able to make a connection, but in my case I need to subscribe to a specific channel. 

I've made a successful to connection to the server and I need to subscribe to let say a channel called people. How can I do this in ws? I am only able to use the client, because I don't have access to the server itself. I've tried some things, but I couldn't get it to work

**Comment by lpinca** [comment]
Sorry but this issue tracker is for only for bugs an feature requests. Use another channel for this kind of questions.
