### ISSUE TITLE
receiver enforces fin while trying to process a ping

### ISSUE THREAD

**Issue by lada77** [websockets/ws#1476]
version: 5.1.1
node: 9.11.2
debian: 8.11

I believe this code in the receiver.js file is incorrect (around line 194)

    } else if (this._opcode > 0x07 && this._opcode < 0x0b) {
     if (!this._fin) {
        this._loop = false;
        return error(RangeError, 'FIN must be set', true, 1002);
      }

When a ping opcode is received (0x09), the logic checks the _fin state to report an error.  However based on the RFC : https://tools.ietf.org/html/rfc6455#page-37 a ping may come in whether or not the frame is closed.  

I was getting range error with FIN must be set to true while acting as a server to a c++ client that is using websockets through a PoCo library.  I commented out the check for this._fin and my server is behaving correctly now.

**Comment by lpinca** [comment]
The linked check is there to ensure that the ping frame has the FIN bit set. All control frames must not be fragmented.
