### ISSUE TITLE
Manually reproduce and test ping, pong, heartbeat, keepalive 

### ISSUE THREAD

**Issue by goktugyil** [websockets/ws#1477]
- [x] I've searched for any related issues and avoided creating a duplicate
      issue.

#### Description

How can we reproduce the edge disconnect cases in our local environment to see how websockets at our localhost behaves? 

The problem I'm having is, I get crashes at the live server after a certain amount of hours, because users keep losing connections in weird ways. But I can't reproduce them in my local machine.

**Comment by lpinca** [comment]
Closing this, discussion can continue if needed.
