### ISSUE TITLE
Multiple path / multiple ws server

### ISSUE THREAD

**Issue by imrefazekas** [websockets/ws#1478]
I would like to have 2 paths for a 'normal' RPC and a JSONRPC2.0 interfaces.

I can create a server around a node server easily. Works.
I can not give multiple paths to the ws server at all and the moment I create 2 servers around a node server with different paths I receive this:

```
     Uncaught RangeError: Invalid WebSocket frame: RSV1 must be clear
```

It seems it is not possible to have multiple paths at all. Does anyone any idea how to solve this?
With socket.io I can use the '.of' function to create different paths with different handlers associated with...

**Comment by lpinca** [comment]
See https://github.com/websockets/ws/pull/885#issue-92503473 If I understand correctly it should address your issue.
