### ISSUE TITLE
Fails on case-sensitive file systems

### ISSUE THREAD

**Issue by tandrewnichols** [websockets/ws#1479]
- [x] I've searched for any related issues and avoided creating a duplicate
      issue.

#### Description

I'm using version 6.1.2 of this module and getting `Cannot find module "./lib/websocket"` on travis, which is Linux. Linux is a case-sensitive file system, and when I explore this module on my system (e.g. `ls node_modules/ws/lib`) I see that the filename is actually `WebSocket.js` which is why it's not found. I'm actually on a Mac, so it works fine for me, but it fails my travis build. The thing that's weird is that when I look at the files here on Github, it's all lowercased in the latest version (which IS 6.1.2). I have no explanation for that but . . . halp? I'm specifically using this via `testem@2.14.0` which uses `socket.io@2.2.0` which uses `engine.io@3.3.2` which uses `ws@6.1.2`.

#### Reproducible in:

- version: 6.1.2
- Node.js version(s): 9.11.2
- OS version(s): Linux or any case-sensitive file system (maybe?).

#### Steps to reproduce:

1. npm install -g testem

2. testem

3. Maybe it will fail? Hard for me to reproduce cause I'm on a case-insensitive system.

#### Expected result:

Testem should start (or more generically, things should work fine.)

#### Actual result:

Error: Cannot find module "./lib/websocket"

#### Attachments:

Travis log:

<img width="440" alt="screen shot 16" src="https://user-images.githubusercontent.com/2755760/50016023-06428480-ff96-11e8-9769-31fb127f4d85.png">

Terminal investigation:

![screen shot 17](https://user-images.githubusercontent.com/2755760/50016051-15293700-ff96-11e8-81eb-35a181f96a21.png)

**Comment by tandrewnichols** [comment]
I should note that I installed this on Mac and committed it. Doesn't seem like that should matter, but I know there are system targeted binaries sometimes.

**Comment by tandrewnichols** [comment]
Follow up: @johndorn tried reproducing this on Linux, but everything was lowercase. So . . . it seems to be a platform issue. But I don't really understand why.

**Comment by lpinca** [comment]
I'm not sure why this issue was opened here. Internal modules name are in lowercase since this commit https://github.com/websockets/ws/commit/3936f3a8a8b3e37e8d43ebcb9558d226d44fb964 included in version 4.0.0

**Comment by tandrewnichols** [comment]
`npm cache clean` fixed this.


...and I just saw your response. So no doubt this was cached on my system prior to that commit. Interesting issue, but not really anything you could do about it on your end other than _maybe_ add a note in the readme for people that happens to, but I don't know how useful that would be. Thanks.

**Comment by lpinca** [comment]
Ok, closing then.
