### ISSUE TITLE
WebSocket.Server completely connected event

### ISSUE THREAD

**Issue by Symous** [websockets/ws#1483]
- [x] I've searched for any related issues and avoided creating a duplicate
      issue.

#### Description

If we use 
```js
new WebSocket.Server({ port: 1112 }).on('connection', (ws, req) => {
   console.log(ws.readyState);   //may be 0,1,3? 
}
```
the readyState of ws may not be connected(1). Is there any way we can monitor when the connection is completely established?Thanks.
#### Reproducible in:

- version: 6.1.2
- Node.js version(s): 10.13.0
- OS version(s): Windows 10

#### Steps to reproduce:
It will be excellent if there is a "connected" event.
1.  
```js
new WebSocket.Server({ port: 1112 }).on('connected', (ws, req) => {
   console.log(ws.readyState); //always be 1 
}
```

**Comment by lpinca** [comment]
When the `'connection'` event is emitted the `readyState` is always `1` (`OPEN`).

**Comment by lpinca** [comment]
I can't see how this can happens. This is called

https://github.com/websockets/ws/blob/3d6692ac1097d5f85ccf36001434b005f6d0552d/lib/websocket-server.js#L305

on the same tick where the `'connection'` event is emitted and it sets the `readyState` to `OPEN`

https://github.com/websockets/ws/blob/3d6692ac1097d5f85ccf36001434b005f6d0552d/lib/websocket.js#L158

**Comment by lpinca** [comment]
In your last example you are reading the `readyState` when a message is received. In that case the `readyState` can be indeed no longer `OPEN` but that is expected.

**Comment by lpinca** [comment]
If you are using permessage-deflate, it's possible that the underlying `net.Socket` is closed while data is being decompressed for example.

**Comment by lpinca** [comment]
Are you calling `close()`? For example

```js
ws.on('message', fn);
ws.close();
```

`ws.close()` sets the `readyState` to `CLOSING` synchronously so if data arrives while you are sending the close frame you might find the `readyState` to `CLOSING` when the `'message'` event is emitted.

Otherwise add listeners for the `'error'`, `'end'`, and `'close'` events on the `net.Socket` to see if any of these is emitted before `'message'`. These all set the `readyState` to `CLOSING`.

```
ws.on('message', fn);
ws._socket.on('error', fn);
ws._socket.on('end', fn);
ws._socket.on('close', fn);
```

**Comment by lpinca** [comment]
Closing, discussion can continue in the closed thread.
