### ISSUE TITLE
clientTracking not working

### ISSUE THREAD

**Issue by lefebvresam** [websockets/ws#1485]
- [ ] I've searched for any related issues and avoided creating a duplicate
      issue.

#### Description

I use ws with express-ws in combination of inversify-express-utils and use this as config:

```typescript
  import { Container } from "inversify";
  import { InversifyExpressServer } from "inversify-express-utils";
  import expressWs from "express-ws";
  ...
  const container = new Container();
  await container.loadAsync(bindings);
  const server = new InversifyExpressServer(container);

  server.setConfig(a => {
    a.use(bodyParser.json());
    a.use(bodyParser.urlencoded({ extended: true }));
    expressWs(a, undefined, {
      wsOptions: {
        clientTracking: true,
        verifyClient: (info: any) => {
          //console.log(info);
          const req: http.IncomingMessage = info.req;
          return (
            req.url === websocketpath1 ||
            req.url === websocketpath2 ||
            req.url === websocketpath3
          );
        }
      }
    });
  });
```

If I try to print the client list it's always undefined and not printed, even if two or more websocket clients are connected:

```typescript
  const app = server.build();

  const serverinst = app.listen(port, ipaddr, () => {
    console.log("Server running at http://%s:%i", ipaddr, port);
  });

  serverinst.on(
    "connection",
    (socket: WebSocket, req: http.IncomingMessage) => {
      //console.log(socket);
      console.log("%j", serverinst.address());
      if (serverinst.clients) {
        console.log("client list found");
        for (const element of serverinst.clients) {
          console.log("%j", element);
        }
      }
    }
  ); 
```

#### Reproducible in:

- version:
- Node.js version(s): 10.14.2
- OS version(s): Windows 10

#### Steps to reproduce:

1. Setup a project with above config

#### Expected result:

I expect a list printed.

#### Actual result:

Undefined

#### Attachments:

NA

**Comment by lpinca** [comment]
What is `expressWs()`?

**Comment by lefebvresam** [comment]
import { Container } from "inversify";
import { InversifyExpressServer } from "inversify-express-utils";
import expressWs from "express-ws";

**Comment by lpinca** [comment]
Report the issue on https://github.com/HenningM/express-ws not here.

**Comment by lpinca** [comment]
See https://github.com/HenningM/express-ws#wsinstancegetwss

> You can use `wsInstance.getWss().clients` to obtain a list of all the connected WebSocket clients for this server.

**Comment by lefebvresam** [comment]
if (serverinst.getWss().clients) {
                     ^
TypeError: serverinst.getWss is not a function

**Comment by lpinca** [comment]
I don't know, sorry, but it's not an issue in ws. express-ws is a different project.
