### ISSUE TITLE
connection refused 

### ISSUE THREAD

**Issue by circuit-monkey** [websockets/ws#1489]
I'm trying to create a socket connection with the example code in the following manner:

```const WebSocket = require('ws');
const ws = new WebSocket('ws://192.168.1.7:8080/api/chatPoints');

ws.on('open', function open() {
  ws.send('something');
});

ws.on('message', function incoming(data) {
  console.log(data);
});

process.on('uncaughtException', function (err) {
  console.log(err);
}); 
```

I'm running Node v8.11.2 with WS 6.1.2

The error that I am getting is:

> { Error: connect ECONNREFUSED 192.168.1.7:8080
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '192.168.1.7',
  port: 8080 }
TypeError: Cannot read property 'aborted' of null
    at ClientRequest.req.on (/Users/mac/Desktop/projects/chatpoint/chatpoint_backend/node_modules/ws/lib/websocket.js:547:19)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketCloseListener (_http_client.js:363:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at TCP._handle.close [as _onclose] (net.js:557:12)

**Comment by lpinca** [comment]
This is probably an issue in your network and not a ws issue. Try to establish a TCP connection to that address and is if it works:

```
nc -v 192.168.1.7 8080
```

**Comment by circuit-monkey** [comment]
I tried that and got 

> Connection to 192.168.1.7 port 8080 [tcp/http-alt] succeeded!

**Comment by lpinca** [comment]
Try with:

```js
const { get } = require('http');

const request = get({ host: '192.168.1.7', port: 8080 }, function(response) {
  response.setEncoding('utf8');
  response.on('data', process.stdout.write.bind(process.stdout));
});

request.on('error', console.error);
```

**Comment by circuit-monkey** [comment]
the output that I am getting now is:

> { Error: connect ECONNREFUSED 192.168.1.7:8080
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '192.168.1.7',
  port: 8080 }

**Comment by circuit-monkey** [comment]
Sorry for the false alarm and thanks a lot for your help. 

Any clue as to how it could be remedied?

**Comment by lpinca** [comment]
I'm not sure. Try to use the latest Node.js 8.x version and see if the issue persist.
Also try to see if it works with `curl`:

```
curl http://192.168.1.7:8080/
```

If it does and does and doesn't work with Node.js check the headers.
If there is a firewall try to disable it.

Hard to know what is wrong without having access to the environment.

**Comment by circuit-monkey** [comment]
I realized that I should try doing: 

`const WebSocket = require('ws')
const wss = new WebSocket.Server({ port: 8080 })`

before the code that you gave me. 

It is no longer creating the same error.

Does it still look like it is a problem with node/network environment?

**Comment by lpinca** [comment]
Of course, there must be a server listening on `192.168.1.7` on port `8080` and yes if you didn't run it it was likely the cause of the error.
