### ISSUE TITLE
Broadcast issue

### ISSUE THREAD

**Issue by simplo** [websockets/ws#1495]
- [X] I've searched for any related issues and avoided creating a duplicate
      issue.

#### Description

Trying to broadcast to all the clients connected, but each client just receives his own messages.

#### Reproducible in:

- version: 6.1.3
- Node.js version(s): 10-15-0
- OS version(s): Windows 7

#### Steps to reproduce:

1. run this code:
const WebSocket = require('ws');

const wss = new WebSocket.Server({ port: 3333 });

wss.broadcast = function broadcast(data) {
            try {
                console.log('length = ' + wss.clients.length);
                wss.clients.forEach(function each(client) {
                    console.log('readyState = ' + client.readyState);
                    if (client.readyState === WebSocket.OPEN) {
                        client.send(data);
                    }
                });
            } catch (e) {
                console.log(e);
            }
            
        };

wss.on('connection', function connection(ws) {
  ws.on('message', function incoming(data) {
	console.log('received: %s', data);
   
	wss.broadcast(data);
    
    });
  });
});

2.
Connect two clients (using websockets from different devices and different applications connecting over Internet)

3.
Send messages from each client.

#### Expected result:

All clients receive all messages.

#### Actual result:

Each client receives only the messages it sent.

**Comment by lpinca** [comment]
Please format your code correctly. It's unreadable.

**Comment by simplo** [comment]
Sorry, I will attach it.
[broadcast.zip](https://github.com/websockets/ws/files/2795622/broadcast.zip)

**Comment by stas-ut21** [comment]
Your example works correctly.

Read more in the documentation:
https://github.com/websockets/ws#server-broadcast

About the number of clients:
```js
console.log('length = ' + wss.clients.length);
```
Always will write: `length = undefined` .

The wss object does not have a length property, because it is a [`Set`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set) object(it would be nice to mention this in the documentation).

**Comment by lpinca** [comment]
@stas-ut21 thanks for looking into this. It is already documented, see https://github.com/websockets/ws/blob/master/doc/ws.md#serverclients.

**Comment by simplo** [comment]
> Your example works correctly.
I knew something was wrong with the "length", but it doesn't matter.
My clients are just receiving their own messages, and I don't know why. 
I'm using two different clients: one running in TouchDesigner and one in Unity...


> 
> Read more in the documentation:
> https://github.com/websockets/ws#server-broadcast
> 
> About the number of clients:
> 
> ```js
> console.log('length = ' + wss.clients.length);
> ```
> 
> Always will write: `length = undefined` .
> 
> The wss object does not have a length property, because it is a [`Set`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set) object(it would be nice to mention this in the documentation).

**Comment by rgawenda** [comment]
> I knew something was wrong with the "length", but it doesn't matter.

Anyway, just _use wss.clients.size_

Change

    wss.clients.forEach(function each(client) {

to

    for (const client of wss.clients) {

> My clients are just receiving their own messages, and I don't know why.

Your server's code has a readyState console logging, how many times is that fired per message, while your two clients are connected?
Insert another console.log before calling send()

**Comment by stas-ut21** [comment]
> I knew something was wrong with the "length", but it doesn't matter.
> My clients are just receiving their own messages, and I don't know why.
> I'm using two different clients: one running in TouchDesigner and one in Unity...

If possible, write that you will give it: 

```js
const WebSocket = require('ws');

const wss = new WebSocket.Server({ port: 3333 });

wss.broadcast = function broadcast(data) {
    try {
        console.log('length = ' + wss.clients.size);
        console.log(wss.clients);
        wss.clients.forEach(function each(client) {
            console.log('readyState = ' + client.readyState);
            if (client.readyState === WebSocket.OPEN) {
                client.send(data);
            }
        });
    } catch (e) {
        console.log(e);
    }

};

wss.on('connection', function connection(ws) {
    ws.on('message', function incoming(data) {
        console.log('received: %s', data);
        wss.broadcast(data);
    });
});

```
This is your code, except `console.log(wss.clients);`
