### ISSUE TITLE
Disabling conversion to Buffer

### ISSUE THREAD

**Issue by SuperOP535** [websockets/ws#1498]
Messages received from clients (on a server) are automatically converted to Node.js buffers (by using Buffer.from) however for me this is bad and I have to convert it back to ArrayBuffer which is inefficient. I am extremely sorry if I have missed something but binaryType does not work on server, only on client.
Please add an option convertToBuffer so I can disable this.

**Comment by lpinca** [comment]
`binaryType` works everywhere.

```js
const assert = require('assert');
const WebSocket = require('ws');

const wss = new WebSocket.Server({ port: 8080 }, function() {
  const ws = new WebSocket('ws://localhost:8080');

  ws.on('open', function() {
    ws.send(Buffer.alloc(5, 'a'));
  });
});

wss.on('connection', function(ws) {
  ws.binaryType = 'arraybuffer';
  ws.on('message', function(msg) {
    assert(msg instanceof ArrayBuffer);
    console.log(msg);

    wss.close();
  });
});
```

**Comment by SuperOP535** [comment]
oh I did not realize that I could set binaryType on the ws client... I did on the server instead lol sorry
