### ISSUE TITLE
on('data') event not available

### ISSUE THREAD

**Issue by dsentker** [websockets/ws#1503]
#### Description
On a default node server (e.g. ```net.createServer();``` ) i can use server.on('data'). This event is missing or not documented how to add an event listener to it.

#### Reproducible in:

- version: 6.1.3
- Node.js version(s): 10
- OS version(s): Win10

#### Steps to reproduce:

1. Use the example setup (section [Simple Server](https://www.npmjs.com/package/ws#simple-server))

2. Try to add ws.on('data', data => { console.log(data) })

3. Write to the socket (e.g. via PHP)

4. Nothing happens

**Comment by lpinca** [comment]
There is no `'data'` event on the WebSocket object. See https://github.com/websockets/ws/blob/master/doc/ws.md#class-websocket for the list of events.
