### ISSUE TITLE
Sending binary data syncronously

### ISSUE THREAD

**Issue by edreal** [websockets/ws#1504]
I am using shared buffer in node to send binary data to clients. Everytime I send data, I will overwrite old data in buffer and send that. In secure websocket connection, looks like the buffer gets sometimes overwritten by data which is supposed to be sent to the next client. (Updates to clients are sent in loop). Without SSL, everything works fine.
Is the ws.send() function asyncronous in ws:// or wss://?
If its not syncronous, could it be changed to work syncronously or would it cause problems?

Thanks guys

**Comment by lpinca** [comment]
It's async for both. Internally [`socket.write()`](https://nodejs.org/api/net.html#net_socket_write_data_encoding_callback) is used. See https://github.com/nodejs/node/blob/048b977d8e5cede2259df69fc7c0bbfedd84100d/lib/_stream_writable.js#L273-L303 and https://github.com/nodejs/node/blob/048b977d8e5cede2259df69fc7c0bbfedd84100d/lib/net.js#L707-L709.

There is no easy way to make it sync unless you want to mess with Node.js internals.

**Comment by edreal** [comment]
Okay! Thank you :)
