### ISSUE TITLE
ws 1.1.6 disappeared from npm registry

### ISSUE THREAD

**Issue by fletling** [websockets/ws#1507]
- [x] I've searched for any related issues and avoided creating a duplicate
      issue.

#### Description

Version 1.1.6 disappeared from npm registry

#### Reproducible in:

- version: n/a
- Node.js version(s): n/a
- OS version(s): n/a

Relevant information may be that this behaviour is observed both locally as well as on our CI (CircleCI and Appcenter) which rules out potential local issues. 

#### Steps to reproduce:

1. Run `curl https://registry.yarnpkg.com/ws/-/ws-1.1.6.tgz`

#### Expected result:

The package is downloaded

#### Actual result:

The result is `{"error":"Not found"}` 

Please let me know if this was a conscious decision to remove it but I can hardly imagine that's the case. Unfortunately this missing package breaks our deployment at the moment.

**Comment by lpinca** [comment]
It never existed. Latest 1.x release was [1.1.5](https://github.com/websockets/ws/releases/tag/1.1.5).

**Comment by fletling** [comment]
lol, that's a great piece of information that explains a lot. Thanks @lpinca 

Then I really wonder how it ended up in our yarn.lock file but that's likely some other issue unrelated to here.
