### ISSUE TITLE
Incorrect header response lower case

### ISSUE THREAD

**Issue by javqui** [websockets/ws#1512]
- [x] I've searched for any related issues and avoided creating a duplicate
      issue.

#### Description
according with RFC6455 the header response include fields like "Sec-WebSocket-Accept" and "Sec-WebSocket-Protocol" 
version 6.1.4 return the name of the previous fields (and probably others) with incorrect capitals 
Connection: Upgrade\r\nUpgrade: websocket\r\nSec-Websocket-Accept: ................\r\nSec-Websocket-Protocol:.......

This little mistake of "s" instead "S" trigger many problems in small systems with limited resources (not a problem for a big PC with big resources) running websockets libraries. 

https://tools.ietf.org/html/rfc6455#section-11.3.3 

#### Reproducible in:

- version: 6.1.4
- Node.js version(s): 10.5.
- OS version(s): all.

#### Steps to reproduce:

1. Connect to websocket using standard examples

2. Header received include Websocket, instead WebSocket. Google chrome accept it without any issue. Embedded Libraries reject connection after compare the string: strstr(buffer,"Sec-WebSocket-Accept") return a null pointer
3. HTTP/1.1 101 Switching Protocols\r\nConnection: Upgrade\r\nUpgrade: websocket\r\nSec-Websocket-Accept: HGDpIoblXGX33qAV6INFxEAgsbI=\r\nSec-Websocket-Protocol: ocpp2.0\r\nVia: 1.1 vegur\r\n\r\nqEe5rXgSnxIe4wV7fGr8XA

#### Expected result:
 "Sec-WebSocket-Protocol:" and "Sec-WebSocket-Accept:"
#### Actual result:
"Sec-Websocket-Protocol:" and "Sec-Websocket-Accept:"

**Comment by lpinca** [comment]
We can change this but it isn't a problem in this lib. From https://tools.ietf.org/html/rfc7230#section-3.2

> Each header field consists of a case-insensitive field name followed
>  by a colon (":"), optional leading whitespace, the field value, and
>  optional trailing whitespace.

**Comment by lpinca** [comment]
By the way I can't reproduce.

- https://github.com/websockets/ws/blob/6.1.4/lib/websocket-server.js#L264
- https://github.com/websockets/ws/blob/6.1.4/lib/websocket-server.js#L283

```
$ cat index.js 
const WebSocket = require('ws');

const wss = new WebSocket.Server({ port: 8080 });
$ node index.js
```

```
$ nc localhost 8080
GET / HTTP/1.1
Host: localhost
Upgrade: websocket
Connection: Upgrade
Sec-WebSocket-Key: rfeGe1izPRq2JyonWunAQw==
Sec-WebSocket-Version: 13

HTTP/1.1 101 Switching Protocols
Upgrade: websocket
Connection: Upgrade
Sec-WebSocket-Accept: prdBmM6el7NzNgJBcdmWum5mTZc=

^C
```

**Comment by javqui** [comment]
> By the way I can't reproduce.
> 
> * https://github.com/websockets/ws/blob/6.1.4/lib/websocket-server.js#L264
> * https://github.com/websockets/ws/blob/6.1.4/lib/websocket-server.js#L283
> 
> ```
> $ cat index.js 
> const WebSocket = require('ws');
> 
> const wss = new WebSocket.Server({ port: 8080 });
> $ node index.js
> ```
> ```
> $ nc localhost 8080
> GET / HTTP/1.1
> Host: localhost
> Upgrade: websocket
> Connection: Upgrade
> Sec-WebSocket-Key: rfeGe1izPRq2JyonWunAQw==
> Sec-WebSocket-Version: 13
> 
> HTTP/1.1 101 Switching Protocols
> Upgrade: websocket
> Connection: Upgrade
> Sec-WebSocket-Accept: prdBmM6el7NzNgJBcdmWum5mTZc=
> 
> ^C
> ```

Very interesting test this morning.
I have a simple node app to forward websocket messages. If I run the app locally (node sever.js), I got the right message ("Sec-WebSocket-Accept"). when I push the app to the Heroku server, I got the the incorrect answer ("Sec-Websocket-Accept").
I modified several debug texts to be sure that I'm using the same server.js version on both cases (locally and on Heroku). 
Additionally, was checking this morning the package.json and it shows "node": 10.15.1 and "ws": 6.1.4
Something different is doing the Heroku guys at some point.

**Comment by lpinca** [comment]
Yes, it could be a proxy that changes the case of the header field name.

**Comment by javqui** [comment]
Could be. Thanks for the quick response.
Just want to report one final test to validate that Heroku is not changing the version of ws.
For testing, I added at the beginning of the "server.js" file the following lines

var pjson = require('./node_modules/ws/package.json');
console.log(pjson._id);

in both cases (local and from heroku) it reports "ws@6.1.4" so looks like the issue is with some proxy at the heroku (at least, I don't have any knowledge of a proxy close to my network).
Thanks again for all your help.
