### ISSUE TITLE
Run ws server locally get close event with code 1006. 

### ISSUE THREAD

**Issue by Manjiz** [websockets/ws#1513]
- [x] I've searched for any related issues and avoided creating a duplicate
      issue.

#### Description

close event with 1006 after connection for a while.

#### Reproducible in:

- version:6.1.4
- Node.js version(s): 8.x
- OS version(s):MAC

#### Steps to reproduce:

Run ws server locally. At `lib/websocket.js`，hadError is false:

```javascript
/**
 * The listener of the `net.Socket` `'close'` event.
 *
 * @private
 */
function socketOnClose(hadError) {
  console.log(hadError)  // <-- false
  // ...
```

**Comment by lpinca** [comment]
It means that [closing handshake](https://tools.ietf.org/html/rfc6455#section-7.1.2) failed not that the [`net.Socket`](https://nodejs.org/api/net.html#net_class_net_socket) had an error.
