### ISSUE TITLE
How to extend interface WebSocket with typescript?

### ISSUE THREAD

**Issue by budarin** [websockets/ws#1517]
- [ ] I've searched for any related issues and avoided creating a duplicate
      issue.

#### Description
I try to extend an interface of a library but without success
I have posted a [question](https://stackoverflow.com/questions/54749028/how-to-extend-interface-websocket-from-ws-library) to stackoverflow but no one answered

I need to add some custom properties to WebSocket instance
Help me please describe it with typescript

#### Reproducible in:

- version: any
- Node.js version(s): any
- OS version(s): any

#### Steps to reproduce:

1. 
``` 
socket.on('connection', (ws: WebSocket, req: http.IncomingMessage) => {
    ws.online = true; // for heartbit but typescript throws a error
}
```

#### Expected result:

typescript is happy

#### Actual result:

typescript is angry

**Comment by lpinca** [comment]
I think you have to extend the existing classes

```typescript
declare class MyWebSocket extends WebSocket {
  online: boolean;
}
```

and similarly for `WebSocket.Server`. I don't think it's possible to modify existing interfaces but I'm a TypeScript noob so I may be wrong.

**Comment by budarin** [comment]
@lpinca , thanks! It helped!

**Comment by piyushkantm** [comment]
Actually it's possible in typescript and works well with other DefinatelyTyped typings also. It just doesn't work with this library..

**user.middleware.ts**
```
import { NextFunction, Request, Response } from "express";

export const userMiddleware = (req: Request, res: Response, next: NextFunction) => {
    req.userId = 1; // NO error here after using below declaration merging

    next();
};
```

**express-augmented.d.ts**
```
import express from "express";

declare module "express" {
    export interface Request {
        userId: number;
    }
}
```

See last two sections: https://www.typescriptlang.org/docs/handbook/declaration-merging.html


But when i try to do the same with this library, it shows errors. I am not 100% sure but i think it's because of all the interfaces inside namespace using the exported class(exported outside namespace)

I am sorry i don't know how DefinatelyTyped typings work exactly but Is there any specific reason why class WebSocket is declared outside namespace WebSocket ?

**Comment by DISKONEKTeD** [comment]
Leaving this here since it took too long to figure this out in typescript (i'm still relatively new to it):

All you have to do is declare this in your file:

```
interface ExtWebSocket extends WebSocket {
    isAlive: boolean;
}
```

then wherever you're defining that, for example:

```
setInterval(() => {
    wss.clients.forEach((ws: WebSocket) => {
        const extWs = ws as ExtWebSocket;

        if (!extWs.isAlive) return ws.terminate();

        extWs.isAlive = false;
        ws.ping(null, undefined);
    });
}, 10000);
```

You cannot augment it via a module, as this particular library implements using a class and not an interface. That's what causes the type errors when trying to add new fields to the websocket object. That's what I gathered after researching.

This uses type assertion: https://basarat.gitbooks.io/typescript/docs/types/type-assertion.html

**Comment by binier** [comment]
I know that this issue is closed but still want to share it here, maybe someone will find this useful, as it worked for me.

```
declare module "ws" {
  class _WS extends WebSocket { }
  export interface WebSocket extends _WS {
      online: boolean;
  }
}
```

though this will not work (since `WebSocket` here refers to the class, not the declared interface):
```
socket.on('connection', (ws: WebSocket, req: http.IncomingMessage) => {
    ws.online = true;
}
```

while these do:

1. without type definition:
```
socket.on('connection', (ws, req: http.IncomingMessage) => {
    ws.online = true;
}
```
2. with type definition (`WebSocket.WebSocket`):
```
socket.on('connection', (ws: WebSocket.WebSocket, req: http.IncomingMessage) => {
    ws.online = true;
}
```

**Comment by budarin** [comment]
@binier Thanks alot!

**Comment by yuriyyakym** [comment]
Try this:
```
import ws from 'ws';

declare module 'ws' {
  export interface WebSocket extends ws {
    online: boolean;
  }
}
```

**Comment by budarin** [comment]
@yuriyyakym thanks!

**Comment by jackpunt** [comment]
Kudos to yuriyyakym!

This is only solution I've found for accessing the method signatures of class WebSocket in VSCode.
(instead of getting namespace ws.WebSock, (or the typescriptlib browser-side WebSocket)

```
import * as ws from "ws"

declare module 'ws' {
  export interface WebSocket extends ws { }
}

```
I can now declare a ```ws: ws.WebSocket ``` and ```ws.send(...)``` shows all the right arg types!

**Comment by TheMachineHerald** [comment]
> I know that this issue is closed but still want to share it here, maybe someone will find this useful, as it worked for me.
> 
> ```
> declare module "ws" {
>   class _WS extends WebSocket { }
>   export interface WebSocket extends _WS {
>       online: boolean;
>   }
> }
> ```
> 
> though this will not work (since `WebSocket` here refers to the class, not the declared interface):
> 
> ```
> socket.on('connection', (ws: WebSocket, req: http.IncomingMessage) => {
>     ws.online = true;
> }
> ```
> 
> while these do:
> 
>     1. without type definition:
> 
> 
> ```
> socket.on('connection', (ws, req: http.IncomingMessage) => {
>     ws.online = true;
> }
> ```
> 
>     1. with type definition (`WebSocket.WebSocket`):
> 
> 
> ```
> socket.on('connection', (ws: WebSocket.WebSocket, req: http.IncomingMessage) => {
>     ws.online = true;
> }
> ```

This was very handy and a slick way of bypassing this restriction.

**Comment by theillarionov** [comment]
Ehm, i tried just:
`declare interface WebSocket {
	playerId: string
}`
in my .d.ts file and it worked. I think it works because of interface merging politics.

**Comment by dani3434** [comment]
I'm trying to access the username property but I can't, this is my code below:

const server = app.listen(4000, () => console.log("Servidor rodando"));

const wss = new ws.WebSocketServer({ server });
declare class CustomWebSocket extends WebSocket {
  userId: string;
  username: string;
}

wss.on("connection", (connection: CustomWebSocket, req) => {
  const cookies = req.headers.cookie;

  if (cookies) {
    const tokenCookieString = cookies
      .split(";")
      .find((str) => str.startsWith("token="));
    if (tokenCookieString) {
      const token = tokenCookieString.split("=")[1];
      if (token) {
        jwt.verify(token, jwtSecret as string, {}, (err, userData) => {
          if (err) throw err;
          const { userId, username } = userData as jwt.JwtPayload;
          connection.userId = userId;
          connection.username = username;
        });
      }
    }
  }

  console.log([...wss.clients].map(c => c.username)); //there is an error on this line: Property 'username' does not exist on type 'WebSocket'.ts(2339)
});

**Comment by ehaynes99** [comment]
I know this issue is old, but it keeps getting referenced, and none of the above are actually correct. Making a type like that is effectively just lying to the type system to create a type like that, as the actual type of the socket object will still be the default `WebSocket`.
```typescript
// online will be `undefined`
wss.on('connection', (ws) => console.log(ws.online.toString())
```
Take note of the type parameter for the server:
```typescript
    class Server<
        T extends typeof WebSocket.WebSocket = typeof WebSocket.WebSocket,
        U extends typeof IncomingMessage = typeof IncomingMessage,
    > extends EventEmitter {
```
It is NOT `T extends WebSocket.WebSocket`, but `T extends typeof WebSocket.WebSocket`. `typeof SomeClass` gives you the type of the class object (constructor function), not the type of an **instance** of the class. Thus, after extending the original `WebSocket` class, the generic type parameter should be `Server<typeof CustomWebSocket>`.

Also note the constructor parameter `WebSocket`. Here, you pass the custom **class**, which is then created here on connection:
https://github.com/websockets/ws/blob/a57e963f946860f6418baaa55b307bfa7d0bc143/lib/websocket-server.js#L382

Full example:
```typescript
import { Server, WebSocket } from 'ws'

export class CustomWebSocket extends WebSocket {
  userId!: string

  sendStuff() {
    this.send('stuff')
  }
}

export class CustomWebsocketServer extends Server<typeof CustomWebSocket> {
  constructor() {
    super({
      WebSocket: CustomWebSocket,
    })
  }

  socketForUser(userId: string): CustomWebSocket | undefined {
    // this.clients is of type Set<CustomWebSocket>
    for (const socket of this.clients) {
      if (socket.userId === userId) {
        return socket
      }
    }
  }
}

const wss = new CustomWebsocketServer()

wss.on('connection', (socket) => {
  // socket is of type CustomWebSocket
  socket.sendStuff()
})
```
Final note: You don't need one, but if you add a constructor to your `WebSocket` subclass, it has to be compatible with that of the original `WebSocket` class, which is techically:
```typescript
constructor(...params: ConstructorParameters<typeof WebSocket>) {}
```
However, it will only ever be called with `null`, so you may as well leave it as a no-args `constructor()`

**Comment by MykhSerhii** [comment]
I found a simple solution to this problem. I use `express-ws` as a basis.

Supporting files
---

`package.json`
```json
{
  "name": "websocket-example",
  "version": "1.0.0",
  "description": "Websocket example",
  "main": "src/index.ts",
  "scripts": {
    "dev:server": "nodemon src/index.ts"
  },
  "author": "Mykhailenko Serhii",
  "dependencies": {
    "config": "^3.3.8",
    "express": "^4.18.1",
    "express-ws": "^5.0.2",
    "uuid": "^9.0.1"
  },
  "devDependencies": {
    "@types/config": "^3.3.0",
    "@types/express": "^4.17.14",
    "@types/express-ws": "^3.0.4",
    "@types/node": "^18.18.5",
    "@types/uuid": "^9.0.7",
    "@types/ws": "^8.5.10",
    "nodemon": "^2.0.20",
    "ts-node": "^10.9.2",
    "typescript": "^4.8.3"
  }
}
```
---
`tsconfig.json`
```json
{
  "compilerOptions": {
    "target": "es2020",
    "module": "commonjs",
    "allowJs": true,
    "outDir": "./dist",
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "strict": true,
    "skipLibCheck": true
  }
}
```

Solution
---

1. Create custom types:
For example, an `id` field will be added to the `ws` object.

`types.ts`
```ts
import {Request, NextFunction} from 'express'
import * as ws from 'ws'


export type MyWs = ws & {id: string}
export type MyWsRequestHandler = (ws: MyWs, req: Request, next: NextFunction) => void
```
---
2. Create router, middleware and controller:

`router.ts`
```ts
import {Router} from 'express'
import {WebsocketRequestHandler} from 'express-ws'
import {MyWsRequestHandler} from './types'
import {v4} from 'uuid'


const generateWsIdMiddleware: MyWsRequestHandler = (ws, _, next) => {
    ws.id = v4()
    next()
}

type TController = {
    getUser: MyWsRequestHandler
    activateUser: MyWsRequestHandler
}

const controller: TController = {
    getUser(ws, req) {
        const clientId = ws.id
        const {userId} = req.params

        console.log(`[ws] + connection | ${clientId}`)

        ws.on('close', () => {
            console.log(`[ws] - close | ${clientId}`)
        })

        ws.on('message', (message) => {
            console.log('[ws] message', message)
            // your code
            // services.onWsMessage(message)
            // services.getUser(userId)
        })
    },

    activateUser(ws, req) {
        const clientId = ws.id
        const {link} = req.params

        console.log(`[ws] + connection | ${clientId}`)

        ws.on('close', () => {
            console.log(`[ws] - close | ${clientId}`)
        })

        ws.on('message', (message) => {
            console.log('[ws] message', message)
            // your code
            // services.onWsMessage(message)
            // services.activateUser(link)
        })
    }
}

export const wsRouter = Router()
wsRouter.ws(
    '/users/:userId',
    generateWsIdMiddleware as WebsocketRequestHandler,
    controller.getUser as WebsocketRequestHandler
)
wsRouter.ws(
    '/users/activate/:link',
    generateWsIdMiddleware as WebsocketRequestHandler,
    controller.activateUser as WebsocketRequestHandler
)
```
---
4. Create a server:

`index.ts`
```ts
import express from 'express'
import expressWs from 'express-ws'
const expressWsServer = expressWs(express())
const app = expressWsServer.app
process.env['NODE_CONFIG_DIR'] = __dirname + '/config/'
import config from 'config'             // necessarily after creating the server
import {wsRouter} from './router'


const PORT = config.get('port') || 5000
app.use(express.json({inflate: true}))
app.use('/ws', wsRouter)

async function start() {
    try {
        app.listen(PORT, () => console.log(`Server listening on ${PORT} ...\n`))
    } catch (err) {
        console.log(err)
    }
}

start()
```

In conclusion
---
I placed the entire finished test project in the archive, link: [websocket.zip](https://github.com/websockets/ws/files/13715765/websocket.zip)

**Comment by jordansaker** [comment]
> I know this issue is old, but it keeps getting referenced, and none of the above are actually correct. Making a type like that is effectively just lying to the type system to create a type like that, as the actual type of the socket object will still be the default `WebSocket`.
> 
> ```ts
> // online will be `undefined`
> wss.on('connection', (ws) => console.log(ws.online.toString())
> ```
> 
> Take note of the type parameter for the server:
> 
> ```ts
>     class Server<
>         T extends typeof WebSocket.WebSocket = typeof WebSocket.WebSocket,
>         U extends typeof IncomingMessage = typeof IncomingMessage,
>     > extends EventEmitter {
> ```
> 
> It is NOT `T extends WebSocket.WebSocket`, but `T extends typeof WebSocket.WebSocket`. `typeof SomeClass` gives you the type of the class object (constructor function), not the type of an **instance** of the class. Thus, after extending the original `WebSocket` class, the generic type parameter should be `Server<typeof CustomWebSocket>`.
> 
> Also note the constructor parameter `WebSocket` in the options for `Server`. Here, you pass the custom **class**, which is then created here on connection:
> 
> https://github.com/websockets/ws/blob/a57e963f946860f6418baaa55b307bfa7d0bc143/lib/websocket-server.js#L382
> 
> Full example:
> 
> ```ts
> import { Server, WebSocket } from 'ws'
> 
> export class CustomWebSocket extends WebSocket {
>   userId!: string
> 
>   sendStuff() {
>     this.send('stuff')
>   }
> }
> 
> export class CustomWebsocketServer extends Server<typeof CustomWebSocket> {
>   constructor() {
>     super({
>       WebSocket: CustomWebSocket,
>     })
>   }
> 
>   socketForUser(userId: string): CustomWebSocket | undefined {
>     // this.clients is of type Set<CustomWebSocket>
>     for (const socket of this.clients) {
>       if (socket.userId === userId) {
>         return socket
>       }
>     }
>   }
> }
> 
> const wss = new CustomWebsocketServer()
> 
> wss.on('connection', (socket) => {
>   // socket is of type CustomWebSocket
>   socket.sendStuff()
> })
> ```
> 
> Final note: You don't need one, but if you add a constructor to your `WebSocket` subclass, it has to be compatible with that of the original `WebSocket` class, which is techically:
> 
> ```ts
> constructor(...params: ConstructorParameters<typeof WebSocket>) {}
> ```
> 
> However, it will only ever be called with `null`, so you may as well leave it as a no-args `constructor()`

Thanks this helped and seems to be the right way extending the class itself. I'd like to add to your last point, if you're using options for your server you can add that to your constructor i.e.

```ts
 constructor(...params: ConstructorParameters<typeof Server>) {}
```

**Comment by jordansaker** [comment]
> Full example:
> 
> ```ts
> import { Server, WebSocket } from 'ws'
> 
> export class CustomWebSocket extends WebSocket {
>   userId!: string
> 
>   sendStuff() {
>     this.send('stuff')
>   }
> }
> 
> export class CustomWebsocketServer extends Server<typeof CustomWebSocket> {
>   constructor() {
>     super({
>       WebSocket: CustomWebSocket,
>     })
>   }
> 
>   socketForUser(userId: string): CustomWebSocket | undefined {
>     // this.clients is of type Set<CustomWebSocket>
>     for (const socket of this.clients) {
>       if (socket.userId === userId) {
>         return socket
>       }
>     }
>   }
> }
> 
> const wss = new CustomWebsocketServer()
> 
> wss.on('connection', (socket) => {
>   // socket is of type CustomWebSocket
>   socket.sendStuff()
> })
> ```

Am I missing something here? Having CustomWebSocket in the CustomWebsocketServer constructor creates a circular import where in ends up passing either port, server, or noServer in the options more than once. When you create a new CustomWebsocketServer instance, even though you haven't passed any options arguments, it's passing the default WebsocketServer arguments more than once.

This error goes away when when you remove the Websocket option and add either port, server, noServer into the constructor.

**Comment by ehaynes99** [comment]
> it's passing the default WebsocketServer arguments more than once.

I don't know what that means. How can you pass arguments more than once? Either way, this has nothing to do with those properties. It's just referenced in a single place here: https://github.com/websockets/ws/blob/d343a0cf7bba29a4e14217cb010446bec8fdf444/lib/websocket-server.js#L385

**Comment by jordansaker** [comment]
This is what your full example is throwing when I run it:

```
 /app/node_modules/ws/lib/websocket-server.js:86

 throw new TypeError(

TypeError: One and only one of the "port", "server", or "noServer" options must be specified
     at new WebSocketServer (/app/node_modules/ws/lib/websocket-server.js:86:13)
     at new CustomWebSocketServer (/app/dist/src/typings/ws.js:21:9)

```

That error goes away with this for example:

```ts 
export class CustomWebSocketServer extends Server<typeof CustomWebSocket> {
  constructor(...params: ConstructorParameters<typeof Server>) {
    super({
      noServer: true
    })
  }
```

**Comment by ehaynes99** [comment]
Well sure, you still have to configure the [rest of the options](https://github.com/websockets/ws/blob/d343a0cf7bba29a4e14217cb010446bec8fdf444/lib/websocket-server.js#L28-L79) as appropriate for your use case, but none of those are related to the custom socket type. E.g.
```typescript
    super({
      WebSocket: CustomWebSocket,
      noServer: true,
    })
```

**Comment by kennethnym** [comment]
i found that the following works good enough:

```ts
import type { WebSocket } from "ws"

interface MyWebSocket extends WebSocket {
  myProp: string
}
```

then when initializing wss, pass `MyWebSocket` to the constructor as a type arg:

```ts
const wss = new WebSocketServer<MyWebSocket>({})
```

**Comment by forrestwilkins** [comment]
Here's all I needed to do to add an `id` field:
```
export class WebSocketWithId extends WebSocket {
  id!: string;
}

export class WebSocketServerWithIds extends WebSocketServer<
  typeof WebSocketWithId
> {}

const webSocketServer = new WebSocketServerWithIds({ path: '/ws' });
```

**Comment by ehaynes99** [comment]
@forrestwilkins that's not actually using your custom class, it's just tricking the type system into thinking that it is. The socket objects will just be `WebSocket`, not `instanceof WebSocketWithId`. If the class did anything beyond declaring properties ([which is completely erased at runtime](https://www.typescriptlang.org/play/?#code/MYGwhgzhAECiAeYC2AHEBTaBvAsAKGmgEsATAQgC5oIAXAJyIDsBzfAXyA)), that would be broken.

```typescript
export class WebSocketWithId extends WebSocket {
  id!: string;

  sayId() {
    console.log('id is:', this.id);
  }
}

// ...
const webSocketServer = new WebSocketServerWithIds({ path: '/ws' });
// create some sockets...
const ws = webSocketServer.clients[0];
// false
const isInstance = ws instanceof WebSocketWithId;
// TypeError: ws.sayId is not a function
ws.sayId();
```
You need the constructor parameter like I showed above:

```typescript
type Params = Omit<ConstructorParameters<typeof WebSocketServer>, 'WebSocket'>

export class WebSocketServerWithIds extends WebSocketServer<typeof WebSocketWithId> {
  constructor(...params: Params) {
    super({
      ...params,
      WebSocket: WebSocketWithId,
    });
  }
}
```
Then the correct type is used:
```typescript
const webSocketServer = new WebSocketServerWithIds({ path: '/ws' });
// create some sockets...
const ws = webSocketServer.clients[0];
// true
const isInstance = ws instanceof WebSocketWithId;
// prints id to the console
ws.sayId();
```

**Comment by matthewoestreich** [comment]
Full disclosure; I'm not a TypeScript expert. So, take this as you may....

This was the only way I could get it to work. For some reason, using other solutions in this thread meant I wasn't able to use other types from `ws`.. (like `RawData`, or `WebSocketServer`, etc..).

### **Solution:**

Create a `ws.d.ts` file (wherever you are keeping your type definitions) with the following contents:

```ts
// ws.d.ts
import * as _ from "ws"; // without this, it wouldn't work correctly

declare module 'ws' {
  export interface WebSocket {
    foo?: Bar; // Your extension
  }
}
```

Again, I'm not a TS expert so if this is not optimal or if I'm doing something incorrect here, please let me know!

**Comment by forrestwilkins** [comment]
@ehaynes99 I stand corrected. Thanks for clarifying that!

**Comment by forrestwilkins** [comment]
@ehaynes99 I actually tried your approach, but got the following error:
```
TypeError: One and only one of the "port", "server", or "noServer" options must be specified
    at new WebSocketServer (/Users/user/project/node_modules/ws/lib/websocket-server.js:86:13)
    at new WebSocketServerWithIds (/Users/user/project/dist/pub-sub/pub-sub.models.js:10:9)
    at /Users/user/project/dist/main.js:53:29
    at Generator.next (<anonymous>)
    at /Users/user/project/dist/main.js:31:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/user/project/dist/main.js:27:12)
    at /Users/user/project/dist/main.js:50:8
    at Object.<anonymous> (/Users/user/project/dist/main.js:72:4)
    at Module._compile (node:internal/modules/cjs/loader:1546:14)
```

**Comment by ehaynes99** [comment]
That would be because you're passing in more than one of "port", "server", or "noServer". It has nothing to do with my example.

**Comment by forrestwilkins** [comment]
@ehaynes99 Here you can see that I'm only passing in `server` when instantiating `webSocketServer`, not `port` or `noServer`.  I still get the above error when attempting to add the constructor.

**Comment by ehaynes99** [comment]
The error might be misleading, but here's where that message comes from:
https://github.com/websockets/ws/blob/68614728c164eb55462ff12ba24cb30451d28ec6/lib/websocket-server.js#L81-L90

My example does just 2 things:
* properly sets the generic types for a subclass of `WebSocket` to be used as intended instead of hacking around in the types
* passes the subclass as the `WebSocket` argument to `WebSocketServer`

It just forwards all of the other configuration.

Note that your `WebSocketServerWithIds` does the generics but doesn't do the latter, but that's not your issue here. Generics only exist at compile time, and since your subclass of `WebSocketServer` doesn't override anything, at runtime it's **exactly** the same as the base `WebSocketServer` class. Try to get that working first and then handle the custom subclass afterwards.
