### ISSUE TITLE
Expose the httpServer officially as a prop in websocket server

### ISSUE THREAD

**Issue by jacobbogers** [websockets/ws#1519]
- [ x ] I've searched for any related issues and avoided creating a duplicate
      issue.

#### Description

the underlying `_server` property on the websocketserver class, would like for it be promoted to the api (via "get server(){...}" property so you also keep the _server prop.  Right now i monkeyPatch the wss class , but this would be a cool thing

#### Reproducible in:

- 4.0.0:
- 10:
- windows 10

#### Steps to reproduce:
NA

**Comment by lpinca** [comment]
It don't like this because there is already a way to use the `http.Server` directly. Instead of creating one implicitly with the `port` option, you create one explicitly as shown in this example https://github.com/websockets/ws#external-https-server.

**Comment by jacobbogers** [comment]
the point is i have to hand over 2 objects instead of one, 
My main goal is to check `http.Server.listening`  prop.  is it possible to expose "listening" prop from the httpServer , so i know its "up" (after for example an error or whatever)

**Comment by lpinca** [comment]
What you mean with two objects? `WebSocketSever` and `http.Server`?
You have to do it anyway even if you get the `http.Sever` from `wss._server` no?

Again I think it doesn't make sense to expose all `http.Server` methods, events, and attributes when you can use it directly.

**Comment by lpinca** [comment]
Closing, discussion can continue if needed.

**Comment by jacobbogers** [comment]
Hi,  yeah the wss implements the event  totally differently then the underlying httpserver

for example, if i httpServer.close().  it will fire the "close" event, the wss server doesnt do that, its strips the all the eventhandlers from the underlying http server,  

if the behavior of wss was the same as the http server, that would be wonderfull, since i implement rest calls and websocket together. I Need to make my node restartable (hot) for whatever reason, so how things shut down is kindof important

I am not going to use "_server" because its not part of the documented api, so it can break, never doing such things again.

What i did was just  use your example of explicitly handling upgrade request, also gives me the most flexibility,  so in the end it all worked out.
