### ISSUE TITLE
How to use the functions defined in sender.js file in javascript code?

### ISSUE THREAD

**Issue by shaiksyedali** [websockets/ws#1524]
- [ ] I've searched for any related issues and avoided creating a duplicate
      issue.

#### Description

I am building a websocket client and server application. For my use, case I have to frame the data and send it to server and vice versa. I have gone through the repository and found sender.js in lib has some handy methods that can acheive this. My question here is how can I use those methods in my implementation code? When I try to an import or require, it always throws me an error..

Example : import * as Sender from '../../../../../node_modules/ws/lib/sender';
Example : const Sender = require('../lib/sender');

Both returning errors.

How do I use these methods in my code?

#### Reproducible in:

- version:
- Node.js version(s):
- OS version(s):

#### Steps to reproduce:

1.

2.

3.

**Comment by lpinca** [comment]
`WebSocket.prototype.send()` will frame and the data. Why do you want to frame the data yourself? Anyway you can use the public `Sender.frame()` method in this way.

```js
const { Sender } = require('ws');
// or
// const Sender = require('ws/lib/sender')

const list = Sender.frame(buf, options);
```
