### ISSUE TITLE
How to signal end of stream after sending a large stream in ws?

### ISSUE THREAD

**Issue by shaiksyedali** [websockets/ws#1527]
- [ ] I've searched for any related issues and avoided creating a duplicate
      issue.

#### Description

I am trying to send a very large stream of data over websockets from client to server.

I am splitting the large stream into smaller chunks and then sending chunks over ws client in a loop

On the server side, they have a limited input buffer size due to some memory constraints. So I am sending the specified chunks via ws client like,

 ws.send(fragments[i], {binary: true});

The server has to wait till all the chunks have been received and then they can process the data. But the server doesn't know how many chunks that client will send and when will the stream end.

I read somewhere in SO that, ws.close() can be used to signal the end of stream.

But I don't want to close the websocket, since the server again have to reconnect with the client to send the processed data back and that adds overhead on the server.

Is there anyway I can signal end of stream to the ws server without closing the socket?

#### Reproducible in:

- version: Latest
- Node.js version(s):
- OS version(s):

#### Steps to reproduce:

1.

2.

3.

**Comment by lpinca** [comment]
It depends. Do you want to receive the whole message a single message on the server? Does it have enough memory to buffer all chunks? If so you can use a fragmented message. What you are doing now is sending `n` messages where `n` is the number of pieces of your original message.

To send a fragmented message use the `fin` option. Set it to `false` for all fragments but the last one. On the server all fragments will be buffered and a single `'message'` event will be emitted when the last fragment is received.

If this is not an option, you have to number your messages.

**Comment by shaiksyedali** [comment]
No. Server cannot handle the entire stream at once. That why I am sending the streams in chunk. I tried the option you suggested and set the fin option of the last frame to be true. But as you said, on the server side, I received the entire message in one go. My server cannot handle that much data.

So, you suggest numbering the frames? There isnt some other way to make this work? Is it a restriction of this ws module or with websocket API?

**Comment by lpinca** [comment]
It's how the protocol work, it's message oriented. I see no other way other than numbering the messages. That is, the info about the last message is in the message itself.

**Comment by lpinca** [comment]
For example, you can add one more byte at the beginning of each piece you send. On the server when you receive the message you remove the first byte. If it is set to `1` you know it is the last one.

**Comment by lpinca** [comment]
You could also make the client send a ping or pong frame to signal that it finished sending a message, but you have to make sure ping/pong is not used for something else.

If you do this keep in mind that a peer automatically responds to ping with a pong.

**Comment by lpinca** [comment]
Yet another option: send one additional message at the end, which can be identified as a "delimitator".

**Comment by shaiksyedali** [comment]
So you are saying at the end of stream, we can send an EOF 1 byte frame to the server to signal the stream is done?

**Comment by lpinca** [comment]
Yes, that's an option.

**Comment by shaiksyedali** [comment]
Let say I send -1 to the server to signal end of stream. But what if the data stream I am sending also contains -1. Is there any specific standard to signal EOF or EOS without running into any risk?

**Comment by lpinca** [comment]
Use something unique, like I don't know 32 random bytes. Chances of collisions are close to 0.

**Comment by lpinca** [comment]
Or if you always send binary frame, use a text frame to signal the end.

**Comment by shaiksyedali** [comment]
Before sending the binary stream, I need to send text frame which carries metadata info about the binary stream. So let me see what I can do there..

**Comment by lpinca** [comment]
You can use that then. In the metadata you can specify the length of your original message is. You know you are done after `length` bytes are received.

**Comment by 89z** [comment]
I came to this page from internet search. If it helps anyone, it seems some implementations abstract this away for you, so you dont have to think about it. For example, Go offers the Message Codec [1], for use with string or byte slice. So as long as you dont go over the MaxPayloadBytes (default 32 MB), then it just works.

1. https://godocs.io/golang.org/x/net/websocket#Message
