### ISSUE TITLE
Does ws.close() flush all the remaining data in both server and client?

### ISSUE THREAD

**Issue by shaiksyedali** [websockets/ws#1528]
- [ ] I've searched for any related issues and avoided creating a duplicate
      issue.

#### Description

I am using ws module to create ws server and client. From the client side, I am sending data in frames and the server sends the processed data back to the client.

My question here , in client side, when I am done sending all the frames,  I do ws.close() to initiate closing handshake. While I am doing this, both the client and server are still sendind data. 

Does ws.close() wait for the server and client to send all the remaining data or does it close the socket immediately?

#### Reproducible in:

- version:
- Node.js version(s):
- OS version(s):

#### Steps to reproduce:

1.

2.

3.

**Comment by lpinca** [comment]
Yes, the socket is closed only when both peer received and sent a close frame so all data is flushed. However it is possible that the closing handshake fails due to network conditions. In that case you have no guarantee.
