### ISSUE TITLE
memory usage is pretty high compared to uws

### ISSUE THREAD

**Issue by NishantDesai1306** [websockets/ws#1530]
I am trying to create a pet project with small server with 1GB of RAM, my use-case includes comparatively small socket clients approx 75-100 and it requires constant data transfer from server to client (basically for a game so new updates are sent from server to client many times a second).

also although the number of socket clients are low the clients will disconnect/reconnect pretty frequently (basically players will leave and join the game pretty frequently at rate of about 5-10 player will leave and new players will join).

Till yesterday I was using uws but due to some issues I switched to ws but now every 2 HR my process runs out of memory, so is 1GB of memory enough for this lib to run smoothly or is there some specific config that I can use for this lib so that it works fine ?

by the way I am using it normally only like no additional options are give to socket server apart from port.

**Comment by lpinca** [comment]
Yes definitely. 100 clients are literally nothing. with 1 GB you should be fine even with a few thousands. I don't know the details of your app and how much data you are sending but I suspect you have a leak somewhere.

**Comment by lpinca** [comment]
Take a look at this discussion https://github.com/websockets/ws/issues/617 if you are broadcasting the same data to all clients and permessage-deflate is disabled.
