### ISSUE TITLE
Is there anyway we can test this ws module in javascript using some mocking library?

### ISSUE THREAD

**Issue by shaiksyedali** [websockets/ws#1534]
- [ ] I've searched for any related issues and avoided creating a duplicate
      issue.

#### Description

I am using this ws npm module for websocket communications.

I want to be able to test the functionalities of ws module like making a socket connection,
socket send, close etc

Is there any mocking library available to mock these functionalities in test?

#### Reproducible in:

- version:
- Node.js version(s):
- OS version(s):

#### Steps to reproduce:

1.

2.

3.

**Comment by lpinca** [comment]
You can try with one of the many modules available on npm like https://github.com/thoov/mock-socket but I do not use them so I don't know.

I'm closing this as it's not an issue in ws.
