### ISSUE TITLE
can have a using processes example?

### ISSUE THREAD

**Issue by shanxiaoda** [websockets/ws#1535]
Hi.
I'm sorry to disturb you. I am a beginner of node.js and I'm a h5 game programmer.
I like 'ws' very much ，he's very simple to use.
I don't know how to use multiple processes to listen on the same port.
Can you write an example by Using multiprocesses ?
my mean is i want write a game server by Using multiprocesses.
Thank you very much.

flashda

**Comment by lpinca** [comment]
Take a look at this example https://nodejs.org/api/cluster.html#cluster_cluster, it's the same.

**Comment by shanxiaoda** [comment]
> Take a look at this example https://nodejs.org/api/cluster.html#cluster_cluster, it's the same.

thank you very much
