### ISSUE TITLE
Complete API Documentation

### ISSUE THREAD

**Issue by Goutam192002** [websockets/ws#1536]
I can see that we do not have a complete API documentation. For example, I was trying to figure out what the wss.clients object looks like but  it seems there is no detailed documentation available.

After looking thoroughly I found that wss.clients is a set, but I wanted to know what the individual item in that set looks like.

**Comment by Goutam192002** [comment]
Also, a few more examples like client identification, messaging to a particular client should have been added.
Helps beginners like me XD

**Comment by lpinca** [comment]
We have decent documentation and examples:

- https://github.com/websockets/ws#api-docs
- https://github.com/websockets/ws/blob/master/README.md
- https://github.com/websockets/ws/tree/master/examples

I thin it is enough to get anyone started.

**Comment by Goutam192002** [comment]
I think I already proved my point above.

**Comment by lpinca** [comment]
Feel free to contribute by opening PR to improve things then.
