### ISSUE TITLE
WebSocket.Server is not a constructor

### ISSUE THREAD

**Issue by pyeongoh** [websockets/ws#1538]
content is same with title.

I used 'ws' module in electron main process not browser.

It work on local environment, but occur error with message 'WebSocket.Server is not a constructor' when packaging. 

I'm tried to solve this with add `external: ['WebSocket', 'WebSocketServer']` in webpack.config.js. but It didn't work.

anyone who can solve this problem. please, tell me how to solve.

**Comment by lpinca** [comment]
webpack probably uses this https://github.com/websockets/ws/blob/master/browser.js. You have to configure it to ignore the browser field in package.json. With browserify this can be done with the `--no-browser-field` flag.

I don't know how to do the same with webpack, maybe https://webpack.js.org/configuration/resolve/#resolvealiasfields?

**Comment by pyeongoh** [comment]
this is will be closed, this problem is because of module import order problem, 
In my webpack configurations, resolve.mainFields's value was ordered by with 'browser' > 'main',
so, I changed order to 'main' > 'browser' and It works right . 
thx to @lpinca, I've got the hint from your comment.

**Comment by andypotato** [comment]
I can confirm the solution by @pyeongoh is working fine. In my case I was using Vue with electron-builder and I had to add the following configuration options to vue.config.js:

```
module.exports = {
  configureWebpack: {
    resolve: {
      mainFields: ['main', 'browser']
    }
  }
}
```
Afterwards everything worked as expected.

**Comment by Domiii** [comment]
@andypotato's workaround did not work for me.

This worked though:

Add a custom alias for `ws` to always target `main` in `webpack.config.js`:

```js
module.exports = {
  // ...
  alias: {
    // ...
    'ws': path.resolve(path.join(projectRoot, 'node_modules/ws/index.js' )) // fix for https://github.com/websockets/ws/issues/1538
  }
};

**Comment by octoquad** [comment]
> I can confirm the solution by @pyeongoh is working fine. In my case I was using Vue with electron-builder and I had to add the following configuration options to vue.config.js:
> 
> ```
> module.exports = {
>   configureWebpack: {
>     resolve: {
>       mainFields: ['main', 'browser']
>     }
>   }
> }
> ```
> 
> Afterwards everything worked as expected.

Funny enough, this is a suitable workaround for https://github.com/websockets/ws/issues/1459 as well.

**Comment by meoyawn** [comment]
I'm getting this with ESM:

package.json:
```json
{
  "type": "module",
  "dependencies": {
    "ws": "^8.2.3"
  }
}
```

```js
import ws from 'ws';

new ws.Server({ port: 8080 });
```


```
TypeError: ws.Server is not a constructor
```

**Comment by lpinca** [comment]
There is no `ws.Server` in the ESM version, use `import { WebSocketServer } from 'ws'` instead.

**Comment by loicgirard** [comment]
> There is no `ws.Server` in the ESM version, use `import { WebSocketServer } from 'ws'` instead.

How do you import it when using in a script ? 
We need to download https://github.com/websockets/ws , add the ws folder in the same repository of our html page and do:
`import { WebSocketServer } from '.ws'` ?

Thanks

**Comment by Domiii** [comment]
@loicgirard The `ws` server cannot run in the browser. 

References:
* https://stackoverflow.com/questions/4786352/will-websockets-allow-a-server-to-run-in-the-browser
* https://stackoverflow.com/questions/19593401/chrome-socket-listener-in-browser
* https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API/Writing_WebSocket_servers

**Comment by GHDanielG** [comment]
I have encountered this problem when building an electron project and other solutions did not work for me.

the message 
`ws does not work in the browser. Browser clients must use the native `

comes from the file ./node_modules/ws/browser.js
because either  electron or ws thinks you are in a browser.

the fix that will work for all is to just change the line 
`"browser": "browser.js",`
in ./node_modules/ws/package.json to
`"browser": "index.js",`
or just delete it . then the error wont show up because even if it thinks you are running in a browser it will still load the index.js main file

**Comment by DBCOOPER90** [comment]
> try this
> 
> import WebSocket, { WebSocketServer as WSWebSocketServer } from 'ws';
> 
> // work with commonjs and esm const WebSocketServer = WebSocket.Server || WSWebSocketServer;

That actually worked for me. Thanks

**Comment by DBCOOPER90** [comment]
I found this : https://linu.us/live-chat-with-sveltekit-and-socketio. Still investigating on my end.

**Comment by Casu3475** [comment]
@DBCOOPER90  thanks a lot, i 'll try this

**Comment by DBCOOPER90** [comment]
I've also discovered that svelte supports its own Event Handler, so you can dispatch events instead of using sockets.io or ws library. Not aure if its just front end dispatch tough.

**Comment by jjxxs** [comment]
this is still an issue for me:

- i use ```ws``` for testing, so i have it declared as a dev-dependency
- the error i get is ```ws_1.Server is not a constructor```
- no webpack or any other bundler in my build
- **downgrading to ```7.0.0``` fixes the issue**

```package.json```:
```
  "devDependencies": {
    "@types/ws": "^8.5.4",
    "typescript": "^5.0.4",
    "ws": "^8.13.0" // also tried e.g. '^8.5.4'
  }
```

```tsconfig.json```:
```
{
   "compilerOptions": {
      "target": "es5",                         
      "module": "commonjs"
   }
}
```

```my.test.ts```:
```
import {Server} from "ws"

const port = 1337
const srv = new Server({port})
```

Error:
```
ws_1.Server is not a constructor
TypeError: ws_1.Server is not a constructor
```

**Comment by paulorenanmelo** [comment]
I'm having the same issue here using Webpack.
None of the suggested actions worked, I tried:
- downgrading to 7.0.0
- copying ws folder to src and dist and changing import to "./ws" in the javascript
- adding webpack.config.js with alias 'ws' pointing to node_modules
Any solution to this issue?

**Comment by sachinabs** [comment]
I have downgraded the websocket to 7.0.0 it's working properly.

**Comment by Tetrax-10** [comment]
Simple fix:

```js
import { WebSocketServer } from "ws"

const server = new WebSocketServer({ port: 8080 })
```
