### ISSUE TITLE
Passing a live socket to a child process

### ISSUE THREAD

**Issue by geoffreyd** [websockets/ws#154]
Is there already a way to pass a WS Socket object as a handle like you can a HTTP socket as seen here:

http://nodejs.org/api/child_process.html#child_process_child_send_message_sendhandle

Or can we use the existing http socket passing so that the ws connection initiates on the parent, we can process it (logon/authentication etc.) then pass it off to a specific child for the rest of the connection.

Our use case is that our users belong to different rooms, that we want to handle on separate children, but we need to authenticate (and find out which room) centrally.

**Comment by endel** [comment]
@geoffreyd I have exactly the same question. Sorry for replying to such an old thread, but did you managed to get this working?

**Comment by lpinca** [comment]
@endel something like this

```js
const cp = require('child_process');
const http = require('http');

const child = cp.fork('child.js');
const server = http.createServer();

server.on('upgrade', (request, socket) => {
  child.send({ headers: request.headers, method: request.method }, socket);
});

server.listen(8080);
```

```js
const WebSocket = require('ws');

const wss = new WebSocket.Server({ noServer: true });

process.on('message', (request, socket) => {
  wss.handleUpgrade(request, socket, undefined, (ws) => {
    ws.send('foo');
  });
});
```

works but I never used ws in this way.

**Comment by endel** [comment]
Awesome, thanks @lpinca !

**Comment by elithrar** [comment]
Note that I believe you should call `socket.pause()` prior to `child.send` and then call `socket.resume()` inside the `message` event emitted within the child process/worker.

This is to mimic the behaviour you would get with [`net.Server`](https://nodejs.org/api/net.html#net_net_createserver_options_connectionlistener) with `pauseOnConnect: true`.

**Comment by lpinca** [comment]
There should not be any data on the socket during the handshake apart from the headers. The spec says that no data should be exchanged before the `'open'` event.

The parent process reads the request headers and the child process writes the response headers so I think it's fine also without pausing/resuming the socket.

**Comment by elithrar** [comment]
Good point. I'd read the spec before, but hadn't interpreted the handshake
boundaries as strictly -

> Once the client's opening handshake has been sent, the client MUST
wait for a response from the server before sending any further data.

**Comment by endel** [comment]
This is not strictly related to `websockets/ws`, but I'd really appreciate if you guys can give me some direction.

I managed to pass the WebSocket connection successfully in the `upgrade` callback - it's where I can be sure we have an actual WebSocket connection.

```javascript
server.on('upgrade', (request, socket, head) => {
  worker.send([Protocol.PASS_WEBSOCKET, {
    headers: request.headers,
    method: request.method,
  }, head], socket);
});
```

The problem, though, is when I have a regular HTTP request and I want to balance it differently. Ideally, I'd use the `server.on('connection', ...)` callback to pass every connection, but apparently, it's not possible to determine if the connection is a WebSocket at this point. On the `"upgrade"` callback I can be sure it **is** a WebSocket, but how could I handle for regular HTTP requests?

I basically need to have different balancing for regular HTTP requests and WebSocket requests. Any idea? 😅

**Comment by lpinca** [comment]
@endel how about

```js
server.on('request', (request, response) => {
  // This is a regular request.
});
```

**Comment by lpinca** [comment]
On second thought that won't work as you can "send" the request socket to a child process but then you would need to read/write to the socket directly without all the benefits of the `request` and `response` objects.

As you said this should be solved upstream but there is no way to know if a TCP socket will be used for a regular request or an upgrade request without reading the headers.

**Comment by endel** [comment]
Not sure if that's the best way to handle this, but I've managed to successfully redirect and a `"request"` from master to worker process by re-creating the request in the worker process. 

https://github.com/gamestdio/colyseus/commit/cc18f9e7b848a77ba474e54efc14fd706d9648db

**Comment by FunFetched** [comment]
Just tried @lpinca 's solution in my own project, and it works great. There's just one caveat; the following line:

` wss.handleUpgrade(request, socket, undefined, (ws) => {`

... throws the following error for me:

if (head.length > 0) socket.unshift(head);
TypeError: Cannot read property 'length' of null

I was able to fix it by exchanging `undefined` for `[]`

**Comment by ORESoftware** [comment]
what is the nature of 'upgrade' / `handleUpgrade`? Namely, I want to know the performance - is it going through the parent process or writing directly to the socket?
