### ISSUE TITLE
Error line 16 in /ws/lib/websocket.js

### ISSUE THREAD

**Issue by DigitalCoin1** [websockets/ws#1540]
- [X] I've searched for any related issues and avoided creating a duplicate
      issue.

#### Description

/home/spero/SperoExchange_Opentrade/node_modules/ws/lib/websocket.js:16
const {
      ^

> SyntaxError: Unexpected token {
>     at exports.runInThisContext (vm.js:53:16)
>     at Module._compile (module.js:374:25)
>     at Object.Module._extensions..js (module.js:417:10)
>     at Module.load (module.js:344:32)
>     at Function.Module._load (module.js:301:12)
>     at Module.require (module.js:354:17)
>     at require (internal/module.js:12:17)
>     at Object.<anonymous> (/home/spero/SperoExchange_Opentrade/node_modules/ws/index.js:3:19)
>     at Module._compile (module.js:410:26)
>     at Object.Module._extensions..js (module.js:417:10)
> 

#### Reproducible in:

- Node.js version(s): v4.2.6
- OS version(s): Ubuntu 16.04

**Comment by lpinca** [comment]
ws@6 is only compatible with Node.js >= 6.

**Comment by DigitalCoin1** [comment]
> ws@6 is only compatible with Node.js >= 6. See https://github.com/websockets/ws/releases/tag/6.0.0

Thank you!
I updated my NODE.
