### ISSUE TITLE
Cannot read property 'headers' of undefined

### ISSUE THREAD

**Issue by agarian-2** [websockets/ws#1542]
Alright, so I've run into an issue. I have a program that has been sitting for years, meaning WS hasn't been updated. Well today I updated it from 1.1.0 to the latest version, and I have an issue I can't fix (maybe it's just me being stupid, but I haven't seen other issues like this). Really all you need to do is try doing stuff with `upgradeReq.headers` to replicate this. Not much to say about it, other than `upgradeReq.headers` no longer works, and I kind of need it to. This is the code we're dealing with; granted, not the full function, but likely more than enough to work with.
![Capture1](https://user-images.githubusercontent.com/36286279/55578848-e40b7880-56e4-11e9-84fe-42d3c3590d16.PNG)

Again I apologize if there are other issues like this; I haven't seen any likewise to this.

**Comment by lpinca** [comment]
See https://github.com/websockets/ws/pull/1099

**Comment by agarian-2** [comment]
That's an oof lol
I noticed some other issues like `socket.destroy()` not working with that latest version that I'll need to square away later, but that works, thanks.

**Comment by lpinca** [comment]
Use `ws.terminate()` if you want to immediately close the connection without waitinf for the closing handling to complete. Internally it calls `socket.destroy()` on the `net.Socket`.
