### ISSUE TITLE
No way to handle "RangeError: Max payload size exceeded"

### ISSUE THREAD

**Issue by travikk** [websockets/ws#1543]
- [x] I've searched for any related issues and avoided creating a duplicate
      issue.

#### Description

When incoming message exceeds maxPayload, exception is thrown and there is no way to handle it.

#### Reproducible in:

- version: 6.2.1
- Node.js version(s): all
- OS version(s): all

#### Steps to reproduce:

1. Set maxPayload option in constructor to something low, like 5
2. Send any message
3. Watch the WS Server explode

#### Expected result:

Perhaps "error" handler should be called?

#### Actual result:

Server blows up by throwing an exception

**Comment by lpinca** [comment]
Add a listener for the `'error'` event on the `WebSocket` instance.

```js
'use strict';

const WebSocket = require('ws');
const { strictEqual } = require('assert');

const server = new WebSocket.Server(
  {
    port: 8080,
    maxPayload: 5
  },
  function() {
    const ws = new WebSocket('ws://localhost:8080');

    ws.on('open', function() {
      ws.send('abcdef');
    });
  }
);

server.on('connection', function(ws) {
  ws.on('close', function(code) {
    strictEqual(code, 1009);
  });

  ws.on('error', console.error);
});
```
