### ISSUE TITLE
@types/ws WebSocket class is not exported, so cannot instantiate a client using typescript

### ISSUE THREAD

**Issue by sonoman** [websockets/ws#1545]
I cannot import WebSocket class into my NodeJS service.

If I write

import * as WebSocket from 'ws';

class WebSocket is not exported.

I fixed it locally by moving WebSocket class inside WebSocket namespace, so I can write

import * as WebSocket from 'ws';
ws = new WebSocket.WebSocket

But I'd like a solution where I don't need to overwrite an external file...

**Comment by lpinca** [comment]
TypeScript type definitions are not maintained by us. They are on [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/ws) repository.
