### ISSUE TITLE
socketserver@2.0.0 No repository field. 

### ISSUE THREAD

**Issue by suchakra** [websockets/ws#1547]
- [ ] I've searched for any related issues and avoided creating a duplicate
      issue.

#### Reproducible in:

- version:
- Node.js version(s):
- OS version(s):

#### Steps to reproduce:

1. npm install some project referring to socketserver@2.0.0

#### Expected result:
no errors

#### Actual result:
socketserver@2.0.0 No repository field.

**Comment by suchakra** [comment]
https://stackoverflow.com/questions/16827858/npm-warn-package-json-no-repository-field the fix is tiny

**Comment by lpinca** [comment]
What is socketserver@2.0.0?
The repository field is already specified in ws [package.json](https://github.com/websockets/ws/blob/master/package.json#L15).

**Comment by suchakra** [comment]
My bad. I shall close the issue. The error message was confusing.
