### ISSUE TITLE
ping throws an exception if connection is broken (not an "error" event)

### ISSUE THREAD

**Issue by jacobbogers** [websockets/ws#1551]
- [x ] I've searched for any related issues and avoided creating a duplicate
      issue.

#### Description
Hi,
The "ping" function throws an exception when the socket is closed (for whatever reason)
should it not throw an error event in this case?
/**

/node_modules/ws/lib/websocket.js:302

#### Reproducible in:

- version:4.1.0
- Node.js version(s): v11.13.0
- OS version(s): linux Ubuntu

#### Steps to reproduce:

1.  socket closes 

2.  try to ping

3.

#### Expected result:

have an error event emitted

#### Actual result:

error event is not emitted

**Comment by lpinca** [comment]
It's like `send()` you have to check the `readyState` and/or use a callback.
See also https://github.com/websockets/ws/pull/1532
