### ISSUE TITLE
Add open() method to handle auto re-connection logic properly

### ISSUE THREAD

**Issue by jerome-benoit** [websockets/ws#1553]
#### Description

In order to add an auto re-connection to my WS client, I have hacked around object reassignment to make it at least kind of working. But to not lose all the callbacks without adding ugly hack, it really be simpler to just add an open() or connect() method that will make the WS try to connect again. 

Current implementation:
[WSClient.js.txt](https://github.com/websockets/ws/files/3103806/WSClient.js.txt)

Could you please give me guidance to add that method to ws ? I'll make a PR once finished.

**Comment by lpinca** [comment]
Sorry but I'm -1 on adding anything that diverges from the HTML https://html.spec.whatwg.org/multipage/web-sockets.html interface.

**Comment by jerome-benoit** [comment]
Le 22/04/2019 à 18:03, Luigi Pinca a écrit :
>
> Sorry but I'm -1 on adding anything that diverges from the HTML
> https://html.spec.whatwg.org/multipage/web-sockets.html interface.
>
The web sockets interface specifications is somewhat old and fail to
take into account some use cases like the one I'm working on : OCPP 1.6
https://www.openchargealliance.org/protocols/ocpp-16/ which is to date
the most widely used version to supervise and administrate charging
stations. In that protocol, messages (JSON fomat) in both direction
between server and charging stations go through two web sockets and for
reliability, that kind of usage *need* a proper way to reconnect without
killing the current disconnected sockets and opening a new WS from
scratch. The network conditions between server and charging stations are
far from being the one you can find between a browser and a HTTP server
on a residential internet access ... or even 4G.

If upstream ws do not what to diverge from the specs, that's fine but at
some point in the future, the specifications will be revised to take
into account that kind of use case that are far from being anecdotal
(for example, some big cities in E.U. have more than 10 000 public
charging stations to supervise and administer using OCPP 1.6). So maybe
adding a public method that will permit to connect a ws make a lot of
sense even if the specs do not cover it yet (and they will be in the
future, trust me :)).

I've not dive into the ws code deeply, but maybe I just have to use a
private method inside my class inheritance (netconnect ?) ?

Regards,

-- 
Jérôme Benoit aka fraggle
Piment Noir - https://piment-noir.org
OpenPGP Key ID : 27B535D3
Key fingerprint : B799 BBF6 8EC8 911B B8D7 CDBC C3B1 92C6 27B5 35D3

**Comment by lpinca** [comment]
> I've not dive into the ws code deeply, but maybe I just have to use a private method inside my class inheritance ?

There is no private method to open the connection. It is only done once in the constructor: https://github.com/websockets/ws/blob/5479eaedff6d92bf1f2cac8f269c474344f88749/lib/websocket.js#L555.

To be honest I don't think the spec will be changed to handle reconnection. It is something that can be done with the existing interface. It is not ideal, because a new instance must be created but it's not that hard to create a wrapper to do that seamlessly. Here are a few examples:

- https://github.com/websockets/ws/blob/5479eaedff6d92bf1f2cac8f269c474344f88749/lib/websocket.js#L555
- https://github.com/lukeed/sockette

If the spec will ever be changed I hope it will be to add the ability to send ping and pong frames from the browser :)

**Comment by jerome-benoit** [comment]
Le 22/04/2019 à 21:13, Luigi Pinca a écrit :
>
>     I've not dive into the ws code deeply, but maybe I just have to
>     use a private method inside my class inheritance ?
>
> There is no private method to open the connection. It is only done
> once in the constructor:
> https://github.com/websockets/ws/blob/5479eaedff6d92bf1f2cac8f269c474344f88749/lib/websocket.js#L555.
>
> To be honest I don't think the spec will be changed to handle
> reconnection. It is something that can be done with the existing
> interface. It is not ideal, because a new instance must be created.
>
It's under discussion currently, because it's simply an API design
mistake to require a full object instate just to simply connect the web
socket. The use of web socket for MSRP (rfc7977) have also raised a
number of discussion at the IETF and w3c on that specific issue, just as
the usage in OCPP and similar protocols that go way beyond the primary
usage of web sockets in browsers.  

-- 
Jérôme Benoit aka fraggle
Piment Noir - https://piment-noir.org
OpenPGP Key ID : 27B535D3
Key fingerprint : B799 BBF6 8EC8 911B B8D7 CDBC C3B1 92C6 27B5 35D3

**Comment by lpinca** [comment]
Ok, we will consider it _after_ it will appear in a specification then, not before.

**Comment by jerome-benoit** [comment]
No problem, I can live with my class extension that will deal with it :)

I think you can close that issue (or I can do it), thanks.

**Comment by lpinca** [comment]
Ok, thank you for bringing this to our attention.
