### ISSUE TITLE
options.method = ingored // const get = isSecure ? https.get : http.get;

### ISSUE THREAD

**Issue by mStirner** [websockets/ws#1561]
#### Description
http 'method' in options is ignored, due to: 
```js
const get = isSecure ? https.get : http.get;
```

https://github.com/websockets/ws/blob/master/lib/websocket.js#L491
```js
const ws = new WebSocket("http://127.0.0.1", {
    ...
    method: "POST"
});
```

**Comment by lpinca** [comment]
The HTTP method for the WebSocket handshake request MUST be GET.

**Comment by lpinca** [comment]
https://tools.ietf.org/html/rfc6455#section-4.1

> The method of the request MUST be GET, and the HTTP version MUST be at least 1.1.
