### ISSUE TITLE
completeUpgrade Issue

### ISSUE THREAD

**Issue by GoalieSave25** [websockets/ws#1566]
In completeUpgrade for websocket-server.js, the 'open' event for the websocket is emitted before the 'connection' event for the server, so setting an open event listener on the connection event doesn't do anything

**Comment by lpinca** [comment]
Yes, this is by design. On the server, the `readyState` of a WebSocket is already `OPEN` when it is returned to the user so listening for the `'open'` event is useless.

It like listening for the `'connect'` event on a server-side `net.Socket`:

```js
'use strict';

const { createServer, connect } = require('net');

const server = createServer();

server.on('connection', function(socket) {
  socket.on('connect', function() {
    throw new Error("Unexpected 'connect' event");
  });

  console.log('server', socket.connecting);
});

server.listen(function() {
  const { port } = this.address();
  const socket = connect(port);

  console.log('client', socket.connecting);

  socket.on('connect', function() {
    console.log('client', socket.connecting);
  });
});
```
