### ISSUE TITLE
Broken in node 7

### ISSUE THREAD

**Issue by jean-emmanuel** [websockets/ws#1568]
The 7.0.0 changelog says "Dropped support for Node.js 6" although https://github.com/websockets/ws/commit/ddf0acaae43d5e5cf7f5d838bfd4350699c5406a#diff-34dddf8023c3dfb0f2c545ed6b94cbc5 breaks it in Node 7 too due to the object spread syntax being available only in version 8 and above.

**Comment by lpinca** [comment]
Node.js 7 is no longer maintained.

**Comment by lpinca** [comment]
EOL was 2017-06-30 I see no reason to keep supporting it.

**Comment by jean-emmanuel** [comment]
Fair enough !
