### ISSUE TITLE
TypeError: WS is not a constructor

### ISSUE THREAD

**Issue by limjiregister** [websockets/ws#1570]
I used webpack4.x to build the codes, and this issues happened. And then I ran the compiled file, 

I found that 'var WS = require('ws')' in mqtt.js.

WS is null. How to fixed this?

**Comment by lpinca** [comment]
Please fill the issue template and provide a way to reproduce the issue. As is the issue description is useless. I searched in https://github.com/mqttjs/MQTT.js issue tracker and found https://github.com/mqttjs/MQTT.js/issues/924. Not sure if that helps.

**Comment by 3rd-Eden** [comment]
> webpack4.x to build the codes

That means you're attempting to bundle `ws` for browsers. This module does not contain any client code, thats why it's failing.

**Comment by 3rd-Eden** [comment]
You can use the WebPack alias feature to point the `ws` to a browser polyfill. https://webpack.js.org/configuration/resolve/#resolvealias
