### ISSUE TITLE
Receiving error 400 with some Sec-Websocket-Keys, but not others

### ISSUE THREAD

**Issue by ecarhengr** [websockets/ws#1571]
#### Description

Server responds with 400 bad request for certain Sec-Websocket-Keys, while others it handles fine.

When I use a websocket tester, it creates a shorter key like this: `l5vmrdbmDwPiguohh/+uYw==`
But the device that I need to connect to the ws server, creates ones like this: 
`JCMCrKJENqcrTU9erFxGoiP5P8JhjeocERQs9vgR/Y4=`

I am testing a device from a manufacturer that is telling me that their charger works fine with other backend systems ( I can confirm this), but it's not working with mine. And I have found the issue to be with the websocket key.

So is the websocket key faulty that the device prodces, or is it an issue with the base64 encoding in ws or something?

I have noticed that the ones that work, have two equals signs (=) and that one example that does not work, only has one.

#### Reproducible in:

- version: 1.0.28
- Node.js version(s): 10.15.3
- OS version(s): Windows 10, Ubuntu 18.04

#### Steps to reproduce:

1. Make ws server (from readme example, for example)

2. Start connection to server with websocket key: JCMCrKJENqcrTU9erFxGoiP5P8JhjeocERQs9vgR/Y4=

3. Server responds with error 400

#### Expected result:

Connection would be succesful

#### Actual result:

Connection fails with HTTP 400

Received: 
HTTP/1.1 400 Bad Request
Connection: close
Content-type: text/html
Content-Length: 11

**Comment by ecarhengr** [comment]
Someone please correct me if I am wrong, but the long key is 32 bits, when it should be 16.

So that means that the device is generating an incorrect key?

**Comment by rgawenda** [comment]
The equal signs at the end of base64 are a padding thing IIRC, and yes, they seem to be using a 32bit nonce.
Check https://github.com/websockets/ws/issues/1560

**Comment by ecarhengr** [comment]
Thanks @rgawenda 

I had a look at #1560 and what I gathered is that only 16 bit keys are valid. Is this correct?

So essentially I should be telling the device manufacturer to fix it? Or is there a way to accept the keys that it generates, though I didn't find an option to do this

**Comment by lpinca** [comment]
You can use an older version of `ws`, 6.1.4 should accept incorrect keys.

**Comment by ecarhengr** [comment]
Thank you! Exactly what I needed
