### ISSUE TITLE
Connection hangs on falsy verifyClient result

### ISSUE THREAD

**Issue by JozefFlakus** [websockets/ws#1572]
#### Description

At the beginning, I have to say - many thanks for this library. `ws` is the lib of choice and was integrated exclusively with Marble.js framework. 💪

The issue is very strange because suddenly it started to occur. The problem is probably with refusing a connection inside `verifyClient` method. If the `verifyClient` method refuses connection then the client hangs and timeouts after some time. An interesting fact is that it occurs even in the simple `ws` server. I typically tested it on Chrome browsers (via some client extensions) and one week ago it worked properly. To be honest I'm not sure if some Chrome update introduced some breaking changes to the WebSocket communication during the handshake phase 🤔

#### Reproducible in:

- version: 7.0.0 (tested also on 6.x.x)
- Node.js version(s): 10.15.0
- OS version(s): macOS
- browser client (Chrome 74.0.3729.169)

#### Steps to reproduce:

```typescript
import * as WebSocket from 'ws';

const ws = new WebSocket.Server({
  port: 8080,
  host: '127.0.0.1',
  verifyClient: (info, cb) => cb(false),
});

ws.on('connection', () => {
  console.log('connected');
});
```

#### Expected result:

- the connection is refused (a proper error is triggered)

#### Actual result:

- the connection hangs and timeouts after some time

#### Attachments:

<img width="821" alt="Zrzut ekranu 2019-05-24 o 20 28 14" src="https://user-images.githubusercontent.com/7793430/58349029-7ff26e80-7e62-11e9-86f1-19c3e446ced6.png">

**Comment by lpinca** [comment]
I can't reproduce with Chrome 74.0.3729.169 on macOS.

```js
'use strict';

const http = require('http');
const WebSocket = require('ws');

const data = `<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
  </head>
  <body>
    <script>
      (function () {
        var ws = new WebSocket('ws://localhost:8080');

        ws.onopen = function () {
          console.log('open');
        };
      })();
    </script>
  </body>
</html>`;

const server = http.createServer();

server.on('request', function(req, res) {
  res.setHeader('Content-Type', 'text/html');
  res.end(data);
});

const wss = new WebSocket.Server({
  server,
  verifyClient(info, cb) {
    cb(false);
  }
});

wss.on('connection', function() {
  console.log('connected');
});

server.listen(8080, function() {
  console.log('Server listening on [::]:8080');
});
```

<img width="857" alt="Screenshot 2019-05-25 at 08 35 49" src="https://user-images.githubusercontent.com/1443911/58365684-2755bc80-7ec8-11e9-8fdd-cc28e9c43e23.png">

**Comment by JozefFlakus** [comment]
It turned out that some extension that was installed interfered with WebSocket connection. The strangest thing is that it only occurred when then the connection was refused.

Anyway, now it works. Thanks again @lpinca!

**Comment by lpinca** [comment]
Anyway, my suggestion is to not use the `verifyClient` hook, see https://github.com/websockets/ws/issues/377#issuecomment-462152231.
