### ISSUE TITLE
handshakeTimeout error code

### ISSUE THREAD

**Issue by WuerfelDev** [websockets/ws#1574]
- [ X ] I've searched for any related issues and avoided creating a duplicate
      issue.

#### Description

I'm writing a Websocket client. When a connection fails I used to received the err.code `ETIMEDOUT` in my `myws.on('error', function error(err){  }`
Now I added `handshakeTimeout` to the request and the err.code is now undefined. This is because err is returning the error stack. 

#### Reproducible in:

- version: 7.0.0
- Node.js version(s): v10.15.3
- OS version(s): Ubuntu 18.04

#### Steps to reproduce:

1. Set up a Websocket client to a connection that will produce `ETIMEDOUT` 

2. add option `handshakeTimeout` to the request

3. in on error function print out err or err.code

#### Expected result:

I want err.code to be `ETIMEDOUT`

#### Actual result:

Its undefined because err itself is an error stack

**Comment by lpinca** [comment]
The error that is emitted when the handshake timeout expires never had a `code` property.
You are probably confusing it with the error emitted by the https://nodejs.org/api/http.html#http_http_request_options_callback that we reemit on the WebSocket but that is a different error.

**Comment by WuerfelDev** [comment]
Hi @lpinca 
My problem is that I need to get the err.code `ETIMEDOUT` to know if the timeout was reached. How else can I know what caused the error

As said here https://github.com/websockets/ws/blob/master/doc/ws.md#new-websocketaddress-protocols-options I can also use the options from `http_request` function. Do I get it right that if I set the handshakeTimeout it effectively sets a regular timeout?https://github.com/websockets/ws/blob/911bb6fb1145c9b09ae4b1cf4c993b3b8ce9e1cf/lib/websocket.js#L508

I wonder why it isnt the same then:
handshakeTimeout is giving the error stack
timeout is returning a `ETIMEDOUT` as err.code but this also doesn't set a timeout, it stays at default

**Comment by lpinca** [comment]
> My problem is that I need to get the err.code `ETIMEDOUT` to know if the timeout was reached

I get it but you don't get `ETIMEOUT` by using the `handshakeTimeout` timeout we never add codes to our errors.

> Do I get it right that if I set the handshakeTimeout it effectively sets a regular timeout?

Yes, but the `timeout` option is overridden, so if you use it is ignored. https://github.com/websockets/ws/blob/911bb6fb1145c9b09ae4b1cf4c993b3b8ce9e1cf/lib/websocket.js#L456

The following is what `ws` does under the hood.

```js
'use strict';

const { get } = require('http');

const request = get({
  host: '192.0.2.1', // Non routable IP address.
  timeout: 1000 // Try to comment this option and you get the code you want.
});

request.on('timeout', function() {
  // This listener is never called if the timeout option is not set. Keep in
  // mind that using `timeout: <number>` in `ws` is like setting it to
  // `undefined`.
  request.abort();

  // We emit the `'error'` event on the WebSocket instance with our error here.
  console.error(new Error('Opening handshake has timed out'));
});

request.on('error', function(err) {
  if (request.aborted) return;

  // We emit the `'error'` event on the WebSocket instance with the original
  // error.
  console.log(err);
});
```

**Comment by WuerfelDev** [comment]
what is the use of the handshakeTimeout option? I mean it does the same only returns a different error. Why isn't timeout simply passed like other options?

**Comment by lpinca** [comment]
> I mean it does the same only returns a different error.

No, it's like `timeout` but it is user responsibility to handle the [`'timeout'`](https://nodejs.org/api/http.html#http_event_timeout) event when the `timeout` option is set. `handshakeTimeout` handles the `'timeout'` event, abort the request and emits the an error in all cases. When using the `'timeout'` option you might get no error or a "socket hang up" error with code `ECONNRESET`.

The error code you want (`ETIMEOUT`) occurs when the TCP connection cannot be established and not when the socket times out due to inactivity. It's a different error.

**Comment by lpinca** [comment]
Also `handshakeTimeout` existed before we allowed all `http.request()` options to be used.

**Comment by WuerfelDev** [comment]
Thanks, i understand. Too bad i cannot identify the cause in my code. Could be a new feature?!

**Comment by lpinca** [comment]
If you can share a reproducible test case I can take a look at it.

**Comment by WuerfelDev** [comment]
```node
const WebSocket = require('ws');

var myws = new WebSocket("ws://192.168.178.44/ws", { handshakeTimeout: 2000 });
myws.on('error', function error(err){
    console.log("Error: "+err.code);
    myws.close();
});

myws.on('open', function open() {
    console.log("CONNECTED");
    myws.close();
});
```

The only possibility to know is to match err against that string which is not a nice way

**Comment by lpinca** [comment]
> The only possibility to know is to match err against that string which is not a nice way

Yes there is no proper way to differentiate errors other than comparing against the error message (err.message). By the way we consider changes to error messages semver-major and `err.code` when present is still a string.

**Comment by malei0311** [comment]
handshakeTimeout not work
```
var myws = new WebSocket("ws://192.168.178.44/ws", { handshakeTimeout: 50 });
myws.on('error', function error(err){
    console.log("Error: "+err.code);
    myws.close();
});

const start = Date.now()
myws.on('open', function open() {
    console.log("CONNECTED", Date.now() - start);
    myws.close();
});
```

result

```
CONNECTED 5128
```

**Comment by zoneix** [comment]
Can't seem to get { handshakeTimeout: x } to work at all when using secure web sockets. Any ideas?

**Comment by Arubinu** [comment]
Not having found a solution either, I went through a `setTimeout` which destroys everything has been reached and therefore a `clearTimeout` in the other cases.
