### ISSUE TITLE
Please help me nodejs server via websocket

### ISSUE THREAD

**Issue by TemKaSD** [websockets/ws#1575]
my code:

var WebSocketServer = new require('ws');
var clients = {};
var webSocketServer = new WebSocketServer.Server({ port: process.argv[2] });

webSocketServer.on('connection', function(ws) {
  var id = Math.random();
  clients[id] = ws;

  console.log("Новое соединение " + id);

  ws.on('message', function(message) {
    console.log('Получено сообщение ' + message);

    for (var key in clients) {
      clients[key].send(message);
    }
  });

  ws.on('close', function() {
    console.log('Соединение закрыто ' + id);
    delete clients[id];
  });
});

Me need add https ws. Help pls.

**Comment by lpinca** [comment]
First line is wrong.

```js
var WebSocketServer = new require('ws');
```

it should be

```js
var WebSocketServer = require('ws');
```

**Comment by TemKaSD** [comment]
thx.

Now i connect: site.com/ghost/

/ghost/ - location nginx.

`		location /ghost/ {
			if ( $http_upgrade != "websocket" ) 
				{
					return 400; 
				}
				proxy_pass http://127.0.0.1:3600;
				proxy_http_version 1.1;
				proxy_set_header Upgrade $http_upgrade;
				proxy_set_header Connection "upgrade";
				proxy_set_header Sec-WebSocket-Key $http_sec_websocket_key;
				proxy_set_header Sec-WebSocket-Version $http_sec_websocket_version;
				proxy_set_header Sec-WebSocket-Protocol $http_sec_websocket_protocol;
				proxy_set_header X-Forwarded-For $remote_addr;
				proxy_set_header X-Frowarded-Https $https;
		}`

Its work.

-----------
I want to make it automated, without nginx config.

site.com:3600

![Screenshot_1](https://user-images.githubusercontent.com/6318282/58754314-86db4a00-8510-11e9-956f-efdfde242167.jpg)

**Comment by lpinca** [comment]
You have to solve it yourself, sorry. This issue tracker is only for bugs in the library. No general support. You might have more luck on StackOverflow.
