### ISSUE TITLE
.DS_Store in installed lib

### ISSUE THREAD

**Issue by OrangeDog** [websockets/ws#1577]
`npm install ws@3.3.3` creates the file `node_modules/ws/lib/.DS_Store`

I'm not using macOS so I'm pretty sure it's not at my end.

**Comment by lpinca** [comment]
It was probably added in the npm package due to this bug https://npm.community/t/ds-store-files-show-up-after-npm-publish/831.

**Comment by lpinca** [comment]
Anyway it doesn't cause any harm.

**Comment by 3rd-Eden** [comment]
Also `ws@3.3.3` is pretty old, you should consider upgrading :)

**Comment by OrangeDog** [comment]
Ah I see, sorry for the pointless report.
It's buried somewhere deep in my dependency tree.
