### ISSUE TITLE
前端用手机连接的时候报错

### ISSUE THREAD

**Issue by CQzhangshuai** [websockets/ws#1582]
前端在pc上面连接是正常的？但是在手机上面连接的时候会报错 报错内容是
isTrusted:true

**Comment by lpinca** [comment]
Sorry, I don't know Chinese.

**Comment by CQzhangshuai** [comment]
I'm sorry ,I speak English

**Comment by CQzhangshuai** [comment]
前端在电脑上面连接是正常的？但是在手机上面连接的时候会报错 报错内容是
isTrusted:true

**Comment by CQzhangshuai** [comment]
Is the front end connected to the computer normal?But when connected to the phone, the error message is
IsTrusted: true,

**Comment by lpinca** [comment]
I have no idea, can you please write here a test case to reproduce the issue? Are you sure the error message is coming from ws?

**Comment by CQzhangshuai** [comment]
thank you for your help,i already solve,it's nginx

**Comment by lpinca** [comment]
Ok, I'm closing then.

**Comment by bqcuong** [comment]
@CQzhangshuai could you share your solution? I encountered the same problem with nginx. Client doesn't connect to the WebSocket server on Android.
