### ISSUE TITLE
Stops auto refreshing if the page remains idle for certain time.

### ISSUE THREAD

**Issue by patelveep** [websockets/ws#1585]
We are using the super socket WebSocket library in our project but facing the auto-refreshing issue from last month.
If I am keeping my site page idle for more then half an hour it stops auto-refreshing it shows the WebSocket is connected. 
Maybe cannot get messages from the server to the client side or something else not able to identify it. Any guidance would be really appreciated!

**Comment by lpinca** [comment]
I have no idea what the super socket WebSocket library is. You can use this example https://github.com/websockets/ws#how-to-detect-and-close-broken-connections as a reference to close unresponsive connections.

P.S. The issue template is there for a reason, please fill it.

**Comment by lpinca** [comment]
It seems SuperWebSocket  is .NET implementation of a WebSocket server and you already opened the same issue in that project issue tracker: https://github.com/kerryjiang/SuperWebSocket/issues/53.

Closing as I can't see how this is related to ws.
