### ISSUE TITLE
Samples on npmjs.com does not match examples in repo

### ISSUE THREAD

**Issue by dmitryrn** [websockets/ws#1586]
I killed two hours trying to get message with `ws.on('event', callback)` but then I see API and examples in repo and realise I need to use `ws.onmessage = cb`...

**Comment by 3rd-Eden** [comment]
The examples are fine. You're just a browser based WebSocket. The code on NPM, which is a mirror of the README are working just fine.

**Comment by 3rd-Eden** [comment]
If you feel strongly about this being an issue, you're more than welcome to create a PR that clarifies this behaviour.
