### ISSUE TITLE
how to disable perMessageDeflate on the client, if it is created on the native webSocket?

### ISSUE THREAD

**Issue by Shub1nk** [websockets/ws#1592]
Hello!

Faced such a problem. The error periodically occurs, but I can not find its solutions. It turns out that the client starts sending a compressed message, but there was no handshake with the server, so the connection is broken.

On the server, the 'ws' library is used, and on the client is the native new Websocket

server
`
const WebSocket = require('ws');
...
const wsServer = new WebSocket.Server({server : httpServer});
`
client
`
const ws = new WebSocket(`ws${settings.isSecured?"s":""}://${settings.IP}:${settings.PORT||9000}/${settings.PATH?settings.PATH:""}`);
`
On the default server, perMessageDeflate is disabled and enabled on the client.

How can this problem be solved?

`
1|www    | ManagerController::triggerBefore()
     
1|www    | QueueManager::idWs(): auth new user m24  
1|www    | QueueManager::joinManager(): manager m24 joined  
1|www    | RangeError: Invalid WebSocket frame: RSV1 must be clear  
1|www    |     at Receiver.getInfo (/opt/node-v8.12.0/projects/cityapp_backend/node_modules/ws/lib/receiver.js:167:14)   
1|www    |     at Receiver.startLoop (/opt/node-v8.12.0/projects/cityapp_backend/node_modules/ws/lib/receiver.js:121:22)  
1|www    |     at Receiver._write (/opt/node-v8.12.0/projects/cityapp_backend/node_modules/ws/lib/receiver.js:69:10)  
1|www    |     at doWrite (_stream_writable.js:396:12)1|www    |     at writeOrBuffer (_stream_writable.js:382:5)  
1|www    |     at Receiver.Writable.write (_stream_writable.js:290:11)  
1|www    |     at Socket.socketOnData (/opt/node-v8.12.0/projects/cityapp_backend/node_modules/ws/lib/websocket.js:794:35)  
1|www    |     at emitOne (events.js:116:13)  
1|www    |     at Socket.emit (events.js:211:7)  
1|www    |     at addChunk (_stream_readable.js:263:12)`

**Comment by lpinca** [comment]
The extension is negotiated and if the server does not support is the client will not use it unless the client is bugged. If it is there is not much you can do just ignore the error.

**Comment by Shub1nk** [comment]
This error sometimes occurs because of it the server crashes. As a result, on the client side, we see a permanent connection and then a disconnection.

How can you prevent server crash?
Will something like this help me:
`ws.on('error', error => {console.log("Websocket crashed with error:", error)});
`
or is it worth trying perMessageDeflate?

**Comment by lpinca** [comment]
Yes, add an `'error'` listener to the `WebSocket` instance.

**Comment by Shub1nk** [comment]
How can imitate the error `RSV1 must be clear` to check the listener's `error`?

I've seen code sample somewhere, but I can't find

**Comment by lpinca** [comment]
Send something like this. It should work.

```js
ws._socket.write(Buffer.from('C200', 'hex'));
```

**Comment by Shub1nk** [comment]
![image](https://user-images.githubusercontent.com/4961851/59766203-16c31700-92b9-11e9-85cc-1d41eca0f881.png)

For the test created 2 wss.
1 - normal
2 - sends data to create an error with RSV1

Added an error listener and the server stopped crashing. wss1 disables only channels that send compressed data frames.

**Comment by lpinca** [comment]
Whatever works for you.

**Comment by Shub1nk** [comment]
Thanks for your help
