### ISSUE TITLE
wss.handleUpgrade callback add "this" context

### ISSUE THREAD

**Issue by mStirner** [websockets/ws#1593]
Is it possible to add in any future release a "this" context to the callback in ```wss.handleUpgrade()``` ?

https://github.com/websockets/ws/blob/master/lib/websocket-server.js#L321

Change from
```js
cb(ws);
````
to
```js
cb.call(this, ws);
```

**Comment by lpinca** [comment]
We could but it would be the websocket server to which you probably have already access. Also what's wrong with `Function.prototype.bind()` if you need a custom context?

**Comment by mStirner** [comment]
I use something like this in my express route
```js
 req.wss.handleUpgrade(req, req.socket, req.headers, function done(ws) {

  //console.log(this)
  req.wss.emit("connection", ws, req);

});
```

and it would be nice and shorter with ```this.emit(...)```

**Comment by lpinca** [comment]
To be honest it doesn't seem a very compelling reason. You could do something like this

```js
const { wss, socket, headers } =  req;
wss.handleUpgrade(req, socket, headers, function done(ws) {
  wss.emit("connection", ws, req);
});
```

and it would be even shorter.

Or with `Function.prototype.bind()`

```js
req.wss.handleUpgrade(req, req.socket, req.headers, function done(ws) {
  this.emit("connection", ws, req);
}.bind(wss));
```

**Comment by lpinca** [comment]
I'm closing this. Discussion can continue if needed.
