### ISSUE TITLE
Not able to upload file more than 300 MB

### ISSUE THREAD

**Issue by sathishkumarece** [websockets/ws#1594]
- [x] I've searched for any related issues and avoided creating a duplicate
      issue.

#### Description

I am not able to upload file from Chrome client to Node js server if size is more than 300MB.
I have added max payload of 800MB eventhough I am not able to.

Is there any limitation?
How I can over come this limitation?

#### Reproducible in:

- version: 7.0.1
- Node.js version(s): V8.11.2
- OS version(s): Windows 7

#### Steps to reproduce:

1.

2.

3.

**Comment by lpinca** [comment]
> Is there any limitation?

No, there is not. Try with the Node.js client (ws). It might be a limit set by the client (Chrome in this case.)

> How I can over come this limitation?

Split the file in multiple pieces.

**Comment by sathishkumarece** [comment]
Hello Ipinca,

Thanks for your quick response.

Actually I have tried from WS Client. Please find below the configuration I have used for it
WS client:
var ws = new WebSocket("ws://localhost"));

WS Server:
var options = {}
  options.maxPayload = 800 * 1024 * 1024
  options.port = port
var wss = new WebSocket.Server(options)

Kindly let me know if more information is required.
It will be great if I some point of direction to proceed further.

**Comment by lpinca** [comment]
Just send the message from the client.

```js
const buf = Buffer.alloc(300 * 1024 * 1024);

ws.on('open', function() {
  ws.send(buf);
})
```

Anyway in https://github.com/websockets/ws/blob/d9b5562e/bench/speed.js there is a case with a 500 MiB message sent from the client to the server and back to client so we already know it works.

**Comment by lpinca** [comment]
I'm closing as answered. Discussion can continue if needed.

**Comment by JeroenMBooij** [comment]
@lpinca Where can I find an example on how to send and receive files through a websocket?

**Comment by lpinca** [comment]
Here is an example using the streaming interface. Useful to send and receive big files and keep memory usage under control. The example creates a copy of the script source file.

```js
const fs = require('fs');
const path = require('path');
const WebSocket = require('ws');

const server = new WebSocket.Server({ port: 0 }, function () {
  const ws = new WebSocket(`ws://localhost:${server.address().port}`);
  const websocketStream = WebSocket.createWebSocketStream(ws);

  function resume() {
    websocketStream.resume();
  }

  let filename;
  let size;
  let bytesRead = 0;
  let fileStream;

  websocketStream.on('data', function (chunk) {
    if (!fileStream) {
      ({ filename, size } = JSON.parse(chunk.toString()));
      fileStream = fs.createWriteStream(`copy_${filename}`);
    } else {
      bytesRead += chunk.length;

      if (!fileStream.write(chunk)) {
        websocketStream.pause();
        fileStream.on('drain', resume);
      }

      if (bytesRead === size) {
        fileStream.end();
        fileStream = null;
        bytesRead = 0;
        console.log('done');
      }
    }
  });
});

server.on('connection', function (ws) {
  const websocketStream = WebSocket.createWebSocketStream(ws, {
    decodeStrings: false
  });

  fs.stat(__filename, function (err, stats) {
    websocketStream.write(
      JSON.stringify({ filename: path.basename(__filename), size: stats.size })
    );

    const fileStream = fs.createReadStream(__filename);
    fileStream.pipe(websocketStream, { end: false });
  });
});
```

For small files it might be easier to read the whole file in a `Buffer` and send/receive it as a single WebSocket message.
