### ISSUE TITLE
WebSocket.terminate() vs WebSocket.close()

### ISSUE THREAD

**Issue by goktugyil** [websockets/ws#1596]
On readme: 
`  // Use `WebSocket#terminate()` and not `WebSocket#close()`.`

There is this line. But it does not explain why, and I dived into the codebase and the issues but still could not find a reason. Can we include this information somewhere?

**Comment by lpinca** [comment]
`ws.terminate()` immediately destroys the connection, `ws.close()` waits for close timer to expire before destroying the connection if the other peer is not responsive.

Technically both can be used but `ws.terminate()` is better in that example (you don't want to wait another 30 sec before the websocket emits the `'close'` event). Feel free to open a PR.
