### ISSUE TITLE
502 from the load balancer crashes the app (invalid ws status code)

### ISSUE THREAD

**Issue by alinalexa** [websockets/ws#1605]
- [x] I've searched for any related issues and avoided creating a duplicate
      issue.

#### Description

Receiving 502 status code from the load balancer set in front of the ws server crashes the ws client app .

#### Reproducible in:

- version:
- Node.js version(s):
- OS version(s):

#### Steps to reproduce:

```
    const WebSocket = require('ws');
    const ws = new WebSocket(url);

    ws.on('open', onOpen);
    ws.on('close', onClose);
    ws.on('message', onMessage);
```
the ws server i am connection to has some network problems and it responds with 502 from time to time. this translates into a crash on the client 

#### Expected result:

handle the exception somehow (reopen the connection)

#### Attachments:

https://pasteboard.co/Intf3Ds.png - sorry for the image, this was sent to the client and i can't crash it again to copy/paste the error.

**Comment by lpinca** [comment]
Add a listener for the `'error'`or [`'unexpected-response'`](https://github.com/websockets/ws/blob/master/doc/ws.md#event-unexpected-response) event.
