### ISSUE TITLE
WS 7.1.1 object spread fails on nodejs 6.x

### ISSUE THREAD

**Issue by FreshXOpenSource** [websockets/ws#1607]
- [x] I've searched for any related issues and avoided creating a duplicate
      issue.

#### Description

Using a project with nodejs 6.x (tested 6.11 and latest 6.17.1) fails importing websocket.js

```bash
# node actor.js
/opt/melnor2home/node_modules/ws/lib/websocket.js:347
      ...options
      ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/opt/melnor2home/node_modules/ws/index.js:3:19)
```
#### Reproducible in:

- version: 7.1.1
- Node.js version(s): 6.11.3 / 6.17.1
- OS version(s): Linux (FC30) / MacOS (Mojave 10.14.3)

#### Steps to reproduce:

1. use nodejs 6.x to `require('ws');`

2.

3.

#### Expected result:

require works

#### Actual result:

```
/opt/melnor2home/node_modules/ws/lib/websocket.js:347
      ...options
      ^^^

SyntaxError: Unexpected token ...```

#### Attachments:

maybe related to https://stackoverflow.com/questions/40066731/node-v6-failing-on-object-spread

**Comment by lpinca** [comment]
https://github.com/websockets/ws/releases/tag/7.0.0

**Comment by tabirkeland** [comment]
I am still seeing this issue with Node `v8.11.2`

**Comment by Yarilo** [comment]
@tabirkeland Looking into this for a while as I was facing the same issue, it seems that `v8.2.1` did not support object spread syntax unless a flag (`--harmony`) is used (as per https://node.green)

**Comment by nsgundy** [comment]
Just ran into this well (was updating socket.io dependency), running with node 6.x. Could the `engine` property be added to `package.json` to clearly state that some nodejs `8.x` is the minimum version?
