### ISSUE TITLE
Unhandled exception with invalid control message

### ISSUE THREAD

**Issue by bmancini55** [websockets/ws#1611]
- [x] I've searched for any related issues and avoided creating a duplicate
      issue.

#### Description

I'm periodically receiving the unhandled exception below. Connections to this same socket server work 99% of the time.

```
     Uncaught RangeError: Invalid WebSocket frame: invalid status code 1005
      at Receiver.controlMessage (node_modules/ws/lib/receiver.js:449:18)
      at Receiver.getData (node_modules/ws/lib/receiver.js:335:42)
      at Receiver.startLoop (node_modules/ws/lib/receiver.js:138:22)
      at Receiver._write (node_modules/ws/lib/receiver.js:74:10)
      at doWrite (_stream_writable.js:415:12)
      at writeOrBuffer (_stream_writable.js:399:5)
      at Receiver.Writable.write (_stream_writable.js:299:11)
      at TLSSocket.socketOnData (node_modules/ws/lib/websocket.js:875:35)
      at addChunk (_stream_readable.js:288:12)
      at readableAddChunk (_stream_readable.js:269:11)
      at TLSSocket.Readable.push (_stream_readable.js:224:10)
      at TLSWrap.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
```

My calling code has an error handler similar to below:
```javascript
let wss = new WebSocket(wssPath, { perMessageDeflate: false });
wss.on("error", err => {});
wss.on("message", msg => {});
``` 

This seems to be an internal error in this library. I took an exploratory look at addressing the issue and adding a try/catch to socketOnData in websocket.js.  This appeared to resolve the issue, though I'm not sure if that's the most appropriate place for a fix.

#### Reproducible in:

- version: 7.1.1
- Node.js version(s): 10.16
- OS version(s): MacOS

#### Steps to reproduce:

I'm seeing this error as part of the CCXWS library that handles web socket connections to cryptocurrency exchanges. I'd be happy to provide some sample code if it's helpful.  This error occurs when there is a reconnection event for the Binance client.  

#### Expected result:

Error is emitted to calling handler.

#### Actual result:

Unhandled exception cause process failure.

**Comment by lpinca** [comment]
Try to figure out why your `WebSocket` object does not have an `'error'` listener when this https://github.com/websockets/ws/blob/91b5173c776881dc1a229ac5b0ba928dcb775602/lib/websocket.js#L780 is emitted.

**Comment by bmancini55** [comment]
Well I'm a total numpty.  Prior to calling close we over aggressively clear all listeners to prevent triggering reconnection logic. 

Thanks for the assist and apologies for wasting your time. Closing the issue.

**Comment by goktugyil** [comment]
> Well I'm a total numpty. Prior to calling close we over aggressively clear all listeners to prevent triggering reconnection logic.
> 
> Thanks for the assist and apologies for wasting your time. Closing the issue.

How do you clear all listners and what did you do to solve this?

**Comment by goktugyil** [comment]
Context:
<img width="533" alt="Screen Shot 2021-07-05 at 12 46 19" src="https://user-images.githubusercontent.com/5816878/124452378-00e4f980-dd8f-11eb-87b2-8ad69dd88b75.png">

I randomly got this. Over millions of socket connection, this just randomly happened and nothing changed recently. 

I am also listening to:
```ts
this.socketServer = new ws.Server({server: expressServer})
socket.on('message', (message, error) => {
socket.on('error', (error) => {
```

And have no idea how to debug why the `error` listener could be disabled?

**Comment by arpowers** [comment]
I am also randomly getting the `22373` socket error. Crashes the ingest server for us as it's uncaught

**Comment by goktugyil** [comment]
> I am also randomly getting the `22373` socket error. Crashes the ingest server for us as it's uncaught

Same here. Did you find any leads?

**Comment by arpowers** [comment]
Ya here's the story

https://github.com/websockets/ws/issues/1922
