### ISSUE TITLE
intellisense

### ISSUE THREAD

**Issue by sneels** [websockets/ws#1614]
Not an issue, this can be closed and removed as soon as it's seen.
I've tried stackoverflow to no avail... I have a package I created that was published to npmjs and the code works, but when I install it in another project I am not getting any intellisense from it, this happens with some packages, but I've noticed the intellisense works fine with ws.

I am using this as a way to reach out to see if @lpinca or some other dev would be willing to open a line of contact outside of github (mail me at stijn.neels@fracarita.org)

Thanks in advance

**Comment by lpinca** [comment]
I've seen it and I have no clue, I don't use VS Code :)

**Comment by sneels** [comment]
Neither am I, I'm using Visual Studio, same difference I guess. Thanks anyway!
