### ISSUE TITLE
Write the library in TypeScript

### ISSUE THREAD

**Issue by ORESoftware** [websockets/ws#1623]
I am looking for a WebSockets library written in TypeScript

https://www.quora.com/unanswered/Is-there-a-Websocket-library-for-Node-js-written-in-TypeScript

it looks like `@types/ws` exists, but since it's packaged separately, often the types become out-of-sync.

**Comment by ORESoftware** [comment]
case in point, latest version of the types is: `@types/ws@6.0.3`, latest version of the lib is 7.x.

**Comment by lpinca** [comment]
No thanks. https://twitter.com/mikeal/status/1150791274053505024

**Comment by ORESoftware** [comment]
@lpinca that thread is about writing @types/ws which already exists. I am talking about writing the library itself in TS.

I looked at the codebase. All you have to do is transpile src to lib:

src -> lib

using TS, it's easy to do

**Comment by lpinca** [comment]
I don't want to rewrite the lib in TypeScript, maintain type definitions, and add any additional transpile step, sorry.

**Comment by shobhitg** [comment]
I respect the choice of not adding work to re-implement the library in typescript. But just wanted to correct that if the all the code is re-written in typescript, then there is no need to maintain type definitions separately.

**Comment by ORESoftware** [comment]
its possible that TS can target WebAssembly, so it might be a good idea :-)

**Comment by beary** [comment]
> I respect the choice of not adding work to re-implement the library in typescript. But just wanted to correct that if the all the code is re-written in typescript, then there is no need to maintain type definitions separately.

Yes, type definitions will be generated automatically at compile time. Just write ts and run `tsc` is enough. This library does not depend on other libraries, it should not be difficult to write using TypeScript, maybe I can have a try if I'm free.
