### ISSUE TITLE
Error in line 347 in server/node_modules/ws/lib/websocket.js

### ISSUE THREAD

**Issue by shinchan33** [websockets/ws#1624]
- [x] I've searched for any related issues and avoided creating a duplicate
      issue.

#### Description
/home/xyz/public_html/server/node_modules/ws/lib/websocket.js:347
      ...options
      ^^^
SyntaxError: Unexpected token ...
    at Object.exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:513:28)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/radvisio/public_html/server/node_modules/ws/index.js:3:19)
    at Module._compile (module.js:541:32)

#### Reproducible in:

- version: 6.11.2
- Node.js version(s):6.2.2
- OS version(s):CentOS

#### Steps to reproduce:

1.

2.

3.

**Comment by lpinca** [comment]
You are probably using ws@7 and not ws@6. ws@7 no longer supports Node.js 6.

**Comment by shinchan33** [comment]
Thanks for your reply i will check the ws version and will get back to you

**Comment by shinchan33** [comment]
I have checked ws version, i am using  ws@7.1.2.
what should i do to use ws ?
I can't upgrade node beacuse i am using centOS  and on that till node@ 6.2.2  versions are supproted.

**Comment by lpinca** [comment]
Use ws@6.

**Comment by lpinca** [comment]
Closing as it's not an issue in the library.

**Comment by Xenonist** [comment]
> Use ws@6.

Can you please explain how to change the ws server version?  I have the same problem like @shinchan33

**Comment by Ulysseus** [comment]
I had a similar problem, its way you are interacting with the library. I know its not that helpful, but change your calling code and it will disappear. as @lpinca says its not a problem with the library.

**Comment by Xenonist** [comment]
> I had a similar problem, its way you are interacting with the library. I know its not that helpful, but change your calling code and it will disappear. as @lpinca says its not a problem with the library.

What do u meen by "calling code"?

**Comment by Xenonist** [comment]
In localhost it works, but on the server not...

**Comment by Ulysseus** [comment]
The javascript code, you are calling the las library from

**Comment by Xenonist** [comment]
> The javascript code, you are calling the ws library from

So what should I do? The same code works on localhost, but crashes on a server (ubuntu)
