### ISSUE TITLE
Unhandled Error: connect ECONNABORTED  in  websocket.js:554:15

### ISSUE THREAD

**Issue by starlino** [websockets/ws#1625]
I have a similar issue to #105 . Up to date on npm. Was this ever fixed and what is causing this ?? How can it be handled.

Error: connect ECONNABORTED 192.168.137.27:80
at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
Emitted 'error' event at:
at ClientRequest.req.on (C:\PROJECTS\XYZ\node_modules\ws\lib\websocket.js:554:15)
at ClientRequest.emit (events.js:198:13)
at Socket.socketErrorListener (_http_client.js:392:9)
at Socket.emit (events.js:198:13)
at emitErrorNT (internal/streams/destroy.js:91:8)
at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by lpinca** [comment]
This is most likely an issue with your server. Try with something like this and see if you get the same error:

```js
const req = http.request({
  port: serverPort,
  headers: {
    Connection: 'Upgrade',
    Upgrade: 'websocket',
    'Sec-WebSocket-Key': 'dGhlIHNhbXBsZSBub25jZQ==',
    'Sec-WebSocket-Version': 13
  }
});

req.on('error', console.error);

req.on('upgrade', function() {
  console.log('It works');
});
```

> How can it be handled.

Add a lister for the `'error'` event on the `WebSocket` instance.

**Comment by starlino** [comment]
@lpinca thank you for your reply. The solution you presented did not help in my case. I have to add that this problem happens not on connection / socket upgrade, but later  when I disable one of the Network Adapters on my computer (the WiFi Hub  on Windows 10).  The server listens on 0.0.0.0:8080  so it is bound to all IP addresses. I think once one of the IP addresses is no longer available the error is triggered inside the WebSocket code as described in my original post.
This can probably be easily reproduced / and properly handled by someone who is familiar with the code.

Below is the relevant portion of my code:

```
//initialize a simple http server
const server = http.createServer();

//start HTTP server
server.listen(process.env.PORT || 80, () => {
    console.log("Server started on  port:" + (server.address() as net.AddressInfo).port );
});

//upgrade HTTP to WebSocket server
export const wss = new WebSocket.Server({ server });

console.log("Upgraded HTTP server to WebSocket Server");

wss.on('error', (error:Error) => {
    console.error("wss error:",error);
});

wss.on('connection', (ws: WebSocket) => {
................
```

**Comment by lpinca** [comment]
From the stack trace

```
at ClientRequest.req.on (C:\PROJECTS\XYZ\node_modules\ws\lib\websocket.js:554:15)
```

you can see that error happens when during the WebSocket handshake when the upgrade request is sent and before the upgrade is complete.

**Comment by lpinca** [comment]
You can also see that error is emitted by the `net.Socket` when it tries to connect to the server: https://github.com/nodejs/node/blob/v10.16.3/lib/net.js#L1106-L1110

**Comment by starlino** [comment]
The only upgrade code I have in my code is:

```
 //upgrade HTTP to WebSocket server
 export const wss = new WebSocket.Server({ server });
```
I can't really see how I can apply your solution to my code. If the library handles the upgrade shouldn't it be the one that handles the error ?

The clients of my server are WebSocket in browser.

Can I use some kind of Global error handler , like for example I have a unhandledRejection for Promises:

```
(process as NodeJS.EventEmitter).on('unhandledRejection', function(error:Error) {
    // Will print "unhandledRejection err is not defined"
    console.warn('Unhandled Promise reject ( please use .catch() or check for bugs in event handlers ):', error);
});
```

**Comment by starlino** [comment]
Re: https://github.com/nodejs/node/blob/v10.16.3/lib/net.js#L1106-L1110

Ok who is calling **afterConnect** ? It's not like I can put a try {}  catch () around it in my code.

**Comment by lpinca** [comment]
The error you posted in the description comes from a client so you are using `ws` as a client somewhere.

Again to handle the error add a lister for the 'error' event on the WebSocket instance.

```js
const ws = new WebSocket(url);

ws.on('error', console.error);
```

Not related but you have to handle errors also on the server

```js
const wss = new WebSocket.Server({ server });

wss.on('connection', function(ws) {
  ws.on('error', console.error);
});
```

**Comment by starlino** [comment]
You're right ! it looks like the error is happening in my Client code not my server code:

However it looks like I am handling errors here as well, also all the code below is inside a promise, again that handles catch(). In worst case scenario the global error handler should handle this 

```
               //attempt to open websocket
                try{
                    this._websocket = new WebSocket('ws://'+address+'/');
                }catch(err){
                    connection_failed(__error(ICError.CONNECTION_ERROR,"Could not create socket: " + err));                    
                    return;	
                }
        
........ // Could be error happen here ????  Should I move the line below under try() ?

                this._websocket.onconnectionerror = this._websocket_onerror.bind(this);
```

**Comment by starlino** [comment]
Is this the same ? (I am not using isomorphic websockets , maybe I should ...  ?)

**ws.onconnectionerror   = console.error**
and
**ws.on('error', console.error);**

**Comment by lpinca** [comment]
No, `ws.onconnectionerror` does not exist.

**Comment by lpinca** [comment]
`ws.onerror = console.error` works.

**Comment by starlino** [comment]
: ) ok thanks. might be some very old api draft ... will update and let you know.

**Comment by lpinca** [comment]
https://github.com/websockets/ws/blob/master/doc/ws.md
