### ISSUE TITLE
heroku WSS

### ISSUE THREAD

**Issue by bryku** [websockets/ws#1627]
So i am trying to use websocket with heroku, but it is forcing me to use wss:// instead of ws://.

After diving into this I have found... well a hole lot of nothing that explains how to change from one to the other. Has anyone got this working?

After messing with this, I could just use the http:// version of the website and use the ws:// version of the websocket.  Works exactly how it is meant to, but this isn't exactly idea. While there isn't much for personal information they still have to login this way.

**Comment by lpinca** [comment]
See https://github.com/websockets/ws#external-https-server. If Heroku can be used as a SSL-terminating load balancer you do not have to change anything.

Please use another channel for general support questions. This issue tracker is only for bugs.

**Comment by bryku** [comment]
Sorry, I'm using a new terminal program and it shows this as "questions". I'm guessing from your response, it is actually "issues". Sorry for the confusion.

I did find a solution, which was similar to the link you provided.
If you are using express, you can just pass express in instead of {port: 8000}.
Express will automatically handle the keys and http / https depending on the situation.
While it is very similar to the described example, you don't have to mess with the keys, when switching between evn like localhost to production. So it makes it a bit smoother. Although, it would be pretty easy to make a function that handles that, for prototyping using express is easier even though I tend not to like it as much.

Thanks for the help either way, ws has been pretty smooth, but some more example would be helpful. Nodejs ws examples almost all go to socket.io... which is questionable itself.

**Comment by andrevenancio** [comment]
Can you provide the solution you found in a bit more detail? I'm at the same cross road as you. my application uses a hapi server, and I've build a custom hapi plugin that internally uses the [ws](https://www.npmjs.com/package/ws) module.

It works perfectly fine over http, but if the users open https and I use `wss://` then i get the following error:

`WebSocket connection to 'wss://XXXXXXXX.herokuapp.com:80/' failed: Error in connection establishment: net::ERR_SSL_PROTOCOL_ERROR`
