### ISSUE TITLE
Best way to customize WebSocket object and pass this to events

### ISSUE THREAD

**Issue by georgii-ivanov** [websockets/ws#1628]
Hello!

Is there any way to customize WebSocket object in order just add more methods/rewrite basic send method.

So I have Json web socket implementation and I need to create some subscribers on some custom actions on `WebSocket` object (not on websocket server).

For example, I'd like to implement custom send method for the socket:

```
   ws.on('connection', (socket, request) => {
          // I need also socket will contain all the methods that come from ws.WebSocket
          socket.send("cmd", "hello world");
          socket.on("cmd", (data) => {
               console.log("received cmd with data", data);
          });
   });
```

Thank you!

**Comment by lpinca** [comment]
It's up to you. You can use a custom wrapper around the `WebSocket` object or use utility functions. Whatever works for your use case and pleases you.

Please use another channel for general support question. This issue tracker is only for bugs.

**Comment by georgii-ivanov** [comment]
I like your answer. Thank you!
