### ISSUE TITLE
README: "authenticate" function not defined

### ISSUE THREAD

**Issue by nahuel** [websockets/ws#1629]
Here the `authenticate` function is not defined: https://github.com/websockets/ws/blob/master/README.md#client-authentication

It will be nice to show how to implement it, how to return a 401 error code and how to get the ws client if the authentication succeds

**Comment by lpinca** [comment]
This is done on purpose as the implementation depends on the use case. You can click the link below the snippet for a full working example.

**Comment by nahuel** [comment]
Ok, please close this issue and sorry for the inconvenience.

**Comment by lpinca** [comment]
No problem.
