### ISSUE TITLE
Reconnecting a client

### ISSUE THREAD

**Issue by nabeelio** [websockets/ws#163]
Hi,

I'm having issues with reconnecting a client - not really sure what's going on. When there's an error or close event, I do a `websocket_client = null`, and then instantiate a new client. This works, except the event listeners start to double up - so with each disconnect and subsequent reconnect, additional methods are added to the callbacks. So this obviously compounds, and when the service comes back up, there are a ton of connects and reconnects really quickly, destabilizing everything.

Looking through the code, I now try:

```
wsc.terminate();
wsc = null;

wsc = new WebSocketClient(...)
```

However, on disconnect, it will attempt one reconnection, and then throw an error:

```
ERROR:14:57:18:lib/websocket/client:on_error - Client "..." to "ws://...:35110", error: "ECONNREFUSED"
  DEBUG:14:57:18:lib/websocket/client:error - Client "..." to "ws://...:35110", retry in 1000 seconds

events.js:71
        throw arguments[1]; // Unhandled 'error' event
                       ^
Error: connect ECONNREFUSED
    at errnoException (net.js:770:11)
    at Object.afterConnect [as oncomplete] (net.js:761:19)
```

You can see on the next retry, after a second, it dies because there's no event listener attached (removeAllListeners is called), but I'm not quite understanding why. It's quite likely I'm doing this wrong. Any help would be appreciated.

**Comment by Bomper** [comment]
@CarloAl: 3+ years later, what's the current way to have a socket automatically reconnect using socket.io?

@3rd-Eden: Primus and socket.io seem overkill for the simple task of reconnecting to a websocket. What are the current thoughts on providing that functionality in ws? Other modules trying to do this, [don't always succeed](https://github.com/pladaria/reconnecting-websocket/issues/48).
