### ISSUE TITLE
Message lost due to async registration of 'on message' callback

### ISSUE THREAD

**Issue by sanji-programmer** [websockets/ws#1630]
- [X] I've searched for any related issues and avoided creating a duplicate
      issue.

#### Description

During the communication between a client and a server using ws, we noticed that some messages were lost. For some reason, we are registering the onMessage callback in an async operation. So, if a message arrives before the onMessage event is registered, this is lost. The code below shows a simplified version of the issue. 

My question is if I am violating some expected atomicity or this may be a bug? 

#### Reproducible in:

- version: ^7.1.2
- Node.js version(s): v10.16.3
- OS version(s): Ubuntu 18.04

#### Steps to reproduce:

```
const ws = require('ws');
const fs = require('fs');

let server = new ws.Server({ port: 8080 }, function () {
    let client = new ws('ws://127.0.0.1:8080');

    client.on('open', function () {
        client.send('msg 1');
        setTimeout(() => client.send('msg 2'), 100);
    });

    client.on('message', function (msg) {
        console.log(msg);
    });
});

server.on('connection', function (socket) {
    // some async operation - here is only an example
    fs.readFile('./package.json', () => {
        socket.on('message', function (msg) {  // this is the considered event 
            console.log(msg);
            socket.send('Hello from server');
        });
    });
});

setTimeout(() => { process.exit() }, 2000);
```

#### Expected result (or at least my expectation):
```
msg 1
Hello from server
msg 2
Hello from server
```
#### Actual result:
```
msg 2
Hello from server
```

**Comment by lpinca** [comment]
> For some reason, we are registering the onMessage callback in an async operation.

This is the problem and it's not a bug in `ws`. You should add a listener for the `'message'` event in the same tick where the `'connection'` event is emitted. Buffer messages if needed.

Alternatively you can pause the socket and resume it when the `'message'` listener is registered.

```js
server.on('connection', function connection(ws) {
  ws._socket.pause();
  
  doSomethingAsync(function callback() {
    ws.on('message', function message() { //
      // ...
    });
    ws._socket.resume();
  });
});
```

**Comment by sanji-programmer** [comment]
@lpinca Thank you very much for the answer. Just to summarize, the general assumption is that you should guarantee atomicity between the callback for 'connection' and the registration of event handler for 'message' event. Otherwise, you can miss messages. 

If you need to do that in some async operation, you should use pause-resume for the socket (BTW, tks it works for me). Is that right?

BTW, this is documented in somewhere in the API?

**Comment by lpinca** [comment]
Yes correct. Everything is done transparently if something like this https://github.com/websockets/ws#client-authentication is used.
