### ISSUE TITLE
Websockets inside a PM2 cluster, ok in production?

### ISSUE THREAD

**Issue by sofasurfa** [websockets/ws#1631]
**Before going to production, we want to make sure that this is an "as expected behavior".**

I have conducted an experiment by laucnhing 4 child processes using a PM2 cluster (I have 4 cores on my machine). Which means there were 4 websocket processes running...

Then on the client I created multiple sockets, and sent many messages to the server. One thing I didn't expect was that Node was able to figure out what child process the socket belonged to, meaning that every message sent by the client was console logged by the correct child process.

It seems like the main worker in the cluster keeps track of what sockets belong where.

So is this managed by Nodejs internally by the "cluster" module? Also is this ok to use in production?

**Comment by lpinca** [comment]
Yes, connection is persistent so there is no "sticky session" problem for WebSocket and the cluster module distributes incoming connections to workers using a round-robin approach.

Refs: https://nodejs.org/api/cluster.html#cluster_how_it_works

**Comment by sofasurfa** [comment]
@lpinca thank you :)

**Comment by sofasurfa** [comment]
For a more indepth answer chck out --> https://github.com/ClusterWS/ClusterWS/issues/143
