### ISSUE TITLE
Error websocket.js options

### ISSUE THREAD

**Issue by tonporaqui** [websockets/ws#1634]
Hello, when using websocket, this generates an error, I share images.

![image](https://user-images.githubusercontent.com/7048226/65521632-e5fa0b80-debf-11e9-9473-27a05b38737a.png)

![image](https://user-images.githubusercontent.com/7048226/65521588-d975b300-debf-11e9-9c03-d72f3d5d44fa.png)

tnx !!!!

**Comment by stas-ut21** [comment]
Hello
Which version of node js are you using?
This statement is not in all versions, lift the node JS version

**Comment by tonporaqui** [comment]
hi @stas-ut21, this is the somewhat old version

![image](https://user-images.githubusercontent.com/7048226/65522903-da0f4900-dec1-11e9-9dea-12fa7b14d5a5.png)

Now update me and work well, thanks

![image](https://user-images.githubusercontent.com/7048226/65524680-99fd9580-dec4-11e9-8a2e-f5badeb386a0.png)
