### ISSUE TITLE
First connection to a server has ~0.2% chance of failure

### ISSUE THREAD

**Issue by davidje13** [websockets/ws#1635]
- [x] I've searched for any related issues and avoided creating a duplicate
      issue.

#### Description

While debugging some tests which occasionally fail, I found that it is possible for a client WebSocket to fail to connect to a vanilla Node server if it is the first request the server has received (also applies when using a `ws` server but I have reduced the issue to the minimum setup). This does not happen when mimicking the client WebSocket protocol using a raw `net.Socket`. I imagine this is somehow a bug or quirk of behaviour in Node's `http` module, but it only applies when using `ws` and I'm not sure why.

Testing shows that adding a delay between starting the server and making the first request does *not* resolve the issue, so this does not appear to be a race.

I claim a ~0.2% error rate because in my testing I have typically seen ~1 error per 500 runs. If the first request succeeds, all subsequent requests to the same server also succeed (at least up to the tens of thousands).

The following code (based on https://github.com/websockets/ws/blob/master/test/websocket.test.js#L449) occasionally shows this issue:

```js
const { promisify } = require('util');
const http = require('http');
const crypto = require('crypto');
const WebSocket = require('ws');

async function runTest() {
  const server = http.createServer();
  server.once('upgrade', (req, socket) => {
    const key = crypto
      .createHash('sha1')
      .update(req.headers['sec-websocket-key'] + '258EAFA5-E914-47DA-95CA-C5AB0DC85B11')
      .digest('base64');

    socket.end(
      'HTTP/1.1 101 Switching Protocols\r\n' +
        'Upgrade: websocket\r\n' +
        'Connection: Upgrade\r\n' +
        `Sec-WebSocket-Accept: ${key}\r\n` +
        '\r\n'
    );
  });

  await promisify((cb) => server.listen(0, cb))();
  await new Promise((resolve, reject) => {
    const ws = new WebSocket(`ws://127.0.0.1:${server.address().port}/`);

    ws.on('close', resolve);
    ws.on('error', reject);
  });
  await promisify((cb) => server.close(cb))();
}

runTest();
```

#### Reproducible in:

- version: 7.1.2
- Node.js version(s): 12.9.1
- OS version(s): macOS 10.14.6

#### Steps to reproduce:

To reliably reproduce the issue, I have created a simple program which loops until the issue occurs. I usually observe issues within the first 500 iterations, and sometimes much sooner. I have experimented with setting `DELAY` as high as 1000 milliseconds, and the issue still appears.

```js
const { promisify } = require('util');
const http = require('http');
const crypto = require('crypto');
const WebSocket = require('ws');

const DELAY = 0;

function logEvents(o, prefix, eventNames) {
  eventNames.forEach((event) => {
    o.on(event, () => process.stdout.write(
      `${Date.now()} | - ${prefix}.${event}\n`,
    ));
  });
}

function runTestWS(server) {
  return new Promise((resolve, reject) => {
    const ws = new WebSocket(
      `ws://127.0.0.1:${server.address().port}/`,
      { handshakeTimeout: 5000 },
    );

    logEvents(ws, 'ws', [
      'close', 'error', 'message',
      'open', 'ping', 'pong',
      'unexpected-response', 'upgrade',
    ]);

    ws.on('close', resolve);
    ws.on('error', reject);
  });
}

async function runTest() {
  const server = http.createServer();
  logEvents(server, 'server', [
    'checkContinue', 'checkExpectation', 'clientError',
    'close', 'connect', 'connection', 'request', 'upgrade',
  ]);
  server.once('upgrade', (req, socket) => {
    const key = crypto
      .createHash('sha1')
      .update(req.headers['sec-websocket-key'] + '258EAFA5-E914-47DA-95CA-C5AB0DC85B11')
      .digest('base64');

    socket.end(
      'HTTP/1.1 101 Switching Protocols\r\n' +
        'Upgrade: websocket\r\n' +
        'Connection: Upgrade\r\n' +
        `Sec-WebSocket-Accept: ${key}\r\n` +
        '\r\n'
    );
  });

  await promisify((cb) => server.listen(0, cb))();
  if (DELAY > 0) {
    await new Promise((r) => setTimeout(r, DELAY));
  }

  await runTestWS(server);
  await promisify((cb) => server.close(cb))();
}

(async () => {
  try {
    for (let i = 0; ; i++) {
      process.stdout.write(`${Date.now()} | iteration ${i}\n`);
      await runTest();
    }
  } catch (e) {
    console.log(e);
  }
})();
```

#### Attachments:

Example output:

```
1569346465666 | iteration 0
1569346465676 | - server.connection
1569346465678 | - server.upgrade
1569346465680 | - ws.upgrade
1569346465680 | - ws.open
1569346465682 | - ws.close
1569346465683 | - server.close
1569346465683 | iteration 1
1569346465684 | - server.connection
1569346465684 | - server.upgrade
1569346465684 | - ws.upgrade
1569346465685 | - ws.open
1569346465685 | - ws.close
1569346465685 | - server.close
[...]
1569346465722 | iteration 37
1569346465722 | - server.connection
1569346465722 | - server.upgrade
1569346465723 | - ws.upgrade
1569346465723 | - ws.open
1569346465723 | - ws.close
1569346465723 | - server.close
1569346465723 | iteration 38
1569346465723 | - server.connection
1569346465723 | - server.upgrade
1569346465724 | - ws.upgrade
1569346465724 | - ws.open
1569346465724 | - ws.close
1569346465724 | - server.close
1569346465724 | iteration 39
1569346470725 | - ws.error
1569346470725 | - ws.close
Error: Opening handshake has timed out
    at ClientRequest.<anonymous> (/<project>/node_modules/ws/lib/websocket.js:545:7)
    at ClientRequest.emit (events.js:209:13)
    at Socket.emitRequestTimeout (_http_client.js:687:40)
    at Object.onceWrapper (events.js:297:20)
    at Socket.emit (events.js:209:13)
    at Socket._onTimeout (net.js:434:8)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
```

Note that on the failing iteration the server never even triggers a `connection` event. The client waits for the `handshakeTimeout` then fails with `error` and `close`.

Using the following code instead of the web socket code works every time (at least up to the tens of thousands):

```js
const net = require('net');

function runTestNet(server) {
  return new Promise((resolve, reject) => {
    const s = new net.Socket();
    s.on('close', resolve);
    s.on('error', reject);
    s.on('data', () => {});
    s.connect(server.address().port, '127.0.0.1', () => {
      s.write([
        'GET / HTTP/1.1',
        'Upgrade: websocket',
        'Connection: Upgrade',
        '',
        '',
      ].join('\r\n'));
      s.end();
    });
  });
}
```

The output follows this pattern:

```
1569346993029 | iteration 0
1569346993035 | - socket.connect
1569346993036 | - socket.ready
1569346993038 | - server.connection
1569346993039 | - server.upgrade
1569346993042 | - socket.data
1569346993042 | - socket.end
1569346993042 | - socket.close
1569346993043 | - server.close
```

**Comment by lpinca** [comment]
Did you try using only `http.get()` on the client instead of a plain `net.Socket`?

**Comment by lpinca** [comment]
Try also to change `socket.end(...)` with `socket.write(...)` and `socket.destroy()` on the server and see if behavior is still the same.

**Comment by davidje13** [comment]
@lpinca using `write` & `destroy` instead of `end` makes no difference.

I can replicate the issue using `get` as you mention. In fact, the following is enough to replicate it:

```js
const http = require('http');
const net = require('net');

const TEST_HTTP = true;

async function test() {
  const server = http.createServer();
  server.on('connection', () => {
    process.stdout.write(`${Date.now()} | - connection\n`);
  });
  server.on('upgrade', (req, socket) => {
    socket.end(
      'HTTP/1.1 101 Switching Protocols\r\n' +
        'Upgrade: websocket\r\n' +
        'Connection: Upgrade\r\n' +
        '\r\n'
    );
  });

  await new Promise((resolve) => server.listen(0, resolve));
  const { port } = server.address();

  if (TEST_HTTP) {
    await new Promise((resolve) => {
      const req = new http.ClientRequest({
        port,
        headers: {
          Connection: 'Upgrade',
          Upgrade: 'websocket'
        }
      });
      req.once('upgrade', resolve);
      req.end();
    });
  } else {
    await new Promise((resolve) => {
      const s = new net.Socket();
      s.on('close', resolve);
      s.on('data', () => {});
      s.connect(port, 'localhost', () => {
        s.write([
          'GET / HTTP/1.1',
          'Connection: Upgrade',
          'Upgrade: websocket',
          '',
          '',
        ].join('\r\n'));
        s.end();
      });
    });
  }

  await new Promise((resolve) => server.close(resolve));
}

(async () => {
  for (let i = 0; ; i++) {
    process.stdout.write(`${Date.now()} | Attempt ${i}\n`);
    await test();
  }
})();
```

if `TEST_HTTP` is set to `false`, this will use the socket version which works every time. But when `true`, it uses `http.ClientRequest` (which is [what `http.get` does internally](https://github.com/nodejs/node/blob/master/lib/http.js#L47))

This puts the bug well-and-truly into Node's territory, but I still don't know where the actual error is. I'll try to narrow it down further and report upstream.

**Comment by lpinca** [comment]
@davidje13 it seems an  ephemeral port exhaustion / connection kept in CLOSE_WAIT state issue. If I change macOS settings as per https://github.com/nodejs/node/issues/28337#issuecomment-515762218 I can no longer reproduce the issue.

**Comment by davidje13** [comment]
@lpinca any idea why that would only affect the first request to the server? In my testing, if I made a single server and many requests to it, if the first succeeded then all subsequent requests would also succeed.

I did notice another behaviour which looks like the one you reference: after many thousand requests some can get delayed, but will eventually succeed (after a few seconds). I suspect that's due to some resource being exhausted and flushing a moment later, which matches that issue.

When you say you can no-longer reproduce the issue with the change, what was your typical observation before the change? Did it jam after a few hundred iterations, or a few thousand / tens-of-thousands? For me it is very much in the hundreds (occasionally as high as 2000, but that is rare).

**Comment by lpinca** [comment]
> I did notice another behaviour which looks like the one you reference: after many thousand requests some can get delayed, but will eventually succeed (after a few seconds). I suspect that's due to some resource being exhausted and flushing a moment later, which matches that issue.

I can only reproduce this with default settings and after ~15k. I'm using an iMac pro.

**Comment by lpinca** [comment]
It is also worth nothing that I can only reproduce this on macOS. No hiccups on Windows (10 pro) and Linux (Ubuntu 18.04) with default settings.

**Comment by lpinca** [comment]
I'm closing as it does not seem to be an issue in ws.
