### ISSUE TITLE
[question] When should I use shouldHandle and when should I use the upgrade event?

### ISSUE THREAD

**Issue by aeisenberg** [websockets/ws#1637]
It looks like there are two ways of checking if a client should be handled by the WebSocketServer. The `shouldHandle` method can be overridden. Also, the `upgrade` event can be handled in the http server and explicitly call `handleUpgrade` only if appropriate.

Can you explain what the difference between these two approaches are and when I should use each approach?

Thanks!

**Comment by lpinca** [comment]
Both work, use what you like more. I would personally go with the `'upgrade'` listener + `handleUpgrade()` as it allows you to write back to the client whatever you want if the request should not be handled.

The difference is that response is written automatically when using `shouldHandle()` or the `verifyClient` hook.

**Comment by aeisenberg** [comment]
Thanks for the clarification.
