### ISSUE TITLE
Custom response headers for Websocket server

### ISSUE THREAD

**Issue by pSnehanshu** [websockets/ws#1638]
Is it possible to set custom headers for WebSocket server when upgrading a request?

**Comment by lpinca** [comment]
See https://github.com/websockets/ws/blob/master/doc/ws.md#event-headers, you can add custom headers to the `headers` array passed as an argument to the listeners of the `'upgrade'` event.

**Comment by pSnehanshu** [comment]
What if I need asynchronous process to modify headers. Will ws wait for me to finish?

**Comment by lpinca** [comment]
No, but you can use either this https://github.com/websockets/ws#client-authentication or the `verifyClient` hook. The `'headers'` will be emitter right before writing the response.

**Comment by lpinca** [comment]
Closing as answered, discussion can continue if needed.
