### ISSUE TITLE
try catch does not actually catch

### ISSUE THREAD

**Issue by jennasisis** [websockets/ws#1639]
- [x] I've searched for any related issues and avoided creating a duplicate
      issue.
**Possible related issue?** #1157 

#### Description
`try {} catch (e) {}` does not work when connecting to a websocket that does not exist.

#### Reproducible in:

- version: 7.1.2
- Node.js version(s): 10.16.3
- OS version(s): KDE Neon 5.16

#### Steps to reproduce:

1. Create a websocket connection to a server that does not exist, and wrap it in a try catch statement
```js
const Websocket = require('ws');

try {
  new Websocket('https://localhost:1337');
} catch (e) { 
  console.error('error!');
  console.error(e);
}
```

#### Expected result:
The result of the error is returned via catch, and the process does not exit
```
$ node ws.js
error!
ECONNREFUSED # (or something like that)
```

#### Actual result:
Nothing is returned.
```
$ node ws.js
$ # (no output, and the process exits)
```

**Comment by lpinca** [comment]
The connection is asynchronous. Add a listener for the `'error'` event.

```js
const WebSocket = require('ws');

const ws new WebSocket('https://localhost:1337');

ws.on('error', function(err) {
  console.error('error!');
  console.error(e.code);
});
```

**Comment by jennasisis** [comment]
Hahahahaha I forgot there was an error event. Stupid mistake.

Cheers

**Comment by bikashprusty** [comment]
Is there any way customize error object?
