### ISSUE TITLE
ws.upgradeReq.headers.cookie dosen't exist

### ISSUE THREAD

**Issue by JJLAAA** [websockets/ws#1645]
#### Description

ws.upgradeReq.headers dosen't have an attribute named 'cookie'，but before there was.What is the possible cause of this happening?

#### Reproducible in:

- version:2.3.1
- Node.js version(s): 10.16.3
- OS version(s):ubuntu 16.04

**Comment by lpinca** [comment]
I don't know. I think the cookie header is not sent? There is not enough info to give you a useful response. Do you have a way to reproduce the issue?

**Comment by JJLAAA** [comment]
The websocket request does not carry a cookie，based on the debug information from the chrome console.But there are cookie which can be shown in EditThisCookie (a chrome Plugin) on my website，i don't know why the request does not carry a cookie.

**Comment by lpinca** [comment]
Check if the cookie was set with the `secure` attribute and if your WebSocket server is running on plain HTTP. Browsers do not send secure cookies if they do not have an HTTPS connection.

**Comment by JJLAAA** [comment]
Does this mean that I have to use wss?

**Comment by lpinca** [comment]
Yes, or use a proxy to terminate the TLS connection.
