### ISSUE TITLE
how can a client close it's connection gracefully?

### ISSUE THREAD

**Issue by npomfret** [websockets/ws#1649]
I'm trying to close my client using the `.close` method and passing in a reason of 1000 (ie a  [Normal Closure](https://developer.mozilla.org/en-US/docs/Web/API/CloseEvent)).

In my `onClose` callback I use the _reason code_ to decide if or not to reopen the socket.  The intent is for anything other than a _Normal Closure_ (ie 1000) code results in the client reopening the WebSocket.

However, the _reason code_ I get in my callback if I close the connection by calling  `ws.close(1000)` is 1006 (Abnormal Closure).  Why is this?  And, what is the _right_ way to gracefully shutdown a WebSocket from the client?

**Comment by lpinca** [comment]
It depends on the server and how it closes the connection. You get a 1000 status code if the server sends a close frame with that code and that frame is received by the client.

**Comment by npomfret** [comment]
@lpinca you misunderstand.  I want my client to close the socket gracefully.

**Comment by lpinca** [comment]
Yes, it still depends on the server. What you do (calling close with status code 1000) is just the first step of the closing handshake.

**Comment by lpinca** [comment]
Closing as answered. What you are doing is correct, the status code depends on the value of the status code written in close frame if sent by the server or received by the client.
