### ISSUE TITLE
Authenticate example: the client ws connection is not terminated on logout?

### ISSUE THREAD

**Issue by AoDev** [websockets/ws#1653]
- [x] I've searched for any related issues and avoided creating a duplicate
      issue.

#### Description

I have been playing with the example [express-session-parse](https://github.com/websockets/ws/tree/master/examples/express-session-parse) to get familiar with `ws`.

In the demo, when logging out the user, it is still possible for him to send and receive messages from ws. Is this on purpose for the demo or just forgotten?
I would expect the user to be completely cut from any interaction with the websocket server.

#### Steps to reproduce:
- run the example, login, send message, logout, still can send message.

#### Expected result:
- It's not really a bug but the example is a bit confusing for a newcomer, so I guess I'd like the example to be clearer. Should one close the client connection or do something else?

#### Attachments:

*After logout, I can still communicate with the server.*

<img width="400" alt="Screen Shot 2019-10-19 at 13 56 35" src="https://user-images.githubusercontent.com/1526150/67144599-56563b80-f278-11e9-8446-ffd54544173b.png">

**Comment by lpinca** [comment]
Yes, "Simulate logout" only destroy the HTTP session. The WebSocket connection is persistent so the client is authenticated until disconnected.

I will update the example so that the WebSocket is closed on logout.

**Comment by AoDev** [comment]
Thank you :)
