### ISSUE TITLE
Socket hang up  after running for several hours

### ISSUE THREAD

**Issue by chishi2612** [websockets/ws#1657]
When i start my websocket after running for several hours, I got socket hang up on client. How could i fix this? thanks

#### Environment
- ws version: 7.1.2
- Node.js version(s): 8.10
- OS version(s): ubuntu 14.04

#### Steps to reproduce:

1. I start websocket server with ssl: 
var wss = new WebSocketServer.Server({
    server: httpsServer, perMessageDeflate: false
  });
2. I create a socket client after running for several hours, I got the socket hang up: 
var WebSocket = require('ws');
var ws = new WebSocket('host:port/');
ws.on('open', function() {
  console.log('open');
});
ws.on('error', (err) => {
  console.log('error: %s', err);
});

**Comment by lpinca** [comment]
I'll try to reproduce when I can but it does not make much sense. "socket hang up" is an error you get when the underlying socket of a HTTP request is closed with no response received. In this case the response was received and the protocol was upgraded to WebSocket.

**Comment by chishi2612** [comment]
Thanks for replying @lpinca. 
I send my detail stack:

    at TLSSocket.onHangUp (_tls_wrap.js:1137:19)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at TLSSocket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  code: 'ECONNRESET',
  path: undefined,
  host: 'xxx',
  port: 'xxxx',
  localAddress: undefined }

I don't handle a HTTP Upgrade request in my code. is it the reason?
I try restart websocket server, then after 6 hours, it got socket hang up and any websocket client can't connect to server.
Do you have a idea to debug or fix this? 

Thanks

**Comment by chishi2612** [comment]
I'm sure that 'open' event is not emitted yet when new clients connect. Do you think the reason is at server or client?

**Comment by lpinca** [comment]
> I'm sure that 'open' event is not emitted yet when new clients connect.

Yes, but is the error is emitted on new clients not existing ones already connected, right? If so it is expected and is a server error but I don't know why it happens. The issue may be caused by resource exhaustion, a broken proxy, etc. Too many variables.

**Comment by chishi2612** [comment]
how many ESTABLISHED connections is maximum in server?
I check logs from server: 

> ALL TCP Connections Count: 
>       5 FIN_WAIT1
>    2496 ESTABLISHED
>       1 SYN_RECV
>       1 Foreign
>       1 established)
>      12 LISTEN

**Comment by lpinca** [comment]
It depends on your server resources and configuration.

**Comment by chishi2612** [comment]
When the number of connections is maximum, do you think I 'll get this error or other? 
Do you know to force close ESTABLISHED connection? 

Thanks for replying

**Comment by lpinca** [comment]
If your client connections are created all from the same machine try to use different local addresses (`localAddress` option).

**Comment by chishi2612** [comment]
I'm sorry all connections are from another. I'll send you the log about TCP connections when i got this error. I hope you'll give me an advise. @lpinca 
Thanks alot

**Comment by chishi2612** [comment]
> ALL TCP Connections Count: 
>    4202 ESTABLISHED
>       3 SYN_RECV
>       1 Foreign
>       1 established)
>      17 FIN_WAIT1
>      12 LISTEN

This is tcp ESTABLISHED  connections in my server when i got socket hang up. it can be server's limitation.

**Comment by chishi2612** [comment]
@lpinca In my server, sometimes mqtt got: 
> Error: read ECONNRESET
almost 4202 ESTABLISHED are mqtt clients. I wonder socket hang up because of mqtt?

**Comment by lpinca** [comment]
What you posted now (read ECONNRESET) is a different error. It is raised when something is written to a socket destroyed by the other peer but you cannot get it after the `'open'` event is emitted. 

MQTT should not be responsible of these errors. I'm sorry but I can't help you any further, it doesn't seem to be an issue in ws.

**Comment by chishi2612** [comment]
@lpinca I want to enable log to track error. how i could do? 
When socket hang up, All old socket clients still can communicate to server. So server is still alive. I 'll upgrade ram, cpu and retry.
