### ISSUE TITLE
Passing the http.IncomingMessage to 'message' event

### ISSUE THREAD

**Issue by AsyncLegs** [websockets/ws#1658]
Hello everyone.
Is it possible to pass the mentioned object to that event as the second parameter?
It might be useful to check some client headers etc during the message handling.

**Comment by lpinca** [comment]
No, but you add it to the `WebSocket` object if you really need to.

```js
function onMessage(msg) {
  console.log(this.request.headers);
  console.log(`Received message ${msg} from user ${client}`);
}

wss.on('connection', function(ws, request) {
  ws.request = request;
  ws.on('message', onMessage);
});
```

**Comment by AsyncLegs** [comment]
Thanks!

**Comment by lpinca** [comment]
Or use `Function.prototype.bind()`

```js
function onMessage(request, msg) {
  console.log(this.request.headers);
  console.log(`Received message ${msg} from user ${client}`);
}

wss.on('connection', function(ws, request) {
  ws.on('message', onMessage.bind(null, request));
});
```

**Comment by trsh** [comment]
@lpinca but this would mean that you always get a copy from request that was set when connecting, not the actual one.

**Comment by lpinca** [comment]
Headers are sent only once, when the is made.
