### ISSUE TITLE
Node 12 Maximum call stack size exceeded

### ISSUE THREAD

**Issue by kybarg** [websockets/ws#1661]
- [x] I've searched for any related issues and avoided creating a duplicate
      issue.

#### Description
When using https://github.com/zeit/pkg to bundle my application get random `error RangeError: Maximum call stack size exceeded` error in `ws` module

#### Reproducible in:

- version: 7.2.0
- Node.js version(s): 12.13.0
- OS version(s): Windows 10 Build 1909

#### Steps to reproduce:

1. package app with pkg

2. run app

3. wait for error

#### Attachments:
```log
error RangeError: Maximum call stack size exceeded
    at WebSocket.<anonymous> (dist\server.js:0:0)
    at WebSocket.emit (events.js:196:13)
    at Receiver.receiverOnMessage (node_modules\ws\lib\websocket.js:800:20)
    at Receiver.emit (events.js:196:13)
    at Receiver.dataMessage (node_modules\ws\lib\receiver.js:423:14)
    at Receiver.getData (node_modules\ws\lib\receiver.js:353:17)
    at Receiver.startLoop (node_modules\ws\lib\receiver.js:139:22)
    at Receiver._write (node_modules\ws\lib\receiver.js:74:10)
    at doWrite (_stream_writable.js:417:12)
    at writeOrBuffer (_stream_writable.js:401:5)
```

**Comment by lpinca** [comment]
Does it happen before bundling with `pkg`?

**Comment by kybarg** [comment]
@lpinca Sorry to bother, seems to be problem with packaged version only, so it is up to `pkg`, thanks anyway

**Comment by suiGn** [comment]
Hello guys, I have been getting emails from this conversation a lot looking
at you guys working in websockets, I dont even remember why I am getting
them but it has surprise me the dedicatiln you guys have been putting into
whatever projects you have been doing, I am a coder myself but never really
got into any team, I am developing stuff on a websocket as well, I had a
bad day today in general and I hate to even express myself as I consider it
weak to do that in my mind. Anyways the point is I have some stuff I have
code in websockets and just feel like sharing it, is nothing but random
stuff working and maybe it may be helpful for some of you guys.

One is designed to keep track of webvisits go to the browser console log
after you click runme

cleaker.me

Is kind of a script you install to websites as a script tag and then you
have all the info coming to cleaker.

And the other is a chat I coded just to be able to open random channels and
keep conversations private and secret through channels

wreckthemedia.herokuapp.com

Let me know what you think.

Cheers.
