### ISSUE TITLE
websocket.upgradeReq property is missing or not set in later versions of ws.

### ISSUE THREAD

**Issue by dashanchang** [websockets/ws#1666]
Hi ws team,

I've been using ws with node.js for a long time. I have noticed the later versions of ws are missing one of the import properties: upgradeReq, causing apps using it to fail.

Adding one line code at line 288 of websocket-server.js would fix it:
ws.upgradeReq = req;

Thanks
Dashan Chang

**Comment by lpinca** [comment]
See https://github.com/websockets/ws/pull/1099. This was changed in version 3.0.0
