### ISSUE TITLE
reconnecting issue

### ISSUE THREAD

**Issue by Ulysseus** [websockets/ws#1667]
#### Description

I was attempting to get a Websocket connection to remain open. 
So I put 
ws.terminate();
call to a function that instantiates a new Websocket connection.
in the onerror function.
It works fine, if it hits an error. The onerror function is called.
But every now and then the entire program would crash .
Always on line 340 of websocket.js
This line reads:
```
throw new Error('WebSocket is not open: readyState 0 `(CONNECTING)');`
```
Nothing I do seems to get past this. So eventually I commented out the line.
It works fine now.
Seems weird, which is why I am creating an issue.

I am using the latest version, from an npm install on nodeJS version 10.16.0 on macOS Catalina

**Comment by lpinca** [comment]
It is intended behavior, see https://github.com/websockets/ws/releases/tag/7.0.0. Wait for the `'open'` event before calling `ws.send()`, `ws.ping()`, and `ws.pong()`.

**Comment by Ulysseus** [comment]
Got it, thx
