### ISSUE TITLE
Client authentication example doesn't work

### ISSUE THREAD

**Issue by uAliFurkanY** [websockets/ws#1674]
```
const http = require('http');
const WebSocket = require('ws');

const server = http.createServer();
const wss = new WebSocket.Server({ noServer: true });

wss.on('connection', function connection(ws, request, client) {
  ws.on('message', function message(msg) {
    console.log(`Received message ${msg} from user ${client}`);
  });
});

server.on('upgrade', function upgrade(request, socket, head) {
  authenticate(request, (err, client) => {
    if (err || !client) {
      socket.destroy();
      return;
    }

    wss.handleUpgrade(request, socket, head, function done(ws) {
      wss.emit('connection', ws, request, client);
    });
  });
});
```
Gives output: Received message a from user undefined

**Comment by lpinca** [comment]
I find it hard to believe because if you run that code it will simply crash as `authenticate()` is not implemented.

**Comment by uAliFurkanY** [comment]
That is the example given in the readme

**Comment by lpinca** [comment]
Yes exactly it is an example. The `authenticate()` implementation is a up to you. If you are looking for a working example check the `express-session-parse` example under the `examples` folder which uses the same logic.

**Comment by uAliFurkanY** [comment]
Ok. My point is that `client` is never passed to `function connection(ws, request, client)`

**Comment by lpinca** [comment]
It is, see `wss.emit('connection', ws, request, client);` inside the `authenticate()` function. You can check its value before emitting that event.

**Comment by uAliFurkanY** [comment]
Oh, I thought it was always passed to `function connection(ws, request, client)`. Thanks for informing.
