### ISSUE TITLE
how to edit a close frame status code?

### ISSUE THREAD

**Issue by hp8wvvvgnj6asjm7** [websockets/ws#1677]
I can't access this so called frame
`RangeError: Invalid WebSocket frame: invalid status code 0`

**Comment by lpinca** [comment]
You can't. It's the code number that is specified when using [`ws.close()`](https://github.com/websockets/ws/blob/master/doc/ws.md#websocketclosecode-reason). See the [RFC](https://tools.ietf.org/html/rfc6455#section-5) for more details.

**Comment by hp8wvvvgnj6asjm7** [comment]
I am not using ws.close() the error comes after a send. Does it mean that the responding server is causing this?

**Comment by hp8wvvvgnj6asjm7** [comment]
> 
> 
> You can't. It's the code number that is specified when using [`ws.close()`](https://github.com/websockets/ws/blob/master/doc/ws.md#websocketclosecode-reason). See the [RFC](https://tools.ietf.org/html/rfc6455#section-5) for more details.

I am not using ws.close() the error comes after a send. Does it mean that the responding server is causing this?

```
  const buffer =  type.encode(message).finish()

  const prefix = Buffer.allocUnsafe(4)
  prefix.writeUInt32BE(buffer.length)

  const msg = Buffer.concat([prefix, buffer])
  


  ws.on('open', () => ws.send(msg))
```

**Comment by lpinca** [comment]
Yes, it's possible. It is definitely caused by the data that is received, not sent.

**Comment by hp8wvvvgnj6asjm7** [comment]
Thank you, I have been struggling with this for two days now.. I didn't know if the error was on my side.

**Comment by hp8wvvvgnj6asjm7** [comment]
btw, this library is not giving me the error message: https://github.com/theturtle32/WebSocket-Node

I really can't change much about it.
