### ISSUE TITLE
RFC 6455 by default?

### ISSUE THREAD

**Issue by basickarl** [websockets/ws#1679]
Is this module by default RFC 6455 compliant? Or must we do for example the utf-8 and safe buffer checking manually?

I was reading this section: https://github.com/websockets/ws#opt-in-for-performance-and-spec-compliance

So I'm guessing manual checking those two things. But are there any other things in the RFC 6455 yous are aware of that ws doesn't do out-of-the-box (that's if ws isn't RFC 6455 compliant ws out-of-the-box)?

**Comment by lpinca** [comment]
> But are there any other things in the RFC 6455 yous are aware of that ws doesn't do out-of-the-box

Apart from UTF-8 validation (which can be made spec compliant via `utf-8-validate`) the only thing I can think of is that the server fir historical reasons also accepts non masked frames whilst the spec specify that

> The server MUST close the connection upon receiving a
>  frame that is not masked.

**Comment by basickarl** [comment]
@lpinca Thanks for the answer and fix, cheers!

**Comment by tcf909** [comment]
This was certainly a breaking change. A semver minor increment would have been appreciated here.

Also, what about the ability to continue not masking connections when mask is explicitly set to false?

**Comment by lpinca** [comment]
In a certain way, every bug fix is a breaking change.

> Also, what about the ability to continue not masking connections when mask is explicitly set to false?

You can still do that but the receiving end, if spec compliant, will close the connection if the frame needs to be masked.

**Comment by angaaron** [comment]
Is there a way to disable the mask check on the client receiving the messages now?

**Comment by lpinca** [comment]
@angaaron no.
