### ISSUE TITLE
Websocket connection to 'ws://localhost:5000' failed: net::ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by leanonybr-7579** [websockets/ws#1685]
Hello guys i'm learning javascript and sockets.io, but when i try to create a server i get this error: 

> WebSocket connection to 'ws://localhost:8000/' failed: Error in connection establishment: 

> net::ERR_CONNECTION_REFUSED

Here is my script(from html):
```html
<script type="text/javascript">
var socks = new WebSocket("ws://localhost:8000")  
socks.onopen = function(){
       alert('Websockets connected sucessfully')
}

socks.onmessage = function(event){
      alert(event.message)
}

socks.onclose = function(){
     alert('Websockets is not working properly')
}
</script>
```

Here is my server script:

```javascript 
var server = require('ws').Server
var usingServer = new server({ port: 8000 })
```

Here is my json file:

```json
{
  "name": "server",
  "version": "1.0.0",
  "description": "",
  "main": "server.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "nodemon server.js",

  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "ws": "^7.2.1"
  },
  "devDependencies": {
    "nodemon": "^2.0.2"
  }
}

```
Obs: i execute in terminal: 

> npm init

> npm install ws

> npm  i --save-dev nodemon

If someone could help, i will be glad!
Thanks!

**Comment by lpinca** [comment]
Make sure the server is started and listening for connections. Sorry but this is not issue tracker is only for bugs in the library. For general support like this please use another channel.
