### ISSUE TITLE
Odd error status code.

### ISSUE THREAD

**Issue by davidnus** [websockets/ws#1686]
- [ x] I've searched for any related issues and avoided creating a duplicate
      issue.

#### Description

I'm getting the following error on a ws websocket server production instance, periodically: 

Invalid WebSocket frame: invalid status code 65535
RangeError: Invalid WebSocket frame: invalid status code 65535
    at Receiver.controlMessage (/home/ec2-user/sm/node_modules/ws/lib/receiver.js:450:18)
    at Receiver.getData (/home/ec2-user/sm/node_modules/ws/lib/receiver.js:336:42)
    at Receiver.startLoop (/home/ec2-user/sm/node_modules/ws/lib/receiver.js:139:22)
    at Receiver._write (/home/ec2-user/sm/node_modules/ws/lib/receiver.js:74:10)
    at doWrite (_stream_writable.js:431:12)
    at writeOrBuffer (_stream_writable.js:415:5)
    at Receiver.Writable.write (_stream_writable.js:305:11)
    at Socket.socketOnData (/home/ec2-user/sm/node_modules/ws/lib/websocket.js:875:35)
    at Socket.emit (events.js:210:5)
    at Socket.EventEmitter.emit (domain.js:475:20)

I couldn't find any documented status code 65535, why it might be occurring, and whether this is a fatal event that should stop the socketserver process. Appreciate any insights. 

#### Reproducible in:

- version: 7.2.1
- Node.js version(s): 12.13.1
- OS version(s): Amazon Linux AMI 2018.03
- Nginx: 1.16.1

**Comment by lpinca** [comment]
It means the other peer is sending a close frame with an invalid status code. Add a listener for the `'error'` event on the `WebSocket` object to handle the error.

**Comment by davidnus** [comment]
We have `'error'` event handling, but`RangeError` is not being emitted correctly it seems.

Code outline:

```
wss.on('connection', (ws) => {
   ws.on('message', (msg) => msgHandler(msg));
   ws.on('error', (err) => socketErrHandler(err));
});
wss.on('error', (err) => socketServerErrHandler(err));
```
To repeat the issue, we manually create the error in `Receiver.startLoop`:

```
startLoop(cb) {
    let err;
     ...
    err = error(RangeError, `invalid status code `, true, 1002);
    cb(err);
  }
```
This will trigger an `uncaughtException` error.

**Comment by lpinca** [comment]
```js
'use strict';

const WebSocket = require('ws');

const wss = new WebSocket.Server({ port: 0 }, function() {
  const ws = new WebSocket(`ws://localhost:${wss.address().port}`);

  ws.on('open', function() {
    ws._socket.write(Buffer.from('888200000000FFFF', 'hex'));
  });
});

wss.on('connection', function(ws) {
  ws.on('error', console.error);
});
```

It works as intended if the error is correctly handled.

**Comment by davidnus** [comment]
Thnx! Found coding error. Appreciate the help!
