### ISSUE TITLE
initAsClient does not populate protocol 

### ISSUE THREAD

**Issue by YoDaMa** [websockets/ws#1687]
## Description of the Issue

In websocket.js the `protocol` value is never populated: https://github.com/websockets/ws/blob/master/lib/websocket.js#L47

## Expected Behavior
Now I'm not sure why this is, but it seems like a bug... My expected behavior is that the websocket object that is returned will have a protocol value that is filled with the value of the `protocols` parameter passed in. 

## Motivation
It seems that previously the protocol value would be populated with for instance `mqtt` if that was passed in as a `protocols` parameter. In the MQTT.js dependent repository `websocket-stream`, it creates an object that contains a websocket in it. See: https://github.com/maxogden/websocket-stream/blob/master/stream.js#L66

The MQTT.js websocket client tests are shown to check that the protocol value equals `mqtt`, so I'm assuming at one point the ws package had poulated the protocol value with something. See: https://github.com/mqttjs/MQTT.js/blob/master/test/websocket_client.js#L96

So, is this a bug that should be addressed?

**Comment by lpinca** [comment]
It is not a bug. The value of the property is the subprotocol selected by the server when the client sends a subprotocol(s).

https://github.com/websockets/ws/blob/7.2.1/lib/websocket.js#L624

**Comment by YoDaMa** [comment]
I see! Thank you. Will close this.
