### ISSUE TITLE
Expose private "_socket" value as public

### ISSUE THREAD

**Issue by YoDaMa** [websockets/ws#1688]
Currently socket is set as a private member of the class: https://github.com/websockets/ws/blob/master/lib/websocket.js#L58

It would be useful information to have this exposed as a public member, similar to protocol.

**Comment by lpinca** [comment]
It is private for good reasons. The most important is that the user should not mess with it (pause, resume, etc).

**Comment by lpinca** [comment]
It will not be hidden behind a symbol so that user can easily access it if they really need to but it will not be made fully public.

**Comment by mmm8955405** [comment]
你是不是笨蛋，在java的任何websocket服务中，都可以访问socket的任何信息。然后你把socket声明成私有的。，以致于很难访问
