### ISSUE TITLE
Feature request: Support multiple handlers for websocket connections

### ISSUE THREAD

**Issue by dtanabe** [websockets/ws#1692]
It appears that this library forbids multiple handlers for WebSockets on the same server by design:  https://github.com/websockets/ws/commit/364126620bf3fe4e6e0042d3b74ec53b5ccbbb08

This makes it hard for [webpack-dev-server](https://github.com/webpack/webpack-dev-server) to support live reloading while also allowing for proxying of websockets using [http-proxy-middleware](https://github.com/chimurai/http-proxy-middleware).

If I patch this line to simply do nothing instead of replying with `400 Bad Request`, both webpack-dev-server and http-proxy-middleware appear to play nicely with each other, so I'm not sure this restriction is really necessary:
https://github.com/websockets/ws/blob/9535702e50525621313941f0e1a972fdca403045/lib/websocket-server.js#L208

A flag to simply ignore requests that should not be acted on rather than actively reject them with a 400 would make this library able to co-exist well with other handlers of the `'upgrade'` event that may also be able to service requests.

**Comment by lpinca** [comment]
Yes this is by design. You can't have multiple WebSocket servers writing to and listening for events of the same `{net,tls}.Socket`. It is broken. There must be 1:1 correspondence.

That said you can handle the `'upgrade'` event yourself and call `server.handleUpgrade()` only when needed as shown in this example https://github.com/websockets/ws#multiple-servers-sharing-a-single-https-server.

**Comment by dtanabe** [comment]
Yeah, I agree the Node API here is a bit broken; I didn't realize just how broken it was until I started digging for the root cause of the problem I was having with `react-scripts`/`webpack-dev-server`.

Thank you for pointing me in the right direction, though; it's clear to me now how the problem can be fixed without a change to this library!

**Comment by ayubov** [comment]
> Thank you for pointing me in the right direction, though; it's clear to me now how the problem can be fixed without a change to this library!

@dtanabe Could you please share with others, how exactly it can be fixed?
