### ISSUE TITLE
use randomBytes async instead of sync

### ISSUE THREAD

**Issue by japrescott** [websockets/ws#1695]
when the node.js flag --trace-sync-io is enabled, it reports this library using a sync version of randomBytes.

```
(node:3962) WARNING: Detected use of sync API
    at randomBytes (internal/crypto/random.js:57:31)
    at frame (/app/node_modules/ws/lib/sender.js:74:18)
    at send (/app/node_modules/ws/lib/sender.js:271:16)
    at send (/app/node_modules/ws/lib/websocket.js:354:18)
```

according to the [node.js crypto docs](https://nodejs.org/api/crypto.html#crypto_crypto_randombytes_size_callback) there is also the possibility to pass a callback instead of (possibly) blocking the event loop

**Comment by lpinca** [comment]
Yes but it isn't a problem. This has been already discussed here https://github.com/websockets/ws/pull/832.

**Comment by japrescott** [comment]
thanks for the information
