### ISSUE TITLE
How to proxy websocket connection

### ISSUE THREAD

**Issue by ORESoftware** [websockets/ws#1697]
I want to be able to proxy a websocket connection from one server to another:

```js
import * as  WS from 'ws';
const wss = new WS.Server({
  port: 3017
});

wss.on('connection', w => {
  
  const c = new WS('ws://localhost:3016/nodejs-ws');
  w.pipe(c);
  c.pipe(w);
  
});

```

I tried it - and there are no pipe methods on the connections.
is there a way to do this? Can it be documented? Here is my attempt?

```js
wss.on('connection', w => {
  
  const c = new WS('ws://localhost:3016/nodejs-ws');
  
   w.on('message', data => {
    c.send(data);
   });

   c.on('message', data => {
    w.send(data);
   });
  
});
```

is that about right?

https://stackoverflow.com/questions/60328836/how-to-proxy-a-websocket-connection

**Comment by lpinca** [comment]
https://github.com/websockets/ws#use-the-nodejs-streams-api

**Comment by lpinca** [comment]
Btw your example is not exactly proxying. A proper proxy will get data as is from the source and pass it to the destination and the other way round without parsing the incoming WebSocket frames and rebuilding them.

Check https://github.com/http-party/node-http-proxy or https://github.com/nxtedition/node-http2-proxy for a reference implementation.
