### ISSUE TITLE
Unclear how to share port with http and ws protocols

### ISSUE THREAD

**Issue by ORESoftware** [websockets/ws#1698]
I have this code:

```typescript
import * as  WS from 'ws';
import * as express from 'express';

const app = express();
app.listen(3017);

const wss = new WS.Server({
  port: 3017
});

wss.on('connection', w => {
  
  const c = new WS('ws://localhost:3016/nodejs-ws');
  w.pipe(c);
  c.pipe(w);
  
});
```

we will get a port conflict - is there some place in the docs that mentions how to reuse the port? I think with Socket.io they do something like this:

```
const app = express();
app.listen(3017);
const wss = new WS.Server(app);
```

can this be documented/implemented? I am also curious how it works (how it's implemented).

**Comment by lpinca** [comment]
https://github.com/websockets/ws#external-https-server
