### ISSUE TITLE
How to use stream API on the server? Are there any relevant examples?

### ISSUE THREAD

**Issue by mmm8955405** [websockets/ws#1699]
I don't see an example of using the stream API on the server side, but the websocket-stream project has

**Comment by lpinca** [comment]
As documented here https://github.com/websockets/ws/blob/master/doc/ws.md#websocketcreatewebsocketstreamwebsocket-options

```js
server.on('connection', function(ws) {
  const duplex = WebSocket.createWebSocketStream(ws, { encoding: 'utf8' });
});
```
