### ISSUE TITLE
Is it possible to connect to a python websocket server with ws?

### ISSUE THREAD

**Issue by yimelia** [websockets/ws#1700]
- [* ] I've searched for any related issues and avoided creating a duplicate
      issue.

#### Reproducible in:

- version:7.2.1
- Node.js version(s): 6.13.4
- OS version(s): win7

#### Steps to reproduce:

1. I created a websocket server in python and can connect to it with chrome and simple javascript code
```
<script>
            var ws = new WebSocket("ws://localhost:8081/"),
                messages = document.createElement('ul');
            ws.onmessage = function (event) {
                console.log(event.data);
            };
        </script>
```
2. I am developing vs code plugin, trying to use ws to connect the server, and found that it was always "connecting".
```
import * as WebSocket from 'ws';
ws = new WebSocket("ws://localhost:8081/");
ws.on('open', () => ws.send('something'));
```

I always get `ws.readyState`=0

3. Is any different between browser client and ws client? can i use ws to connect a python websocket server?

**Comment by lpinca** [comment]
Yes it should work.
