### ISSUE TITLE
Info about minimum supported version

### ISSUE THREAD

**Issue by jonyrock-back** [websockets/ws#1703]
#### Description

Node running the `ws` lib fails on 8.2.1, but works fine on 8.3.0
it's all because of [Spread in object literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax)

**Comment by lpinca** [comment]
https://github.com/websockets/ws/blob/master/package.json#L21

**Comment by jonyrock-back** [comment]
@lpinca plz close the issue if you feel that there is no need to add in to the readme.

thank you for the lib btw

**Comment by lpinca** [comment]
npm/yarn should give you a warning if you install ws on Node.js < 8.3.0
