### ISSUE TITLE
The return of the steam API is not an asynchronous and iterative source. Does it support asynchronous and iterative sources

### ISSUE THREAD

**Issue by mmm8955405** [websockets/ws#1705]
The return of the steam API is not an asynchronous and iterative source. Does it support asynchronous and iterative sources

**Comment by mmm8955405** [comment]
Or what should I do to support asynchronous and iterative

**Comment by mmm8955405** [comment]
What is the way to establish multiplexing on a single WS connection,

Similar to this project:

[](https://github.com/libp2p/js-libp2p-mplex)

**Comment by mmm8955405** [comment]
What is the way to establish multiplexing on a single WS connection？

Similar to this project:

[js-libp2p-mplex](https://github.com/libp2p/js-libp2p-mplex)

**Comment by lpinca** [comment]
`WebSocket.createWebSocketStream()` returns a [`Duplex`](https://nodejs.org/api/stream.html#stream_class_stream_duplex). Multiplexing is up to you.
