### ISSUE TITLE
uncatched error?

### ISSUE THREAD

**Issue by Zibri** [websockets/ws#1706]
```
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: connect ETIMEDOUT xx.xx.xx.xx:yyyy
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
Emitted 'error' event at:
    at Socket.socketErrorListener (_http_client.js:392:9)
    at Socket.emit (events.js:198:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)

```
whatever try catch or error handling in my code can't catch this..
what can I do?

**Comment by lpinca** [comment]
Add a listener for the `'error'` event on the `WebSocket` object.

```js
const ws = new WebSocket(url);

ws.on('error', console.error);
```

Please fill the issue template, it's there for a reason.

**Comment by Zibri** [comment]
I did. and it does not catch it :(

**Comment by lpinca** [comment]
You have to add it to the `WebSocket`, not the server.

```js
wss.on('connection', function(ws) {
  ws.on('error', console.error);
});
```

**Comment by Zibri** [comment]
I don't understand. I have this error on the server. Not on the client.

**Comment by Zibri** [comment]
I have:
var WebSocketServer = require("websocket").server;
then
var wsServer = new WebSocketServer({
......

where should I put that? I see no other place :/

**Comment by lpinca** [comment]
```js
wsServer.on('connection', function(ws) {
  ws.on('error', function(err) {
    // Handle the error.
  })
})
```

**Comment by Zibri** [comment]
ohhhh now I see it.. sorry  and thanks.

**Comment by Zibri** [comment]
hmm even with that it still does not catch it. :(

**Comment by lpinca** [comment]
connect ETIMEDOUT is emitted on the client so add the error listener on the client.

**Comment by lpinca** [comment]
Here is a test case to reproduce the error in the original issue description:

```js
const WebSocket = require('ws');

const ws = new WebSocket('ws://192.0.2.1');

ws.on('error', console.error);
```

192.0.2.1 is a non-routable IP address.

**Comment by Zibri** [comment]
There are no clients in the program.. ok.. anyway I probably found it. Thanks for your help!
