### ISSUE TITLE
Piping the duplex stream errors if the websocket closes the connection

### ISSUE THREAD

**Issue by juanjoDiaz** [websockets/ws#1707]
- [X] I've searched for any related issues and avoided creating a duplicate
      issue.

#### Description

I have a websocket to tcp socket proxy doing something like:
```js
  const websocketStream = WebSocket.createWebSocketStream(client);
  clientStream.pipe(tcpSocketStream);
  tcpSocketStream.pipe(websocketStream);
```
Everything works until the client closes the websoket and the tcp socket tries to push data. Then I get `WebSocket is not open: readyState 2 (CLOSING)`.

I'd expect that the websocketStream stops consuming data one it starts the closing process.

#### Reproducible in:

- version: 7.2.0
- Node.js version(s): 10.X, 12.X
- OS version(s): OSX, Ubuntu

**Comment by lpinca** [comment]
That  error means that you are writing to a WebSocket that started the [closing handshake](https://tools.ietf.org/html/rfc6455#section-1.4), for example if you have buffered writes and the other peer abruptly closes the TCP connection.

**Comment by juanjoDiaz** [comment]
Yup. I understand what the error is.

However, I think that once the closing handshake has been started the stream should backpressure upstream and stop pushing data downstream since it's already been signaled that the WebSocket is closed and it will always fail. Not sure if this could be done using node.streams back pressure or maybe queueing the data when the ws is in CLOSING or CLOSED state like is done when it's CONNECTING in like https://github.com/websockets/ws/blob/master/lib/stream.js#L156
 
What I would expect is that, if the ws flickers (i.e. disconnect and reconnects again) the stream is backpressurring the upstream stream, buffering the data that it already has if necessary, and data continues to flow once the ws reconnects.

**Comment by lpinca** [comment]
> Not sure if this could be done using node.streams back pressure or maybe queueing the data when the ws is in CLOSING or CLOSED state like is done when it's CONNECTING

That would make it fails silently. Upstream backpressure is already handled as no more write are done when a writable stream errors.

Reconnection is not done automatically.

**Comment by lpinca** [comment]
The stream returned by `WebSocket.createWebSocketStream()` works like a https://nodejs.org/api/net.html#net_class_net_socket. Piping a readable stream to a `net.Socket` can cause write errors.

**Comment by lpinca** [comment]
Closing as answered, discussion can continue if needed.

**Comment by juanjoDiaz** [comment]
Yup. I understand the issue.
Not quite what I would expect but I can understand that someone might have different needs than me and I can easily work around it.

Thanks!!
