### ISSUE TITLE
WebSocket specification violation: wrong opcode/length validations

### ISSUE THREAD

**Issue by shiretu** [websockets/ws#1708]
#### Description

WebSocket specification violation.

#### Reproducible in:

- version: 7.2.2
- Node.js version(s): 12.x
- OS version(s): macOS

#### Steps to reproduce:
Open a WS server in a nodejs script and send a large ping payload. When the pong comes back, it will break and error out.

```
setInterval(() => {
    ws.ping(new Array(128 * 1024))
    console.log('Ping...')
  }, 1000)
```

#### Expected result:

No errors thrown, functional

#### Actual result:

Error thrown:
```
RangeError: Invalid WebSocket frame: invalid payload length 127
```

Specification: https://tools.ietf.org/html/rfc6455#section-5.5.3

The specs does not impose any limit on the amount of data sent per ping/pong. This code is wrong:
https://github.com/websockets/ws/blob/7.2.2/lib/receiver.js#L214

reason is because that rule is imposed on `if (this._opcode > 0x07 && this._opcode < 0x0b)` which includes both ping and pong opcodes as responses.

Furthermore, if we want to limit the ping/pong payloads (which we must not do, but if we really really really want that), then the sent ping should definitely be capped to 126 bytes.

**Comment by lpinca** [comment]
You are wrong: https://tools.ietf.org/html/rfc6455#section-5.5

**Comment by shiretu** [comment]
@lpinca in that case, there is still an issue: allowing sending large payloads.

**Comment by lpinca** [comment]
It's not a problem in my opinion, any spec compliant implementation must reject malformed frames. I don't think it makes much sense to throw an error on the sending peer if control frame payload is too big.

**Comment by shiretu** [comment]
well, is not exactly fine tho. Passable? Probably. The lib strives to adhere strictly to the specs, yet it is faulting itself when a client and a server of the same impl get connected. 

IMHO the impl should be either relaxed or strict. Thanks for feedback

**Comment by lpinca** [comment]
Ok convinced, addressed in https://github.com/websockets/ws/commit/e54f08daeef64d4b78f10ec2d7258b429961dac2.
