### ISSUE TITLE
How do I enable broadcasting of events to multiple separate ws server nodes.

### ISSUE THREAD

**Issue by qiulang** [websockets/ws#1712]
Hi, this is a question and I have searched related issues.

- [x] I've searched for any related issues and avoided creating a duplicate
      issue.

#### Description

My question is how do I enable broadcasting of events to multiple separate ws server nodes. For example if I use socket.io I have https://github.com/socketio/socket.io-redis.

Because I using dockers and I start several websocket servers. So it is not always the same ws server that handle the request about the same websocket connection, so if I use socket.io, socket.io-redis is a must then. So I was wondering does ws provide the similar solution ?

Thanks.

**Comment by lpinca** [comment]
> So I was wondering does ws provide the similar solution

No, not out of the box, but you can build something similar for ws. There might already be modules like this on npm.

**Comment by qiulang** [comment]
Hi, thanks for replying my question.
May I ask another question about the ws vs socket.io ? What are reasons to choose ws over socket.io ? Why did you develop ws in the first place ?

Thanks!

**Comment by lpinca** [comment]
ws is an implementation of the WebSocket protocol. Socket.IO is NOT an implementation of the WebSocket protocol. Socket.IO is a protocol on top of different "transports". One of these transport is WebSocket.

Socket.IO uses ws internally.

**Comment by qiulang** [comment]
Sorry did I understand you correctly that 

> Socket.IO uses ws internally.

I check socket.io 's source code briefly and did not find they use ws.

**Comment by lpinca** [comment]
See https://github.com/socketio/engine.io/blob/master/package.json#L34

**Comment by wanglong167** [comment]
> > 所以我想知道ws是否提供类似的解决方案
> 
> 不，不是开箱即用的，但是您可以为ws建立类似的东西。npm上可能已经有用于此的模块。

url? npm name

**Comment by wanglong167** [comment]
> > So I was wondering does ws provide the similar solution
> 
> No, not out of the box, but you can build something similar for ws. There might already be modules for this on npm.

where  npm name  || url
