### ISSUE TITLE
Please provide a clear/detailed example on how to create an authenticate function

### ISSUE THREAD

**Issue by vgoklani** [websockets/ws#1723]
Could you please provide a detailed example of the authenticate function as used in the README example. In particular, I'm confused by the client object? It looks like a callback, but then why do you use a "!" operator?

    const http = require('http');
    const WebSocket = require('ws');

    const server = http.createServer();
    const wss = new WebSocket.Server({ noServer: true });

    wss.on('connection', function connection(ws, request, client) {
      ws.on('message', function message(msg) {
        console.log(`Received message ${msg} from user ${client}`);
      });
    });

    server.on('upgrade', function upgrade(request, socket, head) {
      authenticate(request, (err, client) => {
        if (err || !client) {
          socket.destroy();
          return;
        }

        wss.handleUpgrade(request, socket, head, function done(ws) {
          wss.emit('connection', ws, request, client);
        });
      });
    });

    server.listen(8080);

**Comment by lpinca** [comment]
The assumption is that `authenticate` can call the callback with no argument when there is no error but the authentication failed e.g. when no user is found. In that case (`!client`) the connection is closed.

**Comment by vgoklani** [comment]
could you give me an example of what *client* looks like? thanks!

**Comment by lpinca** [comment]
Could be an ID or an object whatever your authentication layer returns.

**Comment by lpinca** [comment]
There is a working example here. Assume `request.session.userId` is `client` in your example above.

**Comment by cedvdb** [comment]
@lpinca it's a weird api there.

So if this is called, the websocket connection is opened ?

```
    wss.handleUpgrade(request, socket, head, function done(ws) {
      wss.emit('connection', ws, request, client);
    });
```

But if you don't call on('upgrade') and therefor not calling the function above, it will upgrade anyway ? That's why I think it's weird.
