### ISSUE TITLE
Error: WebSocket is not open: readyState 3 (CLOSED)

### ISSUE THREAD

**Issue by leefsmp** [websockets/ws#1724]
Looks like I'm the only one having this issue, I thought I would report it anyway:

When starting my server the socket server works perfectly for about 15-20 minutes, then after that period of time I am getting the following error when a client attempts to connect to it:

```
uncaughtException: Error: WebSocket is not open: readyState 3 (CLOSED)
    at WebSocket.send (/var/app/current/node_modules/ws/lib/websocket.js:329:19)
```

It becomes unusable afterwards. After trying several things with my server I decided to give a try at [another socket library](https://github.com/theturtle32/WebSocket-Node). It has the same surface API so I didn't change anything in my own code: problem's gone. 

I'm not looking at an answer here as I don't have specific code to reproduce, I am just initializing the socket server as illustrated in basic example with a classic express server. I can totally live with it since switching to the other lib spars me some headache.

**Comment by lpinca** [comment]
The error means you are calling `websocket.send()` on a WebSocket whose ready state is `CLOSED`. If you use a callback on `websocket.send()` that error is passed to the callback.

Also in version [7.0.0](https://github.com/websockets/ws/releases/tag/7.0.0) the behavior changed and no error is thrown even if the `callback` function is not provided.

**Comment by leefsmp** [comment]
Thanks, not using a callback. The problem is that once I get that error, no other client will be able to connect to the running websocket.

**Comment by lpinca** [comment]
That's expected because the exception is thrown and unhandled. Until version 7.0.0 the recommended way to deal with the problem was to ensure that the ready state was open.

```js
if (ws.readyState === WebSocket.OPEN) {
  ws.send(data);
}
```

**Comment by lpinca** [comment]
Closing as answered.
