### ISSUE TITLE
Correct way of client reconnect

### ISSUE THREAD

**Issue by tuloski** [websockets/ws#1725]
Suppose I have a client.
The client loses internet connection.
The client detects the disconnection either with .onclose or with ping/pong.

Now what is the best way to try to reconnect automatically?
Just .terminate() and create a new websocket? The new websocket might also fail because the internet connection is still lost. Should I try recreate a new websocket every N seconds until success? Is there a way to keep the same websocket object and only try to connect?
Is there an autoreconnect feature (I didn't see it in the docs)?

**Comment by lpinca** [comment]
> Just .terminate() and create a new websocket? The new websocket might also fail because the internet connection is still lost. Should I try recreate a new websocket every N seconds until success?

Yes.

> Is there a way to keep the same websocket object and only try to connect?

No.

> Is there an autoreconnect feature (I didn't see it in the docs)?

No but there are many modules / wrappers on npm to do this if you don't want to roll your own.

P.S. This bug tracker is only for issues in the library. For general support questions please use another channel.
