### ISSUE TITLE
Provide a way for shouldHandle() to skip upgrade handling without aborting the handshake

### ISSUE THREAD

**Issue by andsens** [websockets/ws#1726]
I am running a webpack devserver through my app using [`http-proxy-middleware`](https://github.com/chimurai/http-proxy-middleware) on an express server, while also hosting apollo-server with [subscriptions](https://github.com/apollographql/subscriptions-transport-ws) on the same server. The `httpServer` passed to `SubscriptionServer` during setup is forwarded to [`ws`](https://github.com/websockets/ws), which [adds an `upgrade` listener](https://github.com/websockets/ws/blob/021d4ef4e3c61c2804651c77a97e4608deebb29c/lib/websocket-server.js#L96-L99). [That handler](https://github.com/websockets/ws/blob/021d4ef4e3c61c2804651c77a97e4608deebb29c/lib/websocket-server.js#L190-L256) can do only one of two things: upgrade the connection or kill it.  
This conflicts quite a bit with the other websocket handler that is installed on the same server, if an upgrade request was intended for that instead.  
`http-proxy-middleware` handles upgrade requests not meant for it, [by simply ignoring them](https://github.com/chimurai/http-proxy-middleware/blob/c2882dfd188ddf42e8d9ab8e813b20970c7feba0/src/http-proxy-middleware.ts#L77-L83). This would IMO also be the expected behavior for the server option `path`:
> `path` {String} Accept only connections matching this path.

Right now my solution is this:
```
const serverProxy = new EventEmitter();
server.on('listening', serverProxy.emit.bind(serverProxy));
server.on('error', serverProxy.emit.bind(serverProxy));
server.on('upgrade', (req: IncomingMessage, ...rest: any[]) => {
  if (req.url === paths.graphqlSubscriptions) {
    serverProxy.emit('upgrade', req, ...rest);
  }
});
apollo.installSubscriptionHandlers(serverProxy as Server);
```

The fix would not change much if `subscriptions-transport-ws` were to address this, and it just seems... awkward. Which is why I created the issue here and not further downstream.

**Comment by lpinca** [comment]
See https://github.com/websockets/ws/pull/1670.

**Comment by lpinca** [comment]
> That handler can do only one of two things: upgrade the connection or kill it.
This conflicts quite a bit with the other websocket handler that is installed on the same server, if an upgrade request was intended for that instead.

This is by design, there can only be a single websocket handler on the same server. If you need some kind of routing the suggested way to do in ws is https://github.com/websockets/ws#multiple-servers-sharing-a-single-https-server.
