### ISSUE TITLE
Help pls (docs are unclear)

### ISSUE THREAD

**Issue by npomfret** [websockets/ws#1727]
In a client socket, what is the difference between (for example):

`ws.addEventListener('close', () => ...);`

`ws.onclose = () => ...;`

`ws.on('close', () => ...);`

Same for `onerror` etc...

Thanks in advance;

**Comment by lpinca** [comment]
When using `ws.addEventListener()` and `ws.onclose = function() {}` the callback receives an `Event` object emulating the browser interface. With `ws.onclose = function() {}` you can only add a single listener while `ws.addEventListener()` allows you to add multiple listener of the same type.

`ws.on()` instead is a method of the Node.js [`EventEmitter`](https://nodejs.org/api/events.html). Listener added using `ws.on()` does not receive an `Event` object. The arguments of the listeners added via `ws.on()` are documented in https://github.com/websockets/ws/blob/master/doc/ws.md.
