### ISSUE TITLE
Validate text message encoding error as early as possible would be better

### ISSUE THREAD

**Issue by LongTengDao** [websockets/ws#1730]
- [x] I've searched for any related issues and avoided creating a duplicate
      issue.

#### Description

Validate and throw encoding error when each fragment is recieved would be better.

**Comment by lpinca** [comment]
The problem is that the text message could be split over multiple fragments and UTF-8 validation could fail if run on the single fragments:

```js
const isValidUTF8 = require('utf-8-validate');

const buf1 = Buffer.from([0xf0, 0x90, 0x80, 0x80]);

console.log(isValidUTF8(buf1)); // => true

const buf2 = Buffer.from([0xf0, 0x90]);

console.log(isValidUTF8(buf1)); // => false
```

**Comment by LongTengDao** [comment]
The 'string_decoder' module maybe provide some ideas to enhance 'utf-8-validate'

**Comment by lpinca** [comment]
https://tools.ietf.org/html/rfc6455#section-5.6

> The "Payload data" is text data encoded as UTF-8.  Note that a
> particular text frame might include a partial UTF-8 sequence;
> however, the whole message MUST contain valid UTF-8.

Not sure how `string_decoder` can help here.

**Comment by LongTengDao** [comment]
I mean `string_decoder` reserve 0~6 bytes at the end of the buffer, and decode them with next buffer :)

<https://nodejs.org/dist/latest-v12.x/docs/api/string_decoder.html>
