### ISSUE TITLE
Second websocket not working as expected

### ISSUE THREAD

**Issue by The-Box1** [websockets/ws#1731]
#### Description

When creating two websockets I am able to receive messages on both as normal but the second websocket doesn't seem to be sending any messages to the server. The first one works as normal.

#### Reproducible in:

- version:
- Node.js version(s): v12.16.1
- OS version(s): Windows 10 Home

#### Steps to reproduce:

1. Create a websocket: `ws = new WebSocket('wss://gateway.discord.gg/?v=6&encoding=json');`

2. Listen and send as normal

3. Create a second websocket: `secondWs = new WebSocket(''wss://us-east289.discord.media);`

4. Listen with `secondWs.onmessage = (e) => {}`

5. Attempt to send message: `secondWs.send(JSON.stringify({ op: VoiceOpcodes.HEARTBEAT, d: Math.floor(Math.random() * 10e10) }));`

#### Expected result:

The server would receive the message and respond accordingly

#### Actual result:

The server doesn't receive any information from the websocket

### Attachments

First websocket: [https://pastebin.com/pka8XyGN](url)
Second Websocket: [https://pastebin.com/vNYP1pDa](url)

**Comment by lpinca** [comment]
This is not a ws issue. Run this as proof.

```js
const WebSocket = require('ws');

const ws1 = new WebSocket('wss://echo.websocket.org/');

ws1.on('open', function open() {
  console.log('ws1 connected');
  ws1.send(Date.now());
});

ws1.on('message', function incoming(data) {
  console.log(`ws1 roundtrip time: ${Date.now() - data} ms`);

  setTimeout(function timeout() {
    ws1.send(Date.now());
  }, 500);
});

const ws2 = new WebSocket('wss://echo.websocket.org/');

ws2.on('open', function open() {
  console.log('ws2 connected');
  ws2.send(Date.now());
});

ws2.on('message', function incoming(data) {
  console.log(`ws2 roundtrip time: ${Date.now() - data} ms`);

  setTimeout(function timeout() {
    ws2.send(Date.now());
  }, 500);
});
```
