### ISSUE TITLE
Why use new Uint8Array?

### ISSUE THREAD

**Issue by LongTengDao** [websockets/ws#1732]
https://github.com/websockets/ws/blob/021d4ef4e3c61c2804651c77a97e4608deebb29c/lib/receiver.js#L107

Why not `dst.set(buf.slice(0, n), offset);` here?

`new Uint8Array` will copy data, while buffer#slice not

**Comment by lpinca** [comment]
It's the same but slightly faster.

```
$ cat index.js 
'use strict';

const Benchmark = require('benchmark');

const suite = new Benchmark.Suite();

const buf = Buffer.alloc(1024);
const n = 256;
let ret;

suite.add('buf.slice()', function() {
  ret = buf.slice(0, n);
  return ret;
});

suite.add('Uint8Array', function() {
  ret = new Uint8Array(buf.buffer, buf.byteOffset, n)
  return ret;
});

suite.on('cycle', function(event) {
  console.log(event.target.toString());
});

suite.on('complete', function() {
  console.log('Fastest is ' + this.filter('fastest').map('name'));
});

suite.run({ async: true });
``` 

```
$ node index.js 
buf.slice() x 26,542,370 ops/sec ±0.55% (91 runs sampled)
Uint8Array x 27,484,667 ops/sec ±0.18% (98 runs sampled)
Fastest is Uint8Array
```

https://github.com/nodejs/node/blob/v13.12.0/lib/buffer.js#L1100-L1106

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array/Uint8Array


> `**buffer**`, `**byteOffset**`, `**length**`
>
> When called with a `buffer`, and optionally a `byteOffset` and a `length`
> argument, a new typed array view is created that views the specified
> `ArrayBuffer`. The `byteOffset` and `length` parameters specify the memory
> range that will be exposed by the typed array view. If both are omitted, all
> of `buffer` is viewed; if only `length` is omitted, the remainder of `buffer`
> is viewed.
