### ISSUE TITLE
Issue connection with some WebSocket Server

### ISSUE THREAD

**Issue by Dystorian** [websockets/ws#1733]
Example list: wss://eu.senpa.io:3001/ , wss://eu.senpa.io:2001/ , wss://asia.senpa.io:1001/

Hello, 
I received error 401 on thoses websockets , when i try to connect , so it does not reach the onOpen. This issue is only related to this lib. i tried with websocket test site , browser websocket , and also another lib nodejs : https://github.com/theturtle32/WebSocket-Node all others working fine and connect to reach onOpen. any fix ? server used seems to be cWebSocket.

Cordialy

**Comment by lpinca** [comment]
I can reproduce but it does not seem an issue in the library. This code only uses Node.js built-in modules and it prints 401 instead of "It works".

```js
const https = require('https');

const request = https.get({
  host: 'eu.senpa.io',
  port: 3001,
  headers: {
    'Sec-WebSocket-Version': 13,
    'Sec-WebSocket-Key': 'pPrH1TkBe68uxHNRKhKeyw==',
    Connection: 'Upgrade',
    Upgrade: 'websocket'
  }
});

request.on('upgrade', function() {
  console.log('It works');
});

request.on('response', function(response) {
  console.log(response.statusCode);
});
```

so it could an issue in Node.js but I don't trust this server https://github.com/ClusterWS/cWS

**Comment by Dystorian** [comment]
why it's working with https://github.com/theturtle32/WebSocket-Node ? and how to fix please ?

**Comment by lpinca** [comment]
Because the server seems to care about the order of the headers. For example

```js
const https = require('https');

const request = https.get({
  host: 'eu.senpa.io',
  port: 3001,
  headers: {
    Connection: 'Upgrade',
    Upgrade: 'websocket',
    'Sec-WebSocket-Version': 13,
    'Sec-WebSocket-Key': 'pPrH1TkBe68uxHNRKhKeyw=='
  }
});

request.on('upgrade', function() {
  console.log('It works');
});

request.on('response', function(response) {
  console.log(response.statusCode);
});
```

It seems a bug in the server implementation. Please report the issue in the server repository: https://github.com/ClusterWS/cWS.

**Comment by Dystorian** [comment]
Okay! I fixed! 
Thank you!
