### ISSUE TITLE
How do I send an array of string ?

### ISSUE THREAD

**Issue by qiulang** [websockets/ws#1740]
Hi this is a question and maybe a suggestion to the documentation. I searched the closed issues too but I can't the answer.

So how do I  send array of string?  I was trying to send `['1', '1025']` to server

```
const ws = new WebSocket('ws://localhost:3000')

ws.on('open', function open() {
  ws.send(['1', '1025']) 
})
```

And the server code

```
const WebSocket = require('ws')
const wss = new WebSocket.Server({ port: 3000 })

wss.on('connection', function connection(ws) {
  ws.on('message', function incoming(message) {
    console.log('on message:received: %s', message)
  })

  ws.send('something')
})
```

When I debug it I found the server got `Buffer(2) [1, 1]`. So how do I turned that to `['1', '1025']` ?

Thanks!

<img width="1050" alt="ws server" src="https://user-images.githubusercontent.com/516243/79354394-ed255b80-7f6e-11ea-9675-658ed2632046.png">

**Comment by lpinca** [comment]
You can't. Use JSON or CBOR/MessagePack if you prefer binary data.

```js
ws.send(JSON.stringify(['1', '1025']));
```

and parse back the message on the receiving end.

**Comment by SannanOfficial** [comment]
What about the cases in which there's a file to be sent to the server alongside some additional info?
