### ISSUE TITLE
so you know, node 13.13 changed this

### ISSUE THREAD

**Issue by andrewhodel** [websockets/ws#1743]
In your code, well the README at least:

```
grep -r req.connection.remoteAddress *
node_modules/ws/README.md:  const ip = req.connection.remoteAddress;
```

You cannot use req.connection.remoteAddress anymore, it's now req.socket.remoteAddress

https://nodejs.org/api/http.html#http_request_connection

```
request.connection#
Added in: v0.3.0Deprecated since: v13.0.0
Stability: 0 - Deprecated. Use request.socket.
```

**Comment by lpinca** [comment]
It's deprecated, not removed.
