### ISSUE TITLE
websocket closing connection automatically

### ISSUE THREAD

**Issue by sachinbaghel14** [websockets/ws#1747]
#### Description

i have deployed websocket server on heroku and Everything is working good but if there is no transfer between server and client after a certain time the connection is closed. i don't know who is closing the connection server or client.

#### Client code
const Websocket = require('ws');

var  ws = new Websocket('https://secure-mountain-02060.herokuapp.com/');

ws.onmessage = function(event){
  console.log(event.data);
}

ws.onclose = function(){
  console.log('server close');
}

**Comment by lpinca** [comment]
Try with sending pings as shown here https://github.com/websockets/ws#how-to-detect-and-close-broken-connections.

**Comment by sachinbaghel14** [comment]
> Try with sending pings as shown here https://github.com/websockets/ws#how-to-detect-and-close-broken-connections. The server is probably closing connections due to inactivity.

what is the default time out ?

**Comment by lpinca** [comment]
I don't know you have to ask it to Heroku. The connection is probably closed by their load balancer. Try to send pings from the client every 30 sec.

```
function noop() {}

const insterval = setInterval(function() {
  ws.ping(noop);
}, 30000);

interval.unref();
```

**Comment by sachinbaghel14** [comment]
is there any function to reconnect the client ?

**Comment by lpinca** [comment]
No, you have to create a new WebSocket. There are many modules/wrapper on npm that can help you with reconnection.

**Comment by lpinca** [comment]
Closing as answered. Discussion can continue if needed.

**Comment by maxp-hover** [comment]
What is `noop` supposed to be? The readme says that pong messages will automatically be sent, but this doesn't seem to be the case

**Comment by sachinbaghel14** [comment]
> What is `noop` supposed to be? The readme says that pong messages will automatically be sent, but this doesn't seem to be the case
i am also confused @maxp-hover.  
please help @lpinca.

**Comment by lpinca** [comment]
The example used it to ignore errors if the WebSocket ready state was not open. It is no longer needed now.

**Comment by sachinbaghel14** [comment]
is there any other method to resolve this problem actually I am now trying to implement a android client every thing is working fine but facing the same issue of connection closing.
I am asking it because having a thought that doing ping will decrease the efficiency of the app 
please help @lpinca

**Comment by netizen-ais** [comment]
> is there any other method to resolve this problem actually I am now trying to implement a android client, every thing is working fine but facing the same issue of connection closing.
> I am asking it because i have a thought that doing ping will decrease the efficiency of the app
> please help @lpinca

The ping (with a reasonable interval) impact of performance should be negligible even when using the websocket to stream continuous data. As a side note, Android will close the ws connection (but that's not an issue of this lib and you should look for help elsewhere)
