### ISSUE TITLE
[Documentation/Feature] Socket identifier or someway to save information against a socket

### ISSUE THREAD

**Issue by barkermn01** [websockets/ws#1749]
- [x ] I've searched for any related issues and avoided creating a duplicate
      issue.

#### Description

There seems to be a lack of information about how we can get a socket identifier. the reason for this is as your example shows there should be an authentication system. but then I need to save information about that authentication into my application.

E.G
Client Connection (socket)
Authentication (App) - needs to save what they are authenticated for
Server Upgrades / Accepts

I tried saving information against the socket E.G
```js
on('connection', (sock) => { sock.id = "something"; })
on('close', (sock) => {console.log("Socket closing", sock.uuid);})
```

If there is a method could it be documented, if there's not would it be possible to provide some method so it could be E.G a socket identifier against the socket on connection or reconnection?

**Comment by lpinca** [comment]
> [x] I've searched for any related issues and avoided creating a duplicate issue

Not really :)

This is out of the scope of the project if you search through closed issues there are multiple suggestions on how to do this. You can add an ID as show in your example (https://github.com/websockets/ws/issues/859) and/or keep a map ID -> websocket.

**Comment by barkermn01** [comment]
I'm sorry I socket identifier is out of the scope of this project then close the project because the whole point about WebSockets is to give a TCP like a stack, every TCP socket system implemented gives a way to identify the socket, you said my example works but it does not so clearly that's a bug, because as my example says it does not work the console.log gives an undefined.

![image](https://user-images.githubusercontent.com/37368/80484654-f7246280-894f-11ea-97fa-43e0a266c6b5.png)

**Comment by lpinca** [comment]
I'm not sure what you are talking about.

```js
const uuid = require('uuid');
const WebSocket = require('ws');

const server = new WebSocket.Server({ port: 0 });

server.on('connection', function(ws) {
  ws.id = uuid.v4();

  console.log('open', ws.id);

  ws.on('close', function() {
    console.log('close', ws.id);
  });
  ws.close();
});

server.on('listening', function() {
  const { port } = server.address();
  const ws = new WebSocket(`ws://localhost:${port}`)
});
```

Run this and you'll see that it works as expected.

[Section 4.2.2](https://tools.ietf.org/html/rfc6455#section-4.2.2) of the RFC describes the server's opening handshake and has nothing to do with what you want. It's what the server should verify and return in the HTTP response sent to the client.

**Comment by barkermn01** [comment]
yeah,

And as part of that opening handshake, there is a socket identifier used that identifier gives it a unique match to the socket, so it should be exposed so applications can use it to know .

The example I have given built from your #859 issue before I opened this ticket, does not work and I have shown in VSCode does not work line 12 of the print screen, then look at the bottom 3 lines of the terminal (it does not even save to the object) . 

The fact is the library must have some way of knowing a socket Identifier otherwise it could not send messages to a socket, all I'm asking for is that identifier to be made public to the socket (and the documentation says how to get it). and if that's too hard just a two-method and a var to the object E.G `setPublicIdentifer(string id); getPublicIdentifer()`.

The fact is without a way to identify a socket how in the hell does one know what the socket is authorised to do E.G if it tries to send something that would change something when they are not authorised to do so. the point is one server many clients, and clients can have different permissions and there needs to be a method to save what permissions each client has on the server.

**Comment by lpinca** [comment]
Using your own code:

```js
const uuid = require('uuid');
const WebSocket = require('ws');

const server = new WebSocket.Server({ port: 0 });

const SocketHandler = (new function SocketHandler() {
  this.openConnection = (sock) => {
    sock.id = uuid.v4();
    sock.on('close', this.closeConnection.bind(this, sock));

    console.log('Socket assigned uuid', sock.id);

  }

  this.closeConnection = (sock) => {
    console.log('Socket closing', sock.id);
  }
});

server.on('connection', SocketHandler.openConnection);

server.on('listening', function() {
  const { port } = server.address();
  const ws = new WebSocket(`ws://localhost:${port}`);

  ws.on('open', ws.close);
});
```

```
$ node index.js
Socket assigned uuid 983f1544-874b-423b-95d2-7674a6fc614e
Socket closing 983f1544-874b-423b-95d2-7674a6fc614e
```

**Comment by barkermn01** [comment]
Well, it's not working for me, so what's different, 

[RealTimeUpdates.zip](https://github.com/websockets/ws/files/4546005/RealTimeUpdates.zip)

I'm running node 14 (current) and it does not work.

**Comment by barkermn01** [comment]
here is a pull request that fixes it, it's due to class / object security as an object of a class in javascript can't have its permanent state updated from outside the class/objects methods

https://github.com/websockets/ws/pull/1751

**Comment by lpinca** [comment]
> it's due to class / object security as an object of a class in javascript can't have its persistent state updated from outside the class/objects methods without it being handled or internally supported by the class/object

It doesn't make much sense. JavaScript allows you to add any property to an object.

```js
class Foo {}

const foo = new Foo();

foo.id = 123;

console.log(foo.id); // => 123
```

```js
this.closeConnection.bind(this, sock);
```

this is needed because your `this.closeConnection()` takes a `sock` argument but is used as a listener for the `'close'` event. The listeners of the `'close'` event only take two arguments. The close `code`, and the `reason`, not the `WebSocket` instance.

I suggest you read the `EventEmitter` documentation and this in particular https://nodejs.org/api/events.html#events_passing_arguments_and_this_to_listeners.

Also read https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/this. The `this` keyword works differently from other languages.

**Comment by barkermn01** [comment]
It's because when an event is called the scope of this is the object the event is being called on E.G
`obj.emit('evntName')` call the eventName with `this` defined as `obj` automatically by JavaScript.

So the closeHandler should have access to WebSocket via this, but because it did not work in my testing i tried looking for sock to be passed in.

**Comment by lpinca** [comment]
> that's the point can't save persistent data on the object from outside its creation scope.

This is not true.

**Comment by lpinca** [comment]
Anyway I've tried to help you and spent quite a bit of my free time here. I'm done, if you don't like the lib and think you can make it better please fork it and use your own fork.

**Comment by barkermn01** [comment]
okies, done that, https://www.npmjs.com/package/better-web-sockets#obtaining-socket-identifyer
