### ISSUE TITLE
ws.terminate should accept execption object

### ISSUE THREAD

**Issue by man1989** [websockets/ws#1752]
- [x] I've searched for any related issues and avoided creating a duplicate
      issue.

#### Description
```destroy``` method of nodejs socket object accept exception object but ```terminate``` method which wraps ```destroy``` method doesn't allow us to pass exception object

#### Expected result:
It should allow to us to pass exception object
#### Actual result:
no parameter support for ```terminate```

**Comment by lpinca** [comment]
This is by design. Any error emitted emitted by the internal socket will not be reemitted on the `WebSocket` so there is no reason to terminate with an error as that error would be ignored.
