### ISSUE TITLE
 reading binary data coming from websocket client

### ISSUE THREAD

**Issue by sachinbaghel14** [websockets/ws#1753]
#### Description
i am trying to read the data coming from this client but when i try to `console.log()` it don't print the actual data. So how can i read the data coming from this client.

    const WebSocket = require('ws');
    const ws = new WebSocket('ws://localhost:8081');
    
    ws.on('open', function open() {
      const array = new Float32Array(5);
    
      for (var i = 0; i < array.length; ++i) {
        array[i] = i / 2;
      }
    
      ws.send(array);
    });

**Comment by lpinca** [comment]
What you get is a `Buffer` instance. To get back a `Float32Array` you have to convert the `Buffer` to a `Float32Array`.

```js
// `buf` is the received `Buffer`.
const array = new Float32Array(buf.buffer, buf.byteOffset, buf.byteLength / 4);
```

**Comment by sachinbaghel14** [comment]
what if i want to send Array of strings?

**Comment by lpinca** [comment]
You can't. Use JSON of a binary equivalent like MessagePack/CBOR.

**Comment by sachinbaghel14** [comment]
can you give me any example of it?

**Comment by sachinbaghel14** [comment]
ok, Thank you so much.
