### ISSUE TITLE
WS incompatible with Yarn PnP

### ISSUE THREAD

**Issue by Mike-Dax** [websockets/ws#1756]
#### Description

Upon attempting to require the `utf-8-validate` and `bufferutil` modules, Yarn PnP will detect the usage of a module that's not installed and error.

#### Reproducible in:

- version: 7.2.3
- Node.js version(s): 12.2.0
- OS version(s): MacOS 10.14.6

#### Steps to reproduce:

1. Use Yarn V2 with PnP

2. Install ws

3. Attempt to use

#### Expected result:

No errors, the fallback happens gracefully.

#### Actual result:

```
Module not found: Error: Can't resolve 'utf-8-validate' in '~/project/node_modules/ws/lib'
resolve 'utf-8-validate' in '~/project/node_modules/ws/lib'
```

**Comment by lpinca** [comment]
I've enabled Plug’n’Play and installed ws with yarn@2.0.0-rc.27. It seems to work fine, no error occurs. I I'm closing this issue. Discussion can continue if needed.
