### ISSUE TITLE
Do use Map() for storage ws objects is relevant ?

### ISSUE THREAD

**Issue by ivan-fr** [websockets/ws#1758]
Hello, 
I have a question,

In your example code with session, you used the Map() object for registry ws object by userId.
I would like to know, if it is a good solution in production environment with a lot of users.

will we have a performance drop?

Thanks.

**Comment by lpinca** [comment]
It's ok, it should work like a hash table with O(1) average complexity for search and lookup.

**Comment by ivan-fr** [comment]
ok thanks :)
