### ISSUE TITLE
"...options" cause problem 

### ISSUE THREAD

**Issue by moserg3000** [websockets/ws#1759]
- [ ] I've searched for any related issues and avoided creating a duplicate
      issue.

#### Description

Code contain "...options" string
#### Reproducible in:

- version:
- /lib/websocket.js current version(s):
- OS version(s): any

#### Steps to reproduce:
 1. Line 348 
    const opts = {
      binary: typeof data !== 'string',
      mask: !this._isServer,
      compress: true,
      fin: true,
      **...options**
    };

2. Line 452

 const opts = {
    protocolVersion: protocolVersions[1],
    maxPayload: 100 * 1024 * 1024,
    perMessageDeflate: true,
    followRedirects: false,
    maxRedirects: 10,
    ...options,
    createConnection: undefined,
    socketPath: undefined,
    hostname: undefined,
    protocol: undefined,
    timeout: undefined,
    method: undefined,
    host: undefined,
    path: undefined,
    port: undefined
  };

#### Actual result:

error

**Comment by lpinca** [comment]
What is the issue? This is the spread syntax on an object literal. See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax

You need to use Node.js version >= 8.3.0
