### ISSUE TITLE
WS Unhandled Error on Alpine Linux AWS ElasticBeanstalk 

### ISSUE THREAD

**Issue by ArielFrischer** [websockets/ws#1760]
#### Description
I'm using image: `mhart/alpine-node:12.16.3` running on elastic beanstalk single docker application.
Our puppeteer package has `ws` as a dependency. The puppeteer installation using yarn seems to install without any errors, but during runtime I get `ws TCP.onReadStream error` which crashes my server and is difficult to catch() because it's run inside `puppeteer`. Judging from my code flow it seems to happen after I call puppeteer's `await browser.close()`.
 ```
events.js:287
      throw er; // Unhandled 'error' event
      ^
Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:205:27)
Emitted 'error' event on WebSocket instance at:
    at WebSocket.finalize (/backend/node_modules/puppeteer/node_modules/ws/lib/WebSocket.js:182:41)
    at Socket.emit (events.js:310:20)
    at Socket.EventEmitter.emit (domain.js:482:12)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: 'ECONNRESET',
  code: 'ECONNRESET',
  syscall: 'read'
}
error Command failed with exit code 1.
```

My yarn.lock 
```
ws@^3.0.0:
  version "3.3.3"
  resolved "https://registry.yarnpkg.com/ws/-/ws-3.3.3.tgz#f1cf84fe2d5e901ebce94efaece785f187a228f2"
  integrity sha512-nnWLa/NwZSt4KQJu51MYlCcSQ5g7INpOrOMt4XV8j4dqTXdmlUmSHQ8/oLC069ckre0fRsgfvsKwbTdtKLCDkA==
  dependencies:
    async-limiter "~1.0.0"
    safe-buffer "~5.1.0"
    ultron "~1.1.0"

ws@^5.2.0:
  version "5.2.2"
  resolved "https://registry.yarnpkg.com/ws/-/ws-5.2.2.tgz#dffef14866b8e8dc9133582514d1befaf96e980f"
  integrity sha512-jaHFD6PFv6UgoIVda6qZllptQsMlDEJkTQcybzzXDYM1XO9Y8em691FGMPmM46WGyLU4z9KMgQN+qrux/nhlHA==
  dependencies:
    async-limiter "~1.0.0"

ws@^7.0.0, ws@^7.2.5:
  version "7.2.5"
  resolved "https://registry.yarnpkg.com/ws/-/ws-7.2.5.tgz#abb1370d4626a5a9cd79d8de404aa18b3465d10d"
  integrity sha512-C34cIU4+DB2vMyAbmEKossWq2ZQDr6QEyuuCzWrM9zfw1sGc0mYiJ0UnG9zzNykt49C2Fi34hvr2vssFQRS6EA==
```
- [x] I've searched for any related issues and avoided creating a duplicate
      issue.  
- [x] I've checked out: https://pkgs.alpinelinux.org/package/v3.11/community/x86_64/ws and tried to install all dependencies, that didn't seem to work.  
- [x] I've added setUserAgent to browser with linux chrome user agent.  
- [x] I've tried setting port 80 as TCP in my load balancer configuration.  
- [x] Tried a bunch of recommended puppeteer troubleshooting settings for alpine docker from puppeteer docs.  

#### Reproducible in:
- version: 3.3.3
- Node.js version(s): 12.16.3
- OS version(s): Linux

**Comment by ArielFrischer** [comment]
After `await browser.close()` I've added `setTimeout() `to give some more time before starting a new browser and that seemed to do trick!

**Comment by lpinca** [comment]
Add a listener for the `'error'` event on the `WebSocket` object:

```js
ws.on('error', function() {
  // Handle the error.
});
```

Also please update ws to a more recent version.

Refs: https://github.com/websockets/ws/issues/1256.

**Comment by lpinca** [comment]
Closing as answered, discussion can continue if needed.
