### ISSUE TITLE
Cloud we use such a websocket package in front-end project?

### ISSUE THREAD

**Issue by BlueSky5300** [websockets/ws#1764]
We build a backend project using ws. Now we want to let our frontend to support **websocket with headers.**

Cloud this package help us to do that or any other suggestions?

**Comment by lpinca** [comment]
No, you can't use custom headers in the browser. You can use a query string:

```js
const ws = new WebSocket('wss://example.com/?foo=bar&baz=qux');
```

**Comment by BlueSky5300** [comment]
Thanks for your suggestion!
