### ISSUE TITLE
Error EPROTO

### ISSUE THREAD

**Issue by tuphampro** [websockets/ws#1766]
I use ElectronJS, Node.js v12.8.1 error as follows

Error: write EPROTO 2754060296:error:100000f0:SSL routines:OPENSSL_internal:UNSUPPORTED_PROTOCOL:../../third_party/boringssl/src/ssl/handshake_client.cc:569:

    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:83:16) {
  errno: 'EPROTO',
  code: 'EPROTO',
  syscall: 'write'
}

**Code**
    const url = `wss://localhost:8080/plugin`;
    const ws = new WebSocket(url, {
      origin: "localhost",
      rejectUnauthorized: false,
      ciphers: 'ALL',
    });

**Comment by lpinca** [comment]
Try to use a [tls socket](https://nodejs.org/api/tls.html#tls_tls_connect_options_callback) directly (without ws) and see if you get the same error.

**Comment by lpinca** [comment]
Also try with the [`--tls-min-v1.0`](https://nodejs.org/api/cli.html#cli_tls_min_v1_0) command line option:

```
node --tls-min-v1.0 index.js
```

I think your server only supports old versions of the protocol.

**Comment by tuphampro** [comment]
I used the old version of Nodejs, I got no errors.

**Comment by lpinca** [comment]
Yes, Node.js now uses TLS 1.2 as default minimum version for security reasons. This is not an issue in ws.
