### ISSUE TITLE
Should calling .close() result in a on('close' ??

### ISSUE THREAD

**Issue by smhk** [websockets/ws#1767]
I'm using a simple ping (exactly like in the doco examples) to close if a connection disappears..

```
if (aClient.isAlive === false) {
	console.log("lost a pingpong... close()")
	return aClient.close();
}
```

Works perfectly.  BUT,

```
wss.on('close', function close(u) {
	clearInterval(interval);
	console.log("\n on('close' happened.");
	...
});

```

It seems the on('close' function is **NOT** called in that case.

Is this correct behavior?

* Note, the example code suggests using terminate() rather than close() if a ping is lost; I tried both; in both cases on('close' is NOT called.

Thanks

**Comment by lpinca** [comment]
The `'close'` event is emitted on the `WebSocket` object, not the server. In your example, it is emitted on `aClient`.

**Comment by smhk** [comment]
Ah, of course, thanks for the great explanation.

So, one could not really put all one's disconnection code in the "on close' function - there are two possible paths.

Thanks again!  This library should have a tip jar

**Comment by smhk** [comment]
ciao @lpinca I wonder if we could contact you (email?) regarding a work project - sorry, I am too old to know twitter! :)  my email is easily on my profile there, saluti !
