### ISSUE TITLE
express-session-parse example not working on server

### ISSUE THREAD

**Issue by sachinbaghel14** [websockets/ws#1770]
i have tried to run this example on the heroku server but it is not working there. It's working fine when i run it on my computer.

**Comment by lpinca** [comment]
Please fill the issue template and create a test case to reproduce the issue. As is this issue report is useless.

**Comment by sachinbaghel14** [comment]
sorry actually i am new in this. 
simulate login button is working but when i click on open websocket connection nothing happens and when i click on send websocket message it prints "No websocket connnection".
when i tried to find out the issue with doing some console.log() i found that 

```
if (!request.session.userId) {
      console.log("socket destroy");
      socket.destroy();
      return;
    }

```
this if condition becomes true and it destroy the socket. 
 
i have uploaded the example as it is on the heroku server and when i run this example on my localhost it works fine.

**Comment by lpinca** [comment]
Are you using multiple dynos? If so yry to enable [session affinity](https://devcenter.heroku.com/articles/session-affinity).

**Comment by sachinbaghel14** [comment]
ok i will try 
i want to ask one more question actually i want a authentication mechanism for websocket and i have seen people using jwt token but i am confused how should client pass that token to the websoket server for authentication.

i have seen many examples where people passing there token through the URL like this 

`const ws = new WebSocket("wss://somedomain.com?token=<token>");` 

but is this secure or should i stick to the express-session-parse example?

**Comment by lpinca** [comment]
> but is this secure

yes that is ok as long as the token is sent over HTTPS.

**Comment by lpinca** [comment]
Any updates?

**Comment by sachinbaghel14** [comment]
still not working nothing happens.

**Comment by lpinca** [comment]
Ok, I'm closing this anyway as it isn't an issue in the library. Discussion can continue if needed.
