### ISSUE TITLE
Issues from 7.2.1 to 7.2.2

### ISSUE THREAD

**Issue by nadirhamid** [websockets/ws#1771]
hello,

I have recently been having issues with your websocket server code. The server code you have done seemed to work fine at version 7.2.1 and before that. However, once I upgraded to the latest version, the code no longer seemed to work due to some websocket "MASK" related issue.

based on what I have been able to find, it seems that the changes from 7.2.1 to 7.2.2 may have caused these issues for me.

looking at your commit:
https://github.com/websockets/ws/commit/4f293a8726092c75539287dd07358afaf151a2e5

lines 231-240 may be the root cause of the issue.

as I am clueless of how to fix this currently, I was wondering if you could explain what your changes do, and if you feel the error is that my websocket client code is not up to date or something.

keep in mind I have been able to use this libary fine:
https://www.npmjs.com/package/websocket

some questions for you:
- what is the reasoning behind the "MASK" change from 7.2.1 to 7.2.2 ?
- do you feel your websocket library is the most up to date in terms of the RFC ?
- can you explain what kind of tests you did to validate the binary OP code ?
- are you able to share psuedo code for the MASK bit logic ?

here is the link to the project I reference your NPM package in:
https://github.com/nadirhamid/asterisk-audiofork

link to the underlying C code that creates the websocket connections:
https://github.com/asterisk/asterisk/blob/16.6/res/res_http_websocket.c
see lines 345 for the "ast_websocket_write" implementation.

can you please share your thoughts - whether you believe the client side code is incorrect, or if your code is incorrect ? I am trying to resolve this issue on the client side so any help is appreciated.

thanks

**Comment by lpinca** [comment]
It's a client issue, frames coming from a client must be masked. From https://tools.ietf.org/html/rfc6455#section-5.1

> The server MUST close the connection upon receiving a frame that is not masked.

> do you feel your websocket library is the most up to date in terms of the RFC ?

We try to be spec compliant, yes.

> can you explain what kind of tests you did to validate the binary OP code ?

We use the opcode bit of each frame as defined here https://tools.ietf.org/html/rfc6455#section-5.2

> are you able to share psuedo code for the MASK bit logic ?

It is a simple bit check https://github.com/websockets/ws/blob/88d0345997ea14b262519c7d5b5baaf6f9d78035/lib/receiver.js#L230

**Comment by nadirhamid** [comment]
thanks. I have confirmed it was a client side issue. I will be using a patched version of the client so that it works with your server library.

**Comment by lpinca** [comment]
Closing as answered.
