### ISSUE TITLE
send-message-to-specific-client-with-ws-and-node-js

### ISSUE THREAD

**Issue by ZuccRoger** [websockets/ws#1772]
I have the same question like 
[https://stackoverflow.com/questions/4647348/send-message-to-specific-client-with-socket-io-and-node-js](url)

**Comment by lpinca** [comment]
Please fill the issue template. This issue tracker is only for bugs in the library.

Anyway to answer your question you just have to get a reference to the correct `WebSocket` instance and use `ws.send()` on it.

```js
for (const ws of wss.clients) {
  if (ws === yourSpecificClient) {
    ws.send(message);
  }
}
```
