### ISSUE TITLE
DeprecationWarning: Buffer()

### ISSUE THREAD

**Issue by promatik** [websockets/ws#1774]
After update to electron 9, which uses Chromium v83, there's this Deprecation Warning about Buffer:
```
(node:18992) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. 
Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead
```

I've been checking ws code, and I couldn't find any use of `new Buffer()` it may be some dependency, is there any way to know which dependency is doing this? If it doesn't get updated soon this may become a bigger problem in future.

**Comment by lpinca** [comment]
ws ha no dependency and we moved away from `new Buffer()` a long ago, not sure if you can try to use the `--trace-deprecation` flag which show stack traces on deprecations on Node.js (not sure if it is available on Electron).

**Comment by lpinca** [comment]
Closing as this is not a ws issue.

**Comment by promatik** [comment]
Thank you @lpinca didn't know about `--trace-deprecation`, I used it  and I was able to spot the issue.
There is already a PR on the lib to change `new Buffer()`.
