### ISSUE TITLE
On a server: .readyState still TRUE even though connection is absolutely closed

### ISSUE THREAD

**Issue by smhk** [websockets/ws#1775]
Seems to be that  .readyState still TRUE even though connection is absolutely closed:

```
const wss = new WebSocket.Server({ port: 666 });
wss.on('connection', function connection(u) {
    ... etc etc
    
    u.on('close', function incoming(m) {
        handleFoundApparentDisconnection()
    });

```
So the connection is totally closed...

Note that `connections` is just a set I manage myself in the usual way

```
var connections = [];
wss.on('connection', function connection(u) {
       u.name = "john" etc
      connections.push(u)
```

So the connection is totally closed

I then **message all connections...**

```
connections.forEach(function tell(c) {
    if (c.readyState == WebSocket.OPEN)
        c.send(.. some message)
});
```

In fact on that one `.readyState == WebSocket.OPEN` is still TRUE

i.e. it DOES try to do this

        c.send(.. some message)

(giving an error/crash correctly)

how can it be that .readyState is still true when the connection is completely closed?  'closed' was indeed already called.

(Obviously, i can remove that connection from the list, but, that does not solve the problem. In a million other places one could be .send and check that the socket is open.)

**Comment by lpinca** [comment]
> how can it be that .readyState is still true when the connection is completely closed? 'closed' was indeed already called.

It can't be. Double check that the `WebSocket` that emitted the `'close'` event and the one whose ready state is `WebSocket.OPEN` are the same `WebSocket`.  This loop

```js
connections.forEach(function tell(c) {
  if (c.readyState == WebSocket.OPEN)
    c.send(.. some message)
})
```

does not give you `WebSocket` objects that already emitted the `'close'` event.

**Comment by lpinca** [comment]
Actually that loop could give closed WebSockets if you manage the `connections` set yourself but I find it hard to believe that the ready state of a WebSocket that emitted `'close'` is changed back to `WebSocket.OPEN`. See https://github.com/websockets/ws/blob/d09daaf67c282e301eeebe21797215ddffd819c5/lib/websocket.js#L178-L192

**Comment by smhk** [comment]
@lpinca Thanks

• yes 'connections' is just a list that I manage myself (notice edit)

HOpwever simply consider this code:

```
connections.forEach(function tell(c) {
    if (c.readyState == WebSocket.OPEN)
        c.send(.. some message)
});
```

**Comment by lpinca** [comment]
What is the error message and stack? It's hard to tell without a test case to reproduce the issue.

**Comment by smhk** [comment]
The error message is just

**Comment by smhk** [comment]
@lpinca  here's an example:

![Screen Shot 2020-07-09 at 2 35 58 PM](https://user-images.githubusercontent.com/3938526/87083214-df8c1480-c1f1-11ea-97bd-ba4cbd651ba3.png)

Notice it works perfectly if you try the actual connection "u"

But if you look in the list of connections, it is still "3"

How can that be?

(I did the test with only one connection, so, it's definitely the same one)

**Comment by lpinca** [comment]
I see nothing wrong in that snippet.

1. The `'close'` event is emitted.
1. The listeners of the `'close'` event take two arguments. The first is the code (a number), the second is the reason. So `m` in your example is the code and `mrs` is `undefined` because it's the value of the `readyState` property on a number. For example`const n = 1000; console.log(n.readyState)`.
1. You then look up for the index of the `u` object in the `connections` array and use that index to access the item in the array and log its `readyState` which is `3` or `WebSocket.CLOSED` as expected.

The error is that `m` is the close code not and not a `WebSocket` object.

**Comment by smhk** [comment]
Ayy, (2) sorry, in the post I stupidly typed "m.readyState" rather than "u.readyState".

Regarding the issue at hand, I will close this issue.

I will carefully investigate and if I can repro I will alert

Thank you as always!
