### ISSUE TITLE
How to send data outside the scope.

### ISSUE THREAD

**Issue by hypo-thesis** [websockets/ws#1780]
- version: "ws": "^7.3.1",
- Node.js version(s): v14.4.0
- OS version(s): windows 10 

#### Steps to reproduce:

```
wss.on('connection', ws => {
  console.log('user is connected to the server')
  const t = setInterval(() => {
    ++count
    ws.send(count)
  }, 2000);
})
```

My concern is: 

1. Is using `setInterval `a right approach to have live feed?

**Comment by lpinca** [comment]
This is not a bug in the library. The issue tracker is only for bugs. For general support questions please use another channel.

> Is using setInterval a right approach to have live feed?

It's up to you. Generally you send data when you need to. If you need to send that number every 2 sec that it ok.
