### ISSUE TITLE
extraneous data in websocketstreams

### ISSUE THREAD

**Issue by YoDaMa** [websockets/ws#1781]
This is complicated, but bear with me. 

The issue is that there is extraneous data showing up in the WebsocketStream that the server does not receive. 

This is what the websocket is receiving. I am just printing it via the following lines of code: 
```js
wss.on('connection', function connection(ws) {
  const duplex = WebSocket.createWebSocketStream(ws, { encoding: 'utf8'})

  duplex.on('data', function (data) {
    console.log('duplex data: ')
    let i;
    for (i = 0; i < data.length; i++) {
        process.stdout.write(data.charCodeAt(i).toString(16) + " ")
    }
    console.log(" ");
  })
  ws.on('message', function incoming(message) {
      manual_duplex.push(message);
      console.log('received: %o', message)
  })
})
```

```log
received: <Buffer 10>
received: <Buffer 51>
received: <Buffer 00 04>
received: <Buffer 4d 51 54 54>
received: <Buffer 04>
received: <Buffer c6>
received: <Buffer 00 0a>
received: <Buffer 00 0f>
received: <Buffer 6d 71 74 74 6a 73 5f 35 64 33 35 36 30 63 61>
received: <Buffer 00 07>
received: <Buffer 57 69 6c 6c 4d 73 67>
received: <Buffer 00 1f>
received: <Buffer 43 6f 6e 6e 65 63 74 69 6f 6e 20 43 6c 6f 73 65 64 20 61 62 6e 6f 72 6d 61 6c 6c 79 2e 2e 21>
received: <Buffer 00 04>
received: <Buffer 64 65 6d 6f>
received: <Buffer 00 04>
received: <Buffer 64 65 6d 6f>
```

```log
duplex data:
10 51 0 4 4d 51 54 54 4 fffd 0 a 0 f 6d 71 74 74 6a 73 5f 35 64 33 35 36 30 63 61 0 7 57 69 6c 6c 4d 73 67 0 1f 43 6f 6e 6e 65 63 74 69 6f 6e 20 43 6c 6f 73 65 64 20 61 62 6e 6f 72 6d 61 6c 6c 79 2e 2e 21 0 4 64 65 6d 6f 0 4 64 65 6d 6f
```

The issue is that there is a difference between what the duplex is emitting as data and what the websocket receives. If you look at the `duplex data` log, there is a two byte value, `fffd`, that is not received on the websocket yet it is given as data consistently through the stream. 

If this is confusing I can provide more in depth reproduction instructions. Perhaps you know why this is happening, like if I am using the duplex stream incorrectly.

**Comment by lpinca** [comment]
Try to remove the `{ encoding: 'utf-8' }` option if you are receiving binary data. That option will decode buffers to strings using the specified encoding.
