### ISSUE TITLE
pipe WebSocketStream to a Transform stream, the output data is  ill-formed

### ISSUE THREAD

**Issue by qiulang** [websockets/ws#1782]
Hi, this is a question and I've searched for any related issues and avoided creating a duplicate issue.

I need the ws server to forward the websocket messages (sip over websocket) to my sip server. So I set up the server like this

```
const wss = new WebSocket.Server({ port: 8080 })
var sipServer = net.createConnection(sipPort, sipHost)

wss.on('connection', function connection(ws) {
    const duplex = WebSocket.createWebSocketStream(ws)
    ws.on('message', function incoming(message) {
        duplex.pipe(server).pipe(duplex) //this sends the sip messages back and forth to my sip server
    })
})

```

It works but because my sip sever can't handle the **ws** keyword in websocket message, e.g.  
`transport=wss` so I need to change that to `transport=tcp`

I wrote 2 `Transform` streams to do that 

```
const { Transform } = require('stream')
let ws2tcp = new Transform({
    transform(chunk, encoding, callback) {
        let raw = chunk.toString()
        let transformed = ... // replace the wss keyword in raw to tcp 
        callback(null, transformed)
    }
})

let tcp2ws = new Transform({
    transform(chunk, encoding, callback) {
        let raw = chunk.toString()
        let transformed = ... // replace the tcp keyword in raw to wss 
        callback(null, transformed)
    }
})

wss.on('connection', function connection(ws) {
    const duplex = WebSocket.createWebSocketStream(ws)
    ws.on('message', function incoming(message) {
        duplex.pipe(ws2tcp).pipe(server).pipe(tcp2ws).pipe(duplex)
    })
})

```

But that does not work as I expected. The sip server logs shows that it will receive one message with the same data copied several times.  When I debug the issue and set the breakpoint in **transform** function I also found the breakpoint will hit several times with the same chunk of data. I can't figure out why but I guess maybe this is the reason my sip server received the ill-formed data.

So can you shed some light on it ?

Thanks a lot

**Comment by lpinca** [comment]
```js
ws.on('message', function incoming(message) {
  duplex.pipe(ws2tcp).pipe(server).pipe(tcp2ws).pipe(duplex)
})
```

This will call `duplex.pipe()` for every message.

**Comment by lpinca** [comment]
Also the `Transform` streams might not work as you expect depending on the implementation. The `wss` keyword might be split between different chunks. For example:

chunk 1

```
w
```

chunk2

```
ss
```

**Comment by qiulang** [comment]
Hi thanks for replying to my message. For your second comment I know wss keyword might be split between chunks but because each sip message is ended with a newline so in my transform function I will check if the raw string is ended with newline, if not I just return call(). I think this may fix the problem.

But I still don't understand your first comment _duplex is piped multiple times to ws2tcp._

When I debug my transform function I found it may be called several time with the same chunk of data, the buffer content was the same. But why was it called several time ?

**Comment by qiulang** [comment]
Oh I see what you mean  _duplex is piped multiple times to ws2tcp._

I have changed to 

```
wss.on('connection', function connection(ws) {
    const duplex = WebSocket.createWebSocketStream(ws)
    duplex.pipe(ws2tcp).pipe(server).pipe(tcp2ws).pipe(duplex)
    ws.on('message', function incoming(message) {
           //It seems that I don't need to do anything here now.
    })
})
```

**Comment by lpinca** [comment]
Yes, you don't need to handle the `'message'` event when using `WebSocket.createWebSocketStream()`.

**Comment by qiulang** [comment]
Thanks for the support!
