### ISSUE TITLE
How do I deal with the situation that client closes the connection and issues a new one ?

### ISSUE THREAD

**Issue by qiulang** [websockets/ws#1783]
Hi this is a question and it is also related to my previous question https://github.com/websockets/ws/issues/1782

When client close the connection and issue a new one, it got the reply **WebSocket ws://localhost:8090 closed**

I don't know how to deal with this case and my server code is like this. 

```
wss.on('connection', function connection(ws) {
    const duplex = WebSocket.createWebSocketStream(ws)
    duplex.pipe(ws2tcp).pipe(server).pipe(tcp2ws).pipe(duplex)
    ws.on('open', function open() {
        console.log('connected');
    })
    ws.on('message', function incoming(message) {

    })
    ws.on('close', function close() {
       //When client closes the connection and issues a new one, close is hit again.
        console.log(`disconnected: `)
    })
})
```

**Comment by lpinca** [comment]
There is not much you can do about it. When the client opens a new connection a new `'connection'` event is emitted. The `'close'` event is emitted only once per connection.

**Comment by qiulang** [comment]
Sorry I didn't say my question clearly. 
When client open a new connection I actually got **another** close event, because there were 2 'disconnected:' at console.log . So I was confused, why ? I just want to the code to handle the new connection. How ?

**Comment by qiulang** [comment]
Please check the screenshot here, when the client closes the connection I got a close event as expected 

<img width="1379" alt="Screen Shot 2020-08-14 at 9 18 06 PM" src="https://user-images.githubusercontent.com/516243/90253550-e69ee600-de73-11ea-828a-af814d66cccb.png">

But when it issues another connection I got a second close event. Were you suggesting the client was actually using the same websocket connection instead of using a new one ??

<img width="1417" alt="Screen Shot 2020-08-14 at 9 19 01 PM" src="https://user-images.githubusercontent.com/516243/90253748-409fab80-de74-11ea-9d2a-af81e9a4fae4.png">

**Comment by lpinca** [comment]
The client uses a new connection every time.

**Comment by qiulang** [comment]
Then why did I got 2 "close the websocket connection" on console.log ?

I just want to handle the new connection. How ?

**Comment by lpinca** [comment]
> Then why did I got 2 "close the websocket connection" on console.log

I don't know, it's your code. Make sure you are opening only one connection.

```js
const WebSocket = require('ws');

const server = new WebSocket.Server({ port: 0 }, function() {
  const { port } = server.address();
  const ws = new WebSocket(`ws://localhost:${port}/?token=123456`);

  ws.on('message', function(message) {
    console.log(message.toString());
  });
  ws.on('open', function() {
    ws.send('foo');
    ws.close();
  });
});

server.on('connection', function(ws, req) {
  const token = new URL(req.url, 'ws://a.b').searchParams.get('token')
  console.log('connection %s', token);

  const duplex = WebSocket.createWebSocketStream(ws);

  duplex.pipe(duplex);

  ws.on('close', function() {
    console.log('close %s', token);
  });
});
```

**Comment by lpinca** [comment]
This is not an issue in the library. Please do not open issues for general support questions.

**Comment by qiulang** [comment]
Sorry for opening the support question here.
Where is the place to ask this kind of question ?

**Comment by lpinca** [comment]
We don't have an official channel for support questions. You can try with SO.

**Comment by qiulang** [comment]
Thanks for the answers and taking time into my question.

**Comment by lpinca** [comment]
@qiulang if you want to get some help, my suggestion is to create a minimal reproducible test case. A piece of code as small as possible, with possibly no dependencies that can be run and reproduces the unexpected behavior. Something like the code snippet I posted above.

Other people know nothing and don't care about your code. Chances are you find the bug yourself when writing the minimal reproducible test case.

**Comment by qiulang** [comment]
@lpinca I know and I was trying to reproduce the problem but because I just jssip and it is not that easy to create a minimal reproducible test case. 

I check jssip code carefully https://github.com/versatica/JsSIP/blob/master/lib/WebSocketInterface.js 
and I still can't find the reason why the second time connection will get closed immediately after it connects.

The close code at server side is 1005. I also asked at jssip google group and no response so I asked you

**Comment by lpinca** [comment]
If the status code is 1005 it means the client sent an empty close frame. It is clean closure. I have no idea why the client closes the connection.

**Comment by lpinca** [comment]
I think the second `'close'` event is the result of the second connection being closed. To verify that the `'close'` event is emitted only once you can use something like this:

```js
server.on('connection', function (ws, req) {
  let closeCalled = false;

  ws.on('close', function () {
    assert(!closeCalled);
    closeCalled = true;
  });
});
```

**Comment by qiulang** [comment]
Hi I used wireshark to check who closes who and from the wireshark it was the server closed the connection,


![ws_pcapng_and_npm_run_ws___tee_output](https://user-images.githubusercontent.com/516243/90463317-3401a880-e13d-11ea-99b0-c4bda7d249e0.png)

**Comment by qiulang** [comment]
OK I finally figure our why!  
It was because here `duplex.pipe(ws2tcp).pipe(server).pipe(tcp2ws).pipe(duplex)`
So when the first connection closes all streams are closed too, so when I got the 2nd connection I need to create a whole new set of streams!

Thanks a lot for the help!!

**Comment by lpinca** [comment]
> when I got the 2nd connection I need to create a whole new set of streams

Yes, correct.
