### ISSUE TITLE
500 (Internal Server Error) on calling ws

### ISSUE THREAD

**Issue by hypo-thesis** [websockets/ws#1784]
#### Reproducible in:

- "ws": "^7.3.1",
- Node.js version(s): v14.4.0
- OS version(s): Linux Ubuntu 18.04 LTS

So I followed one of your instructions and I ended up with the following code 

```
const server = https.createServer({
  cert: fs.readFileSync('/www/server/panel/vhost/cert/mydomain.co/fullchain.pem'),
  key: fs.readFileSync('/www/server/panel/vhost/cert/mydomain.co/privkey.pem')
});

const wss = new Websocket.Server({ server })
server.listen(8082)
```

The SSL keys are valid and working on the website and the website seems to make direct calls through 
`const wss = new Websocket.Server({ port: 8082 })` but when I introduce the code above instead of this one, I get error 500 as 
![jkjkjk](https://user-images.githubusercontent.com/28728305/90344535-44256500-e023-11ea-8a42-c5b91dd64166.jpg) 

I am not sure How I can safely use WSS instead of WS. 
I call the socket from the client side via : const ws = new WebSocket('ws://mydomain.co:8082')
Please help me with this

**Comment by lpinca** [comment]
Use

```js
const ws = new WebSocket('wss://mydomain.co:8082');
```

instead of

```js
const ws = new WebSocket('ws://mydomain.co:8082');
```

By the way, you are getting 500 on a XHR request not a WebSocket request.

**Comment by hypo-thesis** [comment]
> Use
> 
> ```js
> const ws = new WebSocket('wss://mydomain.co:8082');
> ```
> 
> instead of
> 
> ```js
> const ws = new WebSocket('ws://mydomain.co:8082');
> ```
> 
> By the way, you are getting 500 on a XHR request not a WebSocket request.

It is the same deal with wss.
I understand it is 500 but it occurs only when I add the code above. 
I'll look into

**Comment by lpinca** [comment]
This is not an issue in the library. For general support questions please use another channel.
