### ISSUE TITLE
server.handleUpgrade() causes an attempt to reconnect the ws socket on refresh

### ISSUE THREAD

**Issue by hypo-thesis** [websockets/ws#1787]
I am running a nodejs application which runs great the first time I use it but when I refresh and enter the new data Node crashes and gives me this. The error looks like this :

```
/www/wwwroot/domain.to/node_modules/ws/lib/websocket-server.js:267
      throw new Error(
      ^
Error: server.handleUpgrade() was called more than once with the same socket, possibly due to a misconfiguration
    at WebSocketServer.completeUpgrade (/www/wwwroot/domain.to/node_modules/ws/lib/websocket-server.js:267:13)
    at WebSocketServer.handleUpgrade (/www/wwwroot/domain.to/node_modules/ws/lib/websocket-server.js:245:10)
    at Server.upgrade (/www/wwwroot/tehran.us.to/node_modules/ws/lib/websocket-server.js:89:16)
    at Server.emit (events.js:327:22)
    at onParserExecuteCommon (_http_server.js:646:14)
    at onParserExecute (_http_server.js:587:3)
```
Here is my current config :

"ws": "^7.3.1",
Node.js version(s): v14.4.0
OS version(s): Linux Ubuntu 18.04 LTS
 
I am not sure if this a bug with WS or nodejs but the socket is created twice upon refreshing. Is there a way to avoid this recreation? How can I assure every user from each browser can access the application and reuse it?

This is the rest of the code for partial reproduction :

```
const app = express();
const options = {
key: fs.readFileSync('./key.pem'),
cert: fs.readFileSync('./cert.pem')
};
const server = https.createServer(options, app)

server.listen(3000, function () {
  console.log("Express server listening on port " + 3000);
});
I also use Websocket on the same end point and the code looks like this :

const wss = new Websocket.Server({ server })
    console.log(url)
    wss.on('connection', ws => {
        console.log('user is connected to the server #mainpage')
```

**Comment by lpinca** [comment]
It is an incorrect usage in your code. You are creating two `WebSocket` which share the same underlying `net.Socket`. This is not allowed.

If you use `const wss = new Websocket.Server({ server });`, you can't use `wss.handleUpgrade()`. If you want to call `wss.handleUpgrade()` manually you have to use the "no server" mode: `const wss = new Websocket.Server({ noServer: true });`.

**Comment by hypo-thesis** [comment]
> It is an incorrect usage in your code. You are creating two `WebSocket` which share the same underlying `net.Socket`. This is not allowed.
> 
> If you use `const wss = new Websocket.Server({ server });`, you can't use `wss.handleUpgrade()`. If you want to call `wss.handleUpgrade()` manually you have to use the "no server" mode: `const wss = new Websocket.Server({ noServer: true });`.

I actually never used `wss.handleUpgrade()` knowingly and I am not sure how it is called. Let me try the `noServer `mode and report back.

**Comment by lpinca** [comment]
Then is caused by one of your dependencies, see https://github.com/websockets/ws/issues/1704, https://github.com/websockets/ws/issues/1737, https://github.com/websockets/ws/issues/1738, https://github.com/socketio/engine.io/issues/600.

**Comment by hypo-thesis** [comment]
> Then is caused by one of your dependencies, see #1704, #1737, #1738, [socketio/engine.io#600](https://github.com/socketio/engine.io/issues/600).

If I use `noServer `I cannot use SSL anymore, is that correct? Is there away to use wss and `noServer `option?

**Comment by lpinca** [comment]
> If I use `noServer` I cannot use SSL anymore, is that correct?

No, it is totally unrelated. You can use an external HTTPS server.

```js
const server = https.createServer(options);

server.on('upgrade', function (request, socket, head) {
  wss.handleUpgrade(request, socket, head, function (ws) {
    wss.emit('connection', ws, request);
  });
});
```

> I think this is happening because my code runs once without error, the second time I do not close ws so it tries to reopen the port which it cannot and then the error occurs. I tried to close the socket with ws.close() at a timer but I don't think this is the correct way of doing this.

It doesn't matter, the browser closes the connection when you refresh the page.

**Comment by lpinca** [comment]
The problem is that your code calls `wss.handleUpgrade()` more than once for the same socket. This could happen for example if you share the HTTP(S) server with other modules.

It could be that one of your dependencies is trying to handle the `'upgrade'` event as shown above. In that case there would be two `handleUpgrade()` calls with the same `socket` argument when the event is emitted. One from your directly written code and the other from from the dependency code.

Hope it makes sense.

**Comment by hypo-thesis** [comment]
I do not have any module that uses it. The code is barely 20 lines actually. the socket is : 

```
export default async (url, server) => {
    const wss = new Websocket.Server({ server })
    console.log(url)
    
    wss.on('connection', ws => {
        console.log('user is connected to the server #mainpage')
        ws.send(JSON.stringify({
            percentage: 100,
            status: done,
            fileName: nameofmyfile
        }))
    })
    wss.on('close', ws => {
        ws.send('connection close')
    })
}
```

which is called from `createVideo(req.query.data, server)`

```
const app = express();

const server = https.createServer(options, app)

server.listen(3000, function () {
  console.log("Express server listening on port " + 3000);
});
app.use(function (req, res, next) {
  res.header("Access-Control-Allow-Origin", "*");
  res.header("Access-Control-Allow-Headers", "Origin, X-Requested-With, Content-Type, Accept");
  next();
});

app.get('/x', function (req, res) {
  // console.log(req.query.data)
  res.status(200).json({ data: 'works !' })
  createVideo(req.query.data, server)
});
```

And that is it. 1st time runs fine I get the databack, on refresh node crashes on the server and gives me the error above. Is it Express related? Should I ditch Express?

**Comment by lpinca** [comment]
```js
export default async (url, server) => {
    const wss = new Websocket.Server({ server })
    console.log(url)
    
    wss.on('connection', ws => {
        console.log('user is connected to the server #mainpage')
        ws.send(JSON.stringify({
            percentage: 100,
            status: done,
            fileName: nameofmyfile
        }))
    })
    wss.on('close', ws => {
        ws.send('connection close')
    })
}
```

This creates a new `WebSocket` server every time the function is called and it seems you are calling it from the handler of `app.get('/x')`. This is wrong, you should create a single `WebSocket` server and use only the existing `WebSocket` connection, if the is one when the user visits `/x`.

Take a look at this example https://github.com/websockets/ws/blob/master/examples/express-session-parse/index.js to get an idea.

When the user visit `/x` you get the `WebSocket` connection from the map of `WebSocket` connection and use it.
