### ISSUE TITLE
Cannot connect with hostname in Windows.

### ISSUE THREAD

**Issue by Knautiluz** [websockets/ws#1790]
I am using Electron 9.2.1 and ws client. In Windows, the connection never finish or give a error, in Linux its OK

```JAVASCRIPT
WebSocket = require('ws')
//running in 443 (wss)
const ws = new WebSocket('wss://subdomain.mydomain.net')
```
In Windows this last forever without giving an error, in server side i have no logs of this try

**Comment by lpinca** [comment]
I have no idea, it could be the firewall. Try to make a normal HTTPS request to `https://subdomain.mydomain.net` or open a plain TCP connection via `{net,tls}.Socket` and see if it works.

**Comment by Knautiluz** [comment]
> I have no idea, it could be the firewall. Try to make a normal HTTPS request to `https://subdomain.mydomain.net` or open a plain TCP connection via `{net,tls}.Socket` and see if it works.

Yes, it works, almost all WS Clients can connect to it. If helps the address is websocket.knautiluz.net

**Comment by lpinca** [comment]
> Yes, it works.

The WebSocket opening handshake is just a GET request with special headers, so if the HTTPS request works, the WebSocket connection must work too.

> If helps the address is websocket.knautiluz.net

I've just tested from macOS (no Electron) and it works. I don't have a Windows machine at hand.

**Comment by lpinca** [comment]
Does it work from your Windows machine without Electron?

**Comment by Knautiluz** [comment]
> Does it work from your Windows machine without Electron?

Works fine without Electron 😨

**Comment by Knautiluz** [comment]
Find it in Electron repo: https://github.com/electron/electron/issues/25099
