### ISSUE TITLE
How to avoid listening multiple times on ws?

### ISSUE THREAD

**Issue by hypo-thesis** [websockets/ws#1791]
#### Description
I am trying to use WS when an API is called like this : 

```

const server = https.createServer(options, app)
const wss = new Websocket.Server({ server })
app.get('/api', function (req, res) {
  res.status(200).json({ data: 'works !' })
     wss.on('connection', ws => {
        console.log('user is connected to the server #mainpage')
    })
});

```
Now the first time I access the back end I get _user is connected to the server #mainpage_ once. The 2nd time I get 2x and it goes on. If I access the API 100 times I get _user is connected to the server #mainpage_ printed out 100 times.

#### Reproducible in:

- version: 7.3.1
- Node.js version(s): 12.1.1
- OS version(s): windows 10

#### Expected result:

I wish the code to send data through WS just one time.

#### Actual result:

On the 10th time I use the application I get 10 output meaning that the application is listening and adds on.

How can I stop WS from listening once data is sent or check if it is already listening and working just go on with it?

**Comment by lpinca** [comment]
You should add only one listener for the `connection` connection event and _not_ register a new one every time the `/api` endpoint is visited.

Read https://github.com/websockets/ws/issues/1787#issuecomment-680672182 and please do not open issues for general support questions (this is the third time).

**Comment by hypo-thesis** [comment]
Sorry I couldn't figure it out. Won't happen again
