### ISSUE TITLE
Message is always chunked (MQTT)

### ISSUE THREAD

**Issue by Jaarson** [websockets/ws#1793]
- [x] I've searched for any related issues and avoided creating a duplicate
      issue.

#### Description

I'm using Websockets for MQTT messaging. So far works well 👍, but I've noticed that on 'message' event always receives data in 2 chunks. First chunk is only 1 byte long, and the second chunk contains rest of the message (whole message is ~ 20 bytes).
What's could possibly cause this behaviour ? Should I detect if message is split and concat?

#### Reproducible in:

- version: 7.3.1
- Node.js version(s): 14.8.0

#### Steps to reproduce:

1. Basic WS server example `const wss = new WebSocket.Server({ port: 8080, perMessageDeflate: false });`

2. Use any MQTT client to connect (e.g. MQTT Explorer, MQTTX)

#### Expected result:

whole message in one chunk on 'message' event

#### Actual result:

chunked message

#### Attachments:

```
Chunk 1
0:             16

Chunk 2
0:             7
1:             0
2:             4
3:     M       77
4:     Q       81
5:     T       84
6:     T       84
...till the end of message
```

**Comment by lpinca** [comment]
It depends on the other peer and how it sending the data. If you get it in two messages it means the other peer is splitting it in two sperate messages.

**Comment by Jaarson** [comment]
You're right. I've just managed to receive a ~30 byte message in 12 chunks(!) using MQTTBox client. So I'll just need to handle that. Fortunately MQTT packets have its length encoded at the begging, so it should be straightforward to validate if I have complete packed or need to wait for next chunk.
Thanks for your help!

**Comment by lpinca** [comment]
> Fortunately MQTT packets have its length encoded at the beginning

Yes this is common to many protocols. The WebSocket protocol itself specifies the frame payload length in the first bytes of the frame.
