### ISSUE TITLE
indefinite behavior of nodejs/events.once() on WebSocket

### ISSUE THREAD

**Issue by zimtsui** [websockets/ws#1795]
hello guys.

the function `once` of nodejs v12 LTS makes different behaviors between EventEmitter or EventTarget. [REF](https://nodejs.org/dist/latest-v12.x/docs/api/events.html#events_events_once_emitter_name)

>This method is intentionally generic and works with the web platform EventTarget interface, which has no special 'error' event semantics and does not listen to the 'error' event.

`once` makes judgement about whether an emitter is an EventEmitter or an EventTarget according to whether `emitter.addEventListener` is a function. [REF](https://github.com/nodejs/node/blob/e3e0927bb93ed92bcdfe81e7ad9af3d78ccc74fb/lib/events.js#L622)

since WebSocket implements `addEventListener` in

https://github.com/websockets/ws/blob/535c55648db0602735f2ff8466131adfca911dae/lib/websocket.js#L22

`once` will misjudge the emitter to be an EventTarget and it will not listen to `error` event. thus, users cannot do:

```ts
async function connect(){
    ws = new WebSocket('xxx');
    await once(ws, 'open');
}
```

this will be waiting forever if it fails to connect. 

since it's said in docs that 

>This class represents a WebSocket server. It extends the EventEmitter.

, this will mislead users.

but this problem does not exist with nodejs v14, because nodejs v14 makes that judgement via whether `emitter.on` is a function. [REF](https://github.com/nodejs/node/blob/3153c2d3833a8a46d92fde33d2773e63ef21357b/lib/events.js#L667)

i don't think it's a bug, but it'd be better if this problem should be warning in docs

**Comment by lpinca** [comment]
I think https://github.com/nodejs/node/pull/34015 will be backported to Node.js 12 so the issue should only temporary.

**Comment by lpinca** [comment]
I'm closing this as the issue should be fixed in Node.js v12.20.0
