### ISSUE TITLE
Connections stay in CLOSE_WAIT with Node 0.10.x

### ISSUE THREAD

**Issue by nicokaiser** [websockets/ws#180]
After upgrading to Node 0.10 my servers keep accumulating TCP connections in the CLOSE_WAIT state until it hits the max-files limit.

Example server (based on the `ws` README example:

``` javascript
var WebSocketServer = require('ws').Server
  , wss = new WebSocketServer({port: 8080});

wss.on('connection', function(ws) {
  console.log('connection');
  ws.send('something');
  ws.on('close', function() {
    console.log('close');
    //ws.upgradeReq.socket.destroy();
  });
  ws.on('end', function() {
    console.log('end');
  });
});
```
- Run the above server
- Open Chrome console and execute `new WebSocket('ws://localhost:8080/');`  several times (I could not reproduce this issue with `wscat`).
- Hit reload (all the connections close, you see some "close" message in the server output
- `lsof | grep CLOSE_WAIT` lists all the closed connections in CLOSE_WAIT state
- Terminate the server
- `lsof | grep CLOSE_WAIT` is empty

If you modify the server and comment in the destroy line, there are no CLOSE_WAIT connections.

**Comment by mkamioner** [comment]
I think this fixes the issue: https://github.com/websockets/ws/pull/540
