### ISSUE TITLE
"wasClean" is missing in EventEmitter "close" event handler

### ISSUE THREAD

**Issue by Jokero** [websockets/ws#1800]
- [x] I've searched for any related issues and avoided creating a duplicate
      issue.

#### Description

There are different ways to handle close event:
```
ws.onclose = function(event) {};
ws.addEventListener('close', event => {});
ws.on('close', (code, reason) => {});
```
The first two options are using event object with `code`, `reason` and `wasClean` fields. The third option does not have `wasClean`, looks like inconsistency. `wasClean` is quite nice thing and can be used to initiate a reconnection when it's equal to `false`.

Actually `wasClean` is not documented anywhere in API docs.

#### Reproducible in:

- version: 7.3.1
- Node.js version(s): v10.15.0
- OS version(s): macos catalina 10.15.6 

#### Steps to reproduce:

```js
const WebSocket = require('ws');
const ws = new WebSocket('ws://www.host.com/path', {});
ws.on('error', () => {});
ws.on('close', (code, reason, wasClean) => {
    console.log(code, reason, wasClean); // 1006 '' undefined
});
```

#### Expected result:
```
1006 '' false
```

#### Actual result:
```
1006 '' undefined
```

**Comment by lpinca** [comment]
This is done on purpose. The `wasClean` argument is present only when using the `EventTarget` interface to make it consistent with the browser [CloseEvent](https://developer.mozilla.org/en-US/docs/Web/API/CloseEvent).

It is sufficient to check the close code to see if the connection was cleanly closed. When not using custom close codes, anything different from 1000 or 1005 indicates that connection was not cleanly closed.

**Comment by Jokero** [comment]
Ok, thanks for explanation
