### ISSUE TITLE
Using Websocket within Electron and Context Aware Behavior

### ISSUE THREAD

**Issue by SkiBum326** [websockets/ws#1801]
I'm a user of the Websocket module within Electron.

Recently, Electron introduced a change that requires native modules the be context aware:
https://github.com/electron/electron/issues/18397

Since this change, Websocket hangs on connecting to the client in Windows (works fine for Mac OS X).

I'm not very familiar with the mechanics of this change by Electron, but I wondering if this requires a change to the Websocket library to maintain compatibility.

**Comment by lpinca** [comment]
`ws` is not a native module. It has two optional native peer dependencies (`bufferutil` and `utf-8-validate`) but the module works fine without them.

**Comment by lpinca** [comment]
@SkiBum326 I read the description of the referenced issue (https://github.com/electron/electron/issues/18397) and both `bufferutil` and `utf-8-validate` (if you are using them) are NAPI modules so the issue behind https://github.com/electron/electron/issues/25099 should not be https://github.com/electron/electron/issues/18397.

**Comment by lpinca** [comment]
@SkiBum326 I'm closing this. Discussion can continue if needed.
