### ISSUE TITLE
Message ID's

### ISSUE THREAD

**Issue by carlskii** [websockets/ws#1802]
Hi,

I was wondering if there was any way messages sent from the WebSocket server could include an ID that can then be used to determine how to process the message on the client side. e.g. Similar to how Electron's IPC mechanism works. 

Is this possible? 

Best Regards.

**Comment by Jaynator495** [comment]
It's not directly in the Websocket API, however you can implement this by including an ID in your data, for example data I send to the client is {id:{id},data:{payload}}, and then check for it client side

**Comment by lpinca** [comment]
As @Jaynator495 it's up to you. I'm closing this. Discussion can continue if needed.

**Comment by carlskii** [comment]
Perfect thanks
