### ISSUE TITLE
WS with child_process

### ISSUE THREAD

**Issue by carlskii** [websockets/ws#1803]
Hi,

Im using WS with nodes `child_process` to call a command that returns multiple lines via `stdout`. e.g. running a tail on a log file.

What's the best approach for getting the output for each line returned to `stdout` to be sent as a message using WS?

**Comment by lpinca** [comment]
@carlskii this issue tracker is for only for issues in the library. For general support questions please use another channel.

**Comment by lpinca** [comment]
To answer your question, if you are using `child_process.spawn()` you can use something like this:

```js
wss.on('connection', function(ws) {
  const duplex = WebSocket.createWebSocketStream(ws);

  duplex.resume();
  subprocess.stdout.pipe(duplex);
});
```
