### ISSUE TITLE
Websocket Proxy works but errors when used more than once

### ISSUE THREAD

**Issue by shawtylikeamelody** [websockets/ws#1805]
What I am attempting to do is to make a websocket proxy that would connect to websocket servers. It works if you connect to a server only once. If you try multiple times after that it crashes and gives error "Error: server.handleUpgrade() was called more than once with the same socket, possibly due to a misconfiguration." I have tried setting noServer on it but that makes the websocket proxy not work. Heres my code. I would really love the help!

     const WebSocket = require('ws'),
     https = require('https'),
     http = require('http');

     const server_options = {
           key: fs.readFileSync('./ssl/default.key'),
           cert: fs.readFileSync('./ssl/default.crt')
      }

    const server = https.createServer(server_options, app);

    server.on('upgrade', function upgrade(req, socket, head) {

      const wss = new WebSocket.Server({ 
        server: server
       });

      wss.on('connection', function connection(ws) {
        
        console.log(req.url.slice(1))

        // If the URL pathname is "/wss://echo.websocket.org". The proxy would connect to "wss://echo.websocket.org"

        const client = new WebSocket(req.url.slice(1));
  
        ws.on('message', function incoming(message) {
   
          client.send(message)

        });
      
        client.on('message', function incoming(data) {

         ws.send(data)

        })

      }); 

    });

    server.listen(9000);

**Comment by lpinca** [comment]
You are using it incorrectly. Please refer to the examples in the README. If you want to handle the upgrade yourself you have to set the `noServer` option to `true` and use `WebSocketServer.prototype.handleUpgrade()`.

```js
const https = require('https');
const WebSocket = require('ws');

const server_options = {
  key: fs.readFileSync('./ssl/default.key'),
  cert: fs.readFileSync('./ssl/default.crt')
};

const server = https.createServer(server_options, app);
const wss = new WebSocket.Server({ noServer: true });

wss.on('connection', function connection(ws, req) {
  const client = new WebSocket(req.url.slice(1));

  ws.on('message', function incoming(message) {
    client.send(message);
  });

  client.on('message', function incoming(data) {
    ws.send(data);
  });
});

server.on('upgrade', function upgrade(req, socket, head) {
  wss.handleUpgrade(req, socket, head, function done(ws) {
    wss.emit('connection', ws, req);
  });
});

server.listen(9000);
```

**Comment by lpinca** [comment]
Closing as answered. Discussion can continue if needed.
