### ISSUE TITLE
Client authentication example using nodejs https module

### ISSUE THREAD

**Issue by extremety1989** [websockets/ws#1806]
Nodejs v12.19.0
Linux 

ws with https module

when i log request from example "Client authentication"
it logs all hashes from  private.key and public.key etc..

Is it normal ?

server.on('upgrade', function upgrade(request, socket, head) {
  console.log(request);
//  key: '-----BEGIN PRIVATE KEY-----\n' +
// content of my private key hash

**Comment by lpinca** [comment]
No it's not. `request` is an instance of `http.IncomingMessage`. Check your code.
Also please do not open issues for general support questions. This issue tracker is only for bugs in the library.

**Comment by extremety1989** [comment]
@lpinca aa okey sorry for that , i thought it was a bug with ws library

**Comment by extremety1989** [comment]
@lpinca my code is the same as in example,except i am using nodejs https instead of http, also my client is mobile application

**Comment by lpinca** [comment]
if you get something like this

```
IncomingMessage {
  ...
  socket: <ref *1> TLSSocket {
    ...
    server: Server {
      ...
      key: <Buffer xx xx xx ... xxx more bytes>,
      ...
    }
    ...
}
```

then yes it's normal.
