### ISSUE TITLE
WebSocketStream does not emit 'end', 'close' events in 'pipe()' case

### ISSUE THREAD

**Issue by rickzhr** [websockets/ws#1809]
#### Description

WebSocketStream does not emit 'end', 'close', 'error' etc events when its 'readableFlowing' state is not true.
This causes these events not emitted on WebSocketStream
1. before 'data' event callback is added.
2. after pause() is called
3. when using pipe() with net.Socket (since WebSocketStream may also be paused when unpiping)

Noting that net.Socket is always able to emit these events in the same case.

#### Reproducible in:

- version: 7.3.1 and master branch
- Node.js version(s): 12.x
- OS version(s): osx 10.11

#### Steps to reproduce:
Run the test codes below to reproduce the issue.

In the test, we have a pair of `net.Socket` and a pair of `ws.WebSocket` as below.
`serverSocket <===> clientSocket     << pipe >>    clientWSStream <===> serverWebSocket`

If `serverSocket` calls `end()`,  both 'end' and 'close' event should be emitted on `clientWSStream`
However, in this case, neither 'end' nor 'close' event is emitted.
```javascript
const WebSocket = require('ws');
const net = require('net');

function startServer() {
    let server = net.createServer((socket)=>{
        // hold the server socket
        serverSocket = socket;
        socket.on('close', ()=>{
            server.close();
        })
    });
    server.listen(9901, startClient);
}

function startClient() {
    clientSocket = net.connect(9901, "localhost", ()=>{
        startWSServer();
    });
}

function startWSServer() {
    let wss = new WebSocket.Server({ port: 9902 }, startWSClient);
    wss.on('connection', function connection(ws) {
        ws.on('close', ()=>{
            wss.close();
        });
    });
}

function startWSClient() {
    let ws = new WebSocket('ws://localhost:9902/');
    clientWSStream = WebSocket.createWebSocketStream(ws);
    ws.on('open', function open() {
        onWebSocketOpen();
    });
}

function onWebSocketOpen() {
    clientWSStream.on('finish', () => {
        // can be emitted
        console.log("clientWSStream on finish");
    });

    clientWSStream.on('end', () => {
        // not emitted
        console.log("clientWSStream on end");
    });

    clientWSStream.on('close', () => {
        // not emitted
        console.log("clientWSStream on close");
    });

    clientSocket.pipe(clientWSStream);
    clientWSStream.pipe(clientSocket);

    serverSocket.end();

    // Workaround - uncomment the following and then 'end', 'close' would be emitted
    // clientWSStream.on('finish', ()=>{
    //     clientWSStream.resume();
    // });
}

let clientSocket;
let clientWSStream;
let serverSocket;
startServer();
```

#### Expected result:

WebSocketStream is expected to emit 'end', 'close' events

#### Actual result:

WebSocketStream does not emit 'end', 'close' events

**Comment by lpinca** [comment]
This is expected. A `Duplex` stream does not emit `'end'` and `'close'` if it is paused.

```js
const { Duplex } = require('stream');

const duplex = new Duplex({
  read() {},
  write(chunk, encoding, callback) {
    callback();
  }
});

duplex.on('end', function () {
  console.log('end');
});

duplex.on('close', function () {
  console.log('close');
});

duplex.push('foo');
duplex.push(null);

duplex.end();
```

You can work around this by listening to the `'unpipe'` event and resuming the stream:

```js
clientWSStream.on('unpipe', function() {
  this.resume();
});
```

**Comment by lpinca** [comment]
Closing this as answered. Discussion can continue if needed.
