### ISSUE TITLE
Help! Run ws on the same port as a http Express?

### ISSUE THREAD

**Issue by smhk** [websockets/ws#1810]
It should be possible to run both http and ws on the same port.

This guy .. https://stackoverflow.com/a/34838031/294884

suggests doing it by basically

`var app = express(); .. your express app`

Don't launch ws in the usual way.  Instead launch ws like this ..

```
let server = require('http').createServer();
let wss = new require('ws').Server;({ server: server });
server.listen(80, function() {
  console.log(`amazing duo-server listening on 80`);
});
```
and also mount the express app ... something like ..

`server.on('request', app); .. something like that`

In fact, if I launch ws as per the three lines above, ws does _seem_ to work perfectly.

My two questions,

1. In fact is it "OK" to launch ws in that way?

2. Can anyone take pity and tell me how to `server.on('request', .. something` so that said requests go to the express `app` ?

Alternately, is there a well-known way to make ws run with / on the same port 80 as an ordinary express app?

**Comment by lpinca** [comment]
1. Yes that is ok and documented [here](https://github.com/websockets/ws#external-https-server). There is also a sessione sharing example with express. See https://github.com/websockets/ws/tree/master/examples/express-session-parse.
1. `server.on('request', app);` is correct. The `express()` call returns a "spiced up" function that you can use as a listener for the `'request'` event. This is all you need to do. Middleware and route handlers will work as expected after this.

**Comment by lpinca** [comment]
I'm closing this as answered.

**Comment by smhk** [comment]
Incredible @lpinca !!!!  Confirming it works fantastically.

Just incredible!  Where is the PayPal tip jar for WS !!

Note for anyone googling here, here's a full simple explanatory example https://stackoverflow.com/a/64394671/294884
