### ISSUE TITLE
Iterating over WebSocket stream closes the connection abruptly when breaking or throwing an error

### ISSUE THREAD

**Issue by gnarea** [websockets/ws#1811]
- [x] I've searched for any related issues and avoided creating a duplicate
      issue.

#### Description

It's impossible to close the connection with a code other than `1006` when  using a readable stream (`WebSocket.createWebSocketStream()`) as an iterable and there's a `break`/`throw` in the loop. This happens because [the Node.js readable stream calls `duplex.destroy()` in that case](https://nodejs.org/api/stream.html#stream_readable_symbol_asynciterator):

> If the loop terminates with a break or a throw, the stream will be destroyed. In other terms, iterating over a stream will consume the stream fully.

#### Reproducible in:

- version: 7.3.1
- Node.js version(s): 12
- OS version(s): Ubuntu 20.04

#### Steps to reproduce:

Try this, for example:

```typescript
import WebSocket from 'ws';

async function main(): Promise<void> {
  const ws = new WebSocket('wss://echo.websocket.org/', {
    origin: 'https://websocket.org',
  });
  ws.on('close', (code, reason) => {
    console.log('Closing', { code, reason });
  });

  const duplex = WebSocket.createWebSocketStream(ws, { encoding: 'utf8' });
  duplex.write('hi');
  for await (const message of duplex) {
    console.log('Got message', message);
    break;
  }
}

main();
```

#### Expected result:

I'd like the ability to call `ws.close(...)` after the loop. The example above is trivial and I could do it just before the `break`, however, in my real app code, I'm actually yielding the incoming messages and it's up to the consumer to `break` (or not).

One way to achieve this would be to pass an argument to `createWebSocketStream()` to prevent closing the connection automatically when the stream is destroyed.

#### Actual result:

The connection is closed immediately with a `1006` after the `break`.

```
$ ts-node src/wsTest.ts
Got message hi
Closing { code: 1006, reason: '' }
```

**Comment by lpinca** [comment]
In my opinion this is expected and is the correct behavior. Breaking out of the loop means that stream was not fully consumed.

Preventing the stream from being destroyed when breaking out of the loop is out of the scope of this library and you should eventually bring this to Node.js core.

**Comment by gnarea** [comment]
Thanks for getting back!

> Preventing the stream from being destroyed when breaking out of the loop is out of the scope of this library

That's just one way I thought of preventing an abrupt termination of the connection, but I don't mind how it's done: I just need the option to choose the connection gracefully.

For example, another option is to pass an option to the duplex to make it call `ws.close(...)` instead of `ws.terminate()` upon destruction. That option could be an object containing the code and reason, or it could be a callable like `(error?: Error) => ({code, reason})`.

**Comment by lpinca** [comment]
To close the connection gracefully you should call `duplex.end()`. That will call `ws.close()`.
Calling `duxplex.destroy()` directly or indirectly will result in a `ws.terminate()` call.

**Comment by gnarea** [comment]
Actually, I can also try to wrap the readable stream I iterate over around another option that does nothing when `.destroy()` is called inside the loop, which wouldn't require changes to `ws`. I'd just have to make sure to have a `finally` block to close the connection if necessary.

**Comment by gnarea** [comment]
> To close the connection gracefully you should call duplex.end(). That will call ws.close().

Maybe I'm misreading the code, but wouldn't that send the code `1006` to the server without giving me the option to set a different code?

**Comment by lpinca** [comment]
It will call `ws.close()` with no arguments, so the close code will be `1005` which is a clean closure.

**Comment by gnarea** [comment]
Makes sense. In that case I think I'll just change my code to wrap the stream in the loop so that `destroy()` calls `end ()` instead of `terminate()`. Thanks @lpinca!

**Comment by lpinca** [comment]
```js
const WebSocket = require('ws');

const wss = new WebSocket.Server({ port: 0 }, function () {
  const ws = new WebSocket(`ws://localhost:${wss.address().port}`);
  const duplex = WebSocket.createWebSocketStream(ws);

  duplex.resume();
  duplex.end();
});

wss.on('connection', function (ws) {
  ws.on('close', function (code, reason) {
    console.log('code: %s, reason: "%s"', code, reason);
    wss.close();
  });
});
```

**Comment by gnarea** [comment]
Thanks!

**Comment by lpinca** [comment]
I'm closing this. Discussion can continue if needed.
