### ISSUE TITLE
`url` attribute is `undefined` server-side

### ISSUE THREAD

**Issue by piranna** [websockets/ws#1813]
- [x] I've searched for any related issues and avoided creating a duplicate
      issue.

#### Description

On server-side WebSocket instances, `url` attribute is undefined. This is because it's being set at https://github.com/websockets/ws/blob/237960e915b3f41b8c7aabfa5c938171976f2978/lib/websocket.js#L475-L481, that's only being called when `initAsClient()` function is being called, and this is detected if [constructor was called setting `address` as `null`](https://github.com/websockets/ws/blob/237960e915b3f41b8c7aabfa5c938171976f2978/lib/websocket.js#L60-L75). This is fine, but for homogeneity and server-side operation, I would set `url` attribute to the actual url being used by client-side to create the WebSocket instance, recreating the full URL by combining the request host, path and query (fragment is not send to the server). Main drawback would be that since now we would have an address, how to detect if it's a client-side or server-side WebSocket instance. Not sure if setting it afterwards at [WebSocket Server completeUpgrade() method](https://github.com/websockets/ws/blob/237960e915b3f41b8c7aabfa5c938171976f2978/lib/websocket-server.js), or by passing a custom option to flag the instance as server side.

#### Reproducible in:

- version: 7.3.1
- Node.js version(s): 15.0.1
- OS version(s): Ubuntu 20.04

#### Steps to reproduce:

1. Create a WebSocket Server instance
2. Connect from a client
3. Read `socket.url` attribute at server-side

#### Expected result:

A string with the url used by the client to create the WebSocket connection

#### Actual result:

`undefined`

**Comment by lpinca** [comment]
This is documented and done on purpose. See also https://github.com/websockets/ws/pull/1778.

**Comment by piranna** [comment]
> This is [documented](https://github.com/websockets/ws/blob/master/doc/ws.md?rgh-link-date=2020-11-02T17%3A49%3A50Z#websocketurl) and done on purpose. See also #1778.

I understand the motivations, if not the original one, at least a valid one from where the request was received (also being that a proxy) would be useful too, isn't it?

**Comment by lpinca** [comment]
In my opinion on the server it is not needed because all you need is the request path which is already available as `request.url` why spending time on computing the protocol, userinfo and host when it is not needed and not correct (the original one)?

**Comment by piranna** [comment]
> In my opinion on the server it is not needed because all you need is the request path which is already available as `request.url` why spending time on computing the protocol, userinfo and host when it is not needed and not correct (the original one)?

Fair enought... although at least the `path` would be useful to have it set, this way the callback of `handleUpgrade()` would not need to be nested inside the connection handler function just to get the `req.url`... this way it would allow to earn some memory and CPU by not creating new function and closure objects.

**Comment by lpinca** [comment]
I don't like to set `rquest.path` as `websocket.url` because it's not a full URL.
We can make the callback of `handleUpgrade()` take the `request` as second argument.

**Comment by piranna** [comment]
> We can make the callback of `handleUpgrade()` take the `request` as second argument.

That could do the job :-)

**Comment by piranna** [comment]
Cool, thanks! :-)

**Comment by piranna** [comment]
I got into this pitfall... again :-P What about adding a "fake" `url` property that throw an exception pointing to use `request.url` instead? That could help some head scratches :-)

**Comment by lpinca** [comment]
It would be easy as [`websocket.url`](https://github.com/websockets/ws/blob/8.2.0/lib/websocket.js#L173-L175) is already a getter so a simple check `this. _isServer` would do the job but throwing a new error is semver-major. I'll add it to the todo list for the next major version.

**Comment by piranna** [comment]
> I'll add it to the todo list for the next major version.

Fair enought :-)

**Comment by piranna** [comment]
and thanks :-D
