### ISSUE TITLE
`url` attribute is not read-only

### ISSUE THREAD

**Issue by piranna** [websockets/ws#1814]
- [x] I've searched for any related issues and avoided creating a duplicate
      issue.

#### Description

According to https://developer.mozilla.org/en-US/docs/Web/API/WebSocket, `url` attribute should be a read-only string, but [it's currently being set as a plain attribute that can be overwritten](https://github.com/websockets/ws/blob/237960e915b3f41b8c7aabfa5c938171976f2978/lib/websocket.js#L475-L481), and in fact, [it's being `undefined` on server side](https://github.com/websockets/ws/issues/1813). I think this should be replaced by a getter.

#### Reproducible in:

- version: 7.3.1
- Node.js version(s): 15.0.1
- OS version(s): Ubuntu 20.04

#### Steps to reproduce:

1. Create a WebSocket connection
2. Set the `url` attribute

#### Expected result:

Thrown exception about not being able to modify a getter property

#### Actual result:

The `url` attribute is updated with any value provided

**Comment by lpinca** [comment]
We can use a getter and make it read only but I don't think it's very important. Why would anyone change the `url` attribute? Also changing it does not cause any harm.

A similar argument can be made for the `protocol` and `readyState` arguments which are also not read only. Changing `protocol` is ok,  it has no side effects. Changing `readyState` can affects functionality but if you do that you accept the risk.

**Comment by piranna** [comment]
Being more strict and spec compliant... Doing so could prevent some application level bugs and surprises.

**Comment by lpinca** [comment]
The RFC does not say anything about this. I'm ok with browser compatibility but again I see no real benefits. Getters were slower than plain properties, I don't know if this is still true.

**Comment by piranna** [comment]
Thank you :-)

**Comment by craftdelivery** [comment]
> We can use a getter and make it read only but I don't think it's very important. Why would anyone change the `url` attribute? Also changing it does not cause any harm.
> 
> A similar argument can be made for the `protocol` and `readyState` arguments which are also not read only. Changing `protocol` is ok, it has no side effects. Changing `readyState` can affects functionality but if you do that you accept the risk.

I was changing the url to add an url param which helped keep track of the user making the request

**Comment by piranna** [comment]
> I was changing the url to add an url param which helped keep track of the user making the request

Not fully sure if that's the better way to do it... how were you adding the url param? Can you provide some example code?

**Comment by craftdelivery** [comment]
I was adding it client side then doing ws.url=req.url

I'm sure I can figure out a workaround

Thanks, Eli Tabello 647.382.7084
