### ISSUE TITLE
how connect a channel?

### ISSUE THREAD

**Issue by Deboracgs** [websockets/ws#1815]
- [ x] I've searched for any related issues and avoided creating a duplicate
      issue.

Hello, I have a doubt

how can I connect a channel ?

For example, I'm using another server to be a WS, and another server as client, and I want to subscribe an channel and receive data. On server WS I'm using adonis, and works fine, but on another server as client I'm using just express with this library

```
const ws = new WebSocket(`ws://127.0.0.1:3333/adonis-ws`);
const topic = `member:listInvitationOfMacAddress=${mac}`
console.log("topic", topic)
ws.on('open', function open() {
  console.log("teste");
  ws.send(JSON.stringify(
    {
      "event":"subscribe",
      "channel":topic
    }
  ));
});
```

#### Reproducible in:

- version:
- Node.js version(s):
- OS version(s):

#### Steps to reproduce:

1.

2.

3.

**Comment by lpinca** [comment]
This seems a general support question. The issue tracker is only for bugs in the library. Please use another channel for this kind of questions.

Your code snippet looks good. If that is the correct way to subscribe to a channel you should receive messages by adding a listener for the `'message'` event on the `ws` object.

**Comment by lpinca** [comment]
I'm closing this as answered. Discussion can continue if needed.
