### ISSUE TITLE
TypeError: One of the "port", "server", or "noServer" options must be specified

### ISSUE THREAD

**Issue by byeze** [websockets/ws#1822]
- [x] I've searched for any related issues and avoided creating a duplicate
      issue.

#### Description

When exporting a new ws server, and using it on another file, the error thrown is:
`TypeError: One of the "port", "server", or "noServer" options must be specified`

#### Reproducible in:

- version: 7.4.0
- Node.js version(s): v14.13.0
- OS version(s): Windows 10 v1909 c18363.1198

#### Steps to reproduce:

1. Create an index.ts with this code
```
... import here the modules
const app = require('express')();
export const server: Server = createServer(app);
import "./socket.ts"

```
2. Create a sockets.ts file with this code
```
import { server } from "./../"
import { Server } from "ws"

interface Socket extends WebSocket {
    id: string;
}

const socket = new Server({ server: server });

socket.on('connection', (ws: Socket) => {
    ws.id = "sdf"
    console.log("%s se ha conectado", ws.id)

    socket.on('close', (ws: any) => {
        console.log("%s connection closed", ws.e)
    })
})

export {
    socket,
    broadcast
}
```

3. Try to use the socket export, for example, to send another message on another file, let's say "test.ts"
4. You can't run tsc because the error is thrown.

#### Expected result:

Use the socket export to emit and perform the functions of ws.

#### Actual result:

Tsc throws an error because of a Type Error.

**Comment by lpinca** [comment]
The error is thrown by `ws`

https://github.com/websockets/ws/blob/3d5066a7cad9fe3176002916aeda720a7b5ee419/lib/websocket-server.js#L61

and in your case it means that `server` in `sockets.ts` is falsy. There is something wrong in your module organization or how tsc transpiles the above code but this is not an issue in the library.

**Comment by byeze** [comment]
Fixed! I really don't know how did I do it but I did it hahaha.
Thank you!
