### ISSUE TITLE
Server emits 'connection' after WebSocket emits 'open'

### ISSUE THREAD

**Issue by Seairth** [websockets/ws#1824]
#### Description

The 'connection' event on Server is emitting after the WebSocket has emitted its 'open' event.  As a result, there's no way to set up the WebSocket callback for the 'open' event in the 'connection' event callback.  I don't see another way to do this, but this code looks like it's worked this way for a long time.  I can "fix" the issue by making the change described below, but I'm concerned that I'm missing something obvious.

#### Reproducible in:

- version: 7.4.0
- Node.js version(s): 10.17.0
- OS version(s): Ubuntu 18.04 (x64)

#### Possible fix:

Looking at websocket-server, [setSocket is called](https://github.com/websockets/ws/blob/master/lib/websocket-server.js#L323) before ['connection' is emitted](https://github.com/websockets/ws/blob/master/lib/websocket-server.js#L330).  If I instead move the callback up to [the line after where WebSocket is created](https://github.com/websockets/ws/blob/master/lib/websocket-server.js#L285), everything works.

**Comment by lpinca** [comment]
This is by design. There is no `'open'` even on the server. The `'connection'` event gives you an open `WebSocket`. The ready state  starts on `CONNECTED`.

**Comment by Seairth** [comment]
But the WebSocket does have an `'open'` event, which is what I am trying to listen to.  But I get your point about the socket already being open when passed to the Server `'connection'` callback.

Given this, you should probably remove [the `'open'` event](https://github.com/websockets/ws/blob/master/lib/websocket.js#L177).

**Comment by lpinca** [comment]
It's there for the client. The code is shared. We could prevent the event from being emitted on the server but it does not cause any harm. It is basically a [noop](https://github.com/nodejs/node/blob/a26ae70f2b46c7ee7ab41e2346b4ac9763e675d9/lib/events.js#L333-L334).
