### ISSUE TITLE
Network Interface Support

### ISSUE THREAD

**Issue by anna-rmrf** [websockets/ws#1833]
Hello, is there any way we can specify the network interface when initiating a ws instance? Couldn't find any localAddress option either;
Thank you.

**Comment by netizen-ais** [comment]
Just combine the `noServer` option with an external https server, where the `listen()` method has `port[, host]` arguments

**Comment by anna-rmrf** [comment]
@netizen-ais I meant when connecting to a websocket as a client

**Comment by netizen-ais** [comment]
> @netizen-ais I meant when connecting to a websocket as a client

I think that is out of javascript's scope, it seems an OS task to me

**Comment by anna-rmrf** [comment]
@netizen-ais Node.js does support it though without the need to use iptables or whatever
After looking at ws' code https://github.com/websockets/ws/blob/d1a8af4ddb1b24a4ee23acf66decb0ed0e0d8862/lib/websocket.js#L516
It uses http/https and both do support network interface

**Comment by netizen-ais** [comment]
> It uses http/https and both do support network interface

[API docs](https://github.com/websockets/ws/blob/master/doc/ws.md#new-websocketaddress-protocols-options) says you can use localAddress:

- Any other option allowed in http.request() or https.request(). Options given do not have any effect if parsed from the URL given with the address parameter.

**Comment by anna-rmrf** [comment]
@netizen-ais Yeah you have a point
