### ISSUE TITLE
RangeError:Invalid WebSocket frame: invalid payload length 126

### ISSUE THREAD

**Issue by dingrins** [websockets/ws#1837]
Hello,

#### Description
We have a simple Express server and recently we have encountered a problem that the server sometimes crashes with the following error:

`RangeError: Invalid WebSocket frame: invalid payload length 126
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! fx-websocket@1.0.0 start: `node build/bundle.js`
npm ERR! Exit status 1
npm ERR!`

#### Reproducible in:
- version: ^7.2.1
- Node.js version(s): 12.13.0
- OS version(s): Amazon Linux AMI release 2018.03

* We have tried to reproduce this error locally (on Mac with/without Docker) but without success.
* We were unable to find the scenario causing this error to occur on our AWS (Beanstalk) server.
* This server serves both React and React native applications.

Thanks for your support.
Best Regards.

**Comment by lpinca** [comment]
Add a listener for the error event:

```js
wss.on('connection', function(ws) {
  ws.on('error', console.error);
});
```

The error occurs when a client sends the invalid frame. There is nothing to do other than handling the error.

**Comment by lpinca** [comment]
You can easily reproduce like this:

```js
const WebSocket = require('ws');

const wss = new WebSocket.Server({ port: 0 }, function() {
  const ws = new WebSocket(`ws://localhost:${wss.address().port}`);

  ws.on('open', function() {
    ws._socket.write(Buffer.from('89FE', 'hex'));
  });
});

wss.on('connection', function(ws) {
  ws.on('error', console.error);
});
```

**Comment by dingrins** [comment]
I manage to reproduce it with your example and to solve it with handling the error.
Thanks a lot.
