### ISSUE TITLE
SSL Wrong Version number

### ISSUE THREAD

**Issue by Nectres** [websockets/ws#1839]
- [o ] I've searched for any related issues and avoided creating a duplicate
      issue.

#### Description

When i try to use a SSL Certificate and a key to secure the websocket and try to connect to it with "wss://" I get an error stating SSL Wrong Version [ Screenshot Attached Below ]. I tried connecting with "ws://" and that works, connecting to "wss://echo.websocket.org" works too. I don't understand why it's not working
Thank you for the support!!

#### Reproducible in:

- version: 7.4.2
- Node.js version(s): 14.15.0
- OS version(s): Windows 10

#### Steps to reproduce:

1. Start a https server with ssl certificate and key

2. Pass the https server as server in ws

3. Try to connect it with a client locally

#### Expected result:

Connection

#### Actual result:
 
Error. Attached below:

#### Attachments:

![image](https://user-images.githubusercontent.com/12008678/106357479-49a20d80-632c-11eb-991e-c79738edd021.png)

**Comment by lpinca** [comment]
Try with the `https` module:

```js
const https = require('https');

const request = https.get('https://yourServerHost');

request.on('response', function (response) {
  response.resume();
});
```

I'm pretty sure you will get the same error. It's not an issue in `ws` but in your SSL configuration.

**Comment by Nectres** [comment]
Yeah it did produce the same error with the https module. I am sorry i wil close this issue
