### ISSUE TITLE
path option not working

### ISSUE THREAD

**Issue by Soldr** [websockets/ws#1846]
- [x] I've searched for any related issues and avoided creating a duplicate
      issue.

#### Reproducible in:

- version: 7.4.3
- Node.js version(s): 14.15.4
- OS version(s): Ubuntu 20.04

#### Steps to reproduce

1. Create a websocket server with the path option

2. Try to connect to it

#### Expected result:
The client connects to the server fine

#### Actual result:

Status code 404

#### Attachments:

const WebSocketServer = new WebSocket.Server({
    port: config.WebSocketPort || 27823,
    path: '/console'
})

**Comment by lpinca** [comment]
I can't reproduce. It works as expected:

```js
const WebSocket = require('ws');
const assert = require('assert');

const wss = new WebSocket.Server({ port: 0, path: '/console' }, function () {
  const ws = new WebSocket(`ws://localhost:${wss.address().port}`);

  ws.on('open', function () {
    throw new Error('This should not be called');
  });

  ws.on('error', function (err) {
    console.log('It works!');
    assert.strictEqual(err.message, 'Unexpected server response: 400');
  });

  ws.on('close', function (code) {
    assert.strictEqual(code, 1006);
    wss.close();
  });
});

wss.on('connection', function () {
  throw new Error('This should not be called');
});
```

**Comment by lpinca** [comment]
Make sue your clients connect to `/console`, for example `ws://hostname:port/console`.

**Comment by Soldr** [comment]
> Make sue your clients connect to `/console`, for example `ws://hostname:port/console`.

Whoops, turns out i had the port in the wrong place lol, thanks
