### ISSUE TITLE
Connecting to unix socket server from client

### ISSUE THREAD

**Issue by sebam91** [websockets/ws#1847]
How do i connect to .sock server from client? (public js)

**Comment by lpinca** [comment]
See https://github.com/websockets/ws/blob/master/doc/ws.md#unix-domain-sockets

**Comment by sebam91** [comment]
Managed with serverside, but cannot make it work in frontend using browser WebSocket. Only ws: / wss: allowed.

**Comment by lpinca** [comment]
You can't from the browser.

**Comment by lpinca** [comment]
You could use a reverse proxy like NGINX but direct IPC connection is not allowed in the browser. I'm closing this as answered. Discussion can continue if needed.
