### ISSUE TITLE
No way to handle "RangeError: Max payload size exceeded" in permessage-deflate

### ISSUE THREAD

**Issue by yunyu** [websockets/ws#1848]
- [x] I've searched for any related issues and avoided creating a duplicate
      issue.

#### Description

The WebSocket server completely crashes if an error is thrown in inflateOnData: https://github.com/websockets/ws/blob/4e9607bb259dc3747881c2c22c3f65127d018a16/lib/permessage-deflate.js#L481

This is not catchable (e.g. with an "error" handler on the WebSocketServer or WebSocket) or recoverable. I have tried the solution proposed in https://github.com/websockets/ws/issues/1543 to no avail. This will happen if the decompressed size of a frame exceeds maxPayload (e.g. with a zip bomb, or when the compressed size is barely under), but the compressed size does not. 

#### Reproducible in:

- version: 7.4.3
- Node.js version(s): v14.13.0
- OS version(s): Debian 10 running Linux 4.19

#### Steps to reproduce:

1. Construct the server with:
```ts
      wsOptions: {
        perMessageDeflate: true,
      }
```

2. Attach an `error` handler to every accepted WebSocket connection

3. Set the `_maxPayload` of the permessage-deflate extension to something really small (like 5) on every accepted WebSocket connection:

```ts
    const permessageDeflateObject = (ws as any)._extensions[
      "permessage-deflate"
    ];
    if (permessageDeflateObject) permessageDeflateObject._maxPayload = 5;
    // A workaround for this issue would be to set _maxPayload to 0 in PermessageDeflate
```

4. Send any message

5. The WS server completely crashes and stops accepting new connections

#### Expected result:

The `error` handler is called on the WebSocket object, and the server does not crash

#### Actual result:

The server completely crashes, with no error handler called

#### Attachments:

![image](https://user-images.githubusercontent.com/8008350/107478719-f314aa80-6b47-11eb-8e8f-0f264718d9ba.png)

**Comment by yunyu** [comment]
I've been using this as a workaround (it doesn't protect against zip bombs, but stops the crashing):

```ts
(ws as any)._extensions["permessage-deflate"]._maxPayload = 0;
```

**Comment by lpinca** [comment]
> This will happen if the decompressed size of a frame exceeds maxPayload (e.g. with a zip bomb, or when the compressed size is barely under), but the compressed size does not.

I cannot reproduce. Here is a test case

```js
const WebSocket = require('ws');
const { strictEqual } = require('assert');

const server = new WebSocket.Server(
  {
    perMessageDeflate: true,
    maxPayload: 25,
    port: 0
  },
  function () {
    const ws = new WebSocket(`ws://localhost:${server.address().port}`, {
      perMessageDeflate: { threshold: 0 }
    });

    ws.on('open', function () {
      ws.send('A'.repeat(50));
    });
  }
);

server.on('connection', function (ws) {
  ws.on('close', function (code) {
    strictEqual(code, 1009);
  });

  ws.on('error', console.error);
});
```

**Comment by lpinca** [comment]
Btw this is tested. See https://github.com/websockets/ws/blob/99338f7ec6a869dbdd48ae0bcf56ca5d9aaa3f90/test/receiver.test.js#L871-L898.

**Comment by yunyu** [comment]
@lpinca That test case doesn't quite produce the stack trace I'm seeing – I linked the wrong line, here's where it's being thrown: https://github.com/websockets/ws/blob/master/lib/receiver.js#L386

Let me come up with a more simplified repro case...

**Comment by lpinca** [comment]
Here is a test case to trigger that error

```js
const WebSocket = require('ws');
const { strictEqual } = require('assert');

const server = new WebSocket.Server(
  {
    perMessageDeflate: true,
    maxPayload: 49,
    port: 0
  },
  function () {
    const ws = new WebSocket(`ws://localhost:${server.address().port}`, {
      perMessageDeflate: { threshold: 0 }
    });

    ws.on('open', function () {
      ws.send('A'.repeat(25), { fin: false });
      ws.send('A'.repeat(25), { fin: true });
    });
  }
);

server.on('connection', function (ws) {
  ws.on('close', function (code) {
    strictEqual(code, 1009);
  });

  ws.on('error', console.error);
});
```

I still can't reproduce the crash.

**Comment by yunyu** [comment]
I discovered that there was a WebSocket upgrade code path in my application that didn't assign an error handler, which may have been the cause of the crash. I'll be closing this issue for now and let you know if it recurs @lpinca – really appreciate your time
