### ISSUE TITLE
Requesting multicast function 

### ISSUE THREAD

**Issue by supercarrypro** [websockets/ws#1854]
- [ ] I've searched for any related issues and avoided creating a duplicate
      issue.

#### Description

Is it possible to provide multicast support to replace the default broadcast function? In real application, multicast function has higher demand and flexibility. For example, it can create isolated "room" or "channel" function in real application. From the documentation, the wss response ip address is a black box for developer, which means developer cannot control the response to specific one or more client. Same as the "wss.clients" and "client" object.

#### Reproducible in:

- version:
- Node.js version(s):
- OS version(s):

#### Steps to reproduce:

1.

2.

3.

#### Expected result:

Developer can easily use a list to store incoming one or more ip address and return to wss when on message, then wss server will do the rest of the multicast job to the clients.

**Comment by lpinca** [comment]
Multicast is not possible with TCP. The WebSocket protocol is TCP-based protocol.

**Comment by supercarrypro** [comment]
Is there any code reference on how to grouping clients? It is not stated in documentation. Thank you.

**Comment by lpinca** [comment]
It's out of the scope of the project. You can use a `Set` for each "room" / "channel". Here is an example https://github.com/websockets/ws/issues/1308#issuecomment-366808059.

**Comment by supercarrypro** [comment]
I see how you implement id on ws connection to identify the connection. It is a good idea. But there is a problem i have met, which is i cannot match client.id to ws.id through on message event. 

if (message.type === 'NEW_MESSAGE') {
            wss.clients.forEach((client) => {
                if (client.id === ws.id && client.readyState === WebSocket.OPEN) {
                    client.send(data);
                }
            });
        }

I do something like this and it return the data whether the id is true value or not. It does not works as i thought. Is something wrong in my code?

**Comment by lpinca** [comment]
I don't know what you want to do but that code sends `data` only to the `WebSocket` client whose `id` property is `ws.id`. How are you adding the `id` property to the `WebSocket` client? And what is `ws.id`?

**Comment by supercarrypro** [comment]
I define ws.id earlier in the code as a string. It seems that only "ws" can accept an id property while "client" cannot.

**Comment by lpinca** [comment]
You can assign IDs to clients like this https://github.com/websockets/ws/issues/859#issuecomment-253197752.

**Comment by lpinca** [comment]
I'm closing this as it is not an issue in the library.

**Comment by lpinca** [comment]
To add to what was said in https://github.com/websockets/ws/issues/1854#issuecomment-787670393, see https://stackoverflow.com/questions/62370962/how-to-create-join-chat-room-using-ws-websocket-package-in-node-js
