### ISSUE TITLE
How to get the socket information ws used (ex. port number, ip address..., etc)

### ISSUE THREAD

**Issue by agrexgh** [websockets/ws#1857]
- [ ok ] I've searched for any related issues and avoided creating a duplicate
      issue.

#### Description

I use ws for WebSocket client.
I'd like to know only the port number ws used as source port number for debugging,
but I can't understand how to do that from docs.

Could you tell me tha way to get the socket information like source port number ws used ?
If there are some way to get socket information,
could you write it in docs?

**Comment by agrexgh** [comment]
I'd like to assign @lpinca .

**Comment by lpinca** [comment]
You can use the `localPort` option as per https://nodejs.org/api/net.html#net_socket_connect_options_connectlistener which is forwarded from https://nodejs.org/api/http.html#http_http_request_options_callback.

**Comment by lpinca** [comment]
It is documented here https://github.com/websockets/ws/blob/master/doc/ws.md#new-websocketaddress-protocols-options

> Any other option allowed in http.request() or https.request().

**Comment by agrexgh** [comment]
@lpinca Thx a lot for replying.
> You can use the localPort option as per https://nodejs.org/api/net.html#net_socket_connect_options_connectlistener which is forwarded from https://nodejs.org/api/http.html#http_http_request_options_callback.

I think this option is to specify source port number before connecting.
I'd like to know auto-assigned port number for ws after connected.
I'm sorry but your answer was not my expected one.

**Comment by lpinca** [comment]
> I'd like to know auto-assigned port number for ws after connected.

The source port will be the one specified by `localPort`. It is not auto-assigned if the option is used.

**Comment by agrexgh** [comment]
@lpinca I don't use `localport` option, so source port will be auto assigend.

**Comment by lpinca** [comment]
It is for debugging so use it. You can also use

```js
ws.on('open', function () {
  console.log(ws._socket.localPort);
});
```

but that it is not officially supported as the the `_socket` property is "private".

**Comment by lpinca** [comment]
I'm closing this as answered.

**Comment by agrexgh** [comment]
@lpinca Thank you for telling me how to get socket info!

> It is for debugging so use it. You can also use
> 
> ```js
> ws.on('open', function () {
>   console.log(ws._socket.localPort);
> });
> ```
This worked for me!
It shows localPort Number!
I understood that `_socket` is instance of net.Socket class of Node.js (If I misunderstood, please point out it).

> but that is not officially supported as the the `_socket` property is "private".

OK.
This shouldn't be documented.
