### ISSUE TITLE
Is ws.terminate() at cliend sending FIN,ACK to server by design?

### ISSUE THREAD

**Issue by agrexgh** [websockets/ws#1858]
- [ok] I've searched for any related issues and avoided creating a duplicate
      issue.

#### Description

I use client side ws.
I found an Q&A that says ws.terminate() doesn't close frame or send to server.

https://stackoverflow.com/questions/41074052/how-to-terminate-a-websocket-connection

> Forcibly destroys the socket without closing frames or fin packets exchange, and does it instantly, without any timeout.

But I confirmed that ws.terminate() sent FIN,ACK packet to server
(sorry, I can't share the packet capture because it may include our company's internal information).

@lpinca Do you think about this?
Is this behavior by design?

Nodejs ver; 8.11.4
ws ver:3.3.3

**Comment by lpinca** [comment]
Yes, this is by design.

**Comment by agrexgh** [comment]
@lpinca Thx a lot!
Could you write that in docs?
I couldn't read actual meaning of "_Forcibly close the connection._".
https://github.com/websockets/ws/blob/master/doc/ws.md#websocketterminate

So [this Q&A](https://stackoverflow.com/questions/41074052/how-to-terminate-a-websocket-connection) mislead me.

**Comment by agrexgh** [comment]
Thank you for documentation! @lpinca
