### ISSUE TITLE
Passing in request to handleProtocols is a duplication of effort?

### ISSUE THREAD

**Issue by Borduhh** [websockets/ws#1859]
#### Description

Does `request` need to be passed to `handleProtocols` if the protocols from the request are being passed in as the parameter `protocols`? This seems like a duplication of efforts.

#### Reproducible in:

- version: 7.4.3
- Node.js version(s): 15.4.0
- OS version(s): macOS 11.2

#### Expected result:

Request protocols are generated outside the `handleProtocols` function and passed in via the `protocols` param without the request.

**/lib/websocket-server.js**
```javascript
    let protocol = req.headers['sec-websocket-protocol'];

    if (protocol) {
      protocol = protocol.trim().split(/ *, */);

      //
      // Optionally call external protocol selection handler.
      //
      if (this.options.handleProtocols) {
        protocol = this.options.handleProtocols(protocol);
      } else {
        protocol = protocol[0];
      }

      if (protocol) {
        headers.push(`Sec-WebSocket-Protocol: ${protocol}`);
        ws._protocol = protocol;
      }
    }
```

#### Actual result:

Request protocols are generated outside the `handleProtocols` function and passed in via the `protocols` param as well as the request which is not being used

**/lib/websocket-server.js**
```javascript
    let protocol = req.headers['sec-websocket-protocol'];

    if (protocol) {
      protocol = protocol.trim().split(/ *, */);

      //
      // Optionally call external protocol selection handler.
      //
      if (this.options.handleProtocols) {
        protocol = this.options.handleProtocols(protocol, req);
      } else {
        protocol = protocol[0];
      }

      if (protocol) {
        headers.push(`Sec-WebSocket-Protocol: ${protocol}`);
        ws._protocol = protocol;
      }
    }
```

**Comment by lpinca** [comment]
The user might need additional info contained in the `http.IncomingMessage` object (the `request` object) to select the protocol.

**Comment by lpinca** [comment]
See https://github.com/websockets/ws/issues/783.

**Comment by lpinca** [comment]
Why not passing only the `http.IncomingMessage` object then? For backwards compatibility.

**Comment by Borduhh** [comment]
Thanks for the update. I assumed the request was there for a reason. Not sure if it makes sense to change at this point since it will definitely be a breaking change. Just thought I would throw it out there though in case it was overlooked.

**Comment by lpinca** [comment]
I think it does not make sense to have a breaking change for this.
