### ISSUE TITLE
Websocket closes with number 1006 upon sending valid JSON

### ISSUE THREAD

**Issue by heav-4** [websockets/ws#1860]
I can send data like "hi" or "}", but any valid JSON causes the websocket to close with 1006, which means the client closed the connection. The error event is never called. What could cause this?

**Comment by lpinca** [comment]
The close code has nothing to do with the data sent or received. The close code depends on how the connection is closed. 1006 is an "abnormal closure". It means the other peer did not close the cleanly probably because the peer did not sent a close frame.

**Comment by lpinca** [comment]
I'm closing this as answered. Discussion can continue if needed.
