### ISSUE TITLE
Web Socket Server client.send function ignores "if" condition

### ISSUE THREAD

**Issue by supercarrypro** [websockets/ws#1861]
- [ ] I've searched for any related issues and avoided creating a duplicate
      issue.

#### Reproducible in:

- version:
- Node.js version(s): 10. 16. 0
- OS version(s):

#### Steps to reproduce:

1.

2.

3.

#### Expected result:

The wss clients client.send function sends data follow specified "if" operations so that i can send or not send data to specific client.

#### Actual result:

Google Chrome websocket testing tools is used to test the websocket server. The server returns the same json data that i send to it no matter how i write the "if" condition, not even i use the (client !== ws) as stated in the documentation. The server just return the same thing once i send anything to it, even i didn't write the client.send function. Is this a default and fixed design of the websocket server behaviour?

**Comment by lpinca** [comment]
> Is this a default and fixed design of the websocket server behaviour?

No, and I'm 100% sure there is something wrong in your code. Run the following code and open `http://localhost:8080` in your browser. Open the console tab in dev tools and you will see that the message is sent only to the `WebSocket` with `id` `'1'`.

```js
const http = require('http');
const WebSocket = require('ws');

const data = `<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
  </head>
  <body>
    <script>
      (function () {
        var ws1 = new WebSocket('ws://localhost:8080/?id=1');

        ws1.onmessage = function(evt) {
          console.log('message from ws1:', evt.data);
        };

        var ws2 = new WebSocket('ws://localhost:8080/?id=2');

        ws2.onmessage = function(evt) {
          console.log('message from ws2:', evt.data);
        };
      })();
    </script>
  </body>
</html>`;

const server = http.createServer();

server.on('request', (req, res) => {
  res.setHeader('Content-Type', 'text/html');
  res.end(data);
});

const wss = new WebSocket.Server({ server, clientTracking: false });

const connections = new Map();

wss.on('connection', function (ws, req) {
  const id = new URL(req.url, 'ws://a').searchParams.get('id');

  connections.set(id, ws);

  ws.on('close', function() {
    connections.delete(id);
  });

  if (connections.size === 2) {
    connections.get('1').send('Hello');
  }
});

server.listen(8080, function () {
  console.log('Open http://localhost:8080 in your browser');
});
```

**Comment by supercarrypro** [comment]
The test cases is true, but it comes out error when this code snippet is used:

`ws.on('message', function() {
    connections.get('2').send('Hello');
  });`

The error message was:
`TypeError: Cannot read property 'send' of undefined`

but the connections.get('2').send('Hello'); is used in here:
`if (connections.size === 2) {
    connections.get('1').send('Hello');
  }`

and no problem is occurs. 
Is something wrong with ws.on(message) events?

**Comment by lpinca** [comment]
> Is something wrong with ws.on(message) events?

No, you have to wait for both clients to be connected.

**Comment by lpinca** [comment]
I changed the example so that `ws2` waits for `ws1` to be connected and made `ws1` send a message after `ws2` is connected. On the server when the message is received a new message is sent to `ws2`.

```js
const http = require('http');
const WebSocket = require('ws');

const data = `<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
  </head>
  <body>
    <script>
      (function () {
        var ws1 = new WebSocket('ws://localhost:8080/?id=1');

        ws1.onmessage = function (evt) {
          console.log('message from ws1:', evt.data);
        };

        ws1.onopen = function () {
          var ws2 = new WebSocket('ws://localhost:8080/?id=2');

          ws2.onmessage = function (evt) {
            console.log('message from ws2:', evt.data);
          };

          ws2.onopen = function () {
            ws1.send('message');
          }
        };
      })();
    </script>
  </body>
</html>`;

const server = http.createServer();

server.on('request', (req, res) => {
  res.setHeader('Content-Type', 'text/html');
  res.end(data);
});

const wss = new WebSocket.Server({ server, clientTracking: false });

const connections = new Map();

wss.on('connection', function (ws, req) {
  const id = new URL(req.url, 'ws://a').searchParams.get('id');

  connections.set(id, ws);

  ws.on('close', function () {
    connections.delete(id);
  });

  if (id === '1') {
    ws.on('message', function () {
      connections.get('2').send('Hello');
    });
  }
});

server.listen(8080, function () {
  console.log('Open http://localhost:8080 in your browser');
});
```

I'm closing this as this is not an issue in ws.

**Comment by supercarrypro** [comment]
Thanks for the solution.
