### ISSUE TITLE
Error: Server sent no subprotocol

### ISSUE THREAD

**Issue by VidarHUN** [websockets/ws#1862]
- [x] I've searched for any related issues and avoided creating a duplicate
      issue.

#### Reproducible in:

- version: current
- Node.js version(s): 14
- OS version(s): alpine
- Container base image: node:14-alpine

#### Steps to reproduce:

I have 2 container which are works like a websocket proxy. So each container is a server and a client to and run the same code. 
In my case the first one can handle the incoming traffic and create a new connection to the second container and the second container is trying to forward the traffic to the end. 

Code looks like this: 
`var ws = new WebSocket(url, s.metadata.HTTP["headers"]["sec-websocket-protocol"], options);`
Where the options contain the headers.

#### Expected result:

The traffic flow through the two 2 container with the sub protocol. 

#### Actual result:

The second container cannot forward the traffic due `Error: Server sent no subprotocol`
In the first container I have these options: 
```
{
  headers: {
    upgrade: 'websocket',
    origin: '192.168.99.1',
    'sec-websocket-version': '13',
    connection: 'upgrade'
  }
}
```

And the second one works with this: 
```
{
  headers: {
    'sec-websocket-version': '13',
    connection: 'upgrade',
    upgrade: 'websocket',
    origin: '192.168.99.1',
    'sec-websocket-extensions': 'permessage-deflate; client_max_window_bits'
  }
}
```

I don't modify any of these headers. 

I saw that the error is generated because the `serverProt` is undefined. I tried to insert `sec-websocket-protocol` field by hand, into the second headers, but I got the same result.

**Comment by lpinca** [comment]
The error happens when a client sends one or more subprotocols but during the handshake the server sends back no subprotocol. Do not specify a subprotocol unless the final server closes the connection if one is mandatory. In that case you have to use a subprotocol that is supported by the server.

**Comment by VidarHUN** [comment]
But I need this subprotocol and I can not change only for one container because the two container use the same image.
There is any kind of option for the websocket server which can send back the subprotocol?

**Comment by lpinca** [comment]
If your server is `ws` you can use the [`handleProtocols`](https://github.com/websockets/ws/blob/master/doc/ws.md#class-websocketserver) option.

**Comment by VidarHUN** [comment]
Thank you for your help.

**Comment by pimterry** [comment]
@lpinca how would you feel about reconsidering and relaxing this, or maybe adding an option to allow it? It currently matches browser behaviour, but doesn't match the websocket RFC or other implementations. In the RFC, the only relevant normative rule for the response is:

> 6.  If the response includes a |Sec-WebSocket-Protocol| header field
>     and this header field indicates the use of a subprotocol that was
>     not present in the client's handshake (the server has indicated a
>     subprotocol not requested by the client), the client MUST _Fail
>     the WebSocket Connection_.

I.e. if the server returns no subprotocol header, this validation doesn't apply.

Although browsers are stricter and do reject responses without a subprotocol when one was offered, other clients are not (e.g. [python-websockets](https://github.com/python-websockets/websockets/blob/18382874ac46c89eca948bda6a907e5a6934f5e9/src/websockets/client.py#L249-L283)) so this creates incompatibility for some non-browser cases.
