### ISSUE TITLE
npm install ws fails on MacOS big sur

### ISSUE THREAD

**Issue by corydon2017** [websockets/ws#1863]
- [x] I've searched for any related issues and avoided creating a duplicate
      issue.

#### Description

npm ERR! code ENOSELF
npm ERR! Refusing to install package with name "ws" under a package
npm ERR! also called "ws". Did you name your project the same
npm ERR! as the dependency you're installing?
npm ERR! 
npm ERR! For more information, see:
npm ERR!     <https://docs.npmjs.com/cli/install#limitations-of-npms-install-algorithm>

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/koala/.npm/_logs/2021-03-18T00_55_40_611Z-debug.log
#### Reproducible in:

- version:
- Node.js version(s): v14.16.0
- npm version: 6.14.11
- OS version(s): MacOS big sur

#### Steps to reproduce:

1. npm install ws

2.

3.

**Comment by lpinca** [comment]
> npm ERR! Refusing to install package with name "ws" under a package
npm ERR! also called "ws". Did you name your project the same
npm ERR! as the dependency you're installing?

Rename your project to something different from "ws".

**Comment by corydon2017** [comment]
Yes. I rename 'ws' in the package.json as below:
 { 
   "name": "",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "dependencies": {
    "ws": "^7.4.4"
  },
  "devDependencies": {},
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC"
}

% npm install ws
npm WARN @1.0.0 No description
npm WARN @1.0.0 No repository field.

+ ws@7.4.4
added 1 package from 1 contributor and audited 1 package in 1.333s
found 0 vulnerabilities

%npm list -g ws
/usr/local/lib
└── ws@7.4.4 

but in my application code:
const WebSocket = require('ws');

var socket = new WebSocket('ws://demo.xxxx.com/api/ws/');  

 it always _shows closecode: 1006; I used chrome websocket plugin to test 'ws://demo.xxxx.com/api/ws/'. It is fine.

please could you help?

thanks!
