### ISSUE TITLE
WebSockify uses dependency 'tinycolor' that does not carry a license file

### ISSUE THREAD

**Issue by juj** [websockets/ws#1870]
`npm list` pointed me to WebSockify utilizing a dependency `tinycolor`, introduced in https://github.com/websockets/ws/commit/cc9725cc0212aad9646934f8caf2e9e61fa55042:

![image](https://user-images.githubusercontent.com/225351/115251422-36385e80-a133-11eb-8c52-d9f5bda7603d.png)

but unfortunately that package does not have a license file, leading to issue https://github.com/einaros/tinycolor/pull/9

Looking at the repository, it seems that tinycolor has not been updated in a while (last update 2012), so it might not update its licensing any time soon. Maybe WebSockify could reconsider this dependency, is there some other package or method to achieve the same, that would be safe for automated license checkers?

**Comment by lpinca** [comment]
`WebSockify` should update `ws`. They are using `ws@0.4.32`. The latest release is `ws@7.4.5`. `ws` is dependency free since version 7.2.1.

**Comment by lpinca** [comment]
I'm closing this as answered. Discussion can continue if needed.
