### ISSUE TITLE
Client connection to vsock 

### ISSUE THREAD

**Issue by ppmag** [websockets/ws#1871]
I understand, it is possible to connect to UNIX socket using "ws+unix://" url proto prefix.

My question: is there a way to connect to vsock  (AF_VSOCK family) ?
Vsock addresses usually are represented as two numbers separated by colon:   `cid:port`

The only workaround I can see for now is to use `socat` tool.   
Is there a better way?

Vsock man page: http://manpages.ubuntu.com/manpages/cosmic/man7/vsock.7.html

**Comment by lpinca** [comment]
No, this is not supported. The Node.js `net` module only allows [TCP and IPC connections](https://nodejs.org/api/net.html#net_socket_connect_options_connectlistener).

**Comment by lpinca** [comment]
I'm closing this as answered. Discussion can continue if needed.
