### ISSUE TITLE
Invalid WebSocket frame: invalid opcode 2

### ISSUE THREAD

**Issue by Borduhh** [websockets/ws#1874]
- [x] I've searched for any related issues and avoided creating a duplicate
      issue.

#### Description

Invalid WebSocket frame: invalid opcode 2

#### Reproducible in:

- version: 7.4.4
- Node.js version(s): 14.x.x

#### Steps to reproduce:
Reproduced daily from 3rd party IoT device running Linux. We don't see any abnormal events before receiving the error. Normal messages come through until the error. No other client has reported any errors.

#### Expected result:

WebSocket doesn't error at all.

#### Actual result:

```
RangeError: Invalid WebSocket frame: invalid opcode 2
    at Receiver.getInfo (/usr/src/app/node_modules/ws/lib/receiver.js:200:16)
    at Receiver.startLoop (/usr/src/app/node_modules/ws/lib/receiver.js:131:22)
    at Receiver._write (/usr/src/app/node_modules/ws/lib/receiver.js:78:10)
    at writeOrBuffer (node:internal/streams/writable:395:12)
    at Receiver.Writable.write (node:internal/streams/writable:340:10)
    at Socket.socketOnData (/usr/src/app/node_modules/ws/lib/websocket.js:900:35)
    at Socket.emit (node:events:378:20)
    at addChunk (node:internal/streams/readable:313:12)
    at readableAddChunk (node:internal/streams/readable:288:9)
    at Socket.Readable.push (node:internal/streams/readable:227:10)
```

#### Attachments:

```
const server = http.createServer(app);
const wss = (new Ws.Server({
  noServer: true,
  handleProtocols: SocketController.protocolCheck,
}) as unknown) as PlugPulseWebsocket.Server;
```

**Comment by lpinca** [comment]
This is expected. It means the client is sending a fragmented message and one frame after the first has opcode 2. This a violation of the specification. See https://tools.ietf.org/html/rfc6455#section-5.4.

Add a listener for the `'error'` event on the `WebSocket` object.

```js
wss.on('connection', function connection(ws) {
  ws.on('error', console.error);
});
```

**Comment by Borduhh** [comment]
Thank you. Our error handler is catching the error, but it seems like there is nothing we can do to remedy the issue on our end, right?

**Comment by lpinca** [comment]
> it seems like there is nothing we can do to remedy the issue on our end, right?

Correct, there is not much to do. The other peer must follow the specification.

**Comment by Borduhh** [comment]
Spoke with our 3rd party. They are using the `javax.websocket` library and are only fragmenting the messages if the message is too large for the buffer. Increasing the buffer should solve the problem. This sounds like something that might be NodeJS native and not this particular library though. Any thoughts?

**Comment by lpinca** [comment]
No, it has nothing to do with Node.js. If `javax.websocket` decides that a message is too big to send as a single frame and want to send it fragmented that is fine, but the all the frames of the fragmented message after the first must have opcode 0.

**Comment by lpinca** [comment]
I'm closing this as answered. Discussion can continue if needed.
