### ISSUE TITLE
ws引用utf-8-validate 意义何在

### ISSUE THREAD

**Issue by promotion-xu** [websockets/ws#1875]
- [ ] I've searched for any related issues and avoided creating a duplicate
      issue.

#### Reproducible in:

- version:  7.40
- Node.js version(s): 14.16.0
- OS version(s):

#### Steps to reproduce:
https://github.com/websockets/ws/blob/master/lib/validation.js#L86
1.  在我安装的ws库里，我发现这个isValidUTF8, 并没有被ws用到

2.还希望大佬答疑一下

3.

**Comment by promotion-xu** [comment]
sorry, I mean what's the meaning for the "utf-8-validate" in the ws ?
because ws don't use the method of isValidUTF8

**Comment by lpinca** [comment]
> because ws don't use the method of isValidUTF8

It does. See

- https://github.com/websockets/ws/blob/7.4.5/lib/validation.js#L95-L97
- https://github.com/websockets/ws/blob/master/lib/receiver.js#L13

**Comment by lpinca** [comment]
I'm closing as answered. Discussion can continue if needed.

**Comment by promotion-xu** [comment]
My version is 7.4.0, It not used isValidUTF8 in ws.

**Comment by lpinca** [comment]
It is. See https://github.com/websockets/ws/blob/7.4.0/lib/validation.js#L6-L9.

**Comment by promotion-xu** [comment]
I found it, But this method is only exporting, not quoted. So this dependency can be deleted

![image](https://user-images.githubusercontent.com/36992764/116191027-32719100-a75e-11eb-9dcb-7ab76f0b038a.png)

**Comment by lpinca** [comment]
> But this method is only exporting, not quoted.

Can you elaborate? I don't understand. The function is exported and then used here https://github.com/websockets/ws/blob/7.4.0/lib/receiver.js#L13.

**Comment by promotion-xu** [comment]
soory, I read it wrong
