### ISSUE TITLE
how to detect or receive  a networkError on ws

### ISSUE THREAD

**Issue by quanxufeng** [websockets/ws#1876]
ws client

how to detect and receive the connection error when the network is broken or interrupted,
because the connection of ws client gets silent after connect off then on.

#### Expected result:

ws client can throw out a networkError or automatically reconnect to the server when network is reconnected after interrupted

**Comment by lpinca** [comment]
Did you read https://github.com/websockets/ws#how-to-detect-and-close-broken-connections? Reconnection is outside of the scope of the library. You can use one of the many modules on npm to do it or implement it on your own.

**Comment by lpinca** [comment]
I'm closing this as answered. Discussion can continue if needed.

**Comment by quanxufeng** [comment]
I appreciate for your reply, could you recommend some modules which can be able to bind with WS  watching the status of the network connection. really thanks.
