### ISSUE TITLE
unnecessary copy with .toString() ? 

### ISSUE THREAD

**Issue by bitpup** [websockets/ws#1878]
Not to sound dumb, but, coming from a Node perspective, isn't this causing an unnecessary copy to occur?

https://github.com/websockets/ws/blob/fc7e27d12ad0af90ce05302afc85c292024000b4/lib/receiver.js#L437

perhaps it's required for browser API?

**Comment by lpinca** [comment]
We can't use the buffer directly because it's a text message so we need to convert it to a string. Is there another way?

**Comment by bitpup** [comment]
it may well be a text payload, leave it's interpretation to the user?

for now i have a revised method with the buffer going straight to JSON.parse

**Comment by lpinca** [comment]
Passing a buffer to `JSON.parse()` will convert it to a string implicitly.

> leave it's interpretation to the user?

We would then need to emit an additional argument in the `'message'` event to let the user know whether the message is a binary message or a text message. This is a breaking change. Currently a `Buffer` is used for binary messages and a `string` for text messages.

**Comment by bitpup** [comment]
Agreed, I have a solution for now.

I'm not too sure if I like the arbitration of payload that WS employs, I'm thinking perhaps, in this respect it does too much for the user, e.g. it just a payload... I am probably wrong ;-)

Well done on your efforts so far

**Comment by lpinca** [comment]
It is consistent with the browser interface where a `DOMString` or a `Blob`/`ArrayBuffer` is used depending on the type of the message.

There are already some deviations and we are not forced to follow it but I'm not very comfortable to always use a `Buffer`/`ArrayBuffer` because it's a big breaking change and there are a few edge cases like `WebSocket.createWebSocketStream()` that must be thought carefully.

I understand that is some cases, for example when passing data around, avoiding the string conversion might lead to better performances.

**Comment by bitpup** [comment]
for completeness, here's my hack

I've also dropped using `isValidUTF8` as I expect/hope `JSON.parse` will implement a similar validity check

```javascript
const
GET_INFO = 0,
Receiver = require('ws/lib/receiver'),
{concat} = require('ws/lib/buffer-util');

function _dataMessage() {
	if (this._fin) {
		if (this._opcode === 2) {
			Receiver.prototype.dataMessage.call(this);

		} else {
			const messageLength = this._messageLength;
			const fragments = this._fragments;
	
			this._messageLength = 0;
			this._fragments = [];

			this.emit('message', concat(fragments, messageLength));
		}
	}

	this._state = GET_INFO;
}
.
.
.
ws.on('open', function() {
	this._receiver.dataMessage = _dataMessage.bind(this._receiver);
});
```

Maybe, for the edge cases, facilitating overriding would be the next nice to have for WS.

**Comment by lpinca** [comment]
A possible, non breaking way to avoid converting to a string and give the user a `Buffer` for text messages is using a new option, similar to the `maxPayload` option. It might make sense in some cases but I'm not too keen to add it at this time.

If this feature is needed by a consistent number of users, I'm open to reconsider it.

**Comment by lpinca** [comment]
@bitpup I would not skip utf-8 validation:

1. It is mandatory per WebSocket specification.
1. Skipping it might lead to security vulnerabilities. This depends on what you are doing ofc.

**Comment by bitpup** [comment]
```
> JSON.parse(Buffer.from('\uFFFD'))
Uncaught SyntaxError: Unexpected token � in JSON at position 0
```

**Comment by lpinca** [comment]
You are missing double quotes.

**Comment by bitpup** [comment]
your test was incorrect. JSON.parse('"\uFFFD"') is using a string literal and not a buffer

**Comment by lpinca** [comment]
```js
JSON.parse(Buffer.from('"\uFFFD"'));
```

:)

**Comment by bitpup** [comment]
Buffer.from([0x22, 0xf8, 0x22]).toString() is valid JSON ;-p

**Comment by lpinca** [comment]
> `Buffer.from([0x22, 0xf8, 0x22]).toString()` is valid JSON ;-p

It indeed is after `toString()` because the invalid sequence (byte 2) is replaced with `U+FFFD`.

**Comment by bitpup** [comment]
I think I'm safe letting the Buffer replace non utf8, as corrupted strings will be a detectable trivial issue
