### ISSUE TITLE
default statusCode close()

### ISSUE THREAD

**Issue by danny-p93** [websockets/ws#1881]
Hello,
i just want to point out, if it a good idea to set a default statuscode for the ws.close() method.
It is marked as optional, but i noticed, that some ws Server libs need a statuscode to close the connection.
I thought because the code is optional when calling close() that there is a default code set (e.g. 1000). But after i added the 1000 myself it worked.
Or you could add a little hint in the ws.md documentation.

So just an idea.

Best Regards

**Comment by lpinca** [comment]
By default `ws.close()` does not send a status code. It just sends an empty close frame. See https://tools.ietf.org/html/rfc6455#section-7.1.5.

**Comment by danny-p93** [comment]
ah thanks for pointing that out, i just found the status code 1000, which says "normal close", so i thought that must be send in every case. So the serverside does not comply fully to the standard as it just keeps the connection when not receiving an close status code.

Thank you
