### ISSUE TITLE
After installing module found 83 vulnerabilities (3 low, 79 moderate, 1 high)

### ISSUE THREAD

**Issue by elmcapp** [websockets/ws#1884]
I am using the latest version of Electron and node. After installing this module I get the follow
found 83 vulnerabilities (3 low, 79 moderate, 1 high)

**Comment by lpinca** [comment]
There are no known vulnerabilities and this module has no dependencies.

```
$ npm i ws

added 1 package, and audited 2 packages in 2s

found 0 vulnerabilities
```

**Comment by elmcapp** [comment]
Wow. okay. Maybe something updated on me.
