### ISSUE TITLE
Send base64 data Memory Leak

### ISSUE THREAD

**Issue by yh4922** [websockets/ws#1885]
- version: ws 7.4.5
- Node.js version(s):  Node.js v12.20.0
- OS version(s): Windows 10 20H2

#### Steps to reproduce:
[https://github.com/yh4922/ws_memory_demo](https://github.com/yh4922/ws_memory_demo)

#### Expected result:
I hope the memory can be released after sending the data, but there is no

#### Actual result:
When the client connection reaches more than 10, the memory starts to rise significantly, until the system crashes

#### Attachments:
Some memory information is extracted through [node-heapdump](https://www.npmjs.com/package/heapdump) for distribution
![](https://www.hualigs.cn/image/60a5c8ce16973.jpg)

### Thanks for your answer

**Comment by lpinca** [comment]
In the reproduction example I had to change this line https://github.com/yh4922/ws_memory_demo/blob/3f6750d62e7298705098adb341c76510df942297/tmp.html#L107 to just `let uuid;` to make the broadcast send data to more clients.

After that change I've opened 20 tabs and I could not reproduce the leak. Memory usage stabilized at around 700 MiB.

I've also noticed an issue in the example code that prevents WebSocket connections from being GC'ed:

1. When a clients sends the `'clientOpen'` event, it is added to the [`clients` object](https://github.com/yh4922/ws_memory_demo/blob/3f6750d62e7298705098adb341c76510df942297/index.js#L99).
1. If a new clients connects and sends the `'clientOpen'` event with the same UUID, the previous connection is [closed](https://github.com/yh4922/ws_memory_demo/blob/3f6750d62e7298705098adb341c76510df942297/index.js#L98) and the new one is added to the [`clients` object](https://github.com/yh4922/ws_memory_demo/blob/3f6750d62e7298705098adb341c76510df942297/index.js#L99).

This is ok but there is no code that handles the case where the WebSocket connection is simply closed.

1. Assume that a reference to a WebSocket object is held under `clients['1f0d26bd-68f3-45fb-86a1-10fe1cb69aae']`.
1. The corresponding WebSocket connection is closed but the reference is not removed.
1. `clients['1f0d26bd-68f3-45fb-86a1-10fe1cb69aae']` cannot be GC'ed until a new connection with the same UUID is established.
1. If that UUID is not reused by another client, that WebSocket object is kept in memory forever creating a memory leak.

Finally, make sure that data is flowing. It's not a memory leak if you are producing data faster than it can be consumed. In that case you have to stop sending data. Every time you send data to a client, check the value `https://github.com/websockets/ws/blob/master/doc/ws.md#websocketbufferedamount`. If it keeps growing indefinitely, it means the receiver is slower than the sender so you have to stop sending. A threshold value could be used to throttle sends.

**Comment by yh4922** [comment]
> Here is a simplified test that mimics what is done in https://github.com/yh4922/ws_memory_demo.
> 
> ```
> $ cat server.js
> const WebSocket = require('ws');
> 
> const data = Buffer.alloc(300 * 1024).toString('base64');
> 
> const wss = new WebSocket.Server({ port: 8999 }, function listening() {
>   console.log('Server listening on *:8999')
> });
> 
> setInterval(function broadcast() {
>   for (const ws of wss.clients) {
>     for (let i = 0; i < 30; i++) {
>       ws.send(data);
>     }
>   }
> }, 50);
> 
> setInterval(function log() {
>   console.log('clients %d', wss.clients.size);
> 
>   for (const ws of wss.clients) {
>     console.log(
>       'bufferedAmount',
>       (ws.bufferedAmount / 1024 / 1024).toFixed(2) + 'MiB'
>     );
>   }
> 
>   for (const [key, val] of Object.entries(process.memoryUsage())) {
>     console.log(key, (val / 1024 / 1024).toFixed(2) + ' MiB');
>   }
> 
>   console.log('\n---\n');
> }, 10000);
> ```
> 
> ```
> $ cat clients.js
> const WebSocket = require('ws');
> 
> for (let i = 0; i < 10; i++) {
>   new WebSocket('ws://localhost:8999');
> }
> ```
> 
> Run it by running `node server.js` in a terminal and `node clients.js` in another terminal.
> 
> The test sends ~9 MiB of data to every client every 50 ms. This is probably too much even on localhost. Change the broadcast interval from 50 ms to 500 ms and then from 500 ms to 1 s and see the effect on `websocket.bufferedAmount`.
> 
> There is no memory leak, you are just writing too much data too fast.


thank!

I followed your instructions and made changes

Judge the length of bufferedAmount before sending data

Solved my problem very well
