### ISSUE TITLE
Please help me level up my WS game

### ISSUE THREAD

**Issue by matryoshcow** [websockets/ws#1891]
Hi! I don't mean to be a nuisance, but could someone please point me to some reading material that will help me understand how to architect a complex WebSockets server? I am making a game (of course) and I'm pretty sure I need a setup that goes beyond the entry-level stuff that can be gleaned from most material that one finds by performing a simple web search.

I am particularly interested in topics such as:
* Is it "okay" to have a main Node process that runs the WS server and communicates with other Node processes that run nothing but game logic?
* Load balancing.
* The advantages/disadvantages of performing tasks such as authentication through either the WS server or some underlying HTTP/S server, i.e. should _everything_ run over WebSockets or just the communication that strictly has to do with the "game" part (player commands and such)?
* From the `ws` docs: _"The "noServer" mode allows the WebSocket server to be completely detached from the HTTP/S server. This makes it possible, for example, to share a single HTTP/S server between multiple WebSocket servers."_ <-- this feels important, but I have to admit to not understanding why one would want multiple WebSocket servers as opposed to just one.
* etc. etc., you get it :)

I should mention a couple of things:
1. I already have a neat little setup for what you might call a technical alpha, so I'm comfortable with WebSockets on a superficial level both on the client and on the server; it's the scaling up part that really trips me up.
2. I don't expect direct answers here (though that would certainly be appreciated), I'm trying to find resources to educate myself.

Thanks! ^_^

**Comment by lpinca** [comment]
@matryoshcow This issue tracker is only for bugs in the library. For general support questions please use another channel.

**Comment by matryoshcow** [comment]
Yikes! Ok, will do. Thanks!
