### ISSUE TITLE
Messages received from a closed socket

### ISSUE THREAD

**Issue by awerlogus** [websockets/ws#1894]
- [x] I've searched for any related issues and avoided creating a duplicate issue.

Hello, we have been experiencing a very strange issue. 
Quite often when a message event is dispatched the socket turns out to be closed.
As a safety measure we check socket.readyState every time a message arrives.

```js
const { Server } = require('ws')
const assert = require('assert')

const port = 3000

const webSocketServer = new Server({ port })

webSocketServer.on('connection', socket => {
  socket.on('message', () => {
    // Sometimes this assert fails
    assert(socket.readyState === socket.OPEN)

    // Handle a message
  })
})
```

We can't reproduce this locally, however this issue can frequently be found in production.
Sometimes it even happens that we receive a queue of messages from the same **closed** socket.

Observed on NodeJS 14.6.0 and most probably can be observed on other versions.

What could the reason be?

**Comment by lpinca** [comment]
`'message'` events can be emitted while the ready state is `CLOSING`. This is expected and normal behavior. There might buffered data that might result in new messages when a `WebSocket` connection is closing. However `'message'` events should not be emitted when the ready state is `CLOSED`.

**Comment by punarinta** [comment]
Thank you for explanation @lpinca!
Is it safe to assume that if a socket is in `CLOSING` state it will be closed completely in a few next milliseconds? In other words how could a user measure the buffer size to decide whether it can or cannot be ignored?

**Comment by lpinca** [comment]
>Is it safe to assume that if a socket is in `CLOSING` state it will be closed completely in a few next milliseconds? In other words how could a user measure the buffer size to decide whether it can or cannot be ignored?

Yes, unless a closing handshake was initiated and the other peer is not responsive. For example `websocket.close()` starts a 30s timer that will forcibly close the connection upon expiration.

> And one more quick question: is it possible to send a reply to a socket that is `CLOSING` or does it mean it's open for reading only?

No more data can be written when the ready state is `CLOSING`.

**Comment by awerlogus** [comment]
Thanks a lot for your explanations! The ticket may now be closed.
