### ISSUE TITLE
Windows Power Options -> Wireless Adapter Setting causes slowness and closes Web Socket connection

### ISSUE THREAD

**Issue by NoUJoe** [websockets/ws#1896]
My app started to misbehave for no apparent reason. My WebSocket started to close with error code 1006 and no reason given. After some debugging, I discovered it was only when my laptop was unplugged. Even when I had the power mode set to "Best Performance" via system tray, it would still misbehave and close the socket arbitrarily. I discovered it was due to a setting in Windows Power Options -> WIreless Adapter Settings -> Power Saving Mode -> On Battery being set to anything but "Maximum Performance". This setting doesn't affect anything else system wide: Downloading, streaming video, speed test, other networking in Node (such as HTTP/HTTPS).

Another note, it seems it is something to do with the starting of a Node app. What I mean by this is, if I start my app with my charger plugged in, and then unplug it during execution, it doesn't cause the issue and the socket won't close. Likewise, if I start my app unplugged, and then plug my charger in during execution, it doesn't "fix" the issue and the WebSocket will continue to run slow and then close the connection with 1006 code. So it appears that whatever is going on, is happening upon startup of an application. Changing the setting in Windows Power Options to "Maximum Performance" alievates the issue and my app runs just fine, plugged or unplugged. But, as mentioned, this setting doesn't seem to affect anything else throughout my system.

Something else which may or may not be an issue is no `'error'` event is called before the `'close'` event is called.

For example:
When my app is running fine, I will be getting a constant stream of data at about 7Mbps. When the issue happens, it will be about 0.3Mpbs. When I run a speed test, I will get the same result regardless of the Power Options setting, or whether I'm plugged in or not.

#### Reproducible in:

- version: 7.4.6
- Node.js version(s): 14.17.0
- OS version(s): Windows 10

**Comment by lpinca** [comment]
It doesn't seem to be a ws issue. I think you'll get similar results with any other Node.js application. You can try opening an issue in the Node.js core repository if can reproduce the issue using only Node.js core modules but I think there is not much to do.

**Comment by NoUJoe** [comment]
Thanks for response and confirmation. Will search about this issue more and see if it affects other people and what they do for solutions (I guess just change the setting to "maximum performance"). Will close the issue on this repo
