### ISSUE TITLE
Warning: Calling ws.removeAllListeners() with setting wsServer.clientTracking=true causes memory leaks!

### ISSUE THREAD

**Issue by answergithub** [websockets/ws#1900]
I've searched for any related issues and avoided creating a duplicate issue.

#### Description

WebSocketServer(WSS) depends on 'close' event of ws to untrack it.
So if you call ws.removeAllListeners(), you also make WSS not to remove ws from clients!

#### Reproducible in:

- since clientTracking added

#### Steps to reproduce:

1. create a WebSocket.Server, with clientTracking=true
2. client connects to server, and disconnect
3. the websocket object will permanently be hold by WSS.

####

**Comment by lpinca** [comment]
This is expected and it is not a bug in the library. You should only remove the listeners you added yourself. This is valid not only for this library but also for Node.js core modules. Listeners not added by you might be used for cleanup purposes.

**Comment by answergithub** [comment]
> This is expected and it is not a bug in the library. You should only remove the listeners you added yourself. This is valid not only for this library but also for Node.js core modules. Listeners not added by you might be used for cleanup purposes.

Thanks @lpinca 
`ws.on('close', onClose)` onClose here is normally a lamda expression, so it is inconvenience to call `ws.off('close', onClose)`

I remember I didn't make such a mistake with c#. I guess it's because c# does not have a `removeAllListeners` function, haha.
