### ISSUE TITLE
How to change frame size

### ISSUE THREAD

**Issue by xsteadybcgo** [websockets/ws#1903]
- [x] I've searched for any related issues and avoided creating a duplicate
      issue.

#### Description
I use this repo to send msg , but i get error blow '1009:: Frame size of 3691876 bytes exceeds maximum accepted frame size'
I suspect it's the repository's problem with the frame in the websocket implementation ?

**Comment by xsteadybcgo** [comment]
How to control or change the frame size during websocket transmission

**Comment by lpinca** [comment]
I don't think the error is coming from `ws` because no error with a similar message is raised by this module. I think the error you are receiving is coming from [theturtle32/WebSocket-Node](https://github.com/theturtle32/WebSocket-Node) published as `websocket` on npm. See https://github.com/theturtle32/WebSocket-Node/blob/v1.0.34/lib/WebSocketFrame.js#L128-L129.

If you are using `ws` as client to connect to a server created with `websocket` and you get that error, you have two options

1. Change the `maxReceivedFrameSize` option if you control the server as documented here https://github.com/theturtle32/WebSocket-Node/blob/v1.0.34/docs/WebSocketServer.md#server-config-options
2. Split the message into smaller pieces and send it as a fragmented message. See https://github.com/websockets/ws/blob/7.5.0/doc/ws.md#websocketsenddata-options-callback.

**Comment by xsteadybcgo** [comment]
> I don't think the error is coming from `ws` because no error with a similar message is raised by this module. I think the error you are receiving is coming from [theturtle32/WebSocket-Node](https://github.com/theturtle32/WebSocket-Node) published as `websocket` on npm. See https://github.com/theturtle32/WebSocket-Node/blob/v1.0.34/lib/WebSocketFrame.js#L128-L129.
> 
> If you are using `ws` as client to connect to a server created with `websocket` and you get that error, you have two options:
> 
> 1. Change the `maxReceivedFrameSize` option if you control the server as documented here https://github.com/theturtle32/WebSocket-Node/blob/v1.0.34/docs/WebSocketServer.md#server-config-options
> 2. Split the message into smaller pieces and send it as a fragmented message. See https://github.com/websockets/ws/blob/7.5.0/doc/ws.md#websocketsenddata-options-callback.

Yes, the error does come from [theturtle32/WebSocket-Node](https://github.com/theturtle32/WebSocket-Node)，What I mean is, In the process of using `ws` I need to make the frame smaller to avoid this repository reporting errors. Here is my test script: 

```
/**
 * ws proxy server
 */
const WebSocket = require("ws");
const options = {
  perMessageDeflate: true,
};
const wss = new WebSocket.Server({
  port: 8899,
  ...options,
});
const wsc = new WebSocket("wss://rpc.polkadot.io/", options);
let client = null;
wss.on("connection", function connection(ws) {
  client = ws;
  ws.on("message", function incoming(message) {
    wsc.send(message);
  });
});

wsc.on("open", async () => {
  console.log(" messenger open");
  wsc.on("message", (data) => client.send(data));
});
```

```
/**
 * clients
 */
const { ApiPromise, WsProvider } = require("@polkadot/api"); //  Relies on the WebSocket-Node repository
async function client() {
  // const END_POINT = "wss://rpc.polkadot.io";
  const END_POINT = "ws://127.0.0.1:8899"; // proxy server
  const wsProvider = new WsProvider(END_POINT);
  const provider = await wsProvider.isReady;
  ApiPromise.create({
    provider,
  })
    .then(async (api) => {
      const blockHash = await api.rpc.chain.getBlockHash(29231);
      console.log(`blockhash: ${blockHash}`);
      const block = await api.rpc.chain.getBlock(blockHash);
      console.log(`${block}`);
    })
    .catch((error) => {
      console.log(error);
    });
}
client();
```
In the above code, Switching the END_POINT variable, when using the `ws` proxy service, probably because the frame returned by ws is too big, so it causes [theturtle32/WebSocket-Node](https://github.com/theturtle32/WebSocket-Node) to report an error I just added a layer of proxy through ws, should this problem be solved by controlling the frame size of ws? Is there any example to refer to

**Comment by xsteadybcgo** [comment]
I Split the message into smaller pieces and send it as a fragmented message. yeah, The `fin` option of the send method is the key to allocating the buffer, Here is the code snippet for the benefit of those who encountered the same problem as me.

💡

Change to above code to 
```
wsc.on("open", async () => {
  console.log(" messenger open");
  wsc.on("message", (data) => {
    const len = Buffer.from(data).length;
    const maxReceivedMessageSize = 1024 * 1024;
    const maxBufferLen = 1024 * 64;
    if (len > maxReceivedMessageSize) {
      const buffer = Buffer.from(data);
      for (let i = 0; i <= Math.floor(len % maxBufferLen); i++) {
        if (i !== Math.floor(len % maxBufferLen)) {
          const str = buffer
            .slice(i * maxBufferLen, (i + 1) * maxBufferLen)
            .toString();
          client.send(str, {
            fin: false,
          });
        } else {
          const str = buffer.slice(i * maxBufferLen).toString();
          client.send(str, {
            fin: true,
          });
        }
      }
    } else {
      client.send(data);
    }
  });
});
```
