### ISSUE TITLE
Question | How do I pass the http request to ws that is created via worker_threads?

### ISSUE THREAD

**Issue by Keller18306** [websockets/ws#1907]
How do I pass the http request to ws that is created via worker_threads?

![image](https://user-images.githubusercontent.com/23178771/123175687-df306c00-d48a-11eb-89bb-e59588fdfc43.png)
![image](https://user-images.githubusercontent.com/23178771/123175714-e6577a00-d48a-11eb-9130-d26f45f53618.png)
When I send a request or socket to a worker, then I get a clone error
![image](https://user-images.githubusercontent.com/23178771/123175778-02f3b200-d48b-11eb-9a70-4425047cd8d8.png)

**Comment by lpinca** [comment]
You can [send a socket to a child process](https://nodejs.org/api/child_process.html#child_process_example_sending_a_socket_object) but you can't do the same with worker threads. See https://nodejs.org/api/worker_threads.html#worker_threads_port_postmessage_value_transferlist

> Unlike with child processes, transferring handles such as network sockets is currently not supported.

**Comment by lpinca** [comment]
I'm closing this as answered.

**Comment by Keller18306** [comment]
Okay, it does. But how do I provide this socket to the ws module?

**Comment by Keller18306** [comment]
![image](https://user-images.githubusercontent.com/23178771/123275479-0596eb80-d50d-11eb-99d1-88cdf899f8fc.png)

**Comment by Keller18306** [comment]
![image](https://user-images.githubusercontent.com/23178771/123275589-1cd5d900-d50d-11eb-90b9-0f8cbf93a008.png)
![image](https://user-images.githubusercontent.com/23178771/123275601-219a8d00-d50d-11eb-85b7-1a6f9b9de2c4.png)

**Comment by lpinca** [comment]
See the discussion in this issue https://github.com/websockets/ws/issues/154. FYI, the feature is not officially supported.

**Comment by Keller18306** [comment]
![image](https://user-images.githubusercontent.com/23178771/123278519-ae464a80-d50f-11eb-98e2-21ae5e258194.png)
Thanks, this works as I need it !!!
