### ISSUE TITLE
Link to testing library @relaycorp/ws-mock

### ISSUE THREAD

**Issue by gnarea** [websockets/ws#1909]
[@relaycorp/ws-mock](https://github.com/relaycorp/ws-mock-js) allows you to unit test `ws` servers and clients.

If you're happy to link to this project, I can create a PR. I'd probably add it as a new FAQ.

**Comment by lpinca** [comment]
Thanks but it is not something that is frequently asked for and I would prefer to not promote a particular project.

**Comment by gnarea** [comment]
Fair enough 👍🏾
