### ISSUE TITLE
ws doesn't build in Windows 8 (discovered while deploying Karma)

### ISSUE THREAD

**Issue by jcastill0** [websockets/ws#191]
I was trying to deploy Karma and I got an build error pointing to ws.
The suggested alternatives won't work because NET 2.0 SDK and/or Visual Studio 2005 are not supported in Windows 8.
I created a ticket (issue) to the Karma-runner developer and he suggested that I bring it to your attention.
https://github.com/karma-runner/karma/issues/536#issuecomment-17758731

The actual error is:
 MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe". To fix this, 1) install the .NET Framework 2.0 SDK, 2) install Microsoft Visual Studio 2005 or 3) add the location of the component to the system path if it is installed elsewhere. [C:\Users\Julio\AppData\Roaming\npm\node_modules\karma\node_modules\socket.io\node_modules\socket.io-client\node_modules\ws\build\binding.sln]

thanks

**Comment by heri16** [comment]
28\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
MSBUILD : error MSB4132: The tools version "2.0" is unrecognized. Available tools versions are "4.0".
