### ISSUE TITLE
What is the max number of connections / what amount of memory per ‘ws’ is consumed?

### ISSUE THREAD

**Issue by RichardWright** [websockets/ws#1911]
Hi

I'm trying to work out how many websockets we can have per gig of memory. Any idea what this is?

**Comment by lpinca** [comment]
The answer is, it depends. It depends on how much data is buffered per connection. You can easily test yourself using https://nodejs.org/api/process.html#process_process_memoryusage.

**Comment by RichardWright** [comment]
Is this a library that you would use with large amounts of data? We are sending large initial amounts down our sockets, but this is making new connections quite expensive. I'm trying to pick apart how much is the websocket and how much is our data.

**Comment by lpinca** [comment]
If you are sending a lot of data the [streaming interface](https://github.com/websockets/ws/blob/7.5.2/doc/ws.md#websocketcreatewebsocketstreamwebsocket-options) might help you to keep memory usage under control.

**Comment by lpinca** [comment]
I'm closing this as answered. Discussion can continue if needed.
