### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Umut-Ozkan** [websockets/ws#1913]
How To Enable CORS in My WebSocket? (allow disable access)

**Comment by lpinca** [comment]
The CORS policy does not apply to WebSocket.

**Comment by Umut-Ozkan** [comment]
So how do I turn off others from entering?

**Comment by lpinca** [comment]
> So how do I turn off others from entering?

Blocking by IP or with an authentication layer.

**Comment by Umut-Ozkan** [comment]
I'm Closing This
<hr>
Please Enable Discussions

Instead of Opening Problems, There Are Many Opportunities To Chat With Our Questions

`My English are bad sorry translated by google`

Repo Settings > Features
![image](https://user-images.githubusercontent.com/68606364/125416357-68a580fa-2e0a-451b-931f-0b81cb28bd5e.png)

**Comment by Umut-Ozkan** [comment]
@lpinca please read this
