### ISSUE TITLE
Clarify use of text frames with streams

### ISSUE THREAD

**Issue by jberger** [websockets/ws#1915]
#### Description

When using ws with `createWebSocketStream` it is not currently clear how to force the writable side of the duplex to use text frames rather than binary. Since the `send` method is not accessible by design of the stream api, and the duplex option defaults prevent setting the [objectMode](https://github.com/websockets/ws/blob/4c1849a61e773fe0ce016f6eb59bc3877f09aeee/lib/stream.js#L68-L71) I was unsure how to proceed.

I noticed that there was an in-progress PR that referenced a very similar issue, notably with the readObjectMode and so I commented [there](https://github.com/websockets/ws/pull/1904#issuecomment-878590154) however the maintainers have stated that they thought it should be its own report and rightly so. Meanwhile they did offer a working suggestion, namely setting the `decodeStrings` option to `false`. While this does work, I must admit that I had never seen this option for streams before and given its name it seemed to me that it would have done something completely different.

I would propose that either (a) the options object be more flexible so that objectMode could not be set (which overrides the `read` and `write` object modes) and `writeObjectMode` be set to true (this option would conform to my understanding of the paradigm of writing a blob/buffer or string to the websocket to choose its frame type) or else (b) show the `decodeStrings` in the documentation for `createWebSocketStream` along with `encoding` so that others like me will not have to go through this process in the future.

#### Reproducible in:

- version: 7.5.3
- Node.js version(s): all
- OS version(s): all

**Comment by lpinca** [comment]
a) Is not an option. It breaks backpressure handling. See discussion in https://github.com/websockets/ws/issues/1640.
b) See https://github.com/websockets/ws/blob/master/doc/ws.md#websocketcreatewebsocketstreamwebsocket-options and https://nodejs.org/api/stream.html#stream_new_stream_duplex_options and https://nodejs.org/api/stream.html#stream_new_stream_writable_options.

**Comment by lpinca** [comment]
I'm closing this as answered. Discussion can continue if needed.
