### ISSUE TITLE
Sockets crashes with incomprehensible error message

### ISSUE THREAD

**Issue by jestorocompany** [websockets/ws#1916]
Hi,

we implemented a chat based on ws. I worked for quite a while without problems - but recently the socket seems to crash every 20 minutes or so with the error message:

RangeError: Invalid WebSocket frame: invalid status code 22373

We have no clue what exactly this message means and what to do about it.

Maybe, someone has a hint for us.

Thanks in advance
Michael

**Comment by lpinca** [comment]
It means a peer is receiving a close frame with an invalid status code:

```js
const WebSocket = require('ws');

const wss = new WebSocket.Server({ port: 0 }, function () {
  const ws = new WebSocket(`ws://localhost:${wss.address().port}`);

  ws.on('open', function () {
    ws._socket.write(Buffer.from('8882000000005765', 'hex'));
  });
});

wss.on('connection', function (ws) {
  ws.on('error', console.error);
});
```

Add a listener for the `'error'` event.

**Comment by lpinca** [comment]
I'm closing this as answered. Discussion can continue if needed.
