### ISSUE TITLE
Signalr load balancing is sometimes good and sometimes bad

### ISSUE THREAD

**Issue by guangchliu** [websockets/ws#1917]
![image](https://user-images.githubusercontent.com/66109533/125946210-929bc1ea-1530-442a-bd13-7e2f96236388.png)
![image](https://user-images.githubusercontent.com/66109533/125946307-13bd081d-7c7d-46fb-afca-5b0c78d9c0aa.png)
![image](https://user-images.githubusercontent.com/66109533/125947094-5cebc720-95c2-440f-985c-cfb080734301.png)

**Comment by lpinca** [comment]
I'm not sure what to do with this bug report. Please fill the issue template. It seems you are not even using `ws` but the browser WebSocket.

**Comment by lpinca** [comment]
I'm closing this as it does not seem to be a `ws` issue.
