### ISSUE TITLE
localhost signalr service works but not for individual users

### ISSUE THREAD

**Issue by viswanathan1693** [websockets/ws#1919]
- [ ] I've searched for any related issues and avoided creating a duplicate
      issue.

#### Description

signalr message is not getting passed to individual users if we use local signalr service emulator

I have given connection string like below,
"AzureSignalRConnectionString": "Endpoint=http://localhost;Port=8888;AccessKey=ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789ABCDEFGH;Version=1.0;"

using command prompt, I have started asrs emulator like below
=> asrs-emulator start

#### Reproducible in:

- version:
- Node.js version(s):
- OS version(s):

#### Steps to reproduce:

1. Install signalr service emulator using below command,
=> dotnet tool install --global Microsoft.Azure.SignalR.Emulator --version 1.0.0-preview1-10767

2. Configure signalr service connectionstring like below
"AzureSignalRConnectionString": "Endpoint=http://localhost;Port=8888;AccessKey=ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789ABCDEFGH;Version=1.0;"

3. configure below method in azure function,
[FunctionName("negotiate")]
        public static SignalRConnectionInfo Negotiate(
            [HttpTrigger(AuthorizationLevel.Anonymous, "post", "get")] HttpRequest req,
            [SignalRConnectionInfo(HubName = "notifications")] SignalRConnectionInfo connectionInfo, IBinder binder)
        {
            string userId = req.Headers["x-ms-signalr-userid"].ToString();

            SignalRConnectionInfoAttribute attribute = new SignalRConnectionInfoAttribute
            {
                HubName = "notifications",
                UserId = userId
            };

            connectionInfo = binder.Bind<SignalRConnectionInfo>(attribute);

            return connectionInfo;
        }

        [FunctionName("broadcast")]
        public static Task Broadcast(
            [HttpTrigger(AuthorizationLevel.Anonymous, "post")] HttpRequest req,
            [SignalR(HubName = "notifications")] IAsyncCollector<SignalRMessage> signalRMessages)
        {

            var userId = req.Headers["x-ms-signalr-userid"].ToString();

            return signalRMessages.AddAsync(
                new SignalRMessage
                {
                    UserId = userId,
                    Target = "newMessage",
                    Arguments = new[] { "Notification from SignalR" }
                });
        }

        [FunctionName("broadcastall")]
        public static Task BroadcastAll(
            [HttpTrigger(AuthorizationLevel.Anonymous, "post")] HttpRequest req,
            [SignalR(HubName = "notifications")] IAsyncCollector<SignalRMessage> signalRMessages)
        {
            return signalRMessages.AddAsync(
                new SignalRMessage
                {
                    Target = "newMessage",
                    Arguments = new[] { "Notification from SignalR" }
                });
        }

4. try to execute azure function using Postman like below
![image](https://user-images.githubusercontent.com/12513475/126155088-0d4141d7-bb6d-4801-9e09-70eaa7232c64.png)

#### Expected result:

broadcastall method is working fine.
broadcast should work for individual users

#### Actual result:

broadcast is not working for individual users

**Comment by lpinca** [comment]
How is this a `ws` issue?

**Comment by viswanathan1693** [comment]
> There is no trace of `ws` in the issue description. How can this be a `ws` issue?

If we use below connection string in azure function , it is working fine. I can able to get signalr message for individual users. 

"AzureSignalRConnectionString": "Endpoint=https://signalrservice.service.signalr.net;AccessKey=<AcessKey>;Version=1.0;"

 I have problem with local signalr service emulator.

**Comment by lpinca** [comment]
> I have problem with local signalr service emulator.

Ok but is it related to `ws`? If not you are in the wrong repository. This issue tracker is only for bugs in the `ws` module.

**Comment by viswanathan1693** [comment]
Ok I will post this issue in signalr service issues tracker
