### ISSUE TITLE
Specify localAddress in WS Client

### ISSUE THREAD

**Issue by NN-Binary** [websockets/ws#1920]
Hi

const ws = new WebSocket('ws://www.host.com/path', {
  perMessageDeflate: false,
  localAddress: '192.168.1.2' // HERE
});

I would like to bind a specific localAddress, NodeJS HTTP/HTTPS/NET library allows it, is it possible with this library?

**Comment by lpinca** [comment]
Yes, you can do that.

**Comment by NN-Binary** [comment]
Thanks for the reply.
I'm not sure I'm seeing localAddress at all in the doc you've sent

**Comment by lpinca** [comment]
> Any other option allowed in `http.request()` or `https.request()`. Options given do not have any effect if parsed from the URL given with the `address` parameter.

**Comment by NN-Binary** [comment]
Oh god my bad, thank you!
