### ISSUE TITLE
ERROR Invalid WebSocket frame: invalid status code 22373

### ISSUE THREAD

**Issue by arpowers** [websockets/ws#1922]
- [x ] I've searched for any related issues and avoided creating a duplicate
      issue.

#### Description

This appears to be a new issue that is creeping up due to a change somewhere. There are only a few mentions of this code `22373` across the internet but it's been in the last month or so. To me this suggests are recent changes somewhere related to websockets. 

The error is `ERROR Invalid WebSocket frame: invalid status code 22373`

<img width="1059" alt="Screen Shot 2021-07-24 at 11 22 53 AM" src="https://user-images.githubusercontent.com/308134/126877867-772514dc-228e-4509-bd81-2e8cd3b867bc.png">

This error has been completely crashing our analytics server whenever it occurs. Would suggest that WS has a way to catch errors like this as we are likely having data loss because of it. 

#### Reproducible in:

- version:  latest
- Node.js version(s): 14
- OS version(s): latest

#### Steps to reproduce:

1. Unsure how to reproduce a socket frame with this error code

**Comment by lpinca** [comment]
Duplicate of https://github.com/websockets/ws/issues/1916?

**Comment by arpowers** [comment]
@lpinca yes, the same problem. I didn't see that issue as it was closed. 

Not sure where the status code is coming from, but whatever the case, I'd assume it shouldn't be crashing our entire server?  (I can't figure out how to catch this error)

In addition, seems like something changed across the web recently is creating is throwing this status code relatively frequently.

**Comment by lpinca** [comment]
> Not sure where the status code is coming from, but whatever the case, I'd assume it shouldn't be crashing our entire ingest server?

Did you see https://github.com/websockets/ws/issues/1916#issuecomment-879791503? That example triggers the error and the server does not crash. Make sure you have a listener for `'error'` event and that it is not removed until the `'close'` event is emitted.

**Comment by lpinca** [comment]
Are you removing the `'error'` listener sometimes during the lifecycle of the `WebSocket` object?

**Comment by arpowers** [comment]
@lpinca thanks for the follow up, i followed your guide and redeployed last night. It might be working actually, no crashes over night. 

Getting errors caught like this one (is that the same issue?)

<img width="690" alt="Screen Shot 2021-07-26 at 8 50 30 AM" src="https://user-images.githubusercontent.com/308134/127019607-a5f7d46f-70bc-4a09-a5e0-6721b0577aaa.png">

**Comment by lpinca** [comment]
Yes. That is not the same error but it is still caused by an invalid frame.

**Comment by ltm** [comment]
FWIW, we've noticed Safari on iOS 15 beta (`Version/15.0 Mobile/15E148 Safari/604.1`) send an invalid close frame. The frame is missing the [two-byte status code](https://datatracker.ietf.org/doc/html/rfc6455#section-5.5.1), so the first two bytes of the body ("WebSocket is closed...") are interpreted as the status code: `'We' == 0x5765 == 22373`. 

![Screen Shot 2021-07-26 at 4 11 10 PM](https://user-images.githubusercontent.com/714118/127053504-2c755ef7-a03f-4cbe-9da5-fbdc7953d06e.png)

**Comment by arpowers** [comment]
@ltm INTERESTING. Great work!

well for posterity there is the cause of the issue, this is the first time it's been documented in a discoverable way... 

@lpinca thank you as well for this rock solid piece of software

**Comment by matthewp** [comment]
Hi everyone, I've been able to replicate this issue specifically when using the `NSURLSession WebSocket` feature of Safari. If you go to `Develop -> Experimental Features` and select `NSURLSession WebSocket` you should see this error.

It sounds like maybe this a bug in Safari then?

**Comment by goktugyil** [comment]
> Are you removing the `'error'` listener sometime during the lifetime of the `WebSocket` object?

https://github.com/websockets/ws/issues/1611#issuecomment-873973558

Any input in this? The error listener was always there for years, it caught a lot of errors, but this specific `22373` one crashed the whole server

**Comment by lpinca** [comment]
@goktugyil see https://github.com/websockets/ws/issues/1916#issuecomment-879791503.

**Comment by dhillon-lovey3110** [comment]
RangeError: Invalid WebSocket frame: invalid status code 60015

crashing on this, any ideas ?

**Comment by daixianceng** [comment]
> 

Did you solve it? I am now stuck with the error of "60015"

**Comment by RenatoExpert** [comment]
> @dhillon-lovey3110 Did you solve it? I am now stuck with the error of "60015"

I have the same problem :(

**Comment by codeedog** [comment]
I solved this when I was having this problem with Angular 15, Node 18, Webpack Dev Server 4.11.1.

Match the URL for WebSocket to the proxy configuration file. DO NOT USE use the top level `/`. In my example below, I used `/pipe` although it also worked with `/api` for a `ws://` target.

````
// Browser JavaScript snippet
const socket$ = new WebSocketSubject<Message>("ws://localhost:4200/pipe");

# proxy.conf.json
{
  "/api": {
    "target": "http://localhost:3000",
    "secure": false
  },
  "/pipe": {
    "target": "ws://localhost:3000",
    "secure": false,
    "ws": true,
    "logLevel": "debug"
  }
}
````

Below config which didn't work with Angular 15, Webpack Dev Server 4.11.1, but did work in my prior Angular 12, Webpack Dev Server 3.11.3 configuration. It was failing in upgrade and I had no idea why until I beat my head against the wall, the desk, the keyboard, ... and somehow tripped upon the above configuration.

````
*** DOES NOT WORK ***
// Browser JavaScript snippet
const socket$ = new WebSocketSubject<Message>("ws://localhost:4200/");

# proxy.conf.json
{
  "/api": ...,
  "/": {
    "target": "ws://localhost:3000",
    ...
  }
}
````

Finally, in my shell I ran `npm ls http-proxy-middleware` to find out which version of Webpack Dev Server I was running under each configuration (Angular 15, Angular 12). I've also included the results of the run.

For Angular 15:

````
> npm ls http-proxy-middleware
project@0.2.0 /Users/codeedog/src/project
├─┬ @angular-devkit/build-angular@15.0.3
│ └─┬ webpack-dev-server@4.11.1
│   └── http-proxy-middleware@2.0.6
└─┬ @nrwl/angular@15.3.0
  └─┬ @nguniversal/builders@15.0.0
    └── http-proxy-middleware@2.0.6 deduped
````

For Angular 12:

````
npm ls http-proxy-middleware
project@0.1.0 /Users/codeedog/src/project
└─┬ @angular-devkit/build-angular@12.2.18
  └─┬ webpack-dev-server@3.11.3
    └── http-proxy-middleware@0.19.1 
````
