### ISSUE TITLE
docs missing the .on method

### ISSUE THREAD

**Issue by ben-spector-cc** [websockets/ws#1923]
- [ Yes ] I've searched for any related issues and avoided creating a duplicate
      issue.

#### Description

I'm having the hardest time finding in the [documentation](https://github.com/websockets/ws/blob/master/doc/ws.md) the `.on` method for both the WebSocketServer class and the WebSocket objects passed to the callback for the `'connection'` event. 

I understand how to use these methods from the usage examples, however, it is a bit confusing that they aren't in the docs.

**Comment by lpinca** [comment]
https://github.com/websockets/ws/blob/master/doc/ws.md#class-websocketserver

> This class represents a WebSocket server. It extends the `EventEmitter`.

https://github.com/websockets/ws/blob/master/doc/ws.md#class-websocket

> This class represents a WebSocket. It extends the `EventEmitter`.

I'm closing this as answered.
