### ISSUE TITLE
Can I use this repo to get websocket http request header: sec-websocket-key

### ISSUE THREAD

**Issue by zydjohnHotmail** [websockets/ws#1936]
Hello:
I need some code sample on how to detect WebSocket (wss) requests.
Basically, I can visit this URL with Chrome: https://www.websocket.org/echo.html
And click on “Connect” button to connect with the WebSocket server: wss://echo.websocket.org
Then type something in the message box, or using the default text in the message box “Rock it with HTML5 WebSocket”, then click on “Send” button, then I can see the messages on the “log” textbox, like this:
CONNECTED
SENT: Rock it with HTML5 WebSocket
RECEIVED: Rock it with HTML5 WebSocket
Then open Developer Tools from Chrome, on “Network” tab, I can see there is only one WS (WebSocket) request with the following headers:
Request URL:
wss://echo.websocket.org/?encoding=text
1. Request Method:
GET
2. Status Code:
101 Web Socket Protocol Handshake
I can use Chrome developer tools to convert the WebSocket request to Node.JS fetch:
fetch("wss://echo.websocket.org/?encoding=text", {
"headers": {
"accept-language": "en-US,en;q=0.9,fr;q=0.8,nl;q=0.7,zh-CN;q=0.6,zh;q=0.5,zh-TW;q=0.4",
"cache-control": "no-cache",
"pragma": "no-cache",
"sec-websocket-extensions": "permessage-deflate; client_max_window_bits",
"sec-websocket-key": "PVg+yYO5Q3EVgtPLLV2QXQ==",
"sec-websocket-version": "13"
},
"body": null,
"method": "GET",
"mode": "cors"
});
Let me know how I can use this repo to get all the headers, actually, there is only one header I need to get is: "sec-websocket-key": "PVg+yYO5Q3EVgtPLLV2QXQ=="

In my real-world job, I have to detect webscoket request from one specific web site. Using Chrome devtools, I can see that the web page uses rather complicated JavaScript to generate a websocket request, and sends it to the server.  I want to write some kind of browser extension to detect the websocket request headers, actually, I only need this header: "sec-websocket-key".
Please advise,
Thanks,

**Comment by lpinca** [comment]
This issue tracker is only for bugs in the library. For general support question please use another channel.

Anyway, do you need to read the headers on the server of the client? The request headers or response headers? In a browser or not?

**Comment by lpinca** [comment]
FYI, the value of the `Sec-WebSocket-Key` request header are just [16 random base64 encoded bytes](https://github.com/websockets/ws/blob/d5e3549a0350dd94103af88f6fb329d9a27ce193/lib/websocket.js#L646). You can read this value in the browser.

**Comment by lpinca** [comment]
I don't think `ws` is of any use for this. Take a look at https://developer.chrome.com/docs/extensions/reference/webRequest/ instead.

**Comment by lpinca** [comment]
I'm closing this as answered.
