### ISSUE TITLE
Pause and resume of message events

### ISSUE THREAD

**Issue by lb99bl** [websockets/ws#1937]
Hi, I wrote code to pause/resume the message events in a stream way.

In receiver.js I inserted this line in getInfo():
if (this._paused) { this._loop=false; return }

In websocket.js I added 2 lines after "constructor" (I dont know what it is, but I am still learning JS):
pause() { this._receiver._paused = true }
resume() { this._receiver._paused = false ; this._receiver.startLoop(function(err){if (err) console.log('dont know what to do with error')})}

I am sorry for writing here, but I am still learning JS and Github, but I didn't want to wait sharing this code.

**Comment by lpinca** [comment]
Hi, thanks for sharing but this issue tracker is only for bugs in the library.

To properly pause and resume retrieval of `'message'` events use the [stream API](https://github.com/websockets/ws#use-the-nodejs-streams-api):

```js
const ws = new WebSocket('wss://echo.websocket.org/');
const duplex = createWebSocketStream(ws, { encoding: 'utf8' });

ws.on('message', function (data, isBinary) {
  console.log(data);
});

duplex.pause();
```

Keep in mind that `'message'` events might still be emitted after `duplex.pause()` is called until the readable buffer of `duplex` is full.

**Comment by lb99bl** [comment]
Thank you for your reply :)

I tried createWebSocketStream before, but it didn't work. If a browser connects to this proxy script, it only receives binary messages with base64 encoded data in it (besides script errors like"WebSocket is not open"). Or am I doing something wrong?

```javascript
ws_proxy = new (require('ws').Server)({server:https_server})
ws_proxy.on('connection', function(ws_client, req_client){
 const ws_server = new (require('ws'))('wss://nieuwsoverzicht.be/', {})
 ws_server.on('open', function () {
  const duplex_client = require('ws').createWebSocketStream(ws_client, { encoding: 'utf8' })
  const duplex_server = require('ws').createWebSocketStream(ws_server, { encoding: 'utf8' })
  duplex_server.pipe(duplex_client)
 })
```

**Comment by lpinca** [comment]
Use the `decodeStrings` option instead of `encoding` when you create the `duplex_client` and set it to `false`:

```js
const duplex_client = require('ws').createWebSocketStream(ws_client, { decodeStrings: false });
```

See https://nodejs.org/api/stream.html#stream_new_stream_writable_options.

**Comment by lb99bl** [comment]
Ciao. That was very helpful. I added decodeStrings besides the encoding (client and server talks to each other via this proxy). One last question: if the client (browser in my case) disconnects, I get this error:
```
Error: WebSocket is not open: readyState 3 (CLOSED)
    at sendAfterClose (/node_modules/ws/lib/websocket.js:777:17)
    at WebSocket.send (/node_modules/ws/lib/websocket.js:345:7)
    at Duplex.duplex._write (node_modules/ws/lib/stream.js:157:8)
    at writeOrBuffer (node:internal/streams/writable:389:12)
    at _write (node:internal/streams/writable:330:10)
    at Duplex.Writable.write (node:internal/streams/writable:334:10)
    at Duplex.ondata (node:internal/streams/readable:754:22)
    at Duplex.emit (node:events:394:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
```
If I understand your code well, the duplex stream cleans up itself (.destroy()) and also the associated websocket (.terminate()). So does it mean that everything is cleaned up by itself and I can safely ignore the error without memory leaks?

**Comment by lpinca** [comment]
Yes, and the error should also unpipe `duplex_server` from `duplex_client` but you have to end `duplex_server` to close the upstream connection.

```js
duplex_client.on('close', function() {
  duplex_server.end(); // or `duplex_server.destroy()`
});
```

**Comment by lb99bl** [comment]
Oh, I understand. Thank you for everything.

**Comment by lpinca** [comment]
No problem. I'm closing this.
