### ISSUE TITLE
SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by reesericci** [websockets/ws#1939]
- [X] I've searched for any related issues and avoided creating a duplicate
      issue.

#### Description

When running client or server code via nodejs I get this error: `SyntaxError: Cannot use import statement outside a module`

#### Reproducible in:

- version: 8.2.0
- Node.js version(s): 14.17.0
- OS version(s): Fedora 34

#### Steps to reproduce:

1. Copy the example server code into server.js

2. Then run `node server.js`

#### Expected result:

It creates a server

#### Actual result:

I get this error:
```
(node:574766) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
/home/reesericci/endychat/server.js:1
import { WebSocketServer } from 'ws';
^^^^^^

SyntaxError: Cannot use import statement outside a module
```

**Comment by lpinca** [comment]
Save your file with the `.mjs` extension. See https://nodejs.org/api/esm.html#esm_enabling for more details.
