### ISSUE TITLE
GH discussions

### ISSUE THREAD

**Issue by reesericci** [websockets/ws#1941]
- [ X] I've searched for any related issues and avoided creating a duplicate
      issue.

#### Description

Please enable github discussions to allow for stackoverflow-like conversation but confined to this project.

**Comment by lpinca** [comment]
Maybe but not now.

**Comment by reesericci** [comment]
why not?

**Comment by lpinca** [comment]
It's an additional maintenance burden. I _should_ answer questions posted there if it is enabled.

**Comment by reesericci** [comment]
ok makes sense i guess

**Comment by reesericci** [comment]
ok makes sense i guess

**Comment by lpinca** [comment]
I'm not against it. Discussions are part of the development process but it really depends on their quality. GitHub Discussions of other projects are filled with feature and help requests and I would prefer to not have them here. I hope it makes sense.
