### ISSUE TITLE
Messages are in binary instead of plain text.

### ISSUE THREAD

**Issue by vishnuc** [websockets/ws#1942]
I have simple websocket server and client in node js ,

my server

```
var WebSocketServer = require("ws").Server;
var wsServer = new WebSocketServer({ port: 5555 });

wsServer.on("connection", function (ws) {
  console.log("Connection established!");
  ws.send("Connection established!");
  ws.on("message", function (msg) {
    ws.send("Got your message!");
    console.log(msg);
    console.log(msg.data);
  });
});
```
and client looks like below

```
var ws = new WebSocket("ws://localhost:5555");
function sendMsg() {
 ws.send(document.getElementById("msg").value);
}
ws.onmessage = function(event) {
    console.log(event);
 console.log("server mgs:", event.data);
}
ws.onerror = function(event) {
 console.log("Server err:", event.data);
}
```
Connections are getting established but the message received is displaying something like below ,instead of actual text that i have sent from client.I am using visual code terminal in mac.

```
Received: <Buffer 74 65 74>
Received: <Buffer 74 65 74 64 64>
```

**Comment by wh0** [comment]
This only very subtly documented with a sneaky `%s` used in the README example

```js
console.log('received: %s', message);
```

It's more clearly stated in the actual commit message:

> Avoid decoding text messages and close reasons to strings. Pass them as
`Buffer`s to the listeners of their respective events. Also, make
listeners of the `'message'` event take a boolean argument to speficy
whether or not the message is binary.

https://github.com/websockets/ws/commit/e173423c180dc1e4e6ee8938d9e4376a7a8b9757

It references some issues, where it sounds like performance had been a concern. I want to urge the authors of this library not to prioritize string decoding performance over this specific piece of utility (or arguably, correctness).

**Comment by vishnuc** [comment]
Yes %S is printing properly , but I want to do certain operation with message like

`If(message == "ping")
`
how do I just receive plain text ?

**Comment by lpinca** [comment]
See https://github.com/websockets/ws/releases/tag/8.0.0 and https://github.com/websockets/ws/blob/8.2.1/doc/ws.md#event-message.

**Comment by lpinca** [comment]
I'm closing this as answered.

**Comment by StreetStrider** [comment]
@lpinca hello. It seemes I have the opposite problem. I've updated to `8.2.1` and I expected to receive buffer and isBinary, but instead I receive `MessageEvent` container with string data inside. I've tracked data inside ws library running and it is buffer originally, but it converted to string in [event-target](https://github.com/websockets/ws/blob/04c032c51b3219f76a3a48897027e38f4a9f5f50/lib/event-target.js#L193-L200).

I may be mixing something up, but this is the way I used this library in version 7.

I'm also not seeing this change:
> WebSocketServer.prototype.close() no longer closes existing connections

My tests should break in this two aspects, but they still passing in `ws@8` :thinking:

**Comment by lpinca** [comment]
If you are using `websocket.onmessage` or `websocket.addEventListener()` that is expected. The change only affect the `EventEmitter` API.

> I'm also not seeing this change:

I don't know, in your tests the connections are probably closed in some other way.

**Comment by StreetStrider** [comment]
@lpinca oh, I see. To be honest, this was unclear for me, but it clear now. I always thought that event signatures in documentation relates to any event API.
