### ISSUE TITLE
Delayed WebSocketServer.close() callback call

### ISSUE THREAD

**Issue by pongstylin** [websockets/ws#1945]
### 

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Description

I'm running a WebSocketServer and just implemented a feature where terminating the server with Ctrl+C will be caught and trigger a flush of all open/buffered changes to files.  The first step is to run WebSocketServer.close() with a callback then proceed with calling "close" on all connected sockets.  Once the callback is called, I proceed with flushing.  In my test case, there is only one connected socket at the time I close the server.  After calling "close()" on the socket, the browser shows the websocket connection as finished and the "close" event on the socket is called.  However, I might have to wait an extra 90 seconds before the WebSocketServer.close() callback is called.

In all my research, my only theory is that there is a kept-alive connection with the browser delaying the WebSocketServer callback call.  But, the issues I found were concerned with using this package as a client rather than a server.  So, I don't know how to terminate a kept-alive connection even if that was the problem.  I have tried calling "terminate" on a socket after the close event is called on it, but that didn't help.

My only recourse at this point is to not pass a callback to the server close event, and rather use the close events of all connected sockets as the indicator that I may safely proceed with flushing.  But if you have a better sense of the problem and solution, I'll go with that.

I hope the explanation is enough for you to diagnose the problem, but if you need a simple reproduction, I am willing to put in the effort.

### ws version

8.2.2

### Node.js Version

v14.17.4

### System

  System:
    OS: Windows 10 10.0.18363
    CPU: (4) x64 Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz
    Memory: 1.71 GB / 15.84 GB

### Expected result

I expect that the WebSocketServer close callback will be called immediately after all connected sockets' close events are triggered.  A kept-alive connection, if any, should not hinder this as it is irrelevant.

### Actual result

The WebSocketServer close callback may take up to 90 seconds to be called after the last connection has closed.

**Comment by lpinca** [comment]
Please write a simple test case that reproduces the issue. The callback should be called right after all WebSocket connections  emitted the `'close'` event.

**Comment by lpinca** [comment]
I can't reproduce with this test

```js
import WebSocket, { WebSocketServer } from 'ws';

const server = new WebSocketServer({ port: 8080 }, function () {
  console.log('Server listening on port 8080');

  const ws = new WebSocket('ws://localhost:8080');

  ws.on('close', console.log);
});

server.on('connection', function () {
  console.log('connection');
});

process.on('SIGINT', function () {
  server.close(function () {
    console.log('callback');
  });

  for (const ws of server.clients) {
    ws.close();
  }
});
```

**Comment by pongstylin** [comment]
Thank you for the quick response.  Since it was unexpected, I took a deeper look to figure out why I was so special.  As it turned out, I was initiating the close on the http server directly, not via WebSocketServer (I use the server for both express and ws, so I had easy access to it).

So, either this is expected behavior when closing the http server directly or you might consider supporting faster closes (if possible) when a developer takes that route.  Certainly, I was happy to close the WebSocketServer instead of the http server.  I am getting much faster shutdowns now.

**Comment by lpinca** [comment]
> So, either this is expected behavior when closing the http server directly or you might consider supporting faster closes (if possible) when a developer takes that route.

Yes, if you rely on the HTTP server close callback, then that is expected because there might be other open (non WebSocket) connections.

**Comment by pongstylin** [comment]
Fair enough.  Thanks.
