### ISSUE TITLE
WebSocket intermittently won't reach readyState 1

### ISSUE THREAD

**Issue by besworks** [websockets/ws#1946]
### 

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Description

I'm working on an project that consists of two separate node apps each running in a Docker container. One container hosts a WebSocketServer instance and the other connects to it via WebSocket. I ran into an issue where, after deploying a new build of the client, intermittently the socket would not connect right away to the already listening server. It would sometimes take ~1 minute to work (retrying the connection every 15 seconds). No error or close events were being emitted, but the client would not reach readyState 1 and thus the open event would not fire. On the server side, the connection event would fire as expected though and the eventual workaround I came up with was to just have the server send a message to the client from inside the connection event handler. Even though on the client  was in still readyState 0, the message would be received and this would trigger the open event to fire.

Now for the really strange part: This issue would only happen when the **server** app was running inside the Docker container. If I directly ran the node app it would not behave this way. The open/error/close events would always be fired as expected. To be sure it wasn't an async race condition or some other problem with my code I completely rewrote the websocket init sequence on both client and server starting from the examples in the repo here and still experienced this issue.

I can't be sure if this is a Docker networking issue, or something to do with the node:16-alpine image that I used as a base for the container, or if there is actually an issue in the ws package that is causing this behavior. My workaround gets the job done but it feels like a hack and by all reasoning should neither work or be necessary. Maybe somebody here can shed some light on what is going on in this situation... At the very least maybe this post will save somebody else from banging their head against a wall for hours like I did.

### ws version

8.2.2

### Node.js Version

16.6.1

### System

Docker Container Base:
  node:16-alpine@sha256:53ebfa5e6df1e458b47f677cb4f6fd3cf1d079083647dc40d182910a57b5a63d 
  https://github.com/nodejs/docker-node/blob/f52a9c90a41f916c213bfb6bad904928e9fdd3b3/16/alpine3.13/Dockerfile

Docker Host:
    OS: Linux 5.4 Ubuntu 20.04 LTS (Focal Fossa)
    CPU: (12) x64 Intel(R) Xeon(R) CPU X5660 @ 2.80GHz
    Memory: 4.74 GB / 31.35 GB
    Container: Yes
    Shell: 5.0.16 - /bin/bash

### Expected result

I would expect the WebSocket instance to reach readyState 1, 2, or 3 and have the corresponding events emitted.

### Actual result

The WebSocket instance does not change from readyState 0 and no events are emitted client-side.

### Attachments

Dockerfile:
```
FROM node:16-alpine@sha256:53ebfa5e6df1e458b47f677cb4f6fd3cf1d079083647dc40d182910a57b5a63d
RUN apk add dumb-init
ENV PORT 443
ENV NODE_ENV production
WORKDIR /app
COPY --chown=node:node . /app
RUN npm ci --only=production
USER node
CMD ["dumb-init", "node", "/app/index.js"]
```

**Comment by lpinca** [comment]
It does not seem to be a `ws` issue. The only thing I can think of is that the data sent here https://github.com/websockets/ws/blob/055949fd23b0d7f6a23ba9b9532b7834909df192/lib/websocket-server.js#L389 does not reach the client immediately. You can verify this by running this code:

```js
import { WebSocket } from 'ws';

const ws = new WebSocket(url);

ws._req.on('socket', function (socket) {
  socket.on('data', function (chunk) {
    process.stdout.write(chunk.toString());
  });
});
```

You should receive something like this

```
HTTP/1.1 101 Switching Protocols
Upgrade: websocket
Connection: Upgrade
Sec-WebSocket-Accept: Sya072MxqcwIFoTFktlSgSa8KV0=


```

right after the `'headers'` event is emitted on the server. Does the same happen if you use a different base image?

**Comment by besworks** [comment]
I set up a new test this morning using `node:16-alpine@latest` with the same results. I added the `socket`/`data` event handlers as you suggested, whenever the connection hangs the 'socket' event is emitted but the 'data' event is not. I also removed the auto-reconnect code and let it sit for quite some time, the `data` event never happens. I don't know enough about the handshake flow to troubleshoot this behavior... Is the client supposed to send a response to the 'socket' event that triggers the `data` event?

**Comment by lpinca** [comment]
> Is the client supposed to send a response to the `socket` event that triggers the `data` event?

No, I asked you add it to see if the server send response reaches the client. The answer seems to be negative. I don't know why. Are you doing something during the opening handshake like client authentication? Can you try with a non alpine based image? Can you post some code to reproduce the issue?

**Comment by besworks** [comment]
I tried using `node:16-buster` as the base image with the same result. Here's the test code that I'm using.

Server Code:
```
process.on('uncaughtException', err => {
  console.log('Unhandled Exception:', err);
});

const port = 443;

import * as fs from 'fs';
import * as https from 'https';
import { WebSocketServer } from 'ws';

const server = https.createServer({
  cert: fs.readFileSync('./var/ssl/cert.pem'),
  key: fs.readFileSync('./var/ssl/key.pem')
});

const wss = new WebSocketServer({ server });

wss.on('connection', (socket, req) => {
  console.log('WebSocket CONNECTION', req.socket.remoteAddress);
  socket.on('close', event => { console.log('WebSocket CLOSE', event.code); });
  socket.on('error', event => { console.log('WebSocket ERROR', event.error); });
  socket.on('pong',  event => { console.log('WebSocket PONG'); });
  socket.on('message', msg => { console.log('WebSocket MESSAGE', msg); });
});

server.on('listening', event => { console.log('Server LISTENING', port); });
server.listen(port);
```

Client Code:
```
import { WebSocket } from 'ws';

process.env.NODE_TLS_REJECT_UNAUTHORIZED = 0;

let ws = new WebSocket('wss://dev.dealerflow.net/wss-test/');
ws.addEventListener('unexpected-response', event => { console.log('WTF???', event); });
ws.addEventListener('error', event => { console.log('ERROR', event.error); });
ws.addEventListener('close', event => { console.log('CLOSE', event.code, event.reason); });
ws.addEventListener('open', event => { console.log('OPEN'); });
ws.addEventListener('message', event => { console.log('MESSAGE', event.data) });

ws._req.on('socket', socket => {
  console.log('socket started');
  socket.on('data', chunk => {
    process.stdout.write(chunk.toString());
  });
});
```

**Comment by lpinca** [comment]
I will try to build a Docker image with that server code tomorrow to see if I can reproduce.

FYI

```js
ws.addEventListener('unexpected-response', event => { console.log('WTF???', event); });
```

is a noop in `ws@8`.

**Comment by besworks** [comment]
Thanks a lot for looking into this. I appreciate your time. No rush on testing this, my workaround is doing the trick but I would definitely like to get to the bottom of the issue.

By the way, I should add that I'm running this behind a Reverse Proxy through Apache. This doesn't *seem* to be the cause though as running the same code outside of the docker container, but still through the proxy, works fine. Unless perhaps the problem lies between the proxy and Docker...

Apache Proxy Config:

```
SSLProxyEngine On
SSLProxyVerify None
SSLProxyCheckPeerCN Off
SSLProxyCheckPeerName Off
SSLProxyCheckPeerExpire Off
AllowEncodedSlashes NoDecode
ProxyRequests Off
ProxyPreserveHost On
ProxyErrorOverride On
ProxyPass /wss-test/ "https://localhost:4443/"
ProxyPassReverse /wss-test/ "https://localhost:4443/"
<Proxy *>
        Order allow,deny
        Allow from all
</Proxy>
RewriteEngine on
RewriteCond %{HTTP:Upgrade} websocket [NC]
RewriteCond %{HTTP:Connection} upgrade [NC]
RewriteRule .* "wss://localhost:4443/" [P,L]
```

Docker run command:
```
sudo docker run --restart unless-stopped -p 4443:443 --name wss-test -d wsst
```

**Comment by lpinca** [comment]
Too many variables. You should check with wireshark/tcpdump where the data sent by the server stops. The server sends an HTTP response like the one written in https://github.com/websockets/ws/issues/1946#issuecomment-919745920 right before the `'connection'` event is emitted.

**Comment by lpinca** [comment]
My guess is that the proxy does not flush the response and the additional message you send works a "kick" to make it send all the data at once. Anyway this does not explain why it works without Docker.

**Comment by besworks** [comment]
> My guess is that the proxy does not flush the response and the additional message you send works a "kick" to make it send all the data at once.

That seems like a reasonable hypothesis. The `open` event does consistently get logged before the additional message. As if it's been buffered somewhere and getting pushed through.

> Anyway this does not explain why it works without Docker.

Indeed... But either way it does not seem to be an issue with `ws`. So I think we can close this issue.

> You should check with wireshark/tcpdump where the data sent by the server stops.

Good idea, I will look into this when I have the time to learn more about tcpdump/ssldump. I will also try it without the proxy to see if it still happens. If I ever find out what's going on I will report it here in case it may help someone down the road.

Thanks for the troubleshooting tips.
