### ISSUE TITLE
unexpected-response response body

### ISSUE THREAD

**Issue by lemagicien00** [websockets/ws#1947]
### 

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Description

I use the verifyclient() function in my node server side and use callback function for refused the connection like this:

done(false, 401, " message description");

On the client side, I am unable to retrieve this "message description". Only statusCode and statusMessage.

client.on("unexpected-response", (req, res) => {
  console.error("unexpected-response:");
  console.error("statusCode: ", res.statusCode);
  console.error("statusMessage: ", res.statusMessage);
 // no res.body ????
});

I could see that this message was placed in the body of the response. But obviously it does not appear in the response at the level  of the  'unexpected-response' handler.

Can you help me?

### ws version

8.2.2

### Node.js Version

v14.17.3

### System

OS: Windows 10 10.0.19042
CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
Memory: 14.75 GB / 23.81 GB

**Comment by lpinca** [comment]
You have to read the response body yourself. See this test https://github.com/websockets/ws/blob/055949fd23b0d7f6a23ba9b9532b7834909df192/test/websocket.test.js#L652-L682  as an example.

**Comment by lemagicien00** [comment]
Thanks it works
