### ISSUE TITLE
on connection callback doesn't support async

### ISSUE THREAD

**Issue by CodeJuggernaut** [websockets/ws#1951]
### 

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Description

This does not work properly

```
wss.on('connection', async (ws, req) => {
   console.log('before timer');
   const value = await something();
   console.log('after timer');
})

const something = () => {
    setTimeout(async () => {
        console.log('timer');
    }, 1000)
}
```

### ws version

8.2.2

### Node.js Version

v16.9.0

### System

Linux

### Expected result

```
before timer
timer
after timer
```

### Actual result

```
before timer
after timer
timer
```

**Comment by lpinca** [comment]
This has nothing to do with ws.

```
$ cat invalid.js 
const foo = async () => {
  console.log('before timer');
  const value = await something();
  console.log('after timer');
};

const something = () => {
  setTimeout(async () => {
    console.log('timer');
  }, 1000);
};

foo();
```

```
$ node invalid.js 
before timer
after timer
timer
```

**Comment by lpinca** [comment]
FYI, the `something` function should return a promise that is resolved when the timer expires to make it work. You can use something like this

```js
const something = () => {
  return new Promise((resolve) => {
    setTimeout(() => {
      console.log('timer');
      resolve();
    }, 1000);
  });
};
```

or use the [Timers Promise API](https://nodejs.org/api/timers.html#timers_timers_promises_api).

**Comment by CodeJuggernaut** [comment]
Hey @lpinca, thanks for the fast reply! You're right, in my example I wrote it too quickly and forgot to return the promise. It does appear to work properly as async. For some reason, another portion of the code didn't seem to work async, but I will check deeper into that since now I know the callback does support async.
