### ISSUE TITLE
Callback of send() has undocumented error argument and also throw of send() is undocumented

### ISSUE THREAD

**Issue by nolimitdev** [websockets/ws#1953]
### 

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### First doc issue
Here https://github.com/websockets/ws/issues/1763 it was reported but user immediately closed it from another reason (misleading in his code) but user is right that error argument is not documented. I caught self going to remove error arguments from usage like 

```
this.conn.send("..."), (error) => {
    if (error)
        console.log('Failed to send message to server because of readyState ' + this.conn.readyState + ' (' + ['CONNECTING', 'OPEN', 'CLOSING', 'CLOSED'][this.conn.readyState] + ')', error);
});
```

because I asked myself from where I found that this argument exists? Because there is no mention in doc https://github.com/websockets/ws/blob/master/doc/ws.md#websocketsenddata-options-callback Please update doc because now it is misleading and users have to look into source code where I found that error argument exists. I was thinking that I was correctly used error argument in the past but maybe meanwhile it was removed in newer versions (and  wanted to refactor code in all projects and remove it), but it is not removed but just undocumented.

### Second doc issue
Secondly please also add to doc this behavior https://github.com/websockets/ws/releases/tag/7.0.0 of `WebSocket#{p{i,o}ng,send}()` because there is no mention about it. All doc examples without try/catch when calling send() are incorrect because user does not know it can throws in some situation - user does not know it from doc and does not know it from examples where try/catch is missing. I know you think that it is logical that message should not be send before connection is opened so you throw but consider scenario that connection is stored in `this.conn` and there is reconnect mechanism so sometimes during app lifetime many times happens that another independent part of app (via setTimeout/setInterval) calls send() during reconnecting... and nodejs app crashes because of undocumented throw. So please document it. When documented, user knows that must check connection status before send() OR use try/catch (neither is used in your examples).

Thanks for making doc better.

### ws version

any

### Node.js Version

any

**Comment by nolimitdev** [comment]
I thinks that doc update can avoid answering many issues like here
https://github.com/websockets/ws/issues/1551#issuecomment-483353431
https://github.com/websockets/ws/issues/1551
Maybe it would be great to remove throw and just call error callback. Because correct error handling is uselessly complicated

```
try {
    conn.send(error, () => {
        // handle readyState CLOSING or CLOSED
        if (error)
            ...
    });
}
// handle readyState CONNECTING
catch (error) {
    ...
}
```

**Comment by lpinca** [comment]
> **Maybe it would be great to remove throw and just call error callback. I think that different error handling for different readyState was not good idea. What do you think please @lpinca ? Because correct error handling is uselessly complicated...**

An error is thrown only if the ready state is `CONNECTING` and it was done on purpose for compatibility with the browser API. I also this it makes sense. Sending data the before the ready state is `OPEN` is a user error. No error is thrown on the server because you don't have a `CONNECTING` ready state there.

The `WebSocket#{p{i,o}ng,send}()` callback works like [`socket.write()`](https://nodejs.org/api/net.html#net_socket_write_data_encoding_callback) callback. It is called with an error if an error occurs when the data is written.

**Comment by nolimitdev** [comment]
Ok understand, throw leaves without change to becompat with browser, but **please update doc** as mention in this issue (missing mention about error callback and about throw) or should I prepare PR?

**Comment by nolimitdev** [comment]
Great, thanks for doc update!
