### ISSUE TITLE
a question about example

### ISSUE THREAD

**Issue by MadShura** [websockets/ws#1957]
### 

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Description

its about the **External HTTP/S server** example

const server = createServer({
  cert: readFileSync('/path/to/cert.pem'),
  key: readFileSync('/path/to/key.pem')
});

what is the '/path/to/' meaning?
i set the pem,key and this js file in same directory
here is my code:
const server = createServer({
  cert: readFileSync(path.resolve( "./mykey.key")),
  key: readFileSync('./mypem.pem')
});
and node throw an error 

thanks for your help! have a good day!

### ws version

7.4.5

### Node.js Version

14.15.4 type = module

### System

OS: Windows 10 10.0.19041
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 6.59 GB / 15.85 GB

### Expected result

all is ok

### Actual result

throw an error

### Attachments

fs.js:476
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, open './mykey.key'
    at Object.openSync (fs.js:476:3)
    at readFileSync (fs.js:377:35)
    at file:///C:/Users/AXL/Desktop/work/gaopudaimaApi/src/config/WebSocket.js:12:9
    at ModuleJob.run (internal/modules/esm/module_job.js:152:23)
    at async Loader.import (internal/modules/esm/loader.js:166:24)
    at async Object.loadESM (internal/process/esm_loader.js:68:5) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: './mykey.key'
}

**Comment by lpinca** [comment]
> what is the '/path/to/' meaning?

It means the absolute path to the key and certificate files. It does not have to be absolute, you can also use `path.resolve()` as in your example but make that the resolved path is correct.
