### ISSUE TITLE
The "open" event can't be used in my computer

### ISSUE THREAD

**Issue by Vanghua** [websockets/ws#1958]
### 

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Description

```
router.ws("/testSocket", function(ws, req, res) {
    ws.on("message", function(data) {
        console.log(data);
    })
    ws.on("open", function() {
        console.log("new connection!")
    })
});
```
ws.on("message", function(data){...}) can work well. But the "open" event I can't work :(

### ws version

5.0.2

### Node.js Version

14.17.4

### System

OS: Windows 10 10.0.19041
    CPU: (8) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
    Memory: 2.34 GB / 7.89 GB

### Expected result

new Connection!

### Actual result

none

### Attachments

none

**Comment by lpinca** [comment]
Sorry but this issue report is not actionable. Please write a clear description and specify how to reproduce the issue.

**Comment by lpinca** [comment]
I don't know how `express-ws` works but there is no `'open'` event on the server. See https://github.com/websockets/ws#simple-server, when the `'connection'` event is emitted the `WebSocket` ready state is `WebSocket.OPEN`.
