### ISSUE TITLE
WebSocket.Send Binary Messages Queue Up

### ISSUE THREAD

**Issue by tgraupmann** [websockets/ws#1959]
### 

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Description

I'm using ws to send realtime binary data like the server broadcast example.
https://github.com/websockets/ws#server-broadcast

It's a PubSub setup where I have broadcasters and watchers. Broadcasters send the binary data and watchers receive the subscribed binary data.

When the broadcaster stops sending binary data, I've noticed that clients keep receiving data for several minutes afterward.

My guess to what is happening is that `client.send()` might need a send timeout. I want to give it a cutoff, if the watcher can't receive the data within 20 seconds, just kill the message.

The expected result would be even if I stop a broadcast, watchers would only still be seeing messages for 20 seconds and then nothing.

Of course there may be a server option to set the send timeout to avoid this issue, but I didn't find it.

### ws version

^7.4.3

### Node.js Version

v15.9.0

### System

 System:
    OS: Linux 5.4 Ubuntu 18.04.5 LTS (Bionic Beaver)
    CPU: (2) x64 Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz
    Memory: 1.49 GB / 3.66 GB
    Container: Yes
    Shell: 4.4.20 - /bin/bash

### Expected result

A send timeout would be respected so that events taking longer than the timeout would be discarded.

### Actual result

The default send timeout must be infinite so I see binary messages arriving 20 minutes after I stopped sending.

**Comment by tgraupmann** [comment]
If I switched all the messages to send synchronously the throughput would drop dramatically.

However, I could use the callback, infrequently, to measure the delay and if it gets too long clear the send queue to let everything resynchronize.

That could work. Thanks for the tip!

**Comment by lpinca** [comment]
I'm closing this as answered.
