### ISSUE TITLE
secWebSocketProtocol parsing

### ISSUE THREAD

**Issue by lemagicien00** [websockets/ws#1965]
### 

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Description

I using the websocket client in react native, and if we do not specify a protocol

const client = new WebSocket(url, [], {
  headers: myHeaders,
});

, the package Websocket insert in the headers a null string like this:

'sec-websocket-protocol': ' ',

In node js, version 8.2.2 of "ws" package,  in the file "websocket-server.js line 250 the following test is true and
subprotocol.parse failed. because the string is empty. And connection upgrade his rejected.

    if (secWebSocketProtocol !== undefined) {
      try {
        protocols = subprotocol.parse(secWebSocketProtocol);
      } catch (err) {
        return abortHandshake(socket, 400);
      }
    }

I suggest replacing with the following test:

    if (secWebSocketProtocol) {
      try {
        protocols = subprotocol.parse(secWebSocketProtocol);
      } catch (err) {
        return abortHandshake(socket, 400);
      }
    }

### ws version

8.2.2

### Node.js Version

12.18.4

### System

  System:
    OS: Linux 4.19 Debian GNU/Linux 10 (buster) 10 (buster)
    CPU: (1) x64 Intel Core Processor (Haswell, no TSX)
    Memory: 195.75 MB / 1.90 GB
    Container: Yes
    Shell: 5.0.3 - /bin/bash

**Comment by lpinca** [comment]
I'm closing this as answered.
