### ISSUE TITLE
Packet loss, looking to increase writable.writableLength

### ISSUE THREAD

**Issue by NN-Binary** [websockets/ws#1969]
### 

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Description

Hi,

I'm trying to find in this crate/npm how to increase the buffer size on the receiver end, because I'm losing about 2% of the packets (they just don't show up in on('message')) but receive the next ones, so I'm guessing in my case it's not a TCP issue.

I would like to know how to increase the Buffer size in order to mitigate this issue?

### ws version

8.2.3 

### Node.js Version

v16.2.0

### System

    OS: Linux 5.10 Debian GNU/Linux 10 (buster) 10 (buster)
    CPU: (8) x64 Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
    Memory: 20.65 GB / 31.15 GB
    Container: Yes
    Shell: 5.0.3 - /bin/bash

**Comment by lpinca** [comment]
On the client you can use the `highWaterMark`, `readableHighWaterMark`, `writableHighWaterMark`.

```js
const WebSocket = require('ws');

const server = new WebSocket.Server({ port: 0 }, function () {
  const ws = new WebSocket(`ws://localhost:${server.address().port}`, {
    highWaterMark: 1024
  });

  ws.on('open', function() {
    console.log(ws._socket.readableHighWaterMark);
    ws.close();
    server.close();
  });
});
```

On the server you have to change the value of  `ws._socket._readableState.highWaterMark` manually.

Anyway this has nothing to do with packet loss and missing messages.

**Comment by NN-Binary** [comment]
Oh alright, I thought, what could be the curlpit? On about 1 million message of 50 bytes average (fired very fast), a few hundreds just "disappear"

**Comment by lpinca** [comment]
I don't know. Check whether the data actually reaches the receiving end.

```js
ws._socket.on('data', function (chunk) {
  console.log(chunk);
});
```

**Comment by RuralDependencies** [comment]
I'll check that. For UDP when we don't increase sender/rcv buffer size, even locally packets get dropped (increasing the size fixes it).

Thanks for the update

**Comment by lpinca** [comment]
I'm closing this. Feel free to continue the discussion nevertheless.
