### ISSUE TITLE
Problem with handleUpgrade

### ISSUE THREAD

**Issue by ZakiOro** [websockets/ws#1970]
### 

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Description

using handleUpgrade
getting error causing server to crash

socket.on('error', socketOnError);
           ^
TypeError: socket.on is not a function
    at WebSocketServer.handleUpgrade (/root/track/test/node_modules/ws/lib/websocket-server.js:228:12)

### ws version

8.2.3

### Node.js Version

v14.15.4

### System

Ubuntu 16.04.7 LTS VPS

### Expected result

emit connection request to socket

### Actual result

server crash after error

**Comment by lpinca** [comment]
It seems that the `socket` argument you are passing to `server.handleUpgrade()` is not an `EventEmitter`. Make sure that `socket` is an actual instance of `net.Socket` or `tls.Socket`.

**Comment by ZakiOro** [comment]
Thank you for your reply, yes you are right, client was being passed for socket. 

I will close the issue
