### ISSUE TITLE
Unable to create issue through github UI

### ISSUE THREAD

**Issue by m-rousse** [websockets/ws#1974]
It is impossible to create an issue from github's UI.

Steps to reproduce:
- Go to the [new issue](https://github.com/websockets/ws/issues/new/choose) page
- Choose `Bug report`
- Fill in anything (Only the title and the checkbox are mandatory IIUC)
- Get a 400 status code response

Expected output: a 200 page with the properly created issue.

Workaround: I created the issue directly through github API and edited it from the UI once it was created.

Note: I am not sure the root cause of the issue but maybe the custom form for issues is invalid?

**Comment by lpinca** [comment]
I can reproduce but I think this is a GitHub issue. The template was working (for example, see https://github.com/websockets/ws/issues/1971) and not changed have been made to it.

**Comment by lpinca** [comment]
Hmm the issue form works on the Node.js repository, so there must be something wrong with ws issue form. I'll investigate.
