### ISSUE TITLE
Unable to start connection to different domain WSS path

### ISSUE THREAD

**Issue by AgungBudi** [websockets/ws#1982]
### Is there an existing issue for this?

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Description

When the websocket server is different domain than the websocket client, then it will not able to start connection.
In my end both of WS Server, and App Server are in secure protocol, and i use WS Server client authentication (Server->Upgrade) just to validate if client is authorized. 
Perhaps if you could assist me how to achieve that? Basically I just want the WS Server (WSS) and App Server (HTTPS) working together. 
The weird thing is, if the app server and ws server are in the same domain, then there is no issue.

**Comment by lpinca** [comment]
See https://github.com/websockets/ws#external-https-server.

**Comment by lpinca** [comment]
> The weird thing is, if the app server and ws server are in the same domain, then there is no issue.

The WebSocket server can also listen for connections in a different domain but the WebSocket clients should obviously connect to that domain.

**Comment by AgungBudi** [comment]
> See https://github.com/websockets/ws#external-https-server.

Actually my code is quite the same like your suggested. The difference is i use option noServer : true, as i want the Server.Upgrade is triggered at the first connection. I need this because i use it as the authorization. My WebSocket client, is actually pointing to correct WSS domain. I am not really sure which part i need to adjust again.

Hopefully If anyone has the same experience, and let me know the possible solution?

**Comment by AgungBudi** [comment]
Just want to give an update, it turns out that the issue is not in the ws component, but more into node session options and some cors issues. I think we can close this, and my apology for any hussle :)
