### ISSUE TITLE
feature request: allow user-provided unique id for a websocket client

### ISSUE THREAD

**Issue by vobu** [websockets/ws#1984]
### Is there an existing issue for this?

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Description

it would be excellent to have an api (client-side) to uniquely identify a client.
```js
// ws-server has { clientTracking:true } set
const ws = new WebSocket('ws://www.host.com/path', {id: "my-specific-id"})
```

this would allow subsequent messages from a ws-server to only that specific client.
```js
    // id = "my-specific-id" 
    wss.clients.forEach(function each(client) {
      if (client.id === id && client.readyState === WebSocket.OPEN) {
        client.send(data, { binary: isBinary });
      }
    });
```

(found existing issue https://github.com/websockets/ws/issues/1772 which is not entirely relevant though)

### ws version

8.4.0 ? :)

### Node.js Version

14+

### Expected result

only a subset of all connected clients receive a message

### Actual result

all connected clients receive a message (except the sending one)

**Comment by vobu** [comment]
ps: I'd be happy to provide an initial PR and start work on this

**Comment by lpinca** [comment]
Thanks but this is outside of the scope of the project. See https://github.com/websockets/ws/issues/1749 https://github.com/websockets/ws/issues/1419 https://github.com/websockets/ws/issues/1363 https://github.com/websockets/ws/issues/1308 https://github.com/websockets/ws/issues/859

**Comment by sdrsdr** [comment]
@vobu  client id is best to be assigned on the server after a validation/collision checking as clients might lie about their id or if chosen (pseudo)randomly from client it might lead to collision in the server

**Comment by vobu** [comment]
> Thanks but this is outside of the scope of the project. You can use a query parameter as shown here [#859 (comment)](https://github.com/websockets/ws/issues/859#issuecomment-253197752).

ahhh, thanks for the hint.!totally overlooked the possibility of simply assigning an additional property (such as `id`) to the `ws` client instance
→ closing this

**Comment by trasherdk** [comment]
Expanding on @sdrsdr point. Every connection to a server should be considered hostile until proven friendly :smiley:
