### ISSUE TITLE
uncaughtException: RangeError: Invalid WebSocket frame: invalid status code

### ISSUE THREAD

**Issue by DiamondeX** [websockets/ws#1985]
### Is there an existing issue for this?

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Description

The bug is described thorouly here: https://github.com/vercel/next.js/issues/32573

Nevertheless I'm not sure the problem originates from Next.JS or its dependencies. I've decided to mention it here, because I'm getting an error as an uncaughtException, although both websocket and websocketserver have their error handlers set.

### ws version

8.3.0

### Node.js Version

14.17.0

### System

System:
    OS: Linux 5.4 Debian GNU/Linux 10 (buster) 10 (buster)
    CPU: (10) x64 AMD EPYC 7702P 64-Core Processor
    Memory: 47.50 GB / 53.71 GB
    Container: Yes
    Shell: 5.0.3 - /bin/bash

### Expected result

error should be caught by websocket's error handler

### Actual result

error is thrown as uncaughtException

**Comment by lpinca** [comment]
Make sure that the `'error'` listener is not removed before the `'close'` event is emitted.

**Comment by lpinca** [comment]
Here is an example to reproduce the error:

```
const WebSocket = require('ws');

const wss = new WebSocket.Server({ port: 0 }, function () {
  const ws = new WebSocket(`ws://localhost:${wss.address().port}`);

  ws.on('open', function () {
    ws._socket.write(Buffer.from('888200000000d3cc', 'hex'));
  });
});

wss.on('connection', function (ws) {
  ws.on('error', console.error);
});
```

**Comment by DiamondeX** [comment]
> Make sure that the `'error'` listener is not removed before the `'close'` event is emitted.

Again, here is a link to the quite simple code that reproduces the error: https://github.com/vercel/next.js/issues/32573#issue-1082203364
As you may have noticed, there is no place in the server's code where the `'error'` or any other listener is removed. It's never removed. The same is with client's code, although that doesn't matter.
And this happens only if you use Chrome to navigate to the code's main page.

**Comment by lpinca** [comment]
Run the above example yourself.

**Comment by lpinca** [comment]
Give me minimal test case to reproduce the issue without external dependencies, otherwise it's hard to debug.

**Comment by DiamondeX** [comment]
Your above example code, converted to Typescript like this:
```ts
import WebSocket from 'ws';

const wss = new WebSocket.Server({ port: 0 }, function () {
  // @ts-ignore
  const ws = new WebSocket(`ws://localhost:${wss.address().port}`);

  ws.on('open', function () {
  // @ts-ignore
    ws._socket.write(Buffer.from('888200000000d3cc', 'hex'));
  });
});

wss.on('connection', function (ws) {
  ws.on('error', console.error);
});
```

gives this:
```
RangeError: Invalid WebSocket frame: invalid status code 54220
    at Receiver.controlMessage (/home/develop/fde-v3/next-ts-custom-serv/node_modules/ws/lib/receiver.js:555:18)
    at Receiver.getData (/home/develop/fde-v3/next-ts-custom-serv/node_modules/ws/lib/receiver.js:423:42)
    at Receiver.startLoop (/home/develop/fde-v3/next-ts-custom-serv/node_modules/ws/lib/receiver.js:148:22)
    at Receiver._write (/home/develop/fde-v3/next-ts-custom-serv/node_modules/ws/lib/receiver.js:83:10)
    at writeOrBuffer (internal/streams/writable.js:358:12)
    at Receiver.Writable.write (internal/streams/writable.js:303:10)
    at Socket.socketOnData (/home/develop/fde-v3/next-ts-custom-serv/node_modules/ws/lib/websocket.js:1187:35)
    at Socket.emit (events.js:376:20)
    at Socket.emit (domain.js:470:12)
    at addChunk (internal/streams/readable.js:309:12) {
  code: 'WS_ERR_INVALID_CLOSE_CODE',
  [Symbol(status-code)]: 1002
}
```
But it's without even navigating to the main page.

**Comment by lpinca** [comment]
Yes, that is expected. The error is handled and logged via `console.error()`.

**Comment by DiamondeX** [comment]
Then, I think, they (in next.js's dev-server project) apparently do remove the `'error'` listener in some case before the `'close'` event is emitted.
I close this issue for now. I think, guys from next.js will open another issue, if they need

**Comment by DiamondeX** [comment]
Btw, thanks for help)
