### ISSUE TITLE
Replace bufferUtil.mask with a SIMD + WASM version

### ISSUE THREAD

**Issue by ronag** [websockets/ws#1987]
Could provide a performance boost. We some significant time spent in this function.

We already have some experience with WASM + SIMD in undici which we could re-use here.

**Comment by sdrsdr** [comment]
SIMD is great but why waste time in setup with WASM and not do a plain old C module? Given the simple task it should be 100% portable

**Comment by lpinca** [comment]
See https://github.com/websockets/bufferutil/blob/master/src/bufferutil.c

**Comment by ronag** [comment]
AVX2 would do 32 bytes at a time.

**Comment by lpinca** [comment]
Feel free to experiment with it.

**Comment by ronag** [comment]
Ill open a PR when I get to it.
