### ISSUE TITLE
Webscoket with Cookie

### ISSUE THREAD

**Issue by 5paisa** [websockets/ws#1992]
### Is there an existing issue for this?

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Description

I have WebSocket URL Which contain2 parameter  and i also want to pass .aspxauth in cookie while WebSocket connection. but I am not able to pass the cookie there .can you help how I create WebSocket connection with cookie?

Ex:

URl=wss://RandomUrl.com/Feeds/api/chat?Value1=${token}|${code}`
var headers={
  "set-cookie":cookie
  }

 var client = new W3CWebSocket(URL,headers=headers);
 

### ws version

6.14.8

### Node.js Version

v14.15.0

**Comment by lpinca** [comment]
```js
const ws = new WebSocket(url, {
  headers: {
    Cookie: 'foo=bar'
  }
});
```

**Comment by 5paisa** [comment]
Thanks this really works for me. can you help me if i want onmessage function message pass by user according to their preference from outside my sdk is it possible in node js
