### ISSUE TITLE
echo.websocket.org demo not working

### ISSUE THREAD

**Issue by sepych** [websockets/ws#1993]
### Is there an existing issue for this?

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Description

Hi,
I've tried echo demo and it gets stuck at the connection phase and then timeouts
`
import WebSocket from 'ws';

const ws = new WebSocket('wss://echo.websocket.org/', {
  origin: 'https://websocket.org'
});

ws.on('open', function open() {
  console.log('connected');
  ws.send(Date.now());
});

ws.on('close', function close() {
  console.log('disconnected');
});

ws.on('message', function message(data) {
  console.log(`Roundtrip time: ${Date.now() - data} ms`);

  setTimeout(function timeout() {
    ws.send(Date.now());
  }, 500);
});
` 
Tried the same example at two different machines, getting the same result.

### ws version

8.4.0

### Node.js Version

v17.3.0

### System

System:
    OS: Linux 5.11 Ubuntu 21.04 (Hirsute Hippo)
    CPU: (4) x64 Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz
    Memory: 348.60 MB / 7.67 GB
    Container: Yes
    Shell: 5.1.4 - /bin/bash

**Comment by sepych** [comment]
Just realized that it is websocket.org is no longer available

**Comment by lpinca** [comment]
FYI, I've updated the example replacing `echo.websocket.org` with `websocket-echo.com`. `websocket-echo.com` uses https://github.com/websockets/websocket-echo-server under the hood.
