### ISSUE TITLE
The WsServer doesn`t close if there is at least one active connection

### ISSUE THREAD

**Issue by artemtrush** [websockets/ws#1995]
### Is there an existing issue for this?

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Description

Can't close connection from the server side.
Callback is triggered only after closing active connection from the client side.

Try to run the following code:
(It works correctly on ws@7 version)

```
const WebSocket = require('ws');

async function main() {
    console.log('START SCRIPT');

    // Prepare client and server
    const port = 1234;
    const url = `ws://localhost:${port}`;

    const wsServer = new WebSocket.Server({ port });

    wsServer.on('connection', () => {
        console.log('CLIENT CONNECTED');
    });

    const wsClient = new WebSocket(url);

    await sleep(1000);

    // Closing doesnt work
    console.log('TRY TO CLOSE SERVER WITH ACTIVE CONNECTION');

    wsServer.close(() => {
        console.log('SERVER CLOSED');
    });

    await sleep(5000);

    // Closing works after dropping connection from client side
    console.log('DROP ACTIVE CONNECTION');

    wsClient.close();

    await sleep(1000);

    console.log('END SCRIPT');
}

async function sleep(delayMs) {
    return new Promise(resolve => setTimeout(resolve, delayMs));
}

main().catch(error => console.log(error));
```

### ws version

8.4.0

### Node.js Version

v16.13.1

### System

  System:
    OS: Linux 5.11 Ubuntu 20.04.3 LTS (Focal Fossa)
    CPU: (12) x64 11th Gen Intel(R) Core(TM) i5-11400F @ 2.60GHz
    Memory: 8.01 GB / 15.50 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh

### Expected result

START SCRIPT
CLIENT CONNECTED
TRY TO CLOSE SERVER WITH ACTIVE CONNECTION
SERVER CLOSED
DROP ACTIVE CONNECTION
END SCRIPT

### Actual result

START SCRIPT
CLIENT CONNECTED
TRY TO CLOSE SERVER WITH ACTIVE CONNECTION
DROP ACTIVE CONNECTION
SERVER CLOSED
END SCRIPT

**Comment by lpinca** [comment]
See https://github.com/websockets/ws/releases/tag/8.0.0

> - `WebSocketServer.prototype.close()` no longer closes existing connections
>  (df7de574).
>
>  Existing code can be migrated by closing the connections manually.
>
>  ```js
>  websocketServer.close();
>  for (const ws of websocketServer.clients) {
>    ws.terminate();
>  }
>  ```

**Comment by artemtrush** [comment]
Got it, thanks. Issue closed
