### ISSUE TITLE
with NextJs: ModuleNotFoundError: Module not found: Error: Can't resolve 'fs' in '.../node-gyp-build'

### ISSUE THREAD

**Issue by sergiuchuckmisha** [websockets/ws#2001]
### Is there an existing issue for this?

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Description

Trying to use [ws](https://www.npmjs.com/package/ws) package in NextJs web-application

and when building my application get 

ModuleNotFoundError: Module not found: Error: Can't resolve 'fs' in '.../node-gyp-build'

Point is that NextJs with Server Side Rendering there are no server options like 'fs'

Looks like that this problem is related to these [performance options](https://www.npmjs.com/package/ws#opt-in-for-performance):
 - bufferutil
 - utf-8-validate

They are marked in `.../node_modules/ws/package.json` as 

`  "peerDependencies": {
    "bufferutil": "^4.0.1",
    "utf-8-validate": "^5.0.2"
  },
  "peerDependenciesMeta": {
    "bufferutil": {
      "optional": true
    },
    "utf-8-validate": {
      "optional": true
    }
  },`

but build still complains about their dependencies

How is it possible to disable these dependencies?

### ws version

ws@7.4.5

### Node.js Version

v12.20.0

### System

OS: Linux 5.4 Ubuntu 18.04.5 LTS (Bionic Beaver)

### Expected result

absence of 

`ModuleNotFoundError: Module not found: Error: Can't resolve 'fs' in '.../node_modules/node-gyp-build'`

### Actual result

`ModuleNotFoundError: Module not found: Error: Can't resolve 'fs' in '.../node_modules/node-gyp-build'`

**Comment by lpinca** [comment]
`bufferutil` and `utf-8-validate` are optional. Installing them is not required. This seems a Next.js issue.

**Comment by shohamc1** [comment]
This error seems to be due to Webpack 5 not including core Node.JS polyfills by default. I tried adding in the polyfills manually following [this StackOverflow post](https://stackoverflow.com/questions/69602687/webpack-v5-polyfill-error-with-gatsby-site), however I was unable to solve the issue as I got stopped by a `class heritage Writable is not an object or null` error for the `buffer` polyfill.

My `gatsby-node.js` looks like this (there may be some redundant polyfills):
```
exports.onCreateWebpackConfig = ({
  stage,
  rules,
  loaders,
  plugins,
  actions,
}) => {
  actions.setWebpackConfig({
    plugins: [
      plugins.provide({
        Buffer: ["buffer", "Buffer"],
      }),
    ],
    resolve: {
      alias: {
        zlib: require.resolve("browserify-zlib"),
        assert: require.resolve("assert"),
        util: require.resolve("util"),
        os: require.resolve("os-browserify"),
        path: require.resolve("path-browserify"),
        buffer: require.resolve("buffer/"),
      },
    },
    externals: ["tls", "net", "crypto", "http", "https", "fs"],
  });
};
```

Not too sure on how to fix the issue past this.

**Comment by lpinca** [comment]
If you are targeting the browser, don't use `ws`. Use the native `WebSocket` object.

**Comment by sergiuchuckmisha** [comment]
> > How is it possible to disable these dependencies?
> 
> Do not install them. `bufferutil` and `utf-8-validate` are optional. This seems a Next.js issue.

I didn't install them. Did just `npm install ws`

**Comment by sergiuchuckmisha** [comment]
> If you are targeting the browser, do not use `ws`. Use the native `WebSocket` object.
> 
> > This module does not work in the browser. The client in the docs is a reference to a back end with the role of a client in the WebSocket communication. Browser clients must use the native `WebSocket` object. To make the same code work seamlessly on Node.js and the browser, you can use one of the many wrappers available on npm, like isomorphic-ws.

Yes, [isomorphic-ws](https://github.com/heineiuo/isomorphic-ws) does work with NextJs
