### ISSUE TITLE
Does permessage-deflate extension bug affect 6.2.2

### ISSUE THREAD

**Issue by jadell** [websockets/ws#2002]
### Is there an existing issue for this?

- [x] I've searched for any related issues and avoided creating a duplicate issue.

### Description

Is the permessage-deflate extension bug that was fixed in [7.4.4](https://github.com/websockets/ws/releases/tag/7.4.4) also present in 6.2.2?

I realize the 6.x branch is older (and unmaintained?) but ws is a sub-dependency of a library we cannot upgrade due to runtime environment reasons. The static analysis tool we are forced to use is flagging 6.2.2 as susceptible to this bug, though I cannot find any mention of it outside of the tool's reporting.

If the bug is still present, would it be possible to get the fix backported to the 6.x line?

### ws version

6.2.2

**Comment by lpinca** [comment]
> Is the permessage-deflate extension bug that was fixed in 7.4.4 also present in 6.2.2

Version 6.2.2 is not affected. The bug fixed in version 7.4.4 was introduced in version 7.4.3 with https://github.com/websockets/ws/pull/1840.

**Comment by jadell** [comment]
Thank you!
