### ISSUE TITLE
v7 vs v8 WebSocket constructor

### ISSUE THREAD

**Issue by ea167** [websockets/ws#2003]
### Is there an existing issue for this?

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Description

Hello,
I'm struggling on v7 / v8 breaking changes, I do apologize in advance.

In v7, this simple client websocket was working fine
`new WebSocket( "wss://my.server.com/ws/publish/ID-10005100-main-M100001109604_Y5FbuK6dJ?token=xYzAbC&vCount=2" )`

while in v8 it fails with 
`SyntaxError: An invalid or duplicated subprotocol was specified`

Am I missing something, or is there a problem with the URL / query part of the URL in v8?

### ws version

8.4.0

### Node.js Version

16.13.2

### System

Ubuntu 20.04

**Comment by lpinca** [comment]
The error is thrown when the `suprotocols` argument is invalid:

```
const ws = new WebSocket(url, subprotocols);
```

Make sure subprotocol names are valid and not duplicated.

**Comment by ea167** [comment]
Thank you for your explanation Luigi @lpinca!

For the sake of this project, please allow me to gently push back: why isn't there a good default? Why do we need to specify these subprotocols to create a client WebSocket?

In a web browser, we don't. In v7, we don't either: it just works. Why do we have to painfully dig into these in v8?

Honestly this seems like too much arcane detail. As a developer, I just don't want to manage these subprotocols.

I hope the feedback helps! Thank you again for the great lib!

**Comment by lpinca** [comment]
Yes browsers coerce that `null` to a string and send `'null'` for the `Sec-WebSocket-Protocol` header. `ws` is stricter and throws an error because `null` is not a string.

**Comment by ea167** [comment]
Thank you for the great lib and great support Luigi @lpinca!
