### ISSUE TITLE
Cannot work with nativescript angular

### ISSUE THREAD

**Issue by gayatri-kadam** [websockets/ws#2005]
### Is there an existing issue for this?

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Description

I am trying to use ws for nativescript angular android project, while building the app it gives me dependencies can't be resolved errors.

Tried importing it in 3 ways, none worked.
1: const WebSocket = require('ws');
2: require('ws');
3: import WebSocket from 'ws';

### ws version

8.4.2

### Node.js Version

v12.13.1

### nativescript CLI Version

8.1.5

### @nativescript/core Version
8.1.5

### System

System:
    OS: Windows 7 6.1.7601
    CPU: (4) x64 Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz
    Memory: 2.27 GB / 7.65 GB

### Expected result

ws websocket working well for nativescript.

### Actual result

Build fails with following error.

### Attachments

WARNING in ../node_modules/ws/lib/buffer-util.js
Module not found: Error: Can't resolve 'bufferutil' in 'C:\Users\gkadam\Documents\my_project\node_modules\ws\lib'
 @ ../node_modules/ws/lib/buffer-util.js
 @ ../node_modules/ws/lib/sender.js
 @ ../node_modules/ws/index.js
 @ ./app/core/services/web-socket.service.ts
 @ ./app/core/core.module.ts
 @ ./app/app.module.ts
 @ ./main.ts

WARNING in ../node_modules/ws/lib/validation.js
Module not found: Error: Can't resolve 'utf-8-validate' in 'C:\Users\gkadam\Documents\my_project\node_modules\ws\lib'
 @ ../node_modules/ws/lib/validation.js
 @ ../node_modules/ws/lib/sender.js
 @ ../node_modules/ws/index.js
 @ ./app/core/services/web-socket.service.ts
 @ ./app/core/core.module.ts
 @ ./app/app.module.ts
 @ ./main.ts

ERROR in ../node_modules/ws/lib/sender.js
Module not found: Error: Can't resolve 'net' in 'C:\Users\gkadam\Documents\my_project\node_modules\ws\lib'
 @ ../node_modules/ws/lib/sender.js 5:12-26
 @ ../node_modules/ws/index.js
 @ ./app/core/services/web-socket.service.ts
 @ ./app/core/core.module.ts
 @ ./app/app.module.ts
 @ ./main.ts

ERROR in ../node_modules/ws/lib/websocket.js
Module not found: Error: Can't resolve 'net' in 'C:\Users\gkadam\Documents\my_project\node_modules\ws\lib'
 @ ../node_modules/ws/lib/websocket.js 8:12-26
 @ ../node_modules/ws/index.js
 @ ./app/core/services/web-socket.service.ts
 @ ./app/core/core.module.ts
 @ ./app/app.module.ts
 @ ./main.ts

ERROR in ../node_modules/ws/lib/websocket-server.js
Module not found: Error: Can't resolve 'net' in 'C:\Users\gkadam\Documents\my_project\node_modules\ws\lib'
 @ ../node_modules/ws/lib/websocket-server.js 8:12-26
 @ ../node_modules/ws/index.js
 @ ./app/core/services/web-socket.service.ts
 @ ./app/core/core.module.ts
 @ ./app/app.module.ts
 @ ./main.ts

ERROR in ../node_modules/ws/lib/sender.js
Module not found: Error: Can't resolve 'tls' in 'C:\Users\gkadam\Documents\my_project\node_modules\ws\lib'
 @ ../node_modules/ws/lib/sender.js 6:12-26
 @ ../node_modules/ws/index.js
 @ ./app/core/services/web-socket.service.ts
 @ ./app/core/core.module.ts
 @ ./app/app.module.ts
 @ ./main.ts

ERROR in ../node_modules/ws/lib/websocket.js
Module not found: Error: Can't resolve 'tls' in 'C:\Users\gkadam\Documents\my_project\node_modules\ws\lib'
 @ ../node_modules/ws/lib/websocket.js 9:12-26
 @ ../node_modules/ws/index.js
 @ ./app/core/services/web-socket.service.ts
 @ ./app/core/core.module.ts
 @ ./app/app.module.ts
 @ ./main.ts

ERROR in ../node_modules/ws/lib/websocket-server.js
Module not found: Error: Can't resolve 'tls' in 'C:\Users\gkadam\Documents\my_project\node_modules\ws\lib'
 @ ../node_modules/ws/lib/websocket-server.js 9:12-26
 @ ../node_modules/ws/index.js
 @ ./app/core/services/web-socket.service.ts
 @ ./app/core/core.module.ts
 @ ./app/app.module.ts
 @ ./main.ts

**Comment by lpinca** [comment]
See https://github.com/websockets/ws#ws-a-nodejs-websocket-library

>**Note**: This module does not work in the browser. The client in the docs is a reference to a back end with the role of a client in the WebSocket communication. Browser clients must use the native [`WebSocket`](https://developer.mozilla.org/en-US/docs/Web/API/WebSocket) object.

> To make the same code work seamlessly on Node.js and the browser, you can use one of the many wrappers available on npm, like [isomorphic-ws](https://github.com/heineiuo/isomorphic-ws).

**Comment by gayatri-kadam** [comment]
@lpinca Thank you for the prompt response. I am building a "truly native android application" using the Nativescript-Angular framework and I don't need ws to work on a browser anyway. Is it possible to use "ws" for nativescript-angular framework for an android app? Or do you have any other suggestions apart from "nativescript-websockets"?

**Comment by lpinca** [comment]
I don't know. The problem I see is that it fails to use even Node.js core modules like `net` and `tls` and without them `ws` cannot work.
