### ISSUE TITLE
How to use ws.send in a loop

### ISSUE THREAD

**Issue by philippmueler** [websockets/ws#2006]
### Is there an existing issue for this?

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Description

I have this for loop:

`const WebSoket = require("ws");

const ws = new WebSoket("ws://localhost:2002");

for (let index = 0; index < 10; index++) {
    ws.on("open", () => {
        ws.send(JSON.stringify("Hallo"));
    });
    setTimeout(() => {}, 5000);
}`

but js sends the data just one time to my server and quietly losses the data. 
no error message no nothing. i dont know what to do. 
i tried every arrangement of his code

### ws version

8.4.2

### Node.js Version

v10.19.0

### System

 System:
    OS: Linux 5.13 Ubuntu 20.04.3 LTS (Focal Fossa)
    CPU: (4) x64 Intel(R) Core(TM) i5-4210M CPU @ 2.60GHz
    Memory: 673.53 MB / 7.65 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash

### Expected result

every time i loop though the function it should send the data

### Actual result

data gets send only once

**Comment by acceleratorlastorder** [comment]
Hi.
Running one server under nodeJS  and one client on chrome i do manage to send 10 times a message

here's my server side code:
```
import { WebSocketServer } from 'ws';

const wss = new WebSocketServer({ port: 2002 });

wss.on('connection', function connection(ws) {
    ws.on('message', function message(data) {
        console.log('received: %s', data);
    });

    ws.send('message recieved');
});
```

and here the client
```
<!DOCTYPE html>
<html lang="en">
<head>
    <title>test WS</title>
</head>

<body>
    <script>
        const ws = new WebSocket("ws://localhost:2002");
        ws.onmessage = function (event) {
            console.log("message received event: ", event.data);
            sendMessage();
        };

        function sendMessage(){
            for (let index = 10; index-- > 0;) {
                ws.send(JSON.stringify("yoooo:" + (index + 1)));
            }
        }

    </script>
</body>

</html>
```

I hope that sample can help.

**Comment by lpinca** [comment]
This is not a bug, please use SO for questions like this. Anyway the following will send 10 messages to the server.

```js
const WebSocket = require('ws');

const ws = new WebSocket('ws://localhost:2002');

ws.on('open', function () {
  const str = JSON.stringify("Hallo");

  for (let index = 0; index < 10; index++) {
    ws.send(str);
  }
});
```

**Comment by philippmueler** [comment]
@lpinca chill bro.

but yes the error was with me. my python server was missing a while loop. i thought it was a bug in ws because i didn't have an error message and didn't find anything about it. tanks at @acceleratorlastorder for the quick reply. helped me to realize the origin of the error
