### ISSUE TITLE
Add an "allowedOrigins" option to the server constructor, or document how to filter clients by origin

### ISSUE THREAD

**Issue by misterfresh** [websockets/ws#2008]
### Is there an existing issue for this?

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Description

As websockets don't implement same origin policy, many tutorials advise to check the origin header of the handshake request and only allow the connection for allowed origins, to avoid CSRF attacks. 

I've looked at the documentation and searched in the existing issues, but haven't found a clear way to do it. The easiest way would be to be able to set a list of allowed origins when instantiating the websocket server. Short of that, should it be done in the verifyClient option ? It is said that its usage is discouraged. 
I have this so far:
```javascript
const myAllowedOrigins = ['https://www.example.com']
const server = http.createServer();
const wss = new WebSocketServer({server})
server.on('upgrade', function (request, socket, head) {
    if(!myAllowedOrigins.includes(request.headers.origin)) {
        socket.write('HTTP/1.1 401 Unauthorized\r\n\r\n');
        socket.destroy();
    } else {
        wss.handleUpgrade(request, socket, head, function (ws) {
            wss.emit('connection', ws, request);
        });
    }
});
server.listen(3000)
```
With above code I get the error : Error: server.handleUpgrade() was called more than once with the same socket, possibly due to a misconfiguration. Also I dont know if it is possible to listen to the upgrade event without manually creating the http server such as:
```js
const wss = new WebSocketServer({port: 9000})
wss.on('upgrade', (req) => {
    // check origin
})
```

### Node.js Version

16.13

**Comment by lpinca** [comment]
See https://github.com/websockets/ws#client-authentication. Filtering by `Origin` header is the same.

In your example there is a small error:

```js
const wss = new WebSocketServer({server})
```

It should be 

```js
const wss = WebSocketServer({ noServer: true })
```

if you handle the `'upgrade'` event directly.

**Comment by misterfresh** [comment]
what if I just did:
```js
const allowedOrigin = 'https://example.com'
const wss = new WebSocketServer({ port: 3000 })
wss.on('connection', (connection, req) => {
    const origin = req.headers.origin
    if(origin !== allowedOrigin) {
        return connection.close(1015, 'Invalid origin')
    }
})
```
would that be ok ? I'm not sure I want to manually handle the upgrade event.
it would be good if we could just do:
```js
const wss = new WebSocketServer({ port: 3000, allowedOrigins: ['https://example.com'] })
```
if really it is a serious risk to not limit the access of the endpoint to your app's origin. maybe this risk is overblown?

**Comment by lpinca** [comment]
Yes, you can do that. The difference is that the handshake completes in that case so the `'open'` event is emitted on the client.

> maybe this risk is overblown?

A non-browser client can specify any origin so yes allowing a specific origin is only relevant for browsers.

**Comment by misterfresh** [comment]
Ok thanks for your quick response. I will handle it in the connection event then, so as to not have to maintain my own logic for upgrading the connection. I will use browser cookies for authentication so the origin filter will be useful.

**Comment by lpinca** [comment]
There is also https://github.com/websockets/ws/blob/master/doc/ws.md#servershouldhandlerequest

```js
wss.shouldHandle = (request => request.header.origin === 'https://example.com');
```

This will abort the handshake and sends a 400 response if the origin does not match.
