### ISSUE TITLE
ws.send not returning the socket.write return value (backpressure)

### ISSUE THREAD

**Issue by hcldan** [websockets/ws#2009]
### Is there an existing issue for this?

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Description

I am trying to determine when the underlying websocket is buffering at the kernel, but the return value if the inner socket is not returned.

https://github.com/websockets/ws/blob/e1ddacce06d302884e674f50c12cb376e000c6ea/lib/websocket.js#L467
https://github.com/websockets/ws/blob/e1ddacce06d302884e674f50c12cb376e000c6ea/lib/sender.js#L466

I need this to implement backpressure from the data I am trying to write.

### Expected result

ws.write(<data>) === false
when the socket's high water mark is exceeded.

**Comment by hcldan** [comment]
I think we'll also need a drain event on the websocket

**Comment by hcldan** [comment]
It looks like there's already backpressure for getting messages from the ws, but not for sending

**Comment by lpinca** [comment]
This is expected. You can use the `websocket.send()` callback or the [streaming API](https://github.com/websockets/ws#use-the-nodejs-streams-api).

**Comment by hcldan** [comment]
@lpinca That is unfortunate, I really liked the ws ability to control part/whole messages.
will the streaming api treat each call to push as 1 binary message frame?

**Comment by hcldan** [comment]
would you be amenable to a PR that made a new send() option that would return the socket write call on "fin" sends?

**Comment by lpinca** [comment]
> will the streaming api treat each call to push as 1 binary message frame?

Every `webSocketStream.write()` is a message. You can write both binary and text messages if you set the [`decodeStrings`](https://nodejs.org/api/stream.html#new-streamwritableoptions) option to `false`.

> would you be amenable to a PR that made a new send() option that would return the socket write call on "fin" sends?

I'm not sure I understand. `ws.send()` does not return the value of `socket.write()` because the `socket.write()` call is not synchronous if the message is compressed.

**Comment by hcldan** [comment]
socket.write will return false if the os tcp buffer is over the highwater mark.

I want the false to bubble up, and then the 'drain' event on the websocket so that I can implement backpressure.

As you have it right now, I'm pretty sure that if you're blasting messages into ws.send(), you could overwhelm the tcp buffer on the os and lose data (and also never get the callback)

**Comment by hcldan** [comment]
The idea is to slow down the sending of data till the os tcp buffer drains.

some links: 
* https://nodejs.org/api/net.html#socketwritedata-encoding-callback
* https://nodejs.org/en/docs/guides/backpressuring-in-streams/#how-does-backpressure-resolve-these-issues

**Comment by hcldan** [comment]
I am fine with the requirement that compression cannot be used if you want to use backpressure with ws.send

**Comment by hcldan** [comment]
>  is not synchronous if the message is compressed.
I missed that when I read it the first time.

I checked in the code and I see that is true, but because my use-case is fairly low level anyway, I would not mind if I just couldn't use compression (my data happens to already be compressed)

**Comment by lpinca** [comment]
I know what backpressure is and how it works in Node.js, thanks.

> socket.write will return false if the os tcp buffer is over the highwater mark.

Correct, but that value is returned synchronously. `ws.send()` does not always call `socket.write()` synchronously. When we call `ws.send()` and start a compressing the message, what do we return before the the message is actually compressed and written via `ws.send()`?

> As you have it right now, I'm pretty sure that if you're blasting messages into ws.send()

Correct, and that is by design, that's why `ws.send()` has a callback argument.

If you don't want to use the streaming API what you want can be done like this:

```js
ws.send(data, function () {
  // When the last callback is called, that is your `'drain'` event if you ever stopped writing.
});

if (ws.bufferedAmound >= highWaterMark) {
  // Stop writing.
}
```

**Comment by hcldan** [comment]
> I know what backpressure is and how it works in Node.js, thanks.

Yeah, sorry I missed the async for compression part and thought you were confused about something else.

`ws.bufferedAmount` looks promising, thank you.
