### ISSUE TITLE
No `'open'` event on the server

### ISSUE THREAD

**Issue by essential-existence** [websockets/ws#2011]
When the `'connection'` event is emitted the `WebSocket` ready state is `WebSocket.OPEN`.

Have you considered emitting the `'open'` event with `setImmediate` or `queueMicrotask`? This would add more compatibility with the browser `WebSocket`, and therefore with the wrapper libraries above it.

_Originally posted by @lpinca in https://github.com/websockets/ws/issues/1958#issuecomment-939486788_

**Comment by lpinca** [comment]
It does not make much sense on the server and it would be a breaking change for no good reason. You are not waiting for the connection to be established. Users should be able to send data as soon as the `'connection'` event is emitted.

**Comment by essential-existence** [comment]
Yes, it's possible. I just found it inconvenient to write in cross-platform code something like:

> if ( socket.readyState === socket.OPEN ) {
>   /* some code... */
> } else {
>   socket.on( 'open', () => { /* some code... */ } );
> };

However, you can write something like:

> on( 'connection', async ( socket ) => {
>   await (
>     socket.readyState === socket.OPEN ? Promise.resolve()
>     : new Promise( ( resolve, reject ) => {
>       socket.addEventListener( 'open', ( event ) => resolve( event ) );
>     } )
>   );
>   /* some code... */
> } );

**Comment by lpinca** [comment]
That code is risky. A `'message'` event might be emitted while the promise is resolved. Also the else branch will never be taken when using `ws`. `socket.readyState` is always `OPEN` when the `'connection'` event is emitted.

**Comment by essential-existence** [comment]
It's easy to fix:

> if ( socket.readyState !== socket.OPEN )
>   await new Promise( ( resolve, reject ) => {
>     socket.addEventListener( 'open', ( event ) => resolve( event ) );
>   } );
> /* some code... */

So there shouldn't be any message leaks.
And this is exactly the cross-platform section of the code, taking into account the specifics of `ws`.

**Comment by lpinca** [comment]
That branch will never be taken when using `ws` and if you decide to replace `ws` with another module, then there will probably be a lot of other inconsistencies to fix.

**Comment by spalger** [comment]
Do with this was mentioned on the `open` event docs

**Comment by RichardWright** [comment]
@spalger same. I came here to ask the question why the open event isn't raised on websockets inside a websocket server.
