### ISSUE TITLE
req.session Example Not Working

### ISSUE THREAD

**Issue by Megapixel99** [websockets/ws#2017]
### Is there an existing issue for this?

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Description

The example of express-session (found here: https://github.com/websockets/ws/blob/master/examples/express-session-parse/index.js) does not work for me, instead of finding the current session, a new session is created.

Possibly related issue: https://github.com/websockets/ws/issues/1406

### ws version

4.6.0

### Node.js Version

16.6.2 and 17.6

### System

``` 
  System:
    OS: macOS 11.6
    CPU: (8) x64 Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz
    Memory: 24.59 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
```

### Expected result

I expected the session to persist across the express routes and the web socket routes.

### Actual result

A new session is created each time the web socket is called.

### Attachments

Output Logs, after adding logging of the internal session ID:
```
Listening on http://localhost:8080
Updating session for user 75a20782-5988-4081-8468-78ecbd740252
Internal session ID: tCo3eMzEHOKzuHWhy5pHbvh4fNjj_qMF
Parsing session from request...
Internal session ID: orllu-RgKAEYxmiAJQZZI8qgDIOS1QNH
Parsing session from request...
Internal session ID: f0Oe2qIEpa7A7PapSTLhFsDyK5abyhUo
```
Postman Response:
<img width="740" alt="Screen Shot 2022-02-26 at 16 06 37" src="https://user-images.githubusercontent.com/23089578/155862982-247e39fb-92be-4d22-9779-7d19f610e30d.png">
<img width="740" alt="Screen Shot 2022-02-26 at 16 03 15" src="https://user-images.githubusercontent.com/23089578/155862908-b5a5673a-eb9d-4330-aff7-b1f82b580d4a.png">

Code use to log internal session ID:
```console.log(`Internal session ID: ${req.sessionID}`);```

**Comment by Megapixel99** [comment]
In case it was not clear, `req.sessionID` should not change when a session is persistent

**Comment by lpinca** [comment]
It works as expected:

```diff
$ git diff
diff --git a/examples/express-session-parse/index.js b/examples/express-session-parse/index.js
index 8fc4ce0..123e026 100644
--- a/examples/express-session-parse/index.js
+++ b/examples/express-session-parse/index.js
@@ -69,6 +69,7 @@ server.on('upgrade', function (request, socket, head) {
     }
 
     console.log('Session is parsed!');
+    console.log(request.sessionID);
 
     wss.handleUpgrade(request, socket, head, function (ws) {
       wss.emit('connection', ws, request);
```

```
$ node index.js 
Listening on http://localhost:8080
Updating session for user a1514bcd-7a4f-40f9-8fbe-48aaf1404ee3
Parsing session from request...
Session is parsed!
xDfB9iKoTFEcWPumGAmWX0zjuFwvLaF_
Parsing session from request...
Session is parsed!
xDfB9iKoTFEcWPumGAmWX0zjuFwvLaF_
Parsing session from request...
Session is parsed!
xDfB9iKoTFEcWPumGAmWX0zjuFwvLaF_
^C
```

<img width="603" alt="Screenshot 2022-02-27 at 20 14 53" src="https://user-images.githubusercontent.com/1443911/155896414-ef7f4160-0001-4d95-b358-5e907cf4f66d.png">

**Comment by Megapixel99** [comment]
https://user-images.githubusercontent.com/23089578/155906588-62037b4c-aae4-4ce5-bf41-839c7cfe1696.mp4

I have attached a screen recording showing the issue, the code from the example works for me in the browser but does not work in Postman.

**Comment by lpinca** [comment]
The example is made for the browser as it uses cookies. In Postman you have to handle cookies.

**Comment by lpinca** [comment]
I'm closing this as answered.
