### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by JarZem** [websockets/ws#2021]
### Is there an existing issue for this?

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Description

Hi

I am use Node.js version v17.7.1, and when I am run example source codes server I am get this error message:
```
WebSocket/node_modules/ws/lib/websocket.js:672
      throw new SyntaxError(`Invalid URL: ${address}`);
            ^

SyntaxError: Invalid URL: [object Object]
    at initAsClient (/home/jaros/WebSocket/node_modules/ws/lib/websocket.js:672:13)
    at new WebSocket (/home/jaros/WebSocket/node_modules/ws/lib/websocket.js:84:7)
    at file:///home/jaros/WebSocket/index.js:7:13
    at ModuleJob.run (node:internal/modules/esm/module_job:198:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:385:24)
    at async loadESM (node:internal/process/esm_loader:88:5)
    at async handleMainPromise (node:internal/modules/run_main:61:12)
```

### ws version

8.5.0

### Node.js Version

v17.7.1

### System

```
OS: Linux 5.10 Ubuntu 20.04.4 LTS (Focal Fossa)
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 7.03 GB / 7.67 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
```

### Attachments

source code:

```
import WebSocketServer from 'ws';

function heartbeat() {
  this.isAlive = true;
}

const wss = new WebSocketServer({ port: 8080 });

wss.on('connection', function connection(ws) {
  ws.isAlive = true;
  ws.on('pong', heartbeat);
});

const interval = setInterval(function ping() {
  wss.clients.forEach(function each(ws) {
    if (ws.isAlive === false) return ws.terminate();

    ws.isAlive = false;
    ws.ping();
  });
}, 30000);

wss.on('close', function close() {
  clearInterval(interval);
});
```

**Comment by lpinca** [comment]
The problem is in your client code, not the server. The URL used to connect to the server is not valid.

**Comment by Miloune** [comment]
@JarZem had the same problem when i copy / past this example https://github.com/websockets/ws/blob/master/examples/express-session-parse/index.js

Had to do what is describe in this comment:
https://github.com/websockets/ws/issues/348#issuecomment-967803525

`const wss = new WebSocketServer.WebSocketServer({ clientTracking: false, noServer: true });`
istead of 
`const wss = new WebSocketServer({ clientTracking: false, noServer: true });`

**Comment by mludlum** [comment]
> The problem is in your client code, not the server. The URL used to connect to the server is not valid.

Your README needs updating.   That is the problem.
