### ISSUE TITLE
http.Server error handling does not work

### ISSUE THREAD

**Issue by mayfield** [websockets/ws#2023]
### Is there an existing issue for this?

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Description

Hi!

On this line of the `WebSocketServer` any `http.Server` `error` events are proxied to the `WebSocketServer` instance.

https://github.com/websockets/ws/blob/dd3d5a710b490d7b4211f92e882b34b5114c8bc2/lib/websocket-server.js#L112

Because node has some strange designs on events with the literal name `error`, this will result in an `unhandledException` event reaching the process level, which as we all know will try to kill your process.

That might be considered justifiable BUT it actually also breaks error handling at the `http.Server` level.  The `unhandledException` error breaks the `http.Server`'s error event emit loop, so any other `error` listeners registered on the main `http.Server` never get invoked.  There are workarounds that could be employed by the user like ordering your error events such that ws is last, but I had to do a deep dive into the internals of node's `EventEmitter` to figure this out.  Not a great user experience.

I can envision a few ways that this might be handled differently that would allow the user of `WebSocketServer` with an existing `http.Server` that would not create a unique error handling experience.

1. Don't do the error event proxy at all.  Instruct users to use the underlying `http.Server` instead.  Probably not viable as many will be depending on the cur behavior, but worth tossing out.
2. Instead of listening for `error` on the `http.Server` use the `events.errorMonitor` Symbol which allows you to monitor for error events without creating side effects.  Then conditionally emit an `error` event on the `WebSocketServer` instance only if it has `error` listeners.  By using the `events.errorMonitor` if no real `error` event listeners exist on the `http.Server` object it will fallback to node's strange, but by design, `unhandledException` behavior.

For reference, my use case is to monitor `listen(...)` for `EADDRINUSE` errors and retry in a loop with backoff until the port is available.  I'm essentially doing exactly what the node docs say to do here: https://nodejs.org/api/net.html#serverlisten

### ws version

7.5.7

### Node.js Version

17.1.0

### System

I don't use npx.

It's a mac: Darwin HOSTNAME.local.tld 21.3.0 Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_ARM64_T6000 arm64

### Expected result

1. Error event handling on the root Server object to work.
2. Not get an unhandledException error (as a result of having a proper error handler installed on the http.Server object).

### Actual result

Server error handling was broken.
An unexepected.. unexpectedException :smile:

**Comment by mayfield** [comment]
Quick follow up, this is the workaround I'm going to use for now..

```javascript
webSocketServer.on('error', () => void 0);
```

**Comment by lpinca** [comment]
> That might be considered justifiable BUT it actually also breaks error handling at the `http.Server` level.

I disagree because you can either

1. Add a listener for the `'error'` event to the `http.Server` instance before passing it to the `WebSocketServer` constructor.
2. Use the `WebSocketServer` in "noServer" mode.
3. Handle the `'error'` on the `WebSocketServer` instance which should be done anyway as per https://nodejs.org/api/events.html#error-events.

`events.errorMonitor` was added in Node.js v13.6.0 and backported in v12.17.0. We still support Node.js 10 and I do not like to suppress the throwing behavior if there are no listeners for the `'error'` event on the `WebSocketServer` instance.

**Comment by mayfield** [comment]
Hi @lpinca,

I think the **spirit** of my comments may have been overshadowed by my post analysis.  The main point I'm trying to make is that I had an experience that was at odds with the principle of least surprise and it cost me as the casual developer quite a bit of digging to even understand the problem.  What action you take is of less consequence to me.  It's not my code and I'm just trying to help.

**Comment by lpinca** [comment]
Ok, I'm closing this then.

Thank you anyway.
