### ISSUE TITLE
Inconsistent behaviour in a vscode extension

### ISSUE THREAD

**Issue by waterlens** [websockets/ws#2024]
### Is there an existing issue for this?

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Description

I'm trying to open a websocket connection in my vscode extension, but it generates wrong request header. If I use ts-node to run the code directly, it will be all right.

The minimum example (sorry for needing vscode because it only get different behaviour when using `Run Extension`):
> start a empty vscode extension project with `yo code`
```ts
/* extension.ts */
import * as vscode from "vscode";
import * as WebSocket from "ws";

function connect() {
  const ws = new WebSocket("ws://192.168.235.40:8266");
  console.log(ws);
}

export function activate(context: vscode.ExtensionContext) {}

export function deactivate() {}

connect();
```

### ws version

^8.5.0

### Node.js Version

17.7.1

### System

```
System:
    OS: Linux 5.16 Manjaro Linux
    CPU: (16) x64 AMD Ryzen 7 5700G with Radeon Graphics
    Memory: 51.94 GB / 58.82 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
```

### Expected result

The request is right if execute `npx ts-node extension.ts` directly.
```
Hypertext Transfer Protocol
    GET / HTTP/1.1\r\n
    Sec-WebSocket-Version: 13\r\n
    Sec-WebSocket-Key: 9K4JNof/v7KCkl1E4iVCfA==\r\n
    Connection: Upgrade\r\n
    Upgrade: websocket\r\n
    Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits\r\n
    Host: 192.168.235.40:8266\r\n
    \r\n
    [Full request URI: http://192.168.235.40:8266/]
    [HTTP request 1/1]
    [Response in frame: 9966]
```

### Actual result

The request missed a lot of things when `Run Extension`
```
Hypertext Transfer Protocol
    GET / HTTP/1.1\r\n
    Host: 192.168.235.40:8266\r\n
    User-Agent: Go-http-client/1.1\r\n
    Sec-Websocket-Extensions: permessage-deflate; client_max_window_bits\r\n
    Sec-Websocket-Key: u6rveF4jkr7xdw/19znYtg==\r\n
    Sec-Websocket-Version: 13\r\n
    Accept-Encoding: gzip\r\n
    \r\n
    [Full request URI: http://192.168.235.40:8266/]
    [HTTP request 1/1]
```

**Comment by sdrsdr** [comment]
```
User-Agent: Go-http-client/1.1\r\n
```
I **think** this indicates that there is a user agent added to standard http library that you use and this user agent might be breaking the websocket headers mainly 

```
Connection: Upgrade\r\n
Upgrade: websocket\r\n
```

**Comment by waterlens** [comment]
> ```
> User-Agent: Go-http-client/1.1\r\n
> ```
> 
> I **think** this indicates that there is a user agent added to standard http library that you use and this user agent might be breaking the websocket headers mainly
> 
> ```
> Connection: Upgrade\r\n
> Upgrade: websocket\r\n
> ```

Thank you for your reply. You remind me that a local proxy might be responsible for the problem, and it did.
