### ISSUE TITLE
Can't send a header

### ISSUE THREAD

**Issue by Lingaprahasam** [websockets/ws#2027]
### Is there an existing issue for this?

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Description

In Python I am sending a cookie like below in the wrapper

`self.ws_header = [('Cookie', '-http-session-=9;abc=22')]
        self.ws_subProtocol = ['protocol1']

        self.ws = RobWebSocketClient(self.ws_url,
                                     protocols=self.ws_subProtocol,
                                     headers=self.ws_header, onMessage=onMessage, onOpen=onOpen, onClose=onClose)`

where in the library class it takes headers
`class WebSocketClient(WebSocketBaseClient):
    def __init__(self, url, protocols=None, extensions=None, heartbeat_freq=None,
                 ssl_options=None, headers=None, exclude_headers=None):`

I am trying to send a header when creating a websocket
`const ws = new WebSocket(wsLocation, wsProtocol, {
          headers: { Cookie: wsCookie },
        });`
        
 But can't able to make a successful websocket connection.

### ws version

8.5

### Node.js Version

v16.13.2

### Expected result

successful websocket connection

### Actual result

websocket error

**Comment by lpinca** [comment]
You example is ok and it sends the `Cookie` header as expected.

```js
'use strict';

const WebSocket = require('ws');

const server = new WebSocket.Server({ port: 0 }, function () {
  const websocket = new WebSocket(`ws://localhost:${server.address().port}`, {
    headers: { Cookie: 'yummy_cookie=choco' }
  });

  websocket.on('close', function () {
    server.close();
  });
});

server.on('connection', function (websocket, request) {
  console.log(request.headers.cookie);
  websocket.close();
});
```

**Comment by lpinca** [comment]
I'm closing this as answered.
