### ISSUE TITLE
Websocket only connects sometimes...

### ISSUE THREAD

**Issue by Losh531** [websockets/ws#2028]
### Is there an existing issue for this?

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Description

I open a websocket on the server side, the client side tries to connect, but onOpen() is never called - websocket doesn't seem to fully connect?

### ws version

8.2.0

### Node.js Version

16.7.0

### System

System:
    OS: Linux 5.13 Ubuntu 20.04.2 LTS (Focal Fossa)
    CPU: (8) x64 AMD EPYC 7B12
    Memory: 10.83 GB / 62.80 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash

### Expected result

onOpen() to be called and the code talks to the server

### Actual result

The client tries to connect - but fails.

**Comment by lpinca** [comment]
I'm sorry but this issue not actionable. There is not much we can do with the provided info. Please share a minimal code example to reproduce the issue.

**Comment by Losh531** [comment]
Oh - so sorry! I realized that it was a race condition which was why it happened sometimes. Thanks for your help!
