### ISSUE TITLE
I us ws create client, When ws close, report an error when I reConnection 

### ISSUE THREAD

**Issue by liangfz-kit** [websockets/ws#2031]
### Is there an existing issue for this?

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Description

```
const ws = require('ws');
this.client = new ws('ws://127.0.0.1:9999/t/emg');
this.isEmgClose = false;
this.client.onclose = (error) => {
   this.isEmgClose = true
    this.client.close();
};

setInterval(() => {
  console.log('laihuidiao');
  if (this.isEmgClose) {
    this.client = new ws('ws://127.0.0.1:9999/t/emg');
  }

}, 1000);
```

error 
```
/Users/Desktop/ngiq/ngiq-point-desktop/node_modules/ws/lib/websocket.js:440
      throw new Error('WebSocket is not open: readyState 0 (CONNECTING)');
      ^

Error: WebSocket is not open: readyState 0 (CONNECTING)
    at WebSocket.send (/Users/Desktop/ngiq/ngiq-point-desktop/node_modules/ws/lib/websocket.js:440:13)
```

### ws version

8.5.0

### Node.js Version

14.17.0

### System

macos   electron

**Comment by lpinca** [comment]
That error means that `websocket.send()`, `websocket.ping()`, or `websocket.pong()` was called when the ready state was  `CONNECTING`. That is expected. You have to wait for the `'open'` event before calling those methods.

**Comment by liangfz-kit** [comment]
When ws close， How to reconnection ?

**Comment by lpinca** [comment]
That error means that the connection was refused by the server. You have to handle that and reconnect again.

**Comment by lpinca** [comment]
I'm closing this as answered.
