### ISSUE TITLE
Inability to Defer Connection

### ISSUE THREAD

**Issue by Zamiell** [websockets/ws#2039]
Greetings, and thanks for the library.

Upon creating a new `ws` client with e.g.
```js
const ws = new WebSocket(WEBSOCKET_URL);
```
Under the hood, the library will automatically connect to the URL.

This automatic connection is not desired in some contexts. It would be better if the end-user had the ability to defer the connection, like so:

```js
const ws = new WebSocket(WEBSOCKET_URL, {
  connect: false, // This option is true by default
});

// Perform other tasks
// TODO

ws.connect();
```

If I did a pull request for this, would it be accepted?

Instantiating the class before a connection is preferable so that you can avoid programming with non-null checks/assertions. As a small toy example, consider the following code:

```ts
class MyClass {
  ws: WebSocket | null = null;
  
  connect(url: string) {
    this.ws = new WebSocket(url);
  }
  
  send(data: unknown) {
    if (this.ws === null) {
      throw new Error("Grrr, dealing with the null case is annoying!");
    }
    
    this.ws.send(data);
  }
}
```

**Comment by lpinca** [comment]
> If I did a pull request for this, would it be accepted?

I prefer to not deviate from the browser interface and add more non "standard" methods. Using a wrapper like in your example might be a little annoying but I think it is reasonable for edge cases where the wanted behavior is needed/desirable.

**Comment by Zamiell** [comment]
Ok, thank you for the quick response!
