### ISSUE TITLE
How to reconnect automatically if websocket is closed?

### ISSUE THREAD

**Issue by esuarezz** [websockets/ws#2040]
### Is there an existing issue for this?

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Description

Hi!

I am using this websockets and after 24H the platform is disconnecting the websockets so I need to reconnect, how can I do this reconnection automatically?

### ws version

question

### Node.js Version

question

### System

question

### Expected result

question

### Actual result

question

### Attachments

question

**Comment by lpinca** [comment]
There is no automatic reconnection. You have to do it yourself. You can also use a wrapper like https://github.com/porsager/pws or https://github.com/lukeed/sockette.

**Comment by lpinca** [comment]
I'm closing this as answered.
