### ISSUE TITLE
Help with URL on client side

### ISSUE THREAD

**Issue by carlosveny** [websockets/ws#2041]
### Is there an existing issue for this?

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Description

Hello, it's my first time using this plugin and I can't seem to get it to work. I've followed some tutorials and everything works fine on localhost, but I have a server running apache and nodeJS (on different ports) and I'm not able to establish the ws connection. I don't know which URL I have to put on the client side. In local I use localhost but in the webserver I have no idea. I've tried with the URL of the host and the IP and nothing happens. I've also tried using wss instead of ws.  

I don't know if I'm not getting the concept of websockets or that I'm doing something wrong.
Any help will be appreciated.
Carlos

### ws version

8.5.0

### Node.js Version

16.15.0

### System

OS: Linux 4.15 Ubuntu 16.04.1 LTS (Xenial Xerus)
CPU: (4) x64 Intel(R) Core(TM)2 Quad CPU    Q9400  @ 2.66GHz
Memory: 3.31 GB / 7.66 GB
Container: Yes
Shell: 4.3.46 - /bin/bash

### Expected result

I want to establish the connection between the client and the server in my webserver.

### Actual result

Connection is not established.

**Comment by lpinca** [comment]
Do you get any error? You have to use the same URL you use to connect to your server in the browser but with the `ws:` or `wss:` protocol instead of `http:` or `https:`.

**Comment by carlosveny** [comment]
I'm using the same URL with `wss:` instead of `https:`. I get the following errors:
`GET wss://alumnes-ltim.uib.es/gdie2208/:8080` which is a 404 Not Found error.
`Firefox can't establish a connection with the server in wss://alumnes-ltim.uib.es/gdie2208/:8080`.
`WebSocket Connection is closed..`. This is a console.log from the JS when the connection closes so it's not an error.  

I've tried different URLs and nothing works. This is how my server is organized:  
`html`  
--- `repo` 
--- --- `index.html`
--- --- `js`
--- --- --- `script.js` (this contains the code that tries to connect with the websocket)
--- --- `node`  
--- --- --- `server.js` (this contains the websocket configuration on port 8080)  
  
The thing is, which URL do I have to use? To go to my main page (`index.html`) the absolute path is alumnes-ltim.uib.es/gdie2208/repo/index.html.  

Thanks for your help.

**Comment by carlosveny** [comment]
Nevermind, it was a proxy issue on my server. Anyways thanks for your help @lpinca . I'll close this issue

**Comment by KainatNz** [comment]
@carlosveny  how did you resolve the issue i am facing same issue?

**Comment by carlosveny** [comment]
Hello, it was a port issue. I was trying to establish te connection through a wrong port. I just changed the port to the correct one and it worked.
