### ISSUE TITLE
clients should be mapped to an array, I realize it's an object that is circular but you could use mutexes and functions

### ISSUE THREAD

**Issue by andrewhodel** [websockets/ws#2043]
### Is there an existing issue for this?

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Description

You can use `forEach()` but you cannot break from it as it returns for each client.

### ws version

latest

### Node.js Version

16 LTS

### System

Linux 4

### Expected result

```
var mutex = false;
var modify = function(obj) {

  while (mutex === true) {
    // blocking
  }

  mutex = true;

  // work on obj
  var return_value;

  // return the modified object cloned within the mutex session and after modification
  return_value = JSON.parse(JSON.stringify(obj));

  mutex = false;

  return return_value;

}

modify(something);
```

### Actual result

You cannot find a client.

**Comment by lpinca** [comment]
I don't understand. Can you please provide more details? How is this related to `ws`? You are not forced to use `forEach()`, you can use `for...of` to loop over the clients set which allows you to break outside the loop.

**Comment by andrewhodel** [comment]
The `clients` Set is not an Object.

```
for (var client in .clients) {
  // does nothing
}

console.log(.clients.length); // not defined
```

**Comment by lpinca** [comment]
```js
for (const client of server.clients) {
 // Do something with `client`.
}

console.log(server.clients.size);
```

**Comment by andrewhodel** [comment]
What purpose is there in more than objects and arrays other than repeats of different languages and their complexities?

Also, `const` should be handled at compile time (JIT) in this language.  Only var should exist especially with const not even locking objects.

But OK, thanks for the geography lesson?

**Comment by andrewhodel** [comment]
It has no reason, it's just an Object without keys.

```
In addition, Array is considered as “indexed collection” type of data structure, while Set is considered as “keyed collection”.
```

**Comment by lpinca** [comment]
With an array operations like https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set/has and https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set/delete would have an `O(n)` time complexity.

**Comment by andrewhodel** [comment]
You are wrong about using it, I'll open an issue for you.

**Comment by andrewhodel** [comment]
I know, it's faster to delete with order and they say, `it's faster to delete from an ordered set` so the developers just build that stuff.
