### ISSUE TITLE
using Set() instead of [] for clients is wrong

### ISSUE THREAD

**Issue by andrewhodel** [websockets/ws#2044]
### Is there an existing issue for this?

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Description

Too slow.

```
var s = new Set();

var start = Date.now();
var l = 0;
while (l < 50000) {
    s.add(Math.random(50000) * 1111);
    l++;
}
console.log('Set() add 50k Number()s', Date.now()-start);

var s = [];

var start = Date.now();
var l = 0;
while (l < 50000) {
    s.push(Math.random(50000) * 1111);
    l++;
}
console.log('[] add 50k Number()s', Date.now()-start);
```

### ws version

latest

### Node.js Version

16 LTS

### System

Linux/MacOS

### Expected result

Arrays are faster than Sets.

### Actual result

<img width="1429" alt="Screen Shot 2022-05-13 at 4 29 11 PM" src="https://user-images.githubusercontent.com/741705/168224563-c8e26e4d-00e1-406d-96fb-c7dbad5b9aa8.png">

https://www.typescriptlang.org/play?ssl=19&ssc=55&pln=1&pc=1#code/G4QwTgBAzhC8EDsCmB3CBlJAXAFASgG4AoI0SKLcLOCAERCyQDoEB7FfYsiAGxoAZiKABYBLHkgg4+AHggBWfkv54IAbyIQt0JiAAmenAFkGwpmBAI9rALY5FylRABUEAIwe3hTdp4BqP2IAXyIAY1YEKFYJJh5WAHMcAHJMXFV9PQV+AGsIADkAVxsAIyQwfCgkgBo6BmY2DjwAWgoqb1JwaBoAbQBdYg7ySjBqeHpGFnZOQd4BITEJKVks5VUNbR0ABwKoYWNTc0trOwdVl3dPbw3-QKIQ8Mjo5jjEpL6IDKzcwpKyiurahMGvgWsMsIQgA

```
var s = new Set();

var start = Date.now();
var l = 0;
while (l < 50000) {
    s.add(Math.random(500000) * 1111);
    l++;
}
console.log('Set() add 50k Number()s', Date.now()-start);

var s = [];

var start = Date.now();
var l = 0;
while (l < 50000) {
    s.push(Math.random(500000) * 1111);
    l++;
}
console.log('[] add 50k Number()s', Date.now()-start);
```

**Comment by lpinca** [comment]
It might faster to add elements to an array but it is way slower to remove them from an array. As written in https://github.com/websockets/ws/issues/2043#issuecomment-1125701268 this operation https://github.com/websockets/ws/blob/ba214d96939737304fb76f662700e9df01bb4418/lib/websocket-server.js#L403 would have a `O(n)` time complexity with an array.

**Comment by andrewhodel** [comment]
It certainly is not. You cannot access them without finding them first. It is designed to be slow with a large number of socket clients. Why not fix it by using an array?You cannot remove without first looping through the entire set of clients and you may need to do that for each normal http request when using websockets. Why do that to people, it is massively slower. AndrewSent from my Huawei phone-------- Original message --------From: Luigi Pinca ***@***.***>Date: Fri, May 13, 2022, 4:57 PMTo: websockets/ws ***@***.***>Cc: Andrew Hodel ***@***.***>, Author ***@***.***>Subject: Re: [websockets/ws] using Set() instead of [] for clients is wrong (Issue #2044)
It might faster to add elements to an array but it is way slower to remove them from an array. As written in #2043 (comment) this operation https://github.com/websockets/ws/blob/ba214d96939737304fb76f662700e9df01bb4418/lib/websocket-server.js#L403 would have a O(n) time complexity with an array.

**Comment by andrewhodel** [comment]
It is not faster a removing them either. It is faster than array.splice but not setting them to undefined. In fact it is slower in every way. AndrewSent from my Huawei phone-------- Original message --------From: Luigi Pinca ***@***.***>Date: Fri, May 13, 2022, 4:57 PMTo: websockets/ws ***@***.***>Cc: Andrew Hodel ***@***.***>, Author ***@***.***>Subject: Re: [websockets/ws] using Set() instead of [] for clients is wrong (Issue #2044)
Closed #2044.

**Comment by lpinca** [comment]
> You cannot remove without first looping through the entire set of clients and you may need to do that for each normal http request when using websockets.

This is not true. Again see https://github.com/websockets/ws/blob/ba214d96939737304fb76f662700e9df01bb4418/lib/websocket-server.js#L403. When the `WebSocket` object emits the `'close'` event there is no need to find it first. There is already a reference to the object and that reference is used to remove the object from the set without loops.

> Why do that to people, it is massively slower.

This is how the implicit client tracking works. If you are not happy with it with you can set the `clientTracking` option to `false`. In that way no set is used and tracking clients is up to the user.

```js
const wss= new WebSocketServer({ server, clientTracking: false });

wss.on('connection', function (ws) {
  // Save this reference to an array? It's up to you.
});
```

**Comment by andrewhodel** [comment]
![1652426911402](https://user-images.githubusercontent.com/741705/168233291-251e351e-bdcc-49f6-bebd-4d3aac26708c.jpg)

**Comment by andrewhodel** [comment]
There is also the problem of maximum set sizes being another complication. 

![1652426977748](https://user-images.githubusercontent.com/741705/168233470-c355c58c-4c46-4bba-b09c-706d2f239bac.jpg)

**Comment by andrewhodel** [comment]
But you are wrong about the Set being faster. With delete and add.

**Comment by lpinca** [comment]
> It is faster than array.splice but not setting them to undefined

That's exactly the reason why a set is used. Using holey arrays is not an option as it messes up the array length.

**Comment by andrewhodel** [comment]
That does not make sense, they are not holey arrays, you need to use mutexes in modifications routines.

**Comment by andrewhodel** [comment]
It is obvious you are not being honest. You plainly said remove is faster in a set and that is not true.

**Comment by andrewhodel** [comment]
Did you not understand the code for mutexes I provided in the original comment?

**Comment by andrewhodel** [comment]
It is much faster to undefine then move the pointers, that is a splice bug and not relevant to the creation of Set.Set seems useless and existing only to satisfy confusion. Go has a GC too you know. AndrewSent from my Huawei phone-------- Original message --------From: Luigi Pinca ***@***.***>Date: Fri, May 13, 2022, 5:32 PMTo: websockets/ws ***@***.***>Cc: Andrew Hodel ***@***.***>, Author ***@***.***>Subject: Re: [websockets/ws] using Set() instead of [] for clients is wrong (Issue #2044)

It is faster than array.splice but not setting them to undefined

That's exactly the reason why a set is used. Using holey arrays is not an option as it messes up the array length.

**Comment by lpinca** [comment]
> There is also the problem of maximum set sizes being another complication.

That would mean millions of `WebSocket`s which is unrealistic on a single Node.js process.

> But you are wrong about the Set being faster. With delete and add.
> It is obvious you are not being honest. You plainly said remove is faster in a set and that is not true.

```js
'use strict';

const benchmark = require('benchmark');

class Foo {}

const clients = [];

for (let i = 0; i < 1000; i++) {
  clients.push(new Foo());
}


function shuffle(arr) {
  let i, j, x;
  for (i = arr.length - 1; i > 0; i--) {
    j = Math.floor(Math.random() * (i + 1));
    x = arr[i];
    arr[i] = arr[j];
    arr[j] = x;
  }
}

function remove(element) {
  // To remove the element the corresponding index must be found first.
  for (let i = 0; i < array.length; i++) {
    if (array[i] === element) {
      array.splice(i, 1);
      break;
    }
  }
}

const array = [];
const set = new Set();
const suite = new benchmark.Suite();

suite.add('array', function () {
  let i;

  for (i = 0; i < clients.length; i++) {
    array.push(clients[i]);
  }

  shuffle(clients);

  for (i = 0; i < clients.length; i++) {
    remove(clients[i]);
  }
});

suite.add('set', function () {
  let i;

  for (i = 0; i < clients.length; i++) {
    set.add(clients[i]);
  }

  shuffle(clients);

  for (i = 0; i < clients.length; i++) {
    set.delete(clients[i]);
  }
});

suite.on('cycle', function (event) {
  console.log(event.target.toString());
});

suite.on('complete', function () {
  console.log('Fastest is ' + this.filter('fastest').map('name'));
});

suite.run({ async: true });
```

```
$ node index.js
array x 3,413 ops/sec ±1.71% (85 runs sampled)
set x 9,977 ops/sec ±4.04% (73 runs sampled)
Fastest is set
```

**Comment by andrewhodel** [comment]
That's not true, you are using `array.splice(i, 1);` in the delete function instead of undefined and you are only doing it because you know the maximum length of the `Set()` is already limited in Javascript.

There is no reason not to use an array, then the developer implementing the library can maintain an index of the most used array items to search through first and find the actual item by the order in the array.

**Comment by lpinca** [comment]
> you are using array.splice(i, 1); in the delete function instead of undefined

What is the alternative? Doing `arr[i] = undefined` is not an option.

**Comment by andrewhodel** [comment]
You are ignoring the problem here, using `arr[i] = undefined;` is faster.

You can support infinite length arrays with this system and the speed will be based on the number of them (exactly like Set).  `undefined` is faster than splice because it doesn't shift the array each modification.

What you are really missing is that to manage a list of most used items in `clients`, you will have to go through every single item in clients to re-access it.

**Comment by lpinca** [comment]
Again, feel free to use an array. The library allows you to do that with no overhead by using the `clientTracking` option.

**Comment by lpinca** [comment]
`arr[i] = undefined;` creates an holey array.

**Comment by andrewhodel** [comment]
The client being closed at any time is not relevant, the truth is that you use a mutex that is common amongst all functions capable of modifying the data.  Then the return or callback of any of those functions is always finished before returning the data or part of the data.

It doesn't matter to me, I'm just explaining to you that using a `Set()` because it is simpler to implement than an `Array` is a ruin of Javascript and not what's great about languages with garbage collection and modular libraries.  Unicode, etc.

**Comment by andrewhodel** [comment]
It does not create a holey array, you lock the data with a mutex and reloop through the data a second time to remove all of the undefined items.

This prevents splice from doing this internally for every item (why it is slow), makes the speed the same as `Set()` and allows accessing the items by reference (an update() function) for storing data with a client instead of maintaining another data object (javascript's worth).

**Comment by andrewhodel** [comment]
I don't understand `clientTracking`, the only thing it changes is using a set instead of an array?

**Comment by lpinca** [comment]
No, setting `clientTracking` to `false` prevents references to clients to be saved. If you want to keep a reference to them then how to do that it's up to you.

**Comment by andrewhodel** [comment]
This is what's most important and what `Array` should be default.


You can support infinite length arrays with this system and the speed will be based on the number of them (exactly like Set). undefined is faster than splice because it doesn't shift the array each modification.

What you are really missing is that to manage a list of most used items in clients, you will have to go through every single item in clients to re-access it.

**Comment by andrewhodel** [comment]
It's not a reference, Javascript needs directional operators because modules use objects that are accessible throughout and passing them to and from each function is memory heavy.

Directional operators are just using `=, <=, and >=` instead of `* and &` like in C.  Same basic idea.

**Comment by andrewhodel** [comment]
You are basically saying setting `clientTracking` to false uses an `Array` and sends a clone, you know that right.

That's why you would use directional operators instead.

**Comment by andrewhodel** [comment]
```
var l = function(blah) {

  blah <= 'test';

}

var n = 'adsf';
l(n);

console.log(n);
```

**Comment by andrewhodel** [comment]
Anyhow, thanks.  I understand, `Set()` is a lazy, won't be too big faster delete keyless object.
