### ISSUE TITLE
Adding custom headers to HTTP Upgrade response

### ISSUE THREAD

**Issue by bahamut657** [websockets/ws#2053]
### Is there an existing issue for this?

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Description

It seems impossible to add custom headers in respose to the HTTP Upgrade Request.
Is it possible to expose this functionality (with custom callback or exposing an additional parameter in object constructor)?

### ws version

8.0.0

### Node.js Version

16.15.0

### System

System:
    OS: Linux 5.17 Arch Linux
    CPU: (4) x64 Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz
    Memory: 5.05 GB / 11.61 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash

### Expected result

Custom headers are sent during HTTP Upgrade Response

### Actual result

Only standard headers are sent during HTTP Upgrade Response

**Comment by lpinca** [comment]
See https://github.com/websockets/ws/blob/8.7.0/doc/ws.md#event-headers.

**Comment by lpinca** [comment]
I'm closing this as answered.

**Comment by bahamut657** [comment]
It works like expected. Thank you for the support

**Comment by tgbv** [comment]
Could you please provide an example? I tried a few methods but they don't work:
```js
websocketServer.on('headers', function(headers, request) {
  headers.push('x-test', 'test')
});

websocketServer.on('headers', function(headers, request) {
  headers.push('x-test', 'test');

  return headers;
});
```
