### ISSUE TITLE
How to properly close socket on wsClientError event

### ISSUE THREAD

**Issue by Romick2005** [websockets/ws#2054]
### Is there an existing issue for this?

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Description

I am not sure how to properly close socket on `'wsClientError'` as there are line with `The listener of this event is responsible for closing the socket.`

```
wss.on('wsClientError', (error, socket, request) => {
  0) `if (!socket) { return; }` // Do we need check here if socket exist and is open?
  1) `socket.destroy();` // Cover all of the required cleanup?
  2) `socket.end();` // Just end and this will properly close socket
  3) `socket.end('HTTP/1.1 400 Bad Request\r\n\r\n'); `// Is this enough to pass this string? 
});
```

### ws version

8.7.0

### Node.js Version

v16.14.2

### System

    OS: macOS 12.4
    CPU: (8) arm64 Apple M1
    Memory: 62.58 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh

### Expected result

Properly close socket.

### Actual result

Not verified

**Comment by lpinca** [comment]
It's up to you. The socket should be writable, unless something else ended/destroyed it before. You can destroy it without writing anything, write the HTTP response and then end/destroy it.

**Comment by Romick2005** [comment]
Thank you!
