### ISSUE TITLE
"Invalid WebSocket frame: RSV1 must be clear" Error on WS 8.8

### ISSUE THREAD

**Issue by rcaner** [websockets/ws#2058]
### Is there an existing issue for this?

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Description

Before the previous version WS, we have no issue. But after upgrading ws 8.8 we encounter this error.

"Invalid WebSocket frame: RSV1 must be clear".

While Client side is requesting connection, API's are down and restarted. 

Do you have any suggestion about this topic?

PS: I check your changes, you change only environment variables on bufferutil and utf8, how we can use these environment variables? 

### ws version

8.8.0

### Node.js Version

16.15.1

### System

    OS: Linux 5.4 Debian GNU/Linux 10 (buster) 10 (buster)
    CPU: (40) x64 Intel(R) Xeon(R) CPU E5-2658 v2 @ 2.40GHz
    Memory: 19.59 GB
    Container: Yes
    Shell: 5.0.3 - /bin/bash

### Expected result

Connection should be successful and not crashed APIs.

### Actual result

"Invalid WebSocket frame: RSV1 must be clear".

**Comment by lpinca** [comment]
Duplicate of #2055 and #2019.

**Comment by lpinca** [comment]
> PS: I check your changes, you change only environment variables on bufferutil and utf8, how we can use these environment variables?

Set them at the process level. For example

```
$ WS_NO_BUFFER_UTIL=1 WS_NO_UTF_8_VALIDATE=1 node app.js
```

**Comment by rcaner** [comment]
We tried again with #2019 but problem not solved. our API's always failed after upgrading 8.8.0. But I can ask another question, we can't use websocket library in browser. So we have to use JS Websocket , is there any problem about that also ?

**Comment by rcaner** [comment]
Accidentally close so sorry about that.

**Comment by lpinca** [comment]
> So we have to use JS Websocket , is there any problem about that also ?

No, that is ok.

About your problem, write and share a minimal reproducible test case using only `ws`.

**Comment by rcaner** [comment]
Actually we don't send a message at the startup, We only connect socket and API's are crashed with this error. I will prepare a nodejs code for reproducing. Thank you for your support

**Comment by lpinca** [comment]
It doesn't matter _when_ the invalid frame. It can happen at any time.

**Comment by rcaner** [comment]
We found smt but we didn't understand how to reproduce it. In Windows machine code works, but in the docker containerized linux nodejs(node 16) machine not working. Always return 1002 code number while connecting WSS.

**Comment by lpinca** [comment]
I think there is something wrong in your setup but anyway, the server should not crash if there is a listener for the `'error'` event on the `WebSocket` instance when the error is raised. Without a test case to investigate there is not much we can do.

**Comment by rcaner** [comment]
Ok. Thank you very much Ipinca we will investigate into this issue. I'll inform you our solution.

**Comment by rcaner** [comment]
Hey Ipinca, I finally found the problem. Like as you said your code works as expected, but our security guys try smt in the firewall ip intervention rules added. All WS connection requests are distorted. There is no problem right now. Thank you for your support
