### ISSUE TITLE
WSS not working on self-signed certificate (localhost)

### ISSUE THREAD

**Issue by cbeltrangomez84** [websockets/ws#2059]
### Is there an existing issue for this?

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Description

When I follow the example in the readme about how to connect to [wss server](https://github.com/websockets/ws/#external-https-server) and try to connect to the websocket, nothing happens (no connection).

* I'm using a [self-signed certificate](https://medium.com/developer-rants/implementing-https-and-wss-support-in-express-with-typescript-of-course-f36006c77bab) 

* The behaviour I got on localhost is exactly the same in the server.

* I'm using the WebSocket Test Client Extension for Chrome.

### ws version

8.8.0

### Node.js Version

14.16.0

### System

OS: Windows 10 10.0.19044
CPU: (12) x64 Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
Memory: 38.75 GB / 63.82 GB

### Expected result

I expect to open a connection succesfully on wss

### Actual result

Nohing happens, it even does not give any specific error.

If I open for example the port 2053 an try to connect with the tester extension to that port, it only says "error", but if I try to another port (not the one I'm using in my code) the extension does not fail but shows "connecting..." that indicates there is something actually happening when I try to connect.

I have tried connecting to wss://localhost:2053, to wss://127.0.0.1:2053, and to wss://0.0.0.0:2053, but is all the same.

**Comment by lpinca** [comment]
[Tests](https://github.com/websockets/ws/blob/8.8.0/test/websocket.test.js#L3331-L3470) are run using a self-signed certificate, take a look at them. You need to use the [`rejectUnauthorized`](https://nodejs.org/api/tls.html#tlsconnectoptions-callback) option when using a self-signed certificate.

**Comment by cbeltrangomez84** [comment]
Hi, sadly, since I´m building a web application I cannot set the websocket headers in the way the examples does.

**Comment by lpinca** [comment]
> In my implementation I need to use the browser built-in Websocket class

Then you can't use a self-signed certificate unless you make it "trusted" to your browser, but that is nothing to do with `ws`. You can search Google on how to do that. For example, see https://betterprogramming.pub/trusted-self-signed-certificate-and-local-domains-for-testing-7c6e6e3f9548.

**Comment by cbeltrangomez84** [comment]
Thanks, if thats not possible I'll close the issue. (I think I'm facing the same problem in the server because I don't have a domain attached to it so is not possible to have a valid certificate).

Regards.

**Comment by JaielZeus** [comment]
So, I am doing a websocket server with a self-signed certificate. Browserclients using native WebSockets connect correctly, at least from the same host/ip/domain, but my nodejs WebSockets do not. I had to use the ``rejectUnauthorized`` flag for that. What is the deal with that? Why does self-signed Let's encrypt certificate work for Browserclients but ``ws`` rejects it?
