### ISSUE TITLE
when websocket is connected, the eventsListener open to send message is failed

### ISSUE THREAD

**Issue by JimFirst** [websockets/ws#2060]
### Is there an existing issue for this?

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Description

when websocket is connected, the eventsListener open to send message is failed, the server websocket is not receive the message, need delay sometime like 0.3 to send message.

`
const WebSocket = require('ws')
const ws = new WebSocket(url)
ws.on('oepn', () => {
  ws.send(some message). // fail, the server websocket is not receive the message
})
ws.on('oepn', () => {
  setTimeout(() => {
    ws.send(some message). // success, the server websocket receive the message
  }, 30)
})
`

### ws version

v8.5.0

### Node.js Version

v10.5.0

### System

macOS

### Expected result

when websocket is connected, the eventsListener open to send message is success

### Actual result

when websocket is connected, the eventsListener open to send message is failed, the server ws is not receive the message, need delay sometime like 0.3 to send message

**Comment by lpinca** [comment]
No, you can send a message as soon as the `'open'` event is emitted.

```
$ cat index.js 
const WebSocket = require('ws');

const server = new WebSocket.Server({ port: 0 }, function () {
  const ws = new WebSocket(`ws://localhost:${server.address().port}`);

  ws.on('open', function () {
    ws.send('Hello');
  });
});

server.on('connection', function (ws) {
  ws.on('message', function (data) {
    console.log(data.toString());
    ws.close();
  });

  ws.on('close', function () {
    server.close();
  });
});
```

```
$ node index.js 
Hello
```
