### ISSUE TITLE
High ram usage after sending files over a web socket

### ISSUE THREAD

**Issue by westhecool** [websockets/ws#2061]
### Is there an existing issue for this?

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Description

code:
```
ws.send(JSON.stringify({
a: 'files',
function: 'file',
path: path,
data: fs.readFileSync(path).toString('base64')
}));
```

### ws version

v8.7.0

### Node.js Version

v17.3.1

### System

  System:
    OS: Linux 5.13 Ubuntu 20.04.2 LTS (Focal Fossa)
    CPU: (16) x64 AMD EPYC 7B12
    Memory: 37.76 GB / 62.80 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash

### Expected result

It sends the files over and then the ram usage goes down.

### Actual result

It sends the files but then the ram usage just keeps going up as more files are sent. (increasing by the size of the file every time a file is sent)

**Comment by lpinca** [comment]
I'll answer with a tweet: https://twitter.com/matteocollina/status/1537103641638752262

Unless your process crashes due to OOM it is probably ok. Monitor it over time when there is no traffic and see if it stabilises around a given value.

**Comment by lpinca** [comment]
In the following example 10 MiB of binary data are continuously read (using `fs.readFileSync()` as in your example) and sent.

```js
const crypto = require('crypto');
const fs = require('fs');
const WebSocket = require('ws');

fs.writeFileSync('data.bin', crypto.randomBytes(10 * 1024 * 1024));

const server = new WebSocket.Server({ port: 0 }, function () {
  const ws = new WebSocket(`ws://localhost:${server.address().port}`);
});

server.on('connection', function (ws) {
  function send() {
    ws.send(fs.readFileSync('data.bin'), send);
  }
});

setInterval(function () {
  console.log(process.memoryUsage.rss() / 1024 / 1024);
}, 2000);
```

I see nothing wrong with memory usage. The resident set size is stable.

**Comment by westhecool** [comment]
> In the following example 10 MiB of binary data are continuously read (using `fs.readFileSync()` as in your example) and sent.
> 
> ```js
> const crypto = require('crypto');
> const fs = require('fs');
> const WebSocket = require('ws');
> 
> fs.writeFileSync('data.bin', crypto.randomBytes(10 * 1024 * 1024));
> 
> const server = new WebSocket.Server({ port: 0 }, function () {
>   const ws = new WebSocket(`ws://localhost:${server.address().port}`);
> });
> 
> server.on('connection', function (ws) {
>   function send() {
>     ws.send(fs.readFileSync('data.bin'), send);
>   }
> });
> 
> setInterval(function () {
>   console.log(process.memoryUsage.rss() / 1024 / 1024);
> }, 2000);
> ```
> 
> I see nothing wrong with memory usage. The resident set size is stable.

I also ran the test and nothing went wrong but when I remove the ws.send() on my program the memory is fine (even while reading the file)

**Comment by westhecool** [comment]
I found the issue it had nothing to do with this package the problem was node's memory limit was higher than the shared resources ahead available I set it lower and it's working fine now
