### ISSUE TITLE
Connection close event possibly not working

### ISSUE THREAD

**Issue by Nolanrulesroblox** [websockets/ws#2065]
### Is there an existing issue for this?

- [x] I've searched for any related issues and avoided creating a duplicate issue.

### Description

```javascript
//PORT 8082
const WebSocket = require("ws");
  const wss = new WebSocket.Server({  port: SERVER_PORT });
  wss.on("connection",async (ws, req) => {
  console.log(ws)
  })
    ws.on("message", data => {
       console.log(data)
  });
    wss.on("error",(ws, req) => {
      // Manage error here
      console.log(ws);
  });
  wss.on("close",(ws, req) => {
    // Manage closehere
    console.log(ws);
  });

```
BROWSER:
```
    var q = new WebSocket('ws://{IP}:8082?room=3);
    setTimeout(() => {
        const data = { "type": "broadcast",};
q.send(JSON.stringify(data))
    }, 500); 
```

My goal: send a console.log() when the Websocket connection closes (i,e, server and client disconnect)

### ws version

8.8.0

### Node.js Version

v16.0.0

### System

    OS: Linux 5.15 Ubuntu 22.04 LTS 22.04 LTS (Jammy Jellyfish)
    CPU: (96) x64 Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz
    Memory: 6.05 GB / 766.3 GB
    Container: No
    Shell: 5.1.16 - /bin/bash

### Expected result

Log the close of each closure (i.e. by network fail or call by websocketbrowser.close())

### Actual result

Nothing is logged besides the initial connection and Message

**Comment by lpinca** [comment]
You have to add a listener for the `'close'` event to the `WebSocket` object.

```js
const server = new WebSocket.Server({  port: SERVER_PORT });

server.on('connection', function (ws, req) {
  ws.on('close', function (code, reason) {
    // Manage closehere.
  });
});
```

**Comment by lpinca** [comment]
There are 2 different `'close'` events. One is emitted on the `WebSocketServer` object: https://github.com/websockets/ws/blob/8.8.0/doc/ws.md#event-close. The other is emitted on the `WebSocket` object: https://github.com/websockets/ws/blob/8.8.0/doc/ws.md#event-close-1.
