### ISSUE TITLE
TypeError: undefined is not a constructor (evaluating 'new (_$$_REQUIRE(_dependencyMap[0], "ws").WebSocketServer)()'

### ISSUE THREAD

**Issue by AsteriskZuo** [websockets/ws#2066]
### Is there an existing issue for this?

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Description

I've seen this question #2026, but his method didn't work for me.
I am using the `ws` plugin in a react-native project, and debugging the simplest example code also prompts an error.
nodejs version: v16.15.1
@types/node version: 17.0.45
ws version: 8.8.0
@types/ws version: 8.5.3

example:
`
import {WebSocketServer as WSWebSocketServer} from 'ws';
const wss = new WSWebSocketServer();
`
error:
`
  ERROR TypeError: undefined is not a constructor (evaluating 'new (_$$_REQUIRE(_dependencyMap[0], "ws").WebSocketServer)()')
`

### ws version

8.5.5

### Node.js Version

v16.15.1

### System

  System:
    OS: macOS 12.3.1
    CPU: (8) arm64 Apple M1
    Memory: 110.34 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh

### Actual result

  ERROR TypeError: undefined is not a constructor (evaluating 'new (_$$_REQUIRE(_dependencyMap[0], "ws").WebSocketServer)()')

### Attachments

package.json
```
{
  "name": "rn_wayang",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint . --ext .js,.jsx,.ts,.tsx"
  },
  "dependencies": {
    "react": "17.0.2",
    "react-native": "0.66.4",
    "ws": "^8.8.0"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@babel/preset-env": "^7.18.6",
    "@babel/runtime": "^7.12.5",
    "@react-native-community/eslint-config": "^3.0.0",
    "@types/jest": "^26.0.23",
    "@types/node": "^17",
    "@types/react-native": "^0.66.4",
    "@types/react-test-renderer": "^17.0.1",
    "@types/ws": "^8.5.3",
    "babel-jest": "^26.6.3",
    "eslint": "^7.14.0",
    "jest": "^26.6.3",
    "metro-react-native-babel-preset": "^0.66.2",
    "prettier": "^2.7.1",
    "react-test-renderer": "17.0.2",
    "typescript": "^4.4.4"
  },
  "resolutions": {
    "@types/react": "^17"
  },
  "jest": {
    "preset": "react-native",
    "moduleFileExtensions": [
      "ts",
      "tsx",
      "js",
      "jsx",
      "json",
      "node"
    ]
  }
}

```

**Comment by lpinca** [comment]
I'm closing this. Discussion can continue if needed.
