### ISSUE TITLE
Provide a way to detect if a WebSocketServer is http or https

### ISSUE THREAD

**Issue by davidje13** [websockets/ws#2068]
### Is there an existing issue for this?

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Description

Currently, to connect to a server, it is necessary to know whether it is based on `http.Server` or `https.Server`:

```js
const s1 = new WebSocketServer();
const s2 = new WebSocketServer({ server: https.createServer(/*...*/) });

// later, after servers have started

const c1 = new WebSocket(`ws://localhost:${s1.address().port}`);
const c2 = new WebSocket(`wss://localhost:${s2.address().port}`);
```

In a test framework, this information may not be readily available by other means, so having the ability to get this information from the server itself is useful. For the core Node servers, it is possible to simply check `server instanceof https.Server` to find out, but WebSocketServer has no such distinction, and it exposes no official API for accessing the underlying server object (it is available as `._server` but this is presumably not guaranteed).

Please either add an API either to detect whether the server is using https as its transport, or more generally add a supported way to access the underlying `http(s).Server` instance being used.

### ws version

8.8.1

**Comment by lpinca** [comment]
> Please either add an API either to detect whether the server is using https as its transport, or more generally add a supported way to access the underlying http(s).Server instance being used.

See https://github.com/websockets/ws#external-https-server.

**Comment by davidje13** [comment]
@lpinca I'm aware that the passed in server can still be used independently by additionally keeping track of it outside the `ws` library, but I have seen a desire from one of my users to use the `WebSocketServer` as if it were the server itself. Since you already expose `address` and `close` in this library, I'm guessing that's at least a somewhat common way to use it? If so, being able to detect whether the server is http or https seems to be the only piece of information which isn't exposed this way at the moment (likely because it's done with `instanceof` checks rather than a delegatable method in the current NodeJS API).

**Comment by lpinca** [comment]
The info already available to users and `WebSocketServer` can also operate in `noServer` mode so it does not make much sense to me. As you wrote above you can use `websocketServer._server` or `websocketServer.options.server`.

**Comment by davidje13** [comment]
I hadn't realised that `websocketServer.options` existed. Yes, checking `websocketServer.options.server` would work fine for my needs, assuming it's supported? (it isn't mentioned in the documentation)

**Comment by lpinca** [comment]
It is not documented but I guess removing it would be a breaking change. Anyway, again, there is no reliable way to determine if `WebSocketServer` is backed by an HTTP or HTTPS server by only inspecting the `WebSocketServer` instance because it can operate in `noServer` mode.

FWIW, `websocketServer.address()` and `websocketServer.close()` were added only to handle the case where the server is internally created.

**Comment by davidje13** [comment]
OK, in that case I'll rely on the semi-supported `websocketServer.options.server` and if that isn't present, I'll assume it's internally created (which means it must be http since there is no option to create a https server)

In the case of `noServer` none of this matters anyway, since even `address()` will fail.
