### ISSUE TITLE
Messages coming through after connection is terminated

### ISSUE THREAD

**Issue by Borduhh** [websockets/ws#2069]
### Is there an existing issue for this?

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Description

We have some events where we are terminating the connection, but we are still getting messages via the WebSocket without reconnecting the device.

We utilize this for the ping/pong:
```ts
export const interval = setInterval(() => {
  wss.clients.forEach(async (ws) => {
    if (ws.isAlive === false) {
      await onWebsocketClose(ws.evse.id);

      Logger.log({
        type: 'server-websocket-disconnect',
        evseId: ws.evse.id,
        message: 'WebSocket timed out. No pong message received.',
      });

      ws.terminate();
      return;
    }

    ws.isAlive = false;
    ws.ping();
  });
}, 180000);
```

And this for the connection:
```ts
server.on('upgrade', async (req: express.Request, websocket: net.Socket, head: Buffer) => {
  const evseId = req.url.substr(1);

  Logger.log({
    type: 'websocket-connection-init',
    evseId,
    req, // TODO: Only log relevant data from the req
  });

   // other code

  wss.handleUpgrade(req, websocket, head, (websocketSession) => {
    wss.emit('connection', websocketSession, evse);
  });
});

```

```ts
wss.on('connection', async (ws, evse) => {
  // Close socket if there is no protocol per OCPP 1.6J spec (section 3.2)
  if (!ws.protocol) {
    ws.close(1002, 'Invalid WebSocket Protocol');
    return;
  }

  // Set socket status for ping/pong
  ws.isAlive = true;
});
```

And handlers for ping/pong:
```ts
  /**
   * Handle websocket pong messages
   */
  ws.on('pong', function heartbeat() {
    this.isAlive = true;
  });

  /**
   * Handle websocket ping messages
   */
  ws.on('ping', function pong() {
    ws.pong();
  });
```

However on occasion, we get the following sequence of events:

1:11 - `websocket-connection-init`
1:14 - `server-websocket-disconnect` <- Pong timeout
1:14 - `websocket-closed` via `ws.terminate()`
1:20 - websocket message
1:35 - websocket message

I was under the understanding that we should see another connection attempt before receiving any messages.

### ws version

7.5.7

### Node.js Version

16.15.1

### System

System:
    OS: macOS 12.4
    CPU: (10) arm64 Apple M1 Max
    Memory: 8.62 GB / 64.00 GB
    Shell: 5.8.1 - /bin/zsh

### Expected result

The device attempts to create a new connection before sending additional messages.

### Actual result

The device is sending messages even though there should not be a connection.

**Comment by lpinca** [comment]
`'message'` events can be emitted until the `'close'` event is emitted.

**Comment by Borduhh** [comment]
> 1:11 - `websocket-connection-init`
> 1:14 - `server-websocket-disconnect` <- Pong timeout
> 1:14 - `websocket-closed` via `ws.terminate()`
> 1:20 - websocket message
> 1:35 - websocket message

The `1:14 - `websocket-closed` via `ws.terminate()`` is the close event which is handled here:

```ts
ws.on('close', async (code: number, reason: string) => {
    await onWebsocketClose(ws.evse.id);

    Logger.log({
      type: ' websocket-closed',
      evseId: ws.evse.id,
      message: `Websocket closed. ${code} ${reason}`,
    });

    ws.terminate();
  });

/**
 * Processes a Websocket disconnect
 * @param {string} evseId The EVSE ID of the disconnected websocket
 */
const onWebsocketClose = async (evseId: string) => {
  socketConnections.delete(evseId);
  subscriber.unsubscribe(evseId);
};
```

**Comment by lpinca** [comment]
> We are sometimes receiving messages even hours after the close event happens

It doesn't make sense. When the `'close'` event is emitted the underlying socket is destroyed and all buffered data is read. Are you sure that the `'message'` events are coming from the same `WebSocket` instance?

Also calling `ws.terminate()` from a listener of the `'close'` event has no effect. It it a noop if the `WebSocket` is closed.

**Comment by Borduhh** [comment]
It is definitely bizarre. Here is just a sample of the logs where it is happening:

```
{"timestamp":"2022-07-25T05:11:33.225Z","level":"INFO","type":"websocket-connection-init","evseId":"LIV-112021-480-0123","service":"ocpp-websocket-server"}

{"timestamp":"2022-07-25T05:14:54.182Z","level":"INFO","type":"server-websocket-disconnect","evseId":"LIV-112021-480-0123","message":"WebSocket timed out. No pong message received.","service":"ocpp-websocket-server"}

{"timestamp":"2022-07-25T05:14:56.066Z","level":"INFO","type":" websocket-closed","evseId":"LIV-112021-480-0123","message":"Websocket closed. 1006 ","service":"ocpp-websocket-server"}

{"timestamp":"2022-07-25T05:20:01.853Z","level":"INFO","evseId":"LIV-112021-480-0123","ocppMessageId":"35315f1f-568f-42c7-93e0-ba66bd8ad9ba","ocppMessageAction":"Heartbeat","ocppMessagePayload":{},"service":"ocpp-websocket-server"}

{"timestamp":"2022-07-25T05:35:01.835Z","level":"INFO","evseId":"LIV-112021-480-0123","ocppMessageId":"8d12e1ee-51c5-4e10-89ca-467f4bddadae","ocppMessageAction":"Heartbeat","ocppMessagePayload":{},"service":"ocpp-websocket-server"}

{"timestamp":"2022-07-25T05:50:01.855Z","level":"INFO","evseId":"LIV-112021-480-0123","ocppMessageId":"72365474-780f-46b6-8dbd-ffc2912fe7c5","ocppMessageAction":"Heartbeat","ocppMessagePayload":{},"service":"ocpp-websocket-server"}
```

Even after we get the `websocket-closed` log inside the `close` handler:
```ts
ws.on('close', async (code: number, reason: string) => {

    Logger.log({
      type: ' websocket-closed',
      evseId: ws.evse.id,
      message: `Websocket closed. ${code} ${reason}`,
    });

    ws.terminate();
  });
```
the `message` handler continues to get called, which is where the `Heartbeat` logs are coming from:

```ts
 ws.on('message', async (message: string) => {
       // Other Code...

        Logger.ocppMessage({
          evseId: evse.id,
          ocppMessageId: messageId,
          ocppMessageAction: messageAction,
          ocppMessagePayload: messagePayload,
        });

    // Other code...
```

I thought at first that maybe the logs were just coming in weird, but it seems to be happening a decent amount. The event in our system which brought it to light was changing the PING interval from 1 minute to 3 minutes.

**Comment by lpinca** [comment]
Isn't it possible that the same `evseId` is assigned to multiple connections?

**Comment by Borduhh** [comment]
In theory, it is possible and I thought the same myself. We tested that by leaving that device off. No logs came through the system for a 24-hour period.

In addition, since the `websocket-connection-init` log is on the server upgrade listener, shouldn't we be seeing those in every scenario before receiving additional messages if a connection is terminated?

**Comment by lpinca** [comment]
> In addition, since the `websocket-connection-init` log is on the server upgrade listener, shouldn't we be seeing those in every scenario before receiving additional messages if a connection is terminated.

Yes, you should receive a `websocket-connection-init` log for every new connection, but there might be multiple active connections. My suggestion is to use an ID for the connection and also log that.

```js
wss.on('connection', function (ws) {
  ws.uuid = crypto.randomUUID();
});
```

**Comment by Borduhh** [comment]
Indeed that is what was going on. Are there any downsides to just force closing all outdated connections once a device reconnects?

**Comment by lpinca** [comment]
I don't know, it depends on the application. If old connections are just useless connections, I guess it is safe to close them.

**Comment by lpinca** [comment]
I'm closing this as completed.
