### ISSUE TITLE
Do not crash the program if `abortHandshake` is called

### ISSUE THREAD

**Issue by idinium96** [websockets/ws#2070]
### Is there an existing issue for this?

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Description

Repository: [TF2Autobot/tf2autobot](https://github.com/TF2Autobot/tf2autobot)

The `ws` was first use on [tf2autobot@4.5.0](https://github.com/TF2Autobot/tf2autobot/blob/935bda4ac7f0bc21d44eb67ad8679f9a14b36a76/package.json#L69), which uses **ws@7.5.5**.
It then got upgraded to **ws@8.2.3** starting on [tf2autobot@4.5.1](https://github.com/TF2Autobot/tf2autobot/blob/56fa73e00c8dd82cb3e5eed3fdeacfe0a02322a5/package.json#L70), and I keep it up-to-date until **ws@8.7.0** on [tf2autobot@4.13.1](https://github.com/TF2Autobot/tf2autobot/blob/7e4e66a1d8c27116066ef9fcfb3baa0e123efd11/package.json#L70)

During tf2autobot@4.5.1-4.13.1, a lot of people (including myself) were experiencing this issue, which randomly terminated the process:
![image](https://user-images.githubusercontent.com/47635037/182376074-7341ec28-01d1-4a27-ada2-38ddd2cff1a8.png)

After some digging, I've decided to downgrade `ws` to v7.5.8: https://github.com/TF2Autobot/tf2autobot/pull/1148 which was released to [tf2autobot@14.4.0](https://github.com/TF2Autobot/tf2autobot/blob/698c12ffaf992aff6db2a4d162381c8c72e46a9d/package.json#L70)

After that, the issue was fixed. The process never gets terminated again.

Then, on tf2autobot@5.0.0, `discord.js@13.6.0` was installed (which uses [ws@8.4.0](https://github.com/TF2Autobot/tf2autobot/blob/582f0e973e51e8ca7284d84ac4e2246496eb9fac/package-lock.json#L3997)), and the issue seems to have come back to live (the same issue, but this time it comes from discord.js):
![image](https://cdn.discordapp.com/attachments/666909760666468377/1003977196106416158/unknown.png)

I think this is the cause of this issue (which started somewhere on ws@8.x.x):
https://github.com/websockets/ws/blob/975382178f8a9355a5a564bb29cb1566889da9ba/lib/websocket.js#L1063

There is also an issue still open on the `discord.js` repository:
https://github.com/discordjs/discord.js/issues/8199

I might be wrong, but v7.5.9 works just fine.

### ws version

8.x.x

### Node.js Version

16.16.0

### System

```
 System:
    OS: Linux 5.13 Ubuntu 20.04.4 LTS (Focal Fossa)
    CPU: (2) x64 AMD EPYC 7551 32-Core Processor
    Memory: 396.11 MB / 966.14 MB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
```

### Expected result

Just throw in the `error` event, not terminate the process.

### Actual result

_See screenshots in the description._

### Attachments

_See screenshots in the description._

**Comment by lpinca** [comment]
Make sure that the listener for the `'error'` event is not removed before the `'close'` event is emitted. For example, don't do this:

```js
const ws = new WebSocket('wss://websocket-echo.com');

ws.on('error', console.error);
ws.close();
ws.removeListener('error', console.error);
```

**Comment by lpinca** [comment]
I'm closing this as answered. Happy to continue the discussion in the closed thread if needed.
