### ISSUE TITLE
Expose request headers

### ISSUE THREAD

**Issue by johnwchadwick** [websockets/ws#2073]
### Is there an existing issue for this?

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Description

I'd like to be able to get the verbatim request headers for diagnostic purposes, but today I don't see anywhere in the API surface where this can be intercepted. It would be very useful to have an additional API or event for this.

### Node.js Version

v16.14.2

### System

```
  System:
    OS: Linux 5.19 Arch Linux
    CPU: (8) x64 Intel(R) Core(TM) i7-10610U CPU @ 1.80GHz
    Memory: 10.30 GB / 15.26 GB
    Container: Yes
    Shell: 5.9 - /usr/bin/zsh
```

### Expected result

N/A

### Actual result

N/A

**Comment by lpinca** [comment]
```js
server.on('connection', function (websocket, request) {
  console.log(request.headers);
});
```

**Comment by johnwchadwick** [comment]
Thanks for the quick response! Apologies, I realize now that I've made my feature request ambiguous. I meant with reference to the WebSocket client, not the server. That is, the ability to see the actual complete request headers that it sends.

**Comment by lpinca** [comment]
You can use

```js
const ws = new WebSocket(url);

ws._req.getHeaders();
```

but I would prefer to not turn this into an officially supported API.

**Comment by johnwchadwick** [comment]
Fair enough. I appreciate the fast responses.
