### ISSUE TITLE
Question: Set headers for handshake

### ISSUE THREAD

**Issue by MijikHna** [websockets/ws#2074]
### Is there an existing issue for this?

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Description

I couldn't find in the documentation, how I can set headers for handshake in `WebSocket` client class. Could you please provide provide an example where you set headers in WebSocket class.

### ws version

8.5.0

### Node.js Version

18.8.0

**Comment by lpinca** [comment]
See https://github.com/websockets/ws/blob/8.8.1/doc/ws.md#new-websocketaddress-protocols-options

> Any other option allowed in [http.request()](https://nodejs.org/api/http.html#http_http_request_options_callback) or [https.request()](https://nodejs.org/api/https.html#https_https_request_options_callback)

```js
const ws = new WebSocket(url, {
  headers: { foo: 'bar' }
});
```

**Comment by lpinca** [comment]
I'm closing this as answered.
