### ISSUE TITLE
websocket.send does not allow object but docs state that it does

### ISSUE THREAD

**Issue by DLiblik** [websockets/ws#2076]
### Is there an existing issue for this?

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Description

The documentation on the repo states that:

> ### websocket.send(data[, options][, callback])
> - data {Array|Number|Object|String|ArrayBuffer|Buffer|DataView|TypedArray} The data to send.

https://github.com/websockets/ws/blob/master/doc/ws.md?plain=1#L556

...but the code only supports text or binary:

https://github.com/websockets/ws/blob/master/lib/websocket.js#L429

This one went :boom: for us when a developer decided to pass an error structure response (basically a POJO or simple hash) for a rare error and 3 months later, the error occurred and brought down a prod server... our miss on testing coverage 😆 of course but either the docs or the code should change.

### ws version

8.8.1

### Node.js Version

v14.18.2

### Expected result

Docs and code to match

### Actual result

Docs and code do not match, and a TypeError throws from `.send`

**Comment by lpinca** [comment]
You can use an object as described here https://nodejs.org/api/buffer.html#static-method-bufferfromobject-offsetorencoding-length.

**Comment by DLiblik** [comment]
Yes, I understand that (since the call stack that brought down our server traced the TypeError back to "Buffer.from".  But your internal implementation should be opaque to the client's code that calls it.

So I'd still at least modify the documentation then to indicate that your requirement for "Object" is one that supports those requirements (kind of like node does), or at least "Object is only supported if it conforms to the requirements of Buffer.from for your version of node, as documented in https://nodejs.org/api/buffer.html#static-method-bufferfromobject-offsetorencoding-length ).

**Comment by lpinca** [comment]
> Object is only supported if it conforms to the requirements of Buffer.from for your version of node, as documented in https://nodejs.org/api/buffer.html#static-method-bufferfromobject-offsetorencoding-length

Yes it makes sense. All supported Node.js versions since ws@8 only supports Node.js 10 or newer. Feel free to update your PR.

**Comment by DLiblik** [comment]
@lpinca Ok, I restored Object and added further clarification in https://github.com/DLiblik/ws/commit/37e53206cd741c6f1c5900e9e5c4f04d25d499b6

**Comment by JohannCooper** [comment]
@lpinca 
Is there a reason why the JSDoc doesn't limit the type of `data` to be compatible with `Buffer.from` as opposed to currently throwing a `TypeError` in `send`? I'm using TypeScript and it would be super nice to have narrower typing for `data`.

**Comment by whisdev** [comment]
Really great!

I need to fetch transaction confirmateion time as well when use this in Helius Advanced Web socket?
Any advice!!!
