### ISSUE TITLE
[Query] Is it possible to return an error message when the websocket upgrade is rejected

### ISSUE THREAD

**Issue by Sid200026** [websockets/ws#2080]
### Is there an existing issue for this?

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Description

Before upgrading an http connection to websocket, we might reject the connection based on certain policies. In such cases, we would like to send the reason of rejection along with a correlation Id. Currently we are being able to send the http status code using the following snippet, but the corrId is not visible from the client side.

```ts
socket.write('HTTP/1.1 429 Too Many Requests\r\n\r\n');
socket.write(`Corr Id: ${corrId} \r\n`);
socket.destroy();
```

### ws version

v8.5.0

### Node.js Version

v16.16.0

### System

  System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
    Memory: 18.66 GB / 31.71 GB

### Expected result

NA

### Actual result

NA

### Attachments

NA

**Comment by lpinca** [comment]
In `ws` you can use the [`'unexpected-response'`](https://github.com/websockets/ws/blob/master/doc/ws.md#event-unexpected-response) event. In the browser, as far as I know, there is no way to read the response body.

**Comment by Sid200026** [comment]
I tried returning messages from the server using the following
```
socket.write('HTTP/1.1 429 Too Many Requests\r\n\r\n');
socket.write(`Corr Id: ${corrId} \r\n`);
socket.destroy();
```

and then read the `unexpected-response` event from the nodejs client. However I was unable to read this message `Corr Id: ${corrId}` from the response.

Do you have any code snippets or example on how to do it.

**Comment by lpinca** [comment]
```js
import http from 'node:http';
import WebSocket from 'ws';

const server = http.createServer();

server.on('upgrade', function (request, socket) {
  socket.write('HTTP/1.1 429 Too Many Requests\r\n\r\n');
  socket.write('Corr Id: 123 \r\n');
  // Using `socket.end()` or
  // `socket.once('finish', socket.destroy); socket.end()` might be better
  // to ensure that the data is written.
  socket.destroy();
});

server.listen(function () {
  const { port } = server.address();
  const ws = new WebSocket(`ws://localhost:${port}`);

  ws.on('unexpected-response', function (request, response) {
    response.setEncoding('utf-8');

    response.on('data', function (chunk) {
      process.stdout.write(chunk);
    });

    response.on('end', function () {
      server.close();
    });
  });
});
```
