### ISSUE TITLE
[Query] How to add certificate options in a websocket client connecting to a websocket server on C++

### ISSUE THREAD

**Issue by ameeakshay** [websockets/ws#2081]
### Is there an existing issue for this?

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Description

Hi,

I am currently trying to connect using wss to my existing websocket server on C++, with a verified self signed certificate.
My query is, in order for me to connect to this server, is there a way to enter the client certificate details as shown below, and if so where can I get more information about these options::

const ws = new WebSocket(`wss://localhost:3000}`, {
          cert: fs.readFileSync('demo/cert.pem'),
          key: fs.readFileSync('demo/key.pem'),
          rejectUnauthorized: false
        });
        
Moreover, here I am using a secured key, so I would need to enter a passphrase as well, is there any option for that as well, I tried checking the docs for the repo but couldnt find it anywhere..
thanks!!
        

### ws version

8.4.0

### Node.js Version

v16.13.0

### System

 OS: Windows 10 10.0.19042
 CPU: (8) x64 Intel(R) Core(TM) i5-10310U CPU @ 1.70GHz
 Memory: 3.42 GB / 15.76 GB

### Expected result

NA

### Actual result

NA

**Comment by lpinca** [comment]
See https://github.com/websockets/ws/blob/8.9.0/doc/ws.md#class-websocket

> Any other option allowed in [`http.request()`](https://nodejs.org/api/http.html#http_http_request_options_callback) or [`https.request()`](https://nodejs.org/api/https.html#https_https_request_options_callback)

**Comment by ameeakshay** [comment]
Thanks a lot!! it worked by using options based on https.request()
