### ISSUE TITLE
Right-hand side of 'instanceof' is not an object     at initAsClient (websocket.js:666:1)

### ISSUE THREAD

**Issue by samarawallet** [websockets/ws#2084]
### Is there an existing issue for this?

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Description
 
Error Message Recieved when attempting to instantiate the WebSocket object
```
App.vue?b341:204 TypeError: Right-hand side of 'instanceof' is not an object
    at initAsClient (websocket.js:666:1)
```

Code used:

```
// Connect to websocket server running on port 50020. Tested working with other tool
const webSocket = new WebSocket("wss://url-to-domain:50020/");
```

### ws version

8.9.0

### Node.js Version

v16.13.0

### System

  System:
    OS: macOS 12.0
    CPU: (10) arm64 Apple M1 Pro
    Memory: 1.19 GB / 16.00 GB
    Shell: 5.8 - /bin/zsh

### Expected result

Expected websocket to connect correctly

### Actual result

Error thrown in the console: 
 
```
App.vue?b341:204 TypeError: Right-hand side of 'instanceof' is not an object
    at initAsClient (websocket.js:666:1)
```

**Comment by sami4064** [comment]
I am facing the same problem. Any solution?

**Comment by lpinca** [comment]
It's not an issue in ws, you have to find out what `URL` is in environment. I don't know.

**Comment by sami4064** [comment]
I was getting error:
`error - ./node_modules/ws/lib/sender.js:5:0
Module not found: Can't resolve 'net'`
So I added 'net' as dependency and started getting 'instanceof' error

**Comment by lpinca** [comment]
Are you are trying to run in the browser? ws does not work in the browser.

**Comment by samarawallet** [comment]
>Are you are trying to run it in the browser? ws does not work in the browser.

Yes, trying to run it in a browser extension.

Is there any way to force or hack it to work in a web browser?  Thanks in advance!

**Comment by lpinca** [comment]
No, you have to use the native [`WebSocket` object](https://developer.mozilla.org/en-US/docs/Web/API/WebSocket).
