### ISSUE TITLE
how to stream utf8 string

### ISSUE THREAD

**Issue by beilunyang** [websockets/ws#2085]
### Is there an existing issue for this?

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Description

According to the document, i can createWebSocketStream, and set the utf8 encoding.
I did this, but my client still receive the binary messages.
```javascript
const duplex = WebSocket.createWebSocketStream(ws, {encoding: 'utf8'});
const stream = require('fs').createReadStream(pathToFile, {encoding: 'utf8'});
stream.pipe(duplex);
```
Is this a bug?  how can I stream it as utf8?

### ws version

8.9.0

### Node.js Version

16.17.0

### System

```
  System:
    OS: Windows 10 10.0.19044
    CPU: (12) x64 AMD Ryzen 5 2600 Six-Core Processor
    Memory: 7.50 GB / 15.93 GB
```

### Expected result

client receive the utf8 text messages

### Actual result

client still receive the binary messages

### Attachments

![1664880250608](https://user-images.githubusercontent.com/13795713/193799922-9c2157e3-4c73-4bd9-9f14-739540dcf035.png)

**Comment by lpinca** [comment]
Set the `decodeStrings` option to `false`. See https://nodejs.org/api/stream.html#new-streamwritableoptions.

**Comment by beilunyang** [comment]
> Set the `decodeStrings` option to `false`. See https://nodejs.org/api/stream.html#new-streamwritableoptions.

Solved, thanks
