### ISSUE TITLE
[feat] `open` event for compactibility

### ISSUE THREAD

**Issue by loynoir** [websockets/ws#2086]
### Is there an existing issue for this?

- [X] I've searched for any related issues and avoided creating a duplicate issue.

Related https://github.com/websockets/ws/issues/2011

### Description

https://deno.land/manual@v1.26.0/runtime/http_server_apis_low_level#serving-websockets

Within `deno`, websocket server does have `open` event, which like `ws` `connection` event.

According to my memory, also support `websocketServer.addEventListener('open', ...)`

Can we have that in `ws` for compactibility?

Maybe just an use as alias for `ws` backward compactibility.

```ts
  if (pathname === '/foo') {
    wss1.handleUpgrade(request, socket, head, function done(ws) {
      wss1.addEventListener('open', ...)
      wss1.emit('connection', ws, request);
    });
  } 
```

### ws version

8.9.0

### Node.js Version

18.10.0

**Comment by lpinca** [comment]
`deno` API is different. `ws` API is modelled against the [`net.Server`](https://nodejs.org/api/net.html#event-connection) API. When the `'connection'` event is emitted the WebSocket ready state is `OPEN` so it does not make sense to emit the `'open'` event. Your `'open'` event is the `'connection'` event itself or the `websocketServer.handleUpgrade()` callback.

The `'open'` event is actually emitted when [`websocket.setSocket()`](https://github.com/websockets/ws/blob/8.9.0/lib/websocket-server.js#L415-L418) is called, but the `Websocket` object is exposed to the user right after that.

If you really need it you can reemit it

```js
wss.handleUpgrade(request, socket, head, function done(ws) {
  wss.emit('connection', ws, request);
  ws.emit('open');
});
```

but again, it does not make sense in my opinion.
