### ISSUE TITLE
in Docs:  replace "%s" with .toString()

### ISSUE THREAD

**Issue by respectabiggle** [websockets/ws#2087]
### Is there an existing issue for this?

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Description

Sorry if this is the wrong place to post this suggestion.  

In the Docs, a lot of Usage Examples use %s.  

I feel like that is not a well-known method, whereas most people are familiar with .toString().  Even google had trouble with "javascript %s".

Maybe examples could be given in the docs for using both/either methods?
And perhaps an explanation that %s is shorthand convention for .toString()

Hope this helps somebody !

### ws version

8.9.0

### Node.js Version

16.15.0

### System

    OS: Windows 10 10.0.19044

**Comment by lpinca** [comment]
This is well documented. See https://developer.mozilla.org/en-US/docs/Web/API/console#using_string_substitutions

**Comment by lpinca** [comment]
It is a `console.log()` feature. If I did not know I would just read the documentation, just like I would do for `toString()` if I did not know about its existence.

**Comment by respectabiggle** [comment]
Yes I see my misunderstanding.  Thank you for clarifying.  I will close the issue.
