### ISSUE TITLE
Custom Header For WSS Request

### ISSUE THREAD

**Issue by avi0786** [websockets/ws#2089]
### Is there an existing issue for this?

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Description

I am trying to set header to handshake response.
My use-case is to create a webSocket proxy server.
**Client A** sends a WebSocket request to **Server B** and then after some modification to headers and data **server B** Create a new WSS connection to **server C**.
So how can i send the same headers received from **server C** to **client A**. 
Is there any way to do this.

### ws version

8.8.0

### Node.js Version

v16.16.0

### System

 OS: macOS 12.6
    CPU: (10) arm64 Apple M1 Pro
    Memory: 175.20 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh

**Comment by lpinca** [comment]
See https://github.com/websockets/ws/blob/8.9.0/doc/ws.md#event-headers.

**Comment by avi0786** [comment]
Is this async , because we have to wait till we get the headers from the **server C**

**Comment by lpinca** [comment]
No, it is not but if server B has to wait the response of server C before it can send the response.

**Comment by avi0786** [comment]
Then how can we modify the handshake response header, after  doing some async task

**Comment by lpinca** [comment]
You just don't send the response from server B. When server B has the all the response data you send the response.

**Comment by avi0786** [comment]
The webSocket Server is automatically sending the default response headers.

**Comment by lpinca** [comment]
Then you can't do much. You can't change headers after they are sent.

**Comment by avi0786** [comment]
There is no way we can do this?  Or we need to handle socket connection request by own, there we can modify response headers.

**Comment by lpinca** [comment]
See https://github.com/websockets/ws/issues/2089#issuecomment-1283798016

If you don't control Server B you can't do this.

**Comment by avi0786** [comment]
Yes we control the server B, but we don't have control over the we socket response headers, when they are sent to client.

**Comment by lpinca** [comment]
Assuming that server B is using `ws`, you have to do something like this https://github.com/websockets/ws#client-authentication. Replace `autenticate()` with connection to server C and use https://github.com/websockets/ws/blob/8.9.0/doc/ws.md#event-headers.
