### ISSUE TITLE
cannot send raw object with send()

### ISSUE THREAD

**Issue by ORESoftware** [websockets/ws#2093]
### Is there an existing issue for this?

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Description

Just trying to send a raw object with the send() method.

maybe we could add a sendRaw method that can run JSON stringify for us:

```js
send(data, options, cb) => void

sendRaw(data,options,cb) => {
  data = typeof data === 'string' ? data : JSON.stringify(data);
  return this.send(data, options, cb);
}
```

or perhaps just to keep things utterly consistent:

```js
send(data, options, cb) => void

sendRaw(data,options,cb) => {
  return this.send(JSON.stringify(data), options, cb);
}
```

### ws version

latest

### Node.js Version

18

**Comment by lpinca** [comment]
Yes this is documented. https://github.com/websockets/ws/blob/8.11.0/doc/ws.md#websocketsenddata-options-callback

> maybe we could add a sendRaw method that can run JSON stringify for us.

No, please do it in your code / application before calling `websocket.send()`. We could call `object.toString()` and send the resulting string like browsers do, but I think there is no added value.

**Comment by lpinca** [comment]
I'm closing this as answered.
