### ISSUE TITLE
what's meaning of error reason - 2

### ISSUE THREAD

**Issue by alanhg** [websockets/ws#2095]
### Is there an existing issue for this?

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Description

websocket.onerror return `{"reason":2}`

I used WebSocket contains httpAgent.
![image](https://user-images.githubusercontent.com/9245110/202552242-b6aea169-9900-4a61-a235-c82723d74425.png)

![image](https://user-images.githubusercontent.com/9245110/202551726-81ad4e8a-3012-4ae2-ab60-d5a5b0bdf5ac.png)

![image](https://user-images.githubusercontent.com/9245110/202552213-19452055-d82d-476c-ad89-b6f767ee55f6.png)

I want to know what's meaning?

### ws version

8.10.0

### Node.js Version

14.18.0

### System

System:
    OS: macOS 11.7
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 50.09 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh

### Expected result

exact error info or no error

### Actual result

{"reason":2}

### Attachments

![image](https://user-images.githubusercontent.com/9245110/202552393-b760d59b-c036-4620-ad6d-500d8f64f358.png)

**Comment by lpinca** [comment]
I don't know. That error is not coming from `ws`. I guess it is raised by your `httpAgent`.

**Comment by alanhg** [comment]
> I don't know. That error is not coming from `ws`. I guess it is raised by your `httpAgent`.

OK，thank you.
