### ISSUE TITLE
no "open", "listen" or "listening" event

### ISSUE THREAD

**Issue by ORESoftware** [websockets/ws#2096]
### Is there an existing issue for this?

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Description

```js
const server = ws.WebSocketServer(serverConfig);

server.once('listening', () => {
    console.log('server listening on interface:', serverConfig);
});

server.once('listen', () => {
    console.log('server listening on interface:', serverConfig);
});

server.once('open', () => {
    console.log('server listening on interface:', serverConfig);
});
```

none of these events exist, what is the name of the relevant one??

**Comment by ORESoftware** [comment]
nvm, looks like "listening" exists

**Comment by alexandrzavalii** [comment]
`listening` event is never fired for me in `"ws": "8.11.0"`
