### ISSUE TITLE
No way to access underlying socket?

### ISSUE THREAD

**Issue by ORESoftware** [websockets/ws#2097]
### Is there an existing issue for this?

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Description

There doesn't seem to be a way to access the underlying _socket_ for a websocket connection?

See my question:
https://stackoverflow.com/questions/74484801/access-socket-ref-to-pass-to-child-process

**Comment by lpinca** [comment]
You can use `websocket._socket` but that is undocumented and not officially supported.
