### ISSUE TITLE
ws.emit() is not working

### ISSUE THREAD

**Issue by jenkey2011** [websockets/ws#2099]
### Is there an existing issue for this?

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Description

```js
const express = require('express');
const {WebSocketServer} = require('ws');
const app = express();

const wsServer = new WebSocketServer({ port: 3001 });
wsServer.on('connection', socket => {
  socket.on('message', message => {
    socket.send('msg ===  123')
  });
  socket.on('aaaaaaaaaaaa', message => {
    socket.send('send === 123')
  });
});

app.get('/aaa', (req, res) => {
  wsServer.emit('aaaaaaaaaaaa', req )
  res.send('Hello Word~')
})
```

### ws version

8.11.0

### Node.js Version

14.20.1

### System

  System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 419.59 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh

### Expected result

``` socket.send('send === 123')```

### Actual result

``` socket.send('send === 123')``` not working

### Attachments

no~

**Comment by lpinca** [comment]
You are emitting the event on `wsServer` so the listener should be added to `wsServer` not `socket`.

**Comment by lpinca** [comment]
I'm closing this as answered.
