### ISSUE TITLE
Socket Hang Up, causing the Node server to crash.

### ISSUE THREAD

**Issue by KrishnaFlutura** [websockets/ws#2101]
### Is there an existing issue for this?

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Description

Hello,

I have two Node servers, 
1st being the Data Server, running the WebSocket Server which reads data from DB and returns response and
2nd being the client which makes requests to the Data Server, (1st one) and consumes the response.

The code on Client Server (2nd machine) is something like:

```
// app.js
const express = require('express');
  
const app = express();
const PORT = 5000;

app.get('/', (req, res)=>{
    res.status(200);
    res.send("Welcome to root URL of Server");
});

var server = require('http').createServer(app);
var WebSocketServer = require('websocket').server;
var WebSocket = require('ws');

wsServer = new WebSocketServer({
    httpServer: server,
    maxReceivedFrameSize :10 * 1024 * 1024,
    maxReceivedMessageSize: 10 * 1024 * 1024,
    keepaliveGracePeriod: 9000000
});

try {
    var x = new WebSocket("ws://localhost:8081/vs");
} catch (error) {
    console.log("asdasds",error)
}

app.listen(PORT, (error) =>{
    if(!error)
        console.log("Server is Successfully Running,  and App is listening on port "+ PORT)
    else 
        console.log("Error occurred, server can't start", error);
    }
);
```

`
// Package.json
{
  "name": "express",
  "version": "1.0.0",
  "description": "",
  "main": "app.js",
  "dependencies": {
    "express": "^4.18.2",
    "websocket": "^1.0.34",
    "ws": "^8.11.0"
  },
  "devDependencies": {},
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC"
}
`

The problem I am facing is, sometimes my Data server is down/not running.
That time websocket connection from Server 1 fails and gives and error saying:

```
D:\temp\websocketAppExp>node app.js
Server is Successfully Running,  and App is listening on port 5000
events.js:377
      throw er; // Unhandled 'error' event
      ^

Error: socket hang up
    at connResetException (internal/errors.js:639:14)
    at Socket.socketOnEnd (_http_client.js:499:23)
    at Socket.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1333:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
Emitted 'error' event on WebSocket instance at:
    at emitErrorAndClose (D:\temp\websocketAppExp\node_modules\ws\lib\websocket.js:1002:13)
    at ClientRequest.<anonymous> (D:\temp\websocketAppExp\node_modules\ws\lib\websocket.js:854:5)
    at ClientRequest.emit (events.js:400:28)
    at Socket.socketOnEnd (_http_client.js:499:9)
    at Socket.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1333:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  code: 'ECONNRESET'
}

How to make sure the error is handled and not crashing the server?
```

### ws version

^8.11.0

### Node.js Version

14.20.0

### System

npx: installed 1 in 3.246s

  System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz
    Memory: 6.53 GB / 15.77 GB

### Expected result

Server should not crash

### Actual result

Server is crashing.

**Comment by lpinca** [comment]
Add a listener for the `'error'` event.

```js
const ws = new WebSocket(url);

ws.on('error', console.error);
```

That `try...catch` in your code is useless. The `'error'` event is emitted asynchronously.
