### ISSUE TITLE
try  to receiving text data  but get "buffer"

### ISSUE THREAD

**Issue by yiguxianyun** [websockets/ws#2108]
### Is there an existing issue for this?

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Description

Dear ws developer：
i use this👇

ws.on('message', function message(data) {
  console.log('received: %s', data);
});

and then  i get "buffer"……why?
thanks a lot

### ws version

8.11.0

### Node.js Version

v18.12.1

### System

    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
    Memory: 9.93 GB / 15.84 GB

### Expected result

get text

### Actual result

buffer

### Attachments

<Buffer 7b 22 73 6b 65 74 63 68 75 70 22 3a 22 6b 6b 79 79 22 7d>

**Comment by lpinca** [comment]
See https://github.com/websockets/ws/blob/8.11.0/doc/ws.md#event-message. You always get a `Buffer`. The `isBinary` argument of the `'message'` event listener tells you whether the message is binary or not. To get a string use `data.toString()`.

**Comment by yiguxianyun** [comment]
thank you very much!

**Comment by x-yuri** [comment]
Is there a reason to return a buffer for text data? It made me think, "Am I doing it wrong? Why am I receiving a buffer?" Returning a string seems like a better option from a user perspective.

> The opcode field defines how to interpret the payload data: 0x0 for continuation, 0x1 for text (which is always encoded in UTF-8)

https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API/Writing_WebSocket_servers#format

**Comment by lpinca** [comment]
@x-yuri see https://github.com/websockets/ws/commit/e173423c180dc1e4e6ee8938d9e4376a7a8b9757
