### ISSUE TITLE
Add support for buffer.isUtf8

### ISSUE THREAD

**Issue by JMTK** [websockets/ws#2110]
### Is there an existing issue for this?

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Description

New feature in Node 19.4:
https://nodejs.org/dist/latest-v19.x/docs/api/buffer.html#bufferisutf8input

Tested it locally doing something like this. I haven't fully performance tested. I can open a PR if you're open to the idea
```js
const buffer = require('node:buffer');
// ...
/* istanbul ignore else  */
if (!process.env.WS_NATIVE_UTF8_VALIDATE && typeof buffer.isUtf8 === 'function') {
  try {
    console.log("Using native Utf8!");
    module.exports.isValidUTF8 = buffer.isUtf8;
  } catch (e) {
    // Continue regardless of the error.
  }
}
else if (!process.env.WS_NO_UTF_8_VALIDATE) {
  try {
    const isValidUTF8 = require('utf-8-validate');

    module.exports.isValidUTF8 = function (buf) {
      return buf.length < 150 ? _isValidUTF8(buf) : isValidUTF8(buf);
    };
  } catch (e) {
    // Continue regardless of the error.
  }
}
```
and it seemed to work ok

### ws version

8.11.0

### Node.js Version

19.4.0

### System

N/A

### Expected result

N/A

### Actual result

N/A

### Attachments

Testing on my Discord bot
![image](https://user-images.githubusercontent.com/877114/211077305-236f4e1a-2dbf-4363-9eb4-46e1af1823c5.png)

Ran all tests:
![image](https://user-images.githubusercontent.com/877114/211078263-75b26816-af06-4eb9-a5c9-87da37becef0.png)

**Comment by lpinca** [comment]
Yes, I will add it soon. See https://github.com/websockets/utf-8-validate/pull/101#issuecomment-1361406145 for benchmarks. `Buffer.isUtf8()` has the same performance of `utf-8-validate@6`.
