### ISSUE TITLE
Can we send header in the response before websocket upgrade?

### ISSUE THREAD

**Issue by sauravlikhar** [websockets/ws#2111]
### Is there an existing issue for this?

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Description

I want to know if there is any way we can send some data in the response header to the client. I found [this](https://github.com/websockets/ws/blob/master/doc/ws.md#event-headers) but it only sends header in case when socket is ready to be upgraded and not when we do not want to upgrade the socket.

In more detail - 
I have a files server.ts with below implementation

// server.ts
```
import http from 'http';
import { WebSocketServer } from 'ws';

const httpServer = http.createServer(async (_, response) => {
    response.setHeader('somedata','anydata');
    response.end("server created");
});
httpServer.listen(5000);

const wsServer = new WebSocketServer({ noServer: true, path: '/ws'});

httpServer.on('upgrade', async (request,socket, head)=>{
    const reqUrl = new URL('http://localhost' + request.url);
    let val = JSON.parse(reqUrl.searchParams.get('cap')!);
    let something = "something";
    if(val[somthing]!=="abc"){
        socket.end(()=>{
            console.log("closing client tcp socket");
        })
    }
    await upgradeConnection(request,socket, head);
})

async function upgradeConnection(request: http.IncomingMessage,socket: any, head: Buffer){
    wsServer.handleUpgrade(request,socket, head,ws =>{
        wsServer.emit('connection',ws,request);
    })
}

let mydata = "someid"
let MY_HEADER= 'mydata: ${mydata}';

wsServer.on('headers', (headers,request)=>{
    headers.push(MY_HEADER);
})

wsServer.on('connection', async (clientSocket, request)=>{
    clientSocket.on('error', error => {
        console.log(error);
    });
    clientSocket.on('close', ()=>{
        console.log('closing client connection');
    })
})
```

When I hit the ws url `ws://127.0.0.1:5000/ws?cap={"something":"abc"}` , I can see in response that MY_HEADER value is present.
But if I hit the ws url `ws://127.0.0.1:5000/ws?cap={"something":"something"}`, there is no response header.

I also hit the localhost:5000 from the browser and there I got header "somedata:anydata" in response.

In my use case, I want to send the data in the header to the client when he hits the websocket url. The data contains the id of the request which will be generated after http create server so I cant use http response header of the create server as shown above.

Is there any way we can send the id data in the response header to the client on both successful and unsuccessful upgrades?

**Comment by lpinca** [comment]
There are two ways:

1. Write the HTTP response (including the headers) yourself to the socket in the `'upgrade'` event like you are doing in the example.
2. Use the [`verifyClient`](https://github.com/websockets/ws/blob/8.12.0/doc/ws.md#new-websocketserveroptions-callback) hook.

**Comment by lpinca** [comment]
## Option 1

```js
const assert = require('assert');
const http = require('http');
const server = http.createServer();
const url = require('url');
const { WebSocketServer } = require('ws');

const wss = new WebSocketServer({ noServer: true });

wss.on('connection', function (websocket, request) {
  // ...
});

server.on('upgrade', function (request, socket, head) {
  const ok = url.parse(request.url, true).query.ok === '1';

  if (!ok) {
    socket.end(
      `HTTP/1.1 401 ${http.STATUS_CODES[401]}\r\n` + 'foo: bar\r\n\r\n'
    );
    return;
  }

  wss.handleUpgrade(request, socket, head, function (websocket) {
    wss.emit('connection', websocket);
  });
});

server.listen(function () {
  const req = http.get({
    port: server.address().port,
    headers: {
      Connection: 'Upgrade',
      Upgrade: 'websocket',
      'Sec-WebSocket-Key': 'dGhlIHNhbXBsZSBub25jZQ==',
      'Sec-WebSocket-Version': 13
    }
  });

  req.on('response', (response) => {
    assert.strictEqual(response.headers.foo, 'bar');
    response.resume();
    server.close();
  });
});
```

## Option 2

```js
const assert = require('assert');
const http = require('http');
const url = require('url');
const { WebSocketServer } = require('ws');

function verifyClient({ req: request }, callback) {
  const ok = url.parse(request.url, true).query.ok === '1';

  if (!ok) {
    callback(false, 401, http.STATUS_CODES[401], { foo: 'bar' })
  } else {
    callback(ok);
  }
}

const wss = new WebSocketServer({ port: 0, verifyClient }, function () {
  const req = http.get({
    port: wss.address().port,
    headers: {
      Connection: 'Upgrade',
      Upgrade: 'websocket',
      'Sec-WebSocket-Key': 'dGhlIHNhbXBsZSBub25jZQ==',
      'Sec-WebSocket-Version': 13
    }
  });

  req.on('response', (response) => {
    assert.strictEqual(response.headers.foo, 'bar');
    response.resume();
    wss.close();
  });
});

wss.on('connection', function (websocket, request) {
  // ...
});
```

**Comment by lpinca** [comment]
I'm closing this as answered.

**Comment by sauravlikhar** [comment]
Hi @lpinca,
We used the same technique as you suggested in method 1. We found out that on hitting the server with lot of requests(>1000), after some number of successful request all the requests are getting error of  `<ws error> error Parse Error: Header overflow`

We saw that the response header contains the header value 'ok:1' multiple times. I guess it is because of headers.push method in on('header') event handler.

**Comment by lpinca** [comment]
> I guess it is because of headers.push method in on('header') event handler.

Each connection emits its own `'headers'` event with its own [`headers`](https://github.com/websockets/ws/blob/8.12.0/lib/websocket-server.js#L375-L380) so it shouldn't be possible.

Do you have a minimal reproducible test case?

**Comment by sauravlikhar** [comment]
I found the issue - 

Here is the server.ts file -
```
import http from 'http';
import { WebSocketServer } from 'ws';

const httpServer = http.createServer(async (_, response) => {
    response.end("server created");
});
httpServer.listen(5000);

const wsServer = new WebSocketServer({ noServer: true, path: '/ws'});

httpServer.on('upgrade', async (request,socket, head)=>{
    const reqUrl = new URL('http://localhost' + request.url);
    let val = JSON.parse(reqUrl.searchParams.get('cap')!);
    let something = "something";
    if(val[somthing]!=="abc"){
        socket.write("HTTP/1.1 429 Too Many Requests\r\n");
        socket.write(`mydata1: ${mydata}\r\n\r\n`);
        socket.write(`Sorry, request terminated\r\n`);
        socket.end(()=>{
            console.log("end");
        })
    }
    await upgradeConnection(request,socket, head);
})

async function upgradeConnection(request: http.IncomingMessage,socket: any, head: Buffer){
    wsServer.on('headers', (headers,request)=>{
        headers.push(MY_HEADER);
    })
    wsServer.handleUpgrade(request,socket, head,ws =>{
        wsServer.emit('connection',ws,request);
    })
}

let mydata = "someid"+Math.random();
let MY_HEADER= 'mydata: ${mydata}';

wsServer.on('connection', async (clientSocket, request)=>{
    clientSocket.on('error', error => {
        console.log(error);
    });
    clientSocket.on('close', ()=>{
        console.log('closing client connection');
    })
})
```

When I am declaring "on headers" event inside upgradeConnection method, the requests after first one are getting multiple headers of same name. 
![image](https://user-images.githubusercontent.com/85556281/213442987-92e55e5a-2a35-4e95-ab96-ecefa221218a.png)

But if I am declaring "on headers" event outside of upgradeConnection method, all the requests are getting only one response header.
![image](https://user-images.githubusercontent.com/85556281/213443477-2218ffaf-07d4-4bda-9500-5ad66c9f38c1.png)

**Comment by lpinca** [comment]
That is expected, you only have to add _one_ listener for the `'headers'` event.
