### ISSUE TITLE
Node js WebSocket (NPM ws) not returning ping response when windows application in minimize mode

### ISSUE THREAD

**Issue by manojgupta7755** [websockets/ws#2119]
### Is there an existing issue for this?

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Description

I am using NPM ws in my backend project. and i have added ping-pong logic if not getting response of ping in 45 seconds then i'm terminating the web socket connection.

Above logic is working when I'm minimizing the chrome tab I'm still getting the response of ping. But the same code When I'm minimizing the windows application i can see the logs, not getting the response of ping. also i can see the webSocket connection active but not getting the response for ping

### ws version

7.3.0

### Node.js Version

14.16.0

**Comment by lpinca** [comment]
Did you read https://github.com/websockets/ws#how-to-detect-and-close-broken-connections? I think that when the Windows application is minimized the JavaScript execution is paused or throttled to save power. Browsers also do or used to do this.

**Comment by manojgupta7755** [comment]
@lpinca Thank you so much for comment, curios to know if there is any way to check ping from client is reaching to server or apart from relying on pong in return.

**Comment by manojgupta7755** [comment]
No where I'm getting the ping emitted logs

var webServer, wsServer;
webServer = http.createServer(app);
webServer.listen(30000, function () {
  wsServer = new WebSocketServer({
    server: webServer,
  });

  wss.on('connection', function connection(ws) {
    ws.isAlive = true;
    ws.on('error', console.error);
    ws.on('pong', heartbeat);
  });

  // check alive connections
  const interval = setInterval(function ping() {
    wsServer.clients.forEach(function each(ws) {
      if (ws.isAlive === false) {
        return ws.terminate();
      }
      ws.isAlive = false;
      ws.ping(() => {
        ws.on("ping", (data) => {
          console.log("ping emitted ?1");
        });
      });
    });

    ws.on("ping", (data) => {
      console.log("ping emitted ?2");
    });
  }, 450000);
  wsServer.on("ping", (data) => {
    console.log("ping emitted ?3");
  });
  wsServer.on("close", function close() {
    clearInterval(interval);
  });
});

**Comment by lpinca** [comment]
If you are calling `ws.ping()` from the server, the `'ping'` event is emitted on the client.

**Comment by manojgupta7755** [comment]
@lpinca Thank you so much for replies, closing this issue.
