### ISSUE TITLE
Weird behaviour when "Connection" header is omitted or does not include "Upgrade"

### ISSUE THREAD

**Issue by Sainan** [websockets/ws#2121]
### Is there an existing issue for this?

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Description

Sending a request with "Connection: close" or no "Connection" header at all results in the server only sending a TCP ACK, the connection is kept open, but the request is not acknowledged on the HTTP level in any way.
![image](https://user-images.githubusercontent.com/63328889/220826231-76bbb758-ab34-4fb0-a256-2c43c374d14d.png)

### ws version

8.11.0

**Comment by lpinca** [comment]
The `Connection` header must be set to `Upgrade` otherwise the server does not know that the client want to switch to a different protocol (WebSocket) and the request is handled as normal HTTP request. This is not a `ws` issue.

**Comment by Sainan** [comment]
So, the implementer should add HTTP request handling on the ws path?

**Comment by lpinca** [comment]
Yes, see https://github.com/websockets/ws/blob/8.12.1/lib/websocket-server.js#L88-L96 for example.

**Comment by lpinca** [comment]
I'm closing this as answered.
