### ISSUE TITLE
TypeError: One and only one of the "port", "server", or "noServer" options must be specified

### ISSUE THREAD

**Issue by vladyslavv-ua** [websockets/ws#2130]
### Is there an existing issue for this?

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Description

hi i am trying to setup wss using this docs

https://github.com/websockets/ws/blob/master/examples/ssl.js

but i got error TypeError: One and only one of the "port", "server", or "noServer" options must be specified. 

### ws version

8.13.0

### Node.js Version

18.12.0

### System

windows 11 21H2, ubuntu 20

### Expected result

running wss server

### Attachments

![image](https://user-images.githubusercontent.com/110237787/225402682-069634b3-c246-4234-89c5-429fd4188c99.png)
![image](https://user-images.githubusercontent.com/110237787/225403657-59cb8026-6b22-4586-ad04-1b7a22257cae.png)

![image](https://user-images.githubusercontent.com/110237787/225403298-48c4eb8d-db1b-420c-852a-8c5e53380f74.png)
![image](https://user-images.githubusercontent.com/110237787/225403347-98959712-8051-474e-b9d8-beef3c7afdae.png)

**Comment by lpinca** [comment]
The option is called `server`, but you are using `httpsServer`. Use

```js
const server = new WebSocketServer({ server: httpsServer });
```
