### ISSUE TITLE
Documentation does not clearly indicate the message recieved is buffer

### ISSUE THREAD

**Issue by madhurabindu** [websockets/ws#2133]
### Is there an existing issue for this?

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Description

I happened to move from a 7.* version of ws to latest 8.13.0
It took me quite sometime to figure out that the data passed in message event handler is a buffer
The document does not clearly indicate that the data is buffer
The example is right since it use %s which converts it to text format

I finally came across this article, 
https://stackoverflow.com/questions/69485407/why-is-received-websocket-data-coming-out-as-a-buffer
since the documentation hasnt been updated from 8.0.0 for this issue i am raising this request

Request to add the following to example as is given is changelog of 8.0.0 (https://github.com/websockets/ws/releases/tag/8.0.0)
ws.on('message', function message(data, isBinary) {
  const msg = isBinary ?  data.toString() : data;
  console.log('received: %s', data);
});

Also the close handler example need to be changed as per this link https://github.com/websockets/ws/releases/tag/8.0.0
websocket.on('close', function close(code, data) {
  const reason = data.toString();
  // Continue as before.
});

### ws version

8.0.0 and above

### Node.js Version

v14.19.3

### System

 System:
    OS: Linux 5.15 Ubuntu 20.04.6 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
    Memory: 8.35 GB / 15.35 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash

### Expected result

Document is updated with 8.0.0 breaking changes as given in 
https://github.com/websockets/ws/releases/tag/8.0.0

### Actual result

Documentation is not wrong, but not clear either that the data received from 8.0.0 onwards is buffer and not text

**Comment by lpinca** [comment]
See https://github.com/websockets/ws/blob/8.0.0/doc/ws.md#event-message and https://github.com/websockets/ws/blob/8.0.0/doc/ws.md#event-close-1.

**Comment by lpinca** [comment]
I'm closing as answered.

**Comment by madhurabindu** [comment]
I was hoping the documentation on https://github.com/websockets/ws would be changed, considering thats the first documentation a novice would read. In anycase, im late in replying and thank you for your response.
