### ISSUE TITLE
How to access client IP?

### ISSUE THREAD

**Issue by DrCWO** [websockets/ws#2134]
### Is there an existing issue for this?

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Description

In the server I have the need to know from which client the connection comes. Reason for that is that my clients disconnect after a short time to save battery but have to be recognized by the server if reconnecting.
I thought getting the clienet IP in the server would be best but I have no Idea how to get it.

Any ideas?

Cient: 
```
const ws = new WebSocket('ws://192.168.0.193:8096');
ws.on('open', function open() {
 	ws.send(JSON.stringify(... something...));
}
```
Server:
```
	service.wss = new WebSocket.Server({ port: mysettings.port });
	service.wss.on('connection', (conn, req) => {
		conn.on('message', (message) => {
		}
	}
```

**Comment by lpinca** [comment]
See https://github.com/websockets/ws#how-to-get-the-ip-address-of-the-client.

**Comment by lpinca** [comment]
I'm closing this as answered.

**Comment by DrCWO** [comment]
Thank you very much, 👍 
it works even I get a bit stange IP  ..ffff.192.168.0.10
Best DrCWO
