### ISSUE TITLE
[Question] Websockets queue to handle connexion storm 

### ISSUE THREAD

**Issue by jerome-benoit** [websockets/ws#2135]
### Is there an existing issue for this?

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Description

Is there a way to introduce a queue server side that will enqueue websocket opened and dequeue them on specific criterions by using directly the WebSocketServer class? 

I can do a requests queue with an HTTP server: 

```ts
const server = http.createServer((request, response) => {
  enqueueRequest(request);
  // Add conditions for the queue processing
  ... processRequestQueue();
});
```

But I really would like to trigger the queueing at the socket level on specific conditions (simultaneous connections given a time frame) as well as the queue processing.

**Comment by lpinca** [comment]
No, there is not. You can do rate limiting with iptables/nftables and/or a reverse proxy like NGINX.

> But I really would like to trigger the queueing at the socket level on specific conditions (simultaneous connections given a time frame) as well as the queue processing.

I think you can use the `noServer` option and the `websocketServer.handleUpgrade()` method.

```js
import { createServer } from 'http';
import { WebSocketServer } from 'ws';

const server = createServer();
const wss = new WebSocketServer({ noServer: true });

wss.on('connection', function (ws) {
  // ...
});

server.on('upgrade', function (request, socket, head) {
  wss.handleUpgrade(request, socket, head, function done(ws) {
    wss.emit('connection', ws, request);
  });
});

server.listen(8080);
```

**Comment by jerome-benoit** [comment]
> No, there is not. You can do rate limiting with iptables/nftables and/or a reverse proxy like NGINX.

It's a little bit heavy-handed and will not offer randomization on the connexion opening/processing. 

> 
> > But I really would like to trigger the queueing at the socket level on specific conditions (simultaneous connections given a time frame) as well as the queue processing.
> 
> I think you can use the `noServer` option and the `websocketServer.handleUpgrade()` method.
>

Sounds good.

I close the question. 

Thanks.
