### ISSUE TITLE
Websocket does not terminate all connections when calling .close() method

### ISSUE THREAD

**Issue by iamisti** [websockets/ws#2137]
### Is there an existing issue for this?

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Description

I'm using version 8.13.0

I dont exactly know where the issue is, but the following code resulted having hanging/zombie connections on the client side. (they never received a clsoed event from the sever).

The server code:
```
    websocket.close();
    server.close();
```

Note that the websocket has many clients, not only one. (around 5-10 clients in my case)
This resulted zombie clients, not receiving the disconnection/close event.

The code that fixed my issue:
```
    websocket.clients.forEach((a) => {
      a.terminate();
      a.close();
    });

    websocket.close();
    server.close();
    ```

### ws version

8.13.0

### Node.js Version

16.14.2

### Expected result

All connected clients automatically disconnected

### Actual result

Clients still have live connection (seemingly)

**Comment by lpinca** [comment]
See https://github.com/websockets/ws/releases/tag/8.0.0.

> - `WebSocketServer.prototype.close()` no longer closes existing connections
>  (df7de574).
>
>  Existing code can be migrated by closing the connections manually.
>
>  ```js
>  websocketServer.close();
>  for (const ws of websocketServer.clients) {
>    ws.terminate();
>  }
>  ```

**Comment by simplecommerce** [comment]
I have the same issue, which I don't quite understand.

I called wss.close() to close my WebsocketServer using `noServer`.
And my `wss.on("close")` never gets called at all.

Not sure why.

**Comment by lpinca** [comment]
> The server emits a 'close' event when all connections are closed unless an external HTTP server is used and client tracking is disabled.

**Comment by lpinca** [comment]
`wss.close()` does not close existing connections. It only prevents new connections from being accepted.

**Comment by simplecommerce** [comment]
> 

Yes I read that part, so in my tests, I didn't connect any client and was hoping it would timeout or close on its own.
And then i tried to manually turn off my http server which didn't seem to do anything.

If I am using `noServer`, is there any case or scenario which the server would close/shutdown on its own? Or it should always remain until the app itself is closed/terminated?

I am trying to debug an issue where I seem to lose the connection and was trying to trigger it in order to have a proper fix on my end/use case.

**Comment by iamisti** [comment]
Wouldn't it make sense to implicitly close all connections when someone calls `wss.close()`? I think the library should handle that automatically. Just makes sense to finalize all connections within the socket service.

**Comment by lpinca** [comment]
> Wouldn't it make sense to implicitly close all connections when someone calls `wss.close()`?

It was working like this in `ws@7`. In `ws@8` behavior was changed to match the `net.Server` behavior.

**Comment by iamisti** [comment]
ah I see. It makes sense then to be aligned.

**Comment by lpinca** [comment]
@simplecommerce the `'close'` event is emitted if `clientTracking` is enabled

```js
import {WebSocketServer} from 'ws';

const websocketServer = new WebSocketServer({ noServer: true });

websocketServer.on('close', function () {
  console.log('close');
});

websocketServer.close();
```

**Comment by iamisti** [comment]
> > @simplecommerce the `'close'` event is emitted if `clientTracking` is enabled
> > ```js
> > import { WebSocketServer } from 'ws';
> > 
> > const websocketServer = new WebSocketServer({ noServer: true });
> > 
> > websocketServer.on('close', function () {
> >   console.log('close');
> > });
> > 
> > websocketServer.close();
> > ```
> 
> Ok I will try and play with it again, thanks!

Where is clientTracking is enabled in your example

**Comment by iamisti** [comment]
> @simplecommerce the `'close'` event is emitted if `clientTracking` is enabled
> 
> ```js
> import { WebSocketServer } from 'ws';
> 
> const websocketServer = new WebSocketServer({ noServer: true });
> 
> websocketServer.on('close', function () {
>   console.log('close');
> });
> 
> websocketServer.close();
> ```

where is clientTracking enabled in your example?

**Comment by lpinca** [comment]
It is enabled by default.

**Comment by iamisti** [comment]
> It is enabled by default.

In my example I haven't explicitly disabled it so it does not work by default

**Comment by iamisti** [comment]
I've realized i'm using `new WebSocket.Server` insterad of `new WebSocketServer`
Are they the same thing?

**Comment by lpinca** [comment]
Yes they are the same thing and `clientTracking` is enabled by default. Even if `clientTracking` is enabled you still have to close existing connections manually. The example works because there are no open connections.

**Comment by iamisti** [comment]
Thank you for all your answers, appreciate it!

**Comment by guest271314** [comment]
@lpinca How would one go about manually constructing a close `ArrayBuffer` or Node.js `Buffer`, without any message, to send to the client from the server?
