### ISSUE TITLE
Latest benchmark results

### ISSUE THREAD

**Issue by ThisIsMissEm** [websockets/ws#2142]
### Is there an existing issue for this?

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Description

I know benchmarks can be highly dependent on a number of variables, but I also recall seeing stats for how many connections ws could sustain (e.g., wsbench results), would it be possible to have these metrics available?

**Comment by lpinca** [comment]
The answer is to run your own benchmarks. As a rule of thumb, the overhead over a plain `net.Socket` in terms of performance is around 10%. I'm not sure about memory usage, I have not run a benchmark for this in a long time.

See also

- https://github.com/oven-sh/bun/tree/main/bench/websocket-server (https://twitter.com/luigipinca/status/1583044819152437248)
- https://github.com/hashrocket/websocket-shootout (https://github.com/hashrocket/websocket-shootout/issues/44)
- https://github.com/uNetworking/uWebSockets/blob/master/benchmarks/load_test.c
- https://github.com/uNetworking/uWebSockets/blob/master/benchmarks/scale_test.c

**Comment by ThisIsMissEm** [comment]
Thanks for the info!

**Comment by lpinca** [comment]
I'm closing this as answered.
