### ISSUE TITLE
mjs not export `Server`

### ISSUE THREAD

**Issue by wszgrcy** [websockets/ws#2145]
### Is there an existing issue for this?

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Description

I use `socket.io` find this . `socket.io`=>`engine.io`=>`ws`.
`engine.io` use ws.Server. In commonjs work.but in esm not work. I find `Server` not export in mjs 

### ws version

8.11.0

### Node.js Version

16

### Expected result

add Server in mjs or delete Server in cjs

### Actual result

Server  not export in mjs

### Attachments

![image](https://github.com/websockets/ws/assets/9607121/e15e956b-2248-442d-90c5-ff0f53ffc349)

**Comment by lpinca** [comment]
This is by design. Use

```js
import { WebSocketServer } from 'ws'.
```

`WebSocketServer` and `ws.Server` are the same thing.
