### ISSUE TITLE
WebSocket connection to 'wss://websocket_host_name/abc' failed: Insufficient resources

### ISSUE THREAD

**Issue by amoljagdalepucsd** [websockets/ws#2147]
### Is there an existing issue for this?

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Description

Hi Community , 
Most of the times I am getting below error in browser console while Websocket call because of this unable  to connect.
**WebSocket connection to 'wss://websocket_host_name/abc' failed: Insufficient resources**
I am using  "ws": "^5.2.3".
can anyone please help me in this. is it because of some incorrect request , browser issue or network ?

### ws version

"ws": "^5.2.3"

### Node.js Version

greater than > 10.0.0 

### System

- 

### Expected result

Websocket connection should happen properly.

### Actual result

-

**Comment by lpinca** [comment]
I guess `ws` is used as the WebSocket server. Anyway according to Google the "Insufficient resources" error happens because Chrome can't handle a very large number of requests in a short period of time.

**Comment by amoljagdalepucsd** [comment]
Okay @lpinca , 
Thanks for the replay

**Comment by silversword411** [comment]
@lpinca Looks like you're a websocket expert, do you have any insight on why there might be a problem with the mesh agent connecting to the server when CF is involved?

https://github.com/Ylianst/MeshCentral/issues/5302#issuecomment-1703009265
