### ISSUE TITLE
"ws does not work in the browser. Browser clients must use the native WebSocket object" on Node

### ISSUE THREAD

**Issue by david-lee** [websockets/ws#2149]
### Is there an existing issue for this?

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Description

I've got this error in unit tests with Jest + React Testing Lib after upgrading to version 8.12.1.  It is working fine with version <= 8.12.0. 

```
import WebSocket from "ws"

const client = new WebSocket(`ws://localhost:${port}`);
```

### ws version

>= 8.12.1

### Node.js Version

16.20.0

### System

    OS: Linux 5.4 Ubuntu 18.04.6 LTS (Bionic Beaver)
    CPU: (4) x64 Intel(R) Xeon(R) Platinum 8175M CPU @ 2.50GHz
    Memory: 8.73 GB / 15.18 GB
    Container: Yes
    Shell: 4.4.20 - /bin/bash

### Expected result

Running unit tests without an error. It is not running in the Browser but in Node with Jest testing env.

**Comment by lpinca** [comment]
I think your environment uses this conditional export https://github.com/websockets/ws/blob/06728e444d8f54aa5602b51360f4f98794cb1754/package.json#L21. I don't know why but it is not a `ws` issue.

**Comment by david-lee** [comment]
> I think your environment uses this conditional export
> 
> https://github.com/websockets/ws/blob/06728e444d8f54aa5602b51360f4f98794cb1754/package.json#L21
> 
> . I don't know why but it is not a `ws` issue.

Thanks for your answer. I am using `jest-environment-jsdom` for "unit tests". 

```
"testEnvironment": "jest-environment-jsdom",
```
Do you think it is the cause? But as I mentioned in the description, my unit tests are working fine with version `8.12.0` but failed since `8.12.1`. I found that `ws` version 8.12.0 doesn't have the conditional export in the package.json.

**Comment by lpinca** [comment]
> Do you think it is the cause?

It could be.

> I found that ws version 8.12.0 doesn't have the conditional export in the package.json

See https://github.com/websockets/ws/releases/tag/8.12.1

**Comment by david-lee** [comment]
> > Do you think it is the cause?
> 
> It could be.
> 
I was wondering if you know why it is working fine in 8.12.0?

> > I found that ws version 8.12.0 doesn't have the conditional export in the package.json
> 
> See https://github.com/websockets/ws/releases/tag/8.12.1.
>
What I meant is that 8.12.0 doesn't have it and work fine. But since 8.12.1 it has the conditional export and doesn't work.

**Comment by lpinca** [comment]
> I was wondering if you know why it is working fine in 8.12.0?

I guess because without the `browser` condition it uses the `import` condition

https://github.com/websockets/ws/blob/06728e444d8f54aa5602b51360f4f98794cb1754/package.json#L22

**Comment by lpinca** [comment]
Anyway if you are not using something that is specific to `ws` I think you can just use the global `WebSocket` object as suggested in the error message. jsdom uses `ws` under the hood and it should exposes a global `WebSocket` object.

**Comment by lpinca** [comment]
I'm closing this answered.

**Comment by david-lee** [comment]
> I'm closing this answered.

Yes, please. I didn't import it and it is working fine. As you said, I think `jsdom` provides `ws` so it caused the error.
