### ISSUE TITLE
Restore Hixie-76 support

### ISSUE THREAD

**Issue by MFlyer** [websockets/ws#2150]
### Is there an existing issue for this?

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Description

Assumption: checking old ws code I found that Hixie-76 support was removed due to not being in use anymore on "modern" browsers

The assumption is still valid if considering browsers used on desktop & mobile, but it's not valid at all for CTV/HbbTV.

Data supporting the request: many TV devices still alive/in use (different market share by country, e.g. 15-20% Italy / 20-30% Germany) have been release during last 5-7 years with already outdated browsers (affected ones usually run al old webkit aka Safari 5), don't receive support/updates and only rely on Hixie-76

### ws version

latest

**Comment by lpinca** [comment]
Sorry but no, support for Hixie-76 was removed [7 years ago](https://github.com/websockets/ws/pull/871) and in my opinion it does not make sense to restore it just to support a handful of outdated devices. Hixie-76 was only a draft, it was never finalized. It is only an unnecessary complication.

**Comment by MFlyer** [comment]
Ciao @lpinca, I closed the issue before your feedback ad after some tests.
Considerations after some tests with an old webkit 534.something: it makes sense to not restore it, Safari itself has a pesky integration failing immediately after the connection

Cheers
M.
