### ISSUE TITLE
Websocket RangeError: Invalid WebSocket frame: RSV2 and RSV3 must be clear

### ISSUE THREAD

**Issue by smallCF** [websockets/ws#2151]
### Is there an existing issue for this?

- [X] I've searched for any related issues and avoided creating a duplicate issue.
https://github.com/websockets/ws/issues/1285
https://github.com/websockets/ws/issues/1354
https://github.com/websockets/ws/issues/2098
https://github.com/websockets/ws/issues/154
### Description

Question 1：
```
ws.addEventListener('message', (event) => {
  try {
	  if (!event.data) return;
	  const { data, action } = JSON.parse(event.data);
	  if (action === 'ready') {
		  .....
	  }
  } catch (error) {}
});
```
This is the code I started using；
However, after reviewing the issue, I updated the code
```
ws.on('message', function message(event) {
  try {
	  if (!event) return;
	  const { data, action } = JSON.parse(event);
	  if (action === 'ready') {
		 ...
	  }
  } catch (error) {}
});
```
And added an error event for the ws event
`ws.on('error', console.error);`

Question 2：
Now, this issue does not occur on certain servers, and it does not occur during the development phase. How can I simulate this issue during the development phase to facilitate troubleshooting and resolution

### ws version

7.5.9

### Node.js Version

14.16.1

### System

centos 7.7

### Actual result

Websocket RangeError: Invalid WebSocket frame: RSV2 and RSV3 must be clear

**Comment by lpinca** [comment]
> How can I simulate this issue during the development phase to facilitate troubleshooting and resolution

See https://github.com/websockets/ws/issues/2098#issuecomment-1320271965

**Comment by lpinca** [comment]
I'm closing this as answered.
