### ISSUE TITLE
how to use wss.clients? always undefined with 'clientTracking: true' option.

### ISSUE THREAD

**Issue by dorcatty** [websockets/ws#2156]
### Is there an existing issue for this?

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Description

Dear expert,
any idea about how to use wss.clients ?
with Server broadcast example, we see it is possible to use 
wss.clients to loop each connected clients with ‘wss.clients.forEach'
however when we use wss.clients.forEach is has an error of 'undefined', 

Would be possible to learn more about how to use this ? i am sure the option 'clientTracking: true'.
if this func was nolonger available, is it possible to update Example of the main page ?

### ws version

8.19.2

### Node.js Version

18.12.0

### System

 OS: macOS 13.0
    CPU: (10) arm64 Apple M1 Max
    Memory: 18.88 GB / 64.00 GB
    Shell: 5.8.1 - /bin/zsh

### Expected result

to get clients set() no 'undefined' from wss.

### Actual result

console.log(wss.clients);  //undefined error

**Comment by lpinca** [comment]
The `clientTracking` option defaults to `true`.

```js
import WebSocket, { WebSocketServer } from 'ws';

const wss = new WebSocketServer({ port: 0 });

wss.on('connection', function connection(ws) {
  ws.on('error', console.error);

  wss.clients.forEach(function each(client) {
    client.send('Hello');
  });
});

wss.on('listening', function () {
  const ws = new WebSocket(`ws://localhost:${wss.address().port}`);

  ws.on('message', function (message) {
    console.log(message.toString());
  });
});
```

**Comment by lpinca** [comment]
I'm closing this as answred.
