### ISSUE TITLE
Typo in disconnected client example of `README.md`

### ISSUE THREAD

**Issue by joshpwrk** [websockets/ws#2157]
### Is there an existing issue for this?

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Description

In the main `README.md` the example of a heartbeat seems to be wrong:

```javascript
import { WebSocketServer } from 'ws';

function heartbeat() {
  this.isAlive = true;
}

const wss = new WebSocketServer({ port: 8080 });

wss.on('connection', function connection(ws) {
  ws.isAlive = true;
  ws.on('error', console.error);
  ws.on('pong', heartbeat);
});

const interval = setInterval(function ping() {
  wss.clients.forEach(function each(ws) {
    if (ws.isAlive === false) return ws.terminate();

    ws.isAlive = false;
    ws.ping();
  });
}, 30000);

wss.on('close', function close() {
  clearInterval(interval);
});
```

I think the last line `clearInterval(interval)` would terminate ALL heartbeat checks for all existing clients if a single client closes a connection. Unless I'm missing something...

**Comment by lpinca** [comment]
It's not a typo. It's correct. `wss` is the WebSocket server. When it closes there no reason to keep checking as there are no active connections.

**Comment by mortiy** [comment]
Hi @lpinca 
If it is closed, shouldn't it be reopened?
It if is reopened, shouldn't be heartbeat check initialized again?

Or the ws server closed only when app completely crashed?

**Comment by lpinca** [comment]
> If it is closed, shouldn't it be reopened?

It's up to the user to create a new instance.

> It if is reopened, shouldn't be heartbeat check initialized again?

Yes, but it should use the new `WebSocketServer` instance.
