### ISSUE TITLE
No option to disable SSL validation for self-signed certificates?

### ISSUE THREAD

**Issue by jakemangansw** [websockets/ws#2168]
### Is there an existing issue for this?

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Description

I need to test a wss:// connection, but I'm trying to do it with an OpenSSL self-signed certificate.

Other libraries offer rejectUnauthorised or similar options when instantiating the Websocket connection to prevent the client from binning ws connections to certificates it can't validate.

How do I do this with this library? 

### ws version

8.14.1

### Node.js Version

v16.20.0

### System

nil

### Expected result

nil

### Actual result

nil

### Attachments

nil

**Comment by francobramucci** [comment]
You can try NODE_TLS_REJECT_UNAUTHORIZED='0' node app.js

**Comment by lpinca** [comment]
You can use the `rejectUnauthorized` option. See https://nodejs.org/api/https.html#httpsrequesturl-options-callback.
