### ISSUE TITLE
WebSocketServer is not a constructor

### ISSUE THREAD

**Issue by mike-lischke** [websockets/ws#2171]
### Is there an existing issue for this?

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Description

[This patch](https://github.com/websockets/ws/commit/0d114ef48d8baca790733dd2bce23938dd08cb10) (which is supposed to fix another problem) broke use of the `ws` package for us. I just upgraded from 8.12.0 to 8.14 and now my Jest unit tests fail with the error:

> TypeError: _ws.WebSocketServer is not a constructor

Actually, upgrading from 8.12.0 to 8.12.1 shows the error already.

Important detail here is that we run Jest with JSDOM as test environment (since this is a webapp). You can see the [full unit test here](https://github.com/mysql/mysql-shell-plugins/blob/master/gui/frontend/src/tests/unit-tests/supplement/ShellInterface/ShellInterfaceMrs.spec.ts). 

### ws version

8.14

### Node.js Version

20.5.1

### System

gives me 

> npm ERR! cb.apply is not a function

But this a macOS 14.0 box and the system info shouldn't matter.

### Expected result

Creating a WebSocketServer should work as with 8.12.0.

### Actual result

Creating a WebSocketServer instance fails now with the error that this is not a constructor.

**Comment by lpinca** [comment]
The analysis seems correct but it is not a ws issue. The Jest environment should be `'node'` and not `'jsdom'`. There is no WebSocket server in a browser-like environment.

**Comment by mike-lischke** [comment]
Right, there's no WebSocket server in a browser, but that's not the point here. Our web app communicates with a websocket server, we set up temporarily during testing, so we need it regardless of the actual client app. Additionally, as I wrote above, this is a web application, which needs a DOM, so JSDOM (or a similar lib) is mandatory.

Until 8.10 ws worked very well in this setup. Just a small change broke it and I would say this is indeed a ws issue.

**Comment by lpinca** [comment]
Run the server in an environment where it is expected to work. I don't think there is anything actionable to do in ws. If you have a fix, feel free to open a PR.

**Comment by lpinca** [comment]
I think something like this https://github.com/microsoft/accessibility-insights-web/pull/5421/commits/9ad4e618019298d82732d49d00aafb846fb6bac7 should work for your use case.

**Comment by lpinca** [comment]
We can revert https://github.com/websockets/ws/commit/0d114ef48d8baca790733dd2bce23938dd08cb10 but it does not seem a good idea. It is consistent with the pre-existing `browser` field (https://github.com/websockets/ws/blob/8a78f8770618cc5a1ade485a7445cb6d6f46e2f2/package.json#L19).

**Comment by mike-lischke** [comment]
No worries, we use the socket server only for testing, so it's not a show stopper. This can be worked around. Thanks for your quick support Luigi!
