### ISSUE TITLE
Can't resolve modules utf-8-validate and bufferutil in Next.js 13

### ISSUE THREAD

**Issue by samuelnihoul** [websockets/ws#2173]
### Is there an existing issue for this?

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Description

Module not found: Can't resolve 'bufferutil' in '/com.docker.devenvironments.code/node_modules/ws/lib'

Import trace for requested module:
./node_modules/ws/lib/buffer-util.js
./node_modules/ws/lib/websocket.js
./node_modules/ws/index.js
./node_modules/isomorphic-ws/node.js
./node_modules/hashconnect/dist/esm/types/relay.js
./node_modules/hashconnect/dist/esm/hashconnect.js
./node_modules/hashconnect/dist/esm/main.js
./lib/hashconnect.ts
./components/HashButton.tsx

./node_modules/ws/lib/validation.js
Module not found: Can't resolve 'utf-8-validate' in '/com.docker.devenvironments.code/node_modules/ws/lib'

Import trace for requested module:
./node_modules/ws/lib/validation.js
./node_modules/ws/lib/receiver.js
./node_modules/ws/index.js
./node_modules/isomorphic-ws/node.js
./node_modules/hashconnect/dist/esm/types/relay.js
./node_modules/hashconnect/dist/esm/hashconnect.js
./node_modules/hashconnect/dist/esm/main.js
./lib/hashconnect.ts
./components/HashButton.tsx

Unsure how to reproduce but my repo is public: github.com/samuelnihou/karbonbasar7.
Also, the gist of it is that it uses websocket for Web3 wallet connection. I think the repository github.com/hashpack/hashconnect may be more relevant, as you may be able to infer from the error.

### Node.js Version

Bun.js version 1.0.3

### System

System:
    OS: Linux 5.15 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
    Memory: 2.61 GB / 7.62 GB
    Container: Yes
    Shell: 5.1.4 - /bin/bash

### Expected result

No such error.

### Actual result

I have this error when running my Next.js app, during page compilation.

**Comment by lpinca** [comment]
This is not a ws issue. Both `bufferutil` and `utf-8-validate` are [optional peer dependencies](https://github.com/websockets/ws/blob/a049674d936746c36fe928cc1baaaafd3029a83e/package.json#L49-L56).

If you are building for the browser use the global WebSocket object instead of `ws`.

**Comment by lpinca** [comment]
See also https://github.com/websockets/ws/blob/master/doc/ws.md#environment-variables.
