### ISSUE TITLE
[Question] Is it possible to skip compression/decompression of messages when sent or received by the websocket server/client

### ISSUE THREAD

**Issue by Sid200026** [websockets/ws#2174]
### Is there an existing issue for this?

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Description

We are trying to explore a scenario where we will add a proxy websocket server between a websocket client and websocket server similar to the diagram below.

![image](https://github.com/websockets/ws/assets/42297087/e7c41153-8797-467b-af67-cb96659b5ae2)

We want to enable compression of messages from client to improve performance but we do not want compression/decompression to happen inside the proxy's websocket client and server. Is it possible to receive data from the client in a compressed form and forward the same to the websocket server ( No compression and decompression in the proxy )?

**Comment by lpinca** [comment]
If the proxy is implemented as shown in the image, you can skip compression/decompression between the WebSocket server and client inside the proxy.

**Comment by Sid200026** [comment]
If I disable compression/decompression inside the WS server and client inside the proxy, won't the compression of messages by the websocket client/server outside the proxy also be disabled ( Assuming that in a simple client-server setup, both of the client-server needs to have `perMessageDeflate` enabled for compression to actually take place ) ?

**Comment by lpinca** [comment]
In the above example you have all degrees of freedom. There are 3 connections:

1. From the original client to the server inside the proxy. Compression/decompression can be enabled or disabled.
2. From the client inside the proxy to the server inside the proxy. Compression/decompression can be enabled or disabled.
3. From the client inside the proxy to the target server. Compression/decompression can be enabled or disabled.

**Comment by Sid200026** [comment]
Just to clarify,

- I want the client ( outside the proxy ) to receive and send data in compressed form.
- I want the server ( outside the proxy ) to receive and send data in compressed form.
- The client and server inside the proxy should not do any compression/decompression. 

It should receive compressed data from the client ( outside the proxy ), forward the message in compressed form ( there should be no decompression and then compression here ) to the server ( inside the proxy ). The server ( inside the proxy ) should send the message in compressed form to the server ( Outside the proxy ). The server outside the proxy should then decompress the message and then act on it.

Ideally, the goal here is to not add compression/decompression overhead inside the proxy. It should receive data in compressed form and simply forward that compressed message to the server ( outside the proxy ).

**Comment by lpinca** [comment]
> - I want the client ( outside the proxy ) to receive and send data in compressed form.
> - I want the server ( outside the proxy ) to receive and send data in compressed form.
> - The client and server inside the proxy should not do any compression/decompression.
> 
> It should receive compressed data from the client ( outside the proxy ), forward the message in compressed form ( there should be no decompression and then compression here ) to the server ( inside the proxy ). The server ( inside the proxy ) should send the message in compressed form to the server ( Outside the proxy ). The server outside the proxy should then decompress the message and then act on it.
> 

From the image you have a separate server and client inside the proxy. Even if the proxy server will only parse frames without decompressing them, you can't simply forward them to the connection initiated from the client inside the proxy and the destination server because in that handshake the `permessage-deflate` was not negotiated. Also, the negotiated `permessage-deflate` parameters (in particular context takeover control) between the original client and the server inside the proxy might be different from the ones negotiated from the client inside the proxy and the destination server.

**Comment by Sid200026** [comment]
Thanks for the prompt response
