### ISSUE TITLE
Cannot extend Server type

### ISSUE THREAD

**Issue by BCsabaEngine** [websockets/ws#2176]
### Is there an existing issue for this?

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Description

I cannot extend WebSocket server generic type with a custom type, so the original type cannot be extended too.
```
import WebSocket, { Server } from 'ws';
import { IncomingMessage, } from 'http';

export interface ExtendedWebSocket extends WebSocket.WebSocket {
    userId: string;
}
export interface ExtendedIncomingMessage extends IncomingMessage {
    msgId: string;
}

export type ExtendedWebSocketServerA = Server<WebSocket.WebSocket, ExtendedIncomingMessage>;
export type ExtendedWebSocketServerB = Server<ExtendedWebSocket, ExtendedIncomingMessage>;
```

Type 'WebSocket' does not satisfy the constraint 'typeof WebSocket'.
  Type 'WebSocket' is missing the following properties from type 'typeof WebSocket': prototype, createWebSocketStream, Server, WebSocketServer, and 9 more.

Type 'ExtendedWebSocket' does not satisfy the constraint 'typeof WebSocket'.
  Type 'ExtendedWebSocket' is missing the following properties from type 'typeof WebSocket': prototype, createWebSocketStream, Server, WebSocketServer, and 9 more.

### ws version

^8.14.2

### Node.js Version

20

### System

  System:
    OS: Linux 5.15 elementary OS 6.1 Jólnir
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
    Memory: 9.76 GB / 15.35 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh

### Expected result

I should extend types, I use "@types/ws": "^8.5.9",

### Actual result

Type 'WebSocket' does not satisfy the constraint 'typeof WebSocket'.
  Type 'WebSocket' is missing the following properties from type 'typeof WebSocket': prototype, createWebSocketStream, Server, WebSocketServer, and 9 more.

Type 'ExtendedWebSocket' does not satisfy the constraint 'typeof WebSocket'.
  Type 'ExtendedWebSocket' is missing the following properties from type 'typeof WebSocket': prototype, createWebSocketStream, Server, WebSocketServer, and 9 more.

### Attachments

packsge.json:
```
{
  "name": "ws-test",
  "version": "1.0.0",
  "main": "index.js",
  "scripts": {
    "dev": "tsc",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "description": "",
  "devDependencies": {
    "@types/node": "^20.9.1",
    "nodemon": "^3.0.1",
    "ts-node": "^10.9.1",
    "typescript": "^5.2.2"
  },
  "dependencies": {
    "@types/ws": "^8.5.9",
    "ws": "^8.14.2"
  }
}
```

tsconfig: 
```
{
  "compilerOptions": {
    "target": "ESNext",
    "module": "Node16",
    "moduleResolution": "Node16",
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "strict": true,
    "skipLibCheck": true
  }
}
```

**Comment by BCsabaEngine** [comment]
Maybe this will be a solution: https://github.com/websockets/ws/issues/1517#issuecomment-623148704

**Comment by fcastrocs** [comment]
This worked for me 

declare module "ws" {
  declare class MyWebSocket extends WebSocket {
    isAlive: boolean;
    userId: string;
    sendSuccess: (type: string, message?: any) => void;
    sendError: (name: string, message: string) => void;
    sendInfo: (type: string, message: any) => void;
  }
  declare class MyWebSocketServer extends Server<typeof MyWebSocket> {}
}

**Comment by fcastrocs** [comment]
This worked for me without importing anything

![image](https://github.com/websockets/ws/assets/44808362/58d59aad-368d-4002-a409-3fbe86e30b6a)
