### ISSUE TITLE
How are we evaluating a handshake?

### ISSUE THREAD

**Issue by dav1app** [websockets/ws#2177]
### Is there an existing issue for this?

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Description

I'm working on a mock for sockets and for some reason my responses are always interpreted as invalid. 

Then I found this part of the code.

https://github.com/websockets/ws/blob/a049674d936746c36fe928cc1baaaafd3029a83e/lib/websocket.js#L895

 Can I get some clarification on how this work? IMHO it feels a bit weird. It's the only place in the whole code that I have a condition attached to a emit event. 
 
 `else if` conditions are evaluated prior to the if statement, so it can override the response. 
 
 Is there any condition that an `.emit` event would return any value? I couldn't find it anywhere.

**Comment by lpinca** [comment]
I'm closing this as answered.
