### ISSUE TITLE
TypeError when extending WebSocket in typescript

### ISSUE THREAD

**Issue by jrosent** [websockets/ws#2181]
### Is there an existing issue for this?

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Description

I am trying to create a custom WebSocket class by extending WebSocket. 

I then want to use these objects as the default constructor when a socket connects to the server by passing it as the "WebSocket" option in the options parameter of the WebSocketServer.

When a new socket connects and my custom class attempts to call super() I receive the error message:
`TypeError: Class constructor WebSocket cannot be invoked without 'new'.`

The only solution I have found online is to change the "target" property in my tsconfig file to "ES6", but it has not solved the issue.

### ws version

8.14.2

### Node.js Version

20.09

### System
```

var _this = _super.call(this, url) || this;
                           ^
TypeError: Class constructor WebSocket cannot be invoked without 'new'
```

**Comment by lpinca** [comment]
This is now a `ws` issue. The constructor is called with `new` on the server

https://github.com/websockets/ws/blob/208220d018a3571b5bbac541b1e513d1027a6d66/lib/websocket-server.js#L378

and the default `WebSocket` uses the `class` declaration, so it must be called with `new`.

https://github.com/websockets/ws/blob/208220d018a3571b5bbac541b1e513d1027a6d66/lib/websocket.js#L44

**Comment by lpinca** [comment]
I'm pretty sure it can but this is not the right place to ask for these questions. This issue tracker is only for bugs in the library.
