### ISSUE TITLE
Donating Funds to WS

### ISSUE THREAD

**Issue by Lfada** [websockets/ws#2194]
### Is there an existing issue for this?

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Description

Hi WS maintainers. I'm Lucas, a core contributor to the [Drips](https://www.drips.network/) project. I help recipients of donations through their learning and onboarding process.

[Ethers.JS](https://twitter.com/ethersproject) has been using https://github.com/websockets/ws. It's one of their most critical dependencies!

Ethers.JS core contributors (mostly RicMoo) appreciate the work you all do and want to make sure that you are all well-funded to keep doing it. For that reason, they have decided to donate some funds to your project through [Drips](https://www.drips.network/)

Who can I talk to about it?

cc: @lpinca , @einaros , @kaz

### ws version

n/a

### Node.js Version

n/a

### System

n/a

### Expected result

n/a

### Actual result

n/a

### Attachments

n/a

**Comment by lpinca** [comment]
You can use GitHub Sponsors. Is Drips your only option?

**Comment by Lfada** [comment]
Hi @lpinca 

Thank you for your quick response. I understand GH Sponsors but they don't accept cryptocurrencies, Drips is the only option here.

Are you open to receiving cryptocurrencies?

If Yes, let’s discuss how you can receive these funds. 
If No, no worries. We can inform the funder and redirect those funds elsewhere.

Thank you

**Comment by lpinca** [comment]
What is needed? A non custodial wallet? If so what is you recomendation?

**Comment by Lfada** [comment]
@lpinca 

You'd need an Ethereum Wallet. Non-custodial or Custodial is your choice.

You seem to understand the different choices, but[ here's](https://ethereum.org/en/wallets/ ) a guide with the different considerations to pick the right wallet for you.

It's a bit of a nuanced or personal preference question given the different levels of security: Metamask vs mobile wallet vs hardware wallet. Quite a few of us use or like Rainbow Wallet. If you are American, you could use Coinbase to offramp your crypto, and maybe you would like Coinbase Wallet to have everything in one place (fund storage in a wallet and off-ramping in the Coinbase app).

For more context:

Claim process step-by-step video: [video](https://www.youtube.com/watch?v=AOl_XkgWv-A) on the

Explore our [docs](https://docs.drips.network/claim-your-repository) for detailed information on claiming a project and its architecture

**Comment by lpinca** [comment]
Thank you @Lfada. I added ws to Drips and collected the funds.
