### ISSUE TITLE
Support sending Blob

### ISSUE THREAD

**Issue by kettanaito** [websockets/ws#2206]
### Is there an existing issue for this?

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Description

Currently, `ws` doesn't accept `Blob` as an argument to the `.send()` function:

```js
wss.on('connection', (ws) => ws.send(new Blob(['hello']))
```

I believe this is mainly for historic reasons because there used to be no `Blob` in Node.js. There is now, and it would be great to align the sending (and receiving also) with the WHATWG WebSocket standard. 

### ws version

8.16.0

### Node.js Version

v20.11.0

### System

Irrelevant.

### Expected result

`ws` supports sending `Blob` from the server.

### Actual result

- Type error on the unknown input type to `.send()`;
- A runtime `TypeError`:

```
TypeError: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received an instance of Blob
```

**Comment by lpinca** [comment]
It is not for historic reasons, see https://github.com/nodejs/undici/pull/1795#discussion_r1038928224.

**Comment by kettanaito** [comment]
This is an important context, thanks for sharing! So, Blobs being written first is a Node.js thing? 

This is also interesting:

> In practice, even though it requires explicitly setting binaryType, 97% of messages are received as ArrayBuffers. 

Especially given that the default `binaryType` value for `blob`. I believe Undici did end up supporting sending `Blob` from the client (at least, I seem to be able to do that in tests).

**Comment by lpinca** [comment]
> So, Blobs being written first is a Node.js thing?

Yes, because there is no official API to get an `ArrayBuffer` synchronously from a `Blob` and streams do not support `Blob`s natively.

> I believe Undici did end up supporting sending `Blob` from the client (at least, I seem to be able to do that in tests).

I think it is affected by the issue I wrote in that comment.

**Comment by lpinca** [comment]
See also https://github.com/nodejs/undici/pull/1795#issuecomment-1353535714.

**Comment by kettanaito** [comment]
Got it. Thanks for the great references! Do you consider this proposal to be out of scope? We should close it then.

**Comment by kettanaito** [comment]
What about supporting this only on the surface level? Accepting the `Blob` but converting it internally to `nodebuffer` and proceeding as `ws` does now? If that makes any sense, of course (would love to learn if it doesn't). 

My main use case is showcasing `ws` for testing, and it's not great to omit sending/receiving `Blob` data.

**Comment by lpinca** [comment]
> Accepting the `Blob` but converting it internally to `nodebuffer` and proceeding as `ws` does now?

It is not trivial because again, converting a `Blob` to an `ArrayBuffer`/`Buffer` synchronously is not supported by Node.js. We could pause the `Sender` like we do when compressing data but I'm not very happy with it. Also what about support for Node.js versions where `Blob` is not supported?

**Comment by lpinca** [comment]
Yes `ws` still supports Node.js 10.

**Comment by kettanaito** [comment]
> It is a lot easier to convert the `Blob` before calling `websocket.send()`.

I understand this. What I'm proposing is not a matter of convenience but expectations. As in, valid WebSocket usage as per spec should work. Sending a `Blob` is a valid usage. Not supporting it is a limitation of `ws` (as the immediate agent; the issue runs deeper as we've discussed) so it may be a good thing to try to find a solution/compromise here.

**Comment by lpinca** [comment]
Strictly following the WHATWG specification is a non goal for `ws`.

**Comment by lpinca** [comment]
> The issue is that the client will never receive a Blob, even if its `binaryType = 'blob'` (I will double-check on this but I recall that being the outcome of my testing)

That is correct for `ws`. That binary type is not supported. Receiving a `Blob` is easier as it can be created synchronously from an `ArrayBuffer` but if we allow receiving it we should also allow sending it.

**Comment by kettanaito** [comment]
Thank you for your work on this! 💪
