### ISSUE TITLE
WebSocket Ping-Pong Timeout and Connection Closure Failure

### ISSUE THREAD

**Issue by kartikgupta2607** [websockets/ws#2207]
### Is there an existing issue for this?

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Description

Our custom wrapper module built on top of `ws` handles connection events (ping, pong, errors, message, close) on both server and client sides.
###  **Normal workflow involves:**

- Client connects with the server and sends a request.
- Server processes the request and sends a response.
- For long-running requests or multiple requests on the same WebSocket connection, ping-pong calls are sent from the client at regular intervals to ensure the connection remains alive.

### **Observed Issue:**

- Occasionally, a ping call sent from the client is not received at the server end (or at least not logged until [this point](https://github.com/websockets/ws/blob/a04578e36611998d089fbb7c6057d1363a5d5754/lib/websocket.js#L1193) where we have a ping handler which logs the ping request).
- Consequently, a pong timeout issue occurs on the client end, leading to custom retry logic and eventual closure of the connection if retry also fails.

### Failure in Connection Closure:

- After a ping failure, we retry it once, but if it fails again, we attempt to close the connection using our custom close code 3001 (`ws.close(3001)`).
-  However, even the closing handshake fails due to a timeout issue [here](https://github.com/websockets/ws/blob/5e42cfdc5fa114659908eaad4d9ead7d5051d740/lib/websocket.js#L328).

### Additional Request
-  Is there a way to identify if a connection is stuck on either the server or client side?

Please let me know if you require additional details.

### ws version

8.12.1

### Node.js Version

Server (18.12.1), Client (14.18.1)

**Comment by netizen-ais** [comment]
The failed pings should indicate network problems in either side, so the "_closing handshake_" can't complete (as it implies packets between both endpoints)

**Comment by lpinca** [comment]
> Is there a way to identify if a connection is stuck on either the server or client side?

You can capture the traffic with something like tcpdump or Wireshark.

**Comment by lpinca** [comment]
I'm closing this as answered.
