### ISSUE TITLE
Sending TypedArray as binary from server to client?

### ISSUE THREAD

**Issue by wufufufu** [websockets/ws#221]
What would be the server-side set up for something like this? The clientside doesn't allow for mask : 'true'.

I have it set up like this.
## Server:

```
ws.on('message', function(message) {
    var array = new Float32Array(size * 10 + 2);
            //Arbitrary data inserted
    ws.send(array.buffer);
});
```
## Client:

```
connection.onmessage = function (e) {
    var temp = new Float32Array(e.data);
    //Here temp is all 0s regardless of data for some reason
...
}
```

**Comment by jeremykentbgross** [comment]
Actually ws.send(array.buffer); never worked for me, and I always did: ws.send(array);  However with node 12 it seems that i must instead do this: ws.send(new Buffer(array));  This took some debugging and playing around to find, but one annoying aspect is that if I read the node documentation correctly the buffer will be copying the array, not using it directly, which creates unneeded overhead for large buffers which I need to send on connect.

**Comment by lpinca** [comment]
Sending typed arrays should work out of the box. They are converted to buffers without copying the data. Data is copied only when the buffer is masked.
