### ISSUE TITLE
Invalid dns names should not cause an uncatchable fatal exception

### ISSUE THREAD

**Issue by nickgrealy** [websockets/ws#2222]
### Is there an existing issue for this?

- [X] I've searched for any related issues and avoided creating a duplicate issue.

**Related:**

- https://stackoverflow.com/questions/63837969/websocketws-nodejs-handle-error-enotfound
- https://stackoverflow.com/questions/23803061/how-to-try-catch-ws-error-getaddrinfo-enotfound
- https://github.com/websockets/ws/issues/1435

### Description

Creating a websocket for a dns name that doesn't exist or isn't resolvable at that point in time (i.e. network down), crashes the Node application.

```
const ws = new WebSocket('https://does.not.exist')
```

This is a problem, because the host application cannot catch and handle the error, through normal, idiomatic means i.e. `try/catch` or `await promise.catch()`.

The error can be handled using the `ws.on('error', () => {...})` error listener, however this isn't always available (i.e. in the case the `Websocket` is wrapped in another library e.g. [`ethers`](https://www.npmjs.com/package/ethers)).

**Workaround:**

I'm currently "promisifying" my websocket creation, which allows me to catch the "getaddrinfo ENOTFOUND" error and handle it gracefully.

```
const promisifyWebSocket = (url: string): Promise<WebSocket> => {
    return new Promise((resolve, reject) => {
        const ws = new WebSocket(url)
        ws.on('error', reject)
        ws.on('open', () => resolve(ws))
    })
}

try {
    const ws = await promisifyWebSocket('https://does.not.exist')
} catch (err: any) {
    console.error('caught', err.message)
}
```

### ws version

8.16.0

### Node.js Version

v18.19.0

### System

  System:
    OS: macOS 13.5.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 170.91 MB / 64.00 GB
    Shell: 3.2.57 - /bin/bash

### Expected result

The error should be able to be caught / handled in an idiomatic manner (even when the websocket is wrapped by other libraries e.g. [`ethers`](https://www.npmjs.com/package/ethers)).

Alternatively - the default behaviour should not crash the parent application.

### Actual result

The application is killed with exit code `1` and logs.

```
Error: getaddrinfo ENOTFOUND does.not.exist
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:107:26) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'does.not.exist'
}
```

**Comment by lpinca** [comment]
How is this a `ws` issue? The error is emitted like all other errors. It is user responsibility to handle it.

**Comment by lpinca** [comment]
I'm closing this as answered.
