### ISSUE TITLE
Incorrect/incomplete documentation

### ISSUE THREAD

**Issue by omnicron-llc** [websockets/ws#2223]
### Is there an existing issue for this?

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Description

A little embarrassing that the example code in the README.md is incorrect in multiple places - for example, the call back to wss.on('connection') only has 2 parameters, so the line
wss.on('connection', function connection(ws, request, client) {
is incorrect.

In the following 'upgrade' code block, there's also an *undefined* reference to client, which isn't even present in that block at all.

It would seem that at code samples should not at least include things like references to variables that do not exist, or completely invalid function prototypes.

**Comment by lpinca** [comment]
> A little embarrassing that the example code in the README.md is incorrect in multiple places - for example, the call back to wss.on('connection') only has 2 parameters, so the line
wss.on('connection', function connection(ws, request, client) {
is incorrect.

See this line

```js
wss.emit('connection', ws, request, client);
```

> In the following 'upgrade' code block, there's also an undefined reference to client, which isn't even present in that block at all.

See https://nodejs.org/api/http.html#event-upgrade_1.

The example is correct. I'm closing this as answered.

**Comment by omnicron-llc** [comment]
Your code example does not run, even if an authenticate method is provided that matches the prototype provided. Test your own code. I already have a working example, but this is pathetic.
