### ISSUE TITLE
Source Code Confusion

### ISSUE THREAD

**Issue by yuhao423** [websockets/ws#2232]
### Is there an existing issue for this?

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Description

Hello lpinca, this is not a bug report, I've been reading the ws source code recently and it's great, but a question that is confusing me is what are the three parameters that are returned after sending an http request to upgrade, `res` I understand is the upgrade field that is returned by the server, and `socket` and `head` I don't know what they are. The specific code is lib/websocket.js `initAsClient` function in the req.on('upgrade'),sorry to bother you.

![image](https://github.com/websockets/ws/assets/76569582/3e57dd71-7130-4f78-8d91-60c70f6abba0)

**Comment by lpinca** [comment]
See https://nodejs.org/api/http.html#event-upgrade and https://nodejs.org/api/http.html#event-upgrade_1. The former is emitted on the client, the latter on the server. The arguments are the same.

**Comment by yuhao423** [comment]
Thanks, I should spend more time looking at the HTTP API documentation.

**Comment by lpinca** [comment]
I'm closing this as answered.
