### ISSUE TITLE
DoS

### ISSUE THREAD

**Issue by jasurhaydarovcode** [websockets/ws#2234]
### Is there an existing issue for this?

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Description

Hi, won't this affect my repo? 

### ws version

8.17.1

### Node.js Version

v.20.14.0

### System

![Скриншот 21-06-2024 233753](https://github.com/websockets/ws/assets/157284471/dd3b29b8-d39e-4bb5-a499-ec9ef83a932b)

### Expected result

![Скриншот 21-06-2024 233825](https://github.com/websockets/ws/assets/157284471/de810135-2ae5-44fc-8f9b-5657cb74ab39)

### Actual result

![Скриншот 21-06-2024 233825](https://github.com/websockets/ws/assets/157284471/082c8f7d-f082-4cb3-ab08-73993fb2136d)

### Attachments

Hi, won't this affect my repo?

**Comment by lpinca** [comment]
It seems you are using ws@8.16.0. Update it to version 8.17.1

**Comment by jasurhaydarovcode** [comment]
ok thanks
