### ISSUE TITLE
[NOT AN ISSUSE] a simple request

### ISSUE THREAD

**Issue by TrueXPixells** [websockets/ws#2237]
### Is there an existing issue for this?

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Description

hey! sorry about this issuse but i cant found any contact links about you (lpinca)
can you delete this issuse and https://github.com/websockets/ws/issues/1913

**Comment by lpinca** [comment]
Why deleting? Can't https://github.com/websockets/ws/issues/1913 be kept closed.

**Comment by lpinca** [comment]
Ok, done. I'm also deleting this one as per your request.
