### ISSUE TITLE
Contribution Proposal and Chinese Documentation Request for WS Library

### ISSUE THREAD

**Issue by yuhao423** [websockets/ws#2238]
### Is there an existing issue for this?

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Description

Hello,

This is Yuhao, and I am a software developer from China. I recently finished reading the source code of the WS library and found it exceptionally well-written. I appreciate yours open-source efforts and the value this library brings to the community.

As an open-source enthusiast myself, I am keen to contribute to the WS library. Are there any new `bugs` or `features` that need attention or development? I would like to assist in any way I can.

Additionally, there is a big number of developers in China who use the WS library. Would you consider adding Chinese documentation to better support these users? I would be more than happy to assist with the translation and creation of the Chinese documentation.

Thank you for your time.

**Comment by lpinca** [comment]
Hello Yuhao, thank you for your offer of help. The are currently no critical issues or feature requests. I would also prefer not to add a Chinese version of the documentation in source control. Feel free to create one outside of the repository.

**Comment by yuhao423** [comment]
ok，I will fork this in my repository.Thanks for your time.
