### ISSUE TITLE
Type in @types/ws for server address is wrong 

### ISSUE THREAD

**Issue by marcus-pousette** [websockets/ws#2243]
### Is there an existing issue for this?

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Description

According to 
https://github.com/websockets/ws/blob/019f28ff1ffddfcdc428d1de5ecd98648057a2ab/lib/websocket-server.js#L140C30-L140C34

Return type can be null but in the types

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/e2f4498db0cf43c4c89803603cd7bb9a6c744f2c/types/ws/index.d.ts#L344

this is missing

### ws version

master

### Node.js Version

20

### System

-

### Expected result

Same types

### Actual result

Missing null

**Comment by lpinca** [comment]
Open an issue/PR in the DefinitelyTyped repository. We do not maintain the TypeScript type definitions.
