### ISSUE TITLE
How to unsubscribe from a topic

### ISSUE THREAD

**Issue by dj-fiorex** [websockets/ws#2246]
### Is there an existing issue for this?

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Description

Hello guys, maybe i missed something, but i can't understand how to unsubscribe from a topic. 
I can subscribe to new messages with the "on" method, but i can't figure out witch method to use to unsubscibe

Thanks

### ws version

8.18.0

### Node.js Version

20.15.1

### System

  System:
    OS: macOS 14.5
    CPU: (12) arm64 Apple M2 Pro
    Memory: 137.42 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh

### Expected result

A method to unsubscribe from a topic, for example "off"

### Actual result

There is not a method to unsubscribe

**Comment by lpinca** [comment]
`WebSocket` is an `EventEmitter`, see https://nodejs.org/api/events.html#class-eventemitter.

**Comment by lpinca** [comment]
I'm closing this as answered.
