### ISSUE TITLE
Incomplete message from the server: Invalid WebSocket frame: FIN must be set

### ISSUE THREAD

**Issue by noobix** [websockets/ws#2247]
### Is there an existing issue for this?

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Description
```
import express, { NextFunction, Request, Response } from 'express';
import cors from 'cors';
import bodyParser from 'body-parser';
import helmet from 'helmet';
import prisma from './lib/prisma';
import { createServer } from 'http';
import WebSocket, { Server as WebSocketServer } from 'ws';

interface ExtendedWebSocket extends WebSocket {
  isAlive: boolean;
}
interface WebSocketServerRequest extends Request {
  wss?: WebSocketServer;
}

const port = process.env.PORT || 8080;
const app = express();
const server = createServer(app);

async function main() {
  // app.use(express.json());

  app.use(
    cors({
      origin: function (origin, callback) {
        const allowedOrigins = [
         /*
           allowed domains 
         **/
        ];
        if (!origin || allowedOrigins.includes(origin) || origin.startsWith('ws://') || origin.startsWith('wss://')) {
          callback(null, true);
        } else {
          callback(new Error('Not allowed by CORS'));
        }
      },
      optionsSuccessStatus: 200,
    }),
  );

  // Middleware to add the WebSocket server instance to the request object
  const addWebSocketServer = (wss: WebSocketServer) => {
    return (req: WebSocketServerRequest, res: Response, next: NextFunction) => {
      req.wss = wss;
      next();
    };
  };

  app.use(helmet());
  app.use(bodyParser.urlencoded({ limit: '100mb', extended: false }));
  app.use(bodyParser.json({ limit: '100mb' }));

  // Create a WebSocket server
  // const wss: WebSocketServer = new WebSocketServer({ port: 1280 });
  const wss: WebSocketServer = new WebSocketServer({
    server,
    path: '/api/v1/ws',
    perMessageDeflate: {
      zlibDeflateOptions: {
        chunkSize: 1024,
        memLevel: 7,
        level: 3,
      },
      zlibInflateOptions: {
        chunkSize: 10 * 1024,
      },
      clientNoContextTakeover: true,
      serverNoContextTakeover: true,
      serverMaxWindowBits: 10,
      concurrencyLimit: 10,
      threshold: 1024,
    },
    maxPayload: 1024 * 1024 * 10,
    clientTracking: true,
    skipUTF8Validation: true,
    backlog: 1024,
    noServer: false,
  });

  // A map to store connected clients
  const clients: Map<string, ExtendedWebSocket> = new Map();

  // Handle WebSocket connection
  wss.once('connection', (ws: ExtendedWebSocket, req) => {
    // Generate a unique ID for the client and add it to the map
    const clientId = req.headers['sec-websocket-key'] as string;
    clients.set(clientId.toString(), ws);

    console.log('Client connected:', clientId);

    // Implement ping-pong to keep connection alive
    ws.isAlive = true;
    ws.on('pong', () => {
      ws.isAlive = true;
    });
    // Handle incoming messages from the client
    ws.on('message', (message: Buffer) => {
      console.log('message', message.toString());
    });

    // Send a message to the client
    const systemMsg: { id: string; message: string } = { id: clientId.toString(), message: 'Connected' };
    ws.send(JSON.stringify(systemMsg));

    // Store the clients in the app.locals to access them in the routes
    app.locals.clients = clients;

    // Clean up when the client disconnects
    ws.on('close', () => {
      console.log('Client disconnected:', clientId);
      clients.delete(clientId.toString());
    });
    //Error handling
    ws.on('error', (error) => {
      console.error(`Client ${clientId} error:`, error);
    });
  });

  // Implement ping-pong interval
  const interval = setInterval(() => {
    wss.clients.forEach((ws: WebSocket) => {
      const extendedWs = ws as ExtendedWebSocket;
      if (extendedWs.isAlive === false) return ws.terminate();
      extendedWs.isAlive = false;
      ws.ping();
    });
  }, 30000);

  wss.on('close', () => {
    clearInterval(interval);
  });

  //WebSocket middleware
  app.use(addWebSocketServer(wss));
  // Register API routes
 //...

  // Handle webSocket requests
  app.get('/api/v1/ws', (req: WebSocketServerRequest, res: Response) => {
    const wss = req.wss;
    if (wss) {
      //Request websocket upgrade
      wss.handleUpgrade(req, req.socket, Buffer.alloc(0), (ws) => {
        wss.emit('connection', ws, req);
      });
      // Handle the WebSocket request
      console.log('WebSocket server available');
    } else {
      res.status(400).json({ error: 'WebSocket server not available' });
    }
  });

  //event webhook
  app.post('/api/v1/payment/momo-event-webhook', async (req: Request, res: Response) => {
    const event = req.body;

    // Relay the event to all connected clients
    const [clientId] = Array.from(clients.keys());
    const broadcast = (clients: Iterable<ExtendedWebSocket>, message: string) => {
      console.log('Sending event to client', clientId);
      Array.from(clients).forEach((client) => {
        if (client.readyState === WebSocket.OPEN) {
          client.send(message);
        }
      });
    };
    broadcast(clients.values(), JSON.stringify({ event, clientId }));

    res.status(200).json({ success: true, message: 'Event received' });
  });

  // Specific CORS configuration for the webhook route
  const webhookCorsOptions = {
    origin: '*', // Allow from all origins, or specify the exact origin like 'https://payment-gateway.com'
    methods: ['GET', 'POST'], //  Allow POST and GET requests
    allowedHeaders: ['Content-Type'],
  };

  // Webhook route
  app.use('/api/v1/payment/momo-response-webhook', cors(webhookCorsOptions), (req: Request, res: Response) => {
    // Handle the webhook request
    console.log('Webhook received:', req.body);
    res.status(200).json({ success: true, message: 'Webhook received' });
  });

  // Catch unregistered routes
  app.all('*', (req: Request, res: Response) => {
    res.status(404).json({ error: `Route ${req.originalUrl} not found` });
  });

  app.listen(port, () => {
    console.log(`Server is listening on port ${port}`);
  });
}

main()
  .then(async () => {
    await prisma.$connect();
  })
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });
```
/*
Please note that I am new to websocket programming and I don't have any forums I could submit my problems to  either than her. This is actually not a bug but a cry for help.
**/

### ws version

8.18.0

### Node.js Version

v20.11.1

### System

Host Name:                 DESKTOP-*19V***
OS Name:                   Microsoft Windows 11 Pro
OS Version:                10.0.22000 N/A Build 22000
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:          nan****@live.com
Registered Organization:
Product ID:                00330-80000-00000-AA521
Original Install Date:     2/20/2024, 3:49:33 AM
System Boot Time:          8/11/2024, 7:56:18 PM
System Manufacturer:       Hewlett-Packard
System Model:              HP 240 G7 Notebook PC
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 126 Stepping 5 GenuineIntel ~991 Mhz
BIOS Version:              AMI F.23, 7/17/2023
Windows Directory:         C:\Windows
System Directory:          C:\Windows\system32
Boot Device:               \Device\HarddiskVolume1
System Locale:             en-us;English (United States)
Input Locale:              en-us;English (United States)
Time Zone:                 (UTC+00:00) Monrovia, Reykjavik
Total Physical Memory:     16,073 MB
Available Physical Memory: 4,144 MB
Virtual Memory: Max Size:  27,849 MB
Virtual Memory: Available: 7,699 MB
Virtual Memory: In Use:    20,150 MB

### Expected result

No disconnection once initial connection is achieved

### Actual result

Sometimes I get `Disconnected (code: 1006, reason: "")` but mostly I get `Invalid WebSocket frame: FIN must be set` After a reasonable amount of time upon connection. Approximately 30 seconds

### Attachments

![Screenshot 2024-08-13 093351](https://github.com/user-attachments/assets/324e0c86-de46-472d-97d4-5a3343835a6a)

**Comment by noobix** [comment]
I have just noticed the part where I ping the client to keep the connection alive is the cause of the issue. I have to ping because Heroku will disconnect connections that are idle for 55 seconds. How can I sent a ping that has complete data packet that the client experts

**Comment by lpinca** [comment]
https://github.com/websockets/ws/blob/976c53c4065c49ede73bfba824caf5a6e0f290cb/doc/ws.md#websocketpingdata-mask-callback

Perhaps it is the proxy used by Heroku that is causing the issue.

**Comment by noobix** [comment]
Please note that I am deploying to Heroku and as it stands now the websocket server is unable to send message to the client after connection is made. There is a console log when the websocket server attempts to send messages. In my local dev server the logs appear and messages are sent. I don't know why on Heroku I have all my setting make in this order

1. heroku labs:enable http-session-affinity -a your-app-name
2. configure my Procfile
3. heroku ps:scale web=1

And still the Heroku can't send messages to the client

**Comment by lpinca** [comment]
I don't know. Try to simplify your code. Remove everything and deploy only a minimal WebSocket server like https://github.com/websockets/ws?tab=readme-ov-file#simple-server. See how it goes.

**Comment by noobix** [comment]
We actually moved to render and we are very fine.. The actual problem we faced was Heroku timing out after 55 seconds. We tried to send a ping pong but that also killed the connection because the data packet did not contain some vital data. Thanks
