### ISSUE TITLE
`autoPong` is being forcefully read even if the `options` parameter is optional according to the JSDoc.

### ISSUE THREAD

**Issue by Pupix** [websockets/ws#2248]
### Is there an existing issue for this?

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Description

As the title says.

https://github.com/websockets/ws/blob/019f28ff1ffddfcdc428d1de5ecd98648057a2ab/lib/websocket.js#L89-L91

The JSDoc definition:
https://github.com/websockets/ws/blob/019f28ff1ffddfcdc428d1de5ecd98648057a2ab/lib/websocket.js#L47-L53

I found instances of that class being used in as `new WebSocket(null)` in an unrelated project, that broke after upgrading `ws`.

### ws version

8.18

### Node.js Version

v21.7.1

### System

System:
    OS: Windows 11 10.0.22631
    CPU: (8) x64 AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx
    Memory: 859.42 MB / 5.88 GB

### Expected result

Using `new WebSocket(null)` shouldn't crash node.

### Actual result

Using it that way it does indeed crash node.

**Comment by lpinca** [comment]
See https://github.com/websockets/ws/pull/2199, https://github.com/websockets/ws/issues/2188 and https://github.com/websockets/ws/issues/2205. `new WebSocket(null)` is not a public API.

**Comment by Pupix** [comment]
Oh I see, thanks for clarification.
