### ISSUE TITLE
Move abortHandshake (and others?) into WebSocket

### ISSUE THREAD

**Issue by orgads** [websockets/ws#2249]
### Is there an existing issue for this?

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Description

Is there a reason some functions are declared outside the class, and called from within it with this as first argument?

I want to subclass `WebSocket` and call `abortHandshake` for example on `unexpected-response` event, but it's not available outside the library source.

I've also noticed other similar functions like `initAsClient`. Can you explain the design decisions?

### ws version

8.18.0

### Node.js Version

20.16.0

**Comment by lpinca** [comment]
Yes, it is to make them private. They make a lot of assumptions and should not be exposed to the user.

**Comment by orgads** [comment]
Thank you. Can you suggest how to handle `unexpected-response` (I want to log the request and response), and still abort?

**Comment by lpinca** [comment]
See https://github.com/websockets/ws/blob/976c53c4065c49ede73bfba824caf5a6e0f290cb/test/websocket.test.js#L1073-L1127. If you want the `'error'` and `'close'` event to be emitted, call `websocket.close()` or `websocket.terminate()` after reading the response.

**Comment by farr64** [comment]
Just a quick question, regarding @lpinca's comment "They make a lot of assumptions".

There's one assumption that's obvious to the cognoscenti but not obvious to me, a mere mortal.

I have no clue about the assumption behind the `it` in all the expressions in the tests such as this:

```js
it('unexpected response can be read when sent by server', (done) => { 
   server.once('upgrade', (req, socket) => { 
     socket.end( 
       `HTTP/1.1 401 ${http.STATUS_CODES[401]}\r\n` + 
         'Connection: close\r\n' + 
         'Content-type: text/html\r\n' + 
         'Content-Length: 3\r\n' + 
         '\r\n' + 
         'foo' 
     ); 
   }); 
```

Can you please enlighten me? 

What does `it` mean in this context?

Thanks.

Alfredo

**Comment by orgads** [comment]
That's a common syntax for unit tests, used in jest and mocha. https://jestjs.io/docs/api#testname-fn-timeout

**Comment by farr64** [comment]
Thanks very much, @orgads, for helping me fill yet another gap in my knowledge.

I'm simply a happy user of @lpinca's `ws`, which I access via this `Flutter` package: https://pub.dev/packages/web_socket_channel

I have minimal knowledge of js and its tools, such as jest and mocha, which you mentioned.

I'll do my best to learn as much as I can. Meanwhile, back to pushing my own `Flutter` app forward, with many thanks to everyone using the js tools to push `ws`forward .

**Comment by orgads** [comment]
Good luck!

**Comment by farr64** [comment]
Indeed. Thanks to good people like you.

**Comment by lpinca** [comment]
@farr64 `describe() / context()`, `test() / it()`, `before()`, `after()`, etc. is a syntax commonly used for BDD testing (also outside the JavaScript world).
