### ISSUE TITLE
Error: Invalid WebSocket frame: invalid UTF-8 sequence using Node 22.7

### ISSUE THREAD

**Issue by st3ffgv4** [websockets/ws#2252]
### Is there an existing issue for this?

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Description

Yesterday i've updated my client to nodejs 22.7.0 and it started to give this error after a while:

>  Error: Invalid WebSocket frame: invalid UTF-8 sequence
>     at Receiver.dataMessage (/root/b-core-mongo/node_modules/ws/lib/receiver.js:583:28)
>     at /root/b-core-mongo/node_modules/ws/lib/receiver.js:530:12
>      at /root/b-core-mongo/node_modules/ws/lib/permessage-deflate.js:309:9
>      at /root/b-core-mongo/node_modules/ws/lib/permessage-deflate.js:392:7
>      at afterWrite (node:internal/streams/writable:708:5)
>     at onwrite (node:internal/streams/writable:686:7)
>      at Zlib.cb (node:internal/streams/transform:191:7)
>     at Zlib.processCallback (node:zlib:632:8) {
>   code: 'WS_ERR_INVALID_UTF8',
>   [Symbol(status-code)]: 1007
> }

My client configuration is
```
new WebSocket(
      `ws://${config.get("websocket.server.endpoint")}:${config.get(
        "websocket.server.port"
      )}`,
      {
        headers: {
          "x-bnode-name":
            process.env.BNODE_INSTANCE_NAME ?? os.hostname() ?? "test",
          "x-bnode-version": process.env.npm_package_version,
        },
      }
    );
```

My server configuration is:
```
new WebSocketServer({
      port: this.port,
      perMessageDeflate: {
        zlibDeflateOptions: {
          // See zlib defaults.
          chunkSize: 1024,
          memLevel: 7,
          level: 3,
        },
        zlibInflateOptions: {
          chunkSize: 10 * 1024,
        },
        // Other options settable:
        clientNoContextTakeover: true, // Defaults to negotiated value.
        serverNoContextTakeover: true, // Defaults to negotiated value.
        serverMaxWindowBits: 10, // Defaults to negotiated value.
        // Below options specified as default values.
        concurrencyLimit: 10, // Limits zlib concurrency for perf.
        threshold: 1024, // Size (in bytes) below which messages
        // should not be compressed if context takeover is disabled.
      },
    });
```

Bufferutil installed.
With node 22.6.0 all works well.
One thing that i can say is that i send lot of json strings.

### ws version

8.18.0

### Node.js Version

22.7.0

### System

OS: Linux 6.8 Ubuntu 24.04.1 LTS 24.04.1 LTS (Noble Numbat)
    CPU: (12) x64 Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
    Memory: 12.68 GB / 15.28 GB
    Container: Yes
    Shell: 5.2.21 - /bin/bash

### Expected result

no errors thrown

### Actual result

>  Error: Invalid WebSocket frame: invalid UTF-8 sequence
>     at Receiver.dataMessage (/root/b-core-mongo/node_modules/ws/lib/receiver.js:583:28)
>     at /root/b-core-mongo/node_modules/ws/lib/receiver.js:530:12
>      at /root/b-core-mongo/node_modules/ws/lib/permessage-deflate.js:309:9
>      at /root/b-core-mongo/node_modules/ws/lib/permessage-deflate.js:392:7
>      at afterWrite (node:internal/streams/writable:708:5)
>     at onwrite (node:internal/streams/writable:686:7)
>      at Zlib.cb (node:internal/streams/transform:191:7)
>     at Zlib.processCallback (node:zlib:632:8) {
>   code: 'WS_ERR_INVALID_UTF8',
>   [Symbol(status-code)]: 1007
> }

**Comment by lpinca** [comment]
The error is self explanatory. The peer is receiving invalid UTF-8 but it very unlikely to be a `ws` issue as nothing changed. See https://github.com/nodejs/node/issues/54543.

**Comment by lpinca** [comment]
This should be fixed in Node.js 22.8.0.
