### ISSUE TITLE
Ping-pong frames are not displayed in the network

### ISSUE THREAD

**Issue by NikitaMikheev** [websockets/ws#2256]
### Is there an existing issue for this?

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Description

Hello, when using ping-pong on my server, I do not see requests for sending ping-pong frames in Postman or in the browser's network tab. However, when connecting to 'wss://echo.websocket.org', these frames are displayed. What could be the reason for this discrepancy?

### Expected result

![image](https://github.com/user-attachments/assets/5f669846-cde0-4c56-bf8c-c84a333cc1f3)

**Comment by sdrsdr** [comment]
the pong response is mandated by the standard. The ping method is defined but when and how it is called is up to the user. Obviously the  server at echo.websocket.org does a regular ping you software does not

**Comment by lpinca** [comment]
AFAIK control frames are now shown in Chrome. The "Ping" in your screenshot is probably a text message. See [`websocat`](https://github.com/vi/websocat) and [`wscat`](https://github.com/websockets/wscat). They both allows you see ping and pong frames.

```
websocat -v wss://websocket-echo.com
wscat -P wss://websocket-echo.com
```

**Comment by NikitaMikheev** [comment]
Yes, you are right. Thanks
