### ISSUE TITLE
I get some error in My Project by ws

### ISSUE THREAD

**Issue by UjjwalSaini07** [websockets/ws#2260]
### Is there an existing issue for this?

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### ws version

7.5.9, 8.14.2

### Node.js Version

v20.12.2

### System

    OS: Windows 10 10.0.19045
    CPU: (4) x64 Intel(R) Core(TM) i3-10110U CPU @ 2.10GHz
    Memory: 4.12 GB / 11.82 GB

### Expected result

I want it normally merged as other Dependabot Secuirty updates as this severity is also HIGH so its important to add them to my project but it show Again and again erorr 

### Actual result

ws affected by a DoS when handling a request with many HTTP headers
- Dependabot cannot update ws to a non-vulnerable version
- No patched version available for ws

This happen by tackling with the Dependabot and also it show the severity as HIGH so its Important to tackle this in effective way.
- I tried so many thing but I'm confused how to correct this 
- Can Anyone please help me to correct this issue.

### Attachments

![image](https://github.com/user-attachments/assets/f16efec5-1f4f-4d29-9213-7a578fecbc30)

**Comment by lpinca** [comment]
Is the version pinned in you `package.json`? The issue was fixed in versions 5.2.4, 6.2.3, 7.5.10, and 8.17.1.

**Comment by UjjwalSaini07** [comment]
@lpinca Hii, i not get u what you said, But i have a problem in version 7.5.9, 8.14.2

![image](https://github.com/user-attachments/assets/2199f688-fa7a-41af-80e1-22913471a359)

### **_Image Ref1:_**
![image](https://github.com/user-attachments/assets/8aef22bb-7ad7-42b9-a287-5bc95ba24c66)

### **_Image Ref2:_**
![image](https://github.com/user-attachments/assets/5181bd55-f2ba-41dc-a788-bf9303154c44)

I Pinned Respective Screenshot for the same for Getting idea whats the issue in this, Please help me @lpinca

**Comment by lpinca** [comment]
I don't know there is no useful information in those screenshot. Try to update the the dependency manually if needed.

1. `rm -rf node_modules package-lock.json`
2. Update the version in `package.json`
3. `npm install`.

Anyway this is not a `ws` issue. I'm closing this as answered.
