### ISSUE TITLE
idea:  support for Node WebStream / websocketstream?

### ISSUE THREAD

**Issue by seriousme** [websockets/ws#2261]
### Is there an existing issue for this?

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Description

Hi,

As I understand it `ws` currently only supports 'classical' NodeJS streams.
As NodeJS is also supporting [webstreams](https://nodejs.org/api/webstreams.html) I was wondering if `ws` could support those too?   
This could align with the [WebSocketStream API](https://github.com/whatwg/websockets/pull/48) already supported by [Chrome](https://developer.chrome.com/docs/capabilities/web-apis/websocketstream) and [Deno](https://docs.deno.com/api/web/~/WebSocketStream).

Kind regards,
Hans

**Comment by lpinca** [comment]
> As NodeJS is also supporting [webstreams](https://nodejs.org/api/webstreams.html) I was wondering if ws could support those too?

There are utilities to convert Node.js stream to Web Streams. There is no plan to support a slower alternative directly. There is also no plan to support the WeSocketStream API. [`undici`](https://github.com/nodejs/undici/blob/v7.0.0-alpha.3/docs/docs/api/WebSocket.md#class-websocketstream) already supports it.

**Comment by seriousme** [comment]
Many thanks for the answer.

Kind regards,
Hans

**Comment by guest271314** [comment]
@seriousme Here you go https://gist.github.com/guest271314/69c07d422811e82674a8d864a5412a7f.

**Comment by guest271314** [comment]
@lpinca 

> [undici](https://github.com/nodejs/undici/blob/v7.0.0-alpha.3/docs/docs/api/WebSocket.md#class-websocketstream) already supports it.

Undici's `WebSocketStream` implementation doesn't work.

**Comment by guest271314** [comment]
Pardon. `node` using Undici's `WebSocketStream` doesn't send all data unless there is a ~100 ms timeout between 2d and 3d messages. `deno` sends the data back as expected.
