### ISSUE TITLE
Bug in example/express-session-parse: POST /login fails with 405 and CORS error

### ISSUE THREAD

**Issue by thinley4** [websockets/ws#2265]
### Is there an existing issue for this?

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Description

Update the URLs for /login and /logout in app.js to http://127.0.0.1:8080.

Install and configure cors middleware to resolve CORS issues.

### ws version

"^8.18.0"

### Node.js Version

v23.2.0

### Expected result

The POST request to /login, /logout should succeed, and the server should handle the login logic as intended.

### Actual result

The server responds with a 405 Method Not Allowed error.

The browser blocks the request due to a CORS policy error

### Attachments

app.js:20  POST http://127.0.0.1:5500/login 405 (Method Not Allowed)

Has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by thinley4** [comment]
What about CORS error?

**Comment by lpinca** [comment]
There is no CORS error. The origin is the same. I don't know what happens in your environment.
