### ISSUE TITLE
connection close on serrver side with code 1001

### ISSUE THREAD

**Issue by programemail10** [websockets/ws#2268]
### Is there an existing issue for this?

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Description

Hello and thank you for the repo
I have a one way WS where I send live messages to the client 
and i have noticed that there are frequently close events with code 1001 but on the client side nothing trigered it,
so I was thinking that this is happening because of the one way messages so the server doesn't know that the client is live
I was woundering if this is right ? 
Can I set a timeout on the server side ?
I have set a ping message on client side for now, i frequently in ms should be the interval? and can I reset the interval when client recive a 'massage'

### ws version

8.18

### Node.js Version

18.14

### System

System:
    OS: Windows 11 10.0.22631
    CPU: (20) x64 13th Gen Intel(R) Core(TM) i5-13600K
    Memory: 1.00 GB / 15.78 GB

**Comment by lpinca** [comment]
See https://www.rfc-editor.org/rfc/rfc6455.html#section-7.4.1

```
1001 indicates that an endpoint is "going away", such as a server
going down or a browser having navigated away from a page.
```

`ws` doesn't close connections with that close code (unless you explicitly do it).
