### ISSUE TITLE
WS piping

### ISSUE THREAD

**Issue by ptorrent** [websockets/ws#2269]
### Is there an existing issue for this?

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Description

Hello !

What's the best way to pipe websocket to an other socket ?

### ws version

8.18.0

### Node.js Version

18

### Expected result

socket.pipe => function

### Actual result

socket.pipe => undefined

**Comment by lpinca** [comment]
See https://github.com/websockets/ws/blob/8.18.0/doc/ws.md#createwebsocketstreamwebsocket-options.

**Comment by lpinca** [comment]
I'm closing this as answered.
