### ISSUE TITLE
the same client close ws and reconnect , can still receive the old object instance sending message on server , why?

### ISSUE THREAD

**Issue by seifenk** [websockets/ws#2270]
### Is there an existing issue for this?

- [X] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by lpinca** [comment]
I'm sorry but this issue is not actionable at the moment. Please share a minimal example using only `ws` to reproduce the issue.

**Comment by seifenk** [comment]
forget it

**Comment by seifenk** [comment]
forget it
