### ISSUE TITLE
Installation on Windows (win7) fails

### ISSUE THREAD

**Issue by denised** [websockets/ws#240]
When I try `npm install ws` (on my win7 machine), I get the following errors:
```
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Platforms\x64\Microsoft.Cpp.x64.Targets(152,5): error MSB6006: "CL.exe" exited with code
-1073741515. [D:\Sandbox Consulting\node_modules\ws\build\bufferutil.vcxproj]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Platforms\x64\Microsoft.Cpp.x64.Targets(152,5): error MSB6006: "CL.exe" exited with code
-1073741515. [D:\Sandbox Consulting\node_modules\ws\build\validation.vcxproj]
```

I am using npm 1.2.32 and node 0.10.  I have just re-installed Visual Studio 2010 Express for Windows Phone, the win 7.1 sdk and python 2.7.5.   I was getting a slightly different error message before.  However both times, the errors seem to be about some inconsistency between MSBuild and the vcxproj files.

Googling, you can see quite a few questions about npm install errors on windows, sometimes stemming from trying to install bcrypt.  My suspicion is that these issues are related, and may be related to an internal inconsistency snafu with MS products, as discussed here:  http://stackoverflow.com/questions/1901279/windows-7-sdk-installation-failure.  But in my case, following their advice did not fix the problem for me (though it did change the error message)

I'm not enough of a windows dev to really debug the problem.  And I don't know how the build process is supposed to work on windows (how are the vc project files being generated, for example).   But I think if someone figures it out, there are a lot of related issues out there that would be fixed.

**Comment by heri16** [comment]
28\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
MSBUILD : error MSB4132: The tools version "2.0" is unrecognized. Available tools versions are "4.0".
