### ISSUE TITLE
Uncaught, unspecified "error" event.

### ISSUE THREAD

**Issue by seelnolu** [websockets/ws#246]
I received this error:

```javascript
events.js:74
        throw TypeError('Uncaught, unspecified "error" event.');
              ^
TypeError: Uncaught, unspecified "error" event.
    at TypeError (<anonymous>)
    at WebSocket.EventEmitter.emit (events.js:74:15)
    at Receiver.self._receiver.onerror (/opt/ws-server-v2/node_modules/ws/lib/WebSocket.js:719:10)
    at Receiver.error (/opt/ws-server-v2/node_modules/ws/lib/Receiver.js:301:8)
    at Receiver.processPacket (/opt/ws-server-v2/node_modules/ws/lib/Receiver.js:187:10)                                                                                                                     
    at Receiver.add (/opt/ws-server-v2/node_modules/ws/lib/Receiver.js:93:24)
    at CleartextStream.firstHandler (/opt/ws-server-v2/node_modules/ws/lib/WebSocket.js:678:22)
    at CleartextStream.EventEmitter.emit (events.js:95:17)
    at CleartextStream.<anonymous> (_stream_readable.js:746:14)
    at CleartextStream.EventEmitter.emit (events.js:92:17)
```
Node-ws-server seems to run for up to 1 to 48 hours, then I receive that error stated above. I am not sure what is happend. Or if the the packet being sent over web-socket is corrupt or some thing else. What should I do to fix this error?

* node - v0.10.17
* ws - v0.4.30
* express - v3.4.0

websocket code:
```javascript
var WebSocketServer = require('ws').Server;

// Create server
var httpServ = (config.webSocket.ssl) ? require('https') : require('http'),
	fs = require('fs'),
	app = null;

if (config.webSocket.ssl) {
	app = httpServ.createServer({
		// providing server with  SSL key/cert & other options
		key: fs.readFileSync(config.webSocket.ssl_key),
		cert: fs.readFileSync(config.webSocket.ssl_cert),
		ca: fs.readFileSync(config.webSocket.ssl_ca),
		requestCert: config.webSocket.requestCert,
		rejectUnauthorized: config.webSocket.rejectUnauthorized
	}, api.processRequest).listen(config.webSocket.port);
} else {
	app = httpServ.createServer(api.processRequest).listen(config.webSocket.port);
}

// passing or reference to web server so WS would knew port and SSL capabilities
var wss = new WebSocketServer({ server:app });

wss.on('connection', function (ws) {

	function onWsMessage(message) {
		...
	}

	function onWsClose() {
		socket.close(ws);
		delete ws;
	}

	function onWsError(e) {
		console.error('Client #%d error: %s', ws.id, e.message);
	}

	ws.on('message', onWsMessage);
	ws.on('close', onWsClose);
	ws.on('error', onWsError);
});

logger.log("Server started on port " + config.webSocket.port);
```

**Comment by varmando** [comment]
My quick'n'dirty hack. Use at your own risk.

```
--- ws/lib/WebSocket.js 2015-01-03 12:38:40.666944302 +0200
+++ ws-patched/lib/WebSocket.js 2015-01-03 12:40:48.570946126 +0200
@@ -824,7 +824,7 @@
   self._receiver.onerror = function onerror(reason, errorCode) {
     // close the connection when the receiver reports a HyBi error code
     self.close(typeof errorCode !== 'undefined' ? errorCode : 1002, '');
-    self.emit('error', reason, errorCode);
+    //self.emit('error', reason, errorCode);
   };

   // finalize the client
```

**Comment by matghaleb** [comment]
@Dragonight Thx very much for your hack :+1:  it's working fine for me.
Hope a fix will be provided soon..

**Comment by guillaumepotier** [comment]
@matghaleb :+1:

**Comment by boynet** [comment]
thanks, any reason its not got fixed?

**Comment by klinquist** [comment]
My API using ws started crashing every day or so, I put in a listener, and see that it's this error ("reserved fields must be empty 1002").   I am connecting to it with IPWorks ws client and we're only sending basic json strings, any ideas?

**Comment by rainder** [comment]
I get "Uncaught, unspecified "error" event. (reserved fields must be empty)" when I write raw json object to the socket after connection has established 
```js

  let socket = net.connect({
    port: 2001,
    host: '127.0.0.1'
  }, function () {
    console.log('connected');
    socket.write([
      'GET / HTTP/1.1',
      'Host: localhost',
      'Upgrade: websocket',
      'Origin: partner',
      'Connection: Upgrade',
      'Sec-WebSocket-Key: x3JJHMbDL1EzLkh9GBhXDw==',
      'Sec-WebSocket-Protocol: splyt-protocol',
      'Sec-WebSocket-Version: 13',
      '', ''
    ].join('\n'));

    setTimeout(function () {
      socket.write(JSON.stringify({}));
    }, 200);
  });
```


that fixes the problem.
````js
webSocketServer.on('connection', function (socket) {
  socket.on('error', function (err) {
    utils.printError(err);
  });
});
```

**Comment by oswsozmo** [comment]
@rainder , i have seen that error handler in other posts, and still that does not fix the problem, if you handle the error you can see what the reason is and the server keeps running but it is allowing more connections.

**Comment by lpinca** [comment]
Handling the `error` event that is emitted on the `WebSocket` instance should fix this.
Please comment back if you still have issues.

**Comment by fahmi4bd** [comment]
![problem_closeandopenitself](https://user-images.githubusercontent.com/15606963/31002984-8c70391a-a517-11e7-981a-34f490faa263.png)

Hi everybody, i need know why the ws client close and open it self in server. And this happend to all client. 

and the script in bottom `client_ws = [];

var write_error = function(txt){
    path = "./error/";
    var file_name = moment().format("MM_DD_YYYY_HH");
    var dsT = moment().format("YYYY-MM-DD HH:mm:ss");
    file_name = path+file_name+".txt";
    try{
        fs.appendFile(file_name, "[" + dsT + "] " + txt + os.EOL, function (err){
            if(err){
                console.log(err);
                fs.writeFile(file_name, "[" + dsT + "]" + txt + os.EOL , function(err) {
                    fs.appendFile(file_name, 'data to append', function (err) {
                        if (err) throw err;
                        //console.log('Saved!');
                    });
                }); 
            }else{
                //console.log('Saved!');
            }
        });
    }catch(e){
        write_error(e);
    }
}

wss.on('connection', function connection(ws){

    console.log("###");
    var ID_SOCKET = ws._ultron.id;
    client_ws.push({id:ws._ultron.id,client:ws,last_time:moment().valueOf(),state:true,subscribe:[]});
    ws.isAlive = true;
    ws.on('pong', heartbeat);
    
    ws.on('message', function(msg){
        var id = ws._ultron.id;
        var i_s = client_ws.findIndex((item)=> item.id==id);
        console.log(ID_SOCKET + ' received: %s', msg);
        try{
            var data = JSON.parse(msg);
            if(data.subscribe=="date_time"){
                if(i_s > -1){
                    client_ws[i_s].subscribe.push({sub_name:"date_time"});
                    ws.send(json_str({msg_type:"subscribe_list",data:client_ws[i_s].subscribe}));
                }
            }
            if(data.forget=="date_time"){
                console.log("Forget##########################");
                if(i_s > -1){
                    var i_r = client_ws[i_s].subscribe.findIndex((item)=> item.sub_name==data.forget);
                    if(i_r > -1){
                        client_ws[i_s].subscribe.splice(i_r,1);
                        console.log(client_ws[i_s].subscribe);
                    }
                    ws.send(json_str({msg_type:"subscribe_list",data:client_ws[i_s].subscribe}));
                }
            }
        }catch(e){
            console.log(e);
            return;
        }
    }); //message
    ws.on('error', function(msg){
        console.log(ID_SOCKET + " ERROR " + msg);
    }); //error
    ws.on('close', function(msg){
        console.log("WS Close " + ID_SOCKET);
    }); //close
    ws.send(json_str({"server":"ok"}));

});

var check_ws = function(){
    if(state_ws[0].s==true){

        state_ws[0].s = false;
        
        wss.clients.forEach(function each(ws){
            
            var id = ws._ultron.id;
            var i_s = client_ws.findIndex((item)=> item.id==id);
            if(i_s > -1){
                client_ws[i_s].last_time = moment().valueOf();
            }

            if (ws.isAlive === false) return ws.terminate();
            ws.isAlive = false;
            ws.ping('', false, true);

        });

        for (var r = 0; r < client_ws.length; r++){
            var l_t = client_ws[r].last_time;
            var s_t = moment().valueOf() - l_t;
            if(s_t > 1000){
                client_ws[r].state = false;
            }
        }
        state_ws[0].s = true;
    }
}

const interval = setInterval(function ping() {
    check_ws();
}, 100);`

**Comment by tbanj** [comment]
@rainder, thanks your fix works for me.
