### ISSUE TITLE
SocketRocket crashes Node.js WebSocket server

### ISSUE THREAD

**Issue by mattdipasquale** [websockets/ws#254]
Any idea why this is happening?

http://stackoverflow.com/questions/19544935/socketrocket-crashes-node-js-websocket

I've also reported this [issue with SocketRocjet](https://github.com/square/SocketRocket/issues/127).

**Comment by lpinca** [comment]
Adding a listener for the `error` event should prevent the app from crashing when these errors are raised.

```js
wss.on('connection', (ws) => {
  ws.on('error', (err) => handleError(err));
});
```
