### ISSUE TITLE
Error: socket hang up when query parameters used in WebSocket constructor

### ISSUE THREAD

**Issue by DavidDurman** [websockets/ws#258]
I get `Error: socket hang up` whenever I use WebSocket() from NodeJS and pass a url containing query parameters:

```
var ws = new WebSocket('http://localhost:1234'); // works fine

var ws = new WebSocket('http://localhost:1234?foo=bar'); // fails
```

I use the query parameters to send initial data to the server during the handshake. I know that I can use the headers field in the options object to do this similarly but that won't work on my clients where I use native browser WebSocket. Any hint appreciated. Thanks!

**Comment by fvukovic** [comment]
@3rd-Eden  Can u explain how to fetch nad use that parameter on the server side ?

**Comment by swapnilrohom** [comment]
you will get that info in the request - 

**CLIENT** - 
`var ws = new WebSocket('ws://localhost:1234/?id=1&name=foo');`

**SERVER** - 
```
const url = require('url');

wss.on('connection', function connection(ws, req) {
  console.log(url.parse(req.url, true).query); // { id: '1', name: 'foo' }
});
```
