### ISSUE TITLE
anyone have this working with restify?

### ISSUE THREAD

**Issue by rschiavi** [websockets/ws#259]
i see the example with express, and dug through the code/hooks a bit but can't see how to get the proper server object from restify passed into the WebSocket constructor to share the same port/server instance.

thanks..

**Comment by chirgwin** [comment]
In case this is still relevant to you or anyone else, the trick is to use `server.server`, a workaround mentioned here https://github.com/restify/node-restify/issues/717#issuecomment-66122016

This simple example using restify v4.0.4 an ws v1.0.1 works for me:

```
var restify = require("restify");
var WebSocketServer = require("ws").Server;
var server = restify.createServer();
var wss = new WebSocketServer({server: server.server});
server.listen(8080, function () {
  console.log("%s listening at %s", server.name, server.url);
});
```

**Comment by lpinca** [comment]
@chirgwin thank you. I close this, please comment or reopen if needed.
