### ISSUE TITLE
Can we make the path option case insensitive on WS server

### ISSUE THREAD

**Issue by kevbook** [websockets/ws#270]
For example ws://localhost/WS vs ws://localhost/ws should both mean the same to the WS server, currently if i set the path to "/ws", then ws://localhost/WS fails.

**Comment by lpinca** [comment]
You can now override the [`shouldHandle`](https://github.com/websockets/ws/blob/8eb551edc1b4cb0504f707cfc75da572eed1a3be/lib/WebSocketServer.js#L148-L154) method in order to customize the path matching behavior.
