### ISSUE TITLE
Remove older protocols

### ISSUE THREAD

**Issue by trygve-lie** [websockets/ws#279]
Is it any good reasons to keep older protocols around anymore? I'm specially looking at the Hixie draft.

To me it looks like most modern browsers now support protocol 13 and those browsers are now at pretty frequent upgrade rate. I've got a small feeling that there isn't that many browsers out there which will use the older protocols.

Removing some of the older protocols will simplify the code a bit.

**Comment by 3rd-Eden** [comment]
There is no reason to not have them around. There might be usecases where you do want to support every single websocket protocol available.
