### ISSUE TITLE
Installation failed on ubuntu

### ISSUE THREAD

**Issue by Hamilcore** [websockets/ws#281]
npm install ws

npm ERR! Error: failed to fetch from registry: ws
npm ERR!     at /usr/share/npm/lib/utils/npm-registry-client/get.js:139:12
npm ERR!     at cb (/usr/share/npm/lib/utils/npm-registry-client/request.js:31:9)

**Comment by 3rd-Eden** [comment]
This is an `npm` issue, not a `ws` issue.
