### ISSUE TITLE
streaming example?

### ISSUE THREAD

**Issue by benzmuircroft** [websockets/ws#284]
I'm not sure I follow your wording here:

websocket.stream([options], callback)

Streams data through calls to a user supplied function. options can be an object with members mask and binary. callback is executed on successive ticks of which send is function (data, final).

is call back the part that receives the frames/bytes/ticks I am not sure at all by this... Can You provide an example of a client/server stream exchange.

**Comment by russplaysguitar** [comment]
@kenokabe :+1:

**Comment by zhirzh** [comment]
@benzmuircroft :+1:

I too would like an example. Or at least some clarification on what the method does (or doesn't do)
