### ISSUE TITLE
socket nickname gets over written

### ISSUE THREAD

**Issue by benzmuircroft** [websockets/ws#286]
1. I'm using the address bar to define the difference between two users:

example.com?ben

example.com?jon
1. Then sending it to the server where the nickname is set then console.dir server clients list.
2. the second person (jon) visits the page the same thing happens but when I see the server clients list again; both users have different nicknames but the first client can no longer receive messages.

It's like the second user stole the server from the first user.

or there are now multiple socket instances but it only can use the last instance....

the ws.Server.clients object looks like this after the second user: 

``` javascript

[ { _socket:{{usual socket info},
                  nickname:ben
                 },
    _socket:{{usual socket info},
                  nickname:jon
                 }
} ]

```

But if ether ben or jon asks the server what his nickname is; it replies with the name of the last user to load the page...  

QUESTION: could I rename the '_socket' part to the username then do s[1]['ben'].send(); ?

**_Here is my code:**_

server side:

``` javascript
var ss={}
   , s={};
if(!ss[1]||!ss[1]._server){
    ss[1]=new WebSocketServer({port:8001});
    ss[1].on('connection',function(soc){
        s[1]=soc;
        s[1].send('get nickname for s1');
        s[1].on('message',function(_){
            console.log(_); //msg: client nickname =ben / jon
            console.log(s[1].nickname);//first time it's undefined/ then ben /then jon
            console.dir(ss[1].clients);//first time i see one socket (ben) / second time i see two sockets (ben and jon)
            });
        });}
```

client side:

``` javascript
var s={}
   , host='example.com';
if(!s[1]||s[1]===null){
    s[1]=new WebSocket('ws://'+host+':'+(8002));
    s[1].onopen=function(){
        s[1].on('message',function(_){
            if(_==='get nickname for s1'){
                //address bar = example.com?ben
                var nickname=document.location.href.split('?');
                s[1].send('msg: client nickname ='+nickname[1]);
                }
            });
        });
```

is there something like force new connection?

Or (In the server code) should I be using **ws.WebSocket** instead of **ws.Server**?

**Comment by lpinca** [comment]
The problem seems to be in your server code. When you do `s[1]=soc;` you overwrite it every time with the latest connection.
