### ISSUE TITLE
Weird binary messages

### ISSUE THREAD

**Issue by OpenGG** [websockets/ws#288]
Hey all, I put up a server, all working well:

```
ws.on('message', function(buffer, binary) {
        if(binary){
                var a = buffer.readUInt8(0, true);
                // Expects buffer to be instance of `Buffer()`
        }
});
```

Until one day it received weird binary messages, node error log shows that "TypeError: Object [object ArrayBuffer] has no method 'readUInt8' ".

I took a look, found out this weird `buffer` was not an instance of `Buffer()`, nor `ArrayBuffer()`. It came with a `.length` property, instead of `.byteLength`, more liked a `Buffer()` instance without the `.__proto__` property.

My server runs on centos6.4 x64, with node v0.10.12 installed, `npm list` shows:

```
├─┬ mysql2@0.11.4
│ └── fastqueue@0.1.0
└─┬ ws@0.4.31
  ├── commander@0.6.1
  ├── nan@0.3.2
  ├── options@0.0.5
  └── tinycolor@0.0.1
```

**Comment by lpinca** [comment]
You should definitely get a `Buffer` instance. Closing as I think it is no longer an issue in newer versions of `ws`. Please reopen if it is not the case.
Thanks.
