### ISSUE TITLE
Error 1011 when sending String object

### ISSUE THREAD

**Issue by piranna** [websockets/ws#309]
As explained at https://github.com/joyent/node/issues/7504, when sending a String object internally it gets wrongly serialized as an object. I think it would be good to check them and use .toString() method so a string literal is send instead, preventing to raise this error.

**Comment by lpinca** [comment]
I think this is an edge case not worth fixing.
Currently a `String` object is sent as as a [binary frame](https://github.com/websockets/ws/blob/08eb82725afce71f495f82e5f24d3e375a1670d2/lib/WebSocket.js#L364) whose payload is zero-filled.

```js
> var s = new String('foo')
undefined
> Buffer.from(s)
<Buffer 00 00 00>
```

I think it's better to let the consumers of this library handle the edge case.

**Comment by piranna** [comment]
Since the length is correct, I think it's a bug on Node.js Buffer object.

El 13/3/2017 9:46, "Luigi Pinca" <notifications@github.com> escribió:

Closed #309 <https://github.com/websockets/ws/issues/309>.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/websockets/ws/issues/309#event-996832325>, or mute the
thread

**Comment by lpinca** [comment]
It probably uses this [function](https://github.com/nodejs/node/blob/efec14a7d12d9e07e4efcc8e5c0ad7f80c47f83f/lib/buffer.js#L249-L255) but  in the loop `obj[i]` is a string so it fails silently.
Also the length is not correct in all cases:

```js
> var s = new String('1€')
undefined
> Buffer.from(s)
<Buffer 01 00>
> Buffer.from('1€')
<Buffer 31 e2 82 ac>
```

**Comment by piranna** [comment]
Sh*t... :-/ I would open an issue for that...
