### ISSUE TITLE
Is there any doc about the ws connection on server side

### ISSUE THREAD

**Issue by zwz** [websockets/ws#317]
See the server example given in the README.

Each connection is kept in wss.clients.
For each connection, is there also an "onclose" event handler? 
And when it happens, will it be removed from wss.clients? 
......

I hope there is a  FAQ or manual for this great module.

**Comment by lpinca** [comment]
> For each connection, is there also an "onclose" event handler?

Yes.

> And when it happens, will it be removed from wss.clients?

Yes the 'close' listener will remove the client from `wss.clients.

Closing.
