### ISSUE TITLE
Can I use this -easily- with a middleware framework like Express 4?

### ISSUE THREAD

**Issue by Analogreality** [websockets/ws#326]
I have a Express 4 website. The site has a nice router for API calls, however I want to hook up Websocket services to the same port.

What is the -easiest- way of integrating ws with it, since it uses an existing port?

**Comment by streamnsight** [comment]
@alinz example works great, but how is it possible to get session info from ws? 

if I use the `verifyClient` option on the server to get the request object, i don't have cookies or session info.

Do you know of any way to do this?
in other websocket implementations, I see methods like `wss.on('request', cb)` 
but this doesn't seem available with ws.

any suggestion on how to get underlying http session info?
Thanks

**Comment by streamnsight** [comment]
I think I figured it out, using the `server.on('upgrade')` gives access to the original req and allow to use sessionParser to generate the session info, which is then accessible to the ws server

```
server.on('upgrade', function(req, res, next) {
    sessionParser(req, {}, function () {
        console.log("REQUEST:" + req.session);
        // do stuff with the session here
    });
});

var verifyClient = function verifyClient(info, cb) {
    console.log(info);
    // get session here from info.req.session
    cb(true);
};

var wss = new ws.Server({ server: server,  verifyClient: verifyClient});
```

**Comment by tmx976** [comment]
hope this can help: I successfully parsed the session on connection, and used session info on every message. This can secure the connection with the cookie session obtained during user login, and limit the users requests also on server side.

```js
var WebSocketServer = require('ws').Server
  , http = require('http')
  , express = require('express')
  , app = express();

var bodyParser=require('body-parser');
var session=require('express-session');
var sessionParser=session({

	secret: 'goldeneye-iet',
	cookie: { maxAge: null },
	store: sessionStore,
	resave: true,
	saveUninitializes: true
})

app.use(sessionParser);
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({extended: true}));

var server = http.createServer(app);
var wss = new WebSocketServer({
	server: server,
	verifyClient: function (info, done){

		sessionParser(info.req, {}, function(){

			console.log('VERIFY', info.req.session);
			// allow connection only if session is valid and a user is logged in
			done(info.req.session && info.req.session.user && info.req.session.user.id);
		});
	}
});

wss.on('connection', function(ws) {

	ws.on('message', function(message) {

		console.log(message, ws.upgradeReq.session);
		if(message.type && canUserDo(ws.upgradeReq.session.user, message.type)){

			// do stuff here and reply to the message
		}
	}
});


```

**Comment by karatheodory** [comment]
@tmx976 Thank you, the provided example was very helpful for me. Would you mind if I make pull request to the docs with your example? Or, maybe, it is better to just modify one of the examples in the corresponding folder/create a new one?

**Comment by tmx976** [comment]
Glad to be helpful. 
I don't know which solution is best, maybe adding an example is more reachable.. 

However the two are not exclusive: it's OK to make them both.. 

Bye. 

Inviato da BlueMail



Il giorno 14:41 19/Lug/2016, alle ore 14:41, Vasily Loginov <notifications@github.com> ha scritto:

**Comment by lpinca** [comment]
The example is now available in the [examples](https://github.com/websockets/ws/tree/72cf8bee2dcdbdfdc523a5117fb0d82bcfb878bc/examples) folder thanks to @karatheodory.
