### ISSUE TITLE
Supporting  CoAP over WebSockets

### ISSUE THREAD

**Issue by gillesdemey** [websockets/ws#328]
Is this something that could be considered a feature addition?

I've glanced over the specification, (available here http://tools.ietf.org/html/draft-savolainen-core-coap-websockets-02) and it doesn't look all too complicated or different.

**Comment by sequoiar** [comment]
admit

**Comment by jixiaofei** [comment]
How to realize CoAP over WebSokcet?

**Comment by rzr** [comment]
More info there:
https://core-wg.github.io/coap-tcp-tls/draft-ietf-core-coap-tcp-tls.html#rfc.section.4

**Comment by lpinca** [comment]
I'm closing this. I think it's out of the scope of the module which is a library for the WebSocket protocol. 
CoAP over WebSockets could be implemented as an independent module that uses a WebSocket library as dependency (it does not necessarily have to be ws).
