### ISSUE TITLE
memory leak in trivially simple example

### ISSUE THREAD

**Issue by ghost** [websockets/ws#329]
i recently posted a question on stackoverflow (https://stackoverflow.com/questions/24441952/nodejs-memory-leak-in-simple-websocket-examples), whichmay be specific to 'ws'....

i know there have been some other issues describing memory leaks with 1000s of clients; in my case, it is _one_ client that simply opens/closes a websocket repeatedly...

any insights would be helpful....

**Comment by lpinca** [comment]
Closing this as the issue report is very old and I don't know if it is still valid. Please reopen if needed.
