### ISSUE TITLE
Creating a websocket client on the server

### ISSUE THREAD

**Issue by shacharz** [websockets/ws#334]
Hi,
I"m trying to create a websocket client that'll connect to my server, but I want that client to be a node.js server.
Is it possible? Has anyone done that before?
This is what I tried:
var Websocket = require('ws');
var ws = new Websocket('ws://localhost:' + port);
ws.on('open', function() {
    console.log("connected");
    ws.send('something');
});

The websocket server is run by a different server, and is the usual wss code.
I get this error:
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: socket hang up
    at createHangUpError (http.js:1472:15)
    at Socket.socketOnEnd [as onend](http.js:1568:23)
    at Socket.g (events.js:180:16)
    at Socket.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:919:16
    at process._tickCallback (node.js:419:13)

**Comment by iamblue** [comment]
+1

**Comment by cbratschi** [comment]
I am also seeing this issue. Connecting from a web browser works fine but connecting from a Node.js based ws client fails with "socket hang up". The server does not even get any upgrade headers.

Using a non-local server running the same ws server code works fine.

This is very strange.

**Comment by lpinca** [comment]
Closing this as the issue report is very old. The code posted on the issue description should work fine.
