### ISSUE TITLE
vhosting strategies?

### ISSUE THREAD

**Issue by coolaj86** [websockets/ws#335]
Is there a way to put this in the express / connect stack such that I could have multiple instances for various vhosts?

Something like this:

``` javascript
subdomain0 = connect();
subdomain0.use(ws);
app.use(vhost('xyz.example.com'), subdomain0);

subdomain1 = connect();
subdomain1.use(ws);
app.use(vhost('abc.example.com'), subdomain1);
```

**Comment by lpinca** [comment]
I think this could be done by using multiple server instances is `noServer` mode. Similar to this example: https://github.com/websockets/ws#multiple-servers-sharing-a-single-https-server

I'm closing this. Please reopen or comment if I'm wrong or missing something.
