### ISSUE TITLE
Constantly crashing when sending. Error not opened

### ISSUE THREAD

**Issue by thailemon** [websockets/ws#337]
I'm suspecting it's because client is trying to send to a dead socket.
Any other way to handle this?

My scenario is mobile App -> browser. App gets disconnect event too late, so it keeps sending packets while the browser is already disconnected.

Here's my test code:

```
var Client = [];
function findClient(url) {
return (Client.indexOf(url));
}


wss.on('connection', function(ws) {
    Client.push(ws);
    console.log('Connected: %s', ws.upgradeReq.url);
    console.log('Clients: %s', Client.length);

ws.on('message', function(message, flags) {

    for( var i = 0; i < Client.length; i++) {
         Client[i].send(message, function(error) {
         if(error != null) {
         console.log('error: %s', error);
         ws.close();
         ws._socket.destroy();
         Client.splice(findClient(ws.upgradeReq.url));
}
});

ws.on('close', function(user) {
    console.log('Disconnected: %s', ws.upgradeReq.url);
    ws.close();
    ws._socket.destroy();
    Client.splice(findClient(ws.upgradeReq.url));
    console.log('Clients: %s', Client.length);



  });
       ws.on('error', function(error) {
        if(error != null) {
         console.log('error: %s', error);
         ws.close();
         ws._socket.destroy();
         Client.splice(findClient(ws.upgradeReq.url));
    }
  });

    ws.on('close', function(user) {
    console.log('Disconnected: %s', ws.upgradeReq.url);
    ws.close();
    ws._socket.destroy();
    Client.splice(findClient(ws.upgradeReq.url));
    console.log('Clients: %s', Client.length);

  });
```

Any help appreciated :)

**Comment by galambalazs** [comment]
I've seen this problem come up for about 99% of the people starting to use this library. 

Interesting to note that the WHATWG spec only talks about throwing an error when the socket is in CONNECTING state (otherwise the send simply has no effect). 

https://html.spec.whatwg.org/multipage/comms.html#dom-websocket-send

> The send(data) method transmits data using the connection. If the readyState attribute is CONNECTING, it must throw an InvalidStateError exception. Otherwise, the user agent must run the appropriate set of steps from the following list: [...]

**Comment by zag2art** [comment]
Imo, throwing an error is a good for browser but it's absolutely bad practice for server.

**Comment by galambalazs** [comment]
My opinion is that send is inherently asynchronous and it should be left for the callback to handle errors (if needed).

**Comment by piecioshka** [comment]
+1

**Comment by GeekLad** [comment]
The second parameter for the send method is an error handler.  Do something like this where you're sending messages:

```javascript
ws.send(message, function(error) {
	// Do something in here here to clean things up (or don't do anything at all)
});

**Comment by lpinca** [comment]
Add a listener for the `error` event to handle these cases or use a callback as suggested by @GeekLad.

**Comment by JacopoDaeli** [comment]
@lpinca adding a listener won't solve the problem. The only way is use use the callback, or add a try/catch statement around `send()`:

```js
// from lib/WebSocket.js
if (this.readyState !== WebSocket.OPEN) {
  if (cb) cb(new Error('not opened'));
  else throw new Error('not opened');
  return;
}
```

**Comment by JacopoDaeli** [comment]
I open a PR to fix/add this feature: https://github.com/websockets/ws/pull/1300

**Comment by Heck24** [comment]
for me this error handling worked:
`	setInterval(()=>{
		try { if (ws.readyState != WebSocket.CLOSED) { ws.send(`${new Date()}`);} }
		catch(e) {console.log(e);}
	});`

**Comment by satyaraj479** [comment]
that 

> 
> 
> for me this error handling worked:
> ` setInterval(()=>{ try { if (ws.readyState != WebSocket.CLOSED) { ws.send(`${new Date()}`);} } catch(e) {console.log(e);} });`

that worked for me !
