### ISSUE TITLE
ws becomes unstable (not open) after getJSON calls

### ISSUE THREAD

**Issue by benzmuircroft** [websockets/ws#339]
Strange problem really! my app uses ws 0.4.31 and sends many messages fine every time but  then when it does any getJSON the socket may or may not be open, I don't understand why using extra https would cause it to become unstable but all I can say is that after I use it something causes the socket to close.

It was happening with npm jquery $.getJSON aswell so I switched to this:

getJSON=function(options,callback){var https=require("https");var req=https.request(options,function(res){var buffer='';res.setEncoding('utf8');res.on('data', function (chunk){buffer+=chunk;});res.on('end',function(){var data=JSON.parse(buffer);callback(data,res.statusCode);});});req.end();};

getJSON("https://blockchain.info/tobtc?currency=USD&value=1",function(current){
    socket.send('data: '+current); //not open
    });

But something is still melting things 50-60% of the time when I try to send after getJSON

I have ticked of every other module I really am leaning toward the use of http/https as conflicting with something ws. It's not a case of proper error handling as I am doing that but really learning what is going on with the instability and how to avoid it

Any clue?

**Comment by lpinca** [comment]
Closing as this issue report is very old, if the issue still happens with a recent version of `ws` please post back.

Thanks.
