### ISSUE TITLE
Add support for the per-frame DEFLATE extension

### ISSUE THREAD

**Issue by benvanik** [websockets/ws#34]
Spec is here: http://tools.ietf.org/html/draft-tyoshino-hybi-websocket-perframe-deflate-05

This just landed in WebKit/Chrome. Here's the CL: http://trac.webkit.org/changeset/108731

**Comment by sonnyp** [comment]
Support has landed into Firefox https://bugzilla.mozilla.org/show_bug.cgi?id=792831

**Comment by sonnyp** [comment]
I think this can be closed. per-frame deflate has been obsoleted by per-message compression https://tools.ietf.org/html/draft-ietf-hybi-permessage-compression-19 and implemented in #409

**Comment by zz85** [comment]
@sonnyp looks promising! looks like permessage-compression is also available in blink/chromium https://code.google.com/p/chromium/issues/detail?id=280910 but not yet in webkit https://bugs.webkit.org/show_bug.cgi?id=98840?

**Comment by zz85** [comment]
Firefox 36a2 (developer's edition) does not seem to support permessage-deflate yet.. will check back and see.

**Comment by sonnyp** [comment]
@zz85 it will be in 37

**Comment by 3rd-Eden** [comment]
https://github.com/websockets/ws/blob/master/doc/ws.md#optionspermessagedeflate
