### ISSUE TITLE
Is there a way to know the page path from where the ws connection is being called?

### ISSUE THREAD

**Issue by shacharz** [websockets/ws#347]
e.g: A page www.mysite.com/path/to/page.html loads a script that starts ws connection with ws server
Can we know in the ws server what's the path/to/page.html is? - The referrer that is.
All I see is origin/host and the url of the actual ws connection.

**Comment by bradisbell** [comment]
FYI, `ws.upgradeReq` is now undefined...

**Comment by diegoddox** [comment]
You can find this information on the `req` 
```
wss.on('connection', (ws, req) => {
  console.log(req.url, req.headers);
});
```

**Comment by shacharz** [comment]
> wss.on('connection', (ws, req) => {
>   console.log(req.url, req.headers);
> });

That's incorrect, the url is the url of the websocket request not the page, and the referrer is not being sent as a header by browsers.

see https://github.com/websockets/ws/issues/347#issuecomment-66106654 to work around

**Comment by fedd** [comment]
That's really a strange solution that the websocket connection doesn't carry information about the referring page by default. Websockets are normally open from a page, and an application should be able to provide a page-specific service for that page, for example, some news regarding an entity that page is about.
