### ISSUE TITLE
Error: invalid url

### ISSUE THREAD

**Issue by montaro** [websockets/ws#348]
I'm trying to run some script which depends on ws and I get `Global Error: invalid url` raised from the ws library.
I tried to try the library itself and found the same error like this:

```
arefaey@arefaey-MacBook-Pro ~> wscat -c ws://echo.websocket.org
error: Error: unexpected server response (400)
> ~                                                                                                                                       arefaey@arefaey-MacBook-Pro ~> wscat -cn ws://echo.websocket.org

/usr/local/lib/node_modules/ws/lib/WebSocket.js:477
  if (!serverUrl.host && !isUnixSocket) throw new Error('invalid url');
                                              ^
Error: invalid url
    at WebSocket.initAsClient (/usr/local/lib/node_modules/ws/lib/WebSocket.js:477:47)
    at new WebSocket (/usr/local/lib/node_modules/ws/lib/WebSocket.js:59:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/ws/bin/wscat:189:12)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
```

This happens on OS X and Linux BTW, Any advices?

**Comment by Muneem** [comment]
I am also facing same issue and i am using latest version of websocket

**Comment by Vadim-Pelyushenko** [comment]
When trying this example from the package page:
```
import { WebSocketServer } from 'ws';

const wss = new WebSocketServer({ port: 8080 });

wss.on('connection', function connection(ws) {
  ws.on('message', function incoming(message) {
    console.log('received: %s', message);
  });

  ws.send('something');
});
```

I get:
```
SyntaxError: Invalid URL: [object Object]
    at initAsClient (Z:\projects\online-tic-tac-toe\node_modules\ws\lib\websocket.js:625:13)
    at new WebSocket (Z:\projects\online-tic-tac-toe\node_modules\ws\lib\websocket.js:83:7) 
    at Object.<anonymous> (Z:\projects\online-tic-tac-toe\server.js:3:13)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)   
    at node:internal/main/run_main_module:17:47
```

Eventually tried `const wss = new ws.WebSocketServer({ port: 8080 });` instead of
`const wss = new WebSocketServer({ port: 8080 });`
and that fixed it... this took quite a while to figure out.

**Comment by mrhery** [comment]
> 
> 
> When trying this example from the package page:
> 
> ```
> import { WebSocketServer } from 'ws';
> 
> const wss = new WebSocketServer({ port: 8080 });
> 
> wss.on('connection', function connection(ws) {
>   ws.on('message', function incoming(message) {
>     console.log('received: %s', message);
>   });
> 
>   ws.send('something');
> });
> ```
> 
> But can't use "import" so changed it to use `const ws = require('ws');`
> 
> I get:
> 
> ```
> SyntaxError: Invalid URL: [object Object]
>     at initAsClient (Z:\projects\online-tic-tac-toe\node_modules\ws\lib\websocket.js:625:13)
>     at new WebSocket (Z:\projects\online-tic-tac-toe\node_modules\ws\lib\websocket.js:83:7) 
>     at Object.<anonymous> (Z:\projects\online-tic-tac-toe\server.js:3:13)
>     at Module._compile (node:internal/modules/cjs/loader:1101:14)
>     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
>     at Module.load (node:internal/modules/cjs/loader:981:32)
>     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
>     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)   
>     at node:internal/main/run_main_module:17:47
> ```
> 
> Eventually tried `const wss = new ws.WebSocketServer({ port: 8080 });` instead of `const wss = new WebSocketServer({ port: 8080 });` and that fixed it... was quite a bit of searching online before I randomly tried that...

I faced the same problem. But then got few ways to worked it out. One of them is:

```
const wss = new WebSocketServer({ port: 8080 });
```

change to 
```
const wss = new WebSocketServer.Server({ port: 8080 });
```

I think it's maybe got few updates to the library which most tutorial dont update them yet.
