### ISSUE TITLE
Allow HTTP authorization

### ISSUE THREAD

**Issue by binarykitchen** [websockets/ws#362]
I have a test page here, protected with .htpasswd, which works fine whenever I visit it.

That test page also runs websockets with this module. Whenever I pass that HTTP authorization, the page begins to load with the script and tries to establish a connection to the server but a 401 occurs:

```
WebSocket connection to 'wss://staging.mytestsite.io/' failed: Error during WebSocket handshake: Unexpected response code: 401 
```

Why? Shouldn't WebSockets from the same domain be automatically authorized whenever the HTTP authorization was successful?

**Comment by nahuel** [comment]
Now all the browsers but Safari works with Websockets + Basic Authentication (but ws doesn't), see:

https://bugs.chromium.org/p/chromium/issues/detail?id=123862
https://bugs.webkit.org/show_bug.cgi?id=80362

I think this bug must be reopened.

**Comment by nahuel** [comment]
quoting https://tools.ietf.org/html/rfc6455 :

>   12.  The request MAY include any other header fields, for example,
>         cookies [RFC6265] and/or authentication-related header fields
>         such as the |Authorization| header field [RFC2616], which are
>         processed according to documents that define them.

**Comment by lpinca** [comment]
@nahuel ws works with basic auth, see https://github.com/websockets/ws/blob/9c39adfc9734073c1e949c62d56614f3c315ebee/test/websocket.test.js#L1850-L1863. You can specify username and password in the connection URL or build the header manually.
