### ISSUE TITLE
SSL certificate issue and config options

### ISSUE THREAD

**Issue by tomalex0** [websockets/ws#365]
I'm trying to connect secured websocket layer and getting DEPTH_ZERO_SELF_SIGNED_CERT.
Is there a way to pass certificate as config option to resolve this, I will anyway get proper certificate. 
Like to know what all config options i can give.

```
var ws = new WebSocket('wss://test.com/websock');
```

**Comment by xmax5** [comment]
![2022-08-16_19-22-51](https://user-images.githubusercontent.com/91722354/184930022-a5248744-bc00-4e64-979e-0c71927ca6bb.png)

**Comment by xmax5** [comment]
![2022-08-16_19-22-51 (2)](https://user-images.githubusercontent.com/91722354/184930329-c5379ffa-7090-42c4-9601-03f510542e7d.png)
