### ISSUE TITLE
How to get the HTTP GET request in server.on('connection`) ?

### ISSUE THREAD

**Issue by ibc** [websockets/ws#378]
My WS server verifies some stuff in the HTTP GET WebSocket Upgrade request (via `verifyClient` and `handleProtocols`), but then, once my WebSocket server has validated it, I need to tell the application about a new connection and I need to provide it with the HTTP request so the application can inspect the URL query, the Origin header or whatever.

I do not see in the WebSocket API any way to get the HTTP request. Is it?

**Comment by Bacto** [comment]
Hi,

You can get parameters by parsing the upgradeReq.url:

```
var url = require('url');

wss.on('connection', function(client) {
	url.parse(client.upgradeReq.url, true).query;
});
```

**Comment by lpinca** [comment]
As @Bacto said the `upgradeReq` property stores a reference to the upgrade request.
