### ISSUE TITLE
ws.Server.on('connection') is called even if the TCP connection was closed by client

### ISSUE THREAD

**Issue by ibc** [websockets/ws#380]
Usecase:
- Receive a WS connection.
- `options.verifyClient(info, cb)` is called, but the app does not invoke `cb(true)` immediately but after an asynchronous operation that takes 2 seconds.
- But before those 2 seconds the client disconnects the TCP connection.
- Later when the app invokes `cb(true)` the `ws.Server.on('connection')` event is fired, and if you log `socket.readyStatus` is gives you `WebSocket.OPEN`, which IMHO SHOULD NOT.

Perhaps ws should check the socket status just before firing the 'connection' event?

Thoughts?

**Comment by lpinca** [comment]
https://github.com/websockets/ws/pull/890 should fix this as it checks if the socket is [writable](https://github.com/websockets/ws/pull/890/files#diff-b399c7c93b40d23eb7415a67c99b89a7R245) and the server is `allowHalfOpen` is `false`.

It might makes sense to also check if the socket is readable as @ibc did in #379 to handle cases where `allowHalfOpen` is true.

Thanks for reporting this.
