### ISSUE TITLE
ws does not support multiple paths

### ISSUE THREAD

**Issue by ibc** [websockets/ws#381]
```
var ws = require('ws');
var http = require('http');

var httpServer = http.createServer();
httpServer.listen(10080, '127.0.0.1');

var ws1 = new ws.Server({server:httpServer, path:"/qwe"});
ws1.on('connection', function(){
  console.log("connection on /qwe");
});

var ws2 = new ws.Server({server:httpServer, path:"/asd"});
ws2.on('connection', function(){
  console.log("connection on /asd");
});
```

OK, now go to a browser (Chrome for example) and open a ws connection to both paths:

```
CHROME: new WebSocket("ws://local.protoo.org:10080/qwe");
NODE: > connection on /qwe

CHROME: new WebSocket("ws://local.protoo.org:10080/asd");
NODE: > connection on /qwe  <--- same!
```

And even worst, it behaves wrong after that and does not react on new events, etc. For example try to connect to path "/nonexist" and later again to "/qwe", nothing happens then.

So, is this feature really tested?

**Comment by yarax** [comment]
Hi! I proposed a pull request https://github.com/websockets/ws/pull/481 for using regexp both with string paths

**Comment by sushantdhiman** [comment]
I am having same issue when sharing the WS servers with same express server.

**Comment by lpinca** [comment]
I agree with @ibc. The feature is kinda broken when using 2+ server that share the same HTTP server.
I've also proposed a PR (https://github.com/websockets/ws/pull/885) to remove the broken feature.

**Comment by ibc** [comment]
Closed without proper rationale. Good project management, @3rd-Eden

**Comment by lpinca** [comment]
@ibc I think it has been closed because #885 has been merged.

**Comment by ibc** [comment]
Nice to know, thanks. So sorry for my comment.

**Comment by lpinca** [comment]
No problem.
