### ISSUE TITLE
Can't get peer certificate on wss connect

### ISSUE THREAD

**Issue by scaret** [websockets/ws#389]
Secure websocket works, but I can't find a function/getter like tls.getPeerCertificate to get the certificate information from the server when wss socket is connected. Currently I'm hacking to `Websocket.js` to have this functionality, but it's nice if you have this feature.

**Comment by alanhoff** [comment]
Actuallly you can pass an option to your https server and request the client cert:

```javascript
var ws = require('ws');
var fs = require('fs');
var https = require('https').createServer({
  key: fs.readFileSync('keys/key.pem'),
  cert: fs.readFileSync('keys/cert.pem'),
  requestCert: true,
}, function(req, res) {
  res.end('Please upgrade the connection');
}).listen(8080);

var server = new ws.Server({
  server: https,
  verifyClient: function(info, cb) {
    console.log(info.req.connection.getPeerCertificate(true));
    cb(true);
  }
});

server.on('connection', function(client) {
  console.log('Connected');
});
```

**Comment by scaret** [comment]
Thank you @alanhoff ! I think it's what I wanted
