### ISSUE TITLE
text frame aggregation

### ISSUE THREAD

**Issue by PeterA1** [websockets/ws#408]
Hi,

I am porting a WebSocket app that works fine in iOS & desktop Chrome & Safari to Android.  Since the android platform I'm using has no native WebScoket implementation, I'm using a library which I believe is based on the Java WebSocket implementation.  However if I try and send from node.js to the client a message of above about 8k bytes the socket closes with message...

'text frame aggregation disabled', code 1008.

How would I enable text frame aggregation?

For now I will slice the messages.

Best Regards
Peter

**Comment by lpinca** [comment]
> How would I enable text frame aggregation?

I don't know but it sounds like it is something that should be handled by the Java library used on Android.

Closing as I think this isn't a `ws` issue. Please comment or reopen if needed.
