### ISSUE TITLE
High memory usage (or memleak?)

### ISSUE THREAD

**Issue by nicokaiser** [websockets/ws#43]
Hi all!

I created a small example for the memory leak my ws (or WebSocket.IO) server has. 

This small server only accepts WebSocket connections and sends one message.
Client count and memory usage is displayed every 2 seconds.

The client open 10,000 connections, then every minute 2,000 new connections are openend and 2,000 are closed, so the count stays at about 10,000. 

https://gist.github.com/2152933

![Memory Graph](http://f.cl.ly/items/1o3a3i0S1h2n2q2O0Y3V/ws-test-10min.png)

The graph is the output of server.js (run on a EC2 "large" instance with node 0.6.13 and ws 0.4.9).
- Server startup: RSS is about 13 MB (0 clients)
- When the first 10,000 clients are connected, RSS = 420 MB
- During the next 10 minutes clients come and go (see client.js), RSS grows to 620 MB
- heap usage stay stable
- Client is stopped =(> RSS falls to 220 MB waited 1 minute for GC)
- After 1 minute, client ist started again => RSS jumps to 440 MB (10,000 clients)
- During the next minutes, RSS grows again up to 630 MB (after 10 minutes)
- Client is stopped => RSS falls to 495 MB
- When I start the client again, RSS usage seems stable (at least compared to the two runs before).

Questions:
1. 400 MB for 10.000 clients (with no data attached) is much. But I see JS as an interpreted language is not that memory optimized than C. BUT, why does opening and closing 20.000 connections (during the 10 minute period) consume another 200 MB? 
2. The process is at about 30% CPU, so the GC has the chance to kick in (and, ws uses nextTick, so the GC really has a chance)
3. Why is he GC unable to free the memory after the second run? Can't be the Buffer/SlowBuffer problem (fragmented small Buffers in different 8k SlowBuffers), as there are no Buffers used anymore...
4. Why does the RSS usage remain pretty stable after the first two runs? 

The effect is the same (but slower) with only 1,000 client connections per minute, but things get even worse when I don't stop the client after 10 minutes. Our production server runs with about 30-40% CPU constantly (30k connections), 1-5% at night (1-2k connections), but is never completely idle. The growing of the RSS usage never seems to stop.

On the production server, RSS grows until node crashes (0.4.x crashes at 1 GB) or the process gets killed by the system (0.6 supports more than 1 GB).

I'll try two things tomorrow:
- The same setup with Node 0.4 (as 0.4 seems much better in regards of memory consumption than 0.6), and 
- with different WebSocket libraries, e.g. "websock", which is not 100% stable but only consumes one third (still leaking though), and a variant of WebSocket.IO with the original Socket.IO (not ws!) hybi parsers, see my "nows" branch.

The setup is a default Amazon EC2 large instance, so this must be an issue for anyone who runs a WebSocket server using ws (or must likely also WebSocket.IO with ws receivers) with _some_ traffic. I refuse to believe Node is not capable of serving this.

Or am I missing something?

Nico

**Comment by damianobarbati** [comment]
@nicokaiser how did you solve this in the end? I see a very high memory consumption, and when sockets are closed memory is still used (at least most of it).

**Comment by damianobarbati** [comment]
@nicokaiser could you show a simplified example about "avoiding retained references"?
I typically associate data to ws object (i.e: `ws.token = token`) but shouldn't `close` event and `terminate` method be enough to have the gc clean up the empty references?

Thanks for helping!

**Comment by nicokaiser** [comment]
Hi!

Yes, the GC got much better since Node 6 or 8. I‘m trying to remove event listeners on the connection objects etc., but associated data should not be a big problem. You could try to unset these properties in the close event to see if there is a difference, but I doubt there is much impact.

Also, disabling the compression made a huge difference back then in my case...

Nico
