### ISSUE TITLE
Readme's binary-send use case has ambiguous endianness

### ISSUE THREAD

**Issue by popham** [websockets/ws#435]
The _Sending binary data_ section of the Readme sends `var array = new Float32Array(5);` over the wire.  I'm assuming that the `ArrayBuffer` that underlies `array` gets sent over the wire.  Since the server and client environments may have different endianness, sending `array` could produce garbage.  I figure that `Buffer`, `Uint8Array`, and `Int8array` can be sent, but multibyte-arrays should be using the `DataView` api.

I'm no expert on browser compatibility.  Do all browsers have endianness aligned with Node's?  [pretty much](http://stackoverflow.com/questions/7869752/javascript-typed-arrays-and-endianness).

**Comment by lpinca** [comment]
> I'm assuming that the ArrayBuffer that underlies array gets sent over the wire.

Correct, the `ArrayBuffer` is converted to a `Buffer` which is then sent over the wire.

The issue shouldn't exist as you you still get back a `Buffer` or an `ArrayBuffer` and it's up to you to handle the endianness if it doesn't align with the server endianness.
