### ISSUE TITLE
Error pop-up when install ws

### ISSUE THREAD

**Issue by liboshi** [websockets/ws#444]
ENV Information:
OS Version: Windows 7 x64 and Windows 8.1 x64
Nodejs Version: node-v0.10.36-x64

Console output:
C:\Users\Administrator>npm install --save ws
Error: ENOENT, stat 'C:\Users\Administrator\AppData\Roaming\npm'

C:\Users\Administrator>mkdir AppData\Roaming\npm

C:\Users\Administrator>npm install --save ws
|
> ws@0.7.0 install C:\Users\Administrator\node_modules\ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

C:\Users\Administrator\node_modules\ws>node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild

Looking forward for your reply.
Thanks in advance.
-Boush

**Comment by 3rd-Eden** [comment]
Could you provide the full npm output?

**Comment by liboshi** [comment]
### Full npm output:
C:\Users\Administrator>npm install --save ws
\
> ws@0.7.0 install C:\Users\Administrator\node_modules\ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)


C:\Users\Administrator\node_modules\ws>node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
VCBUILD : error : project file 'C:\Users\Administrator\node_modules\ws\build\bufferutil.vcproj' was not found or not a valid project file. [C:\Users\Administrator\node_modules\ws\
build\binding.sln]
VCBUILD : error : project file 'C:\Users\Administrator\node_modules\ws\build\validation.vcproj' was not found or not a valid project file. [C:\Users\Administrator\node_modules\ws\
build\binding.sln]
ws@0.7.0 node_modules\ws
├── options@0.0.6
├── ultron@1.0.1
└── nan@1.5.3

### npm-debug.log
$ cat npm-debug.log
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '--save',
1 verbose cli   'ws' ]
2 info using npm@1.4.28
3 info using node@v0.10.36
4 verbose node symlink C:\Program Files\nodejs\\node.exe
5 error Error: ENOENT, stat 'C:\Users\Administrator\AppData\Roaming\npm'
6 error If you need help, you may report this *entire* log,
6 error including the npm and node versions, at:
6 error     <http://github.com/npm/npm/issues>
7 error System Windows_NT 6.1.7601
8 error command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save" "ws"
9 error cwd C:\Users\Administrator
10 error node -v v0.10.36
11 error npm -v 1.4.28
12 error path C:\Users\Administrator\AppData\Roaming\npm
13 error code ENOENT
14 error errno 34
15 verbose exit [ 34, true ]

### builderror.log
$ cat builderror.log
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Administrator\node_modules\ws
gyp ERR! node -v v0.10.36
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok

**Comment by liboshi** [comment]
Hi

I have two questions about the build processes:
-Must Visual studio be installed?
-Which version of Visual studio should I use?

**Comment by 3rd-Eden** [comment]
@liboshi The reason that the build is failing is because of the (optional) binary addons fail to install and that is probably due to a missing visual studio. The `node-gyp` that npm uses the build binary addons states:

  * On Windows:
    * [Python][windows-python] ([`v2.7.3`][windows-python-v2.7.3] recommended, `v3.x.x` is __*not*__ supported)
    * Windows XP/Vista/7:
      * Microsoft Visual Studio C++ 2010 ([Express][msvc2010] version works well)
      * For 64-bit builds of node and native modules you will _**also**_ need the [Windows 7 64-bit SDK][win7sdk]
        * If the install fails, try uninstalling any C++ 2010 x64&x86 Redistributable that you have installed first.
      * If you get errors that the 64-bit compilers are not installed you may also need the [compiler update for the Windows SDK 7.1]
    * Windows 7/8:
      * Microsoft Visual Studio C++ 2012/13 for Windows Desktop ([Express][msvc2012] version works well)

[windows-python]: http://www.python.org/getit/windows
[windows-python-v2.7.3]: http://www.python.org/download/releases/2.7.3#download
[msvc2010]: http://go.microsoft.com/?linkid=9709949
[msvc2012]: http://go.microsoft.com/?linkid=9816758
[win7sdk]: http://www.microsoft.com/en-us/download/details.aspx?id=8279
[compiler update for the Windows SDK 7.1]: http://www.microsoft.com/en-us/download/details.aspx?id=4422

I'm in the progress of moving out the binary addons that are build in to this module so we can leverage the `optionalDependencies` from npm to prevent these kind of build failures in the future.

**Comment by liboshi** [comment]
@3rd-Eden 
I have tested follow your above comments, installation process work fine :-)
I installed Visual Studio C++ 2008 on my Windows PCs.

Thanks very much!!!
