### ISSUE TITLE
Segmentation fault in node 0.12

### ISSUE THREAD

**Issue by PrinC** [websockets/ws#448]
I've got an segementation fault with ws0.7.1, development environment is list below:
node.js 0.12, ws0.7.1,gcc 4.9.1 ubuntu x64 in vmware workstation

The same application runs successfully in centos 6.5, gcc 4.4.7;

The output in gdb is:
Program received signal SIGSEGV, Segmentation fault.
0x00007fffef57af04 in BufferUtil::Mask(v8::FunctionCallbackInfo<v8::Value> const&) ()
   from /home/princ/workspace/nico-server/node_modules/pomelo/node_modules/pomelo-admin/node_modules/socket.io-client/node_modules/ws/build/Release/bufferutil.node

**Comment by 3rd-Eden** [comment]
This doesn't seem to use the latest ws build. Can you post the output of your `npm ls` and the full npm install output?

**Comment by 3rd-Eden** [comment]
https://github.com/NetEase/pomelo/blob/master/package.json#L31 - It's still using the old socket.io which doesn't depend on ws@0.7. They should upgrade to the latest version of socket.io and engine.io-client should bump to https://github.com/Automattic/engine.io-client/blob/master/package.json#L26 0.7 as well.

**Comment by PrinC** [comment]
I change the package.json of pomelo-admin, the output of segmentation fault is with ws 0.7.1

**Comment by 3rd-Eden** [comment]
Provide a full output of the build and the output of npm ls.

**Comment by PrinC** [comment]
npm ls:
![u62c1wy 07652_ctba 4 0](https://cloud.githubusercontent.com/assets/2363404/6150174/c74e41fe-b248-11e4-8bb7-7bccff63276f.png)

build:
![6jpl5pqa09 g j_knfhwp j](https://cloud.githubusercontent.com/assets/2363404/6150207/fc6e17b0-b248-11e4-8270-c9a717c54788.jpg)

**Comment by PrinC** [comment]
And the bt of gdb:
```
#0  0x00007fffef57b507 in BufferUtil::Mask(v8::FunctionCallbackInfo<v8::Value> const&) ()
   from /home/princ/workspace/nico-server/node_modules/pomelo/node_modules/pomelo-admin/node_modules/socket.io-client/node_modules/ws/node_modules/bufferutil/build/Release/bufferutil.node
#1  0x000000000082a11c in v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) ()
#2  0x000000000084c1ff in v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*) ()
```

**Comment by aisouard** [comment]
I have exactly the same segmentation fault at the same location.
I am using another WebSocket implementation since I need the simulated W3CWebSocket one, I've reported the same bug over there : https://github.com/theturtle32/WebSocket-Node/issues/196
