### ISSUE TITLE
WebSocket connection closes immediately

### ISSUE THREAD

**Issue by fredrikslattman** [websockets/ws#449]
The WebSocket client part of this library has stopped working for me. I always get the log ``` closed with code 1000 ``` when running the following code, but when I'm actually connecting to my server with the native WebSocket implementation in the browser it works fine. My server doesn't even get the request, so it seems to be in the WebSocket connection layer.

Can this issue be related to a upgradeReq.url in combination with a sub protocol?

Example
----
``` javascript
var WebSocket = require('ws');
var ws = new WebSocket('ws://localhost:3001/?client=MTI3&tag=8f261', 'protocol.example.com');

ws.on('open', function open() {
  ws.send('something');
});

ws.on('close', function (code) {
  console.log('closed with code', code);
});
```

**Comment by 3rd-Eden** [comment]
well if you want to connect with an unknown protocol the connection would be closed by the server.

**Comment by fredrikslattman** [comment]
I'm aware of this, I'll update the issue with the server implementation. It's not related to the sub protocol.
