### ISSUE TITLE
How to close a client from server ?

### ISSUE THREAD

**Issue by jonixfu** [websockets/ws#450]
How to close a client from server ?

**Comment by jonixfu** [comment]
in timeout state.
or dead line state. 

thanks

**Comment by cra0kalo** [comment]
sender.terminate(); ??

**Comment by 3rd-Eden** [comment]
You use exactly the same API as a websocket client. which is the close method.

**Comment by Dillybob92** [comment]
@3rd-Eden  However the close state does NOT delete the socket object from the server, how do we do that? For example:

```
var WebSocketServer = require('ws').Server
  , wss = new WebSocketServer({ port: 9300 });

wss.on('connection', function connection(socket) {
  socket.on('message', function incoming(message) {
    
  });
  
socket.on('close', function () {
		   socket.close();
		   
		   
		
		
		
		setTimeout(function(){
			
				console.log(socket);
				
			
		}, 1000);
		
	
  
});

 
});
```

It will still console.log the socket even after closing the connection, how can we delete that so it's not left in memory?

**Comment by 3rd-Eden** [comment]
V8's garbage collection takes care of that. If there are no more references to it, it will eventually be removed.

**Comment by Dillybob92** [comment]
@3rd-Eden how long does it take for V8 to do that though? If a user keeps refreshing the page instantly over and over again the unnecessary memory consumption will be very evident. Is there a way to delete that socket object data upon closing?
