### ISSUE TITLE
Support for automatic reconnecting client?

### ISSUE THREAD

**Issue by Jakobud** [websockets/ws#455]
If the client looses connection for whatever reason (temporarily loss of internet connection, server temporarily offline, etc), it would be awesome if this library would automatically make reconnection attempts.

**Comment by 3rd-Eden** [comment]
That's out of the scope of this library and there already projects who implement this so it makes no sense to add it here as well.

**Comment by Jakobud** [comment]
Can you point me to some projects that do that? I have only ever seen this client side library: https://github.com/joewalnes/reconnecting-websocket

**Comment by Bomper** [comment]
@Jakobud: this was discussed in #431
