### ISSUE TITLE
How do I grab the client data and objects?

### ISSUE THREAD

**Issue by Dillybob92** [websockets/ws#460]
For example:
http://i.gyazo.com/d08c7e7e1ab28871ccc25350a716cb47.png

I'm using this to loop through the client data.
Let's say I want to grab the users IP address, or.. the clients user-agent? It's inside such a huge array, I have no idea how to select the data. I did console.log(client) the data is so big on the my console screen I cannot even see where to begin....

`wss.clients.forEach(function each(client) {
			client.send("SERVER Testing "+client+"");
			 console.log(client);
		});`

**Comment by Dillybob92** [comment]
Nvm this question guys, I figured it out. I just wish there was a documentation and manual of all the properties in the socket object...

**Comment by 3rd-Eden** [comment]
https://github.com/websockets/ws/blob/master/doc/ws.md

pretty much documents all the things..

**Comment by Dillybob92** [comment]
No it doesn't There is no documentation for all the properties in the WS object.

**Comment by 3rd-Eden** [comment]
@Dillybob92 I'm sorry that I didn't link to the part of the documentation where we list the properties but here you go: https://github.com/websockets/ws/blob/master/doc/ws.md#class-wswebsocket and the documentation made the assumption that people know the properties of a http request or know where they can find them or how to google it.. Maybe we should linked the part where it said "http request" and link it to http://nodejs.org/api/http.html#http_class_http_clientrequest.

As for the remoteAddress not showing up, why on earth are you ranting about that here while it's not even remotely (ooh see what I did there) related to this project as it's clearly something that Node.js does.

**Comment by Dillybob92** [comment]
Huh? I'm not talking about the http request stuff. You can grab the remoteAddress by using the (ws) socket object. But, when you do console.log(socket) (from this ws plugin), it shows this: 

http://i.gyazo.com/d192a93bb3f817fd7c4617d8f32421ac.png
AND
http://i.gyazo.com/d192a93bb3f817fd7c4617d8f32421ac.png
Hell, the property list is so long, you have to download a new console just to read the rest of the properties. Which you have, absolutely NO documentation for is my point...

Also here is a copy and paste of socket.upgradeReq.connection:

```
Game functions imported and ready!
{ _connecting: false,
  _hadError: false,
  _handle:
   { fd: undefined,
     reading: true,
     owner: [Circular],
     onread: [Function: onread],
     onconnection: null,
     writeQueueSize: 0 },
  _host: null,
  _readableState:
   { objectMode: false,
     highWaterMark: 16384,
     buffer: [],
     length: 0,
     pipes: null,
     pipesCount: 0,
     flowing: true,
     ended: false,
     endEmitted: false,
     reading: true,
     sync: false,
     needReadable: true,
     emittedReadable: false,
     readableListening: false,
     defaultEncoding: 'utf8',
     ranOut: false,
     awaitDrain: 0,
     readingMore: false,
     decoder: null,
     encoding: null,
     resumeScheduled: false },
  readable: true,
  domain: null,
  _events:
   { end: [ [Object], [Object] ],
     finish: [Function: onSocketFinish],
     _socketEnd: [Function: onSocketEnd],
     drain: [ [Function: ondrain], [Function: socketO
     timeout: [Function],
     error: [ [Function: socketOnError], [Object] ],
     close: { [Function] __ultron: 0 },
     data: { [Function: firstHandler] __ultron: 0 } }
  _maxListeners: undefined,
  _writableState:
   { objectMode: false,
     highWaterMark: 16384,
     needDrain: false,
     ending: false,
     ended: false,
     finished: false,
     decodeStrings: false,
     defaultEncoding: 'utf8',
     length: 0,
     writing: false,
     corked: 0,
     sync: false,
     bufferProcessing: false,
     onwrite: [Function],
     writecb: null,
     writelen: 0,
     bufferedRequest: null,
     lastBufferedRequest: null,
     pendingcb: 0,
     prefinished: false,
     errorEmitted: false },
  writable: true,
  allowHalfOpen: true,
  destroyed: false,
  bytesRead: 734,
  _bytesDispatched: 175,
  _pendingData: null,
  _pendingEncoding: '',
  server:
   { domain: null,
     _events:
      { request: [Function],
        connection: [Function: connectionListener],
        clientError: [Function],
        error: [Function],
        upgrade: [Function] },
     _maxListeners: undefined,
     _connections: 1,
     _handle:
      { fd: undefined,
        reading: false,
        owner: [Circular],
        onread: null,
        onconnection: [Function: onconnection],
        writeQueueSize: 0 },
     _usingSlaves: false,
     _slaves: [],
     allowHalfOpen: true,
     pauseOnConnect: false,
     httpAllowHalfOpen: false,
     timeout: 120000,
     _connectionKey: '4:0.0.0.0:9300' },
  _idleTimeout: -1,
  _idleNext: null,
  _idlePrev: null,
  _idleStart: 6349714,
  parser: null,
  _paused: false,
  read: [Function],
  _consuming: true }
```


** And where in the world is .remoteAddress at may I ask?** Why is it not there? Do you know, that might be something to list in the documentation? Because quite frankly, I have wasted far too much time trying to find out why and spending countless hours on google trying to find the users IP. It's just sad.

**Comment by 3rd-Eden** [comment]
That is how node's console works, either deal with it or use a different module to output objects to stdout. It's not our fault that node works this way, and there absolutely no reason that we reproduce node's console documentation in this project.
