### ISSUE TITLE
Why is ws getting compiled every time?

### ISSUE THREAD

**Issue by binarykitchen** [websockets/ws#461]
Whenever I have installed ws and run a `npm i` afterwards for whatever reason, ws is re-compiled again. Why? There is no need to compile it when the version matches:

```
$ npm i
... 
> ws@0.6.5 install /var/www/videomail/staging/source/node_modules/websocket-stream/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory `/var/www/videomail/staging/source/node_modules/websocket-stream/node_modules/ws/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node: Finished
  COPY Release/bufferutil.node
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/obj.target/validation.node
  SOLINK_MODULE(target) Release/obj.target/validation.node: Finished
  COPY Release/validation.node
make: Leaving directory `/var/www/videomail/staging/source/node_modules/websocket-stream/node_modules/ws/build'
```

Is there a workaround for that for better performance? Because I am running `npm i` when deploying things on the server.

**Comment by 3rd-Eden** [comment]
Because that's how npm works.

**Comment by binarykitchen** [comment]
So, in other words I should discuss this on npm ....

**Comment by 3rd-Eden** [comment]
@binarykitchen Ideally, yes. IMHO npm should pre-build binary dependencies on various of platforms and download those instead of building binary modules on the users systems. Which is a quite error prone design. There are modules like `node-pre-gyp` which attempts to solve this but that is not an ideal solution.

**Comment by 3rd-Eden** [comment]
@binarykitchen but also make sure you upgrade to 0.7 which uses optionalDependencies instead of install scripts for the binary dependencies.

**Comment by binarykitchen** [comment]
Oh @3rd-Eden, v0.7 is out and solves this by default?

**Comment by 3rd-Eden** [comment]
@binarykitchen I don't know, I'm not really affected by this bug because I don't npm install . a lot, I only install dependencies but I noticed that your installing 0.6.x instead of the newest 0.7 which does handle binary dependencies differently.

**Comment by binarykitchen** [comment]
Ok, when is v0.7 getting npm-published?

**Comment by binarykitchen** [comment]
Ah, I am already using v0.7.1 here but I found out that the websocket-stream package still uses ws v0.6.5 which causes this. I'll ask them to bump this version, see https://github.com/maxogden/websocket-stream/issues/64.
