### ISSUE TITLE
is the documentation out of date?

### ISSUE THREAD

**Issue by mreinstein** [websockets/ws#462]
this is straight from the documentation, but when it's run it throws an error about `on` is undefined:

```javascript
var WebSocket = require('ws');
var ws = new WebSocket('ws://www.host.com/path');

ws.on('open', function open() {
  ws.send('something');
});
```

however this works:

```javascript
var WebSocket = require('ws');
var ws = new WebSocket('ws://www.host.com/path');

ws.onopen(function open() {

});
```

same results for the other event types `onmessage`, etc.

**Comment by nkzawa** [comment]
No, the doc should be correct. What version of ws do you use?

**Comment by mreinstein** [comment]
0.7.1

**Comment by mreinstein** [comment]
I'm using this via browserify, in a browser context. Though I don't think that matters.

**Comment by nkzawa** [comment]
It's matter because on browser, `ws` returns `global.WebSocket` which has slightly different API. 
You can use `ws.onopen = function() {}` form instead.
