### ISSUE TITLE
Limit the maximum incoming message size

### ISSUE THREAD

**Issue by tiagoalves** [websockets/ws#469]
I need to limit the size of incoming messages so that I can avoid memory attacks. I searched the code and the issue list but found no option for that.

Does this feature exist or is it planned? If not, would it be of general interest?

Thanks.

**Comment by Dillybob92** [comment]
Easy, just use the length property of a string inside the .on('message').

**Comment by tiagoalves** [comment]
Thanks for your feedback and the suggestion regarding the rate limiter.

As for using the `string.length` property, if I understood it correctly, this doesn't eliminate the problem. I believe that by the time `on('message')` is fired, we have already read the whole message into memory, even if it is a 1GB message. That's exactly what I am trying to avoid.

I think it's necessary to check the message size as it is being buffered and close the connection with error code 1009.

**Comment by Dillybob92** [comment]
Oh, well we need check it then in Websockets.js or somewhere in the \apps\node_modules\ws\lib directory. I'm not sure where the message payload is initially received :(.

**Comment by avesus** [comment]
:+1:

**Comment by lpinca** [comment]
It is now possible to limit the maximum size of a message with the `maxPayload` option.
