### ISSUE TITLE
Sending Masked Text Data?

### ISSUE THREAD

**Issue by Dillybob92** [websockets/ws#470]
So, here is some psuedo code that's inside my server js file.

```
wss.on('connection', function(socket) { // Inside the socket and connected.
    socket.on('message', function(Message, flags) {
  socket.send('hello', { binary: false, mask: true });
```

But I receive this error: 

```
     events.js:85
     throw er; // Unhandled 'error' event
     ^
    TypeError: Cannot read property 'send' of null
```

Any idea if it's possible to mask text data as well? In the documentation it says that it's possible, thanks!

Edit: Mind you:

```
socket.send('hello');
```

Works fine, it's just when I add the object parameter to send.. hmm

**Comment by lpinca** [comment]
From https://tools.ietf.org/html/rfc6455#section-5.1

> A server MUST NOT mask any frames that it sends to the client.
