### ISSUE TITLE
Why 504?

### ISSUE THREAD

**Issue by binarykitchen** [websockets/ws#475]
I am getting these errors from time to time, from Nginx

```
Error during WebSocket handshake: Unexpected response code: 504
```

Here are the essential parts of the request header

```
Accept-Encoding:gzip, deflate, sdch
Accept-Language:en-GB,en-US;q=0.8,en;q=0.6
Cache-Control:no-cache
Connection:Upgrade
Host:videomail.io
Origin:http://localhost:8080
Pragma:no-cache
Sec-WebSocket-Extensions:permessage-deflate; client_max_window_bits
Sec-WebSocket-Key:U1kshGmySrxG/w7mN9WqDw==
Sec-WebSocket-Version:13
Upgrade:websocket
User-Agent:Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.101 Safari/537.36
```

When I wait a bit, reload the browser, then it works again. Weird. Any clues?

Not sure if it's an nginx issue, with the WS package or in my code. How can I find this out?

**Comment by 3rd-Eden** [comment]
I would say it comes from your load balancer as 504 is a gateway timeout. Could it be that the server had a frozen event loop or swamped with load?

**Comment by binarykitchen** [comment]
Maybe it's coming from nginx but I still do not see why. I have a proxy configuration with proxy caching. But I always close the websocket when the user has exited.

Hmmm ... has anyone every configured a nginx proxy cache together with websockets?

**Comment by binarykitchen** [comment]
I think I found the cause, but am not sure. In nginx I changed the config:

```
location / {
  try_files $uri @proxy;
}

location @proxy {
  proxy_pass https://127.0.0.1:$proxy_port;

  # this avoids upstream time outs (110: Connection timed out)
  # proxy_read_timeout 260s;

  # disables proxy cache completely. does not go well with websockets
  proxy_cache_bypass 1;
  proxy_no_cache 1;
}
```

Here, disabling the proxy cache is the answer. Too bad I cannot use them caches for websockets anymore :(
