### ISSUE TITLE
Socket timeout

### ISSUE THREAD

**Issue by lght** [websockets/ws#484]
Hi guys,

my ios application is using a websocket to communicate with my nodejs server, implementing this websocket server. The application is connecting to the websocket through Nginx and its proxy.

If I put my phone in airplane mode, the server is not receiving that the websocket has been interrupted. Is there something to do on my server, or on nginx directly ?

**Comment by aryeharmon** [comment]
you should have an event to handle that on the server

**Comment by lpinca** [comment]
There are cases where the only way to detect that a connection has been closed is via a heartbeat system which can be implemented, for example, by sending [pings](https://tools.ietf.org/html/rfc6455#section-5.5.2).

**Comment by paredesivan** [comment]
@lpinca 
and how can I forcefully close once I detect that it is no longer present?

**Comment by lpinca** [comment]
@paredesivan https://github.com/websockets/ws#how-to-detect-and-close-broken-connections
