### ISSUE TITLE
Not possible to `removeListener` for specific events

### ISSUE THREAD

**Issue by DamonOehlman** [websockets/ws#489]
Because of the way [listener registration occurs](https://github.com/websockets/ws/blob/master/lib/WebSocket.js#L430) within ws it is not possible to remove the listeners using the originally provided functions.

Not sure that this behaviour can be changed, but I think it's worth noting the limitation (hence this issue - couldn't find another) so people know this might be something they need to workaround themselves.

**Comment by coolaj86** [comment]
Yeah, this is also a problem for me.

**Comment by JoshuaWise** [comment]
This is only the case when you use the WC3 events interface. If you just use the Node.js EventEmitter interface, you can do all the normal event things.
```
function handler(msg) {
    console.log('received a message.');
}
ws.on('message', handler);
ws.removeListener('message', handler);
```

**Comment by piranna** [comment]
+1, `removeEventListener()` needs to be added, I try to use as much as possible the browser API to be sure to be compatible with browsers... :-/

**Comment by 0x8890** [comment]
+1 for `removeEventListener`.

**Comment by timhuff** [comment]
Dear reader of the future: While this issue is still open, `removeEventListener` appears to be working.

**Comment by jbaudanza** [comment]
Looks like this is fixed in #805. I've monkey-patched this PR into my project and it works great. Hopefully this will get merged soon.

**Comment by Mo33n** [comment]
Y its not still working :-(

**Comment by Globik** [comment]
@JoshuaWise and when not ws.on(jmessage',...) but an other listener? For examle eventemitter.on('someevent',...)??? How to be?

**Comment by Kostanos** [comment]
Guys, any idea why I got the error: **Raise the error: Uncaught TypeError: "listener" argument must be a function**

refer: https://stackoverflow.com/questions/56066983/ws-removelistener-after-first-run-on-nodejs

**Comment by noszone** [comment]
Could anyone advise how to remove event listeners in nodejs?
My problem that client has many listeners and onmessage event repeated many times.

How I can kill the listeners in case of nodejs?

```
const WebSocket = require("ws");
const express = require("express");
let app = express();

let client;
let isWsConnected=false;

const wsConnect=()=> {
	client = new WebSocket('ws://192.168.0.34:9998/replication/d0f6abe6876e25',{ rejectUnauthorized: false, handshakeTimeout: 3500 });
  
		console.log("ws client trying to connect...");
		
		client.onmessage=(message) => {
		};

		client.onopen = () => {
		  //client.send("Message From Client");
		  console.log("ws open");
		  isWsConnected=true;
		};

		client.onclose = () => {
		  console.log("ws closed");
		  isWsConnected=false;
		  client=null;
		};
		
		client.onerror=(e)=> {
		isWsConnected=false;
		console.log("ws error:",e.message);

}

if (isWsConnected == false) {
	try {
		wsConnect();
	} 
	catch (err) {
		console.log("WEBSOCKET_RECONNECT: Error", new Error(err.message));
	}
	console.log(isWsConnected);
}

app.get("/echo", async function (req, res) {
  client.once("connection", function connection(cli) {
    cli.send(msg);
    res.send("send");
  });
});

app.listen(9998, function () {
  console.log("Zik-Skud Replication listening on port 9998!");
});

setInterval(async() => {
  if (isWsConnected == false) {
	try {
		wsConnect();
	} 
	catch (err) {
		console.log("WEBSOCKET_RECONNECT: Error", new Error(err.message));
	}
	console.log(isWsConnected);
  }
  //console.log(isWsConnected);
}, 5000);

```
