### ISSUE TITLE
TypeError: Uncaught, unspecified "error" event.

### ISSUE THREAD

**Issue by JSReligion** [websockets/ws#490]
Hi, just got ws server crush on my system with error

events.js:74
        throw TypeError('Uncaught, unspecified "error" event.');
              ^
TypeError: Uncaught, unspecified "error" event.
    at TypeError (<anonymous>)
    at WebSocket.emit (events.js:74:15)
    at Receiver.onerror (/home/wss/stock/node_modules/ws/lib/WebSocket.js:833:10)
    at Receiver.error (/home/wss/stock/node_modules/ws/lib/Receiver.js:317:8)
    at /home/wss/stock/node_modules/ws/lib/Receiver.js:463:32
    at /home/wss/stock/node_modules/ws/lib/Receiver.js:354:9
    at InflateRaw.onError (/home/wss/stock/node_modules/ws/lib/PerMessageDeflate.js:222:5)
    at InflateRaw.emit (events.js:95:17)
    at Zlib._binding.onerror (zlib.js:299:10)

/////////////////////////////////////////////////////////////
//wss init part of code
var WebSocketServer = require('ws').Server,
var cfg = {
    ssl : true,
    key : fs.readFileSync(__dirname + "/ssl/localhost.key");,
    cert : fs.readFileSync(__dirname + "/ssl/localhost.cert"),
    rejectUnauthorized : true,
    passphrase : "*******",
    port : 82
};

var app = https.createServer(cfg).listen(cfg.port);
var wss = new WebSocketServer({server : app});
wss.on("connection", function(socket){/_some logic_/};
/////////////////////////////////////////////////////////////

server params

Ubuntu 14.04.2 LTS (GNU/Linux 3.13.0-32-generic x86_64)
node.js 0.10.38
ws 0.7.1

client params
browser google chrome v 42.0.2311.90 (64-bit)
osx mac 10.10.2

**Comment by aslushnikov** [comment]
+1

**Comment by diegito** [comment]
+1

**Comment by agalazis** [comment]
Well I guess you would be better off configuring ssl on nginx rather than configuring your node servers and serve plain ws
@aslushnikov @diegito did you experience this when using wss as well?

**Comment by diegito** [comment]
I was feeding data from a chrome extension. It works for some time (like a couple minutes) and then it crashes with this same error. To be honest I was using plain ws and not wss.

Eventually I decided to move to Python and Tornado to serve on a websocket.

**Comment by lpinca** [comment]
You should add a listener for the `error` event.

```
wss.on('connection', (ws) => {
  ws.on('error', (err) => {
    // Handle the error.
  });
});
```
