### ISSUE TITLE
Use specific error types with codes, etc

### ISSUE THREAD

**Issue by hessryanm** [websockets/ws#491]
I was asking questions about errors in this module on #node.js, and they suggested I write this ticket.

In WebSocket.js, line 233, it throws `new Error('not opened')`.  This isn't a big deal in our code, so I need to catch the error, and if it matches anything except this one, throw it again.  Because this is a generic error with no class or code, the only way to catch it is through string matching.

User joepie91 on #node.js says you should use `errors` or `createError`.

**Comment by lpinca** [comment]
We don't have codes for errors but messages and types have been improved in 695c5ea988801ed75c121ad9bc76ed7abd70ccd1. Hope this helps.
