### ISSUE TITLE
Discriminate connections using host in addition to path

### ISSUE THREAD

**Issue by manvalls** [websockets/ws#498]
When using `options.server` you can use `options.path` to discriminate requests based on pathname, and two `WebSocketServer`s aren't allowed to use the same path. However, one may have two different services listening on the same `http.Server`, each one with a different host, by inspecting `req.headers.host` and using SNI, which node does allow.

In this case, both services are forced to use different paths for their WebSocket endpoint, when both are in fact distinguishable by looking at `req.headers.host`. Using `options.host` to discriminate requests in this scenario would definitely save me and anyone trying to use this approach some headache.

**Comment by JoshuaWise** [comment]
Pull requests are welcome!

**Comment by lpinca** [comment]
This can be done by overriding [`WebSocketServer.prototype.shouldHandle()`](https://github.com/websockets/ws/blob/f941a4046481f1aa182aba11bb958e4306fd92fc/doc/ws.md#servershouldhandlerequest).
