### ISSUE TITLE
high cpu load

### ISSUE THREAD

**Issue by rangercyh** [websockets/ws#499]
I use ws 0.7.1 with node 0.12.2 
I run single node process with ws and accept ws client to connect.
the code is here: https://gist.github.com/rangercyh/ff5d996cdad5b2643b9c
with 1000 clients, the cpu up to 50%-60%
with 2000 clients, the cpu up to 100%
the server runs on an linux and it has 12 cpu core and 24G memory.
I don't know why ws module run like this, the cpu is so high?
the same env, I run the node net.tcp module to hold 4000 clients, the cpu is 20%-30%
please help me!

**Comment by rangercyh** [comment]
![image](https://cloud.githubusercontent.com/assets/1217541/7629432/02a975da-fa5f-11e4-9488-c4706f2b6ad4.png)
![image](https://cloud.githubusercontent.com/assets/1217541/7629435/0ca88800-fa5f-11e4-99e4-3f449f3aea3f.png)

**Comment by woverton** [comment]
I am running your sample applications with 3000 clients on my laptop and the cpu usage is only about 40%. The issue you're having might be outside of ws and be an issue in your application. Are you doing any big looping over all your clients or anything like that?
