### ISSUE TITLE
Protocol support very outdated

### ISSUE THREAD

**Issue by Temptin** [websockets/ws#501]
The front page says the following about Protocol support:

```
Hixie draft 76 (Old and deprecated, but still in use by Safari and Opera.)
HyBi drafts 07-12
HyBi drafts 13-17
```

Unless people are using a 5 years old Safari (5.x) or Opera, this is _totally_ false. The only reason someone would use Safari 5.x is if they're still using an iPad 1 (iOS 5 is stuck on Safari 5), or if they're using the final Safari for PC (5.x). But who uses Safari on PC anymore? Apple killed it 5 years ago to focus all their work on the Mac version instead.

Every browser made after December 2011 supports RFC 6455:
http://en.wikipedia.org/wiki/WebSocket#Browser_support

And if we're going to "bully" browsers by labeling them based on older versions of the browser, why not also say that "Hixie draft 76" is used by Android and Chrome 5 years ago?

Anyway, I propose this change:

```
Hixie draft 76 (Old and deprecated, but still in use by browsers older than 2011, such as Safari on iOS 4/5 and various old Android versions.)
HyBi drafts 07-12
HyBi drafts 13-17 (Supported by [http://en.wikipedia.org/wiki/WebSocket#Browser_support](all major browsers released after December 2011))
```

Here is a full list of old versions of major browsers that still use Hixie:
https://github.com/Atmosphere/atmosphere/wiki/How-to-use-the-older-WebSocket-draft-00-hybi-00-hixie-76-protocol

**Comment by EddieOne** [comment]
You could submit a pull request

**Comment by Temptin** [comment]
@EddieOne Yeah but that is overkill for a small edit like this.

**Comment by sam-github** [comment]
PRs can be merged by pressing a button, you want busy people to hand edit a README for you, if it bugs you, PR it.

**Comment by lpinca** [comment]
Hixie-76 is no longer supported, closing.
