### ISSUE TITLE
'close' event isn't fired when a connection failed

### ISSUE THREAD

**Issue by flowersinthesand** [websockets/ws#505]
How to reproduce the issue:
```javascript
var ws = new (require('ws'))('ws://no.where'); // 0.7.2
ws.onerror = function() {
    console.log('error');
};
ws.onclose = function() {
    console.log('closed');
};
```

Output:
```
error
```

Expected:
```
error
closed
```

As the [API doc](https://github.com/websockets/ws/blob/master/doc/ws.md#websocketonclose) says, `websocket.onclose` emulates the W3C Browser based WebSocket interface so it would be nice if it follows other browsers' behavior where it fires `error` and `close` event together in such cases.

How to reproduce the issue in browser:
```javascript
var ws = new WebSocket('ws://no.where');
ws.onerror = function() {
    console.log('error');
};
ws.onclose = function() {
    console.log('closed');
};
```

Chrome output:
```
WebSocket connection to 'ws://no.where/' failed: Error in connection establishment: net::ERR_NAME_NOT_RESOLVED
error
closed
```

Firefox output:
```
Firefox can't establish a connection to the server at ws://no.where/.
"error"
"closed"
```

IE output:
```
SCRIPT12007: WebSocket Error: Network Error 12007, The server name or address could not be resolved
error
closed
```

I would like to contribute if it's right that it should fire `error` and `close` event in such cases. Let me know that.

**Comment by 3rd-Eden** [comment]
Fixed in master.
