### ISSUE TITLE
Bump version to 1.0.0

### ISSUE THREAD

**Issue by rmg** [websockets/ws#508]
I didn't see any previous discussions on this, so please forgive me if I missed it.

Is there any objection to bumping the version to 1.0.0 for the next release?

It would be nice if dependants could more easily get improvements to the module (like the latest release's improvements w.r.t. binary dependencies) while using the default `^x.y.z` version specifier.

**Comment by sam-github** [comment]
Please do this - not using semver causes ripple effects of manual upgrades of 0.x releases through node ecosystem.

By "not using semver" I mean that a 0.y.z release has ***no guarantees*** of any kind on compatibility. The meaning of a bump of the `z` is not defined, the meaning of a bump of `y` is not defined, so its hard to depend on it.
