### ISSUE TITLE
Memory leak or this how node runs?

### ISSUE THREAD

**Issue by Dillybob92** [websockets/ws#509]
Saw my memory usage go up in task manager each time I was refreshing a new browser connection to connect to the ws module through node. It never went down after the client quit or exited the browser/closed connection. So I figured.. I have about 100KB's of code scattered all over in my gameserver.js file, there is probably some temporary object leakage somewhere.

So I decided to just throw up a test.js with:
WebSocketServer = require('ws').Server, wss = new WebSocketServer({port: 9300});

and run it.

1st Refresh:
http://i.gyazo.com/f9379781dd15c0db1aae7bd79c33a36f.png

2nd Refresh:
http://i.gyazo.com/532598c74b81749043882b84b3666af5.png

3rd Refresh:
http://i.gyazo.com/7d2997e94dc5222166bb13a133c7ac36.png

Now, each time I refresh the browser and connect to the server or send some some data each refresh adds memory usage and it doesn't go down.. EVEN when a user has closed their connection.
 So I could theoretically just keep refreshing for hours/day and the memory usage would be through the ROOF.  Is this intended? If so... why does this do this?

Edit: Shouldn't the memory usage go down after a client has exited?

**Comment by Dillybob92** [comment]
Also, if this is intended.. This would be the worse module ever to work on a production game server.  I cannot imagine the memory usage going through the roof after players have join/left countless of games and entered channels/chatted/etc.. Holy shit.

**Comment by Dillybob92** [comment]
Hey guys, I posted this on SO instead:

http://stackoverflow.com/questions/30608110/why-does-nodejs-have-incremental-memory-usage

 I explained my issue there better and tried to be less acetone :)

**Comment by Dillybob92** [comment]
Alrighty, sorry for the quadruplet post. But, I've been using this to close the connections gracefully on the serverside:

var WebSocketServer = require('ws').Server
  , wss = new WebSocketServer({ port: 9300 });

wss.on('connection', function connection(socket) {
  socket.on('message', function incoming(message) {
    
  });
  
socket.on('close', function () {
		   socket.close();
		   
		   
		
	
  
});

 
});


And even when I use socket.close() to end their connection instantly the memory usage doesn't go down. Is there a timeout that this plugin uses to remove/delete the socket buffer/data for a unused connection? Can we edit that? :P

**Comment by Dillybob92** [comment]
Ohhh... 'cleanupWebsocketResources' function on line 1050 :) :D :D

**Comment by Deathspike** [comment]
You're keeping the reference to `socket` in the scope with that `setTimeout`. The object that was used to contain the values is not going to be garbage collected while there is something with a reference to it. After the `setTimeout` callback has ran, there is no reference to `socket` anymore and it will become eligible to garbage collection. That doesn't mean it's collected immediately, rather, it means that it *may be garbage collected at some point*. 

Watching the memory usage on your OS is meaningless, as it doesn't show the actual in-use memory but rather the committed memory to that particular application. The same principle applies to other applications, including C#, Java and even non-GC'ed languages like C++. Does the use go down? Probably. But you'll likely not see it any time soon. Perhaps when the OS is starving for memory, a request will be made to applications to release chunks. Start worrying about this if you ever get memory exceptions, and not before that point.
