### ISSUE TITLE
Is there a way to limit the maximum size of a message?

### ISSUE THREAD

**Issue by Deathspike** [websockets/ws#513]
I have an application in which I wish to limit the maximum size of a message that was sent across the wire by a connected client. Since the theoretical maximum of a message is several hundreds of gigabytes, i actually never want my application to allocate that big a chunk of memory if some malicious clients tries to send an over-sized packet. Where can I limit the message size, to say, 1024 bytes?

**Comment by Dillybob92** [comment]
I'd use `string.length >  10000` (or whatever) and then close their connection.

But, I am pretty much the memory is already allocated as .length needs to read that string. Hmm not quite sure :(

**Comment by Dillybob92** [comment]
I posted your question here: http://stackoverflow.com/questions/30817727/is-there-a-way-to-limit-the-maximum-size-of-a-string

**Comment by Deathspike** [comment]
Nothing yet. Does nobody care about taking down a server by sending a huge ws frame?

**Comment by Deathspike** [comment]
So here is a `server.js`:

var WebSocketServer = require('ws').Server;
var server = new WebSocketServer({port: 8080});

    var WebSocketServer = require('ws').Server;
    var server = new WebSocketServer({port: 8080});

    server.on('connection', function(socket) {
      console.log('Got a connection!');
      socket.on('message', function() {
        console.log('Got a message!');
      });
      socket.on('close', function() {
        console.log('Got a close!');
      });
    });

And a client that allocates a little buffer and sends over `n` connections at once:

    var buffer = new Buffer(require('smalloc').kMaxLength);
    var numberOfConnections = 1000;
    var WebSocket = require('ws');

    for (var i = 0; i < numberOfConnections; i++) {
      (function() {
        var ws = new WebSocket('ws://localhost:8080/');
        ws.on('open', function() {
          ws.send(buffer, {binary: true, mask: false}, function() {
            ws.close();
          });
        });
      })();
    }

Leave it running for a while and it will push your server over the edge and crash. Up `n` to more connections to accelerate the effect. This is exactly why I want to limit the size of a single message, to avoid malicious behavior like this. There should be something to limit it, right?

**Comment by 3rd-Eden** [comment]
You as developer should be limiting the data that YOU are sending. It would be silly to enforce limits on this as there might be valid usecases where sending a few mb as buffers actually makes sense (streaming binary video data or what not for example).

**Comment by Deathspike** [comment]
The point is not from a perfectly controlled environment perspective where every client plays nice and everything is rainbows an unicorns. The reality is that malicious users can forge a gigantic frame and send them to any `ws` server which then starts to allocate a ton of memory for no good reason. Eventually, that will crash your node process.

A websocket frame is prefixed with a length. The server should be able to set a hard limit on that and start dropping connections when a frame is too large. There is absolutely no good reason for the server to try and get a message that is larger than `n` bytes (where I set `n` to something that works for my application).

**Comment by Deathspike** [comment]
Edited my previous messages to be a more clear and understandable.

**Comment by Dillybob92** [comment]
@Deathspike You need to post on your question on stackoverflow these forums don't have a ounce of the intelligence compared to SO.

For your example code above, that can be mitigate by using iptables to limit the number of new connections per ip:  This is why using websockets on a production / linux server is a must.

#  Allows Websocket Connections (only 10 attempts by an IP every 30 seconds, drop the rest to prevent  attacks) ~ 
iptables -A INPUT -p tcp -m tcp --dport 9300 -m state --state NEW -m recent --set --name WEBSOCKET --rsource
iptables -A INPUT -p tcp -m tcp --dport 9300 -m state --state NEW -m recent --update --seconds 6 --hitcount 10 --name WEBSOCKET --rsource -j DROP
iptables -A INPUT -p tcp -m state --state NEW --dport 9300 -j ACCEPT

you may also use; https://github.com/jhurliman/node-rate-limiter  is what I use once my player is connected to my gameserver to limit packet spamming.



The code you posted above isn't what you explained in your OP. The code you posted is a new connection flooder.  What you explained in your OP is how a user can send a packet with an immense amount of data and it will overflow the memory buffer when `.length` is checking it which is a problem as well.

Unless, there is a way to limit the size of data that can be sent over tcp with iptables, I cannot really find a solution. You need to post your question on SO though and give me a link to it so I can watch it, thanks.

**Comment by Deathspike** [comment]
That's not the point, either. I'm just creating a bunch of connections to exhibit the problem **faster**, but regardless of additional security measures, the fact remains that there is no maximum message size. And the question topic "*Is there a way to limit the maximum size of a message?*" is exactly the point of this issue.

I honestly don't want to debate the merits and cons of iptables, but please note that dropping anything over `n` connections will effectively rule out multiple connections from a place where there can be multiple clients for good reasons (large companies, internet cafes, schools/universities, LAN parties, etc). Rate limiters have similar pros/cons and are effectively **not** the point of this issue. Good security practice will almost always have both techniques implemented in some way, though. Still, not the point of this issue; I'm only looking at `ws` in this issue.

And really, **all I'm after is not having nodejs allocate a buffer of a huge size for no reason**. Why? Because there is no reason for the nodejs server to allocate and read a huge buffer when I explicitly want to tell it to never ever have a need for that (wasted resources, CPU, network, RAM -- and possibly catastrophic errors, too large buffer exceptions, ram exceeded, starting to swap, etc).

**Comment by 3rd-Eden** [comment]
@Dillybob92 

>  these forums don't have a ounce of the intelligence compared to SO

These are not forums, but an issue tracker. Seems like your "superior" "intelligence" missed that part. I'm going to close this issue. Feel free to re-open a new issue if a normal discussion about this problem can take place.
