### ISSUE TITLE
 Is there a way to limit the maximum size of a message?

### ISSUE THREAD

**Issue by Deathspike** [websockets/ws#515]
Please see: https://github.com/websockets/ws/issues/513

I'm not sure why _my issue report_ is closed for improper wording/opinion _of another person_?

I'd like to keep this issue going. Preferably in the original issue report as it contains the discussion.

**Comment by Dillybob92** [comment]
Because, this is a not a 'forum', remember? It's a issue tracker where we cannot quote or make discussions with other people! That logic though... 

 I told you, the intellegence here is lacking and it needs to be posted on SO or another site. They don't want to admit they have a vulnerability and they will most likely end up saying: 'It's not a WS problem, it's a `nodejs` issue itself', please contact them! That's what they always do :)

Inb4 that happens.

**Comment by 3rd-Eden** [comment]
There was absolutely no reason for such discussion to take place in a bug report. But lets get back on topic here.

There is indeed no way to limit the maximum size of a message. The closed thing to message size moderation are:

- Looking at the bufferedAmount property of the connection and actively start dropping or blocking connections based on that.
- Attach an additional data listener to the socket that `ws` wraps. 
- Add functionality for this directly in to the project, which is probably the `received.js` file.

**Comment by Deathspike** [comment]
I'd be in complete favor for the latter option. The first two options are not exactly straight to the point and therefore will be harder to reason about and/or maintain in future. On top of that, the WebSocket protocol describes the way a message is framed and a message is always framed with the length. Upon receiving this header, we know the size of the payload and whether or not it exceeds our maximum. This is the perfect place to drop the connection when the incoming payload is violation; we don't have to waste any further resources on something that we know is in violation of our constraints.

From a quick glance, I'd say that rule would have to be checked in the `getData` functions of the binary and text opcode handlers. That is https://github.com/websockets/ws/blob/master/lib/Receiver.js#L423 and https://github.com/websockets/ws/blob/master/lib/Receiver.js#L488. That said, I'm not too familiar with the `ws` internals and cannot possibly reason about the entire code base from a quick glance. But, that's what make sense to me.

Should I take a quick stab at this later and see what I can come up with? Or is someone else preferring to do this instead, or has alternatives/better locations and/or issues with the suggested checks at the suggest location?

**Comment by Dillybob92** [comment]
Wait, I thought this wasn't a forum, why are you asking questions?

**Comment by apsillers** [comment]
To the repo owner(s): you have ability to moderate discussion via edits and deletions of others' comments on issues; no need to close the entire issue if you can clean it via moderation. (Please delete this comment once you've read it, as it's completely off-topic.)

**Comment by lpinca** [comment]
@Deathspike The feature you are looking for is available in [`faye-websocket`](https://github.com/faye/faye-websocket-node) under the option `maxLength`, so keep in mind that there are also alternatives.

**Comment by Deathspike** [comment]
So, I have a pull request open for this issue now. I did not find a good way to figure out what the length is going to be after decompressing. I presume, since it is an extension on the protocol, the decompressed length is not transmitted at all. So, the current version I implemented only supports a check with the pre-decompression length, so the decompressed buffer can still be larger than the maximum payload. At least, you can cut down the 2GB packets back to a reasonable number that (probably) won't get (too) big.

**Comment by Deathspike** [comment]
Ah, the test suite is failing. The tests don't seem to work on Windows, so I can't actually run them..

**Comment by avesus** [comment]
The test suite is failing because you have changed some APIs: ```Receiver (maximumPayload, extensions)```.
