### ISSUE TITLE
No function of ws.on('timeout') even though this module uses net as a base ...

### ISSUE THREAD

**Issue by belldandu** [websockets/ws#521]
would be nice to add a on timeout function.
i use ws to connect to a chat so far everything works unless there is a timeout 
because ws has no way to handle a timeout when it should
i cant make it close the connection and reconnect

any chance you guys gonna add this or should i just add it myself?
@3rd-Eden

**Comment by lpinca** [comment]
This lib explicitly disables idle timeout on the socket by using `socket.setTimeout(0);` so I think it's unlikely that it will happen.

**Comment by 3rd-Eden** [comment]
I agree, if there is usecase for this and we do get timeouts, feel free to make PR to add this functionality.
