### ISSUE TITLE
WS server: Append `req` to argumentlist when emitting 'headers' or save response headers

### ISSUE THREAD

**Issue by andsens** [websockets/ws#525]
When emitting the `headers` event in [WebSocketServer.js](https://github.com/websockets/ws/blob/2d0e338af86e1a04ceb63a0a77a4432c3b72532f/lib/WebSocketServer.js#L231) no context is passed and since response headers are not saved anywhere subsequent code cannot act on the response headers.

Because of this, there is no way to either dynamically create response headers depending on the connection info (since we do not have access to that in the `headers` listener) or later on act on whichever headers were sent.

Here is one use case:

> We have a client which communicates with a server through both WS and REST. Initial authentication happens on the WS server, which is expensive cpu-cycle wise (many hashing rounds etc.). Because of that we create a session ID which can be used for requests against the REST server, where authentication is a matter of doing a simple lookup.
> To set that session ID we would like to send a cookie with the upgrade response headers.
> 
> After that `verifyClient()` should remember that the ID belongs to an authenticated user id (if that's the case).
> 
> None of this is of course possible, because async operations are not possible in the `headers` listener and `verifyClient()` has no clue which session ID was sent.

I propose changing `self.emit('headers', headers);` to `self.emit('headers', headers, req);`. This change would be minimal, backwards compatible, and allows a connection to be identifiable throughout the upgrade process.

EDIT: When writing the use case, I misunderstood the order of the `headers` event and `verifyClient()`. We of course run `verifyClient()` first and _then_ emit the `headers` event.

**Comment by lpinca** [comment]
Ref: #787.
