### ISSUE TITLE
Support sending array in binary?

### ISSUE THREAD

**Issue by andrewdep** [websockets/ws#529]
We recently upgraded to node 0.12 and the latest ws. Our codebase was calling `send` with an array of 8-bit numbers and {binary: true}, which worked before but now causes this exception:
```
TypeError: Invalid non-string/buffer chunk
    at validChunk (_stream_writable.js:186:14)
    at DeflateRaw.Writable.write (_stream_writable.js:215:12)
    at PerMessageDeflate.compress (/home/vagrant/keli/node_modules/ws/lib/PerMessageDeflate.js:260:17)
    at Sender.applyExtensions (/home/vagrant/keli/node_modules/ws/lib/Sender.js:273:54)
    ...
```
We could go through our codebase and modify it to wrap the array into a typed array or a buffer, but it would be easier for us if `ws` just supported arrays like it used to.
Of course, if this is a bad idea then it's not a big deal for us to change our codebase, otherwise I can submit a pull request with a potential fix. We are currently working off of the fix in a fork, but see this as temporary.
Let me know what you think.

**Comment by nkzawa** [comment]
The issue is already fixed through https://github.com/websockets/ws/pull/524, though I think It's not released yet.

**Comment by andrewdep** [comment]
I looked at #524 and even pulled it and tested it. Unfortunately it does not work with plain old arrays, only with ArrayBuffers.

**Comment by nkzawa** [comment]
Ah, I didn't know ws supports sending an array before...
I'm not sure whether it's the intended behavior or not, since you can always use TypedArray and ArrayBuffer on Node.js. Any idea @3rd-Eden ?

**Comment by 3rd-Eden** [comment]
@nkzawa Just like you, I was not aware that ws even worked with "regular" arrays. I would have assumed in order to send binary that you needed to send actual binary based types such as TypeArray, Buffers and ArrayBuffer etc.

**Comment by nkzawa** [comment]
Then we should not officially support sending a plain array as binary IMO.

**Comment by andrewdep** [comment]
That makes sense. I'll recommend to my team that we convert our code base to using typed arrays.
