### ISSUE TITLE
Allow to configure handshake request headers

### ISSUE THREAD

**Issue by chge** [websockets/ws#53]
It would be very helpful if ws.WebSocket implementation would allow to override/append HTTP request headers for handshake. For example, client may want to set custom headers with implementation-specific values, instead of sending them after handshake.

The RFC-6455 doesn't restrict this.

```javascript
new WebSocket(
    'ws://example.com',
    {...
        headers: {
            'User-Agent': 'Node v0.7.7',
            'X-Custom-Authentication-Header': 'qwerty'
        }
    }
);
```

**Comment by eagle21st** [comment]
Hi,

I see the issue was posted almost three years ago, is the feature supported now? If so, is it documented anywhere?

Thanks,

**Comment by glennschler** [comment]
This issue has already been resolved in a previously merged commit which solved several related issues. Includes a passing test "Custom headers" in the test/WebSocket.test.js

commit 43a0b2b0277d64ffbb58e074b69cb9341923a3d2

I have been using this custom headers feature in my WS clients without issue, though before realizing this open issue.

**Comment by 3rd-Eden** [comment]
Thanks for the heads up, seems like I missed this issue when closing a bunch of things.
