### ISSUE TITLE
SSL

### ISSUE THREAD

**Issue by THEDARKK** [websockets/ws#532]
Hello, I can not to operate in ssl, how we can do?
var ws = new WebSocketServer({port: 8303});
Thank you to you

**Comment by coolaj86** [comment]
See https://github.com/coolaj86/ws/commit/42ba0385800565fa11b703adc13493b102605b57

Then use `https` instead of `http`.

See https://github.com/coolaj86/nodejs-ssl-example/blob/master/serve.js#L21-L36

**Comment by lpinca** [comment]
What @coolaj86 said, closing.
