### ISSUE TITLE
A server must not mask any frames that it sends to the client.

### ISSUE THREAD

**Issue by McFarts** [websockets/ws#538]
Using this simple code to send a masked string to the client:

```
socket.send('hey', { mask: true });

```

I get this error in chrome:

A server must not mask any frames that it sends to the client.

Any idea?

**Comment by JoshuaWise** [comment]
The Websockets specification (RFC-6455) dictates that the server MUST NOT send masked data clients, and that clients MUST send masked data to the server.
If you're looking to incorporate some sort of security measure, create your ws server on an HTTPS server.

**Comment by McFarts** [comment]
@JoshuaWise, my issue is the user can see the data in the chrome debugging console and was wondering how to mask that?

**Comment by woverton** [comment]
Do you mean that every message is automatically console.log'ed into the console or that it is accessible somehow?

**Comment by McFarts** [comment]
Like if you run binary websockets they are masked when you inspect the Websocket debugger in chrome. But for string's they are not.

(Forces the user to use grooveshark or a packet sniffer to read the contents) that's what I want, but with strings.

**Comment by lpinca** [comment]
Closing this as it isn't a `ws` issue.
I'm not sure how to achieve what you want without using binary frames or adding overhead on both client and server.
