### ISSUE TITLE
Inconsistent error/close behavior between client running in Node.js vs browser 

### ISSUE THREAD

**Issue by jondubois** [websockets/ws#543]
I noticed a few inconsistencies between how the client works when running in the browser vs in Node.js.

When the WS server crashes/is killed, if the client is running in the browser, the code is `1006` (which indicates an error - This is the desired behavior) but when running the client on Node.js, the code is `1000` (which indicates a normal disconnection) - This is a problem because a reconnection will not happen if the code is 1000 - I only want to reconnect if the connection was lost due to a failure (so the Node.js client will fail and not reconnect).

Another difference is that when running the client in the browser, when I try to connect to a non-existing server, it triggers the onclose handler with an error code (which is nice). When running the client in Node.js - The onclose handler is never called - Instead, the onerror handler will be called.

I'm using v0.7.2

**Comment by jondubois** [comment]
To reproduce the issue, you should:

1. Create a WebSocketServer in its own Node.js process
2. Then connect to it using the WebSocket client (running in a separate Node.js process).
3. Now kill the server process

The Socket 'close' event will be emitted but the status code will be 1000 - This is different from the behavior in the browser where the status code will be 1006.

The WebSocket client appears to get an error as expected inside its cleanupWebsocketResources() method, but it incorrectly reports the status code as 1000 (normal).

**Comment by jtblin** [comment]
Same problem. This is a major issue for us as we cannot handle reconnection properly, see https://tools.ietf.org/html/rfc6455#section-7.4.1 for exit codes.

It looks like `0.8.0` is trying to fix the issue by [returning 1006 in case of error](https://github.com/websockets/ws/blob/master/lib/WebSocket.js#L924) but from my testing there is no error captured when the server crashes so it doesn't actually fix the problem.

The `cleanupWebsocketResources` is called from the `close` listener on https://github.com/websockets/ws/blob/master/lib/WebSocket.js#L778 but doesn't seem to have any relevant information.

**Comment by jondubois** [comment]
@jtblin Yes, I think a second problem which my solution doesn't solve is that the error is not always raised when it should be.

Also my previous patch doesn't fix this issue (which I mentioned in my initial post):

"... When running the client in Node.js - The onclose handler is never called - Instead, the onerror handler will be called."

I think in this case both the onerror AND the onclose handlers should be called. This issue was simple for me to work around though, it doesn't seem as bad as the first one.

**Comment by jondubois** [comment]
@jtblin For me, when I kill the server, it's the 'end' event which is invoking the cleanupWebsocketResources function: https://github.com/websockets/ws/blob/master/lib/WebSocket.js#L777

This 'end' event comes from ultron which itself wraps a plain TCP/net socket object. This event here: https://nodejs.org/api/net.html#net_event_end

It looks like the problem here is that the TCP 'end' event is assumed to mean that the connection was closed cleanly. This is true in TCP land, but in WebSocket land, if the underlying TCP socket was closed without having both sent AND received a close control frame beforehand - Then that actually counts as a failure (1006 code?). See here: https://tools.ietf.org/html/rfc6455#section-7.1.2

**Comment by jondubois** [comment]
@jtblin @3rd-Eden This should take care of the condition where the socket is closed without having received a close control frame (which happens when you kill the server abruptly). The RFC indicates that the 1006 status code should be used in this case too.

I made a pull request: https://github.com/websockets/ws/pull/566

**Comment by piwi82** [comment]
I used a simple wrapper to get the client to reconnect automatically :
https://github.com/websockets/ws/wiki/Websocket-client-implementation-for-auto-reconnect

**Comment by lpinca** [comment]
Closing this as it seems to have been fixed by #566.
