### ISSUE TITLE
'npm install ws' can not find required files when windows on drive D

### ISSUE THREAD

**Issue by Porama6400** [websockets/ws#544]
I got error!
please tell me why

 C:\Users\Porama\.node-gyp\0.12.6\Release\node.lib : fatal error LNK1106: invalid file or disk full: 
    cannot seek to 0x1B0C8 [C:\Users\Porama\node_modules\ws\no
   de_modules\bufferutil\build\bufferutil.vcxproj]
    gyp ERR! build error
    gyp ERR! stack Error: `C:\Program Files\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
    gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\
    npm\node_modules\node-gyp\lib\build.js:269:23)
    gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
    gyp ERR! System Windows_NT 6.1.7601
    gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modu
    les\\node-gyp\\bin\\node-gyp.js" "rebuild"
    gyp ERR! cwd C:\Users\Porama\node_modules\ws\node_modules\bufferutil
    gyp ERR! node -v v0.12.6
    gyp ERR! node-gyp -v v2.0.1
    gyp ERR! not ok

**Comment by 3rd-Eden** [comment]
This is an issue with `npm` not with the `ws` module. Please open an issue in their repositories instead.
