### ISSUE TITLE
Lots of net::ERR_TIMED_OUT

### ISSUE THREAD

**Issue by binarykitchen** [websockets/ws#545]
Often my local websockets cannot reach the server and I experience the above timeouts after two minutes in Chrome.

No idea why. How can I debug this best?

In the Chrome dev console, under the network tab, I can see the websocket frames. All it shows is this one row:

```
(Opcode -1)	53	12:47:19.565
```

Length is 53. How can I see inside that? I want to see what's filling these 53 bytes. Probably it contains some information I need to know for fixing the timeouts.

On the timing tab I see that the connection has been stalled for `47.3 min`?? But the timeout occured after two minutes. I do not understand.

Thanks for any clarifications and guidance.

**Comment by woverton** [comment]
Weird.

Out of interest, does this issue occur in other browsers? Do you always see the same message in those browsers as you do chrome?  What happens if you connect to your web socket server using https://www.npmjs.com/package/wscat ?

**Comment by binarykitchen** [comment]
For other browsers I cannot say because their dev consoles cannot display websocket frames.

I doubt that wscat will help because the above issues happen by random.

For now, I suggest to improve the error mechanisms around time out handling and to throw errors with good descriptions to assist clueless, poor developers like me ;)

**Comment by binarykitchen** [comment]
@woverton yeah, with wscat it works - but i still cannot access from my app within using ws.

**Comment by woverton** [comment]
Well at least that confirms it is not an issue with your node app or server config.

**Comment by binarykitchen** [comment]
wait - can you specify the port via wscat?

**Comment by woverton** [comment]
Yes with the normal way you would with a url: wscat -c ws://echo.websocket.org:80

**Comment by binarykitchen** [comment]
thanks - i figured out that my machine on ubuntu 15.04 is having very weird networking issues i cannot reproduce nor locate. this has caused these timeouts. difficult to crack. just not related to this issue tracker.
