### ISSUE TITLE
Broadcasting messages does not work consistently (some message is lost)

### ISSUE THREAD

**Issue by bitliner** [websockets/ws#548]
My use case is the following:
- the server receives a message that then is forwarded to all connected clients
- if I send to the server messages very fast, some one is lost

Imagine, for example, a user _user1_ that types in an input text. Each typed letter is sent to the server - that broadcast the letter to other clients.
.
But other users don't receive some of the last messages, this is happening every time _user1_ types quiet fast.

Is this the expected behavior?
Is there any issue under heavy load that I should take care of?

**Comment by goldfire** [comment]
Do you have any sample code?

**Comment by bitliner** [comment]
No

**Comment by woverton** [comment]
Do you think you could mock up some code so we can investigate it a bit further?

Thanks

**Comment by woverton** [comment]
It certainly is not expected behaviour. Are you sure all messages are reaching the ws server? Have you incorporated any custom/accidental locking?

**Comment by bitliner** [comment]
It did not happen again. I will run more test in the next future, going to investigate more and provide more details if I will be able to repicate it

**Comment by lpinca** [comment]
Closing, please reopen or comment if the issue reappears.
