### ISSUE TITLE
Can't install ws on iojs v3.0.0

### ISSUE THREAD

**Issue by tresdin** [websockets/ws#549]
I've tried to install `ws` on iojs v3.0.0 and it fails at `node-gyp rebuild` stage. Is there any work around for this issue?

**Comment by 3rd-Eden** [comment]
To be honest here, if that part fails, it's really iojs / npm to blame as these are *optional* binary dependencies that fail to build (work is already being done to get them working on iojs 3). They should just ignore the node-gyp and continue with the installation of the module.. 

I would suggest also reporting these issues at npm/iojs's repositories. Having that said, community members are already fixing parts of the failing code in the related websockets/* repositories.

**Comment by tresdin** [comment]
@3rd-Eden I have know idea about the cause, otherwise I've done that.

**Comment by 3rd-Eden** [comment]
Please confirm that master is working, i've bumped the optionalDependencies now that they support nan 2.0 for iojs 3.0

**Comment by tresdin** [comment]
It fails with same error.

**Comment by tresdin** [comment]
It actually works fine with `rebuild` but `install`.

**Comment by 3rd-Eden** [comment]
Did you install it using `npm install websockets/ws` ? Or in a different way?

**Comment by 3rd-Eden** [comment]
This is my output with the latest iojs:

```
\
> utf-8-validate@1.2.0 install /Users/V1/Projects/node_modules/ws/node_modules/utf-8-validate
> node-gyp rebuild

  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/validation.node

> bufferutil@1.2.0 install /Users/V1/Projects/node_modules/ws/node_modules/bufferutil
> node-gyp rebuild

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/bufferutil.node
ws@0.7.2 node_modules/ws
├── options@0.0.6
├── ultron@1.0.2
├── utf-8-validate@1.2.0 (bindings@1.2.1, nan@2.0.5)
└── bufferutil@1.2.0 (bindings@1.2.1, nan@2.0.5)
```

**Comment by tresdin** [comment]
No. I use the instructed command `npm install --save ws`.

**Comment by 3rd-Eden** [comment]
Ok, that just installed the latest published release in npm, not the one from github's master branch.

**Comment by tresdin** [comment]
I got your output with `npm install websockets/ws`.

**Comment by 3rd-Eden** [comment]
The release is out. Thanks for your patience.
