### ISSUE TITLE
Is it possible to send gzipped data over websockets?

### ISSUE THREAD

**Issue by McFarts** [websockets/ws#554]
I used a library called LZ-String:

http://pieroxy.net/blog/pages/lz-string/index.html

And it works fine, but only if you do compressToUTF16.

100KB of JSON data is actually compressed to like 10kb which is amazing.

Problem is, I want to gzip the data over the websocket instead to get even a lower filesize. But, when gzipping stuff and sending the data across the websocket pipe, it's all encoded data and not utf16, and plus I don't know of a gzip decoder for javascript.

Any help is much appreciated, ty

**Comment by 3rd-Eden** [comment]
https://github.com/websockets/ws/blob/master/doc/ws.md#optionspermessagedeflate is what you're looking for.
