### ISSUE TITLE
Please version bump ws to 0.7.3 for easy npm install

### ISSUE THREAD

**Issue by CxRes** [websockets/ws#555]
Currently npm picks up `ws` at `0.7.2` with `bufferutils` and `utf-8-validate` at `1.1.x`. 

This becomes massively inconvenient while installing upstream libraries that include `ws` at `0.7.x` or `latest` on iojs 3.0.0 where I need to manually change `package.json` in those projects. 

Please version bump. Thanks!!!!!

**Comment by ronkorving** [comment]
+1

**Comment by 3rd-Eden** [comment]
As the binary internals required a refactor to work, the ws version is bumped to 0.8 - but the release is out. Thanks for your patience.

**Comment by ronkorving** [comment]
Awesome, thanks!
