### ISSUE TITLE
Core dump when running the test suite with io.js 3.1 and gcc/g++ 4.9 

### ISSUE THREAD

**Issue by ide** [websockets/ws#558]
The native npm deps compile for io.js 3.x with gcc/g++ 4.9 on Travis CI's Docker container, but the test suite core dumps. These are the logs: https://travis-ci.org/websockets/ws/jobs/76527772#L489. Making note of this problem here & hope the community can help figure this out.

**Comment by Nibbler999** [comment]
This is probably https://github.com/websockets/bufferutil/issues/1

**Comment by ide** [comment]
Very interesting. Thanks for the pointer about -O2. Maybe bufferutil/ws should just use that.

**Comment by ide** [comment]
Tried running ws with bufferutil and utf-8-validate built with -O2 but no luck.

**Comment by 3rd-Eden** [comment]
The release is out. Thanks for your patience.

**Comment by 3rd-Eden** [comment]
(And contributions)
