### ISSUE TITLE
proxy websocket?

### ISSUE THREAD

**Issue by atian25** [websockets/ws#559]
hi, I'm using `node-http-proxy` to proxy websocket, but got some trouble at modify the response,
after search, not found any websocket frame parser for node.

so I wonder, can I use some class from `ws` to decode/encode message?  any example?

or will `websockets/ws` support proxy to another websocket && support modify req/res message.

thanks

**Comment by nguyenvanhau** [comment]
Also, could you please add some options to use proxy directly. It's so helpful for many server.
Thanks

**Comment by woverton** [comment]
Mind if I ask the use cases for this? I have been using HAProxy to proxy web sockets with no issues. HAProxy will be faster than node as a proxy.

**Comment by atian25** [comment]
node adapter :  target ws server don't support `wss` , or want to modify res/resp to target server

**Comment by woverton** [comment]
Oh I get you, that's pretty cool. You will probably have to act as a ws server and then be a client to the destination. ws uses secure keys to talk (https://github.com/websockets/ws/blob/master/lib/WebSocket.js#L612) so you would have to really rip ws apart to do this I think.

(I'm not a ws dev, just did some digging)

**Comment by woverton** [comment]
Just found this: https://github.com/websockets/ws/pull/514

It needs some defining before a dev will merge it though.

**Comment by atian25** [comment]
@woverton you're right, and sometime, we need to do some dirty thing in node ws server, then proxy to target server, such as :
- do special auth at node server on connection
- modify the response to add some data :  target response {uid:123}  , node query db for uid, then return {uid:123, nickName:'xxx'}

**Comment by felicienfrancois** [comment]
@atian25 @woverton You should have a look at [http-mitm-proxy](https://github.com/joeferner/node-http-mitm-proxy).
This is a nodejs MITM proxy (i.e. which allow to read and change request and response). It supports HTTPS and WebSocket out of the box

**Comment by lpinca** [comment]
Another option is https://www.npmjs.com/package/https-proxy-agent, closing.
