### ISSUE TITLE
How can I use per-message-deflate with gzip compression?

### ISSUE THREAD

**Issue by McFarts** [websockets/ws#561]
Just curious as I cannot find really anything about per message deflate.

Basically I want to send a deflated (compressed) gzip string (or data) over the websocket pipe as as string to the client, is that possible?

What compression algorithm does perMessageDeflate use, gzip as well? How exactly can I set that up?

**Comment by Nibbler999** [comment]
[Deflate](https://en.wikipedia.org/wiki/DEFLATE) is the name of the algorithm and it's enabled by default. You can't use gzip.

**Comment by McFarts** [comment]
Hmm, so that means the 'bytes' that I see here: 

![](https://i.gyazo.com/f4b856acf03ea7f0bcd4030312f2383e.png)

Are not truthy? I need to take consideration of Deflate? What's the real amount of data being sent over the pipe then?

**Comment by lpinca** [comment]
Closing this as there is not much to do here.
