### ISSUE TITLE
What's new in 0.8?

### ISSUE THREAD

**Issue by julien-f** [websockets/ws#562]
Is it safe to upgrade?

**Comment by 3rd-Eden** [comment]
Upgraded to the latest NaN for IO.js which required a rewrite and major version bump of the binary addons. So yes, it should be safe to upgrade in most cases.

**Comment by julien-f** [comment]
Thank you :)

It would be nice to put your answer in the [releases page](/websockets/ws/releases) in case someone else wonders the same thing.
