### ISSUE TITLE
Where has wscat gone?

### ISSUE THREAD

**Issue by woverton** [websockets/ws#563]
I noticed that when installing ws I do not get the wscat command?

Any tutorial seems to state that this should work, for example: http://einaros.github.io/ws/

I did find https://www.npmjs.com/package/wscat which does correctly install, but the github link is now gone. I find this command very useful and hope that it was not purposely removed :)

**Comment by Nibbler999** [comment]
It was split off into its own module, see #256 

https://github.com/websockets/wscat

**Comment by woverton** [comment]
Ah okay, I'll open an issue on that project to fix their npm link.

Thanks
