### ISSUE TITLE
performance feature - send array of buffers (iovecs)

### ISSUE THREAD

**Issue by guymguym** [websockets/ws#564]
Hi

I was doing some profiling on my application that uses ws. My application protocol creates a json and then number of bulk buffers after it per each message. Sending these as one framed message required the application to call `Buffer.concat()` right before calling `ws.send()`, which was very noticeable in the profiler - 30% of the cpu of the sender in benchmark doing just sends and waiting for acks.

It was rather easy to change in the sender to accept an array of buffers and iterate to send on the socket, just like iovecs I/O operations in linux. in my benchmark this got me ~25% performance improvement.

After that I saw that now the receiver is also hogging the cpu for buffer copying.
In theory it sounds possible to allocate the exact buffer size needed after reading just the header of the message, but I haven't yet managed to find how to change.

Is that a good candidate for pull-request?

Thanks,
Guy

**Comment by woverton** [comment]
I would certainly like to look at your code. Faster is better in my books :)

**Comment by 3rd-Eden** [comment]
I'll be more then happy to support that.

**Comment by guymguym** [comment]
see suggested code in #565

**Comment by guymguym** [comment]
I added a benchmark in `bench/iovecs.js` that runs a comparison for such protocols that require multiple buffers per message. here are the results on my mac-air:

```
Sending messages with 1 buffers of 8 kB (options {"binary":true,"compress":false,"mask":false})
without iovecs:	5s	13.38 MB/s
with    iovecs:	5s	15.03 MB/s
 
Sending messages with 8 buffers of 1 kB (options {"binary":true,"compress":false,"mask":false})
without iovecs:	5s	14.24 MB/s
with    iovecs:	5s	14.69 MB/s
 
Sending messages with 1 buffers of 128 kB (options {"binary":true,"compress":false,"mask":false})
without iovecs:	5s	92.57 MB/s
with    iovecs:	5s	117.15 MB/s
 
Sending messages with 8 buffers of 16 kB (options {"binary":true,"compress":false,"mask":false})
without iovecs:	5s	89.74 MB/s
with    iovecs:	5s	109.43 MB/s
 
Sending messages with 1 buffers of 1 MB (options {"binary":true,"compress":false,"mask":false})
without iovecs:	5.1s    201.12 MB/s
with    iovecs:	5s	241.12 MB/s
 
Sending messages with 8 buffers of 128 kB (options {"binary":true,"compress":false,"mask":false})
without iovecs:	5s	202.38 MB/s
with    iovecs:	5s	253.14 MB/s
 
Sending messages with 1 buffers of 128 kB (options {"binary":true,"compress":false,"mask":true})
without iovecs:	5s	78.33 MB/s
with    iovecs:	5s	106.79 MB/s
 
Sending messages with 1 buffers of 128 kB (options {"binary":true,"compress":true,"mask":true})
without iovecs:	5s	13.83 MB/s
with    iovecs:	5s	13.68 MB/s
```
