### ISSUE TITLE
Can we get 0.7.2 binaries uploaded?

### ISSUE THREAD

**Issue by BrianGenisio** [websockets/ws#568]
Trying to upgrade an upstream package (protractor) on Windows, which ultimately requires ~0.7.1 of WS.  Everything used to work with 0.7.0 because we can pull the binaries, but in 0.7.2, we get the infamous "python missing" error.  

Can we get 0.7.2 windows binaries pushed to the cloud?

**Comment by 3rd-Eden** [comment]
We never published binaries, it was always a compile step during installation.

**Comment by BrianGenisio** [comment]
Interesting.  Thanks for this update.

I don't have Python installed on my machine, although installing 0.7.0 does not fail.  0.7.2 fails telling me that I need Python.

Any idea why one would work, and the other would not?
