### ISSUE TITLE
Cannot get Clustering to work

### ISSUE THREAD

**Issue by McFarts** [websockets/ws#571]
Hey,

So basically I setup a test ws server like so:

```
var cluster = require('cluster');

if (cluster.isMaster) {
	var numCPUs = require('os').cpus().length;
	for (var i = 0; i < numCPUs; i++) {
		cluster.fork();
	}

} else {
	var WebSocketServer = require('ws').Server,
		wss = new WebSocketServer({
			port: 9300,
			maximumPayload: 200,
			speedLimit: 5
		}); // speedLimit is in miliseconds 5ms // Payload is in bytes ~ 1048576 = 1 MB.  (Length of websocket message is around 500k with this setting)
	wss.on('connection', function connection(ws) {

		ws.on('message', function incoming(message) {
			console.log('received: %s', message);
		});


		setInterval(function() {

			var obj = {
				'abcdef': 1,
				'qqq': 13,
				'19': [1, 2, 3, 4]
			};
			for (var i = 0; i < 5000; i++) {
				ws.send(' ' + JSON.parse(JSON.stringify(obj)));
			}
		}, 500);
	});
}
```

Which works fine, and I get 6 processes spawned.  (I have 6 cores), but after waiting 2-4 minutes, look at the memory usage for each process:
![](https://i.gyazo.com/254c355d84568312edd35e98909d641d.png)
It looks like the main process is still consuming everything. Is there a limit of the amount of memory consumption it uses before clustering it to other processes?

**Comment by 3rd-Eden** [comment]
I don't see how this is a `ws` issue. It looks more like a `node` issue to me where it doens't correctly load balance your cluster. I suggest creating an issue in their repository to get this resolved.
