### ISSUE TITLE
WS Unique ID

### ISSUE THREAD

**Issue by dweberlj** [websockets/ws#573]
How do I get an unique ID from a 'connection' so I can send direct messages to that client?

**Comment by McFarts** [comment]
You either need to reference the socket._sender object to an object (that user), and then use that to send information to them if they are still connected

**Comment by lpinca** [comment]
@dweberlj clients don't have a unique identifier. You can create a unique id in the `connection` listener and add it to client if you want that.

**Comment by greenbea** [comment]
Is this the ideal way to set an ID to for client?
```
wss.on("connection", (socket, request) => {
  console.log("Client Connected")
  socket.id = unique_id
});
``

**Comment by netizen-ais** [comment]
> Is this the ideal way to set an ID to for client?

This is not an issue, question would be better at SO. Anyway, ideal is not only subjective, but in this context it even depends heavily on your chosen code arquitecture
