### ISSUE TITLE
Why socket.setTimeout(0)?

### ISSUE THREAD

**Issue by binarykitchen** [websockets/ws#584]
RFC declare that web sockets should timeout after a certain period of inactivity.

**Comment by nkzawa** [comment]
Can I ask where can I find the definition?

**Comment by binarykitchen** [comment]
just search:
https://github.com/websockets/ws/blob/7debd827d39925650bba5a270811ed82616f0eb1/lib/WebSocketServer.js#L242
https://github.com/websockets/ws/blob/7debd827d39925650bba5a270811ed82616f0eb1/lib/WebSocketServer.js#L391

**Comment by nkzawa** [comment]
Sorry, I'd like to know where the definition of the timeout is on RFC.

**Comment by binarykitchen** [comment]
this rfc does not mention anything about a timeout but recommends a ping pong mechanism to keep the connection alive: https://w3c.github.io/websockets/

> 6 Ping and Pong frames
> 
> The WebSocket protocol specification defines Ping and Pong frames that can be used for
> keep-alive, heart-beats, network status probing, latency instrumentation, and so forth. These are
> not currently exposed in the API.
>
> User agents may send ping and unsolicited pong frames as desired, for example in an attempt to
> maintain local network NAT mappings, to detect failed connections, or to display latency metrics to
> the user. User agents must not use pings or unsolicited pongs to aid the server; it is assumed that
> servers will solicit pongs whenever appropriate for the server's needs.

In other words, this mechanism should be used instead of disabling the timeout. I think this is correct because disabling the timeout is not a guarantee that the connection is still alive.

**Comment by nkzawa** [comment]
So I think that's the reason of  `socket.setTimeout(0)`, there is no timeout of inactivity except ping pong. You need to call `ws.ping()` manually, though WebSocket on browser doesn't have `ping`.

**Comment by binarykitchen** [comment]
Exactly. And when `ws.ping()` is used, then the code line `socket.setTimout(0)` shouldn't be here. A bit tricky I guess.

**Comment by nkzawa** [comment]
`socket.setTimout(0)` looks good to me since it disables unexpectedly added timeouts. A socket must not have a timeout, and the method call will make that clear.
