### ISSUE TITLE
Permessage-deflate extension fails on streaming binary data

### ISSUE THREAD

**Issue by tresdin** [websockets/ws#585]
The error `invalid compressed data` occurs while I was trying uploading multiple files (mostly 10 files) to server via websocket. The raw data seems to be incorrectly decompressed by `per-message deflate` extension. The connection is closed due to this error.
![pmderror](https://cloud.githubusercontent.com/assets/7781091/9901372/7d9e06ae-5c91-11e5-9edc-f88460581c0a.png)

**Client - Chrome**

```
inputFileElement.onchange = function(){
    let files = this.result;
    let chunkSize = 32768; //32KB
    let fr = new FileReader();
    fr.onload = function(){
        let buffer = this.result;
        let offset = 0;
        for(let i=0,len = Math.ceil(buffer.byteLength/chunkSize);i<len;i++){
            WebSocket.send(buffer.slice(offset,offset+chunkSize));
            offset += chunkSize;
        }
    };
};
```

**Server**

```
ws.on('message',function(message){
    if(message.byteLength){
            console.log('id',file.id,'chunk size',message.byteLength,'size',file.size);
    }
});
```

This error can be fixed by disabling _per-message deflate_ extension or reducing the number of uploading files to less than 3.

**Comment by yutakahirano** [comment]
https://crbug.com/532424

**Comment by nkzawa** [comment]
@tresdin Thanks for your report. Can you try https://github.com/websockets/ws/pull/595 if possible ?

**Comment by tresdin** [comment]
@nkzawa Sorry for the late reply. I've tried your fix and it works perfectly after that.

**Comment by nkzawa** [comment]
@tresdin thx!
@3rd-Eden can you review #595 ?
