### ISSUE TITLE
Nodejs 4.0.0 support

### ISSUE THREAD

**Issue by hinell** [websockets/ws#586]
It seems there is a lot of problems with [an engine.io building issue](https://github.com/socketio/socket.io/issues/2228) related to this dependency. 
Need your help to resolve it. 
socketio/socket.io#2228

**Comment by 3rd-Eden** [comment]
Bug socket.io about updating their dependencies. Also, it's not a build failure it's an **optional** dependency that fails to build, the install is still correct.

**Comment by jokeyrhyme** [comment]
With asm.js and V8 improvements lately, is it possible that the JavaScript implementation is close to the native implementation in performance? Beyond performance, are there other reasons to have this optional dependency?
