### ISSUE TITLE
IPv6 connections rejected?

### ISSUE THREAD

**Issue by Mygod** [websockets/ws#588]
```
var ws = require('ws');
new ws.Server({ port: 9999 });
```

Then connecting to `127.0.0.1:9999` gives `not implemented`, while `[::1]:9999` gives `ERR_CONNECTION_REFUSED`.

**Comment by lpinca** [comment]
By default the server is bound to `0.0.0.0` or any IPv4 address. Can you try using a custom hostname? You can specify it via the `host` option.
