### ISSUE TITLE
Implementing WS as a stream without affecting current functionality

### ISSUE THREAD

**Issue by Gray1989** [websockets/ws#596]
I seem to have succeeded in implementing your WebSocket object as a native Node-based duplex stream, complete with automatic data flow-control (back-pressure management), and seemingly without causing any adverse or negative side-effects. One continuous stream can be piped to a slower stream without worry. Also, it doesn't actually affect it at all performance-wise when using it as normal, as it uses a trigger to detect when it's being used as a stream and then completes the setup of the stream from there, and can either be used as a stream or just as-is without any extra actions necessary.

I've never done so before, but I would be willing to do one of those pull request things. Or I can even just give snippets of code with instructions on what to do. Please let me know as I am actually very interested in getting this working in the official copy and I'm sure there are many others as-well.

**Comment by yunong** [comment]
@Gray1989 Do you have this implementation available somewhere? This would be great for us too -- since we'd prefer to just be able to leverage WS as a node.js stream.

**Comment by Gray1989** [comment]
I will make a fork and update when I have the time

**Comment by Gray1989** [comment]
@yunong Please check this pull request https://github.com/websockets/ws/pull/602

You may also try out the module by installing it with NPM using a little-known command:
`npm install -i --save https://github.com/Gray1989/ws/tarball/master`

**Comment by Gray1989** [comment]
@yunong I did make an implementation without actually modifying the source-code of ws itself. With this implementation you need to pass an instance of the WebSocket as the first parameter when creating a `new WSStream` object, and it will return you an instance of a stream object you can use. It also has full flow-control/back-pressure support. I think you may like this implementation more as it will allow you to use the ws module as a stream but also be able to update it when necessary without having to re-mod it. I'm sure you'll end up changing it to suit your needs anyways so here it is:

```javascript
var WSStream = (function(){
	var WSStream = function(ws, wsOptions, streamingOptions) { // Only the websocket (ws) is mandatory
		// Proper duplex stream with automatic flow control (backpressure) management
		if(!(this instanceof WSStream)) return new WSStream(ws, wsOptions, streamingOptions);
		if(!(wsOptions instanceof Object)) wsOptions = {binary: false};
		Duplex.call(this, streamingOptions);
		this.waitingForData = true;
		this.writeModBufferEmpty = true;
		this.webSocket = ws;
		this.webSocketOptions = wsOptions;
		this.on("finish", finishEventHandler(this));
		ws._socket.write = writeMod(ws._socket.write, this);
		ws._socket.on("drain", drainEventHandler(this));
		ws._socket.on("error", errorRouter(this));
		ws.on("close", closeEventHandler(this));
		ws.on("message", messageHandler(this));
		},
	finishEventHandler = function(self) {
		return function() {
			if(self.webSocket !== null) {
				self.webSocket.close();
				self.webSocket = null;
				};
			self.emit("close");
			};
		},
	writeMod = function(nativeWriteFunction, self) {
		return function() {
			return self.writeModBufferEmpty = nativeWriteFunction.apply(this, arguments);
			};
		},
	drainEventHandler = function(self) {
		return function() {
			self.writeModBufferEmpty = true;
			self.emit("drain");
			};
		},
	closeEventHandler = function(self) {
		return function() {
			self.push(null);
			}
		},
	errorRouter = function(self) {
		return function() {
			self.emit.apply(self, ["error"].concat(arguments));
			};
		},
	messageHandler = function(self) {
		return function(data) {
			if(!self.push(data) && self.waitingForData) {
				self.webSocket._socket.pause();
				self.waitingForData = false;
				}
			};
		};
	util.inherits(WSStream, Duplex);
	WSStream.prototype._read = function(size) {
		if(!this.waitingForData) {
			this.waitingForData = true;
			this.webSocket._socket.resume();
			}
		};
	WSStream.prototype._write = function(chunk, encoding, callback) {
		this.webSocket.send(chunk, this.webSocketOptions, callback);
		return this.writeModBufferEmpty;
		};
	return WSStream;
	}());
```

Usage: `wsStream = new WSStream(ws)`
