### ISSUE TITLE
Web socket connection errors - socket hang ups after re-opening new connections

### ISSUE THREAD

**Issue by s1riedel** [websockets/ws#597]
I have been having problems using the WS module for some months now under relatively high-volume scenarios. We are using Ubuntu for the client servers as well as the server-side servers. The initial websockets/connections work fine, however, after running for a little while, closing existing web sockets and attempting to open new web socket connections, all new connections are refused and the following error is received on the client side:

{ '0': { [Error: socket hang up] code: 'ECONNRESET', sslError: undefined } }
Error: socket hang up

No server-side errors are received/logged/thrown. Despite tweaking all kinds of server settings for number of connections, memory thresholds, etc, we have not been able to identify the cause of the issue or any kind of resolution. The memory and CPU usage on both the client and server-side servers do not show any kind of spike or issues such as running out of CPU/memory. 

Any help would be greatly appreciated. Thank you.

**Comment by ChandanLal** [comment]
i am also getting the same error. Please help me too.

**Comment by kamilbiela** [comment]
@s1riedel do You have ping/pong mechanism implemented to keep alive connection, etc? also, try to use socket through wss://

**Comment by s1riedel** [comment]
Yes, we send a ping/pong every 2 minutes through the web socket to keep it alive.

Could you please clarify what you mean by "try to use socket through wss://"? Do you mean when the connection is opened to use the wss:// protocol? If that is what you mean, that is already how I am doing connections.

Thank you.

**Comment by kamilbiela** [comment]
@s1riedel just to calrify, I'm not maintainer of this project, I have just throw some ideas that might help You. Maybe try to use older/newver version? Also check if You have latest version installed. By default "npm install" installs older v0.42 not 0.8 version in my case for some odd reason.

**Comment by s1riedel** [comment]
We are using version 0.8. 

Thank you for the ideas. I've tried everything I can think of.

**Comment by kamilbiela** [comment]
maybe problem is in proxy then? also maybe but ngnix in front of node, and log all connections. Also You could try to upgrade node version (or dig through changelog)? Whats Your infrastructure? What server provider You use?

**Comment by mkozjak** [comment]
+1 on this.

nodejs version 5.8.0, ws 1.0.1.

backend is a qt5 application with QWebSocketServer using SecureMode (same happens with NonSecureMode)
no errors are reported on the backend. 'ws' client sends a RST packet, which produces the ECONNRESET error.

**Comment by s1riedel** [comment]
@mkozjak@mkozjak It does appear that I am using a much older version of the ws module - version 0.6.5. I will try with the newer version.

Thanks!

**Comment by s1riedel** [comment]
@kamilbiela We have tried having NGINX in front of the requests, and get the following error in the logs:

2016/06/02 18:51:25 [error] 902#0: *527 upstream prematurely closed connection while reading response header from upstream, client: *.*.*.*, server: *.****, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:8443/", host:*** 

(private info hidden with asterisks **)

**Comment by Geek4IT** [comment]
@s1riedel Hi, have you fixed the prematurely closed  problem? Pls have a look at this:

[upstream prematurely closed connection while reading response header from upstream](http://stackoverflow.com/questions/38812677/upstream-prematurely-closed-connection-while-reading-response-header-from-upstre)

If you have any idea, pls help me. Thank you.

**Comment by s1riedel** [comment]
@Geek4IT Sorry, I have not made any progress on this issue. Good luck with this.

**Comment by lpinca** [comment]
Closing this, please comment or reopen if needed.

**Comment by chishi2612** [comment]
@s1riedel could you share me how to fix this problem?
