### ISSUE TITLE
What is best way to compare 2 sockets?

### ISSUE THREAD

**Issue by fkkcloud** [websockets/ws#601]
I have sockets hash as

```
var socket_hash = {};
socket_hash[guid] = ws;
```

and I want to compare the sockets but 

```
if (socket_hash[guid1] != socket_hash[guid2]) //seems like heavy compare..
```

is there like unique string ID that I can use to compare the sockets?

**Comment by aaronryden** [comment]
why not assign a GUID for each new connection and store on the ws property? you can store guid -> ws in a map.

**Comment by lpinca** [comment]
> if (socket_hash[guid1] != socket_hash[guid2])

is actually very fast and lightweight as you are only comparing two references, way better than comparing two strings.
