### ISSUE TITLE
wscat: unsupported protocol version

### ISSUE THREAD

**Issue by thauer** [websockets/ws#612]
I just installed ws on ubuntu 15.04 (with `npm install -g ws`) and when running `$ wscat -c ws://echo.websocket.org -p 8`,  I get an exception from 

```
  if (options.value.protocolVersion !== 8 && options.value.protocolVersion !== 13) {
    throw new Error('unsupported protocol version');
  }
```

The reason being that at this point, when specified on the command line, `options.value.protocolVersion` seems to be a `String`, rather than a `Number`.

**Comment by janpieper** [comment]
I have the same problem.

`options.value.protocolVersion` is a string, not a number!

**Comment by Ugarz** [comment]
Right, thanks to @thauer and @janpieper this worked for me !
In file located at `/usr/local/lib/node_modules/wscat/node_modules/ws/lib/WebSocket.js:568:11` (i'm using a mac).
Replace the if statement line 567 by this (just add `"`around numbers):
```javascript
if (options.value.protocolVersion !== "8" && options.value.protocolVersion !== "13") {
    throw new Error('unsupported protocol version');
  }
```

**Comment by oblalex** [comment]
I also confirm this.

**Comment by lpinca** [comment]
Fixed in https://github.com/websockets/wscat/commit/4de45ae56f817a37af5a2a689b7e1c59f748e441.
