### ISSUE TITLE
node-gyp rebuild fails due to outdated bufferutil version

### ISSUE THREAD

**Issue by arikalfus** [websockets/ws#620]
When running `npm install cluster-store`, the build would fail due to node-gyp rebuild from bufferutil. After some investigation, I found that cluster-store's dependency is ws, which has a dependency on bufferutil for 1.1.x. The current version of bufferutil is 1.2.0, and after briefly speaking with the maintainers of bufferutil, ws' dependency on bufferutil should be updated to resolve this issue.

**Comment by Nibbler999** [comment]
No, `cluster-store` needs to update its ws dependency to 0.8.0
