### ISSUE TITLE
[Question] Why does `wss.send` block?

### ISSUE THREAD

**Issue by NoelAbrahams** [websockets/ws#624]
Hi,

I have a long-running request handled by a method on a web service as below:

```typescript

function longRunningTask(wss/*Reference provided by NodeJS when routing the request*/) {

  wss.clients[0].send('Starting task 1...');

  // Carry out IO work 1
  doFoo();

   wss.clients[0].send('Completed task 1');
   wss.clients[0].send('Starting task 2...');

  // Carry out IO work 2
  // etc.

   wss.clients[0].send('Complete all tasks);
  return 'Success';
}

```

I have a single browser client connected to the web service. The client connects to WS on load then  executes `longRunningTask` via HTTP.

The problem I'm having is that all the messages arrive from the server only on completion of the HTTP request. My expectation is that the socket messages should arrive as they are emitted. But instead I get (in one bunch)
```
Starting task 1...
Completed task 1
Starting task 2...
Complete all tasks
Success
```

I'm guessing this is a problem with the single-threaded executing context in NodeJS.

Is there a solution to this problem?

**Comment by Eeems** [comment]
You could probably setup some sort of lazy send that runs on the next tick instead of immediately.
http://howtonode.org/understanding-process-next-tick

**Comment by NoelAbrahams** [comment]
@Eeems, that seems like the logical thing to do, and in fact I tried `setTimeout` and `nextTick` and they do not work. 

What did work in the end was to fork out a child process.

```typescript
import * as cp from 'child_process';

const worker = cp.fork('./worker');

// later.
worker.send('message');
```

and do the socket work in `worker.js`.

I'm closing this as I've found a resolution. Thanks.
