### ISSUE TITLE
IP Address of WebSocket

### ISSUE THREAD

**Issue by ghost** [websockets/ws#626]
How can one get the IP address from a `ws` object? I realise that an issue has been opened about this already but that returned 127.0.0.1, aka the server's IP.

**Comment by kparperi** [comment]
This is what i use to get the IP address,
function getIPInfo(ws) {
    return {
        remoteIP: ws.upgradeReq.connection.remoteAddress,
        family: ws._socket._peername.family,
        port: ws._socket._peername.port
    };
};

**Comment by Eeems** [comment]
Issues #338 and #117 already answer this.
Are you testing this all locally? If so that's probably why your IP would be 127.0.0.1.

**Comment by kracekumar** [comment]
`socket._socket.remoteAddress` yields `127.0.0.1`. Web socket client is connected via mobile client.

I am running the server behind EC2 load balancer and process is managed by `supervisord`.

**Comment by EthanRutherford** [comment]
The value of `ws.upgradeReq.connection.remoteAddress` is the server's public IP for me, what is going on?

**Comment by DubiousDillan** [comment]
`ws.upgradeReq.connection.remoteAddress` does not exist..

**Comment by lpinca** [comment]
@katp4's example should work.

@EthanRutherford if you use a reverse proxy `ws.upgradeReq.connection.remoteAddress` will be the IP of the proxy.

@DubiousDillan the value may be undefined if the socket is destroyed (for example, if the client disconnected).
