### ISSUE TITLE
Nasty client memory leak

### ISSUE THREAD

**Issue by rorph** [websockets/ws#629]
I've been using ws client on server-side to do multiplexing, turns out it has a nasty memory leak on upgradeHeader handler.

The server was patched, but looks like the client wasn't.
I'm attaching a patch file with the fix for this.

[WebSocket.patch](https://github.com/websockets/ws/files/58453/WebSocket.patch.txt)

Cheers

**Comment by Eeems** [comment]
You may want to open a pull request instead of attaching a patch file.

**Comment by rupamkhaitan** [comment]
Is this patch for memory leak on the server side?
We use ws library to open socket connection on our server side, will this patch have impact on memory leak on server side?

**Comment by JoshuaWise** [comment]
If anyone is still experiencing this, please reopen the issue of submit a pull request.
