### ISSUE TITLE
No certificate options?

### ISSUE THREAD

**Issue by izy521** [websockets/ws#630]
I'm working with someone who primarily uses a PHP backend, and was tasked to create a chat service using WebSockets (on a Node backend). It worked fine until we required HTTPS. Looking around, it seems as though all certificate options require Express to be running. So do I require an entire webserver framework just for a secure connection?

**Comment by Eeems** [comment]
From what I understand you should just be able to create a [https server](https://nodejs.org/api/https.html#https_https_createserver_options_requestlistener) and pass that over to ws to use.

**Comment by izy521** [comment]
Yeah, I saw that and was kind of hoping to avoid doing so, but thank you very much.
