### ISSUE TITLE
a question about 'wscat'

### ISSUE THREAD

**Issue by clearbug** [websockets/ws#631]
when i use 'wscat -c ws://echo.websocket.org -p 8' (from http://websockets.github.io/ws/), terminal show 'wscat: command not found' .my ws is ws@0.8.1 .Has the command been removed?

**Comment by lpinca** [comment]
@clearbug `wscat` has been extracted and moved into its own repo https://github.com/websockets/wscat.

**Comment by clearbug** [comment]
@lpinca Thank you !

**Comment by arkon** [comment]
The [website](https://websockets.github.io/ws/) should probably updated to reflect this.

**Comment by lpinca** [comment]
@arkon yes, see https://github.com/websockets/ws/commit/cb1cb6d2e96586c83e908227179daa205b775dbe
Not sure why deploy failed.
