### ISSUE TITLE
node_zlib.cc: Assertion '(false) == (ctx->pending_close_ && "close is pending")' failed

### ISSUE THREAD

**Issue by jancurn** [websockets/ws#633]
I received this assertion failure when working with the ws package (the node.js process crashed right after that):

`node: ../src/node_zlib.cc:124: static void node::ZCtx::Write(const v8::FunctionCallbackInfo<v8::Value>&) [with bool async = true]: Assertion '(false) == (ctx->pending_close_ && "close is pending")' failed.`

A simplified code that I was using:

``` javascript
// ws is a WebSocket object for an accepted connection (i.e. this is a server)
ws.on('close', function (code) {
    // this guy gets called too
});
ws.send(myLongMessage, function ack(err) {
    if( err )
        ws.close(1003);
});
```

IMHO WebSocket should check that `_deflate` stream is not closed in `PerMessageDeflate.js`.

**Comment by 3rd-Eden** [comment]
Is this still an issue in the latest release?

**Comment by jancurn** [comment]
sorry I don't know, this error happened to me only once and haven't repeated since then

**Comment by Regul777** [comment]
I have this error almost each hour and my node.js is crushes :( Maybe, I can help with this problem?

**Comment by 2PacIsAlive** [comment]
I am still seeing this issue, was there a fix?

**Comment by lpinca** [comment]
@2PacIsAlive do you have a way to reproduce the issue?

**Comment by 2PacIsAlive** [comment]
I'll see what I can to to get a minimal reproduction but it will take some time. Essentially, I am using socket.io, and the error occurs when I refresh my browser. Right after the client disconnects the process crashes with that error:
```
[2019-04-10T03:46:19.847] [INFO] server - RMM-UxSFb5rfpWwxAAAC disconnected
node[26976]: ../src/node_zlib.cc:150:static void node::{anonymous}::ZCtx::Write(const v8::FunctionCallbackInfo<v8::Value>&) [with bool async = true]: Assertion `(false) == (ctx->pending_close_ && "close is pending")' failed.
 1: node::Abort() [node]
 2: 0x8d071b [node]
 3: 0x943408 [node]
 4: 0xe3ae34753a7
Aborted
```
nonetheless I will work on getting a repro in place and get back to you

**Comment by marchaos** [comment]
We just had this error in our prod environment, causing node to crash. No other information other than was is provided above.

**Comment by alwaysAn0n** [comment]
I have also been getting this in one of my app's production environments ( Heroku ).

Node v.9.0.0
ws v.7.2.3

```
2020-03-19T05:38:41.474454+00:00 app[web.1]: node[12]: ../src/node_zlib.cc:150:static void node::{anonymous}::ZCtx::Write(const v8::FunctionCallbackInfo<v8::Value>&) [with bool async = true]: Assertion `(false) == (ctx->pending_close_ && "close is pending")' failed.
2020-03-19T05:38:41.484374+00:00 app[web.1]: 1: node::Abort() [node]
2020-03-19T05:38:41.484867+00:00 app[web.1]: 2: 0x8d071b [node]
2020-03-19T05:38:41.485368+00:00 app[web.1]: 3: 0x943408 [node]
2020-03-19T05:38:41.485390+00:00 app[web.1]: 4: 0x2e7aefa3d747
```

**Comment by jancurn** [comment]
@lpinca perhaps we should re-open this issue?

**Comment by lpinca** [comment]
If it happens only on Node.js 9 no as that version no longer supported.

**Comment by marchaos** [comment]
We've upgraded to node 12 on our production machines, so will report back if we see this again, but suspect that given zlib is bundled with node, this should be resolved with an upgrae
