### ISSUE TITLE
Masking key not random per-frame

### ISSUE THREAD

**Issue by SEAPUNK** [websockets/ws#634]
RFC:

```
   The masking key is a 32-bit value chosen at random by the client.
   When preparing a masked frame, the client MUST pick a fresh masking
   key from the set of allowed 32-bit values.
```

The code generates a masking key, and then reuses it for each subsequent frame: https://github.com/websockets/ws/blob/master/lib/Sender.js#L192

Is this by design?

**Comment by 3rd-Eden** [comment]
Isn't the sender instance create per connection and therefor generating a new masked frame for each client?

**Comment by SEAPUNK** [comment]
Per *connection*, it generates a new masking key. The RFC states that it should create a new masking key per frame, not connection.

**Comment by 3rd-Eden** [comment]
I guess thats a bug then.

Arnout Kazemier

**Comment by SEAPUNK** [comment]
Alright, I'll create a PR for it.

**Comment by rupamkhaitan** [comment]
Will this create any problem in terms of socket close or any packet loss for long running connection in AWS hosted machine with ELB?

**Comment by SEAPUNK** [comment]
@rupamkhaitan I wouldn't think so. The Mocha tests for my PR worked (and I'll write that test I need to write to get the PR merged), and I'll run the Autobahn test suite later.
