### ISSUE TITLE
reserved fields must be empty error on custom headers in the request

### ISSUE THREAD

**Issue by jaggukaka** [websockets/ws#637]
I'm getting "reserved fields must be empty" error repeatedly on the 'error' event of ws server when I pass custom headers from the client. The client is a different (java) implementation of websockets. 

I even tried to use the verifyClient option on ws server creation. Though verifyClient works well with the 'Origin' header present in the connection request, a few moments later the connection fails with "reserved fields must be empty" error.

I tried setting perMessageDeflate to true/false, disableHixie to true/false, but no luck.

Everything works fine when I remove this custom header or/and 'Origin' header on the client side.

Any thoughts would be appreciated, If this is not a bug and if I'm missing some configuration, please provide the required information.

Thanks

**Comment by mhamlet** [comment]
@jaggukaka, did you solved this problem?
