### ISSUE TITLE
Upgrade Required status

### ISSUE THREAD

**Issue by Bramvangemert** [websockets/ws#638]
Hi there,

I am writing a node.js application that requires a websocket. 
Even when I use:

      var WebSocketServer = require('ws').Server
       , wss = new WebSocketServer({ port: 8080 });

     wss.on('connection', function connection(ws) {
     ws.on('message', function incoming(message) {
     console.log('received: %s', message);
     });

     ws.send('something');
     });

I get a status: Upgrade Required
How do I fix this issue?

Greetings,
Bram van Gemert

**Comment by Lawris** [comment]
Hi, how did you fixed this ?

Thank you.
