### ISSUE TITLE
WebSocket server takes a lot of CPU usage and sometimes RAM.

### ISSUE THREAD

**Issue by SzAmmi** [websockets/ws#644]
```javascript
var WebSocket = require('ws');
var ws = new WebSocket.Server({ port: 8080, perMessageDeflate: false });
ws.on('connection', function(conn) {
		conn.pinging = setInterval(function() { conn.readyState == conn.OPEN && conn.ping() || clearInterval(this.pinging); }, 25000);
		conn.myArr = [];
		
		conn.onmessage = function(message) {
			json = JSON.parse(message.data);
			switch (json.action) {
				case 0:
					myArr.push(Math.random().toFixed(2));
					break;
				case 1:
					for (value of myArr) {
						console.log("case 1: " + value);
					}
					break;
				case 2:
					for (value of myArr) {
						console.log("case 2: " + value);
					}
					break;
				case 3:
					for (value of myArr) {
						console.log("case 3: " + value);
					}
					break;
				case 4:
					for (value of myArr) {
						console.log("case 4: " + value);
					}
					break;
				case 5:
					for (value of myArr) {
						console.log("case 5: " + value);
					}
					break;
				case 6:
					conn.send("case 6");
					break;
			}
		};
	});
```
When I've got 20 connections I've got usage: 300-400MB of RAM, 30%-40% of CPU. When I got 200 connections the usage is: 600-700MB of RAM, 80% - 90% of CPU. Why? Is this a bug?

**Comment by wangq8** [comment]
on Windows or on Linux?

**Comment by SzAmmi** [comment]
Ubuntu Server 15

2015-12-30 10:50 GMT+01:00 wangq8 <notifications@github.com>:

> on Windows or on Linux?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/websockets/ws/issues/644#issuecomment-167969943>.
>



-- 
Pozdrawiam,
Szymon Marczak

**Comment by wangq8** [comment]
I tested on Windows 7, with 100 connection only takes 60M (working set), should be an issue of Ubuntu?

**Comment by wangq8** [comment]
I tested on SUSE Linux 11.13, with 100 connections takes only 57M (resident set), I believe it should be an issue of Ubuntu, or did you use the virtual size as the program memory size, it is not correct.
Windows 7: working set: 60M, virtual size: 600 M
SUSE: working set: 57M, virtual size: 700 M.

**Comment by SzAmmi** [comment]
What about the CPU usage? I optimized my script and it takes max 100MB of
RAM, and about 80-100% of CPU. I ran it on a VPS (Cloud 3) -
https://www.ovh.com/us/vps/vps-cloud.xml . Probably it isn't caused by
Ubuntu, but probably by the machine - there are virtual cores, not real.
Probably I should buy a server...

2015-12-31 9:46 GMT+01:00 wangq8 <notifications@github.com>:

> I tested on SUSE Linux 11.13, with 100 connections takes only 57M
> (resident set), I believe it should be an issue of Ubuntu, or did you use
> the virtual size as the program memory size, it is not correct.
> Windows 7: working set: 60M, virtual size: 600 M
> SUSE: working set: 57M, virtual size: 700 M.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/websockets/ws/issues/644#issuecomment-168152258>.
>



-- 
Pozdrawiam,
Szymon Marczak

**Comment by wangq8** [comment]
Ah, for percentage of CPU, like 80%-100%, it is no accurate. If CPU is virtual, then it should be less accurate. I suggest you test this in your laptop, no in VM to get CPU usage. or in a real environment.

**Comment by SzAmmi** [comment]
Thanks! This topic can be closed for now.

2016-01-07 9:22 GMT+01:00 Qi Wang <notifications@github.com>:

> Ah, for percentage of CPU, like 80%-100%, it is no accurate. If CPU is
> virtual, then it should be less accurate. I suggest you test this in your
> laptop, no in VM to get CPU usage. or in a real environment.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/websockets/ws/issues/644#issuecomment-169593008>.
>



-- 
Pozdrawiam,
Szymon Marczak
