### ISSUE TITLE
How to install the ws on Windows 7?

### ISSUE THREAD

**Issue by wangq8** [websockets/ws#646]
I try to install it as steps in windows:
1. install python, and set %path% with python included.
2. npm install -g node-gyp
3. npm install ws
it failed with can not found msbuild.exe ... how could this happened? why I need msbuild.exe? it is a pure javascript, why needs c++ stuffs...

**Comment by 3rd-Eden** [comment]
Try installing the master branch, `npm install websockets/ws` -- this will be released today as 1.0.0 which has all the binary addons removed.

**Comment by 3rd-Eden** [comment]
Released 1.0.0 -- should fix this issue

**Comment by wangq8** [comment]
Thank you very much, now it is working.
