### ISSUE TITLE
webSockserver.close() does not remove old listeners from the http server

### ISSUE THREAD

**Issue by avrahams** [websockets/ws#648]
I noticed that if I close a webSocketServer instance and then create a new instance with the same path I get "Connection failed: Invalid frame header" errors in the websocket client.
The reason for that is that webSockserver.close() does not remove the listeners it set for the http server 'upgrade' & 'error' events
so when the second server was created the handleUpgrade function was called twice leading to duplicate headers 

I patch it by keeping the listeners when I create the webSoketServer instance and removing them from the http server when I close the instance 

``` javascript

//create web socket server 
this.webSocketServer = new WebSocketServer({ server: app.server, path :  '/mypath'});
//patch till this bug will be fixed in ws - 
//keep http server listeners for 'upgrade' and 'error' added by webSocketServer and remove them when the webSocketServer is closed 
this.wssErrorListener = _.last(app.server.listeners('error'));
this.wssUpgradeListener = _.last(app.server.listeners('upgrade'));
....
.//close the server
this.webSocketServer.close();
app.server.removeListener('error', this.wssErrorListener);
app.server.removeListener('upgrade', this.wssUpgradeListener);
```

**Comment by lpinca** [comment]
This should no longer be an issue. Closing.
