### ISSUE TITLE
Remove old protocol support

### ISSUE THREAD

**Issue by feross** [websockets/ws#651]
As we've learned with all the recent [TLS downgrade attacks](https://www.praetorian.com/blog/man-in-the-middle-tls-ssl-protocol-downgrade-attack), supporting old version of protocols for compatibility with ancient clients has a real cost.

By supporting 3 different websocket specifications, the attack surface area of this module is increased threefold. If someone finds a bug in _any_ of the three implementations, they can attack a server using `ws`.

It should be safe to remove support for these versions by now, right? (This would be a major version release, to be sure.)

Thoughts?

**Comment by Eeems** [comment]
We could at least disable them by default and have the documentation showing how to enable them warn the users about the potential risks of enabling them.

**Comment by 3rd-Eden** [comment]
Yes, No, Maybe.

I'm considering doing it after the whole code base has received scrub of old legacy code and a rewrite to ES6.

**Comment by feross** [comment]
Fair enough. Out of curiosity, which browsers would lose support if you dropped all but the latest spec implementation?

Would it be helpful to look up the marketshare of each browser so we know exactly what the stakes are?

**Comment by lpinca** [comment]
Hixie-76 is no longer supported. Closing.

**Comment by feross** [comment]
👏
