### ISSUE TITLE
BufferUtil should be a dependency and not a devdependency apparently

### ISSUE THREAD

**Issue by rogierschouten** [websockets/ws#658]
Since the latest version 1.0.1,  browserifying anything with a reference to ws gives the following error:

Error: Cannot find module 'bufferutil' from 'C:\myproject\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\lib'

Apparently bufferutil is referenced somewhere in the ws code while it is not installed by default?

**Comment by rogierschouten** [comment]
Same goes for module utf8-validate

**Comment by 3rd-Eden** [comment]
It's a devDependency as there is no need to depend on it directly as all require statements that reference the said module are in a try/catch statement with the correct fallback code.

As for browserify, there is no client code in this library. Exclude it from your browserify build.

**Comment by rogierschouten** [comment]
See the error message. Apparently, socket.io-client depends on engine.io-client which depends on ws and it includes this code?? Maybe it is an engine.io-client issue then?
