### ISSUE TITLE
Backport security fix to 0.8 branch.

### ISSUE THREAD

**Issue by STRML** [websockets/ws#660]
I've backported in https://github.com/STRML/ws/tree/backport_secfix for users who need the security fix but aren't ready to deal with the browserify / webpack breakage ([1](https://github.com/websockets/ws/commit/e54d45fbab3b19c2940e9057ce1e7b8f105873e0#commitcomment-15214843), [2](https://github.com/socketio/engine.io-client/issues/450)) and bufferutil/utf-8-validate breakage.

@3rd-Eden , would you be willing to make a 0.8 branch so I can submit this as a PR and this can be tagged as `0.8.2`?

**Comment by STRML** [comment]
@3rd-Eden ping

**Comment by dceejay** [comment]
Seconded !

**Comment by lpinca** [comment]
Closing this as I think this is no longer needed, please comment if this is not the case.
