### ISSUE TITLE
The project description should be updated.

### ISSUE THREAD

**Issue by JacksonTian** [websockets/ws#665]
`ws`: The fastest RFC-6455 WebSocket implementation for Node.js. http://einaros.github.com/ws 

The link is 404 now, should change to http://websockets.github.io/ws/ .

**Comment by RIAEvangelist** [comment]
OR build the page from the settings panel.

:+1:

**Comment by alexhultman** [comment]
"The fastest" should be "A fast". It is *not* the fastest WebSocket library for Node.js.

**Comment by Eeems** [comment]
Which one is the fastest then?

**Comment by alexhultman** [comment]
I don't know. But it is not ws.

**Comment by LordMajestros** [comment]
@alexhultman which one is faster then?

**Comment by alexhultman** [comment]
There are many libraries written in other (native) languages that are faster, one such is libwebsockets, another is WebSocket++, etc. However, these are not available for Node.js so I am working on bringing libwebsockets to Node.js by wrapping it. node-lws is that project and it is certainly faster than ws.

**Comment by LordMajestros** [comment]
So it is still "the fastest RFC-6445 Websocket implementation for node.js" at least until you finish your wrapper. Any plans to support using node-lws with express or koa?

**Comment by alexhultman** [comment]
What do you mean by "finished"? It is software - it will never be "finished". You can run it today, you can benchmark it today. It will be stable in a couple of days.

Besides, I'm not claiming to be fastest - that is just silly since I cannot scout the entire internet to prove such a thing. The same applies to ws. A better description would therefore be one that does not use superlatives.

**Comment by 3rd-Eden** [comment]
@alexhultman You are what we call in the Netherlands a "mieren neuker". Who gives a rats ass if we used the word fastest. At that time that this library was created it was indeed the fastest.

**Comment by alexhultman** [comment]
*Used* I have nothing against - but keep on *using* is a completely different thing. If you market a T-Ford as the fastest car in 2016 then it is simply false marketing which spreads ignorance in users. But yeah - I have no authority to change anything here and I'm not going to harass you, even if you seem to handle competition with countering personal degrading descriptions.
