### ISSUE TITLE
Limit upload size...

### ISSUE THREAD

**Issue by jcalfee** [websockets/ws#670]
Is their anyway to prevent a connection from uploading so much data the server runs out of memory?

**Comment by LordMajestros** [comment]
You can try my PR https://github.com/LordMajestros/ws
There is supposed to be some way to this from nginx/haproxy i.e. your front end but I haven't found a way for nginx `proxy_buffers` seems to limit the connection to the backend not the connection from the client

**Comment by jcalfee** [comment]
Thank you!  That is quite a patch, recent too.  Any idea when this might be merged?  

Maybe I can wait a bit, we have not released anything yet.

We allow a number of IP requests per hour that would potentially lead to a large amount of legit traffic.  So your patch is ideal because we need to look in the message and weed out abnormal activity.

**Comment by LordMajestros** [comment]
Thank you, no idea on this but this works only with hybi sockets not hixie sockets. No idea when it will be merged.
Also there is supposed to be a better way to do this at the edge server i.e. nginx or haproxy as it would be more ideal there. I am still searching for the settings for nginx.

**Comment by LordMajestros** [comment]
@jcalfee It's been merged https://github.com/websockets/ws/pull/650#issuecomment-172607260
