### ISSUE TITLE
Multithreading with WebSockets

### ISSUE THREAD

**Issue by SzAmmi** [websockets/ws#674]
How to make multithreaded server? Like http://valler.ca/multithreaded-socketio-server/ . There are clusters (workers): https://nodejs.org/api/cluster.html But I have no idea how to make it. I wanna make multithreaded chat server...

**Comment by SzAmmi** [comment]
Done. Each worker communicates with another one.

**Comment by mato75** [comment]
How did you do it?

**Comment by slidenerd** [comment]
@ghost kindly share how you did it if you dont mind

**Comment by Shivaratn** [comment]
@ghost could you please share how you did it? It might be helpful for us.
