### ISSUE TITLE
How to listen to ping?

### ISSUE THREAD

**Issue by computersarecool** [websockets/ws#675]
How can I detect when a client receives a ping? I can log the pongs being sent back, but I want to do something on the browser upon receipt of a ping.

I have tried `ws.addEventListener('ping')` and also checked to see if the `message` event contained the ping data - neither of these worked.

Is there a way?

**Comment by ThomBogers** [comment]
Are you looking for this? https://github.com/websockets/ws/blob/master/doc/ws.md#event-ping

**Comment by computersarecool** [comment]
That is the event that I am looking for, however, I was wondering if it is possible to listen to this event on the Client Side (i.e. from a web browser).

**Comment by computersarecool** [comment]
I have read the documentation for the protocol and this does not seem to be possible because of limits of the spec, not the library.
