### ISSUE TITLE
Do I need to remove a closed ws object from the wss.clients array

### ISSUE THREAD

**Issue by computersarecool** [websockets/ws#676]
Do I need to add code such as the following to remove a socket connection when a close event is fired?
```javascript
 ws.on('close', function () {
      console.log('socket closed');
      var socketIndex = wss.clients.indexOf(ws);
      if (socketIndex > -1) {
        wss.clients.splice(socketIndex, 1)
      };
    });
```

**Comment by 3rd-Eden** [comment]
You do not. It's done for you. https://github.com/websockets/ws/blob/master/lib/WebSocketServer.js#L266-L270

**Comment by computersarecool** [comment]
I should have read that.  Thank you very much.
