### ISSUE TITLE
onclose not called if a client disconnects due to network failure

### ISSUE THREAD

**Issue by pavan4** [websockets/ws#686]
I am listening to the close event from a client on a node server using `websocket.on('close', function close() { } );` 

However, the callback is not being fired if a client gets disconnected due to network failure. 

Is there any way to detect dead connections on the server side ?

**Comment by pavan4** [comment]
https://github.com/FlorianBELLAZOUZ/ws/tree/KeepAlive This provides an implementation for the above issue

**Comment by urosjarc** [comment]
@pavan4 I have the same issue can you explain the strategy of your implementation, I ques you sending pings to the client and if no response you close them? :+1:

**Comment by pavan4** [comment]
@urosjarc  The implementation I mentioned above does this out of the box for you with pings but it doesnt work on ubuntu 14.0.4 and the timeout on tcp defaults to 30s always. Pings to the client result in error and are crashing the server, I am not able to rely on the pings.

**Comment by urosjarc** [comment]
Then what are your suggestions? I know only pings checking if connection is alive...

**Comment by pavan4** [comment]
I am planning to use https://github.com/theturtle32/WebSocket-Node This package has similar performance as ws and provides a onclose notification when the client disconnects

**Comment by urosjarc** [comment]
Did you check onclose method for network drop, does it really emit?

**Comment by r-pr** [comment]
I've got the same problem with detecting connections experiencing network errors. I've tried setting keepAlive, as pointed [here](https://github.com/websockets/ws/issues/353#issuecomment-76350912), but `close` event still fired only 10 s after network got down. Finally, I figured out how to use Websocket ping-pong mechanism: 
```
var WebSocketServer = require('ws').Server,
    wss = new WebSocketServer({ port: 4444 });

var PONG_TIMEOUT = 1500; //client has 1.5s to respond with pong

wss.on('connection', function connection(ws) {
    var lastPongReceived = Date.now();
    ws._socket.on('data', function(data) {
        if (data[0] == 0x8a) { //opcode of pong response
            lastPongReceived = Date.now();
        }
    });

    var x = setInterval(function() {
        if (Date.now() - lastPongReceived > PONG_TIMEOUT) {
            console.log('pong timeout elapsed');
            //...code to run if connection unavailable
            clearInterval(x);
            ws.close(); //this won't raise 'close' event, because close message 
                        //cannot be delivered to client      
        }
        if (ws.readyState === 1) {
            ws.ping('.', false);
        } 
    }, 1000);

    ws.on('close', function() {
        console.log('connection closed');
    })
});
```

**Comment by john-doherty** [comment]
@r-pr how has the above ping/pong code worked out for you? Have you used it in production and if so how many connections? Thanks!

**Comment by urosjarc** [comment]
This is my implementation:
https://github.com/urosjarc/websocketRest.js/blob/master/bin/WebsocketRest.js

**Comment by urosjarc** [comment]
It's used in production for 1 year +2000 mobile devices connected which are switching connections (wifi, 3G) all the time. We were having many problems with duplicats but now this lib is running 1 year without error.

**Comment by urosjarc** [comment]
I will add additional docs if there will be an interest in this lib.

**Comment by r-pr** [comment]
@john-doherty It seems that the mechanism does the job, but I haven't used it in production.

**Comment by john-doherty** [comment]
@r-pr I'm going to use a slightly modified version of your concept. I'll let you know how it goes.

**Comment by r-pr** [comment]
@john-doherty OK

**Comment by zs9024** [comment]
has the issue been solved in the latest version?

**Comment by lpinca** [comment]
A possible way to handle this issue is illustrated here: https://github.com/websockets/ws#how-to-detect-and-close-broken-connections.
Closing, feel free to continue discussing on the closed thread.
