### ISSUE TITLE
Hixie-76 doesn't work behind a proxy (e.g. HAProxy)

### ISSUE THREAD

**Issue by agilethomas** [websockets/ws#687]
This issue has been reported and fixed on other web socket implementations, but not this one.

When the socket server is behind a proxy (in my case HAProxy), the server waits for the nonce before replying with the response header, but HAProxy won't send the extra data until the server responds.

Same issue reported on other libraries:

https://github.com/ninenines/cowboy/issues/73

https://github.com/faye/faye-websocket-node/issues/4

**Comment by lpinca** [comment]
Closing as Hixie-76 is no longer supported.
