### ISSUE TITLE
 add different event listeners than ws.on('message',....); on client and server side

### ISSUE THREAD

**Issue by Xsmael** [websockets/ws#693]
Hello, i was wondering if it's possible to add some extra event listeners apart the default "on message"
like socket.io does; so that I can use different event listeners for different type of messages.

I mean this: 

```
// Server side
ws.on('auth', function(data) {
  // processing...
});

ws.on('message', function(data) {
  // processing...
});

ws.on('query', function(data) {
  // processing...
});
```

```
// Client side
ws.send('auth', obj);

ws.send('message', data);

ws.send('query',data);
```

Is that possible, ? with ws ? I know its possible using socket.io, but ws is more suitable for my current project. Thanks!

**Comment by ericmdantas** [comment]
I'd say that's out of this project scope and you'd have to write the wrapper yourself - which should not be complicated.

**Comment by lpinca** [comment]
I agree with @ericmdantas.
