### ISSUE TITLE
Option to start listening on my own terms

### ISSUE THREAD

**Issue by muxahuk** [websockets/ws#696]
Hey, I would like to know don't u want to make option witch will determin to start listening server or not..:

WebSocketServer.js : 59 line

```
this._server.listen(options.value.port, options.value.host, callback);
```

I would want to be able to start listening on my own terms like after 10 sek server is started ( timeout ) or whatever terms i want...

but writing my own http.createServer is'n a solution as u already have that.. I think something like:

```
self.once( 'listen', () => this._server.listen(options.value.port, options.value.host, callback) );
```

would be enought

and u could do something like:

```
self.once( 'listen', () => this._server.listen(options.value.port, options.value.host, callback) );
if( option.listen ) self.emit( 'listen' );
```

**Comment by JoshuaWise** [comment]
A server isn't really a server until it's listening for connections. Just don't create the WebSocketServer object until you plan on listening. Alternatively, you can pass your own http.Server object like so:
```js
var server = http.createServer();
var wss = new WebSocketServer({server: server});
server.listen(80);
```

**Comment by muxahuk** [comment]
Well, i could create my own server, but if i pass server and port within parametrs it will still create server and would not use mine + every time, when i want custom listening, i am required to write these:
```javascript
var server = http.createServer(function (req, res) {
    var body = http.STATUS_CODES[426];
    res.writeHead(426, {
        'Content-Length': body.length,
        'Content-Type': 'text/plain'
    });
    res.end(body);
});
server.allowHalfOpen = false;
```
and pass `server` variable and then write .listen atc..
My solution at 1-st comment woun't break beckwords compatibility and will add these feature of listening on my terms, not after crated websocketserver...
Please consider these request and answer why not if u decide not to use it.
Thanks.

**Comment by JoshuaWise** [comment]
> but if i pass server and port within parametrs it will still create server and would not use mine

To make it use your server and not create a new one, you must **not** pass a `port` option. Does this help?

**Comment by muxahuk** [comment]
No.. Problem remains.. the problem isn't that i can't pass port.. problem is that if i pass - i can't control when to listen.

**Comment by JoshuaWise** [comment]
I'm not sure I understand the problem. Why do you have to pass the port number? If you don't pass the port number, it won't start listening on your server automatically.

**Comment by muxahuk** [comment]
well, i don't want to create ( wrote in my 2-nd reply ) code all the time in every project. Especially if you already do that ( u have server creation already, why should i dublicate your code? ).
I'm passing only port number, but i want to start listening for the server, for example, after i have connected to database. in regular usecases that cannot be acheaved. Imagine these:
```javascript
const server = new WebSocketServer( { port: 1233 }, () => { console.log( 'listening' ) } );
// currently here will be logged 'listening'
// with my preposal from 1-st comment
const db = new DB( options );
db.on( 'ready', () => server.emit( 'listen' ) ); // only on emit( 'listen' ) will be logged 'listening'
```

**Comment by JoshuaWise** [comment]
Ahhh, I finally understand your concern. In order to prevent breaking compatibility, we'd have to add an option like `dontListenAutomatically`, which would add extra complexity to the already-complex options we have. How about you do something like this:
```js
var wss;
database.connect(function () {
  wss = new WebSocketServer({port: 80});
  wss.on('listening', everythingIsReady);
});
function everythingIsReady() {
 // blah blah blah
}
```

**Comment by muxahuk** [comment]
I already do not remember why ( it's a long time from march now ), but in my case i couldn't do that, but i definetly tryed and failed ( sticked with creating server and not passing port ).
I think it was becouse i'v needed to pass wss to db in orther to db do something with it ( listen for 'listening' and start making queries i guess ).. shortly - becouse of injections, i think..

**Comment by JoshuaWise** [comment]
It seems like your situation was fairly unique, so I'd prefer not to increase the complexity of something that is meant to be a "time saver" (the `port` option). I almost always create my own servers anyways, because it provides me with more flexibility. The `port` option is really just for the simple cases. Is it alright if I close this?

**Comment by muxahuk** [comment]
well, then maybe u could make ne function like WebSocketServer.createServer() with will include 
```javascript
WebSocketServer.createServer = function() {
var server = http.createServer(function (req, res) {
    var body = http.STATUS_CODES[426];
    res.writeHead(426, {
        'Content-Length': body.length,
        'Content-Type': 'text/plain'
    });
    res.end(body);
});
server.allowHalfOpen = false;
return server;
}
```
in order for us not to dublicate these code ? ( u could replace creation with these function also ).
If no, then u can close these issue.

**Comment by JoshuaWise** [comment]
I'm not opposed to something like this. The code is already there, so why not expose it?  I'll write something up later tonight.

**Comment by lpinca** [comment]
@muxahuk are you still interested in adding that static method?

**Comment by muxahuk** [comment]
@lpinca well, i think it would save much time, whenever i need to control the server.. but currently i'm in no need of this feature for my projects..

**Comment by lpinca** [comment]
Ok, I close this. Feel free to send a PR if/when you want.
