### ISSUE TITLE
Status 200 on iOS and exspress server

### ISSUE THREAD

**Issue by dorshay6** [websockets/ws#699]
I get
`WebSocket connection to 'ws://*.azurewebsites.net' failed: Unexpected response code: 200`
when working on WS along with express .

any help?

**Comment by lpinca** [comment]
Did you enable WebSocket on Azure Web Sites?

**Comment by dorshay6** [comment]
Solved Thanks

**Comment by lpinca** [comment]
Thanks for the prompt reply, closing.
