### ISSUE TITLE
broadcast() example in README has a bug

### ISSUE THREAD

**Issue by Jared-Sprague** [websockets/ws#700]
I got an error copying the example from the README file for broadcasting to multiple clients:

```
wss.broadcast = function broadcast(data) {
  wss.clients.forEach(function each(client) {
    client.send(data);
  });
};
```

Because one of the clients wasn't open yet.  This really should be wrapped in a readyState check like this:

```
wss.broadcast = function broadcast(data) {
  wss.clients.forEach(function each(client) {
    if (client.readyState === WebSocket.OPEN)
      client.send(data);
  });
};
```

**Comment by lpinca** [comment]
Fixed in 7bec220f9e3650afc5d92c17fb04a949dce0e7fd.
Thanks.
