### ISSUE TITLE
when client (iphone 6p) change fly mode ,there is no disconnect event 

### ISSUE THREAD

**Issue by xhacker5000** [websockets/ws#702]
when client (iphone 6p) change fly mode ,there is no disconnect event
How to catch the client disconnect event when I change the fly mode, the close event not be called.

any solutions ?

**Comment by lotas** [comment]
I think this is the same as #686

**Comment by lpinca** [comment]
There are cases where the only way to detect that a connection has been closed is via a heartbeat system which can be implemented, for example, by sending [pings](https://tools.ietf.org/html/rfc6455#section-5.5.2).
