### ISSUE TITLE
What causes `Error: This socket has been ended by the other party`?

### ISSUE THREAD

**Issue by binarykitchen** [websockets/ws#704]
I'd like to know what can trigger the error below? It rarely happens for my app and is very difficult to debug/fix. Thanks!

```
Error
Error: This socket has been ended by the other party

Error properties (debug)
code: EPIPE

Stack
Error: This socket has been ended by the other party
at TLSSocket.writeAfterFIN [as write] (net.js:274:12)
at Sender.frameAndSend (/var/www/videomail/production/source/node_modules/ws/lib/Sender.js:232:22)
at /var/www/videomail/production/source/node_modules/ws/lib/Sender.js:126:12
at /var/www/videomail/production/source/node_modules/ws/lib/PerMessageDeflate.js:301:5
at afterWrite (_stream_writable.js:355:3)
at onwrite (_stream_writable.js:346:7)
at WritableState.onwrite (_stream_writable.js:89:5)
at afterTransform (_stream_transform.js:79:3)
at TransformState.afterTransform (_stream_transform.js:54:12)
at Zlib.callback (zlib.js:613:5)
```

**Comment by ckross01** [comment]
Typically this is sent when another application (client, browser, etc.) closes the socket when you are still sending data to it from the server. 

I've had it happen when my browser drops the connection to the server on the socket while I am writing data to it.

**Comment by binarykitchen** [comment]
got it, thanks

**Comment by njam** [comment]
What is the recommended way to handle/catch such an error?
cc @vogdb

**Comment by ckross01** [comment]
The readme section on handling errors is pretty solid for when sends throw exceptions.

https://github.com/websockets/ws#error-handling-best-practices

**Comment by njam** [comment]
Sorry, my bad, thanks for the link!

**Comment by palashjain** [comment]
@binarykitchen can you please help me for the same? I am getting same error when executing scripts on multiple physical devices connected to one USB hub.

Full details [here](https://stackoverflow.com/questions/56625053/appium-getting-error-this-socket-has-been-ended-by-the-other-party-while-doi).
