### ISSUE TITLE
Error while using an Agar.io client for spawning bots using Proxies

### ISSUE THREAD

**Issue by LPArigma** [websockets/ws#708]
The more proxies i have the more it happens.... and i just dont understand... Please help.
Error A
`[TypeError: Cannot assign to read only property 'type' of reserved fields must be empty]`

Error B
`[TypeError: Cannot assign to read only property 'type' of continuation frame cannot follow current opcode]`

This just randomly started happening yesterday and the more proxies i have the more it hapens and the longer it lasts before continuing. Please give feedback! Thanks!

**Comment by pulviscriptor** [comment]
Fixed in https://github.com/websockets/ws/pull/681
