### ISSUE TITLE
Where has browser.js gone?

### ISSUE THREAD

**Issue by sebpiq** [websockets/ws#714]
This was quite handy : https://github.com/websockets/ws/blob/7812a55c64603d882892cf628aac16c9fc07802b/lib/browser.js

Now I have to write the shim myself :/

**Comment by fisch0920** [comment]
Also wondering the exact same thing; shouldn't `ws` package work by default in the browser when included via browserify or webpack?  This shim and accompanying "browser" link in package.json made that the default.

**Comment by JacksonTian** [comment]
It was simple wrapper that really doesn't belong in a full ledged node.js library. If you want browser support you could just conditionally import it the WebSocket server. var WS = window.WebSocket || require('ws')

**Comment by JacksonTian** [comment]
Closed it. Any question, feel free to reopen it.

**Comment by fisch0920** [comment]
Thanks!
