### ISSUE TITLE
hixie 76 is broken in node 6

### ISSUE THREAD

**Issue by ArtemGovorov** [websockets/ws#716]
There's [this breaking change in node 6](https://github.com/nodejs/node/pull/5522), so it's required to pass the `binary` encoding as a second argument to all `hash.update` calls at:
- https://github.com/websockets/ws/blob/master/lib/WebSocketServer.js#L421, 
- https://github.com/websockets/ws/blob/master/lib/WebSocketServer.js#L427,
- and also ideally at https://github.com/websockets/ws/blob/master/lib/WebSocketServer.js#L221

**Comment by lpinca** [comment]
Closing as Hixie-76 is no longer supported.
