### ISSUE TITLE
Packet error while using it for Agar.io client with proxies

### ISSUE THREAD

**Issue by LPArigma** [websockets/ws#722]
I get this error in the console:
`Packet error detected for packet: 10 e7 1b 00 00 59 21 00 00 00 00 00 00`
then it says this:
`Crash will be prevented, bot will be disconnected`

Please help me solve this issue for its effecting the clients performance, Thanks!

**Comment by Sonicmaster13** [comment]
This is not the place for Agar.io related problems. That error looks extremely like it was from using Agario-Client. I suggest you close this issue and post it on that instead

**Comment by 3rd-Eden** [comment]
I agree with @Sonicmaster13
