### ISSUE TITLE
Implement onopen, onclose, onerror, onmessage as addEventListener is not part of the standard

### ISSUE THREAD

**Issue by tothandras** [websockets/ws#723]
We had a weird [issue](https://github.com/maxogden/websocket-stream/issues/87) with [websocket-stream](https://github.com/maxogden/websocket-stream) which has `ws` as it dependency. From one time to another `WebSocket.prototype.addEventListener` disappeared from Chrome, completely (it wasn't accidentally overwritten).
The following functions are part of the [standard](https://developer.mozilla.org/en-US/docs/Web/API/WebSocket), but they don't seem to be part of the `ws` implementation:
- `onopen`
- `onclose`
- `onerror`
- `onmessage`

Although the `addEventListener()` is not part of it, I assume it can disappear anytime again. We would like to use the same WebSocket API both on server and client side.

**Comment by 3rd-Eden** [comment]
https://github.com/websockets/ws/blob/master/lib/WebSocket.js#L402-L484

It's been in this module for ages already.

**Comment by tothandras** [comment]
@3rd-Eden Oh, sorry! :) I haven't noticed.
