### ISSUE TITLE
clientTracking

### ISSUE THREAD

**Issue by sethdorris** [websockets/ws#724]
Where can I go to find out what clientTracking: true, enables and  how to use that feature?

And how do I grab the session ID on connection?

**Comment by nkolban** [comment]
+1 please

**Comment by fictorial** [comment]
https://github.com/websockets/ws/search?utf8=%E2%9C%93&q=clientTracking

**Comment by JoshuaWise** [comment]
`clientTracking: true` enables you to use the `WebSocketServer#clients` property, which is an array of all currently connected clients. The property does not return a safe copy—the array's contents will constantly change as users connect and disconnect.
