### ISSUE TITLE
Stream and send at the same time

### ISSUE THREAD

**Issue by psinghsp** [websockets/ws#726]
Hi

I did not see in the docs - but can you call:
Websocket.send()
and
Websocket.stream()

on the same socket object at the same time?

Does the stream have the same "binary" and "compress" options?

**Comment by psinghsp** [comment]
Actually, even just the stream does not have an example. Does the support exist? I see Websocket.prototype.stream() - but I do not see an example for it.

**Comment by zhirzh** [comment]
:+1: I would also *love* to have an example on `Websocket#stream`.

**Comment by syzer** [comment]
👍

**Comment by kichooo** [comment]
:+1:

**Comment by lpinca** [comment]
Closing this as the `stream` method has been removed. Take a look at https://github.com/maxogden/websocket-stream for stream support.

**Comment by psinghsp** [comment]
The package mentioned in the last comment does not support Websocket streaming and sending discrete messages separately at the same time. The websocket protocol allows implementations to do both.

**Comment by lpinca** [comment]
@psinghsp yes but you have to queue the "discrete" messages if you are streaming another message.

You can't mix frames of different message, only control frames can be added in the middle of a fragmented message.
