### ISSUE TITLE
websocket configuration issue

### ISSUE THREAD

**Issue by pokal4u** [websockets/ws#727]
HI,

I try to create a application using paho mqtt with websocket.

I followed this link https://www.nginx.com/blog/websocket-nginx/ to configured my nginx config file.
I am getting error

mqttws31.js:36 WebSocket connection to 'ws://domain.com:8020/websocket' failed: Error during WebSocket handshake: Unexpected response code: 502

My config file:

http {
    map $http_upgrade $connection_upgrade {
        default upgrade;
        '' close;
    }

    upstream websocket {
        server domain.com:8010;
    }

    server {
        listen 8020;
        location / {
            proxy_pass http://websocket;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $connection_upgrade;
        }
    }
	server {
        listen       80;
        server_name  domain.com ;
		server_tokens off; 

		location /websocket {
            proxy_pass http://websocket;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $connection_upgrade;
        }
    }
}

code:

var client = new Paho.MQTT.Client("ws://domain.com:8020/websocket", "myClientId" + new Date().getTime());

I tried different wyas like:

ws://domain.com/websocket
ws://domain.com:8010/websocket
ws://localhost:8020/websocket
ws://localhost/websocket

PLease help me

Thanks

**Comment by pokal4u** [comment]
Now connected like:

var client = new Paho.MQTT.Client("ws://domain.com:8010/websocket", "myClientId" + new Date().getTime());


getting response :+1: 
![mqtt](https://cloud.githubusercontent.com/assets/498771/15204904/89b395f2-1830-11e6-8ece-6a21cfe18fe1.png)
![mqtt1](https://cloud.githubusercontent.com/assets/498771/15204905/89b8015a-1830-11e6-9b2d-74461c4ed2bc.png)

**Comment by LongLiveCHIEF** [comment]
@pokal4u can you close this issue please?
