### ISSUE TITLE
Can't connect to the server through JS?

### ISSUE THREAD

**Issue by prog112** [websockets/ws#730]
Hey, weird problem. I created the server in node and can connect fine through another node client, but in my web app the JS script can't seem to connect at all (as if the server was offline). I'm not even doing anything fancy:

var websocket = new WebSocket("ws://localhost:9007");

Why can I connect through node np and it doesn't work on browser?

**Comment by LordMajestros** [comment]
What browser and version? Have you tried another browser? How do you know it doesn't connect?

**Comment by prog112** [comment]
I tried Chrome and Safari newest versions, it doesn't because neither my server logs the connector and the clients return errors WebSocket connection to 'ws://127.0.0.1:9007/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED

**Comment by LordMajestros** [comment]
Let's get the basics out of the way, your node.js server is bound to localhost on port 9007
You are running the client and server on the same computer?

**Comment by prog112** [comment]
var WebSocketServer = require('ws').Server;
var wss = new WebSocketServer({ port: 9009 }); unless there are any more settings to set on the launchup then yeah

And yes same machine

**Comment by LordMajestros** [comment]
9009 or 9007?

**Comment by prog112** [comment]
I edited the message, I copy pasted the code from older version. The port is 9007 and everyone set up properly.

**Comment by LordMajestros** [comment]
It might be a CORS issue on the browser. You may have to share some code.

**Comment by prog112** [comment]
Sure, but there really isn't much - I tried to cut it down to the simplest form

$(document).ready(function () {

    var websocket = new WebSocket("ws://127.0.0.1:9007/");

    websocket.onopen = function (event) {
        websocket.send(JSON.stringify({
            request: 'getBuckets'
        }));
        websocket.onmessage = function (str) {
            var response = JSON.parse(str.data);
            $('#test').html(response.buckets);
            websocket.close();
        };
    };

});

However as I said, there is already problem during the connection so the rest doesn't really matter now.

**Comment by prog112** [comment]
Pf, neeeeveer mind, I might be retarded. JS is obviously executed on the client side unlike PHP so I had to replace that localhost with an external address lol.

**Comment by LordMajestros** [comment]
Actually I run ws on localhost all the time. The js however usually has to come from the same address it's trying to connect to. Glad you found a solution though.
