### ISSUE TITLE
Process never terminates.

### ISSUE THREAD

**Issue by adjohnson916** [websockets/ws#732]
The process never terminates despite calling `close`, whose callback executes but there appear to be active handles still listening.

``` js
var WebSocketServer = require('ws').Server
  , wss = new WebSocketServer({ port: 8080 });

wss.close(function () {
  console.log('closed');
  require('active-handles').print();
});
```

Originally discovered in urish/firebase-server#52.

**Comment by wmsmacdonald** [comment]
Your issue is that `new ws.Server([options], [callback])` is asynchronous. Put `.close()` in the callback and it should close properly.

```javascript
var WebSocketServer = require('ws').Server;
var wss = new WebSocketServer({ port: 8080 }, function() {
  wss.close(function () {
    console.log('closed');
  });
});
```

**Comment by adjohnson916** [comment]
@wmsmacdonald Ah, thanks, I didn't realize that as I've seen libraries appear to use it synchronously. Would we like to introduce behavior to queue such methods so that they can be called synchronously and are executed later on the next appropriate lifecycle hook?

**Comment by lpinca** [comment]
Closing this as @wmsmacdonald explanation is correct, thanks.
