### ISSUE TITLE
Origin header in outcoming server-side connections

### ISSUE THREAD

**Issue by koutsenko** [websockets/ws#736]
Hello.

I want create ticket-based authorization, so as  the part of process I need communication between web-service and server. User browser performs an request to web-service, service checks his cookies and creates temp ticket, one copy for user and second copy for server. So the server can compare two copies and then accept or reject user connection.

I completely stuck at the moment of sending ticket from service to server using WebSocket connection.
I wanna check service origin or referer and prevent server to get fake ticket from fake service.

But no origin or referer headers are present on ws.upgrageReq.headers object.
So then I decided to send it manually according your docs:

```
  var socket = new ws(address, {
    headers: {
      'Origin': 'http://my-pretty-website'
    }
  });
```

It works but I understand that it's also can be faked in the same manner that I did here.
Is the HTTPS (WSS) and certificates are only way to solve that problem, or there is some another way?

Or I must do things simple - because it's almost impossible to sniff traff between web-service and web-server, so all I need is send some secret key in the headers or in the request body?

**Comment by lpinca** [comment]
> Or I must do things simple - because it's almost impossible to sniff traff between web-service and web-server, so all I need is send some secret key in the headers or in the request body?

I think this is the easiest way. You can also use a query string with a secret:

```js
const ws = new WebSocket('ws://myserver.com/?secret=foo');
```

you can then verify the secret with something like this:

```js
url.parse(ws.upgradeReq.url, true).query.secret === SERVICE_SECRET
```

**Comment by lpinca** [comment]
Closing this, please post back if needed.
