### ISSUE TITLE
ws.Server not opening

### ISSUE THREAD

**Issue by RowanHarley** [websockets/ws#750]
Whenever I try to create a WebSocket Server, the websocket doesn't seem to open. Here's my code:

    var WebSocketServer = require('ws').Server;

    var server = new WebSocketServer({port: config["port"], path: "/slither"});

    server.on("open", function(){
	    console.log("[SERVER] Server Started at 127.0.0.1:" + config["port"] + "! Waiting for Connections...");
    });

Any idea why the server doesn't seem to start?

**Comment by ericmdantas** [comment]
Try `.on('connection', () =>...)`.

**Comment by RowanHarley** [comment]
@ericmdantas I have that but I want `server.on("open", function(){ });` to check if the server started because I've been getting some errors recently about the websocket server not being open

**Comment by JoshuaWise** [comment]
You're looking for `server.on('listening', () =>...)`

**Comment by ericmdantas** [comment]
Also, if you want to check if the client is open you can do:

```js
if (client.readyState === client.OPEN) {
  // now you can use the client
}
```
