### ISSUE TITLE
Change project description "fastest" -> "fast".

### ISSUE THREAD

**Issue by alexhultman** [websockets/ws#757]
I see you went ahead and closed the other issue that other people reported. Of course you closed it without actually making any changes, not really solving anything but rather just denying the situation.

So the deal is, you cannot have a project description that is completely ignoring the very existence of other projects already proved to be a lot faster. The only act needed to correct this is to acknowledge the situation and change the project description.

So the deal is not to "bash" someone. It is just simple, humble sportsmanship to accept the situation and not completely ignore it like you have done now for months. By having a description "fastest" you are basically slapping any other faster projects in the face. I'm not interested in collaboration at all, I'm not interested in any kind of mud slinging. I just want this project to acknowledge the very situation and stop spreading misinformation.

Good sportsmanship involves accepting newcomers and acknowledging their effort.

**Comment by PokemonAshLovesMyTurkeyAndILikeYouTwo** [comment]
+1.

@3rd-Eden  You are correct about the `perMessageDeflate` issue and I apologize for my tone on my last issue.

The problem is about this benchmark:
https://github.com/alexhultman/uWebSockets/issues/152#issue-160389186

The performance difference between `ws` and `uws` is drastic. Even if you disable the `perMessageDeflate` setting, `uws` is still around **7-8**x faster than `ws`. And, the `perMessageDeflate` setting is enabled by default.

After looking at the benchmarks [here](https://github.com/alexhultman/uWebSockets/issues/152#issue-160389186), and when `perMessageDeflate` is enabled... the performance difference is around **16x**...

And, the description of this module is ``ws`: The fastest RFC-6455 WebSocket implementation for Node.js.`. That's just not simply true anymore. @3rd-Eden  It's time to let it go.

**Comment by alexhultman** [comment]
@PokemonAshLovesMyTurkeyAndILikeYouTwo You cannot compare one server with permessage-deflate and one without, so the only valid number from your benchmark is the 7x (which is a massive number, we are talking about 700% difference, not 0.1% or something like that).

**Comment by PokemonAshLovesMyTurkeyAndILikeYouTwo** [comment]
Oops yeah you're right. I was just assuming since perMessageDeflate is enabled by default (and no documentation about it) -- most people probably wouldn't of known when doing their own benchmarks.

But yeah, it's technically not fair. I'll edit my post ty

**Comment by alexhultman** [comment]
It is documented here: https://github.com/websockets/ws/blob/master/doc/ws.md#optionspermessagedeflate :wink:

**Comment by alexhultman** [comment]
@3rd-Eden Let me guess, Arnout, you are going to ignore this issue for a month then freeze-close it after posting some high-horse noble quote about being civil. The problem with this is, the only one not really being civil is you. You treat other people with neglect, not even bothering to acknowledge their presence or effort. You claim to invite people to civil discussions, but you always do this right before freeze-closing the discussion effectively making it impossible to even respond.

I think I've been pretty much civil he whole time, straight from the first post (#665) I made about 4 months ago, which you freeze-closed after posting "**You are what we call in the Netherlands a "mieren neuker". Who gives a rats ass if we used the word fastest. At that time that this library was created it was indeed the fastest.**" - intentionally misunderstanding the problem as being about the past. The problem is that your marketing is hurting my marketing since people stumble upon two completely colliding claims. I still get people asking me to prove myself because of how ws is marketing itself. Nobody is asking ws to prove itself because ws has already been established as "fastest" even though this is completely false.

As we have seen in #665, you have already updated the description before and that went without the world ending so I do not think the world will end from you changing it from fastest to fast (or any other description you want that is actually based on truth).

Again, it's up to you. You can either freeze-censor-block this thread or just make up for past neglect.

**Comment by lpinca** [comment]
I agree that the description should be updated but this is kinda funny.

> I think I've been pretty much civil he whole time

This is an excerpt from a deleted comment:

![screen shot 2016-06-17 at 11 50 28](https://cloud.githubusercontent.com/assets/1443911/16147220/1e2cd4a6-3482-11e6-965c-d6eecc4aa3b8.png)

I've read quite a few of these :)

**Comment by alexhultman** [comment]
So can we please update the description or what is holding up?

**Comment by 3rd-Eden** [comment]
I've updated the description.

![](https://wellspentjourney.files.wordpress.com/2013/02/boromir-argument-internet.jpg)

**Comment by alexhultman** [comment]
Thanks.

**Comment by alexhultman** [comment]
@3rd-Eden uws is cross-platform now, so I guess you need to add a few more qualifiers to your description in order to keep this charade going...

**Comment by alexhultman** [comment]
@3rd-Eden You will need to perform some serious mind gymnastics to come up with a valid description. I have thought about it and I have a hard time imagining any qualifier that excludes uws:

* Both ws and uws implement RFC-6455
* Both ws and uws are available for Node.js
* Both ws and uws are cross-platform
* Both ws and uws are written partly in JavaScript and partly in C++

The last bullet point is the weak link, that point can probably be tweaked a little bit as ws itself is 100% JavaScript, while it makes use of separate (optional) C++ modules. However, if not counting the C++ modules, the performance of ws gets dramatically worse and I'm not even sure if ws outperforms the other JavaScript-only WebSocket implementations then.

**Comment by manast** [comment]
It still says fastest actually. 
![image](https://cloud.githubusercontent.com/assets/95200/24082265/ef1b25d6-0cc2-11e7-96b5-f9bf9efdd31f.png)

**Comment by alexhultman** [comment]
@manast I've learnt over the last year that this is not really an issue with websockets/ws specifically but rather an issue with the general JavaScript community, where it is common for a project to claim performance without anything to back this up. This is the norm of marketing in the JavaScript world.

I call this the rule of inverted marketing. You basically take a JavaScript project, invert its marketing claims and this is what you get in reality.

This also holds up for Socket.IO which claims to be the fastest real-time engine in the universe, all categories. Apply the rule of inverted JavaScript marketing and you get the reality: Socket.IO is more likely to be the world's most bloated and slow real-time engine in the universe.

Always remembr the rule of inverted JavaScript marketing, it is very useful. It holds true for Express.js and Node.js itself also and most of what is highly starred in the NPM registry.

Anyways, this is not an issue (for me) anymore as I opened this issue up when my own project had some rough times getting accepted but this is all solved now so I don't personally care if they so want to play pretend and claim to be this or that.

**Comment by lpinca** [comment]
Does `uws` work on all Node.js supported platfroms? Specifically

|  System      | Support type | Version                          | Architectures        | Notes            |
|--------------|--------------|----------------------------------|----------------------|------------------|
| GNU/Linux    | Tier 1       | kernel >= 2.6.18, glibc >= 2.5   | x86, x64, arm, arm64 |                  | 
| macOS        | Tier 1       | >= 10.10                         | x64                  |                  |
| Windows      | Tier 1       | >= Windows 7 or >= Windows2008R2 | x86, x64             |                  |
| SmartOS      | Tier 2       | >= 15 < 16.4                     | x86, x64             | see note1        |
| FreeBSD      | Tier 2       | >= 10                            | x64                  |                  |
| GNU/Linux    | Tier 2       | kernel >= 4.2.0, glibc >= 2.19   | ppc64be              |                  |
| GNU/Linux    | Tier 2       | kernel >= 3.13.0, glibc >= 2.19  | ppc64le              |                  |
| AIX          | Tier 2       | >= 6.1 TL09                      | ppc64be              |                  |
| GNU/Linux    | Tier 2       | kernel >= 3.10, glibc >= 2.17    | s390x                |                  |
| macOS        | Experimental | >= 10.8 < 10.10                  | x64                  | no test coverage |
| Linux (musl) | Experimental | musl >= 1.0                      | x64                  |

If not I think the description (fastest crossplatform for Node.js) is still valid as I don't know any other WebSocket implementation for Node.js that have better performance than ws.

I can't really understand what's the point in comparing Socket.IO with a pure WebSocket server but that's another story.

**Comment by alexhultman** [comment]
Well I don't care to argue like I mentioned. But yes, it does run on all those platforms (they are all Unix-like with the exception for Windows). Anyways, I want very little to do with this discussion, I genuinely do not care what websockets/ws claims - it doesn't affect me in any way.

**Comment by lpinca** [comment]
So now it also properly supports SSL on Windows for Node 4,x? Nice.
Anyway I've just updated the description to reflect the one in the npm package so hopefully this will come to an end.

**Comment by alexhultman** [comment]
ws doesn't run on AmigaOS so it is not cross-platform either (see the infinite logical error here?). You can just add "oh, but it doesn't run on Nintendo GameBoy 1 from the early 80s, so it is not *truly* cross-platform". Pathetic tinkering with the context just to hold on to that "fastest" keyword.

**Comment by lpinca** [comment]
> ws doesn't run on AmigaOS so it is not cross-platform either (see the infinite logical error here?)

Hmm no sorry I can't see it. ws runs where Node.js runs (all versions, platforms and features). Anyway we have different opinions so there is no point in keeping this going especially now that the description has been updated.

Good night.

**Comment by alexhultman** [comment]
Well there is no superlative anymore but the rule of inverted JavaScript marketing still applies.

**Comment by alexhultman** [comment]
Ah so "cross-platform" is defined as "across platforms that Node.js supports". Right, Node.js defines what "cross-platform" means. If you cannot run Node.js on a microwave then it is not really cross-platform.
