### ISSUE TITLE
No close event when VPN is broken

### ISSUE THREAD

**Issue by jiyinyiyong** [websockets/ws#759]
I ran into such situation several times. This time I was turning of a PPTP connection and no `close` event is fired. Not sure if it's a bug but is there a solution for such case?

**Comment by lpinca** [comment]
There are cases where the only way to detect that a connection has been closed is via a heartbeat system which can be implemented, for example, by sending [pings](https://tools.ietf.org/html/rfc6455#section-5.5.2).
