### ISSUE TITLE
How can I use WebSocket server to listen unix socket?

### ISSUE THREAD

**Issue by vladimirsazhin** [websockets/ws#762]
I want to use it with nginx.

**Comment by lpinca** [comment]
Look here http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_pass at the UNIX-domain socket example. The rest of the configuration should be the same.

```
location / {
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header Host $host;
    proxy_set_header X-NginX-Proxy true;

    proxy_pass http://unix:/tmp/backend.socket;
    proxy_redirect off;

    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
}
```

**Comment by lpinca** [comment]
Closing this, please comment if needed.

**Comment by lpinca** [comment]
I think you question was actually how to make the server listen on a UNIX socket.
In that case you can follow the Node.js [documentation](https://nodejs.org/api/http.html#http_server_listen_path_callback) and then pass the server to the `WebSocket.Server` constructor.

Hope this helps.
