### ISSUE TITLE
error installing with npm

### ISSUE THREAD

**Issue by mehmetkose** [websockets/ws#763]
ubuntu 14.04

![ws-error-1](https://cloud.githubusercontent.com/assets/706678/16356929/b67904f4-3af0-11e6-8089-9ca1cff9fbb3.png)

![ws-error-2](https://cloud.githubusercontent.com/assets/706678/16356930/bda0c2ee-3af0-11e6-9ad7-b8505f1ae344.png)

![ws-error-3](https://cloud.githubusercontent.com/assets/706678/16356932/c1e0131e-3af0-11e6-875a-2dc355656f99.png)

![ws-error-4](https://cloud.githubusercontent.com/assets/706678/16356935/c64fb1d4-3af0-11e6-8fc5-f592f1e30150.png)

**Comment by 3rd-Eden** [comment]
Your installing an out of date version, update to latest.
