### ISSUE TITLE
add the custom options

### ISSUE THREAD

**Issue by hd19861028** [websockets/ws#764]
when i connect the web socket, i wish that i can add the custom options(e.g. the request headers).
as bellow: 

```
var ws = require('ws');
var option = {
	headers: {
		"WS-Auth-DeviceGuid": "xxxxxxxx",
		"WS-Auth-Timestamp": "xxxxxxxx",
		"WS-Auth-Signature": "xxxxxxxxx"
	}
};
ws.connect('http://api.xxxxxx.cn/websocket/device', option);
```

**Comment by hd19861028** [comment]
`
var option = {
	headers: {
		"WS-Auth-DeviceGuid": "xxxxxxxx",
		"WS-Auth-Timestamp": "xxxxxxxx",
		"WS-Auth-Signature": "xxxxxxxxx"
	}
};
ws.connect(cfg.wsurl + '/device', option);
`

**Comment by JoshuaWise** [comment]
This is already supported. It's just not supported by the shorthand `.connect` method. Use this instead:
```
var ws = require('ws');
var option = {
    headers: {
        "WS-Auth-DeviceGuid": "xxxxxxxx",
        "WS-Auth-Timestamp": "xxxxxxxx",
        "WS-Auth-Signature": "xxxxxxxxx"
    }
};
var client = new ws('http://api.xxxxxx.cn/websocket/device', option);
client.on('open', callback);
```

**Comment by hd19861028** [comment]
thanks
