### ISSUE TITLE
How to change the close timeout?

### ISSUE THREAD

**Issue by hisune** [websockets/ws#766]
```js
// Close timeout

var closeTimeout = 30 * 1000; // Allow 30 seconds to terminate the connection cleanly
```
The default value is ```30 * 1000```, how to change it without hack the lines?

**Comment by 3rd-Eden** [comment]
Why would you need to change it?

**Comment by hisune** [comment]
Because I think 30 sec is too short.

**Comment by 3rd-Eden** [comment]
Why is it too short, what are you seeing as a result of this that made you want to change it?

**Comment by hisune** [comment]
sorry, I was wrong. ```closeTimeout``` not heartbeat timeout.
