### ISSUE TITLE
1.1.1 not in master?

### ISSUE THREAD

**Issue by STRML** [websockets/ws#768]
Here's the compare over 1.1.0:

https://github.com/websockets/ws/compare/1.1.0...1.1.1

Appears this was a hotfix release - without a CHANGELOG it's difficult to find so I'm posting this here for search.

**Comment by jgrund** [comment]
Any update on this? This is many commits behind master now.

**Comment by 3rd-Eden** [comment]
No clue what it was or what commit.

**Comment by STRML** [comment]
Please see the link above @3rd-Eden, the commit was yours.

**Comment by 3rd-Eden** [comment]
Lol oops, was a vulnerability that needed silent patching to prevent DDOS attacks. Hence it was not documented for a while as we needed people to move to the latest patch release. It should eventually be added the changelog file now that a significant time has passed.

**Comment by lpinca** [comment]
I've added the compare link in the releases section. it's not a proper changelog but it's better than nothing.
