### ISSUE TITLE
Readme's express example

### ISSUE THREAD

**Issue by caub** [websockets/ws#776]
concerning https://github.com/websockets/ws#expressjs-example isn't it better to do this [way](http://stackoverflow.com/a/17697134/3183756) rather than `server.on('request', app);`?

**Comment by Bobozee** [comment]
That's correct. This is the way how I am doing it:

    const server = http.createServer(app);
    const WebSocketServer = require('ws').Server;
    const websocket = new WebSocketServer({server: server});

    websocket.on('connection', (client) => {

        client.on('message', (message) => {
            console.log(`message: ${message}`);
            client.send(message);
        });

        client.on('close', () => {
            console.log('close');
        });
    });

    server.listen(port);

**Comment by lpinca** [comment]
It's the same. From https://nodejs.org/dist/latest-v7.x/docs/api/http.html#http_http_createserver_requestlistener:

> The requestListener is a function which is automatically added to the 'request' event.
