### ISSUE TITLE
Origin not sent?

### ISSUE THREAD

**Issue by mkschreder** [websockets/ws#779]
I'm having problems with this library on lighttpd. Lighttpd does not accept websocket requests that do not have Origin header. Is this a lighttpd problem or is it a missing feature in this module? 

When I added "Origin" to WebSocket.js file, it started working fine: 
'Origin': "http://"+headerHost,

**Comment by ide** [comment]
`options.origin` is supported: https://github.com/websockets/ws/blob/master/lib/WebSocket.js#L702. You need to explicitly specify it because Node has no concept of the current origin.

**Comment by mkschreder** [comment]
How about sending server ip as default origin?

**Comment by JoshuaWise** [comment]
Which IP? A server can have many different IP addresses, as there are many different network devices on a typical computer. That's why you have to specify it yourself

**Comment by lpinca** [comment]
Closing this, please comment if needed.
