### ISSUE TITLE
Ws + Nginx

### ISSUE THREAD

**Issue by johncordeiro** [websockets/ws#780]
I followed [NGINX Tutorial](https://www.nginx.com/blog/websocket-nginx/) to proxy websockets, but when I try to connect to server using my domain, it returns:

Response Code: 426 - Upgrade Required

I added to `nginx.conf`:

```
map $http_upgrade $connection_upgrade {
    default upgrade;
    '' close;
}
```

My server settings:

```
upstream websocket {
    server 127.0.0.1:5000;
    keepalive 8;
}

server {
    listen 80;
    listen 443 ssl;

    server_name mydomain.com;
    server_tokens off;

    location / {
        proxy_pass http://websocket;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        proxy_set_header Host $host;
    }
}
```

My websocket server:

```
var WebSocket = require('ws');
var WebSocketServer = WebSocket.Server;
var wss = new WebSocketServer({port: 5000});

wss.on('connection', function (ws) {
        //connection code
});
```

It works fine when requesting directly to IP. Do you know if I need to change anything on server creation or nginx settings?

**Comment by SEAPUNK** [comment]
There's a chance that nginx is routing your request to a different location. Make sure that `server_name` is correct, and that there is no other domain overriding that config.

**Comment by lpinca** [comment]
Closing this as this is most likely a NGINX configuration issue.

**Comment by richard1015** [comment]
![image](https://user-images.githubusercontent.com/13060263/56860836-582bfa00-69cd-11e9-9609-93af0eca853f.png)
![image](https://user-images.githubusercontent.com/13060263/56860840-5cf0ae00-69cd-11e9-8d97-a968c7fa1f1e.png)
Help me look at it.
