### ISSUE TITLE
Different protocols depending on endpoint

### ISSUE THREAD

**Issue by Turbo87** [websockets/ws#783]
My websocket server needs to support two different protocols depending on which HTTP endpoint was used to create the websocket. Unfortunately I don't seem to have access to the upgrade request in the `handleProtocols()` function so all I can do is accept both protocols or parse the protocols header myself in `verifyClient()` and reject them there already.

Is there a better solution for this? Should `handleProtocols()` have access to the upgrade request?

**Comment by lpinca** [comment]
> Should handleProtocols() have access to the upgrade request?

Yes, I think this makes sense.

**Comment by lpinca** [comment]
@Turbo87 a PR for this is welcome.
