### ISSUE TITLE
[request] Disable Nagle's algorithm

### ISSUE THREAD

**Issue by finscn** [websockets/ws#791]
Disable Nagle's algorithm could improved performance.
And many browsers use nagle disabled sockets by default,

https://groups.google.com/forum/#!topic/native-client-discuss/T8zdrMjiTAE

https://bugs.webkit.org/show_bug.cgi?id=102079

There is thread talk about it :
http://stackoverflow.com/questions/23810373/disable-nagles-algorithm-for-nsoutputstream

**Comment by lpinca** [comment]
Nagle's algorithm is already disabled, see https://github.com/websockets/ws/blob/4167e5c7997633334fed5ba270567687d4b0b8ce/lib/WebSocketServer.js#L262.
