### ISSUE TITLE
How to check if a client is open?

### ISSUE THREAD

**Issue by bitliner** [websockets/ws#793]
Sometimes, when i run broadcasting with following code:

```
wss.broadcast = function broadcast(data) {
        wss.clients.forEach(function each(client) {
            // Logger.info('Sending message', data);
            client.send(JSON.stringify(data));
        });
    };
```

it looks like some client is closed, throwing an error.

Is there a way to test if a client is open or closed?

**Comment by ericmdantas** [comment]
```js
if (client.readyState === client.OPEN) {
   // open
}
```

**Comment by bitliner** [comment]
Btw, it looks like if a client disconnect, it is not automatically removed from the list of clients.

I have to run a check on broadcast.

Is it the expected behavior?

My main question is: why a client is closed? it is because it disconnected for any reason but it is still in the list of clients?

**Comment by ericmdantas** [comment]
If I remember correcly, if you ignore the error, the server will crash because you're trying to write to a not-ready-to-receive-info-socket.

As for the list of clients, it should clean itself ([ref](https://github.com/websockets/ws/blob/fba58584e283c450d402fe2ffb8b36b2c14d4ebc/lib/WebSocketServer.js#L281-L285)).

**Comment by bitliner** [comment]
Well, I am trying to figure out where the error happens.

I am using version v0.7.2, that still removes the client on close event. So this version should be fine.

My code runs a `ws.close()` instruction when the client is not authorized anymore (according to my authentication system).

So even when the client is not authorized, then the client should be removed from the list.

But apparently there is still something that puts the state of client as not ready, but the client is not removed from the list clients.

Do you have any recommendation on which could be the cause?

Is there any other not handled event that could cause this issue?

**Comment by ericmdantas** [comment]
Well, `cleanupWebsocketResources` ([ref](https://github.com/websockets/ws/blob/4167e5c7997633334fed5ba270567687d4b0b8ce/lib/WebSocket.js#L936)) calls `emit('close')`, maybe you could try to check if that's being called and check the params?

Other than that, I'd try against a newer `ws` version.

**Comment by lpinca** [comment]
@bitliner a client is removed from the list of clients when the ready state is changed to `CLOSED` and the `close` event is emitted.

After calling `ws.close()` a client changes its ready state to `CLOSING` and starts a closing handshake. This can take some time and if you try to send data when the ready state is `CLOSING` you get an error.

As suggested by @ericmdantas check if the ready state is `OPEN` before sending data and use a newer version of `ws` :)
