### ISSUE TITLE
Getting response on websocket connection?

### ISSUE THREAD

**Issue by Dranithix** [websockets/ws#796]
Hi,

I'm trying to connect to an API's websocket and they send a 'socketId' on connection which I must send back as a form of handshake. They send the 'socketId' through a JSON response on connection, though I have no way to access any responses the client receives upon connection.

Any ideas on how to do it? It does not appears as a message event either.

https://i.gyazo.com/beb68e94c85a6aad04320d8ca8ce8db0.png

Thanks,
Dranithix

**Comment by 3rd-Eden** [comment]
That's not a WebSocket request.
