### ISSUE TITLE
Cannot get ws server to send server initiated data

### ISSUE THREAD

**Issue by SonnyRajagopalan** [websockets/ws#798]
I have the following code in `api.js`:

        var WebSocketServer = require ('ws').Server;
        var wss = new WebSocketServer({port: 8088});
        //var sleep = require ('sleep');
        var uuid = require('node-uuid');
        var EventEmitter = require ('events').EventEmitter;
        var anEventEmitter = new EventEmitter ();
        var wsObject = {};
        function onMessage (msg) {
          console.log ('received: %s', msg);
        }

        wss.on ('connection', function (ws) {
          wsObject[0] = ws;
          ws.on ('message', function (msg) {
            console.log ('received: %s', msg);
          });
          console.log ('Adding an event handler....')
          ws.addListener ('someEvent', function (someMessage) {
            console.log ("fired!");
            wss.clients.forEach(function each (client) {
              client.send (someMessage);
            });
          });
          ws.emit ('someEvent', "tickler of tummies");
        });
        function sendSomething (message) {
          wss.clients.forEach(function each (client) {
            client.emit ('someEvent', 'called later....')
          })
        }

        exports.send = sendSomething;

I am hoping to send something to a client that attaches (randomly selected from the clients that connects) at a future time by using the above code as a module in `trigger.js`:

    var api=require('./question.js');
    api.send (); 

That unfortunately crashes with:

    events.js:160
          throw er; // Unhandled 'error' event
          ^

       Error: listen EADDRINUSE 0.0.0.0:8088

Which I understand to be that `trigger.js` actually tried to create another server and so it has to bomb (as `api.js` already is listening on that port).

How do I go about using the server object to send something to some client?

I am looking to send only to one client, and the code in [https://github.com/websockets/ws#server-sending-broadcast-data](url) is where I started with the above code.

Any help is appreciated.

**Comment by NoNameProvided** [comment]
The `EADDRINUSE` error means that the specified address (0.0.0.0:8088) is already used by an another process. Try to bind to a different port. 

On a Mac you can type into your terminal: `lsof -i tcp: 8088` which will list the process using using that port. On windows you can [use](http://stackoverflow.com/a/23718720/2019689) the resource monitor. 

Hope this helps.

**Comment by SonnyRajagopalan** [comment]
I am closing this issue as my question is poorly written. I will open another issue with my question.
