### ISSUE TITLE
Last frame's payload not delivered and code 1006 returned

### ISSUE THREAD

**Issue by cyrus-and** [websockets/ws#799]
The title may not be 100% accurate, I apologize for that but it's not too clear to me what's happening...
### Versions

I can say for sure that this happens with version 1.1.1 but not with 0.4.32.

**Edit:** It doesn't work with version 0.8.1 either. The only difference with respect to 1.1.1 is that the close event code is still 1000.
### Client code

The client code is not really important, you can use the basic:

``` js
var WebSocket = require('ws');
var ws = new WebSocket(process.argv[2]);

ws.on('message', function (data, flags) {
    console.log('>', data);
});

ws.on('close', function (code, message) {
    console.error('#', code, message);
});
```

or even [`wscat`](https://github.com/websockets/wscat), what really matter is the `ws` version.
### How to reproduce

This behavior has been observed with the Google Chrome's Remote Debugging Protocol WebSocket; (cyrus-and/chrome-remote-interface#39).

Here are the step to reproduce this issue:
1. start a new Chrome session with `--remote-debugging-port=9222`;
2. fetch a list of the currently open tabs:
   
   ```
   $ curl http://localhost:9222/json
   [ {
      "description": "",
      "devtoolsFrontendUrl": "/devtools/inspector.html?ws=localhost:9222/devtools/page/952808E7-26BC-470B-B1DF-B61519786481",
      "faviconUrl": "https://www.google.it/favicon.ico",
      "id": "952808E7-26BC-470B-B1DF-B61519786481",
      "title": "New Tab",
      "type": "page",
      "url": "chrome://newtab/",
      "webSocketDebuggerUrl": "ws://localhost:9222/devtools/page/952808E7-26BC-470B-B1DF-B61519786481"
   },
   [...]
   ```
   
   Locate the new empty tab (`chrome://newtab/`) and not the WebSocket URL (in this case `ws://localhost:9222/devtools/page/952808E7-26BC-470B-B1DF-B61519786481`).

3. connect to that URL:
   
   ```
   $ wscat -c ws://localhost:9222/devtools/page/952808E7-26BC-470B-B1DF-B61519786481
   connected (press CTRL+C to quit)
   ```
4. from Chrome open the DevTools for that tab (this will close the WebSocket).
#### What happens with 1.1.1

```
connected (press CTRL+C to quit)
disconnected
```

Using a custom client we obtain the close event code 1006.

Using Wireshark we notice:
- `Sec-WebSocket-Extensions` is set to `permessage-deflate; client_max_window_bits=15` in the handshake reply;
- `Fin: True` and `Reserved: 0x04` and the payload is not human-readable in the last (and only) WebSocket frame.
#### What happens with 0.4.32

```
connected (press CTRL+C to quit)
< { "method": "Inspector.detached", "params": { "reason": "replaced_with_devtools"} }
disconnected
```

Using a custom client we obtain the close event code 1000.

Using Wireshark we notice:
- `Sec-WebSocket-Extensions` is not set in the handshake reply;
- `Fin: True` and `Reserved: 0x00` and the payload is the above JSON text in the last (and only) WebSocket frame.

**Comment by cyrus-and** [comment]
You may want to know that git-bisecting this issue the "first bad commit" is a810bfa44f08c84ff3f43cc71327e9bb5fb273ef.

**Comment by cyrus-and** [comment]
Indeed, the issue disappears (still 1006 though) if I set the option `perMessageDeflate` to `false`.

**Comment by lpinca** [comment]
I _think_ this is a server issue. The server should send a close frame and wait for a close frame from the client. See https://tools.ietf.org/html/rfc6455#section-7.1.2.

I think what happens here is that the server sends a compressed frame and the closed the TCP connection. The client receives the frame and starts decompressing it. Then the connection is closed but

1. The client didn't receive a close frame
2. The frame has not been decompressed yet

so the WebSocket connection is closed abnormally (1006).

I think you'll get the same result if you use a different client. Did you try with faye-websocket which has support for permessage-deflate?

When permessage-deflate is disabled the frame is processed before the TCP connection is closed so the message is not discarded but the close frame is still missing and this explains why you still get the 1006 close code.

This is kinda bad but I think it is the correct behavior.

**Comment by cyrus-and** [comment]
> I think you'll get the same result if you use a different client. Did you try with faye-websocket which also supports permessage-deflate?

That's exactly the case, I just tried with faye-websocket and the behavior is the same.

While I agree that this is an "abnormal closure", I'm not sure that the RFC states than an endpoint MUST/SHOULD discard the payload in such case.

The fact is that data is actually received in both cases (permessage-deflate or not) but the library delivers to the application only when the compression is not used. I spot some inconsistency here...

> The frame has not been decompressed yet

Of course I'm assuming that the compressed payload contains the whole (final) message. In my case I've 77 byte worth of compressed payload while the plaintext is 83 byte long, which seems legit IMHO.

**Comment by lpinca** [comment]
> The fact is that data is actually received in both cases (permessage-deflate or not) but the library delivers to the application only when the compression is not used. I spot some inconsistency here...

Yeah I agree, to make it work with permessage-deflate we should ignore the TCP close until all data has been processed or an error while processing occurs. #840 attempted to do this. Now the parser has changed significantly and it may be a bit harder.

**Comment by lpinca** [comment]
cc: @Nibbler999

**Comment by lpinca** [comment]
@cyrus-and #945 should address this issue. Can you please try installing from `gh-799` and see if it works as expected on your end?

Thanks.

**Comment by cyrus-and** [comment]
Yes, I can confirm, it works. Thank you so much!
