### ISSUE TITLE
how can I have my server only respond on certain domains?

### ISSUE THREAD

**Issue by x13machine** [websockets/ws#807]
I only want my server to respond if someone is using: ws://example.com but not ws://1.2.3.4. If they do connect to something other then example.com I want it to send an error message

**Comment by ericmdantas** [comment]
> SOP/CORS does not apply to WebSocket, but browsers will send an origin header that contains the hostname of the server that served the HTML with the JS that opened the WebSocket connection. A WebSocket server can then restrict access by checking origin

[ref](http://stackoverflow.com/questions/23674199/why-is-there-no-same-origin-policy-for-websockets-why-can-i-connect-to-ws-loc#comment36372038_23674863)

**Comment by x13machine** [comment]
I care about the "Host" header not any other header.

**Comment by lpinca** [comment]
The [`verifyClient`](https://github.com/websockets/ws/blob/master/doc/ws.md#new-websocketserveroptions-callback) option should allow you to do this.
