### ISSUE TITLE
How can I cause the server to receive error code 1006?

### ISSUE THREAD

**Issue by drew-gross** [websockets/ws#808]
I'm building an application that has a client and server in JS using websockets. The server needs to take some action if the client closes abnormally (eg. error 1006). I need to write tests for this behaviour. For most of my tests, I just create a client that connects to the server in the test, then close it with the appropriate error code:

``` js
const client = ... create the websocket ...
client.close(4000);
... assert that server has taken action appropriate for code 4000 ...
```

But for error code 1006, I can't do `client.close(1006)`. How can I test that the server is responding appropriately to code 1006?

**Comment by SEAPUNK** [comment]
You'll need to modify ErrorCodes.js manually.

https://github.com/websockets/ws/blob/master/lib/ErrorCodes.js#L11

**Comment by lpinca** [comment]
@drew-gross you can override `isValidErrorCode` in the test:
```js
const errors = require('./lib/ErrorCodes');

const original = errors.isValidErrorCode;

// Override `isValidErrorCode`.
errors.isValidErrorCode = () => true;

// Restore the original value when test is completed 
errors.isValidErrorCode = original
```
