### ISSUE TITLE
"Error: not opened"

### ISSUE THREAD

**Issue by Lolums** [websockets/ws#814]
Sometimes (not always), when I connect to the server and then send a packet, the server gets an exception called "Error: not opened".

I know that this is referring to the state of the WebSocket.

When I refresh the page that connects to the server and reconnect, I get the same error. Once I get the error once for a single client, that client always gets this error.

How does one fix this?

**Comment by Lolums** [comment]
Oh, I've found that this issue only occurs on the second connection from the same browser (haven't tried any more concurrent ones), aka if I open a second tab that connects in exactly the same way.

It sends one packet, which gets there and then disconnects due to being in the wrong connection state.

**Comment by rkaw92** [comment]
Seeing the same issue, but from the server's side - when a particular event on the server occurs, all clients are notified by iterating over sockets and send()ing a message to each. Suspecting stale sockets and missing clean-up on my side somewhere.

**Comment by rkaw92** [comment]
In my case, this was an error in our code. I was trying to send to sockets that really were closed (a cleanup routine was broken).

**Comment by JoshuaWise** [comment]
Sounds like you figured it out. Any objections to closing this issue?

**Comment by Lolums** [comment]
Not at all!15.09.2016, 21:21, "Joshua Wise" <notifications@github.com>:Sounds like you figured it out. Any objections to closing this issue?
