### ISSUE TITLE
Event close is emitted even open event was not emitted

### ISSUE THREAD

**Issue by polomsky** [websockets/ws#820]
version 1.1.1
When client connects to invalid url both events error and close are emitted.
In versions 0.8.1 and (1.0.x) only error event was emitted which is in my opinion correct behaviour.

**Comment by lpinca** [comment]
@polomsky this is consistent with browsers (at least in recent versions) where both `onerror` and `onclose` listeners are called.

Closing, please comment or reopen if needed.
