### ISSUE TITLE
Add leading / for requestOptions.path

### ISSUE THREAD

**Issue by 8alery** [websockets/ws#821]
There is a problem then using connectionString like this:
'ws://localhost:6464?sessionId=3aed8be6-ed38-467a-ae21-fcc7a1be3a19'
because http module expects / for path option, but url.parse result is: '?sessionId=3aed8be6-ed38-467a-ae21-fcc7a1be3a19'. If you add check for leading / near 688 line in file WebSocket.js these problem will be fixed. I understand that I can just write 'ws://localhost:6464/?sessionId=3aed8be6-ed38-467a-ae21-fcc7a1be3a19' (I did it for now) and it will work fine. But in browser  'ws://localhost:6464?sessionId=3aed8be6-ed38-467a-ae21-fcc7a1be3a19' works and it is really hard to understand what's gone wrong because only error code i got was 1006 - socket hang up.

**Comment by JacksonTian** [comment]
Pull Request is welcome.
