### ISSUE TITLE
Has this repository been abandoned?

### ISSUE THREAD

**Issue by JoshuaWise** [websockets/ws#824]
The last commit was on July 28th. The last time the author replied to an issue or pull request was July 29th.

If this repository was abandoned, someone should start a fork to continue development.

**Comment by BaiYinSilver** [comment]
Last author's reply was Sept 12. 
https://github.com/websockets/ws/issues/821#issuecomment-246302968
Looks like this is actively maintained.

**Comment by 3rd-Eden** [comment]
I am looking for additional maintainers as I can't contribute as much as I've hoped due to health issues. But its not abandoned.

**Comment by JoshuaWise** [comment]
Oh no! I hope you're okay. You're very important to the JavaScript community, if I do say so myself. I'd be happy to be a maintainer, if you'll have me.

Here's an a pull request I have on `ws`, as an example of my code:
https://github.com/websockets/ws/pull/811

**Comment by JacksonTian** [comment]
welcome @JoshuaWise

**Comment by JoshuaWise** [comment]
Thank you. I'm happy I can help 😄
