### ISSUE TITLE
For what needed callback in construct new Server?

### ISSUE THREAD

**Issue by Aleksey-Danchin** [websockets/ws#827]
In document write:

new ws.Server([options], [callback])

But when callback called? Just on start? It's all? Why I can't attempt callback without port?

**Comment by JoshuaWise** [comment]
The callback is invoked when the underlying HTTP server is listening for connections. A WebSocket server requires an underlying HTTP server. If you do not supply one yourself (`options.server`), then one will be created for the given port number (`options.port`).
