### ISSUE TITLE
Cannot work with nativescript 

### ISSUE THREAD

**Issue by willin** [websockets/ws#831]
a bit like react-native

``` js
var ws = null

    if (typeof WebSocket !== 'undefined') {
      ws = WebSocket
    } else if (typeof MozWebSocket !== 'undefined') {
      ws = MozWebSocket
    } else {
      ws = window.WebSocket || window.MozWebSocket
    }

    module.exports = ws
```

there is no `window` in native.

and here's a plugin but cannot support mqtt subprotocol https://github.com/NathanaelA/nativescript-websockets

**Comment by coolaj86** [comment]
maybe make a PR with a change for `else if (typeof window !== 'undefined')`?

**Comment by lpinca** [comment]
I agree with @coolaj86.

**Comment by taoqf** [comment]
Actually, It is not as simple as we think, I don't think I can find the code webpack generated.
https://github.com/mqttjs/MQTT.js/issues/462

**Comment by taoqf** [comment]
https://github.com/webpack/webpack/issues/5367

**Comment by alex-lucid** [comment]
it is still not working, why issue was closed?

**Comment by PhilippS93** [comment]
Any news on this issue?
