### ISSUE TITLE
Using websockets in javascript library

### ISSUE THREAD

**Issue by Bezdekm** [websockets/ws#837]
Hello,
I have one question. I have one main server written in Node.JS. And I have one javascript library that is running on the client by inserting `<script src="xxx.js"></script>` tag. The nodeJS server is running on stable URL and the client's library can be anywhere.

Is there any possibility to hold connection between the server and client? A mean import **ws** into client's pure javascript library which will connect to the server (nodeJS application)?

Thanks!

**Comment by JoshuaWise** [comment]
To use WebSockets in a browser, you have to use the native `WebSocket` global object.

You can read about it here: https://developer.mozilla.org/en-US/docs/Web/API/WebSocket

**Comment by Bezdekm** [comment]
Ok, thanks. So I can use native WebSocket object in the client library, on the server I will use this WS package and together it will works well?

**Comment by JoshuaWise** [comment]
That's exactly right!
