### ISSUE TITLE
How get IP address?

### ISSUE THREAD

**Issue by semiromid** [websockets/ws#857]
How get IP address  `before` connecting?

`          var webSocketServer = new WebSocketServer.Server({port: 8081, verifyClient: function(info, callback) { });`

**Comment by lpinca** [comment]
The `info` object should contain a reference to the `request` object.

**Comment by semiromid** [comment]
`info.request` ?

**Comment by lpinca** [comment]
`info.req` where `req` is the full request object.

**Comment by semiromid** [comment]
I don't find IP address client on server - console.log(info.req);
                                       console.log(util.inspect(info, false, null));

**Comment by zia-newversion** [comment]
Been at this _exact_ spot for 2 hours now! Google, SO, WS docs, everything. :weary: 

- `info.req.remoteAddr` is `undefined`
- `info.req.connection.remoteAddr` is `undefined`
- `info.req.socket.remoteAddr` is `undefined`
- `info.req.connection.socket` is `undefined`
- `info.req.socket._socket` is `undefined`
- `info.req.socket.upgradeReq` is `undefined`

**Comment by lpinca** [comment]
It should be `info.req.connection.remoteAddress`.

**Comment by zia-newversion** [comment]
IKR? If `req` is a copy of the Node.js `http.ClientRequest`, `remoteAddr` should be at `req.connection.remoteAddr`, except it's not...

    new ws.Server({
        server,          // (server instanceof http.Server) === true
        verifyClient(info) {
            console.log(info.req.connection.remoteAddr);
            return true;
        },
    });

Yields

    undefined

Can someone reproduce?

**Comment by JoshuaWise** [comment]
Since when was it `connection.remoteAddr`? The Node.js docs clearly state `connection.remoteAddress`

**Comment by zia-newversion** [comment]
Oh damn... I'm embarrassed now! Sorry. My bad. I have been reading that as `remoteAddr`, even when @Ipinca commented above. So sorry...

**Comment by semiromid** [comment]
lpinca  - Very Thanks You!!!

**Comment by lpinca** [comment]
np.
