### ISSUE TITLE
Add @Nibbler999 as collaborator

### ISSUE THREAD

**Issue by lpinca** [websockets/ws#858]
@3rd-Eden what do you think about adding @Nibbler999 as collaborator?
He is doing an awesome job:

- https://github.com/websockets/ws/pulls/Nibbler999
- https://github.com/websockets/bufferutil/pull/52

**Comment by 3rd-Eden** [comment]
+1 & done.

**Comment by 3rd-Eden** [comment]
@lpinca And so are you.

**Comment by lpinca** [comment]
Yeah noticed, thanks!

**Comment by Nibbler999** [comment]
What does this mean? I don't see any new options.

**Comment by lpinca** [comment]
@Nibbler999 didn't you receive and invite via email?

**Comment by Nibbler999** [comment]
No.

**Comment by lpinca** [comment]
Now?

**Comment by Nibbler999** [comment]
Now I do, thanks :)
