### ISSUE TITLE
plans to support koa.js

### ISSUE THREAD

**Issue by Eric24** [websockets/ws#868]
Any plans to support koa.js or examples of using ws with koa.js?

**Comment by ladytellur** [comment]
@Eric24 you could take a look at [koa-ws](https://github.com/mekwall/koa-ws) as an example

**Comment by lpinca** [comment]
There is also [`koa-websocket`](https://github.com/kudos/koa-websocket/tree/next).

**Comment by Eric24** [comment]
We ended up using [koa-socket](https://github.com/mattstyles/koa-socket), and have been very pleased with the results so far.
