### ISSUE TITLE
How use ping/pong?

### ISSUE THREAD

**Issue by semiromid** [websockets/ws#876]
Hi! How use ping/pong? Please show example. 

```
websocket.ping([data], [options], [dontFailWhenClosed])
websocket.pong([data], [options], [dontFailWhenClosed])
```
How use - `dontFailWhenClosed `? Example please.

**Comment by semiromid** [comment]
maybe 
```
setInterval(function() {
ws.pong('pingdata');
}, 60000);
```

**Comment by semiromid** [comment]
How of clint send on server ping?

**Comment by lpinca** [comment]
`dontFailWhenClosed` is a boolean argument you can use to prevent `ping` from throwing an error when ready state is not `OPEN`.

If a peer receives a ping message it automatically responds with a pong message.
