### ISSUE TITLE
How to create wss protecol ?

### ISSUE THREAD

**Issue by AaronWB** [websockets/ws#878]
I was build WSS connection , but i don't know how to create WebSocket server , thanks.

**Comment by lpinca** [comment]
If I understand your question correctly, you have to create a HTTPS server as specified here https://nodejs.org/dist/latest-v7.x/docs/api/https.html#https_https_createserver_options_requestlistener and pass that server to the `WebSocketServer` constructor via the `server` option:

```js
const server = https.createServer(options);
const wss = new WebSocket.Server({ server });
```

**Comment by lpinca** [comment]
Closing, please comment or reopen if needed.
