### ISSUE TITLE
How to handle message binary data from the client

### ISSUE THREAD

**Issue by saste** [websockets/ws#879]
Hi,

I'm using ws for the first time to implement a client connecting to a websocket server.

I'm creating a websocket client with this code:
 
            var WS = require('ws');
            websocket = new WS(config.url, null, {
                rejectUnauthorized: false
            });
            websocket.binaryType = 'arraybuffer';

            console.log("Sending connection request to '" + config.url + "' with object ws:" + JSON.stringify(websocket));
            [...]
            websocket.on('message', onMessage);

And the onMessage:

    function onMessage (data, flags) {
        log.info("onMessage data(", data, ") ", typeof(data), " flags(", flags, ")");

        var dv = new DataView(data),
            msgSize = dv.getUint32(0, true),
            binSize = dv.getUint32(4, true),
            msg;

I expect `data` to be an ArrayBuffer. Instead I got a "buffer" object, which I cannot convert to a DataView.

This is the log I get:
```
Sending connection request to 'wss://localhost:8333/auth' with object ws:{"domain":null,"_events":{},"_maxListeners":10,"_socket":null,"_ultron":null,"_closeReceived":false,"bytesReceived":0,"readyState":0,"supports":{"binary":true},"extensions":{},"_binaryType":"arraybuffer","_isServer":false,"url":"wss://localhost:8333/auth","protocolVersion":13}
onMessage data( <Buffer 0f 00 00 00 00 00 00 00 52 0d 0a 04 6e 6f 6e 65 52 05 50 4c 41 49 4e 00> )  object  flags( { masked: false,
  buffer: <Buffer 0f 00 00 00 00 00 00 00 52 0d 0a 04 6e 6f 6e 65 52 05 50 4c 41 49 4e 00>,
  binary: true } )

client.js:
        var dv = new DataView(data),
                 ^
Error: Object must be an ArrayBuffer.
```

Question is: what kind of data must I expect in the onMessage callback, in case I'm using binary data? How can I convert the received buffer in an ArrayBuffer/DataView?

Thanks.

**Comment by lpinca** [comment]
Hi,
right now you get an `ArrayBuffer` only when using the `addEventListener` method, see https://github.com/websockets/ws/blob/95001508cdec29dfe49b9e87a493f9d9f559bcb7/lib/WebSocket.js#L426-L428.

If you use `on` you'll get a `Buffer` and you have to convert it yourself.

**Comment by saste** [comment]
I confirm that using `websocket.onmessage = onMessage;` is now working correctly, thanks!
