### ISSUE TITLE
Context per connection?

### ISSUE THREAD

**Issue by leebenson** [websockets/ws#898]
More of a question, than an issue. Are there any known no-nos/gotchas with setting a per-connection context directly on the callback param set when emitting `connection` ?

I'm toying with the idea of setting up a context Map to store ephemeral session data. It would be handy to have access to that data when handling future messages from the client on the same connection.

When the connection closes, I assume `connection` goes away and anything connected to the context Map will be GC'd, right?

**Comment by lpinca** [comment]
Yes, it should work. You can null the null the map when you are done with it to be extra sure but it should be GC'd if there are not other references that keep it alive.

**Comment by leebenson** [comment]
Awesome, thanks @lpinca. I'm surprised I haven't seen this pattern promoted more. IMO, it's a huge win for Websockets to do a session handshake _once_ and allow future messages to re-use it. In my current project, that'd shave ~50ms vs every http request, which is pretty major. Thanks!
