### ISSUE TITLE
Event for client disconnection?

### ISSUE THREAD

**Issue by leebenson** [websockets/ws#899]
Looking at [`WebSocketServer.js`](https://github.com/websockets/ws/blob/master/lib/WebSocketServer.js), I don't see an event being fired when the client terminates a connection.

Is there one?

**Comment by lpinca** [comment]
```js
wss.on('connection', (ws) => {
  ws.on('close', () => console.log('disconnected'));
});
```

**Comment by leebenson** [comment]
ah, perfect - thanks!
