### ISSUE TITLE
err: webSocketServer is not a constructor  

### ISSUE THREAD

**Issue by eliezergu** [websockets/ws#901]
Hi I tried to run this code >>>
'use strict';
var server = require('https');
var express = require('express');
var fs = require('fs');

var privateKey = fs.readFileSync('<<my-path>>', 'utf8');
var certificate = fs.readFileSync('<<my-path>>', 'utf8');

var credentials = {key: privateKey, cert: certificate};

var app = express();

server.createServer(credentials, app);

var url = require('url');
var webSocketServer = require('ws').server;

wss = new webSocketServer({server: server});

var port = 8443;

app.use(function (req, res) {
    res.send({msg: 'Hello'});
});

wss.on('connection', function connection(ws) {
    var location = url.parse(ws.upgradeReq.url, true);
    
ws.on('message', function incoming(message) {
    console.log('received: %s', message);
});
    
ws.send('Thanks for message');    
});

server.on('request', app);
server.listen(port, function () {
    console.log('Listening on ' + server.address().port);
});

And node complains about webSocketServer isn't a constructor
here is the err node throw >>>
  wss = new webSocketServer({server: server});
      ^

TypeError: webSocketServer is not a constructor
    at Object.<anonymous> (C:\Users\shulem\Documents\myWebRTCApp\expressWS.js:18:7)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

Any suggestions???

**Comment by lpinca** [comment]
You have a typo on this line
```js
 var webSocketServer = require('ws').server;
```
It should be `require('ws').Server`.

**Comment by lpinca** [comment]
Closing this, please comment if needed.

**Comment by eliezergu** [comment]
Thank you I followed your instructions  and didn't got the err anymore but i'm still getting other err's you can check it out here  https://github.com/websockets/ws/issues/904
I'll appreciate
