### ISSUE TITLE
Receiving binary data from client isn't working

### ISSUE THREAD

**Issue by rico345100** [websockets/ws#902]
When I got binary data from client, it wasn't ArrayBuffer object. I tried with using addEventListener or just attached event handler "onmessage" directly, both won't worked.

I'm sending ArrayBuffer from client like this:
```javascript
// Client
socket.addEventListener('open', () => {
	console.log('Connected.');

	socket.binaryType = 'arraybuffer';
	socket.send(buffer);
});
```

And got from server like this:
```javascript
// Server
wss.on('connection', (socket) => {
	socket.addEventListener('message', (e) => {
		let buffer = e.data;

                console.log(buffer instance of ArrayBuffer);    // false

		let dv = new DataView(buffer);    // TypeError: First argument to DataView constructor must be an ArrayBuffer
	});
});
```

I read this article: https://github.com/websockets/ws/issues/879, but not working on me.

**Comment by lpinca** [comment]
Try to add `socket.binaryType = 'arraybuffer'` on the server side, it should work

**Comment by rico345100** [comment]
Oh, it works. Thanks. But still I need to use addEventListener, instead of on method.

**Comment by lpinca** [comment]
Yes, `socket.onmessage = fn` should also work.

**Comment by lpinca** [comment]
Closing this, please comment if needed.
