### ISSUE TITLE
Can websockets support express-session?

### ISSUE THREAD

**Issue by Emiya0306** [websockets/ws#906]
Just like the title, I use the [Example](https://github.com/websockets/ws#expressjs-example) of README.MD, try to support `express-session`. But it cannot work to call `socket.upgradeReq.session` which is undefined on one connected socket.

I think the [Example](https://github.com/websockets/ws#expressjs-example) that WS and express are two separate modules and WS are not proxy by express, so `express-session` is not working on WS. Is any method to call `socket.upgradeReq.session` to get session data? Get session Id by `socket.upgradeReq.headers.cookie` and use session store is not very graceful, I think.

**Comment by lpinca** [comment]
@Emiya0306 `express-session` does not work because it's not run for upgrade requests (WebSocket requests).

> Get session Id by socket.upgradeReq.headers.cookie and use session store is not very graceful, , I think.

This is actually the best way to avoid incurring in nasty race conditions.

**Comment by Emiya0306** [comment]
Got it. Now I run this session parse when socket connect event happen. Thanks! 😃

**Comment by lpinca** [comment]
You can also parse it in the `verifyClient` hook if you want to have it before `connection` event is emitted.

**Comment by GeometricAlgorithm** [comment]
@lpinca Care to elaborate? How do I get the cookie/sid saved during `verifyClient` so that it is available in the `connection` event?

**Comment by lpinca** [comment]
@GeometricAlgorithm there is an example under the `examples` folder in this repo.

**Comment by GeometricAlgorithm** [comment]
@lpinca TYVM for the swift response! I have been stuck on this for days.

Right now I've got my code following the example, but the `req` object is undefined in the following lines:
```
wss.on('connection', (ws, req) => {
  ws.on('message', (message) => {
    //
    // Here we can now use session parameters.
    //
    console.log(`WS message ${message} from user ${req.session.userId}`);
  });
});
```

**Comment by lpinca** [comment]
Make sure that your `ws` version is >= 3.
