### ISSUE TITLE
Discussion

### ISSUE THREAD

**Issue by GrosSacASac** [websockets/ws#907]
Why do you use the ultron dependency ? I looked here  https://github.com/unshiftio/ultron/blob/master/index.js and it does nothing special.

**Comment by lpinca** [comment]
It is used to remove only the listeners added by us as `emitter.removeAllListeners()` also removes the listeners added the user and in some cases by Node.js.

**Comment by lpinca** [comment]
See https://github.com/websockets/ws/issues/392.

**Comment by 3rd-Eden** [comment]
> I looked here https://github.com/unshiftio/ultron/blob/master/index.js and it does nothing special.

Best compliment a project can get imho. Code that does looks so simple, yet does amazingly useful stuff. :D

**Comment by GrosSacASac** [comment]
Good idea. I now see why you chose ultron. Where can I read more about the web socket internal API and how ws works ?

**Comment by lpinca** [comment]
@GrosSacASac Most of the work is done in the [`Receiver`](https://github.com/websockets/ws/blob/master/lib/Receiver.js) and [`Sender`](https://github.com/websockets/ws/blob/master/lib/Sender.js).
The [server](https://github.com/websockets/ws/blob/master/lib/WebSocketServer.js) is pretty simple.

If you are not familiar with WebSocket data framing read the [RFC](https://tools.ietf.org/html/rfc6455#section-5).

**Comment by GrosSacASac** [comment]
Allright, thanks have a great day ! :)
