### ISSUE TITLE
messages  heap on client

### ISSUE THREAD

**Issue by icecxh** [websockets/ws#911]
when server send message in a small interval,the client receive the message not on time ,It's store and then some time receive many of them one-time

**Comment by lpinca** [comment]
I'm not sure I understand the issue. Can you please clarify with a small code example?
Thanks.

**Comment by icecxh** [comment]
###server 
`index=1
a=setInterval(function(){
			var data={info:[[],1,xxx]};
			var buf=messageSchema.encode(data);
			for(var i=0;i<clients[index].length;i++){
				if(clients[index][i].ws.readyState===1){
					clients[index][i].ws.send(buf);
				}
			}
		},15)`
### client
`beforeTime=0;
ws.onmessage()=function(e){
       console.log(Date.now()-beforeTime);
	beforeTime=Date.now();
	var message=messageSchema.decode(e.data);
        ................`
![qq 20161124151732](https://cloud.githubusercontent.com/assets/19871501/20592351/ef45d6a6-b267-11e6-9dd2-e4c20c8af406.jpg)

I test it at local area network,with my classmate's computer,thanks!

**Comment by lpinca** [comment]
What platform is the server on? We use [`socket.setNoDelay()`](https://nodejs.org/api/net.html#net_socket_setnodelay_nodelay) so this should not happen.

It works as expected on localhost (macOS):

```js
'use strict';

const WebSocket = require('ws');

const wss = new WebSocket.Server({ port: 3000 }, () => {
  const ws = new WebSocket('ws://localhost:3000');

  let time = Date.now();

  ws.on('message', () => {
    const now = Date.now();

    console.log(now - time);
    time = now;
  });
});

wss.on('connection', (ws) => {
  const data = Buffer.from('hello');
  setInterval(() => ws.send(data), 15);
});
```

**Comment by icecxh** [comment]
windows 7,when I test on one computer it's not happen(client and server both run on my own computer) ,but it's  appear when the server run on my computer and the client run on other computer .I found the server send the message as expected. the problem might on client side . And I'm not sure the reason,Maybe it's because of the network?

**Comment by lpinca** [comment]
@icecxh it may be Windows. I tried on two different machines, Linux and macOS.
The server runs on Linux and client on macOS. The machines are on wireless lan.
Everything works as expected.

**Comment by lpinca** [comment]
Just tried with the server on Windows 10. It also works, ¯\_(ツ)_/¯.

**Comment by icecxh** [comment]
I'm so sorry to bother you,the problem might on my computer's WLAN card, I try to test on other computer and it works as expected , thank you very much!

**Comment by lpinca** [comment]
No problem. Closing this, please comment back or reopen if needed.
