### ISSUE TITLE
Handshake failure when a protocol is specified

### ISSUE THREAD

**Issue by vitorz** [websockets/ws#922]
Hi,
i need to use websocket with protocol(is the unique safe place where to put auth info). I found an error in WebSocketServer.js (line:196) the headers var is an array not an object, so the right line would be:

headers.push('Sec-WebSocket-Protocol: '+ protocol);

as you wrote in other places in that file.
Hope to have been helpful.

Best regards

Vitor

**Comment by lpinca** [comment]
@vitorz what version of `ws` are you using? Is this issue in master?

**Comment by vitorz** [comment]
Hi
to be honest i was thinking to be in the forked project called streamws(maybe i clicked in the wrong link while i was in their website), the issue is related to forked version of the file that i mentioned. Sorry if it's not relevant for this project.

**Comment by lpinca** [comment]
No problem.
