### ISSUE TITLE
`Error: not opened` in `open` event

### ISSUE THREAD

**Issue by WeeJeWel** [websockets/ws#924]
So, I've got this (simplified) code:

```javascript
ws.on('open', function(){
	ws.send('foo'); // throws Error: not opened
})
```

Specifically: https://github.com/WeeJeWel/node-webos/blob/master/lib/remote.js#L63

Seems like a bug to me, because it all happens in the same tick.

**Comment by lpinca** [comment]
This is indeed weird, are you able to reproduce it or it happens randomly?

I would tell you to try installing from master and see if the issue persists but this is not a good idea if this is a production system.

**Comment by lpinca** [comment]
@WeeJeWel I just took a look at your code.
Is it possible that you are calling `ws.send()` on a `ws` object different from the one that emitted the `open` event?

What you are doing is this:

```js
this.ws = new WebSocket(...);
this.ws.on('open', onOpen.bind(this));
```

then in the `onOpen` function you call `this.ws.send()` but maybe `this.ws` is already a different instance.

Does it makes sense?

**Comment by WeeJeWel** [comment]
@lpinca I'm 99% that doesn't happen. The Remote class is only initiated once, and the `this` object is also bound to the onOpen method

**Comment by lpinca** [comment]
Yeah but `_reconnect()` changes the `ws` instance. A race condition in the reconnection is all I can think of.

**Comment by lpinca** [comment]
@WeeJeWel to exclude that 1% try to add the `ws` instance as an argument to the `onOpen` function and see if the instances matches:

```js
this.ws.on('open', onOpen.bind(this, this.ws));

function onOpen(ws) {
  this.debug('onOpen, %s', ws === this.ws);
  ...
}
```

**Comment by lpinca** [comment]
@WeeJeWel any update on this?

**Comment by WeeJeWel** [comment]
I haven't seen it occur anymore, and didn't have time to test the snippet unfortunately. I'll close it for now!
