### ISSUE TITLE
Cannot send objects to the client

### ISSUE THREAD

**Issue by mercmobily** [websockets/ws#928]
var WebSocketServer = require('ws').Server;
    var wss = new WebSocketServer({ server: server, path: '/ws' })

    wss.on('connection', function connection(ws) {
      var location = require('url').parse(ws.upgradeReq.url, true);

      ws.on('message', function incoming(message) {
        console.log('received: %s', message);
      });

      setTimeout(function(){
        // This doesn't work
        ws.send( { type: 'something', text: 'THIS WILL ARRIVE AFTER 2 SECONDS FROM THE SERVER' }, { binary: true, mask: true }  );
        // This works
        //ws.send( [1,2,3] );

      }, 2000)
    });

It's  very straightforward, and yet it doesn't work:

    About to send something to the client...
    events.js:141
          throw er; // Unhandled 'error' event
          ^

    TypeError: Invalid non-string/buffer chunk
        at validChunk (_stream_writable.js:185:14)
        at DeflateRaw.Writable.write (_stream_writable.js:212:12)
        at PerMessageDeflate.compress (/disk/home/merc/Data/Development/node/hotplate/node_modules/ws/lib/PerMessageDeflate.js:306:17)

I tried adding `perMessageDeflate: false`. The error changes:

    About to send something to the client...
    buffer.js:156
      throw new TypeError('must start with number, buffer, array or string');
      ^
    TypeError: must start with number, buffer, array or string
        at fromObject (buffer.js:156:9)
        at new Buffer (buffer.js:65:10)
        at Sender.frameAndSend (/disk/home

Using: node 4.4.4 and the latest npm installation of ws.

I *can* `JSON.stringify()` before sending it. But. I *can* send binary data using the client without any trouble (it comes through as an object). So... I would have a protocol where data is stringified from the client to the server, and not vice-versa, which feels a little weird...

Help?

**Comment by lpinca** [comment]
This is not a bug but intended behavior. 
In order to send an object you have to serialize it. There are countless ways to do this (`JSON.stringify()`, MessagePack, etc.).
The client works exactly in the same way so it doesn't work out of the box if you send a plain object.
