### ISSUE TITLE
How to authenticate a client via token using verifyClient?

### ISSUE THREAD

**Issue by subwaystation** [websockets/ws#929]
Currently I am trying to implement a way so that a client who wants to connect to the `websocket` has to be authenticated first. Mainly,  I wanted to reproduce this example: [http://iostreamer.me/ws/node.js/jwt/2016/05/08/websockets_authentication.html](url)
However, the `websocket` specifications [https://html.spec.whatwg.org/multipage/comms.html#network](url) state that the only arguments allowed on the client side are `url` and `protocol`. Furthermore, the `ws` module won't be available on the client side. I tried `browserify`, but this does not work. Now I am wondering how an secure client authentication using `tokens` and `verifyClient` is possible with `ws`?
A server and client side example would be awesome.

An additional question I have:
```javascript
wss.on('connection', function connection(ws) {
  var location = url.parse(ws.upgradeReq.url, true);
  console.log(location);
}
```
Gives me:
```javascript
Url {
  protocol: null,
  slashes: null,
  auth: null,
  host: null,
  port: null,
  hostname: null,
  hash: null,
  search: '',
  query: {},
  pathname: '/',
  path: '/',
  href: '/' 
}
```
How can I set all these fields on the client side?

I also stumbled across [websockets.github.io/ws/](url). Though here the `websocket` handshake already took place before the authentication process. Furthermore, a client would still be able to send stuff not containing the `authentication` header which then would not have to be authenticated. Or am I getting something wrong?

Any help would be appreciated.
All the best.

**Comment by lpinca** [comment]
You can add your token in the connection URL:

```js
const ws = new WebSocket('ws://example.com/?token=abcde');
```

Then in the `verifyClient` hook you can validate the token:

```
options.verifyClient = (info) => {
  const token = url.parse(info.req.url, true).query.token;
  
  //
  // Now validate the token and return `true` or false accordingly.
  //
};
```

**Comment by lucj** [comment]
In verifyClient, I check the token provided in the query string but there is a check I cannot done without having access to the ws.
I perform this second check within the .on('connection') callback but cannot properly close the socket is it fails:
- ws.close() does not close the client
- ws.destroy() is not available
Anything I'm missing ?

**Comment by lpinca** [comment]
@lucj may I ask why you need access to the `ws` object?

There is `ws.terminate()` which calls `socket.end()` sending a FIN packet to other peer.

**Comment by lucj** [comment]
@lpinca I need to perform an api call to get a list of ids to which the socket (ws) needs to subscribe to:

- in the verifyClient, I get the list (one api call) and reject the socket if it's empty
- in the on('connection') callback I get the list (same api call) and subscribe the socket to the ids

Obviously, performing twice the same call is not good, so I'll do it only in the callback and use the terminate() method.

Thanks for your help.

**Comment by subwaystation** [comment]
@lpinca Thanks for the tipp above, works like a charm.

**Comment by lpinca** [comment]
@lucj if the API call is the same, you can store the result in the `req` object and reuse it within the `on('connection')` handler:

```js
options.verifyClient = (info, cb) {
  request('endpoint', (err, res, body) => {
    if (!ok) return cb(false);

    info.req.yourListOfIds = yourListOfIds;
    cb(true);
  });
}; 

wss.on('connection', (ws) => {
  const ids = ws.upgradeReq.yourListOfIds;
  ws.upgradeReq.yourListOfIds = null;
});
```

**Comment by lucj** [comment]
@lpinca I'm sure this will work, and is more elegant than performing twice the same call :)
Thanks, I'll try this approach.

**Comment by caniko2** [comment]
What if I want to send the verification token using POST and not GET.

Yes, I am using the new method for verifying the client (not using verifyClient), but the issue still stands (obviously).

Thanks

**Comment by lpinca** [comment]
You can't use POST, the handshake request must use the GET method as per spec.
