### ISSUE TITLE
"Refused to set unsafe header" error

### ISSUE THREAD

**Issue by dotansimha** [websockets/ws#938]
The following lines:
https://github.com/websockets/ws/blob/master/lib/WebSocket.js#L556-L560

causes these errors in a browser:
```
modules.js?hash=5d5cfef…:78093 Refused to set unsafe header "sec-websocket-version"
modules.js?hash=5d5cfef…:78093 Refused to set unsafe header "sec-websocket-key"
modules.js?hash=5d5cfef…:78093 Refused to set unsafe header "sec-websocket-protocol"
modules.js?hash=5d5cfef…:78093 Refused to set unsafe header "sec-websocket-extensions"
```

Any idea how to avoid/fix?

**Comment by lpinca** [comment]
How are you using the module? The client is for Node.js

**Comment by dotansimha** [comment]
I see. Is there a client for browsers? Or I should use the regular WebSocket object of the browser?

**Comment by lpinca** [comment]
> Or I should use the regular WebSocket object of the browser?

This.

**Comment by dotansimha** [comment]
Thanks @lpinca! Do you have an example of how to use the server with upgrade request? (with WebSocket of the browser)

**Comment by lpinca** [comment]
I'm not sure I understand your question correctly. Do you want to use a pre-created server and handle the [upgrade](https://nodejs.org/dist/latest-v7.x/docs/api/http.html#http_event_upgrade_1) event?

**Comment by lpinca** [comment]
<details>
<summary>Internally started server</summary>

```js
'use strict';

const WebSocket = require('ws');

const wss = new WebSocket.Server({
  port: 3000
}, () => console.log('listening on *:3000'));

wss.on('connection', (ws) => {
  ws.send('foo');
});
```
</details>


<details>
<summary>Pre-created server</summary>

```js
'use strict';

const WebSocket = require('ws');
const http = require('http');

const wss = new WebSocket.Server({ noServer: true });
const server = http.createServer();

server.on('upgrade', (request, socket, head) => {
  wss.handleUpgrade(request, socket, head, (ws) => {
    ws.send('foo');
  });
});

server.listen(3000, console.log('listening on *:3000'));
```
</details>


<details>
<summary>Browser</summary>

```js
const ws = new WebSocket('ws://example.com:3000');

ws.onopen = function () {
  console.log('open');
}

ws.onmessage = function (evt) {
  console.log(evt.data);
};
```
</details>

These should answer your question.

**Comment by dotansimha** [comment]
Great. Thanks @lpinca
