### ISSUE TITLE
Including ws into Angular 2 front end.

### ISSUE THREAD

**Issue by NeuralChris** [websockets/ws#941]
Hey guys,

I'm having an issue including the WebSocket library into an Angular 2 frontend.  I'm trying to run the line

`Import { WebSocket } from "ws";`

But it keeps saying it can't find ws.  Is there something special that needs to be done with this library to make it so Angular 2 can find it properly?  It seems as though Webpack is picking it up and putting WS into the bundle.js.  Also, I can include classes from rxjs or other libraries just fine.  

Any help would be greatly appreciated!

**Comment by lpinca** [comment]
@NeuralChris on the browser you should use the native `WebSocket` object, not `ws`.

That said `ws` exports the `WebSocket` class as default so maybe this works:

```js
import WebSocket from 'ws';
```
