### ISSUE TITLE
maxPayload doesn't take effect

### ISSUE THREAD

**Issue by narychen** [websockets/ws#943]
I want to set limit on per max message size, so that if someone continue to send very big size msgs won't consume a lot of my server memory.
I wrote like this 
var server = new WebSocket.Server({ maxPayload: 1024});
But when I sent a message bigger than 1024 byte , I still could receive it.
I search the code in ws package but found no maxPayload key word.

**Comment by narychen** [comment]
My version is 1.0.1. I check the latest release is this version.
But I search the current master branch code, there is maxPayload in it.
Is this feature have not been released yet?

**Comment by lpinca** [comment]
The latest version available on npm is 1.1.1.

**Comment by lpinca** [comment]
@narychen just tested and it works as expected with 1.1.1:

```js
'use strict';

const crypto = require('crypto');
const WebSocket = require('ws');

const data = crypto.randomBytes(1025);

const wss = new WebSocket.Server({
  maxPayload: 1024,
  port: 3000
}, () => {
  const ws = new WebSocket('ws://localhost:3000');

  ws.on('open', () => ws.send(data));
});

wss.on('connection', (ws) => {
  ws.on('error', (err) => {
    console.error(err.message);
    // => payload cannot exceed 1024 bytes
  });
});
```

**Comment by lpinca** [comment]
Closing, please reopen if needed.
