### ISSUE TITLE
question - Instantiating socket server is synchronous?

### ISSUE THREAD

**Issue by ORESoftware** [websockets/ws#946]
Quick question for you - I only need TCP not HTTP -

looking at the docs here:
https://github.com/websockets/ws/blob/master/doc/ws.md

it says websockets.Server constructor takes a callback

> callback will be added as a listener for the listening event when the HTTP server is created internally and that is when the port option is provided.

when only using the socket server (no http server) should I use the callback, and wait to make client connections until the callback fires?

**Comment by ORESoftware** [comment]
Also, as an aside, as a nice design pattern for asynchronous constructors, with asynchronous methods you can do this:

```js
function AsyncConstructor(){

this.ready = false;

this.init = function(cb){

   if(this.ready){
    return process.nextTick(cb);
   }

   doSomeAsyncSetup(err => {
        this.ready = true;
        cb(err)
    });
 
}

}


AsyncConstructor.prototype.someMethod = function(data, cb){

this.init(err => {
  //handle error
       doSomeWork(this, cb);
 }

}

```

I like that pattern

**Comment by lpinca** [comment]
> when only using the socket server (no http server) should I use the callback, and wait to make client connections until the callback fires?

No as the `WebSocketServer` callback is not called in this case. For example:

```js
const WebSocket = require('ws');
const http = require('http');

const server = http.createServer();
const wss = new WebSocket.Server({ server });

server.listen(port, () => {
  // The server is now listening so you can start creating client connections.
});
```

but you can also pass an already listening server.

Hope this makes sense.

**Comment by lpinca** [comment]
Closing this, discussion can continue if needed.
