### ISSUE TITLE
Support question - Using emphemeral ports

### ISSUE THREAD

**Issue by ORESoftware** [websockets/ws#947]
Is it possible to use emphemeral ports with this library?

The only way I see this working is if all the websocket clients were on the same machine, and when the broker starts up, it would write the port number being used to a known / predetermined location on the filesystem.

Just curious if this is possible with this library! thanks

**Comment by lpinca** [comment]
> The only way I see this working is if all the websocket clients were on the same machine, and when the broker starts up, it would write the port number being used to a known location on the filesystem.

Yes, I think that something like this is the only way.

**Comment by ORESoftware** [comment]
ok, my use case fits this - I just don't know how to tell ws to use an emphemeral port. If I do not supply a port to ws (e.g. wss = new WebSocketServer({ port: null});

a) will ws use an emphemeral port?
b) if (a), how can I retrieve the port # that ws will end up using?

**Comment by lpinca** [comment]
I'm not sure about version `1.1.1` but on master using `{ port: 0 }` should work.
When using a random port I think it's better to use an external http server.

```js
const WebSocket = require('ws');
const server = require('http');

const wss = new WebSocket.Server({ server });

...

server.listen(() => {
  const addr = server.address();
  ...
});
```

This way you have better control.

**Comment by lpinca** [comment]
Closing this, please comment if needed.
