### ISSUE TITLE
support question - source of error

### ISSUE THREAD

**Issue by ORESoftware** [websockets/ws#948]
I get this error when I have more than one client connected to the websocket broker/server - it happens after I close one of the clients, then throws this error:

```console
/home/oleg/WebstormProjects/oresoftware/observable-persistent-queue/node_modules/ws/lib/WebSocket.js:219
    else throw new Error('not opened');
         ^

Error: not opened
    at WebSocket.send (/home/oleg/WebstormProjects/oresoftware/observable-persistent-queue/node_modules/ws/lib/WebSocket.js:219:16)
    at /home/oleg/WebstormProjects/oresoftware/observable-persistent-queue/node_modules/live-mutex/broker.js:177:24
    at Array.forEach (native)
    at Timeout.timeouts.(anonymous function).setTimeout [as _onTimeout] (/home/oleg/WebstormProjects/oresoftware/observable-persistent-queue/node_modules/live-mutex/broker.js:176:24)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
```

I am sure the error is due to my code - however I don't know why the error is happening. Under what circumstances would this error occur and how can I prevent it? thanks!

**Comment by lpinca** [comment]
This happens when you try to write to a closed or closing socket.

**Comment by ORESoftware** [comment]
ok, do you recommend monkey -patching the ws.send method?

something like this:

```js
const send = ws.send;

ws.send = function(){
  if(ws.readyState === WebSocket.OPEN){
     return send.apply(this,arguments);
  }
else{
  console.error('error - socket closed');
}
});
```

or maybe if I pass a callback, then error will get passed, instead of thrown?

```js
ws.send('foo', function(err){});
```

if this is true, then it would be nice if the error message said "Pass a callback to prevent this error from being thrown". Right?

**Comment by lpinca** [comment]
Yes, if you use a callback, the error is passed there instead of being thrown.

>  it would be nice if the error message said "Pass a callback to prevent this error from being thrown"

I don't know, I think "not opened" is clear enough.

**Comment by ORESoftware** [comment]
sure that's fine. One more question, what is the best pattern to use on the server side, to handle when the client closes the connection (maybe the client process crashes abruptly)? How do I clean up the connection from the server's perspective?

**Comment by lpinca** [comment]
Under normal circumstances, even when connection is closed abruptly, cleanup work fine.
There are however cases where you may need to call `close()` or `terminate()`, for example when there is no way to detect that the connection has been closed, no FIN packet, unplugged cable etc.

In these cases an heartbeat system based on ping/pong should help.

**Comment by lpinca** [comment]
Closing this, please comment if needed.

**Comment by ORESoftware** [comment]
thanks for the info!
