### ISSUE TITLE
Sometimes no events emitted when making a connection

### ISSUE THREAD

**Issue by liyuanqiu** [websockets/ws#959]
Code here:

```js
'use strict';

const WebSocket = require('ws');

function test() {

  // this address can not connect, test on error
  let ws = new WebSocket('ws://192.168.2.19:8888');

  console.log('make a websocket connection...');

  ws.on('open', () => {
    console.log('open');
  }); 

  ws.on('message', () => {
    console.log('message');
  }); 

  ws.on('close', () => {
    console.log('close');
    setTimeout(() => {
      test();
    }, 2000);
  });

  ws.on('error', () => {
    console.log('error');
  }); 

  ws.on('ping', () => {
    console.log('ping');
  }); 

  ws.on('pong', () => {
    console.log('pong');
  }); 

  ws.on('unexpected-response', () => {
    console.log('unexpected-response');
  }); 
}

test();
```

This small program connect to an offline ws address, when closed, do reconnecting.
Here is output:

```sh
$ node test/test-connect.js 
make a websocket connection...
error
close
make a websocket connection...
error
close
make a websocket connection...
error
close
make a websocket connection...
error
close
make a websocket connection...
error
close
make a websocket connection...
error
close
make a websocket connection...
error
close
make a websocket connection...
error
close
make a websocket connection...
error
close
make a websocket connection...
```

Look at the last line, no events emitted after connecting, then the program stall. I don't why.
Maybe a timeout is required in WebSocket constructor?

**Comment by lpinca** [comment]
Yes, a timeout option makes sense.
Anyway right now it shouldn't hang indefinitely. After some time, depending on the OS, the TCP connection should timeout and an `ETIMEDOUT` error emitted.

**Comment by liyuanqiu** [comment]
@lpinca Thank you very much for your reply.
My program output shows a random result, sometimes it fails immediately and emits error/close events, sometimes it hangs. I found it maybe a virtualbox nat port forward problem, not ws's problem.
Thank you anyway.

**Comment by damianobarbati** [comment]
@liyuanqiu @lpinca I'm experiencing the same: sometimes when connecting I see the websocket instantiated with readyState=0 but it never emits then a failure in connection, hangs undefinitely.

Any chance to set a timeout when using `new Websocket`? 

```
try {
    const websocket = this.websocket = new WebSocket(url);

    console.log('done!', websocket.readyState); // sometimes readyState = 0

    websocket.on('open', this.open.bind(this));
    websocket.on('message', this.message.bind(this));
    websocket.on('close', this.close.bind(this));
    websocket.on('error', this.error.bind(this));
}
catch (error) {
    console.error(error);
}
```

**Comment by lpinca** [comment]
See the [`handshakeTimeout`](https://github.com/websockets/ws/blob/master/doc/ws.md#new-websocketaddress-protocols-options) option.

**Comment by damianobarbati** [comment]
Thanks @lpinca, that made the trick 👍
