### ISSUE TITLE
Cannot manually send continuation/non-final frame

### ISSUE THREAD

**Issue by tdhsmith** [websockets/ws#972]
It seems that `WebSocket.send` doesn't respect `{fin: false}` when called directly. (It *does* work when using the stream methods.) 

Is this the intent? The docs refer to it and make it sound like I should be able to send a non-final frame:

> **[websocket.send(data, [options][, callback])](https://github.com/websockets/ws/blob/master/doc/ws.md#websocketsenddata-options-callback)**
> * `options` {Object} 
>   * `fin` {Boolean} Specifies whether data is the last fragment of a message or not. Defaults to `true`.

For reference I'm on v1.1.1. The `fin` setting is getting overrided in WebSocket.js at [line 231](https://github.com/websockets/ws/blob/1.1.1/lib/WebSocket.js#L231).

**Comment by tdhsmith** [comment]
I totally understand if you want to ensure protocol correctness and prevent people from sending incorrect `fin` flags, but then it would be nice if the docs indicated that they will be ignored. 😉

**Comment by tdhsmith** [comment]
Derp; I was looking at the 2.0.0 docs, wasn't I?

OK nevermind the docs and the functionality are totally in line. 😄

**Comment by lpinca** [comment]
Yes, you are right, the `fin` option is unconditionally set to `true` in 1.x.
This has been fixed in 2.x.
