### ISSUE TITLE
1006 ETIMEDOUT with cross domain server-side client/server

### ISSUE THREAD

**Issue by benzmuircroft** [websockets/ws#973]
I have two webistes both have (server-side only scripts not browser) client and server.

connecting siteB to wss://siteA.com:8004...

{ [Error: connect ETIMEDOUT '**.**.**.**:8004]
  code: 'ETIMEDOUT',
  errno: 'ETIMEDOUT',
  syscall: 'connect',
  address: '**.**.**.**',
  port: 8004 }
{ e: 1006, r: '' }

that is closed abnormally right..

siteA connecting to siteA works fine!
siteB connecting to siteB works fine!

**They both don't want to connect to each other even when I disable CSF LFD firewalls.**

server:

```
var wss=new ws.Server({
    	server:({perMessageDeflate:false},hardhttps.createServer({key:pem.key,cert:pem.cert,ca:[pem.ca],passphrase:pem.pass,requestCert:true})).listen(8004)
    ,	verifyClient:function(info,cb){
    		var ip=info.req.headers['x-forwarded-for']||info.req.connection.remoteAddress||info.req.socket.remoteAddress||info.req.connection.socket.remoteAddress;
                console.log(ip);
    		if(clients.indexOf(ip)!==-1&&wss.clients.length==0){
                cb(true);
                }
    		}});
    wss.on('error',function(e){console.dir(e);});
    wss.on('connection',function(c){
        console.log('connection');
```

Client:

```
var connection=new ws('wss://siteA.com:8004',{key:pem.key,cert:pem.cert,ca:[pem.ca]});
	    connection.on('unexpected-response',function(e){console.dir(e);});
            connection.on('error',function(e){console.dir(e);});
            connection.on('close',function(e,r){
				console.dir({e:e,r:r});
                });
            connection.on('open',function(){
                console.log('connected');
```

also tried starting the server like `new ws.Server({port:8004})` instead of having the http server to see if that was the issue.

can't see anything related in /var/log/error_log or access_log

**Comment by lpinca** [comment]
It seems that the connection can't be established. Try to see if you can establish a TCP connection with `nc(1)` or similar:

```
nc siteA.com 8004
```

**Comment by benzmuircroft** [comment]
Ncat: Could not resolve hostname "siteA.com:8004": Name or service not known. QUITTING. but the site is view-able in the browser!

**Comment by lpinca** [comment]
Check the command syntax, you must add a space between the hostname and the port.

**Comment by benzmuircroft** [comment]
nc siteA.com 8004
Ncat: Connection timed out.

**Comment by lpinca** [comment]
Looks like a network issue, maybe a firewall, I don't know but this confirms that it's not a ws issue.

**Comment by benzmuircroft** [comment]
netstat -an | grep "LISTEN "
 
tcp6       0      0 :::8004                 :::*                    LISTEN

**Comment by benzmuircroft** [comment]
Yeah, should I close or close later when i paste the solution?

**Comment by lpinca** [comment]
Whatever you think is better, but let's just not keep this open indefinitely :)

**Comment by benzmuircroft** [comment]
iptables maybe did not like that particular port ... i changed it to 8001 which is also open and it works, why? i don't flippin know lol
