### ISSUE TITLE
How do we enable ping/pong?

### ISSUE THREAD

**Issue by john-doherty** [websockets/ws#977]
Can someone please explain how the ping/pong works with this module?

**Comment by lpinca** [comment]
Hi,
ping/pong works as specified in the [RFC](https://tools.ietf.org/html/rfc6455#section-5.5.2).
An endpoint can send a ping frame via `ws.ping()` at any time after the connection is established.
Upon receipt of a ping frame, an endpoint sends a pong frame in response which triggers the `pong` event.

Using this one can implement a heartbeat system to check if the connection is still alive.

Maybe in future, after 2.0.0 is released we can add a built-in version of this heartbeat/keep-alive system basing it on the awesome work done by @FlorianBELLAZOUZ in #635.

**Comment by john-doherty** [comment]
Thanks @lpinca. Is the connecting client expected to respond to the ping or will the browser take care of that?

**Comment by lpinca** [comment]
The endpoint receiving the ping frame (including the browser) will automatically respond with a pong frame. This is per spec.

**Comment by john-doherty** [comment]
Thats great, thanks for taking the time to explain it!

**Comment by voxpopmxadmin** [comment]
Have a question....
Why am I receiving a "pong" event from the client twice? I applyed the example given in this main project page.

**Comment by YarikST** [comment]
@voxpopmxadmin 


hello, the server, depending on the implementation, sends a few ping while the connection is alive - and the web for each ping corresponds to pong - in order to keep the connection alive - as soon as it stops responding pong, the server learns that the clip is knocked out

**Comment by xgqfrms** [comment]
# js & websocket & ping / pong

> seems not work ?

```js

 // ping
ws.send(0x9);
// pong
// ws.send(0xA);

```

**Comment by xgqfrms** [comment]
> Have a question....
> Why am I receiving a "pong" event from the client twice? I applyed the example given in this main project page.
> 
> ```
> ws.on('pong', function heartbeat() {
> 	this.isAlive = true;
> 	console.log('Pong from store: ' + this.store_id);
> });
> ```

# what's wrong with this?

> Uncaught TypeError: ws.on is not a function

![image](https://user-images.githubusercontent.com/7291672/62118852-00b16900-b2f1-11e9-99d3-b265c5f2be24.png)

**Comment by vr-fox** [comment]
> > Have a question....
> > Why am I receiving a "pong" event from the client twice? I applyed the example given in this main project page.
> > ```
> > ws.on('pong', function heartbeat() {
> > 	this.isAlive = true;
> > 	console.log('Pong from store: ' + this.store_id);
> > });
> > ```
> 
> # what's wrong with this?
> > Uncaught TypeError: ws.on is not a function
> 
> ![image](https://user-images.githubusercontent.com/7291672/62118852-00b16900-b2f1-11e9-99d3-b265c5f2be24.png)

that error is beacuse you are using the pure JS WebSocket not the ws library from node

**Comment by manojgupta7755** [comment]
I am using NPM ws in my backend project. and i have added ping-pong logic if not getting response of ping in 45 seconds then i'm terminating the web socket connection.

Above logic is working when I'm minimizing the chrome tab I'm still getting the response of ping. But the same code When I'm minimizing the windows application i can see the logs not getting the response of ping. also i can see the webSocket connection active but not getting the response for ping

**Comment by sagwtg34rgsdf** [comment]
я ваших матерей ебал
