### ISSUE TITLE
How to connect to a Node.js WebSocket Server from a port forwarded server?

### ISSUE THREAD

**Issue by NineNineNineIonoSpheres** [websockets/ws#978]
Hello, 

My friend and I are looking for an answer to the question in the title. We have posted all the info here: http://stackoverflow.com/questions/41847918/how-to-connect-to-a-node-js-websocket-server-from-a-port-forwarded-server

Can someone give us a hand here?

Regards,
Iono

**Comment by lpinca** [comment]
If you get this error:

```
WebSocket connection to 'ws://exampleSite.com:5555/' failed: Error during WebSocket handshake: Unexpected response code: 302
```

it means that you are not hitting the WebSocket server. The upgrade requests made by `ws` should be forwarded to the WebSocket server.

**Comment by lpinca** [comment]
After re-reading, I noticed that you get a 302 status code. `ws` does not follow redirects so the problem could be this, see also #812.

**Comment by NineNineNineIonoSpheres** [comment]
Got it. Thank you.

**Comment by lpinca** [comment]
Closing for now. Please comment or reopen if needed.
