### ISSUE TITLE
two connections to same URL leads events to last made connection

### ISSUE THREAD

**Issue by steve2507** [websockets/ws#980]
When you setup two connections towards the same URL, the last made connection receives all message events (even those meant for the first connection).
<pre>
const WebSocket = require('ws');

//setup first ws connection
let ws1 = new WebSocket(`wss://...somewhere...}`);
ws1.addEventListener('message', (event) => {

	//this never fires
	console.log(`ws1: ${event.data}`);

});

//setup second connection
let ws2 = new WebSocket(`wss://...somewhere...}`);
ws2.addEventListener('message', (event) => {

	//this fires twice for each message event
	console.log(`ws2: ${event.data}`);

});</pre>

The above is the minimal use-case I could find, which may seem silly.
However, I'm actually using this across several workers in a cluster, where the same issue still persists. 

In case you're wondering why I'm not setting up the connection in the master 'thread'; the workers are 'individuals' that go about their own tasks which could be anything.

**Comment by lpinca** [comment]
I can't reproduce the issue. Tested on master with the following code:

```js
'use strict';

const cluster = require('cluster');
const WebSocket = require('..');

const port = 8181;

if (cluster.isMaster) {
  const wss = new WebSocket.Server({ port }, () => {
    cluster.fork();
    cluster.fork();
  });

  wss.on('connection', (ws) => ws.send('message'));
} else {
  const ws = new WebSocket(`ws://localhost:${port}`);

  ws.addEventListener('message', (event) => {
    console.log(`${cluster.worker.id} ${event.data}`);
  });
}
```

**Comment by steve2507** [comment]
After reviewing this a bit more, I noticed the issue was actually at the server side where a socket was overwritten.
