### ISSUE TITLE
Syntax Error with IE11

### ISSUE THREAD

**Issue by jameslai** [websockets/ws#993]
Please let me know if WebSockets no longer intends to support IE11, but this line:

https://github.com/websockets/ws/commit/44f9e89a501026b0459bad725216dc9500355d63#diff-ac4015dfd17173726807df0406ae1d2bR25

...has broken compatibility with IE11. You'll note that arrow functions are not supported in any version of IE http://caniuse.com/#feat=arrow-functions (if Edge is considered a "different browser").

**Comment by JoshuaWise** [comment]
This is a Node.js package. Front-end code is expected to use the global `WebSocket` object, or some wrapper library for it.

**Comment by jameslai** [comment]
Fair enough, thank you.
